### ISSUE TITLE
The yarn install command has been executed for at least 30 minutes or is still waiting like the log

### ISSUE THREAD

**Issue by serical** [iron-fish/ironfish#1008]
### What happened?

The yarn install command has been executed for at least 30 minutes or is still waiting like the log

### Version

v0.1.21

### Relevant log output

```shell
[root@vmxxxx ironfish]# yarn install
yarn install v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[-/6] ⠄ waiting...
[-/6] ⠄ waiting...
[3/6] ⠄ node-datachannel
[-/6] ⠄ waiting...
[-/6] ⠄ waiting...
```

**Comment by deekerno** [comment]
Does this issue still persist after the latest update?

**Comment by jrwashburn** [comment]
I also have this issue on M1 with the last two updates 0.1.128 and 0.1.129. Yarn install never completes.

**Comment by deekerno** [comment]
We recommend that users try to install using NPM (unless you intend to make contributions to the codebase). You can do by running `npm install -g ironfish`. Try using that and let us know if you still have an issue with running the node.

**Comment by lwisne** [comment]
Are you still having issues here?
