### ISSUE TITLE
CLI doesn't respond at all

### ISSUE THREAD

**Issue by alterkahn** [iron-fish/ironfish#101]
trying to `enableTelemetry` but CLI doesn't respond, also can't check node or miners state, or at least account balance.

![Снимок экрана 2021-04-25 в 13 46 51](https://user-images.githubusercontent.com/67752860/115990581-b72ca580-a5cc-11eb-8868-d4e53817936c.png)
![Снимок экрана 2021-04-25 в 13 39 23](https://user-images.githubusercontent.com/67752860/115990539-6d43bf80-a5cc-11eb-8c45-cbca38aaf4e1.png)
![Снимок экрана 2021-04-25 в 13 39 56](https://user-images.githubusercontent.com/67752860/115990540-6e74ec80-a5cc-11eb-8e75-66ff67f6b387.png)
![Снимок экрана 2021-04-25 в 13 44 32](https://user-images.githubusercontent.com/67752860/115990541-6e74ec80-a5cc-11eb-999e-bf2fb4189d9c.png)

**Comment by Ding65535** [comment]
The block is not sync or node is not running

**Comment by alterkahn** [comment]
![Снимок экрана 2021-04-25 в 17 43 16](https://user-images.githubusercontent.com/67752860/115997979-cbcd6580-a5ed-11eb-8513-4d80f76aee2a.png)

also doesn't work, or it wouldn't help?

**Comment by alterkahn** [comment]
![photo_2021-04-25_18-02-06](https://user-images.githubusercontent.com/67752860/116006247-009fe380-a613-11eb-910b-837e654ff7ab.jpg)

this was the only time when I could get a response to the `ironfish status` and I figured out that the blockchain doesn't syncing, could you tell me how to fix it? coz even node reinstalling didn't help.
