### ISSUE TITLE
All decryptable notes should be in the noteToNullifier map 

### ISSUE THREAD

**Issue by typhoonbb** [iron-fish/ironfish#102]
when I try to query account balance, it says **All decryptable notes should be in the noteToNullifier map** ,how to fix this

**Comment by dguenther** [comment]
Thanks for reporting, we're looking into this. As a temporary workaround, you should be able to run the following to reset the state of your local accounts database. 
```
ironfish accounts:rescan --reset
```
Keep in mind that block syncing is not working properly right now, so your account balance may fluctuate or transactions may not appear on the chain.

**Comment by alterkahn** [comment]
have the same issue today, and ` ironfish accounts:rescan --reset` killed all my balance

**Comment by mat-if** [comment]
Closing as I believe we've fixed this bug, but if not, a new issue can/should be used as this one has become very old
