### ISSUE TITLE
Node crash after mining block 'Assertion val->IsArrayBufferView() failed'

### ISSUE THREAD

**Issue by wd021** [iron-fish/ironfish#1042]
### What happened?

Node crashed after mining a block (118840). Error: Assertion `val->IsArrayBufferView() failed`.

<img width="1033" alt="Screen Shot 2022-02-18 at 11 56 46 AM" src="https://user-images.githubusercontent.com/2752586/154680415-c9a91584-6b49-44dd-bb6f-f4842c224b9c.png">
 

### Version

v0.1.23

**Comment by lwisne** [comment]
We think this is fixed now. Let us know if you don't agree!
