### ISSUE TITLE
miners:mined runs into 'Failed to unwrap shared reference of `NativeNoteEncrypted` type..'

### ISSUE THREAD

**Issue by wd021** [iron-fish/ironfish#1043]
### What happened?

My node crashed after successfully mining a block (issue reported https://github.com/iron-fish/ironfish/issues/1042). I decided to run `miners:mined` and ran into this error:

<img width="1300" alt="Screen Shot 2022-02-18 at 12 08 28 PM" src="https://user-images.githubusercontent.com/2752586/154681017-41f58cb6-feb4-450b-981f-702d9073f60e.png">
 

### Version

v0.1.23

**Comment by Kupuyc** [comment]
Hey there. Could you try to repeat bug on `test-fix-reference` branch?

**Comment by wd021** [comment]
@Kupuyc tested. branch fixes it 👍
