### ISSUE TITLE
Cannot connect to Node

### ISSUE THREAD

**Issue by DroidGirl** [iron-fish/ironfish#1047]
5:34:59 PM - Starting compilation in watch mode...

5:34:59 PM - Found 0 errors. Watching for file changes.
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run start -d default -p 9033
    Error: Parsing hosts.json Failed
    Unexpected token "\u0000" (0x00) in JSON at position 0 while parsing near
    "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u
    0000\u0000\u0000\u0000\u0000..." in hosts.json

    > 1 |
        | ^

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by mat-if** [comment]
Thanks for reporting this. We're going to try to fix this this week, in the mean time, you can delete `hosts.json` in your `~/.ironfish` folder as a temporary workaround

**Comment by deekerno** [comment]
Thanks for reporting! A fix for this went out in v0.1.25.

If you haven't already claimed testnet credit, please feel free to do so.

**Comment by DroidGirl** [comment]
How do I claim testnet credit?
________________________________
