### ISSUE TITLE
dont have telemetry in node status

### ISSUE THREAD

**Issue by bakarapara** [iron-fish/ironfish#1058]
### What happened?

telemetry in config is enabled but cant see its status in node status
graffiti: bakara
https://monosnap.com/file/dHeOz9MzD6pGYrL11N8Ql8usXduhCr
https://monosnap.com/file/KiWV2PTOLTR4W5TeiDcDEGoMLHOLWf

### Version

0.1.24

**Comment by mat-if** [comment]
Did you install from source? If so, can you run `yarn clean` and `yarn build` in the root folder (`ironfish`) and try again?

**Comment by bakarapara** [comment]
yes, from source. tried to rebuild but it doesn't solve the issue.

**Comment by deekerno** [comment]
Does this issue still persist after the latest update?

**Comment by bakarapara** [comment]
@deekerno no, it has been fixed. now everything is ok for me
