### ISSUE TITLE
Add "Getting-Started" or "New-Users-README and Links" channel to Discord 

### ISSUE THREAD

**Issue by crProductGuy** [iron-fish/ironfish#1062]
### Description

 I propose that we add self-contained introductory material in a new clearly-named Discord channel that's read-only.  We would put some "must-know" info there to reduce common questions in Discord channels, and prevent user heartache later. 

It should include a few key links, including a link to an enhanced FAQ page that the community can keep up to date.

Main problems to be solved:

- To serve new users better and reduce the support load.

- To prevent the continuing user pain of of "I didn't register", "I didn't set my grafitti", "I mined 20 blocks but didn't get credit", "someone claimed my blocks", etc.

Background:
We continue to have new users referred into the Discord from various places, who have never seen the Ironfish or Testnet websites, install guides, or anything.  They want help right away, and don't realize there are web instructions available if they only searched the Internet.  I think cross-language issues may be a part of this challenge for users.  It can be hard to search for things you don't know exist in a second language.

There is also the challenge that info needed to be successful is in different documents, so things get missed, like registering before installing, setting blockGraffiti before mining, etc.

My 2 proposals for the channel name are in the Issue Description above.  I think "New-Users-README" is more compelling.

Here is suggested content, inspired by and enhanced from this question and exchange in "General" channel on 22feb22

"Can I install Iron Fish node on Ubuntu"
https://discord.com/channels/771503434028941353/771503434028941356/945882072449441802

Here are some important links: Understand the Iron Fish Incentivized Testnet here and register:

https://testnet.ironfish.network/about.   This contains many other useful links.

Testnet rules: only one email address and blockGraffiti is allowed per person. These will be used for KYC when Testnet rewards are distributed.

When you register, be sure you make a distinct nickname or string, called a blockGraffiti, identify your account and track points in the Leaderboard.  It could be the same as your Discord handle, or something else you will remember.  The registration page will check it for uniqueness.

You need to **configure your registered blockGrafitti into your mining node**, otherwise **blocks you mined will not be credited to you.**

Installation page: https://ironfish.network/docs/onboarding/installation-iron-fish.   
 Options include Docker or Source method on Ubuntu, Windows, and Mac M1, and native via "homebrew" on Intel Mac

The easiest way to ensure grafitti on node matches what you registered in the Testnet is to use the 'testnet' command in the CLI on the node.    
The command format is
 `ironfish testnet userID`   (or `yarn start:once testnet userID` if you installed from source).

The UserID parameter is either the user number at the end of your testnet leaderboard URL, like 1080 in this example, or the whole URL like this:   https://testnet.ironfish.network/users/1080.

You can find your user number by searching for your blockGraffiti in the Leaderboad: https://testnet.ironfish.network/leaderboard

Sample `testnet` command:
`ironfish testnet 1080`     Of course put your own user number, not 1080.  

Check your blockGraffiti on your node by running the command `ironfish config:show`

Check that you registered successfully by visiting the Leaderboard and searching for your blockGraffiti

---

< text about use "ironfish" in native environment, "yarn start" from source, etc >

a few other must-knows

Then Link to an updated FAQ page (that can be maintained and updated by PRs from the community)

----------------------

***FAQs***:  (on website)

TOPIC: Testnet and rewards

Q: Is there a token pre-sale?
A: No.   Ignore scams that say there is one.  Nobody from the Iron Fish team will DM you.
  There are no "moderators" or "customer support" people who will contact you. All are scams!

Q: When with the Testnet Rewards be distributed?
A:   TBD

What are the tokenomics of the mainnet?

What rewards can I earn?

How fast will I get points credited after I make a contribution and request the points?

TOPIC: keeping up to date with the team and releases

How can I found out important announcements?
 - view Announcements channel
 - register in the choose-alerts channel

How can I follow the team's monthly updates?
 - see Monthly Chat update and Events

How can I know when to update my software?

 How to do updates?  (see Updates FAQ Topic below)

TOPIC: machine and mining questions:

Why is mining capped at 1000 reward points and 10 blocks/week?

What should I do after I hit the 10 block cap?

Can I use another graffiti with my miner after I reach 10 blocks?

My miner isn't getting blocks any more. What's going on?

My machine mined a block but I didn't get credit on the Leaderboard? Why not?
A: 1st and 2nd "races".   "submitted hash for a block" doesn't mean it was accepted as final.

Why does my Account say total blocks and Available to Spend?

What's the minimum machine that can run Iron Fish (maybe not be strong enough to win blocks, but for learning)

What kind of machine can win blocks now?

My machine has Hashate X?  How often should it win a block?

How can I learn more about performance of different machines?
 - read the Mining channel

How can I find out how long it might take for my machine to mine a block?
 - ironfishnet.com hashrate calculator

How can I mine on more than one machine and get the points on my blockGraffiti?

I have high-core-count servers like EPYC or ZEON. How can I optimize my hashrate?
 - batchsize

TOPIC: Installing from source:

What is Git?   What is Git Pull?    If I don't know Git, how can I install from source?

TOPIC: Updating to new versions of Iron Fish

How can I update if I installed from source?

How do I update if I installed using Docker?

How do I update if I'm running on an Intel Mac and installed with Brew?

TOPIC:  Faucet and Accounts

Why doesn't the faucet seem to be working?  Why doesn't it give me ORE **Iimmediately?**

How do I send IRON to someone?

How do I back up my account & wallet before an upgrade and restore it afterwards?

Do I need to save my wallet or account to get my Testnet points for mined blocks? 
 - no, but it's good practice

Can I put the same account and keys on different nodes so I see all my mined IRON in one account?
 - how would I do that?

---

TOPIC: Common Errors:

another node has the database open
 - kill, etc.
 - 

< various yarn failures >
  - get in the right directory for what you are trying to do
  - run npm update before doing yarn build, especially after taking source updates

Syncing slow or stuck

Crashes

**Comment by NullSoldier** [comment]
I think before we revamp our docs, what if we put this on a coda and also put this in a channel with a link to it as well as the only message? Then we can share that link around.

**Comment by AmberKiso** [comment]
I've also seen other discord channels have a captcha bot verify new joiners and drop them in a similar welcome/readme/faq channel, then have them add an emoji to signify they've read it.
That might reduce the common questions.

**Comment by NullSoldier** [comment]
We do use a captcha bot, but it doesn't have this feature. Do you know what bot they are using?

**Comment by NullSoldier** [comment]
I just set up our wiki and made it editable by our community, https://github.com/iron-fish/ironfish/wiki/Getting-Started

**Comment by AmberKiso** [comment]
I've seen CAPTCHA.BOT or Wick used on other projects.

Check out the Avalanche server. After verification, you get dropped in the
#start-here channel with a bunch of details on the project and rules. And
it requires you to click on an emoji to acknowledge and agree to them.

This sort of structure would be an ideal place to have all the onboarding
things discussed here.

**Comment by AmberKiso** [comment]
Some feedback on the wiki page:

- Not sure how we should align this with the webpage. Some sort of reference from web to wiki?
- Add all the socials (twitter + telegram + etc...) at the bottom of the page
- Checking the graffiti in section 2. Maybe show the explicit line in the config?
- Can we put a bounty out for translating this into the most common non-English languages?

I like this.

**Comment by crProductGuy** [comment]
Closing issue as the main intent is done and has proven to be useful to users and a time-saver for Devs & Community members.
  
Thanks for your good suggestions above, @AmberKiso !   
We can continue to work toward those, so I think there are future smaller specific tickets that can come out of this work.

I figure to do some more editing on the wiki over time.
