### ISSUE TITLE
"Error: Expect type String or Object or Number, but got Function" when starting node after update to 0.1.25

### ISSUE THREAD

**Issue by crProductGuy** [iron-fish/ironfish#1082]
### What happened?

New error, repeatable 3x on the same system after starting the node.

I had just updated from 0.1.24 to 0.1.25 via Git Pull, did a successful yarn install & build.
  (Win 11)

 - Before doing the yarn commands, I deleted node-modules directories under Source/

Started the node (Win 11) and am getting the error messages below in the Log box

Note: there may be something messed up with my database.  A different error:

Yesterday on the test-fix-branch of 0.1.23 on the same machine, I started getting this error when running `balance:show`:

`All decryptable notes should be in the noteToNullifier map`

Same behavior after I updated to 0.1.24 and now 0.1.25.

--
I exported my account.

Next I attempted to reset my ironfish and it failed with this:

You are about to destroy your node data at C:\Users\Marktest2\.ironfish
Are you sure? (Y)es / (N)o: y
Backing up 0 accounts to C:\Users\Marktest2\.ironfish\accounts.backup.json
Deleting databases... done
C:\Users\Marktest2\Source\ironfish\build\src\primitives\nullifier.js:20
        hasher.update(element);
               ^

Error: Expect type String or Object or Number, but got Function
    at NullifierHasher.merkleHash (C:\Users\Marktest2\Source\ironfish\build\src\primitives\nullifier.js:20:16)
    at C:\Users\Marktest2\Source\ironfish\build\src\merkletree\merkletree.js:137:44
    at LevelupDatabase.withTransaction (C:\Users\Marktest2\Source\ironfish\build\src\storage\database\database.js:39:34)
    at async MerkleTree.add (C:\Users\Marktest2\Source\ironfish\build\src\merkletree\merkletree.js:136:9)
    at async C:\Users\Marktest2\Source\ironfish\build\src\blockchain\blockchain.js:645:13
    at async LevelupDatabase.withTransaction (C:\Users\Marktest2\Source\ironfish\build\src\storage\database\database.js:39:28)
    at async C:\Users\Marktest2\Source\ironfish\build\src\blockchain\blockchain.js:797:17 {
  code: 'InvalidArg'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

C:\Users\Marktest2\Source\ironfish-cli>

---

### Debug output

```shell
yarn start:once debug
yarn run v1.22.17
$ yarn build && yarn start:js debug
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run debug
Iron Fish version            0.1.25 @ src
Iron Fish library            0.0.1 @ src
Operating system             Windows_NT x64
CPU model(s)                 AMD Ryzen 7 5700G with Radeon Graphics
CPU threads                  16
RAM total                    31.34 GiB
Node version                 v16.13.0
ironfish in PATH             true
Telemetry enabled            true
Accounts head hash           00000000000049bf0ceaa9aae8ad84975c9594da2106b499ff2b7ccf8a40bad7
Accounts head in chain       true
Accounts head sequence       129747
Done in 2.79s.
```

### Relevant log output

```shell
Version       0.1.25 @ src
Node Name     ProductGuy_Node2-Ryzen7-5700G
Graffiti      ProductGuy
Peer Identity cjcJwIQYA55wL+L0a31xJaP8ELcTdLck5wWYDfNdYng=
Peer Agent    ironfish-cli/0.1.25/src
Peer Port     9033
Bootstrap     test.bn1.ironfish.network

WebSocket server started at :::9033
Connected to the Iron Fish network
Starting sync from bRuWrJ2 (lino). work: +523890601893747, ours: 129747, theirs: 129765
Finding ancestor using linear search on last 3 blocks starting at 00000...0bad7 (129747) from peer bRuWrJ2 (lino) at 129765
Found peer bRuWrJ2 (lino) ancestor 00000...0bad7, syncing from 129747 -> 129765 (18) after 1 requests
Requesting 20 blocks starting at 00000...0bad7 (129747) from bRuWrJ2 (lino)
Stopping sync from bRuWrJ2 (lino) due to Error: Expect type String or Object or Number, but got Function
    at NullifierHasher.merkleHash (C:\Users\Marktest2\Source\ironfish\build\src\primitives\nullifier.js:20:16)
    at C:\Users\Marktest2\Source\ironfish\build\src\merkletree\merkletree.js:137:44
    at LevelupDatabase.withTransaction (C:\Users\Marktest2\Source\ironfish\build\src\storage\database\database.js:39:34)
    at async MerkleTree.add (C:\Users\Marktest2\Source\ironfish\build\src\merkletree\merkletree.js:136:9)
    at async C:\Users\Marktest2\Source\ironfish\build\src\blockchain\blockchain.js:645:13
    at async LevelupDatabase.withTransaction (C:\Users\Marktest2\Source\ironfish\build\src\storage\database\database.js:39:28)
    at async C:\Users\Marktest2\Source\ironfish\build\src\blockchain\blockchain.js:797:17
Peer bRuWrJ2 (lino) disconnected (DISCONNECTED) while syncing.
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

Error: Expect type String or Object or Number, but got Function
    at NullifierHasher.merkleHash (C:\Users\Marktest2\Source\ironfish\build\src\primitives\nullifier.js:20:16)
    at C:\Users\Marktest2\Source\ironfish\build\src\merkletree\merkletree.js:137:44
    at LevelupDatabase.withTransaction (C:\Users\Marktest2\Source\ironfish\build\src\storage\database\database.js:39:34)
    at async MerkleTree.add (C:\Users\Marktest2\Source\ironfish\build\src\merkletree\merkletree.js:136:9)
    at async C:\Users\Marktest2\Source\ironfish\build\src\blockchain\blockchain.js:645:13
    at async LevelupDatabase.withTransaction (C:\Users\Marktest2\Source\ironfish\build\src\storage\database\database.js:39:28)
    at async C:\Users\Marktest2\Source\ironfish\build\src\blockchain\blockchain.js:797:17 {
  code: 'InvalidArg'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by NullSoldier** [comment]
We changed the rust bindings, so you'll need to rebuild the rust bindings with a `yarn build` at the root.
