### ISSUE TITLE
using the 'ironfish status' command after node restart is not displayed correctly

### ISSUE THREAD

**Issue by eee-byte** [iron-fish/ironfish#1090]
### What happened?

**I rebooted the node due to an API connection error while it was running and used the 'ironfish stats' command to check the node status to discover a block mined previously that now wasn't displayed (1 mined - >; 0 mined)`**

My Graffiti is "202"

`Version              0.1.25 
Node                 STARTED
Memory               Heap: 61.99 MiB / 76.66 MiB (80.9%), RSS: 817.37 MiB (0.1%), Free: 998.56 GiB (0
.9%)
P2P Network          CONNECTED - In: 1.66 KB/s, Out: 6.90 KB/s, peers 41
Mining               STARTED - 3 miners, 0 mined

`

`
work: 1087653500263043007, head-work: 1281866760514889985, work-diff: 194213260251846978     [82/1498]
202-1 Error submitting telemetry to API: Request failed with status code 422                           
202-1 Added block seq: 135720, hash: 00000...be335, txs: 1, progress: 100.00%, time: 88.7ms            
202-1 Error submitting telemetry to API: Request failed with status code 422                           
202-1 202-1 Error submitting telemetry to API: Request failed with status code 422                     
202-1 Added block to fork seq: 130950, head-seq: 135724, hash: 00000...1114f, head-hash: 00000...bd659$
 work: 1127544437629791165, head-work: 1282201548329361013, work-diff: 154657110699569848              
202-1 Added block to fork seq: 127721, head-seq: 135724, hash: 00000...a5321, head-hash: 00000...bd659,
 work: 1031176901963447663, head-work: 1282201548329361013, work-diff: 251024646365913350              
202-1 Error submitting telemetry to API: Request failed with status code 422                           
202-1 Error submitting telemetry to API: Request failed with status code 422

 `
### Version

0.1.25

**Comment by alar0n** [comment]
After restart service - stats always reset to zero. I don't thinks what this a bug.

**Comment by eee-byte** [comment]
> After restart service - stats always reset to zero. I don't thinks what this a bug.

Thank you for your answer, I understand, but the design is actually a little unreasonable

**Comment by lwisne** [comment]
We believe this is now fixed. Let us know if you don't agree!
