### ISSUE TITLE
Installing threads

### ISSUE THREAD

**Issue by Mayovka** [iron-fish/ironfish#1099]
### What happened?

When installing the node, I did not specify the number of threads, and gave an error, what should be indicated in this field?
![Снимок экрана (85)](https://user-images.githubusercontent.com/95088734/157227881-d28652cd-bd2e-4b1e-84b4-8d92113e8aaa.png)

### Version

0.1.25

**Comment by Kupuyc** [comment]
It looks you used installation script of Nodes Guru project. Described issue is related to their script rather than Ironfish. I would recommend to contact them in their [telegram channel](https://nodes.guru/ironfish).

**Comment by deekerno** [comment]
As @Kupuyc stated, the screenshot shows the use of a script that is not officially supported. It is advised that you ask the script author for assistance.
