### ISSUE TITLE
Trying to run the CLI from source on Windows throws an exception

### ISSUE THREAD

**Issue by Camtendo** [iron-fish/ironfish#11]
After installing prerequisites on Windows and running/building from source, I encounter the following error:

![image](https://user-images.githubusercontent.com/4380972/113749080-d4a5d800-96ce-11eb-9d05-bc5075de325b.png)

**Comment by dguenther** [comment]
Thanks, this is really helpful. We need to go through and put together some verified build steps for Windows still -- I think you mentioned at some point that following steps here are necessary for getting the Rust build to work: https://github.com/alexcrichton/cc-rs#compile-time-requirements

**Comment by Camtendo** [comment]
Another note to make it this far, to fix the issues from `cargo install wasm-pack` I had to install Visual Studio 2019's C++ packages, as well as download `mingw-w64` using the guide from https://github.com/alexcrichton/cc-rs#compile-time-requirements and add the bin folder containing `cc` to the PATH.

**Comment by prestwich** [comment]
I am getting the same error on Ubunutu

**Comment by TAVAU** [comment]
I am getting the same error on Mac with cargo 1.48 and node v14.16.0

**Comment by faried** [comment]
Workaround: type `cd ironfish-cli` and run `yarn start:js start`.

**Comment by QuickMythril** [comment]
i was able to build but i get this when i try to run using "yarn start" (with or without ":js start"):
```
9:17:58 PM - Starting compilation in watch mode...
9:17:58 PM - Found 0 errors. Watching for file changes.
$ OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run
'OCLIF_TS_NODE' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
```

**Comment by NullSoldier** [comment]
These need `env` before to be compatible with windows. We'll take care of it, thanks.

**Comment by QuickMythril** [comment]
that took me one step ahead.  here's the next error:
```
$ env OCLIF_TS_NODE=0 env IRONFISH_DEBUG=1 node bin/run start
    TypeError: Cannot read property 'box' of undefined
Note: This command was run via npm module 'win-node-env'
error Command failed with exit code 1.
```

**Comment by Camtendo** [comment]
I tried a mix of the above, but `env` isn't available (I assume if it worked for others it was available via git bash or some other extra tool).
![image](https://user-images.githubusercontent.com/4380972/113876522-708e1d00-977d-11eb-95df-5ad5d88c8df9.png)


Then, I tried changing the package.json to `"start:js": "set OCLIF_TS_NODE=0 && set IRONFISH_DEBUG=1 && node bin/run",` but I don't think that's writing variables to the same spot that node is expecting.

![image](https://user-images.githubusercontent.com/4380972/113876790-b0ed9b00-977d-11eb-9ecf-ccc61d16b5b3.png)

**Comment by Camtendo** [comment]
I also tried git bash with the `env` change for kicks and get further, but I run into what appears to be segfault exceptions anyway

![image](https://user-images.githubusercontent.com/4380972/113877134-075ad980-977e-11eb-8704-53e04df91d38.png)

**Comment by dguenther** [comment]
Just an update here that we're focusing on fixing block syncing and network congestion issues first, since those issues are preventing people from connecting to the network anyway. Then we'll follow up and work on fixing crashes with the windows builds and packaging them up.

**Comment by dguenther** [comment]
As of #112, it should be possible to build and run from source on Windows without any errors or crashes by following the steps in the README. I haven't run a node for an extended period of time on Windows yet, but it doesn't immediately error now.

**Comment by dguenther** [comment]
I ran a node on Windows from source for several hours without any crashes, so I'm going to close this out for now in favor of more specific issues as they come up. We're also still interested in packaging up a release for Windows to avoid the need to run it from source.
