### ISSUE TITLE
Неначислюються бали

### ISSUE THREAD

**Issue by Balkoivan** [iron-fish/ironfish#1127]
### What happened?

Неначислаються бали за завдання :ретвіт у твітер , та пост в медіум

### Graffiti

Balko ivan

**Comment by delef** [comment]
This is an area of communication in English. 🤦‍♂️

**Comment by deekerno** [comment]
As @delef stated, please use English when creating an issue, if possible. A translation of the issue text seems to concern testnet points and how they are awarded. If you have any questions, please send an email to contact@ironfish.network.
