### ISSUE TITLE
Minor issue with messages in miner

### ISSUE THREAD

**Issue by QustomQure** [iron-fish/ironfish#1165]
### Description

Sometimes miner has just mess up work messages when getting work from official pool
![Screenshot (11)](https://user-images.githubusercontent.com/43998465/159120624-7d158a4d-397f-4ff1-a6fe-ddd01b97d50b.png)
![Screenshot (12)](https://user-images.githubusercontent.com/43998465/159120625-6893b0ac-0379-4d66-9ece-a8bcf868630e.png)

**Comment by lwisne** [comment]
This one is probably some async timing thing and wouldn't be worth the effort it would take to fix.
