### ISSUE TITLE
Npm fails install on wsl2 ubuntu

### ISSUE THREAD

**Issue by QustomQure** [iron-fish/ironfish#1236]
### What happened?

root@QSTM:~# nvm install node
Downloading and installing node v18.0.0...
Downloading https://nodejs.org/dist/v18.0.0/node-v18.0.0-linux-x64.tar.xz...
###################################################################################################################################################################################################################################### 100.0%
Computing checksum with sha256sum
Checksums matched!
Now using node v18.0.0 (npm v8.6.0)
Creating default alias: default -> node (-> v18.0.0)

After updating nodejs and trying to use npm -g install ironfish i get error:

/usr/bin/ironfish -> /usr/lib/node_modules/ironfish/bin/run

> bcrypto@5.5.0 install /usr/lib/node_modules/ironfish/node_modules/bcrypto
> node-gyp rebuild

gyp WARN EACCES current user ("nobody") does not have permission to access the dev dir "/root/.cache/node-gyp/14.19.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/ironfish/node_modules/bcrypto/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/ironfish/node_modules/bcrypto/.node-gyp'
gyp ERR! System Linux 5.10.102.1-microsoft-standard-WSL2
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/ironfish/node_modules/bcrypto
gyp ERR! node -v v14.19.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

Started install from root user even with sudo command, lol

![Screenshot (22)](https://user-images.githubusercontent.com/43998465/164772604-7b720e2d-9765-4360-b04b-5b92a81a5e0c.png)
[2022-04-22T16_14_56_358Z-debug.log](https://github.com/iron-fish/ironfish/files/8543192/2022-04-22T16_14_56_358Z-debug.log)

### Version

v.0.1.29

### Graffiti

Qualia

**Comment by QustomQure** [comment]
I was having 16+ node that time still it is for 0.1.29 version which is not relevant anymore :)
That was the point. Did you read message itself? )

**Comment by dguenther** [comment]
Versions >16 aren't supported: https://github.com/iron-fish/ironfish/blob/1abccc9460b918a6632f0d0f6d1afcd7ba7455ba/ironfish-cli/package.json#L23 

Could you post logs that show you using exactly Node.js 16? The issue details show you using either Node.JS v18.0.0 or v14.19.1:

> Now using node v18.0.0 (npm v8.6.0)

> gyp ERR! node -v v14.19.1
