### ISSUE TITLE
Account balance not showing after updating and integrating account

### ISSUE THREAD

**Issue by FlyingCacti** [iron-fish/ironfish#1278]
### Description

Just wondering if I missed anything on my update.

Here are the steps I took:

Checked balance
Exported account to file
Updated yarn
Updated from git
Reset ironfish
Imported account
Set account graffiti to previous one
Waited for Chain to sync
Balance showing as 0 Iron
Attempted to faucet with same email but comes back as exit 1 error

If you have any suggestions, please let me know.

Cheers, FC

**Comment by diesunddass** [comment]
The blockchain was reset. So clean slate.

**Comment by dguenther** [comment]
That update is as expected since we reset the chain to a clean state, sorry if we didn't communicate it well enough. The faucet has been taken offline as well for the new testnet phase.
