### ISSUE TITLE
nodes

### ISSUE THREAD

**Issue by SunnyBoy00l** [iron-fish/ironfish#1280]
### What happened?

WebSocket server started at :::9033
error parsing message <Buffer 06 6f 00 69 90 95 f9 54 0b 45 3a dd 8a fc 31 6e 27 e2 ab 96 45 b2 d9 83 43 93 17 b5 f5 32 a7 94 22 09 62 6f 6f 74 73 74 72 61 70 49 23 0e 00 17 69 72 ... 61 more bytes>
error parsing message <Buffer 06 6f 00 69 90 95 f9 54 0b 45 3a dd 8a fc 31 6e 27 e2 ab 96 45 b2 d9 83 43 93 17 b5 f5 32 a7 94 22 09 62 6f 6f 74 73 74 72 61 70 49 23 0e 00 17 69 72 ... 61 more bytes>
error parsing message <Buffer 06 6f 00 69 90 95 f9 54 0b 45 3a dd 8a fc 31 6e 27 e2 ab 96 45 b2 d9 83 43 93 17 b5 f5 32 a7 94 22 09 62 6f 6f 74 73 74 72 61 70 49 23 0e 00 17 69 72 ... 61 more bytes>
error parsing message <Buffer 06 6f 00 69 90 95 f9 54 0b 45 3a dd 8a fc 31 6e 27 e2 ab 96 45 b2 d9 83 43 93 17 b5 f5 32 a7 94 22 09 62 6f 6f 74 73 74 72 61 70 49 23 0e 00 17 69 72 ... 61 more bytes>
Miner connected while the node is syncing. Will not start mining until the node is synced
Miner connected while the node is syncing. Will not start mining until the node is synced
error parsing message <Buffer 06 6f 00 69 90 95 f9 54 0b 45 3a dd 8a fc 31 6e 27 e2 ab 96 45 b2 d9 83 43 93 17 b5 f5 32 a7 94 22 09 62 6f 6f 74 73 74 72 61 70 49 23 0e 00 17 69 72 ... 61 more bytes>
error parsing message <Buffer 06 6f 00 69 90 95 f9 54 0b 45 3a dd 8a fc 31 6e 27 e2 ab 96 45 b2 d9 83 43 93 17 b5 f5 32 a7 94 22 09 62 6f 6f 74 73 74 72 61 70 49 23 0e 00 17 69 72 ... 61 more bytes>
error parsing message <Buffer 06 6f 00 69 90 95 f9 54 0b 45 3a dd 8a fc 31 6e 27 e2 ab 96 45 b2 d9 83 43 93 17 b5 f5 32 a7 94 22 09 62 6f 6f 74 73 74 72 61 70 49 23 0e 00 17 69 72 ... 61 more bytes>
error parsing message <Buffer 06 6f 00 69 90 95 f9 54 0b 45 3a dd 8a fc 31 6e 27 e2 ab 96 45 b2 d9 83 43 93 17 b5 f5 32 a7 94 22 09 62 6f 6f 74 73 74 72 61 70 49 23 0e 00 17 69 72 ... 61 more 
…………

### Version

0.1.29

### Debug output

```shell
/root/.ironfish:/root/.ironfish registry.cn-qingdao.aliyuncs.com/sunnyboykeven/iron:v1 debug
Database in use, skipping output that requires database.
Stop the node and run the debug command again to show full output.

Iron Fish version       0.1.29 @ 26c2bb2
Iron Fish library       0.0.7 @ 26c2bb2
Operating system        Linux x64
CPU model(s)            Intel(R) Xeon(R) E-2288G CPU @ 3.70GHz
CPU threads             16
RAM total               62.46 GiB
Node version            v16.13.0
ironfish in PATH        true
Telemetry enabled       false

root@server:/usr/src/app# yarn start:once debug    
yarn run v1.22.15
$ yarn build && yarn start:js debug
$ tsc -b
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '../lib/tsc.js'
Require stack:
- /usr/src/app/node_modules/.bin/tsc
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/src/app/node_modules/.bin/tsc:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/src/app/node_modules/.bin/tsc' ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
root@server:/usr/src/app#
```

### Relevant log output

```shell
WebSocket server started at :::9033
error parsing message <Buffer 06 6f 00 69 90 95 f9 54 0b 45 3a dd 8a fc 31 6e 27 e2 ab 96 45 b2 d9 83 43 93 17 b5 f5 32 a7 94 22 09 62 6f 6f 74 73 74 72 61 70 49 23 0e 00 17 69 72 ... 61 more bytes>
error parsing message <Buffer 06 6f 00 69 90 95 f9 54 0b 45 3a dd 8a fc 31 6e 27 e2 ab 96 45 b2 d9 83 43 93 17 b5 f5 32 a7 94 22 09 62 6f 6f 74 73 74 72 61 70 49 23 0e 00 17 69 72 ... 61 more bytes>
error parsing message <Buffer 06 6f 00 69 90 95 f9 54 0b 45 3a dd 8a fc 31 6e 27 e2 ab 96 45 b2 d9 83 43 93 17 b5 f5 32 a7 94 22 09 62 6f 6f 74 73 74 72 61 70 49 23 0e 00 17 69 72 ... 61 more bytes>
error parsing message <Buffer 06 6f 00 69 90 95 f9 54 0b 45 3a dd 8a fc 31 6e 27 e2 ab 96 45 b2 d9 83 43 93 17 b5 f5 32 a7 94 22 09 62 6f 6f 74 73 74 72 61 70 49 23 0e 00 17 69 72 ... 61 more bytes>
Miner connected while the node is syncing. Will not start mining until the node is synced
Miner connected while the node is syncing. Will not start mining until the node is synced
error parsing message <Buffer 06 6f 00 69 90 95 f9 54 0b 45 3a dd 8a fc 31 6e 27 e2 ab 96 45 b2 d9 83 43 93 17 b5 f5 32 a7 94 22 09 62 6f 6f 74 73 74 72 61 70 49 23 0e 00 17 69 72 ... 61 more bytes>
error parsing message <Buffer 06 6f 00 69 90 95 f9 54 0b 45 3a dd 8a fc 31 6e 27 e2 ab 96 45 b2 d9 83 43 93 17 b5 f5 32 a7 94 22 09 62 6f 6f 74 73 74 72 61 70 49 23 0e 00 17 69 72 ... 61 more bytes>
error parsing message <Buffer 06 6f 00 69 90 95 f9 54 0b 45 3a dd 8a fc 31 6e 27 e2 ab 96 45 b2 d9 83 43 93 17 b5 f5 32 a7 94 22 09 62 6f 6f 74 73 74 72 61 70 49 23 0e 00 17 69 72 ... 61 more bytes>
error parsing message <Buffer 06 6f 00 69 90 95 f9 54 0b 45 3a dd 8a fc 31 6e 27 e2 ab 96 45 b2 d9 83 43 93 17 b5 f5 32 a7 94 22 09 62 6f 6f 74 73 74 72 61 70 49 23 0e 00 17 69 72 ... 61 more 
…………
```

### Graffiti

SunnyBoy

**Comment by deekerno** [comment]
Your node is outdated. The latest version is 0.1.31. Please update and let us know if that fixes the issue.

**Comment by SunnyBoy00l** [comment]
I also found that the version of my node is too low, it has been updated to the latest version, there is no problem at present, but there is a new log information, is this normal?  
………………
Received non-buffer message {"type":0,"destinationIdentity":null,"disconnectUntil":1652069767322,"reason":1,"sourceIdentity":"jSTas4AQCXnRjlEvzIUrAI5ZSXkLw/sqjhV4mgxudhc="}
Added block seq: 7720, hash: 00000...c98ab, txs: 1, progress: 100.00%, time: 20.8ms
Received non-buffer message {"type":0,"destinationIdentity":null,"disconnectUntil":1652069795410,"reason":1,"sourceIdentity":"+J5Nm7DVfaVAYWvBqcm1SSI71cUdyGIJ0yUcez5nh0Q="}
Received non-buffer message {"type":0,"destinationIdentity":null,"disconnectUntil":1652069930648,"reason":1,"sourceIdentity":"ceBBTMp2L8nf++Wd5bU1vGmVyVVXmY5CpHIR9iDHSz4="}
Received non-buffer message {"type":0,"destinationIdentity":null,"disconnectUntil":1652069936709,"reason":1,"sourceIdentity":"j9s6a5NhmZl2N/r0OB10v/vH/uFoFWWu4fRmkV2MQww="}
Received non-buffer message {"type":0,"destinationIdentity":null,"disconnectUntil":1652069948803,"reason":1,"sourceIdentity":"jSTas4AQCXnRjlEvzIUrAI5ZSXkLw/sqjhV4mgxudhc="}
Received non-buffer message {"type":0,"destinationIdentity":null,"disconnectUntil":1652070082093,"reason":1,"sourceIdentity":"kd/cWXwwj9FQWpCmZCQiiSSD2LsYggLI4GdqVb0ydy8="}
Received non-buffer message {"type":0,"destinationIdentity":null,"disconnectUntil":1652070090104,"reason":1,"sourceIdentity":"kd/cWXwwj9FQWpCmZCQiiSSD2LsYggLI4GdqVb0ydy8="}
Received non-buffer message {"type":0,"destinationIdentity":null,"disconnectUntil":1652070106167,"reason":1,"sourceIdentity":"kd/cWXwwj9FQWpCmZCQiiSSD2LsYggLI4GdqVb0ydy8="}
Received non-buffer message {"type":0,"destinationIdentity":null,"disconnectUntil":1652070138391,"reason":1,"sourceIdentity":"kd/cWXwwj9FQWpCmZCQiiSSD2LsYggLI4GdqVb0ydy8="}
Received non-buffer message {"type":0,"destinationIdentity":null,"disconnectUntil":1652070237540,"reason":1,"sourceIdentity":"j9s6a5NhmZl2N/r0OB10v/vH/uFoFWWu4fRmkV2MQww="}
Added block seq: 7740, hash: 00000...81396, txs: 2, progress: 100.00%, time: 73.8ms
Added block seq: 7760, hash: 00000...f3825, txs: 1, progress: 100.00%, time: 14.5ms
Added block seq: 7780, hash: 00000...0646f, txs: 1, progress: 100.00%, time: 12.4ms
Received non-buffer message {"type":0,"destinationIdentity":null,"disconnectUntil":1652072054099,"reason":1,"sourceIdentity":"2wtRUdDa6ZrFy74tCmrAZ1/k2u3f3Wkf8cRBDPq0m2Y="}
Received non-buffer message {"type":0,"destinationIdentity":null,"disconnectUntil":1652072056003,"reason":1,"sourceIdentity":"HBQFVjLOvDH0xipt24RAfNkNsktHC27NtpNPbiwRcSI="}
Received non-buffer message {"type":0,"destinationIdentity":null,"disconnectUntil":1652072547557,"reason":1,"sourceIdentity":"0G2hSq80Du8S3EvtLToiIBI7IrotTmJxH2lBbmIgLT8="}
Added block seq: 7800, hash: 00000...1de2c, txs: 1, progress: 100.00%, time: 9.2ms
Received non-buffer message {"type":0,"destinationIdentity":null,"disconnectUntil":1652072803302,"reason":1,"sourceIdentity":"FEb1lymp0yCmSnCRxhP/r4GEFl/H/4JllpbeVKiy3Vk="}
………………

**Comment by deekerno** [comment]
That is likely a result of your node receiving messages from peers with an older version than the newest one. We'll look into decreasing the log output.

**Comment by SunnyBoy00l** [comment]
Ok, thanks for telling me
