### ISSUE TITLE
The question about whether the current integral will be cleared

### ISSUE THREAD

**Issue by SunnyBoy00l** [iron-fish/ironfish#1290]
Hello, now you can normally get the points, but someone said that the current points will be cleared when the formal incentive starts. Could you please help confirm this information? In addition, if the points are cleared, will the iron tokens now obtained be cleared?

**Comment by dguenther** [comment]
The Testnet Phase 1 leaderboard is locked in place here: https://phase1.testnet.ironfish.network/leaderboard Points in the Phase 1 testnet have been earned already, and aren't affected by the points in Phase 2.

The Phase 2 testnet is now live, and can be viewed here: https://testnet.ironfish.network/leaderboard

So in summary, the two testnets are completely separate, and we will award rewards for both testnets once we're closer to mainnet launch. Hope this helps!
