### ISSUE TITLE
ironfish deposit help error

### ISSUE THREAD

**Issue by kenwayliu** [iron-fish/ironfish#1291]
### Description

Enter ironfish deposit help to prompt the following error：

```bash
ironfish deposit help
 ›   Error: Unexpected argument: help
 ›   See more help with --help
```

You can enter only --help

The standard should be help？

**Comment by dguenther** [comment]
Closing this since the error message indicates the correct command to run to get help. CLIs typically expect `--help` to get help for a particular command.
