### ISSUE TITLE
Building on Linux from source requires an additional dependency 'lerna'

### ISSUE THREAD

**Issue by taarushv** [iron-fish/ironfish#13]
Following these instructions https://ironfish.network/docs/onboarding/installation-iron-fish#from-source

Using Ubuntu 20.04, ran into the following when I tried `yarn build`: 

```[INFO]: Compiling to Wasm...
    Finished release [optimized] target(s) in 0.04s
[INFO]: License key is set in Cargo.toml but no LICENSE file(s) were found; Please add the LICENSE file(s) to your project directory
[INFO]: Installing wasm-bindgen...
[INFO]: Optimizing wasm binaries with `wasm-opt`...
[INFO]: Optional fields missing from Cargo.toml: 'description', 'repository'. These are not necessary, but recommended
[INFO]: :-) Done in 26.35s
[INFO]: :-) Your wasm pkg is ready to publish at /home/fireball/code/ironfish/ironfish-wasm/web.
Replacing name in web/package.json...
Done!
$ lerna run build
/bin/sh: 1: lerna: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Doing `yarn global add lerna` followed by `yarn` in the root folder fixed it, just wanted to bring this to your notice. Not sure if this is an issue just on my end.

**Comment by dguenther** [comment]
Does `lerna` show up in the root `node_modules/.bin` folder? It should be there after running `yarn install` from root, then any scripts in the `package.json` that reference `lerna` should be able to use it without having to globally install it.

**Comment by dguenther** [comment]
Going to close this as I think it might be an issue with the local environment -- The same steps run for me on CI and in a sandboxed Linux environment without having to install `lerna` globally.

**Comment by taarushv** [comment]
Yup, a clean install fixed it for me. Definitely just an issue on my end.
