### ISSUE TITLE
Iron fish is not giving me credit

### ISSUE THREAD

**Issue by ironfishwhale** [iron-fish/ironfish#1306]
### What happened?

So turns out, iron fish is mining, it's just not giving me the irons that I have earned. Would appreciate if any one could help
<img width="1105" alt="Screen Shot 2022-05-11 at 7 49 10 AM" src="https://user-images.githubusercontent.com/105171356/167760092-bd16012f-ccf4-4219-9ee0-9b44979a3e6f.png">
d

### Graffiti

ironfishup

**Comment by QustomQure** [comment]
It is mining, it is just less verbose by default now after updates. It is even shows MH/s. You can start miner with -v parameter and it will show all messages like it was in previous versions. Please close this issue.

**Comment by ironfishwhale** [comment]
But my graffiti is not getting updated

**Comment by ironfishwhale** [comment]
It still says my balance is zero, whereas people have been earning a lot of points through mining.

**Comment by QustomQure** [comment]
That is not true that they are earning points through mining. Did you read faq? https://testnet.ironfish.network/faq

**Comment by ironfishwhale** [comment]
It is true. I did read FAQ's. Through mining, I would earn irons which I can then send to the iron bank. Thing is I am not getting irons. I ran one account for a few hours. And now I switched to a second one. Nothing. Let me attach a screenshot
