### ISSUE TITLE
Search with legit graffiti in explorer search box returns no matches

### ISSUE THREAD

**Issue by johnsgeorgecet** [iron-fish/ironfish#1308]
### What happened?

In explorer.ironfish.network homepage, when i enter my graffiti "johnsgeorge" which is a valid one, it says no matches. not returning any searches.
![explorer search with graffiti error](https://user-images.githubusercontent.com/53503800/167783942-e94faa96-2cd0-470b-815d-ba0e2849302a.jpeg)
 

### Graffiti

johnsgeorge

**Comment by johnsgeorgecet** [comment]
Version is 0.1.32

**Comment by wd021** [comment]
the explorer only returns results if your graffiti mined a block.

you can check your user in the leaderboard -> https://testnet.ironfish.network/users/30508.
