### ISSUE TITLE
Missing points in dashboard

### ISSUE THREAD

**Issue by johnsgeorgecet** [iron-fish/ironfish#1310]
### What happened?

I am running two miners in mining pool. Totally 12 deposits are done until now, however the dashboard shows only 9 points in my name. 
The transaction hashes are the following:
Windows miner:
339d2dd63f147cbdd84b2220f1bd61fcc3759f5e94ccf3c3a39290de964ff65c
caa6cd372fbda18bbc40c09b36a717f034b0baff0aa3dc4a4eab1b4c637eb713
f0618e967d5154c29bba7fbce7937a1fe3d96bdddba068a92c44da679dabe5a7
c580cf1a28cfcd7f57fb65f754e339903556ee41fc1b3cd0433fb6a771293643
b32b63be202fc66fae43ce8ec5480a9b5b3d021b3ff22e349993a274a8ed0891

Mac miner:
7549700c11cef7bb3a79a7a78e3767a9ae10a460fd382a7b8a16ad75eb194e95
3c49c606e3ecc3d54fed51c18d4a119f3258823dfa0481dfe0a0e2632e45d8f5
e43af98a1ced38547163e6a77a3841024a25c8a14918bba6b5bc511f14553798
115249154c31f46eca00a3637ef82f5f1b8437e9315035b9d84f07cfd73fd9f1
fc673925577ffcb767af8940614cd83e1ffb9824468b582a70d238f9a30587ae
096b497ff512be54298d0f1b3ec1a2633203dc0373c5f03f7bd1b70b9d77512c
a1f33ff947869e7f5c381c4839d5ef236d2cb1bc13c9d30d40370bb298dbd96c

### Version

0.1.32

### Graffiti

johnsgeorge

**Comment by johnsgeorgecet** [comment]
Thanks, will this not be considered a bug in that case?

**Comment by lwisne** [comment]
We think this is fixed now. Let us know if you don't agree!
