### ISSUE TITLE
Wrong balance shows while current transaction in pending

### ISSUE THREAD

**Issue by lionff** [iron-fish/ironfish#1313]
### What happened?

Hello. I have made a transaction, and when I tried to make one more transaction I found that my balance shown as zero. But it is not true - the balance became show true only after confirmation of previous transaction.

![iron](https://user-images.githubusercontent.com/79597699/167842338-3c1e0a67-38e2-4226-8a40-f894ddcc90c9.png)

### Version

v0.1.32

### Graffiti

okayko

**Comment by lwisne** [comment]
We believe this is now fixed. Let us know if you don't agree!
