### ISSUE TITLE
synced but lost function

### ISSUE THREAD

**Issue by terrancewong** [iron-fish/ironfish#1314]
### What happened?

After node synced and properly mining, somehow not sending new work (block template stream) to miner,

 Also  Transaction / deposit says
```
Error: Request failed (400) validation: Your node must be connected to the Iron Fish network to send a transaction
waiting for balance.
```
at this moment the node is still synced to the chain, height is up to date.

account:balance works correctly.

### Version

0.1.32

### Debug output

```shell
Database in use, skipping output that requires database.
Stop the node and run the debug command again to show full output.

Iron Fish version       0.1.32 @ src
Iron Fish library       0.0.10 @ src
Operating system        Linux x64
CPU model(s)            Intel(R) Xeon(R) CPU E5-2651 v2 @ 1.80GHz
CPU threads             48
RAM total               23.47 GiB
Node version            v16.13.1
ironfish in PATH        false
Telemetry enabled       false
```

### Graffiti

bh9sqoCqIR3rDFstCCCw1g

**Comment by lwisne** [comment]
Do you still see this error?

**Comment by hughy** [comment]
We've made significant changes to the wallet since this issue was created. Please create a new issue if you've run into this again on a more recent version. Thanks!
