### ISSUE TITLE
confusing or confused `--expirationSequence`

### ISSUE THREAD

**Issue by terrancewong** [iron-fish/ironfish#1317]
### What happened?

in help
```
$ ironfish deposit --help                             
Deposit $IRON for testnet points

USAGE
...
  -e, --expirationSequence=<value>  max number of blocks for the transaction to wait before expiring
...
```

it says `--expirationSequence` is **relative**

do a `deposit` with `--expirationSequence=5` returns error
```
$ ironfish deposit --expirationSequence=5 --confirm -v
Connecting to 0.0.0.0:9023
Creating the transaction: [████████████████████████████████████████] 100% | ETA: 0s
An error occurred while sending the transaction.
 ›   Error: Request failed (400) validation: Invalid expiration sequence for transaction
```

do a `deposit` with `--expirationSequence=1060` also returns error
```
$ironfish deposit --expirationSequence=1060 --confirm -v 
Connecting to 0.0.0.0:9023
Expiration sequence should not be above 120 blocks
```

Looks like , some part of the code thinks  `--expirationSequence` is relative  but some other part thinks it's absolute Sequence.

### Version

0.1.32

### Graffiti

bh9sqoCqIR3rDFstCCCw1g

**Comment by dguenther** [comment]
This is useful, I agree with your assessment. Thanks for the bug report!
