### ISSUE TITLE
Transaction expiration during mining

### ISSUE THREAD

**Issue by 1613557499** [iron-fish/ironfish#1320]
### What happened?

A bug happened!
![image](https://user-images.githubusercontent.com/86406225/167862466-3af995f2-7e29-4b8f-b536-3b048d96064d.png)

**Comment by weneve2** [comment]
same error , three nodes with several miners crashed many times of this error
![image](https://user-images.githubusercontent.com/41933070/167991204-57c5c1c2-1ebf-4921-abe7-817d19a4ace7.png)

**Comment by lwisne** [comment]
We believe this is fixed now. Comment here if you're still experiencing this issue!
