### ISSUE TITLE
The transaction was sent but is not displayed in the explorer

### ISSUE THREAD

**Issue by okovale** [iron-fish/ironfish#1327]
### What happened?

I sent a transaction in the amount of 0.1 IRON , the transaction was sent without errors. I got the TXID: https://explorer.ironfish.network/transaction/a217c090f734605ab5d8b320f82a1ffe7af2c80ef6018cdab6c9442a45bcae16

But the explorer is empty. After the transaction, a lot of time passed, the coins were debited from the balance. For some reason, the transaction was not sent or an error occurred
![44e68f3e-aba1-4e3a-87b3-89cbb2e4896c](https://user-images.githubusercontent.com/103566189/167943371-c0fb8271-3383-49ce-aa2a-0ec7e3dd95e2.png)
.

### Version

v0.1.32

### Debug output

```shell
Iron Fish version       0.1.32 @ src
Iron Fish library       0.0.10 @ src
Operating system        Linux x64
CPU model(s)            AMD Ryzen 9 5950X 16-Core Processor
CPU threads             32
RAM total               125.77 GiB
Node version            v16.15.0
ironfish in PATH        true
Telemetry enabled       true
```

### Graffiti

okovalev

**Comment by lwisne** [comment]
I see this one now on the leaderboard, closing
<img width="1604" alt="Screen Shot 2022-07-28 at 2 53 26 PM" src="https://user-images.githubusercontent.com/27844/181615733-5600c1e7-93ed-4815-a0c1-895d5188f09a.png">
