### ISSUE TITLE
Missing points in leaderboard for transactions made

### ISSUE THREAD

**Issue by okovale** [iron-fish/ironfish#1328]
### What happened?

I made several transactions that didn't count towards the leaderboard. There were several transactions, for example I will give two.
1) https://explorer.ironfish.network/transaction/f991a526c7b70441a9cf3d95cb43a3ccab9e736ba4f0d8e01ce67a358fc90581
Sent the transaction, it was confirmed. They didn't give me points on the leaderboard for it. The screenshot of the sent transaction is below.

![Screenshot_97](https://user-images.githubusercontent.com/103566189/167947798-7711b88c-984a-4410-aa4a-cb59a129568f.png)

2) https://explorer.ironfish.network/transaction/5fb5ca94328f9c1a9efe9b9fe4554f15922ddf5370e0a6c179aaa3ded162046c
I also sent this transaction, I also did not receive points for it.

![Screenshot_99](https://user-images.githubusercontent.com/103566189/167947846-0dc26871-4dee-44b9-a6e1-da76877f3f10.png)

These are just 2 transactions for an example. There were more such unrecorded transactions, about 7.

### Version

v0.1.32

### Debug output

```shell
Iron Fish version       0.1.32 @ src
Iron Fish library       0.0.10 @ src
Operating system        Linux x64
CPU model(s)            AMD Ryzen 9 5950X 16-Core Processor
CPU threads             32
RAM total               125.77 GiB
Node version            v16.15.0
ironfish in PATH        true
Telemetry enabled       true
```

### Graffiti

okovalev

**Comment by lwisne** [comment]
Looks like these eventually got picked up - like the first one is here (ends with 0581):

![Screen Shot 2022-08-01 at 6 35 07 PM](https://user-images.githubusercontent.com/27844/182256969-8971f59b-f34b-4cee-ac37-69ccf232e854.png)
