### ISSUE TITLE
throw new Error(verification.reason);

### ISSUE THREAD

**Issue by qsobad** [iron-fish/ironfish#1333]
Ironfish Version : 0.1.32 @ src
OS : ubuntu 20.04 LTS

Problem:
The node stopped and several deposits could not confirm, which returns 400

`Added block seq: 1600, hash: 00000...ab3a0, txs: 77, progress: 80.88%, time: 980.1ms
Requesting 20 blocks starting at 00000...cfa61 (1601) from itZzgpt
Received non-buffer message {"type":0,"destinationIdentity":null,"disconnectUntil":1652327273605,"reason":1,"sourceIdentity":"fdrusyjBp+lKAEGqwKdoofu/tT3wRpS601UY2mG8eQ0="}
Received non-buffer message {"type":0,"destinationIdentity":null,"disconnectUntil":1652327291323,"reason":1,"sourceIdentity":"cGJ9Zq6j0o5Qh4OAqVP+vB9ZtOHtlTPBL9din8qTVRQ="}
Received non-buffer message {"type":0,"destinationIdentity":null,"disconnectUntil":1652327304480,"reason":1,"sourceIdentity":"3NE+yb6N9Kek6XHpp2Ms/Ncsd4T+Sh+4EMNQinx1TU4="}
Added block seq: 1620, hash: 00000...47128, txs: 8, progress: 81.57%, time: 90.3ms
Received non-buffer message {"type":0,"destinationIdentity":null,"disconnectUntil":1652327316316,"reason":1,"sourceIdentity":"19OhsbtZw38D8Hw07zqhR0T93ZO/y0RlGGg0IWABdgs="}
Requesting 20 blocks starting at 00000...4e824 (1621) from itZzgpt
Received non-buffer message {"type":0,"destinationIdentity":null,"disconnectUntil":1652327338023,"reason":1,"sourceIdentity":"46Sse4TDx/WY55aPXEOV21jykpW+Hcu10nq3v/DF2FI="}
Added block seq: 1640, hash: 00000...15c8a, txs: 132, progress: 82.70%, time: 1527.7ms
Requesting 20 blocks starting at 00000...32ca2 (1641) from itZzgpt
Received non-buffer message {"type":0,"destinationIdentity":null,"disconnectUntil":1652327396050,"reason":1,"sourceIdentity":"ZsLS+vlhtN7uTbEv9CZyLJgikCybIvFv0OeeoduXPG4="}
Received non-buffer message {"type":0,"destinationIdentity":null,"disconnectUntil":1652327396525,"reason":1,"sourceIdentity":"Z4hywA2Sdop9rc3B6nZAPFbfHxKdZJFt9BdROj5j9m8="}
Added block seq: 1660, hash: 00000...6fe4d, txs: 6, progress: 83.42%, time: 83.0ms
Requesting 20 blocks starting at 00000...2909a (1661) from itZzgpt
Received non-buffer message {"type":0,"destinationIdentity":null,"disconnectUntil":1652327437072,"reason":1,"sourceIdentity":"FPJgLoUquVHly3woRxx86CZ6ynMYecb3l1fG/0QrkVo="}
Added block seq: 1680, hash: 00000...27ad0, txs: 139, progress: 84.45%, time: 1354.1ms
Received non-buffer message {"type":0,"destinationIdentity":null,"disconnectUntil":1652327447799,"reason":1,"sourceIdentity":"rGww3lJnWG84USJU2ADjTkQkJA2sRcNnGI5urrJgYmE="}
Requesting 20 blocks starting at 00000...86807 (1681) from itZzgpt
Received non-buffer message {"type":0,"destinationIdentity":null,"disconnectUntil":1652327461397,"reason":1,"sourceIdentity":"BqHiriuD4+pIuwLI8E48h8nW0qUBaYfrsstyD3KcBVw="}
Added block seq: 1700, hash: 00000...bcefa, txs: 10, progress: 85.18%, time: 118.5ms
Requesting 20 blocks starting at 00000...6d3f3 (1701) from itZzgpt
Received non-buffer message {"type":0,"destinationIdentity":null,"disconnectUntil":1652327500044,"reason":1,"sourceIdentity":"sUyhf5aqDxOwUeph5i4P0awARqf2AAGvq986zjY/X2s="}
Added block seq: 1720, hash: 00000...c2811, txs: 90, progress: 86.31%, time: 972.6ms
Requesting 20 blocks starting at 00000...5391f (1721) from itZzgpt
Received non-buffer message {"type":0,"destinationIdentity":null,"disconnectUntil":1652327538439,"reason":1,"sourceIdentity":"4RiuOJgOwkgG37ofx3/mu3DVYmbYpZDP+KSNyU85SE8="}
Peer itZzgpt sent orphan 00000...f666f (2047), syncing orphan chain.
Added block seq: 1740, hash: 00000...3fc3b, txs: 33, progress: 87.21%, time: 1673.6ms
Requesting 20 blocks starting at 00000...082a6 (1741) from itZzgpt
Received non-buffer message {"type":0,"destinationIdentity":null,"disconnectUntil":1652327598036,"reason":1,"sourceIdentity":"MiH3sWzTOzBwt1QmWRw4BqP49JeI/hPHVTHzHsWhchY="}
Peer n45DpKn (bloxx) sent orphan 00000...1ace6 (2048), syncing orphan chain.
Received non-buffer message {"type":0,"destinationIdentity":null,"disconnectUntil":1652327619892,"reason":1,"sourceIdentity":"8fwbOf3x712B7gMW8vv3DmJyA+cUwg7ZsAzC9dW8eQM="}
Peer EhlO0NF (luckynode.tech.asd123sada) sent orphan 00000...4f62d (2048), syncing orphan chain.
Peer EhlO0NF (luckynode.tech.asd123sada) sent orphan 00000...31254 (2049), syncing orphan chain.
Added block seq: 1760, hash: 00000...cb2a9, txs: 108, progress: 88.01%, time: 3183.7ms
Requesting 20 blocks starting at 00000...f3bad (1761) from itZzgpt
Peer NTwa1UF (Eli) sent orphan 00000...3c936 (2050), syncing orphan chain.
Received non-buffer message {"type":0,"destinationIdentity":null,"disconnectUntil":1652327684086,"reason":1,"sourceIdentity":"+A+TEiwMKeH0SwcbpT55s4mzBpp1jMD2sa1LOTugP18="}
/usr/src/app/node_modules/@ironfish/sdk/build/src/blockchain/blockchain.js:605
                    throw new Error(verification.reason);
                          ^

Error: Transaction expired
    at /usr/src/app/node_modules/@ironfish/sdk/build/src/blockchain/blockchain.js:605:27
    at async LevelupDatabase.withTransaction (/usr/src/app/node_modules/@ironfish/sdk/build/src/storage/database/database.js:39:28)
    at async Blockchain.newBlock (/usr/src/app/node_modules/@ironfish/sdk/build/src/blockchain/blockchain.js:555:16)
    at async MiningManager.createNewBlockTemplate (/usr/src/app/node_modules/@ironfish/sdk/build/src/mining/manager.js:93:26)
    at async streamNewBlockTemplate (/usr/src/app/node_modules/@ironfish/sdk/build/src/rpc/routes/mining/blockTemplateStream.js:84:33)`

**Comment by qsobad** [comment]
I guess it occurs when several deposit happens at the same time, but not very sure about it.

**Comment by lwisne** [comment]
We believe this is fixed now. Comment here if you're still experiencing this issue!
