### ISSUE TITLE
error: could not compile `backtrace`

### ISSUE THREAD

**Issue by ddim77** [iron-fish/ironfish#1335]
### What happened?

During installation from scratch, on a clean server (Ubuntu 20.04 64 bit) an error appeared in the logs. Despite this, the installation continued further, and even the node and miner were able to start. But whether they will continue to work correctly is unknown. The following script was used for installation https://api.nodes.guru/ironfish.sh

![12-05-2022 13-58-40](https://user-images.githubusercontent.com/28446928/168014839-adc4a771-52fa-4ffb-a7f9-db1b26362ced.jpg)

### Version

0.1.32 @ src

### Graffiti

Ironf_node

**Comment by dguenther** [comment]
Ah, it looks like that error occurred while installing wasm-pack, which isn't necessary for current Iron Fish installations. That script is not an officially-supported installation method, and it looks like it may be a bit out-of-date. The 3 lines:

```
cargo install --force wasm-pack
```

can safely be deleted.
