### ISSUE TITLE
[issue name] Wrong response after correct run of command

### ISSUE THREAD

**Issue by devzorg** [iron-fish/ironfish#1343]
### What happened?

If you type wrong command it could help u with correct option but after that will show Error but selected option on "Did you mean blabla" will run success. So just need to remove Error message when something choosen on Did you mean

### Version

0.1.32

### Relevant log output

```shell
root@n4f7925:~# ironfish miner:mined
 ›   Warning: miner:mined is not a ironfish command.
Did you mean miners:mined? [y/n]: y
Scanning for mined blocks...
Scanning for mined blocks from 1 -> 2692
Scanning blocks: [========================================] 2692/2692 100% | ETA: 0 | SEQ 2692
 ›   Error: command miner:mined not found
```

### Graffiti

rad1k

**Comment by wd021** [comment]
the bug isn't relevant to Ironfish code. We'll have to deal with it using `@oclif/core`.
