### ISSUE TITLE
Amount available Balance to spend is not immediatly recovered once a transaction has been launched

### ISSUE THREAD

**Issue by Danzou62** [iron-fish/ironfish#1344]
### What happened?

Steps to reproduce : 

1 - enter a command to get your account balance. see the response below :
_The balance is: $IRON 0.60041228 ($ORE 60,041,228)
Amount available to spend: $IRON 0.60041228 ($ORE 60,041,228)
Done in 7.21s._
2 - Launch a transaction  _ironfish deposit_ . See response below : 
_You are about to send $IRON 0.10000000 ($ORE 10,000,000) plus a transaction fee of $IRON 0.00000001 ($ORE 1) to the Iron Fish deposit account.
Your remaining balance after this transaction will be $IRON 0.50041227 ($ORE 50,041,227).
The memo will contain the graffiti "Danzou62"._
3 - Check your account balance right after . Response below :
_The balance is: $IRON 0.50041227 ($ORE 50,041,227)
Amount available to spend: $IRON 0.00000000 ($ORE 0)
Done in 7.36s._

Observed : 

As on the first command to check account balance it shows me my amount available to spend $IRON 0.60041228 and i send a transaction of $IRON 0.1 after that. I was expecting on my account balance an Amount available to spend equal to $IRON 0.50041228
I think there is something to clafify on the diffrent message or something ot fix if this is a real bug

### Version

v0.1.32

### Debug output

```shell
Iron Fish version       0.1.32 @ src
Iron Fish library       0.0.10 @ src
Operating system        Linux x64
CPU model(s)            AMD Ryzen 9 5900X 12-Core Processor
CPU threads             24
RAM total               7.72 GiB
Node version            v16.15.0
ironfish in PATH        true
Telemetry enabled       true
Done in 2.35s.
```

### Graffiti

Danzou62

**Comment by wd021** [comment]
maybe messaging needs to be clarified, but this isn't a bug. you need to wait for the tx nullifier to be done before your amount to spend is non-zero.
