### ISSUE TITLE
Getting a yarn error message while trying to deposit some $IRON

### ISSUE THREAD

**Issue by Danzou62** [iron-fish/ironfish#1345]
### What happened?

**Steps to reproduce :**
1 - Make a transaction using ironfish deposit without having any sufficient amount available to spend
2 - check the message

Observed : 

I am getting a yarn  error message while the command is okay

_Insufficient balance: 0. Required: 0.10000001
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command._

**Expected :** 

We should just have an error message to indicate us that the amoubt is not sufficient 

### Version

v0.1.32

### Debug output

```shell
Iron Fish version       0.1.32 @ src
Iron Fish library       0.0.10 @ src
Operating system        Linux x64
CPU model(s)            AMD Ryzen 9 5900X 12-Core Processor
CPU threads             24
RAM total               7.72 GiB
Node version            v16.15.0
ironfish in PATH        true
Telemetry enabled       true
Done in 2.27s.
```

### Graffiti

Danzou62

**Comment by lwisne** [comment]
As far as I know this is WAI. Closing.
