### ISSUE TITLE
Transaction time is taking into account the confirmation delay

### ISSUE THREAD

**Issue by Danzou62** [iron-fish/ironfish#1346]
### What happened?

Steps to reproduce :
1 - Make a transaction
You are about to send $IRON 0.10000000 ($ORE 10,000,000) plus a transaction fee of $IRON 0.00000001 ($ORE 1) to the Iron Fish deposit account.
Your remaining balance after this transaction will be $IRON 0.34454449 ($ORE 34,454,449).
2 - Wait 60sec before confirming the transaction
_Do you confirm (Y/N)?: y_
3 - Check transaction delay
_Depositing $IRON 0.10000000 ($ORE 10,000,000) from Danzou62
Transaction Hash: f7df0c7ffda03148132d0e2bc267b25011902c4d14b08c9af9fbb5b8a5becc6c
Transaction fee: $IRON 0.00000001 ($ORE 1)

Find the transaction on https://explorer.ironfish.network/transaction/f7df0c7ffda03148132d0e2bc267b25011902c4d14b08c9af9fbb5b8a5becc6c (it can take a few minutes before the transaction appears in the Explorer)
Done in 49.27s._

Observed : 

The transaction took 15 sec to be validated but it show 49.27 because time to confirm has been taken into account

Expected :

Transaction delay should start when the user has confirmed his transaction

### Version

v0.1.32

### Debug output

```shell
Iron Fish version       0.1.32 @ src
Iron Fish library       0.0.10 @ src
Operating system        Linux x64
CPU model(s)            AMD Ryzen 9 5900X 12-Core Processor
CPU threads             24
RAM total               7.72 GiB
Node version            v16.15.0
ironfish in PATH        true
Telemetry enabled       true
Done in 2.19s.
```

### Graffiti

Danzou62

**Comment by wd021** [comment]
`Done in` is the time of your function execution, not the transaction. this is standard everywhere.
