### ISSUE TITLE
Upgrade to 0.1.33 goes through but status still shows 0.1.32

### ISSUE THREAD

**Issue by johnsgeorgecet** [iron-fish/ironfish#1358]
### What happened?

On Mac OS. I upgraded to 0.1.33 using the command:
brew update && brew uninstall ironfish && brew install ironfish

upgrade looked successful.
however when i ran the status command it still showed 0.1.32. When starting the node also it still showed 0.1.32

### Version

0.1.33

### Graffiti

johnsgeorge

**Comment by johnsgeorgecet** [comment]
![0 1 33 upgrade](https://user-images.githubusercontent.com/53503800/168197288-f6633265-b655-4fad-a9f9-98ba17b0dde4.jpg)

**Comment by wd021** [comment]
looking at your screenshot, you're downloading `ironfish-cli-1abccc9.tar.gz`. that's the hash for v0.1.32.

https://github.com/iron-fish/ironfish/releases/tag/v0.1.32
