### ISSUE TITLE
Npm install on Windows choking powershell, not able to stop node using Control+C

### ISSUE THREAD

**Issue by johnsgeorgecet** [iron-fish/ironfish#1359]
### What happened?

Running a node on Windows in powershell is choking it up after some time of running. 
I was not able to stop the node using Ctrl+C. Used the direct npm install on windows. 

I then had to close the powershell terminal and open a new one. 

### Version

0.1.32

### Graffiti

johnsgeorge

**Comment by lwisne** [comment]
need more info to do much here. Feels like it may be related to out of memory errors such as https://github.com/iron-fish/ironfish/issues/1367
