### ISSUE TITLE
Npm install on windows showing misleading npm message about vulnerability

### ISSUE THREAD

**Issue by johnsgeorgecet** [iron-fish/ironfish#1360]
### What happened?

Upgrading to 0.1.33, on windows. npm install. 

installation was done, and it showed:
1 critical severity vulnerability

To address all issues, run:
  npm audit fix

however When i ran npm audit fix it didnt find any vulnerability:

1 critical severity vulnerability

To address all issues, run:
  npm audit fix

the messages are misleading. 

### Version
0.1.33
_No response_

### Graffiti
johnsgeorge
_No response_

**Comment by johnsgeorgecet** [comment]
![windows npm upgrade message discrepancy 0 1 33](https://user-images.githubusercontent.com/53503800/168200775-71399f21-27b9-4c3e-b765-a20548523838.PNG)

**Comment by lwisne** [comment]
This is an npm issue, not something we can fix directly
