### ISSUE TITLE
Node restart and restart again [issue name]

### ISSUE THREAD

**Issue by alar0n** [iron-fish/ironfish#1361]
Hello. After update to 0.1.33 and use command:
ironfish accounts:rescan --reset
Node worked normal about 30 minutes, but after time she is started restart and crashed with this erro:
![image](https://user-images.githubusercontent.com/31000576/168206823-bd3b4cf0-d070-4112-aa0f-c7b7d707ef94.png)

Now node can not start with same erorr

**Comment by lwisne** [comment]
We believe this is resolved now. Let us know if you're still having issues!
