### ISSUE TITLE
Can not use ironfish deposit[issue name]

### ISSUE THREAD

**Issue by alar0n** [iron-fish/ironfish#1364]
### What happened?

Hello. My node is work:
![image](https://user-images.githubusercontent.com/31000576/168240623-834d414a-a832-4a01-8287-cb95032bc987.png)

I have IRON on balance:
![image](https://user-images.githubusercontent.com/31000576/168240829-c20023c2-244c-4bef-b82c-f61b72402cb2.png)
But when i try **ironfish deposit**, i take this error:
![image](https://user-images.githubusercontent.com/31000576/168240983-b5d1587f-1dbf-4e4f-9399-056ceebc74ed.png)

After **ironfish accounts:rescan --reset** and restart of node problem still exists

### Version

ex 0.1.33

### Debug output

```shell
yarn run v1.22.18
$ yarn build && yarn start:js debug
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run debug
Database in use, skipping output that requires database.
Stop the node and run the debug command again to show full output.

Iron Fish version       0.1.33 @ src
Iron Fish library       0.0.11 @ src
Operating system        Linux x64
CPU model(s)            Intel(R) Xeon(R) Gold 6248R CPU @ 3.00GHz
CPU threads             42
RAM total               31.39 GiB
Node version            v16.15.0
ironfish in PATH        true
Telemetry enabled       true
Done in 1.77s.
```

### Graffiti

alar0n

**Comment by lwisne** [comment]
We believe this is resolved now. Let us know if you're still having issues!
