### ISSUE TITLE
Impossible to send transaction while there is sufficient funds

### ISSUE THREAD

**Issue by Danzou62** [iron-fish/ironfish#1368]
### What happened?

Steps to reproduce : 
1 - Send a transaction and confirm

You are about to send $IRON 0.10000000 ($ORE 10,000,000) plus a transaction fee of $IRON 0.00000001 ($ORE 1) to the Iron Fish deposit account.
Your remaining balance after this transaction will be $IRON 1.23980650 ($ORE 123,980,650).
The memo will contain the graffiti "Danzou62".

* This action is NOT reversible *

Do you confirm (Y/N)?: y
Creating the transaction: [████████████████████████████████████████] 100% | ETA: 0s
An error occurred while sending the transaction.
 ›   Error: Request failed (400) error: Insufficient funds
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Observed : 

There are sufficient fund to send the transaction but i received an error while trying to
This can be due to the fact BLockchain in not syncronized 
In my opinion we should prevent this with another error message "You can send transaction while blocks are not synchronized"
Or transaction should be paused with option to cancel it

### Version

v0.1.33

### Debug output

```shell
Iron Fish version            0.1.33 @ src
Iron Fish library            0.0.11 @ src
Operating system             Linux x64
CPU model(s)                 AMD Ryzen 9 5900X 12-Core Processor
CPU threads                  24
RAM total                    7.72 GiB
Node version                 v16.15.0
ironfish in PATH             true
Telemetry enabled            true
Accounts head hash           0000000000082ebde08ccf7f4a33221e7ade87754b44e25279ca335ba4932ae7
Accounts head in chain       true
Accounts head sequence       3782
Done in 2.33s.
```

### Graffiti

Danzou62

**Comment by lwisne** [comment]
We can definitely improve the messaging here when the blockchain is not synced.

**Comment by hughy** [comment]
Update error messages related to sending transactions in #2101
