### ISSUE TITLE
My cpu used 98% but hashrate show 0 H/s

### ISSUE THREAD

**Issue by forfangnft** [iron-fish/ironfish#1369]
### What happened?

My cpu used 98% but hashrate show 0 H/s
![ironfish](https://user-images.githubusercontent.com/105493703/168271122-b0731d7b-4a94-4f7f-a41b-598c628438d5.png)

### Version

My cpu used 98% but hashrate show 0 H/s

### Debug output

```shell
yarn run v1.22.18
$ yarn build && yarn start:js miners:start
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run miners:start
Starting to mine with graffiti: forfangnft connecting to node
Connecting to node...
Successfully connected to node
Listening to node for new blocks
Hashrate... ⣷ 0 H/s (0)
```

### Graffiti

forfangnft

**Comment by xbeastx** [comment]
can you show
```ironfish debug -v```

**Comment by xbeastx** [comment]
In my case there was 2 processor server.
```ironfish config:set minerBatchSize 100000```
Magically helps
