### ISSUE TITLE
Amount of coins in account is larger than number of caught blocks 

### ISSUE THREAD

**Issue by GoUpToDream** [iron-fish/ironfish#1371]
### What happened?

A bug happened!
Three blocks are displayed on the explorer. For each block, 20 IRON is received, i.e 60 IRON has been received in total.
After 216 transactions, valued at 0.1 IRON each, there should be 38 IRON left in the account.
However, the balance request displays 61 IRON remaining in the account.
It appears that one of the caught blocks is not being displayed by the explorer.

![image](https://user-images.githubusercontent.com/79373364/168294874-646ea9c1-027c-4fd5-aec1-d26dbc5bf6ca.png)

![image](https://user-images.githubusercontent.com/79373364/168298790-b2f04145-980f-424e-b037-d960a8f8e0dc.png)

### Graffiti

SunBird

**Comment by wd021** [comment]
think this is a balance display issue and not a extra block missing from block explorer issue..

**Comment by hughy** [comment]
The Wallet 2.0 refactor released in [v0.1.48](https://github.com/iron-fish/ironfish/releases/tag/v0.1.48) included significant changes to the way that account balances are stored and calculated.

Please open a new issue if you run into this again!
