### ISSUE TITLE
Node does not sync when mining is active

### ISSUE THREAD

**Issue by sunsweet733** [iron-fish/ironfish#1375]
### What happened?

My node does not sync when the miner is running, when the miner is turned off, the synchronization is restored.
Number of miner threads: 38 out of 40

Video of problem
https://dropmefiles.com/vPl2Q

### Version

v 0.13.3

### Debug output

```shell
Iron Fish version       0.1.33 @ src
Iron Fish library       0.0.11 @ src
Operating system        Linux x64
CPU model(s)            Common KVM processor
CPU threads             40
RAM total               11.41 GiB
Node version            v16.15.0
ironfish in PATH        true
Telemetry enabled       true
Done in 4.94s.
```

### Graffiti

ssw73

**Comment by wd021** [comment]
your video link doesnt work. can you try reuploading?

**Comment by lwisne** [comment]
Need a bit more info here - sorry about the delay on viewing the video. Can you re-upload? Otherwise, will have to close.

**Comment by hughy** [comment]
Closing as stale
