### ISSUE TITLE
Misleading status message for ironfish faucet command when email is invalid

### ISSUE THREAD

**Issue by johnsgeorgecet** [iron-fish/ironfish#1376]
### What happened?

when an invalid text is entered for the email, the status message says collecting your funds first and then says invalid email. need to say a consistent message. 

<<<
PS C:\Users\johnsge> ironfish faucet

::::::::::          :::::::::::::::::
::::::::::::       :::::::::::::::::::
:::::::::::::     :::::::::::::::::::::
::::::::::::::   ::::::::::::::::::::::::
 ::::::::::::: ::::::::::        :::::::::
   :::::::::::::::::::::          ::::::::::
   :::::::::::::::::::::          :::::::::
 ::::::::::::: ::::::::::        :::::::::
::::::::::::::   ::::::::::::::::::::::::
:::::::::::::     :::::::::::::::::::::
::::::::::::       :::::::::::::::::::
::::::::::           ::::::::::::::::

Enter your email to stay updated with Iron Fish: asdfdsa
Collecting your funds... You entered an invalid email.
>>>>

### Version

0.1.33

### Graffiti

johnsgeorge

**Comment by lwisne** [comment]
faucet is no longer valid
