### ISSUE TITLE
usage of help option in commands is not consistent

### ISSUE THREAD

**Issue by johnsgeorgecet** [iron-fish/ironfish#1377]
### What happened?

The help option used in the topics is like "help", however the same usage in first level commands result in an error and ask the user to use "--help". Not a major issue, but a good enhancement i believe.

PS C:\Users\johnsge> ironfish deposit help
 »   Error: Unexpected argument: help
 »   See more help with --help
PS C:\Users\johnsge> ironfish accounts help
Create and delete accounts

USAGE
  $ ironfish accounts:COMMAND

COMMANDS
  accounts:balance    Display the account balance
  accounts:create     Create a new account for sending and receiving coins
  accounts:export     Export an account
  accounts:import     Import an account
  accounts:list       List all the accounts on the node
  accounts:pay        Send coins to another account
  accounts:publickey  Display or regenerate the account public key
  accounts:remove     Permanently remove an account
  accounts:rescan     Rescan the blockchain for transaction
  accounts:use        Change the default account used by all commands
  accounts:which      Show the account currently used.

PS C:\Users\johnsge>

### Version

0.1.33

### Graffiti

johnsgeorge

**Comment by johnsgeorgecet** [comment]
one flipside is when I inadvertently used "help" option, in ironfish accounts:create option, it created an account with the name help :-)

PS C:\Users\johnsge> ironfish accounts:create help
Creating account help
Account help created with public address 868adb0de2684358c86df5f85ca051e94ce46dbd1eef7fc5650f7ddccc7f146e675e0cd2bb45e8364fdda2
Run "ironfish accounts:use help" to set the account as default

**Comment by wd021** [comment]
not sure this is a bug..

help is a valid keyword. `help` in the context of `ironfish accounts help` has nothing to do with `help`. if you don't type in a valid `accounts:[COMMAND]`, it will show you the options, help or no help.
