### ISSUE TITLE
Cannot connect to node when rpc.tcp is used even if node is started

### ISSUE THREAD

**Issue by johnsgeorgecet** [iron-fish/ironfish#1378]
### What happened?

The node is connected and running fine. however when i use rpc.tcp option it says cannot connect to node, start your node first. 

PS C:\Users\johnsge> ironfish status

Version              0.1.33 @ 48d9cef
Node                 STARTED
Memory               Heap: 114.87 MiB / 153.25 MiB (75.0%), RSS: 448.82 MiB (2.8%), Free: 5.01 GiB (68.2%)
P2P Network          CONNECTED - In: 596.39 KB/s, Out: 32.81 KB/s, peers 48
Mining               STARTED - 0 miners, 0 mined
Mem Pool             95 tx
Syncer               IDLE - avg time to add block 4979.28 ms
Blockchain           SYNCED @ HEAD 000000000002e216acac45aa0eec3f9fababe8cb39d646d2be446d109f8b49b2 (4224)
Telemetry            STARTED - 1343 <- 4 pending
Workers              STARTED - 0 -> 3 / 6 - -0.1 jobs Δ, 1.08 jobs/s
PS C:\Users\johnsge>
PS C:\Users\johnsge>
PS C:\Users\johnsge>
PS C:\Users\johnsge> ironfish accounts:list --rpc.tcp
Cannot connect to your node, start your node first.
PS C:\Users\johnsge>

### Version

0.1.33

### Graffiti

johnsgeorge

**Comment by lwisne** [comment]
By design, the accounts commands do not work with the `rpc.tcp` flag.
