### ISSUE TITLE
Usage of "@" in account name - inconsistent result and error

### ISSUE THREAD

**Issue by johnsgeorgecet** [iron-fish/ironfish#1379]
### What happened?

When @ is used in creating new account name, in one scenario it says unrecognzied token, but in another scenario it is accepted and account is created

PS C:\Users\johnsge> ironfish accounts:create @
At line:1 char:26
+ ironfish accounts:create @
+                          ~
Unrecognized token in source text.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnrecognizedToken

PS C:\Users\johnsge> ironfish accounts:create @test
Enter the name of the account: @test
Creating account @test
Account @test created with public address ec3714c92eef191de9b90676709199045b066f2b66960077a7a8b33cf42de90298981f0aef69464bbdc424
Run "ironfish accounts:use @test" to set the account as default
PS C:\Users\johnsge> ironfish accounts:create @1223233
Enter the name of the account: @
Creating account @
Account @ created with public address 12e33c3163f364d9d84f430fb949f2dd30a6c6c0ecdc7e2521bbf058d1fcc3b604b26ef30b37c9cdb48f1a
Run "ironfish accounts:use @" to set the account as default
PS C:\Users\johnsge> ironfish accounts:create @#$%$%#$%
At line:1 char:26
+ ironfish accounts:create @#$%$%#$%
+                          ~
Unrecognized token in source text.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnrecognizedToken

PS C:\Users\johnsge>

### Version

0.1.33

### Graffiti

johnsgeorge

**Comment by sunsweet733** [comment]
I haven't this error
http://joxi.ru/p27BK7ptZvpy6m

What is your operating system?

**Comment by sunsweet733** [comment]
What client are you using to connect to the server?

**Comment by johnsgeorgecet** [comment]
THe pasted output is from Windows, npm install. command ran from powershell.
Let me try in mac OS as well

**Comment by johnsgeorgecet** [comment]
Do you mean '@' is a legit input for an address? 

Let me include a few cases how an input with @ behave

case 1 - @ followed by alphanumeric eg. @abc 
-------
PS C:\Users\johnsge> ironfish accounts:create @abc
Enter the name of the account: @abc
Creating account @abc
Account @abc created with public address 257ebe548f3e89efcc016b8b5e3f2093eebd3cb2db27524683a1c4c0be3b1120b609d8f23e947521177d33
Run "ironfish accounts:use @abc" to set the account as default

If @ is a legit character, the command should not ask to enter the name again, because it is accepting the same input after that also. 

Case 2 - when input is only @ or @ following by special characters
-----------------------------------
Here it throws error

PS C:\Users\johnsge> ironfish accounts:create @
At line:1 char:26
+ ironfish accounts:create @
+                          ~
Unrecognized token in source text.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnrecognizedToken


PS C:\Users\johnsge> ironfish accounts:create @#$*
At line:1 char:26
+ ironfish accounts:create @#$*
+                          ~
Unrecognized token in source text.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnrecognizedToken


case 3 - when @ followed by some special characters like (, % etc
---------------------------------------------------------------------------
it is giving one more input prompt, like a shell, but printing error again


PS C:\Users\johnsge> ironfish accounts:create @)(%%_
>> aabc
At line:1 char:26
+ ironfish accounts:create @)(%%_
+                          ~
Unrecognized token in source text.
At line:1 char:27
+ ironfish accounts:create @)(%%_
+                           ~
Unexpected token ')' in expression or statement.
At line:1 char:32
+ ironfish accounts:create @)(%%_
+                                ~
Missing closing ')' in expression.
At line:2 char:1
+ aabc
+ ~~~~
Unexpected token 'aabc' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnrecognizedToken

PS C:\Users\johnsge> ironfish accounts:create @)(#
>> aabbc
>> test
At line:1 char:26
+ ironfish accounts:create @)(#
+                          ~
Unrecognized token in source text.
At line:1 char:27
+ ironfish accounts:create @)(#
+                           ~
Unexpected token ')' in expression or statement.
At line:2 char:6
+ aabbc
+      ~
Missing closing ')' in expression.
At line:3 char:1
+ test
+ ~~~~
Unexpected token 'test' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnrecognizedToken



case 4 - @ followed by character ^
---------------------------------------
This time, it throws a good message saying the input is not the expected ones, but still error in the message, the unexpected arguments it says is some r, o, n etc. 

PS C:\Users\johnsge> ironfish accounts:create @^
 »   Error: Unexpected arguments: r, o, n, f, i, s, h
 »   See more help with --help


----------------------------------------

Instead the command must behave consistently, throw an error message if any illegit input is detected, and show the user what characters are allowed and what is not.

**Comment by johnsgeorgecet** [comment]
oops, github is modifying some of my output printed

**Comment by johnsgeorgecet** [comment]
attaching screeshots of the above as well
![1](https://user-images.githubusercontent.com/53503800/168406198-101d1a9d-c725-4f6f-9140-c8b7d05f6f0c.PNG)
![2](https://user-images.githubusercontent.com/53503800/168406201-9ca2f4ff-e485-45ce-a3fa-77a125104b22.PNG)
![3](https://user-images.githubusercontent.com/53503800/168406203-e890ac35-9709-43b1-852f-3754fa186516.PNG)

**Comment by johnsgeorgecet** [comment]
Mac OS shows different behaviour:

only @ character is not throwing error:

johnsgeorge@Johnss-MacBook-Pro ~ % ironfish accounts:create @  
Connecting to /Users/johnsgeorge/.ironfish/ironfish.ipc
Creating account @
Account @ created with public address 9d58dfbe03c5019f5dd23ff92e1ebfe3fdb4a2c640a1c3bd5762bff1718731d763f4d210c746796d031a26
Run "ironfish accounts:use @" to set the account as default

**Comment by johnsgeorgecet** [comment]
Mac OS:

input as @#$* - is not throwing error but it creates account without *
-------------------------
johnsgeorge@Johnss-MacBook-Pro ~ % ironfish accounts:create @#$*
Connecting to /Users/johnsgeorge/.ironfish/ironfish.ipc
Creating account @#
Account @# created with public address ba7810b2f7e0fe016ed4f50cfe99b69c8999160b3c13aad2462307d6c5a4f6ba2aa371f81c616a0983f142
Run "ironfish accounts:use @#" to set the account as default
johnsgeorge@Johnss-MacBook-Pro ~ % 


When input has ( in it - it correctly throws error. but the message can be more informative - include what is accepted and what is not. 
----------------
johnsgeorge@Johnss-MacBook-Pro ~ % ironfish accounts:create @)(%%_
zsh: parse error near `)'
johnsgeorge@Johnss-MacBook-Pro ~ % 





However when input is '@^' - it creates the account, not throwing error unlike that in windows
---------------------------

johnsgeorge@Johnss-MacBook-Pro ~ % ironfish accounts:create @^    
Connecting to /Users/johnsgeorge/.ironfish/ironfish.ipc
Creating account @^
Account @^ created with public address 7bd99468489e49a11cdb60a22245746a0e039f5ca9c4e1c0d8dd1efcfb0fbb24e726caa83f593a35f10406
Run "ironfish accounts:use @^" to set the account as default

**Comment by sunsweet733** [comment]
Мне удалось поймать такую же ошибку. Пожалуй правильным действием было бы обернуть имя в двойные кавычки, например "@)(%%_", или сделать это сразу в коде

**Comment by johnsgeorgecet** [comment]
I also noticed that the account created with the name @ or @ followed by any characters, cannot be deleted. 

PS C:\Users\johnsge> ironfish accounts:remove @
At line:1 char:26
+ ironfish accounts:remove @
+                          ~
Unrecognized token in source text.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnrecognizedToken

PS C:\Users\johnsge> ironfish accounts:remove @@
At line:1 char:26
+ ironfish accounts:remove @@
+                          ~
Unrecognized token in source text.
At line:1 char:27
+ ironfish accounts:remove @@
+                           ~
Unrecognized token in source text.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnrecognizedToken

PS C:\Users\johnsge> ironfish accounts:remove @abc
 »   Error: Missing 1 required arg:
 »   name  name of the account
 »   See more help with --help
PS C:\Users\johnsge> ironfish accounts:remove @test
 »   Error: Missing 1 required arg:
 »   name  name of the account
 »   See more help with --help

**Comment by lwisne** [comment]
The bug here is we should properly validate command line input. Will validate and set as a good first issue.

**Comment by danield9tqh** [comment]
Hey @johnsgeorgecet I think that these errors are either related to the way the shell parses characters or the way node parses them (see [related](https://github.com/ng-select/ng-select/issues/1114)). Both of these we do not have much control over in this codebase (without some major investigation and possibly tool changes). If you enclose the account name in quotations then I believe creation will work every time. Or just running `ironfish accounts:create` and following the prompt should work for most cases. 

I'm going to close this issue because we do have a (pretty easy) workaround for creating account names and because fixing this would require considerable effort and may not even be possible in some cases. Let me know if this is not sufficient for you. Thanks for reporting!!
