### ISSUE TITLE
Wrong status message for invalid input in command ironfish blocks:show

### ISSUE THREAD

**Issue by johnsgeorgecet** [iron-fish/ironfish#1380]
### What happened?

When i enter an input starting with @ for this command, it says the parameter itself is missing, instead it must show that the input is not valid or similar. 

PS C:\Users\johnsge> ironfish blocks:show @ssdfsd
 »   Error: Missing 1 required arg:
 »   search  the hash or sequence of the block to look at
 »   See more help with --help

### Version

0.1.33

### Graffiti

johnsgeorge

**Comment by sunsweet733** [comment]
Similar Issue
https://github.com/iron-fish/ironfish/issues/1379
