### ISSUE TITLE
special characters in chain:export command input forcing the command to export from block 1

### ISSUE THREAD

**Issue by johnsgeorgecet** [iron-fish/ironfish#1381]
### What happened?

If the input contains any special character like @, #, $ etc, the export is performed from block 1 itself, without any indication to the user. When the chain becomes large, this might unnecessary cause issues.

PS C:\Users\johnsge> ironfish chain:export 4285
Exporting chain from 4285 -> 4290 to C:\Users\johnsge\.ironfish\data.json
Exporting blocks: [========================================] 4290/6 100% | ETA: 0s
PS C:\Users\johnsge> ironfish chain:export @###
At line:1 char:23
+ ironfish chain:export @###
+                       ~
Unrecognized token in source text.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnrecognizedToken

PS C:\Users\johnsge> ironfish chain:export @44
Exporting chain from 1 -> 4290 to C:\Users\johnsge\.ironfish\data.json
Exporting blocks: [========================================] 4290/4290 100% | ETA: 0s
Export complete
PS C:\Users\johnsge> ironfish chain:export 4285
Exporting blocks: [========================================] 4292/8 100% | ETA: 0s
Export complete
PS C:\Users\johnsge> ironfish chain:export @
+ ironfish chain:export @
+                       ~
Unrecognized token in source text.
    + FullyQualifiedErrorId : UnrecognizedToken

PS C:\Users\johnsge> ironfish chain:export @!
At line:1 char:23
+ ironfish chain:export @!
+                       ~
Unrecognized token in source text.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnrecognizedToken

PS C:\Users\johnsge> ironfish chain:export !
Exporting chain from 1 -> 4293 to C:\Users\johnsge\.ironfish\data.json
Exporting blocks: [========================================] 4293/4293 100% | ETA: 0s
Export complete
PS C:\Users\johnsge> ironfish chain:export %^&%&$%^$^$%
At line:1 char:25
+ ironfish chain:export %^&%&$%^$^$%
+                         ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation
marks ("&") to pass it as part of a string.
At line:1 char:27
+ ironfish chain:export %^&%&$%^$^$%
+                           ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation
marks ("&") to pass it as part of a string.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : AmpersandNotAllowed

PS C:\Users\johnsge> ironfish chain:export #$%#$%#$%#
Exporting chain from 1 -> 4294 to C:\Users\johnsge\.ironfish\data.json
Exporting blocks: [========================================] 4294/4294 100% | ETA: 0s
Export complete
PS C:\Users\johnsge> ironfish chain:export 4285@@@
Exporting chain from 1 -> 4295 to C:\Users\johnsge\.ironfish\data.json
Exporting blocks: [========================================] 4295/4295 100% | ETA: 0s
Export complete

### Version

0.1.33

### Graffiti

johnsgeorge

**Comment by CalebKoranda** [comment]
I believe it exports from block 1 when you provide invalid input because invalid input is treated essentially as no input and thus the default behavior is to export from block 1. What do you believe the desired behavior should be in cases of invalid input?

**Comment by johnsgeorgecet** [comment]
Got it. However i believe it will be good to throw a message to the user, before running the command, something like
it is an invalid input, the command will run with default input from block 1, do you want to continue?

hence the user is not surprised.

**Comment by sunsweet733** [comment]
Similar Issue
https://github.com/iron-fish/ironfish/issues/1379

**Comment by lwisne** [comment]
The bug here is we should properly validate command line input. Will validate and set s a good first issue.

**Comment by neuronull** [comment]
#1379 was closed manually per:

https://github.com/iron-fish/ironfish/issues/1379#issuecomment-1213518550

, does the same logic apply to this issue or is this one still verified? @lwisne  @danield9tqh

**Comment by aminazeb** [comment]
I am interested in working on this issue.

**Comment by aminazeb** [comment]
> #1379 was closed manually per:
> 
> [#1379 (comment)](https://github.com/iron-fish/ironfish/issues/1379#issuecomment-1213518550)
> 
> , does the same logic apply to this issue or is this one still verified? @lwisne @danield9tqh

@lwisne @danield9tqh Is this still an open issue?
