### ISSUE TITLE
miners pool started without -v switch printing new work messages

### ISSUE THREAD

**Issue by johnsgeorgecet** [iron-fish/ironfish#1382]
### What happened?

Node installed on mac os. 
Started the miners in ironfish official pool without using -v switch. however it is printing the new work lines.
In the same terminal, i ran the miner in pool with the same command, it was not printing the new work lines. but when i had to stop the miner, used Ctrl+C, and then later stared with the same command (by using up arrow), it started printing the new work lines. 

### Version

0.1.33

### Graffiti

johnsgeorge

**Comment by johnsgeorgecet** [comment]
![miner without -v showing new work lines](https://user-images.githubusercontent.com/53503800/168334583-f90ba42c-4f65-4ce2-bb61-df7419ec7533.jpeg)

**Comment by lwisne** [comment]
Think this is WAI. Any reason you're assuming it should work differently?
