### ISSUE TITLE
accounts:import filename does not work

### ISSUE THREAD

**Issue by wk27** [iron-fish/ironfish#1385]
### What happened?

Hi 

Just a little clarification about accounts:import syntax.
From documentation:
>> ironfish accounts:import filename
It doesn't work.
The same for:
>> ironfish accounts:import $IRONFISH_WALLET filename.json

Correct solution way is:
cd $HOME/ironfish/ironfish-cli
cat filename.json | ironfish accounts:import

Please fix the page
https://ironfish.network/docs/onboarding/iron-fish-accounts-commands#import-an-account

Thank you.

### Version

0.1.33

**Comment by wd021** [comment]
@wk27 i just tested both import methods and they work. if you are importing with filename, remember its `ironfish accounts:import filename` and not `ironfish accounts:import $IRONFISH_WALLET filename`
