### ISSUE TITLE
mining work lag

### ISSUE THREAD

**Issue by terrancewong** [iron-fish/ironfish#1390]
### What happened?

Mining work via `miner/blockTemplateStream` arrives 3-5 sec after node synced a new block

### Version

v0.1.33

### Graffiti

bh9sqoCqIR3rDFstCCCw1g

**Comment by lwisne** [comment]
Need more information here, or else we will close this one.

**Comment by terrancewong** [comment]
need what information, this issue still not solved, v0.1.41
and the latency becomes longer and longer, into hundreds of seconds. the node is useless for mining.

**Comment by lwisne** [comment]
This is same as https://github.com/iron-fish/ironfish/issues/1418, right?

**Comment by terrancewong** [comment]
yes. a long lasting issue.
