### ISSUE TITLE
cannot send transaction after upgrade to 0.1.33, wrong balance detection

### ISSUE THREAD

**Issue by gzivdo** [iron-fish/ironfish#1392]
### What happened?

Before upgrade transactions worked, after upgrade stoped.
Balance was 1.7
![изображение](https://user-images.githubusercontent.com/13568002/168426900-3e3d91b8-4a90-47b1-9eb1-3756c7973757.png)
Then i made a rescan and it start working again.
![изображение](https://user-images.githubusercontent.com/13568002/168426920-c377249c-51a6-4952-bbc1-ac6b771d1313.png)
Some bug present here, not sure that provided info will help to detect it.

### Version

0.1.33

### Graffiti

ar2Obyahain

**Comment by suugee** [comment]
Same problem

**Comment by gzivdo** [comment]
today 1 block mined and the same
![изображение](https://user-images.githubusercontent.com/13568002/168463690-93e9b276-f0cf-488c-81df-50809abfb2fc.png)

**Comment by lwisne** [comment]
We believe this issue has been resolved - let us know if you're still seeing it.
