### ISSUE TITLE
node crashing right after start after last possible deposit

### ISSUE THREAD

**Issue by gzivdo** [iron-fish/ironfish#1393]
### What happened?

When balance is not sufficient for transaction, node is crashed in attempt of sending transaction. Then it cannot start in a boot loop.
![изображение](https://user-images.githubusercontent.com/13568002/168427435-1497bd76-5ee2-40cb-8d48-9a9fe5a08bb2.png)

### Version

0.1.33

### Graffiti

ar2Obyahain

**Comment by lwisne** [comment]
We believe this is now fixed. Let us know if you believe otherwise!
