### ISSUE TITLE
its possible to sign up with Graffiti.postfix and become owner of pool :)

### ISSUE THREAD

**Issue by gzivdo** [iron-fish/ironfish#1394]
### What happened?

Pools are Graffiti.postfix. It is possible to sign up with that name and you are like an owner of that pool.
Need to forbid to register such Graffiti (exising pool name).
And forbid to use pool name if the such graffiti exists.
Better - forbid to use point in graffiti name.

### Version

0.1.33

### Graffiti

ar2Obyahain

**Comment by wd021** [comment]
not sure this is a bug. pool name and graffitis are separate and there's no overlap that causes a conflict with the same name.

**Comment by lwisne** [comment]
agreed. closing.
