### ISSUE TITLE
MacOS upgrade to 0.1.34 from 0.1.33 is not upgrading, status still shows 0.1.33 and node starts on 0.1.33

### ISSUE THREAD

**Issue by johnsgeorgecet** [iron-fish/ironfish#1398]
### What happened?

Mac OS. upgraded to 0.1.34 using the command
brew update && brew uninstall ironfish && brew install ironfish

however the status still shows 0.1.33. node started and running as 0.1.33

### Version

0.1.34

### Graffiti

johnsgeorge

**Comment by johnsgeorgecet** [comment]
![0 1 34 upgrade](https://user-images.githubusercontent.com/53503800/168437263-b960d1f8-febf-4190-ac7e-18b097923692.jpg)

**Comment by deekerno** [comment]
It appears that Homebrew has not finished updating with the new release. It should be up later today.

**Comment by johnsgeorgecet** [comment]
oh i see, thanks. will check again later when it is up. 
will there be any update message in discord when it is up?
