### ISSUE TITLE
Error: Request failed (400) error: Insufficient funds

### ISSUE THREAD

**Issue by pgulyaev88** [iron-fish/ironfish#1401]
### What happened?

![изображение](https://user-images.githubusercontent.com/17798697/168450833-8169e0c3-a5e1-449f-b280-ce3e2c91818e.png)

### Version

0.1.34 @ e0f5e11

### Graffiti

BelarusNoda

**Comment by suugee** [comment]
Same problem

**Comment by lwisne** [comment]
We believe this issue has been resolved. Let us know if you are still seeing it.
