### ISSUE TITLE
testnet.ironfish.network crashed with an application error

### ISSUE THREAD

**Issue by CalebKoranda** [iron-fish/ironfish#1410]
### What happened?

While trying to load the testnet leaderboard at testnet.ironfish.network, the website went completely black and produced the message: "Application error: a client-side exception has occurred (see the browser console for more information)."
<img width="946" alt="testnetError" src="https://user-images.githubusercontent.com/54342982/168480066-f60682b4-093c-4a37-b7bc-1a71d6618fd0.png">
The browser console shows the following errors:
<img width="498" alt="consoleOutput" src="https://user-images.githubusercontent.com/54342982/168480144-27fb1262-22ac-4cdd-9935-f751437bc7df.png">

### Version

v0.1.33

### Graffiti

cajoko

**Comment by wd021** [comment]
wrong repo, also just temporarily down..
