### ISSUE TITLE
Hosted Node, negative number in the field, hours until the next reward

### ISSUE THREAD

**Issue by Rodeni4** [iron-fish/ironfish#1414]
### What happened?

1. The supplier has turned off the electricity.
2. I started the node, 3 hours of waiting was displayed
3. Three hours have passed ->  0 hours until next reward was displayed
4. Four hours have passed ->  -1 hours until next reward was displaye
![Screenshot_20220515-233957_Chrome](https://user-images.githubusercontent.com/65849224/168515101-94548009-d32c-492b-9179-fa3554015d6e.jpg)
d

5. I'm watching now
![ironfish2](https://user-images.githubusercontent.com/65849224/168515341-1340ef82-ff48-4598-830c-120bf3b33b6f.jpg)

### Version

v0.1.34

### Graffiti

MSI2020

**Comment by wd021** [comment]
should go in this repo -> https://github.com/iron-fish/website-testnet

**Comment by lwisne** [comment]
This is fixed now.
