### ISSUE TITLE
Hours to reward exceed 12 hours

### ISSUE THREAD

**Issue by HN92127** [iron-fish/ironfish#1415]
### What happened?

While running a Node, the Testnet Leaderboard showed 20 hours to my next reward .  The Graffiti is "AP#5552".  I also have the same issue with my other Node ran under the Graffiti "APPOWER".  Screen captures provided.

![image](https://user-images.githubusercontent.com/104040588/168612350-d44d66fd-e03f-4f7a-b7bc-b34c083d4179.png)
![Ironfish bug](https://user-images.githubusercontent.com/104040588/168640617-2c2c0a37-cadc-446f-80d8-1560c5e49e9e.JPG)

### Version

v01.32

### Graffiti

AP#5552

**Comment by lwisne** [comment]
We think this has been fixed. Let us know here if you believe that not to be the case.
