### ISSUE TITLE
Very long latency in mining

### ISSUE THREAD

**Issue by terrancewong** [iron-fish/ironfish#1418]
### What happened?

For `miner/newBlocksStream`, node gives out a new work for next block very long time after a new block synced. could be 10-80sec or even longer, under very low (< 2) system load.

### Version

0.1.34

### Graffiti

bh9sqoCqIR3rDFstCCCw1g

**Comment by terrancewong** [comment]
0.1.36 still suffers from this issue. please look into it!

**Comment by lwisne** [comment]
Are you still seeing this behavior?

**Comment by terrancewong** [comment]
Yes. this issue still not solved, v0.1.41
and the latency becomes longer and longer, into hundreds of seconds. the node is useless for mining.

to verify this. start a miner/newBlocksStream, wait for new works, check last blcok timestamp. 

```
for a in 1 ; do echo -n '{"type":"message","data":{"mid":1,"type":"miner/blockTemplateStream"}}\x0c' ; sleep 1 ; done | nc <node IP> <node port> | tr '\014' '\n'
```

**Comment by terrancewong** [comment]
Can also compare node status with `newBlocksStream` side by side, mining work comes much later than new block on the node.

**Comment by holahula** [comment]
Closing due to staleness. If the issue persists in versions `1.0.0+` - please file a new issue
