### ISSUE TITLE
Payout percent calculation issue

### ISSUE THREAD

**Issue by xbeastx** [iron-fish/ironfish#1419]
### What happened?

It looks like there is a bug in payout amount calculation:
https://github.com/iron-fish/ironfish/blob/d6845e388a5a3fc6911ed1ca1e70571c36f5af91/ironfish/src/mining/poolShares.ts#L122

The default value balancePercentPayout is 10 (10 percents) and it will calculate correct 200 / 10 = 20. But if we will choose another value let's say 50% than 200 / 50 it's not make sense.

### Version

v0.1.34

**Comment by devzorg** [comment]
It should be multiplicated,
something like `const payoutAmount = BigIntUtils.multiply(confirmedBalance, BigIntUtils.divide(this.balancePercentPayout, 100))`
