### ISSUE TITLE
Hosted Node bug : Every 2 hour will give me 10 point.

### ISSUE THREAD

**Issue by SUGARTOP** [iron-fish/ironfish#1421]
### What happened?

A bug happened!

Normally , Hosted Node will give 10 point every 12 hours.

Now , Hosted Node give 10 point to me every 2 hours.

Photo report : https://drive.google.com/file/d/11r90vureRP4I97lTJAdeD7DtKtMFia-u/view?usp=sharing

### Version

0.1.34@src

### Graffiti

SUGARTOP

**Comment by lwisne** [comment]
This is fixed now.

**Comment by lwisne** [comment]
(for reference, the points were valid and we had some delays in rewarding them properly)
