### ISSUE TITLE
Hosted Node gives reward before 12 hours causing next payout to be greater than 12 hours

### ISSUE THREAD

**Issue by CalebKoranda** [iron-fish/ironfish#1423]
### What happened?

This bug is similar to bug: #1415 . The time until the node gives points for hosting is greater than 12 hours. I believe this is because there is another bug that causes the node to payout quicker than 12 hours and so it compensates by adding more time on the next cycle. For instance, I got 10 points for hosting a node and then another 10 points approximately an hour and half later.
<img width="938" alt="2hours" src="https://user-images.githubusercontent.com/54342982/168655883-9427b1f5-04ef-438b-b9b7-a4fd236b90c9.png">
This caused my next payout to be 21 hours until points.
<img width="312" alt="21hours" src="https://user-images.githubusercontent.com/54342982/168655941-01e47e5b-2062-4851-83d2-43459f384af1.png">
I believe the issue happens here:
<img width="419" alt="timeUntilReward" src="https://user-images.githubusercontent.com/54342982/168656008-ac6373fe-e4bb-4579-b1b3-574a92bf0482.png">
My guess is that totalHours becomes negative somehow and caused the timeUntilReward to be greater than 12 hours. Just a theory.

### Version

v0.1.33

### Graffiti

cajoko

**Comment by lwisne** [comment]
We had a few problems with the timing being exactly right a few months back. Should be fixed now.
