### ISSUE TITLE
Discrepancy between overall leaderboard rank and pool 1 rank

### ISSUE THREAD

**Issue by CalebKoranda** [iron-fish/ironfish#1424]
### What happened?

The testnet shows that I am ranked 901st in pool 1 but 897th overall. However, I don't have any pool 2 points so I don't see how it is possible to have a better overall rank than my pool 1 rank. I believe this must be some sort of bug.
<img width="938" alt="leaderboard" src="https://user-images.githubusercontent.com/54342982/168658047-f11931be-025e-4d0e-b1e1-1c2bb11f0205.png">

### Version

v0.1.33

### Graffiti

cajoko

**Comment by lwisne** [comment]
I think this was some sort of blip - the numbers make sense now (Pool 1 rank is slightly better than overall due to 0 Pool 2 pts)
