### ISSUE TITLE
Pool payments

### ISSUE THREAD

**Issue by qubinets** [iron-fish/ironfish#1426]
### What happened?

i had that problems because of 2 wallets , pool trying to pay from default wallet but rewards came to another, so to repair payments i manually moved today coins from second wallet to default and balance started lowering,meaning that it paying now.So bug here is that rewards receives not pool wallet but another,need mechanism to autoswitch to right wallet
i believe there is a problem near pool wallet name and "Insufficient balance".

### Graffiti

Qubinets

**Comment by wd021** [comment]
pool payments should go to the publickey you started mining pool with. is that not correct?
