### ISSUE TITLE
Error: Request failed (400) error: Insufficient funds

### ISSUE THREAD

**Issue by divnovvv** [iron-fish/ironfish#1427]
### Description

Faced with a similar problem, everything is fine, but the transaction does not pass. What could be the problem? I use "ironfish deposit --confirm"
›   Error: Request failed (400) error: Insufficient funds
![image](https://user-images.githubusercontent.com/98264742/168740975-b5c00444-2caa-4882-951e-b4ab2242d045.png)
![image](https://user-images.githubusercontent.com/98264742/168740994-9065a3b1-2a38-4abd-81d8-0028df1427c7.png)
![image](https://user-images.githubusercontent.com/98264742/168741010-2a72f42f-ba3e-4e28-81e2-00c13fe553a4.png)
![image](https://user-images.githubusercontent.com/98264742/168741028-d7c62cad-85c4-46d7-9ff2-6bf64ad9da4c.png)

https://discord.com/channels/771503434028941353/816795916627345450/975660545648775168

**Comment by lwisne** [comment]
We believe this issue is resolved now. Let us know if you don't think that's the case!

**Comment by divnovvv** [comment]
Yes, i got it.

**Comment by divnovvv** [comment]
Yes, i got it.
