### ISSUE TITLE
Hosting a node reward issue

### ISSUE THREAD

**Issue by cryptocapchik** [iron-fish/ironfish#1430]
### What happened?

A bug happened! 
Rewards earned not every 12 hours but once a day in the period of 1 hour. And there more rewards then it should be.

May 15
Hosted a node | 2022-05-15 17:57:12 | 10 
Hosted a node | 2022-05-15 16:45:50 | 10

May 16
Hosted a node | 2022-05-16 20:18:49 | 10
Hosted a node | 2022-05-16 20:11:55 | 10
Hosted a node | 2022-05-16 20:05:04 | 10

### Version

v0.1.34

### Debug output

```shell
Iron Fish version            0.1.34 @ src
Iron Fish library            0.0.12 @ src
Operating system             Linux x64
CPU model(s)                 AMD EPYC 7282 16-Core Processor
CPU threads                  10
RAM total                    58.87 GiB
Node version                 v16.15.0
ironfish in PATH             true
Telemetry enabled            true
Accounts head hash           000000000007ac98073bd49f00daefd818dbb6033379b93967c300161cfb9734
Accounts head in chain       true
Accounts head sequence       8442
```

### Graffiti

cryptocapchik

**Comment by lwisne** [comment]
Looks like this one resolved. Thanks for participating in the testnet!
