### ISSUE TITLE
[issue name]the balance is wrong 

### ISSUE THREAD

**Issue by hxltyy** [iron-fish/ironfish#1436]
### What happened?

A bug happened!
the account balance si wrong。 the first query is 332  coin . after two hours  is 310 
![6370528714dc5bc8f971c93f7c35279](https://user-images.githubusercontent.com/103976370/168987934-70676d61-b6f7-4eec-a80f-aa7fc548e8a0.png)
![8d4f72813d8e117a9168ff0fbcdf6b1](https://user-images.githubusercontent.com/103976370/168987977-6d3aaaae-4a86-4dfe-8e1e-a5aa939fbb4d.png)

### Version

0.1.34

### Graffiti

hxltyy

**Comment by adi7dev** [comment]
Check this out: https://github.com/iron-fish/ironfish/wiki/FAQ#i-mined-a-block-according-to-ironfish-status-but-i-dont-see-iron-available-to-spend-in-ironfish-accountsbalance-why-is-that  to learn more about the difference in amounts visible.
