### ISSUE TITLE
[issue name]host rewards wrong

### ISSUE THREAD

**Issue by hxltyy** [iron-fish/ironfish#1437]
### What happened?

A bug happened! my host time time goes back  
![879dbecc4448ab62259da007a8e9ab0](https://user-images.githubusercontent.com/103976370/168988283-6ec6f9b1-a8df-4baa-b834-f48bfbd7653f.png)

### Version

0.1.34

### Graffiti

hxltyy

**Comment by rohanjadvani** [comment]
Please see [this](https://discord.com/channels/771503434028941353/829416209787256832/976923652136239134) message for more details.
