### ISSUE TITLE
Not receiving points for hosting node despite being synced

### ISSUE THREAD

**Issue by gjfrn** [iron-fish/ironfish#1441]
### What happened?

I am running a note which is constantly fully synced and Telemetry has been enabled throughout. I have had no issue with hosting a node throughout Phase 1 so I know this has been reliable.

I have only received two rewards for hosting a node (originally as 0.1.33) as follows:
Hosted a node | 2022-05-14 03:59:36 | 10 |  
Hosted a node | 2022-05-13 15:55:17 | 10 |
[GFIRONFISH](https://testnet.ironfish.network/users/8468)

However, I have not received any other rewards despite consistently hosting a node. Upgrading to 0.1.34 has not resolved this issue, nor does restarting the node. The node remains fully synced:

![169036667-20a617ca-ddb7-412b-af6a-d6bd5f4a884c](https://user-images.githubusercontent.com/95665400/169042384-3e8285af-4d0f-44cd-996f-7167b19e407b.png)

During the period where I won points, I did mine to my own node, but shortly after switched to mining to the pool. I will test mining to my node again and report back.

### Version

0.1.34

### Debug output

```shell
yarn run v1.22.17
$ yarn build && yarn start:js debug
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run debug
Database in use, skipping output that requires database.
Stop the node and run the debug command again to show full output.

Iron Fish version       0.1.34 @ src
Iron Fish library       0.0.12 @ src
Operating system        Darwin arm64
CPU model(s)            Apple M1
CPU threads             8
RAM total               16.00 GiB
Node version            v16.5.0
ironfish in PATH        true
Telemetry enabled       true
✨  Done in 2.25s.
```

### Graffiti

GFIRONFISH

**Comment by iPaulPro** [comment]
Same here. Been running a node for over 24 hours with graffiti set and telemetry on, but have received no points and dashboard shows 0 hours.

I ran `ironfish testnet` then `ironfish start`. I have been successfully mining on the node, so I know it's fully synced and working.

**Comment by lwisne** [comment]
It looks like this resolved for you? I'm seeing 1,344 hours of node online time.
