### ISSUE TITLE
奖励时间为负数？

### ISSUE THREAD

**Issue by elilth** [iron-fish/ironfish#1452]
一直都有得到积分，重新安装了操作系统，而后同步完数据，为什么是”-28 小时直到下一次奖励“？
这是关闭节点，一段时间后开启节点的惩罚机制吗？
节点版本是0.1.34。
刚刚换了0.1.35版本不知道会不会修复。
![image](https://user-images.githubusercontent.com/39581395/169182038-e7d0e453-e338-4001-b654-fe1a9c7e9998.png)

**Comment by rohanjadvani** [comment]
我们知道这个问题，您的积分将在未来进行调整。 请参阅 [this](https://discord.com/channels/771503434028941353/829416209787256832/976923652136239134) 了解更多信息。
