### ISSUE TITLE
explorer doesn't see my node

### ISSUE THREAD

**Issue by alterkahn** [iron-fish/ironfish#1455]
### Description

I'm running the latest -v of ironfish node but the explorer doesn't see me

<img width="740" alt="Снимок экрана 2022-05-19 в 11 07 59" src="https://user-images.githubusercontent.com/67752860/169245122-47ea4712-eff2-40a5-9dbd-549afc2d5b94.png">
<img width="1193" alt="Снимок экрана 2022-05-19 в 11 07 48" src="https://user-images.githubusercontent.com/67752860/169245130-9b19e581-6d68-47fa-aef7-5498de60639a.png">
<img width="826" alt="Снимок экрана 2022-05-19 в 11 10 37" src="https://user-images.githubusercontent.com/67752860/169245349-dc365161-4358-4ddf-823e-2e90cb7ce6a4.png">

**Comment by QustomQure** [comment]
It is known issue. Reported many times to the point many of discord topics are swarmed with this reports

**Comment by rohanjadvani** [comment]
@alterkahn - Can you clarify what `but the explorer doesn't see me` means? Are you referring to the negative hours until your next reward?

**Comment by alterkahn** [comment]
> @alterkahn - Can you clarify what `but the explorer doesn't see me` means? Are you referring to the negative hours until your next reward?

yes, I'm talking about negative hours and about that the points for the node hasn't been assigned from 16th of May

**Comment by rohanjadvani** [comment]
Please see [this announcement](https://discord.com/channels/771503434028941353/829416209787256832/976923652136239134) in Discord. We had an issue accumulating points (either crediting hours too quickly or too slowly). The events will adjust over time as your node stays online and you will not lose any points.

**Comment by alterkahn** [comment]
> Please see [this announcement](https://discord.com/channels/771503434028941353/829416209787256832/976923652136239134) in Discord. We had an issue accumulating points (either crediting hours too quickly or too slowly). The events will adjust over time as your node stays online and you will not lose any points.

ok, got it, thanks
