### ISSUE TITLE
setting of telemetry

### ISSUE THREAD

**Issue by erzhongdetaozi** [iron-fish/ironfish#1456]
### What happened?

A bug happened!

Normally, every body will follow the official guideline to set up the ironfish node and start it. But in the official guideline, there is no reminder for the setting of telemetry, so hope the guideline can be updated to add the command "ironfish config:set enableTelemetry true" 

### Graffiti

keving

**Comment by lwisne** [comment]
Agree, this is not documented as well as I would prefer.

**Comment by hughy** [comment]
Closing as stale
