### ISSUE TITLE
'$$' as input value in commands is interpreted as some variable

### ISSUE THREAD

**Issue by johnsgeorgecet** [iron-fish/ironfish#1457]
### What happened?

If I use the characters '$$' in any commands like accounts:create, it is interpreted and taken as some variable value both in Mac OS and Windows npm install. In Mac OS it is always taken as the number 584. Whereas in windows npm install, it keeps changing with values used last time. 

Windows:
-----------------

PS C:\Users\johnsge> ironfish accounts:create $$testaccount$$
Creating account accounts:listtestaccountaccounts:list
Account accounts:listtestaccountaccounts:list created with public address 43a2e509ee3217a0158a9977dd704d74f3c582a2ace0b753968c69112133817eed47f0caddd8a4cd0bd3d7
Run "ironfish accounts:use accounts:listtestaccountaccounts:list" to set the account as default
PS C:\Users\johnsge>
PS C:\Users\johnsge>
PS C:\Users\johnsge>
PS C:\Users\johnsge>
PS C:\Users\johnsge> ironfish accounts:create $$testaccount$$
Creating account $$testaccount$$testaccount$$testaccount$$
Account $$testaccount$$testaccount$$testaccount$$ created with public address 03404828e0c3b3a993ff4bc5ea2a296d74e78b4ffa5425e747a174476797f04946f1f5d468af9543828761
Run "ironfish accounts:use $$testaccount$$testaccount$$testaccount$$" to set the account as default
PS C:\Users\johnsge>

Mac OS:
-----------
johnsgeorge@Johnss-MacBook-Pro ~ % ironfish config:set enableTelemetry $$ 
Connecting to /Users/johnsgeorge/.ironfish/ironfish.ipc
Could not convert "584" from string to boolean
johnsgeorge@Johnss-MacBook-Pro ~ % ironfish config:set enableTelemetry - 
Connecting to /Users/johnsgeorge/.ironfish/ironfish.ipc
Could not convert "-" from string to boolean
johnsgeorge@Johnss-MacBook-Pro ~ % ironfish accounts:create $$testaccount$$
Connecting to /Users/johnsgeorge/.ironfish/ironfish.ipc
Creating account 584testaccount584
Account 584testaccount584 created with public address 127021c1fbb0f50721425d3d23c7a66cd449c157e97ba601904851f7baeda0686ae355212b74346d37438b
Run "ironfish accounts:use 584testaccount584" to set the account as default

### Version

0.1.35

### Graffiti

johnsgeorge

**Comment by lwisne** [comment]
yes, this is the case with any command line. Not really something we plan to support.
