### ISSUE TITLE
The transfer could not reach the account

### ISSUE THREAD

**Issue by SunnyBoy00l** [iron-fish/ironfish#1464]
### What happened?

  
I tried to transfer money from account A to account B, but it said that the transfer was successful, but the account could not be transferred, and the transaction hash could not be found, is this caused by A bug?  Could you help to find the cause of this problem?
 

### Version

0.1.35

### Debug output

```shell
Iron Fish version       0.1.35 @ 4bc3765
Iron Fish library       0.0.13 @ 4bc3765
Operating system        Linux x64
CPU model(s)            Intel(R) Xeon(R) E-2288G CPU @ 3.70GHz
CPU threads             16
RAM total               62.46 GiB
Node version            v16.13.0
ironfish in PATH        true
Telemetry enabled       false
```

### Relevant log output

```shell
https://explorer.ironfish.network/transaction/7c8b09241770e604fd01de04e9acaee4ceb1c6ef2db117d1a3d88307c2736eb4
```

### Graffiti

S-pool

**Comment by wd021** [comment]
can you print more of the error log

**Comment by lwisne** [comment]
with no further details here, have to close
