### ISSUE TITLE
RAM issue

### ISSUE THREAD

**Issue by alterkahn** [iron-fish/ironfish#1466]
### What happened?

Looks like the memory issue is actual again.
The system requires a restart.

<img width="1097" alt="Снимок экрана 2022-05-20 в 12 15 40" src="https://user-images.githubusercontent.com/67752860/169496715-1dccc39a-c8a7-44ee-a7da-0b908b05b913.png">

### Version

v0.1.35

### Graffiti

alterkahn

**Comment by centrd** [comment]
Not sure if it's the same issue, but I noticed the RAM utilisation creeping up on my node, eventually eating into swap.

name       ironfish
version    0.1.35
git        4bc3765
runtime    node/16.13.0

Linux ubuntu 5.4.0-110-generic #124-Ubuntu SMP Thu Apr 14 19:46:19 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 20.04.4 LTS
Mem:           3897

**Comment by holahula** [comment]
Closing due to staleness. If the issue persists in versions `1.0.0+` - please file a new issue
