### ISSUE TITLE
nullifire is null leads to ironfish clashed

### ISSUE THREAD

**Issue by ffteng46** [iron-fish/ironfish#1468]
### What happened?

Ironfish failed to start when using command of "ironfish start",error message is "nullifierToNote mappings must have a corresponding noteToNullifier map.".I check the code find that the variant of nullifire which is null leads to this error.
I don't known why but i think we should ignore this null value and just refuse to process this nullifire.
See the code:
// If newSequence is null and blockHash is null, we're removing the transaction from
                // the chain and it wasn't created by us, so unmark notes as spent
                const isRemovingTransaction = newSequence === null && blockHash === null;
                for (const spend of transaction.spends()) {
                    const nullifier = spend.nullifier.toString('hex');
                    const noteHash = this.nullifierToNote.get(nullifier);
                    if (noteHash) {
                        const nullifier = this.noteToNullifier.get(noteHash);
                        if (!nullifier) {
                            continue;//not throw error just ignore this value
                            throw new Error('nullifierToNote mappings must have a corresponding noteToNullifier map');
                        }
                        await this.updateNoteToNullifierMap(noteHash, {
                            ...nullifier,
                            spent: !isRemovingTransaction,
                        });
                    }
                }
I just simply add a continue  before throw the error,and it does work!.I'm not familiar with the overall construct ,maybe this is a bug.

### Version

0.1.35 

### Debug output

```shell
Iron Fish version       0.1.35 @ src
Iron Fish library       0.0.13 @ src
Operating system        Linux x64
CPU model(s)            AMD EPYC 7F32 8-Core Processor
CPU threads             16
RAM total               251.84 GiB
Node version            v16.15.0
ironfish in PATH        false
Telemetry enabled       true
```

### Relevant log output

```shell
ironfish/ironfish/build/src/account/accounts.js:318
                            throw new Error('nullifierToNote mappings must have a corresponding noteToNullifier map');
                                  ^

Error: nullifierToNote mappings must have a corresponding noteToNullifier map
    at ironfish/ironfish/build/src/account/accounts.js:318:35
    at async LevelupDatabase.withTransaction (ironfish/ironfish/build/src/storage/database/database.js:39:28)

nullifire=697d8a3780f3601858d73f6bd3a1d82d159d0924dea061a6b3406016451b8858
null
I catch this address to trigger the error above.
```

### Graffiti

luol-tech-worker29

**Comment by lwisne** [comment]
We believe this to be resolved now. Let us know if you're still seeing this behavior.
