### ISSUE TITLE
[ironfish deposit] Error fetching deposit address

### ISSUE THREAD

**Issue by zhouwu5222** [iron-fish/ironfish#1472]
### What happened?

A bug happened!worker01<2022-05-21 12:45:10> /data0/iron
root># curl https://api.ironfish.network/deposits/address
{"address":"1199c69c1b05e5c8d2e87fab15bf2338fdefed2a2fa6ab2604062dd15fb1bf430b021e41071e39e0b46e58"}
worker01<2022-05-21 12:46:14> /data0/iron
root># ironfish deposit --datadir=/data0/iron/ironfish
Error fetching deposit address. Please try again later.

### Version

0.1.35 linux-x64 node-v16.15.0

### Graffiti

minerCoin

**Comment by wd021** [comment]
don't think this is a permanent error. please try again, it should work.
