### ISSUE TITLE
Crashing after update

### ISSUE THREAD

**Issue by Ivan123-ops** [iron-fish/ironfish#1474]
### What happened?

I updated to  0.1.35 @ src and now node crashes

May 21 08:05:55 ubuntu yarn[21942]: WebSocket server started at :::9033
May 21 08:05:56 ubuntu yarn[21942]: /root/ironfish/ironfish/build/src/account/accounts.js:318
May 21 08:05:56 ubuntu yarn[21942]:                             throw new Error('nullifierToNote mappings must have a corresponding noteToNullifier map');
May 21 08:05:56 ubuntu yarn[21942]:                                   ^
May 21 08:05:56 ubuntu yarn[21942]: Error: nullifierToNote mappings must have a corresponding noteToNullifier map
May 21 08:05:56 ubuntu yarn[21942]:     at /root/ironfish/ironfish/build/src/account/accounts.js:318:35
May 21 08:05:56 ubuntu yarn[21942]:     at async LevelupDatabase.withTransaction (/root/ironfish/ironfish/build/src/storage/database/database.js:39:28)
May 21 08:05:56 ubuntu yarn[21923]: error Command failed with exit code 1.
May 21 08:05:56 ubuntu yarn[21923]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
May 21 08:05:56 ubuntu yarn[21884]: error Command failed with exit code 1.
May 21 08:05:56 ubuntu yarn[21884]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
May 21 08:05:56 ubuntu systemd[1]: ironfishd.service: Main process exited, code=exited, status=1/FAILURE
May 21 08:05:56 ubuntu systemd[1]: ironfishd.service: Failed with result 'exit-code'.

### Version

 0.1.35 @ src

### Debug output

```shell
none
```

### Relevant log output

```shell
none
```

### Graffiti

777stakes

**Comment by lwisne** [comment]
We believe this to be resolved now. Let us know if you're still seeing this behavior.
