### ISSUE TITLE
the balance number is not equal to the available amount

### ISSUE THREAD

**Issue by erzhongdetaozi** [iron-fish/ironfish#1478]
### What happened?

when i check my wallet, the result shows that:
The balance is: $IRON 0.49931913 ($ORE 49,931,913)
Amount available to spend: $IRON 0.45870935 ($ORE 45,870,935)

I think this belongs to system error. the balance and the available number should be the same

### Graffiti

keving

**Comment by lwisne** [comment]
We believe this to be resolved now. Let us know if you're still seeing this behavior.
