### ISSUE TITLE
black hole transfer

### ISSUE THREAD

**Issue by chenghua0322** [iron-fish/ironfish#1481]
### What happened?

When conducting black hole transfers. The transaction was successful but the website cannot find it.

### Version

0.1.35

### Debug output

```shell
Iron Fish version       0.1.35 @ src
Iron Fish library       0.0.13 @ src
Operating system        Windows_NT x64
CPU model(s)            12th Gen Intel(R) Core(TM) i9-12900KF
CPU threads             24
RAM total               63.81 GiB
Node version            v16.13.1
ironfish in PATH        true
Telemetry enabled       true
Done in 3.57s.
```

### Graffiti

jackchen

**Comment by wd021** [comment]
whats this black hole transfer?

**Comment by lwisne** [comment]
Possibly you mean bank transfer here?

Can you give more info on what you were expecting?
