### ISSUE TITLE
Request failed (400) error: Insufficient funds

### ISSUE THREAD

**Issue by D-Elektra** [iron-fish/ironfish#1485]
### What happened?

A bug happened!
Yesterday I tried to make deposits and caught a weird bug.
I had this balance after the transaction:
Your remaining balance after this transaction will be $IRON 4.68187443 ($ORE 468,187,443).

Next transaction ended up with an error
An error occurred while sending the transaction.
 ›   Error: Request failed (400) error: All decryptable notes should be in the noteToNullifier 
 ›   map
error Command failed with exit code 2.
Insufficient balance: 0. Required: 0.10000001
error Command failed with exit code 1.

I made rescan-reset
I checked balance
Account - DiElektra
The balance is: $IRON 0.00000000 ($ORE 0)
Amount available to spend: $IRON 0.00000000 ($ORE 0)

After 1 hour I tried to check balance
The balance is: $IRON 3.91966678 ($ORE 391,966,678)
Amount available to spend: $IRON 3.91966678 ($ORE 391,966,678)
I tried to send one more transaction 
The balance is: $IRON 3.68399948 ($ORE 368,399,948)
Amount available to spend: $IRON 3.68399948 ($ORE 368,399,948)

The same error occurred.
After the error, my balance was $IRON 2.96118643

Today all is good, transactions are sent and the balance is correct. But the bug was weird...

![IMG_4772](https://user-images.githubusercontent.com/87807935/169725506-0e5bb9cc-49f3-4ca5-b09f-58507d296717.png)

### Version

v0.1.35

### Debug output

```shell
Iron Fish version       0.1.35 @ src
Iron Fish library       0.0.13 @ src
Operating system        Linux x64
CPU model(s)            Intel Xeon Processor (Skylake, IBRS)
CPU threads             6
RAM total               15.63 GiB
Node version            v16.15.0
ironfish in PATH        true
Telemetry enabled       true
```

### Relevant log output

```shell
An error occurred while sending the transaction.
 ›   Error: Request failed (400) error: All decryptable notes should be in the noteToNullifier 
 ›   map
error Command failed with exit code 2.
Insufficient balance: 0. Required: 0.10000001
error Command failed with exit code 1.
```

### Graffiti

DiElektra

**Comment by lwisne** [comment]
Appreciate the long explanation here - we are in the process of making balance reporting more efficient. Will close as this is hard to reproduce.
