### ISSUE TITLE
Config option maxPeers does not affect number of peers

### ISSUE THREAD

**Issue by dalloc** [iron-fish/ironfish#1486]
### What happened?

I wanted to lower the number of connected peers to 30 by running

`ironfish config:set maxPeers 30`

That accomplished nothing: I see 49 peers in `ironfish status -f`, even after node reboot.
![image](https://user-images.githubusercontent.com/59087625/169734793-63aa1db0-536c-4c93-86b3-55ed5647a04c.png)

Steps to reproduce:
1. Start node
2. Set peer target to K using `ironfish config:set targetPeers K`
3. Set peer cap to N (N < K) using `ironfish config:set maxPeers N`
4. Restart node

Expected behavior:
Peer connection capped at N

Observed behavior:
Peer connection capped at K

### Version

v0.1.35 @ 4bc3765

### Debug output

```shell
Iron Fish version       0.1.35 @ 4bc3765
Iron Fish library       0.0.13 @ 4bc3765
Operating system        Linux x64
CPU model(s)            AMD EPYC 7282 16-Core Processor
CPU threads             8
RAM total               29.39 GiB
Node version            v16.15.0
ironfish in PATH        true
Telemetry enabled       true
```

### Relevant log output

```shell
Outputs of ironfish config:show

{
...
   "maxPeers": 30,
   "minPeers": 1,
   "targetPeers": 50,
...
}
```

### Graffiti

dalloc

**Comment by wd021** [comment]
can you double-check this? I've tried reproducing on my end but it seems like the maxPeers value is respected.
