### ISSUE TITLE
Endless "Database reset" prompt

### ISSUE THREAD

**Issue by daveconcannon** [iron-fish/ironfish#1494]
### What happened?

After updating to the latest docker image, ironfish continually prompts the following:

`Error: You are running a newer version of ironfish on an older database.
    Run "ironfish reset" to reset your database.
`

There is no change after running "ironfish reset" or deleting the database files.

### Version

0.1.35 @ 4bc3765

### Debug output

```shell
Version       0.1.35 @ 4bc3765
Node Name     VUCANAUT
Graffiti      NONE
Peer Identity eUiceOM+9YC8kS8vuNjDQHoYDOcUifDycGt1ikkH+UM=
Peer Agent    ironfish/0.1.35/4bc3765
Peer Port     9033
Bootstrap     test.bn1.ironfish.network
 
    Error: You are running a newer version of ironfish on an older database.
    Run "ironfish reset" to reset your database.
```

**Comment by lwisne** [comment]
We believe this to be fixed now. Let us know here if you don't think this is the case.
