### ISSUE TITLE
Error when machine cpu > 80

### ISSUE THREAD

**Issue by garysdevil** [iron-fish/ironfish#1502]
### What happened?

Bug:  I run miner failed when my machine CPU > 80 and  setting threads of miner more than 80.
Hoping: I can run miner success when my machine CPU > 80 and setting threads of miner more than 80.

Faile when setting threads of miner more than 80:
<img width="1439" alt="error" src="https://user-images.githubusercontent.com/41293784/170181837-2f64b416-81dd-481c-872b-3634808aa708.png">

Success when setting threads of miner less than 80:
<img width="1437" alt="success" src="https://user-images.githubusercontent.com/41293784/170182653-6f06368d-0aeb-4964-93f7-7c6f38013fc5.png">

### Version

0.1.35

### Debug output

```shell
Iron Fish version            0.1.35 @ 4bc3765
Iron Fish library            0.0.13 @ 4bc3765
Operating system             Linux x64
CPU model(s)                 AMD EPYC 7H12 64-Core Processor
CPU threads                  128
RAM total                    1.96 TiB
Node version                 v16.13.0
ironfish in PATH             true
Telemetry enabled            false
Accounts head hash
Accounts head in chain       false
Accounts head sequence       null
```

### Graffiti

54528

**Comment by lwisne** [comment]
nofix for now. We don't claim to support this number of threads.
