### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by maviroot** [iron-fish/ironfish#1511]
### What happened?

Problem with installation from official guide.

New clear server. 
Ubuntu 20.04 
Node v16.15.0

```
root@maviroot:~# node --version
v16.15.0
root@maviroot:~# npm install -g ironfish
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -2
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-05-26T11_20_47_658Z-debug-0.log
```

Log is too long to attach.

### Version

0.1.35

### Graffiti

sergsup

**Comment by danuzlav** [comment]
Hi @maviroot,
Please attach the log file - `/root/.npm/_logs/2022-05-26T11_20_47_658Z-debug-0.log`

**Comment by wd021** [comment]
@maviroot if the log is too long to attach, can you please extract the relevant part for when it fails.

**Comment by maviroot** [comment]
[2022-05-26T11_20_47_658Z-debug-0.log](https://github.com/iron-fish/ironfish/files/8781285/2022-05-26T11_20_47_658Z-debug-0.log)

**Comment by danuzlav** [comment]
```
1197 error syscall spawn git
```
Make sure you have the `git` installed on your env.

Also, try then to clear `npm` cache according to: https://reactgo.com/npm-clear-cache/

**Comment by lwisne** [comment]
We think this is fixed now. Let us know if you don't agree!
