### ISSUE TITLE
CRITICAL

### ISSUE THREAD

**Issue by Masternode24** [iron-fish/ironfish#1527]
### What happened?

if I try on the fly set TCP RPC = true

then all will be brocken !!!

Please confirm !!!

```
root@Ubuntu-2004-focal-64-minimal-hwe ~ # ironfish accounts:balance
yarn run v1.22.18
$ yarn build && yarn start:js accounts:balance
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run accounts:balance
No route found account/getBalance in namespace account for method getBalance
Done in 1.77s.
```

### Version

0.35

### Graffiti

Masternode24.de

**Comment by zbretta** [comment]
Confirmed - work around pass key in start command: 
```
ironfish start --rpc.tcp
```

**Comment by Masternode24** [comment]
If confirmed please send su some points for our work =)
![image](https://user-images.githubusercontent.com/81598429/170894898-3c2d7562-ba5f-456e-9c11-1c8463a0d98c.png)

**Comment by Masternode24** [comment]
Also we dont find any RPC docs (Requests). Please send us this information for our testing

**Comment by danield9tqh** [comment]
Can you confirm what you mean by "on the fly set TCP RPC = true". Are you setting a config variable while the node is running?

**Comment by Masternode24** [comment]
YesSent from my Galaxy
-------- Original message --------From: Daniel Cogan ***@***.***> Date: 06/06/2022  19:27  (GMT+02:00) To: iron-fish/ironfish ***@***.***> Cc: Oleg Pahl ***@***.***>, Author ***@***.***> Subject: Re: [iron-fish/ironfish] CRITICAL (Issue #1527) 
Can you confirm what you mean by "on the fly set TCP RPC = true". Are you setting a config variable while the node is running?

**Comment by lwisne** [comment]
I think what was happening here is you were changing config settings while the node is running. These changes would require a node restart.

Going to close - let me know if there is something further here.
