### ISSUE TITLE
Ironfish deposit cannot be executed

### ISSUE THREAD

**Issue by ponpon-ux** [iron-fish/ironfish#1530]
### What happened?

I'm using docker.
The execution of the ironfish deposit command is very slow, isn't it?

There was one case where there was no response even if I entered the following command.
I ran it a second time now, but there is no response.

```
docker exec -it <contena ID> ironfish deposit --confirm

```

The screen below didn't move for about 30 minutes, and I couldn't do desipod.
```
PS C:\Users\marom> docker exec -it c4e7539541fe ironfish deposit --confirm
>>
Creating the transaction: [████████████████████████████████████████] 100% | ETA: 0s
```

### Graffiti

ponpon111

**Comment by lwisne** [comment]
Does this behavior persist? We've seen lots of transactions and haven't seen this problem, I suspect it will be hard to recreate.
