### ISSUE TITLE
memory[issue name]

### ISSUE THREAD

**Issue by imp050t0r** [iron-fish/ironfish#1534]
### What happened?

starting node with --> yarn start start -d default -p 9033

after day or so i will run out of memory ??

time 17:25
![time 17_28](https://user-images.githubusercontent.com/106441783/170832008-2b772cec-0335-46ef-8d2a-08f532933113.jpg)

time 17:35
![time 17_35](https://user-images.githubusercontent.com/106441783/170832184-9e605773-d0b5-44bc-a719-3684fae54792.jpg)

when i run out of memory the node appears to be synchronising, but in fact it is not. it is not possible to send a deposit. the status indicates that the node is sync but the thing stops !!!!

### Version

1.35

### Graffiti

IMP05t0R

**Comment by holahula** [comment]
Closing due to staleness. If the issue persists in versions `1.0.0+` - please file a new issue
