### ISSUE TITLE
accounts:balance not work when rpc tcp is enabled

### ISSUE THREAD

**Issue by gzivdo** [iron-fish/ironfish#1535]
### What happened?

I changed 2 config values:
ironfish  config:set rpcTcpHost 0.0.0.0
ironfish  config:set enableRpcTcp true
then accounts balance does not work

### Version

0.1.35

### Debug output

```shell
ironfish accounts:balance 
No route found account/getBalance in namespace account for method getBalance
```

### Graffiti

ar2Obyahain

**Comment by gzivdo** [comment]
and other "accounts:" commands not work too, including deposit

**Comment by zbretta** [comment]
Pass to start instead:
```
ironfish start --rpc.tcp --rpc.tcp.host=0.0.0.0
```

**Comment by gzivdo** [comment]
same, should i remove from config those settings?

**Comment by gzivdo** [comment]
removed, kept only cmd parameters. but this is a bug in any case

**Comment by wd021** [comment]
@gzivdo its expected behavior. accounts and config routes are not available over TCP unless rpcTcpSecure is enabled. you need to run `ironfish config:set rpcTcpSecure true`.

**Comment by hairtail** [comment]
Account related routes are not mounted when you connection via tcp.
