### ISSUE TITLE
Feature Request: deposit should be possible without running node on the miner instance

### ISSUE THREAD

**Issue by gzivdo** [iron-fish/ironfish#1538]
### Description

Need to make deposit command independable from node, like public api gateways. possibly gateways runners should get testnet reward too. in case of mining in pool or via rpc with separate key its impossible now to make deposit from miner address/key. 
or at least allow deposit using remote node via rpc

**Comment by lwisne** [comment]
This should be possible. You can run the node with rpc.tcp functionality that allows remote commands. Is this not what you're looking for?

**Comment by hughy** [comment]
Closing as stale
