### ISSUE TITLE
Wrong Miners Count (DISCORD)

### ISSUE THREAD

**Issue by Masternode24** [iron-fish/ironfish#1539]
### What happened?

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/81598429/170909815-7f4987f0-d210-4491-ad86-036f3363aa08.png">

Hi Team,

i have setup ironfish discord hook for our small internal pool.
We have just 4 our nodes (miners).
We found 1 block in few hours.
I can see on the screenshot that we have 13 miners (TOTAL)! Its wrong info. Please investigate and confirm as BUG for us!

BR,
Masternode24.de

### Version

0.35

### Graffiti

Masternode24.de

**Comment by lwisne** [comment]
We haven't seen this issue with other pool (including our own). Going to close for now.
