### ISSUE TITLE
[issue name]

### ISSUE THREAD

**Issue by zubastik096** [iron-fish/ironfish#1548]
### What happened?

My transaction was not found:(https://explorer.ironfish.network/transaction/8401831c3b685d3dbb416e9ee1bdffd9c8520512624b5eae0ade677c6bf10702

### Version

0.1.34

### Debug output

```shell
Depositing $IRON 0.10000000 ($ORE 10,000,000) from default
Transaction Hash: 8401831c3b685d3dbb416e9ee1bdffd9c8520512624b5eae0ade677c6bf10702
Transaction fee: $IRON 0.00000001 ($ORE 1)

Find the transaction on https://explorer.ironfish.network/transaction/8401831c3b685d3dbb416e9ee1bdffd9c8520512624b5eae0ade677c6bf10702 (it can take a few minutes before the transaction appears in the Explorer)
```

### Graffiti

zippo

**Comment by mat-if** [comment]
Thanks for reporting - looks like our deposit syncer got stuck. Pending fix PR: https://github.com/iron-fish/ironfish-api/pull/863

Going to close since this is technically an API issue and not a node issue and fix will be out shortly

**Comment by zubastik096** [comment]
Transaction not found
