### ISSUE TITLE
rescan can be executed but directly go to completed if it met node shut down during the last rescan

### ISSUE THREAD

**Issue by hellogit2021** [iron-fish/ironfish#1556]
### What happened?

rescan can be executed but directly go to completed if it met node shut down during the last rescan
1.run ironfish start  -> make sure sync completed
2.run ironfish accounts:rescan  ->wait till it start scaning
3.shut down the node ->IMPORTANT, WHEN NODE DOWN, NO MATTER BY HAND OR OTHER REASONS
4.we will  see the rescan terminal shows the rescan completed
5.run ironfish start
6.run ironfish accounts:rescan  --> we will see it completed in 1 seconds, acctually it did nothing!****

### Debug output

```shell
$ /root/ironfish/node_modules/.bin/ironfish accounts:rescan --reset --local
Rescanning Transactions... Scanning Complete
Done in 0.72s.
```

### Relevant log output

```shell
$ /root/ironfish/node_modules/.bin/ironfish accounts:rescan --reset --local
Rescanning Transactions... Scanning Complete
Done in 0.72s.
```

### Graffiti

fatgeek

**Comment by hughy** [comment]
We've made significant changes to the wallet since this issue was created. Please create a new issue if you've run into this again on a more recent version. Thanks!
