### ISSUE TITLE
"Another node is using the database, waiting for that node to close.",but no other node is running at the same machine

### ISSUE THREAD

**Issue by hellogit2021** [iron-fish/ironfish#1561]
### What happened?

when reboot the node, get error message: Another node is using the database, waiting for that node to close.
tried:
1.ps -ef | grep ndoe  -->no other node is running
2.reboot machine --->not work
3.delete the LOCK file under 3 directories accounts/databases/indexes  -->not work

only delete the whole databases folder or execute the node reset  can solve this problem,but that will cause grealy time cost re-sync job

### Version

0.1.35

### Debug output

yarn run v1.22.15
$ yarn build && yarn start:js debug
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run debug
Database in use, skipping output that requires database.
Stop the node and run the debug command again to show full output.

Iron Fish version       0.1.35 @ src
Iron Fish library       0.0.13 @ src
Operating system        Linux x64
CPU model(s)                   Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz
CPU threads             12
RAM total               15.97 GiB
Node version            v16.15.0
ironfish in PATH        true
Telemetry enabled       true
Done in 19.32s.

### Relevant log output

yarn run v1.22.15
$ yarn build && yarn start:js start
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run start

::::::::::          :::::::::::::::::
::::::::::::       :::::::::::::::::::
:::::::::::::     :::::::::::::::::::::
::::::::::::::   ::::::::::::::::::::::::
 ::::::::::::: ::::::::::        :::::::::
   :::::::::::::::::::::          ::::::::::
   :::::::::::::::::::::          :::::::::
 ::::::::::::: ::::::::::        :::::::::
::::::::::::::   ::::::::::::::::::::::::
:::::::::::::     :::::::::::::::::::::
::::::::::::       :::::::::::::::::::
::::::::::           ::::::::::::::::

Version       0.1.35 @ src
Node Name     *****node
Graffiti     *****
Peer Identity kKArrgF9BO/8HNeKVP+vq1QEFxfjBxIDu4dXvmQ4ol8=
Peer Agent    ironfish/0.1.35/src
Peer Port     9033
Bootstrap     test.bn1.ironfish.network

Another node is using the database, waiting for that node to close.

### Graffiti

fatgeek[](url
![error](https://user-images.githubusercontent.com/88391197/171551322-716c7274-4b4f-4c11-beb6-39f9a046d35d.png)
)

**Comment by lwisne** [comment]
maybe a lock file that didn't get properly cleaned up?

**Comment by aminazeb** [comment]
@hellogit2021 You can try rebooting. It mostly works.
