### ISSUE TITLE
 Why not deposit？？？？？？？？？？？？？？？？

### ISSUE THREAD

**Issue by HanHanPecan** [iron-fish/ironfish#1562]
### Description

yarn run v1.22.10
$ yarn build && yarn start:js deposit
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run deposit

You are about to send $IRON 0.10000000 ($ORE 10,000,000) plus a transaction fee of $IRON 0.00000001 ($ORE 1) to the Iron Fish deposit account.
Your remaining balance after this transaction will be $IRON 0.16159446 ($ORE 16,159,446).
The memo will contain the graffiti "pecan".

* This action is NOT reversible *
      
Do you confirm (Y/N)?: Y
Creating the transaction: [████████████████████████████████████████] 100% | ETA: 0s

Depositing $IRON 0.10000000 ($ORE 10,000,000) from pecan
Transaction Hash: 607a2a0159ef829aecd8301b1c1a121fe5e64a389938bc27da9113aa67d94756
Transaction fee: $IRON 0.00000001 ($ORE 1)

Find the transaction on https://explorer.ironfish.network/transaction/607a2a0159ef829aecd8301b1c1a121fe5e64a389938bc27da9113aa67d94756 (it can take a few minutes before the transaction appears in the Explorer)
✨  Done in 129.35s.

==========

Version              0.1.35 @ src
Node                 STARTED
Memory               Heap: 219.46 MiB / 251.73 MiB (87.2%), RSS: 914.13 MiB
(5.6%), Free: 168.40 MiB (99.0%)
P2P Network          CONNECTED - In: 189.04 KB/s, Out: 3.68 MB/s, peers 37  
Mining               STARTED - 0 miners, 0 mined
Mem Pool             16757 tx
Syncer               SYNCING - 0.27 blocks per seconds, avg time to add block
9870.96 ms, progress: 99.34% 
Blockchain           SYNCED @ HEAD 000000000003adc99cddc05d95031970e7056bcc6867b
94794349ac028d94485 (32626)
Telemetry            STOPPED
Workers              STARTED - 0 -> 2 / 6 - -0.84 jobs Δ, 33.62 jobs/s   

===========

It has been deposited many times, but after each success, the balance will be reduced temporarily. After a period of time, the balance will be restored, which means it cannot be deposited.

**Comment by lwisne** [comment]
You are likely running into network congestion + miners not picking up the transaction.

We are looking at ways to resolve, so you can easily transact and earn your points!

https://github.com/iron-fish/ironfish/issues/1879
