### ISSUE TITLE
Build code in armV7 platform (like pi or quark-N)  Cannot find module

### ISSUE THREAD

**Issue by kakathy** [iron-fish/ironfish#1567]
### Description

Output:
pi@Quark-N:~/ironfish/ironfish$ yarn test
yarn run v1.22.18
$ lerna run test
lerna notice cli v4.0.0
lerna info versioning independent
lerna info Executing command in 3 packages: "yarn run test"
lerna info run Ran npm script 'test' in 'eslint-plugin-ironfish' in 121.4s:
$ node index.test.js
lerna ERR! yarn run test exited 1 in '@ironfish/sdk'
lerna ERR! yarn run test stdout:
$ tsc -b && tsc -b tsconfig.test.json && jest
jest-haste-map: Haste module naming collision: @ironfish/sdk
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/package.json
    * <rootDir>/build/package.json

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run test stderr:
FAIL @ironfish/sdk src/merkletree/merkletree.test.ts
  ● Test suite failed to run

    Cannot find module '@ironfish/rust-nodejs-linux-arm-gnueabihf' from '../ironfish-rust-nodejs/index.js'

    Require stack:
      /home/pi/ironfish/ironfish/ironfish-rust-nodejs/index.js
      jest.setup.env.js

      216 |             nativeBinding = require('./ironfish-rust-nodejs.linux-arm-gnueabihf.node')
      217 |           } else {
    > 218 |             nativeBinding = require('@ironfish/rust-nodejs-linux-arm-gnueabihf')
          |                             ^
      219 |           }
      220 |         } catch (e) {
      221 |           loadError = e

      at Resolver.resolveModule (../node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (../ironfish-rust-nodejs/index.js:218:29)

code  index.js like this

case 'arm':
        localFileExisted = existsSync(
          join(__dirname, 'ironfish-rust-nodejs.linux-arm-gnueabihf.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./ironfish-rust-nodejs.linux-arm-gnueabihf.node')
          } else {
            nativeBinding = require('@ironfish/rust-nodejs-linux-arm-gnueabihf')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
break

I think ironfish support arm, so how to get @ironfish/rust-nodejs-linux-arm-gnueabihf

I found those rust-nodejs bleow :
[https://libraries.io/search?q=ironfish](https://libraries.io/search?q=%40iron-fish)

Help me ,Thks

**Comment by holahula** [comment]
Closing due to staleness. If the issue persists in versions `1.0.0+` - please file a new issue
