### ISSUE TITLE
[Bug] Total balance and available balance of mining pool address

### ISSUE THREAD

**Issue by Fow1088** [iron-fish/ironfish#1576]
### Description

Several times I tried different settings of basic mining pool on different machines and noticed few types of problems with balance : 1) Pool is mining in fork, but doesn’t admit it and shows Available balance, which includes coins from fork, which always results in “insufficient funds” error, but you can’t get the problem for quite a long time due to the reason Total and Available balances shows same numbers and seems to be fine; 2) Pool finds block sometimes in the fork, sometimes in canonical chain and Total Balance is much more, then Available which is also confusing. For example, mining pool, which found 20 blocks has a total balance of 400, but Available is 220 , because 9 blocks are not in canonical chain; 3) Mining Pool payouts. Basically problem comes from balance issues and if you play with poolBalancePercentPayout setting and puts the number higher, thEn default (10) payouts most of the time either don’t work at all with “insufficient balance” error or doesn’t payout correct number. For example, I have 40 miners connected, Total Balance and Available Balance of 100 IRON with 10% payout and payout works and distributed proportionally using 10 IRON. When I tried the same, but with 50, 40, 90, 85 and all other numbers amount distributed was totally incorrect ( with 80% setting it distributed not 80 IRON , but somehow 0.275 IRON) or “insufficient balance” error

**Comment by lwisne** [comment]
Thanks for the feedback. The payout issue should be fixed, the rest is still outstanding.

**Comment by Fow1088** [comment]
Thanks for your email! Hope this will help! Trying to figure out how to fix
something beside just reporting , but it’s quite tough for me, I’m web
developer)

**Comment by aminazeb** [comment]
@lwisne @Fow1088 Does the issue still persist?

**Comment by hughy** [comment]
We've made significant changes to the wallet since this issue was created. If you encounter similar issues, please open a new issue. Thanks!
