### ISSUE TITLE
"-2 hour until next reward" error is back in Leaderboard User Page on v 0.1.36 on 6jun22

### ISSUE THREAD

**Issue by crProductGuy** [iron-fish/ironfish#1588]
### What happened?

Accessed my leaderboard page, got the -hours error again

https://testnet.ironfish.network/users/213

![IronFish User Page again shows '-2 hour till next reward', a few hours after release of ver 0 1 36 on 2022-06-06 at 7 47 53 PM](https://user-images.githubusercontent.com/95465010/172285271-8ad6c18f-2198-461d-9a54-4525bf4f926c.png)

### Version

0.1.36

### Debug output

```shell
N/A - this is visible on the Testnet User page.
```

### Relevant log output

```shell
N/A - see user page
```

### Graffiti

ProductGuy

**Comment by wd021** [comment]
should be good now :)
