### ISSUE TITLE
Miner shows block submitted successfully even through its on a fork

### ISSUE THREAD

**Issue by Zvix123** [iron-fish/ironfish#1596]
### What happened?

Miner shows block submitted successfully even though its on a fork.
![F9B5E4B8-478D-4EB2-87BD-99F3122E37BE](https://user-images.githubusercontent.com/84890591/172629927-4e23bbb5-1bc0-4ae4-8046-fa1738698d51.jpeg)
![DEDBD4C7-22A8-4A93-A5F2-4D401B8F340A](https://user-images.githubusercontent.com/84890591/172629938-fabbaec2-bd9f-4e2d-87e9-dfc2ce472fc3.jpeg)

### Version

0.1.36

### Graffiti

zviki

**Comment by lwisne** [comment]
This is a bit misleading, but the miner doesn't know if the block is on a fork at the time it is accepted. There's not an obviously better way to do it?
