### ISSUE TITLE
Transaction result is Success, but in real it's not

### ISSUE THREAD

**Issue by justmml** [iron-fish/ironfish#1603]
### What happened?

Transaction can fail, but result will be Success, even Transaction Hash and transaction link are generated.

Hardware:
CPU: 4 core AMD EPYC 7282
RAM: 8 Gb
OS: Ubuntu 20.04

Steps to reproduce:
1. Try to make 3-4 transactions using `ironfish deposit` command without ironfishd service restarting

Result: 3d or 4th transaction and next will be not successful, balance after failed transactions **does not decrease**
Expected result: all transactions are successful

Hint: restarting ironfishd service after every 2-3 transactions helps to make successful transactions

### Version

v0.1.36

### Debug output

```shell
Iron Fish version       0.1.36 @ src
Iron Fish library       0.0.14 @ src
Operating system        Linux x64
CPU model(s)            AMD EPYC 7282 16-Core Processor
CPU threads             4
RAM total               7.77 GiB
Node version            v16.15.1
ironfish in PATH        true
Telemetry enabled       true
```

### Relevant log output

```shell
yarn run v1.22.18 ironfish deposit
$ yarn build && yarn start:js deposit
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run deposit

You are about to send $IRON 0.10000000 ($ORE 10,000,000) plus a transaction fee of $IRON 0.00000001 ($ORE 1) to the Iron Fish deposit account.
Your remaining balance after this transaction will be $IRON 1.09911069 ($ORE 109,911,069).
The memo will contain the graffiti "mml_node".

* This action is NOT reversible *

Do you confirm (Y/N)?: Y
Creating the transaction: [████████████████████████████████████████] 100% | ETA: 0s

Depositing $IRON 0.10000000 ($ORE 10,000,000) from mml_wallet
Transaction Hash: 7d063bd3f0c71dfc529762e3531f31cc888ab29f07901fd41ae4dd82f0bd45f8
Transaction fee: $IRON 0.00000001 ($ORE 1)

Find the transaction on https://explorer.ironfish.network/transaction/7d063bd3f0c71dfc529762e3531f31cc888ab29f07901fd41ae4dd82f0bd45f8 (it can take a few minutes before the transaction appears in the Explorer)
Done in 1575.37s.
```

### Graffiti

mml_node

**Comment by mat-if** [comment]
Hi @justmml thanks for reporting,

I'm going to go ahead and link to the same reply I gave to an issue with the same report. https://github.com/iron-fish/ironfish/issues/1628#issuecomment-1157003421
