### ISSUE TITLE
account balance shows zero after import

### ISSUE THREAD

**Issue by msa6867** [iron-fish/ironfish#1612]
### What happened?

On May 25 I exported the account shown below; account balance was approximately 5.88 $IRON.  Thereafter I stopped ironfish (v0.1.32).  On May 26 I started ironfish (v0.1.35) on a new computer and imported my account.  Upon import account showed a zero balance.  After several days, the correct amount eventually  showed

{
   "name": "msa6867",
   "spendingKey": "ba08767fcfd7fe8dac00220af41da89954a42218a90ed0c2d43d670a46fe0c24",
   "incomingViewKey": "4f39480898a0cc3228c9ace07776a3b4dc93e5129648790a5ccb7229ccd02b04",
   "outgoingViewKey": "6ceb3fb0a07f92d1f945584f797fe50b40f29d1704f70bc486317bfe5503d7a5",
   "publicAddress": "fcf77bf384221f25ae90583dc62ade76f43b5c5bfb8403b0a636c7f2d663eecab45a3ff2272a1b7c8da665",
   "rescan": null
}

### Version

v0.1.35

### Debug output

```shell
Iron Fish version            0.1.35 @ 4bc3765
Iron Fish library            0.0.13 @ 4bc3765
Operating system             Windows_NT x64
CPU model(s)                 AMD Ryzen 9 5950X 16-Core Processor
CPU threads                  32
RAM total                    31.92 GiB
Node version                 v16.15.0
ironfish in PATH             true
Telemetry enabled            true
Accounts head hash
Accounts head in chain       false
Accounts head sequence       null
```

### Graffiti

msa6867

**Comment by mat-if** [comment]
Hi @msa6867, thanks for reporting.

When you first imported, had you already synced the node on the new computer? I suspect what happened is that you imported the account prior to fully syncing, which means that your new node did not yet know about the blocks that contained the transactions that resulted in your 5.88 $IRON.

For example: the current block is `52303` according to the block explorer. Let's say I send you 1 $IRON right now, this transaction would probably get picked up in block 52304, let's say for the sake of this example.

If you have a node who has only synced up to, example, block 50,000, your node would not have knowledge of this transaction. Once it synced to 52304, your balance would then reflect the 1 $IRON I sent you.

I'm going to close this, but feel free to re-open or comment if this is not the case

**Comment by msa6867** [comment]
yes I was already synced.  However, since I have no way to reproduce this
event I understand that there may be nothing that can be done except to
close this
