### ISSUE TITLE
memory leak when depositing

### ISSUE THREAD

**Issue by gzivdo** [iron-fish/ironfish#1616]
### What happened?

A bug happened!
![изображение](https://user-images.githubusercontent.com/13568002/173186178-2a560e5f-4b06-4596-b85c-3202e5c60e62.png)
![изображение](https://user-images.githubusercontent.com/13568002/178006522-40a771bb-512b-4285-bd1b-a11187eb4383.png)

discharges on the graph is a node restart

### Version

0.1.36
0.1.37

### Graffiti

ar2Obyahain

**Comment by lwisne** [comment]
Duplicate of https://github.com/iron-fish/ironfish/issues/1925
