### ISSUE TITLE
ironfish accounts:balance

### ISSUE THREAD

**Issue by 76Valeriy** [iron-fish/ironfish#1617]
### What happened?

Balance is not displayed

yarn run v1.22.19
$ yarn build && yarn start:js accounts:balance
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run accounts:balance
All decryptable notes should be in the noteToNullifier map

### Version

Iron Fish version       0.1.36 @ src

### Debug output

```shell
Iron Fish version       0.1.36 @ src
Iron Fish library       0.0.14 @ src
Operating system        Linux x64
CPU model(s)            AMD Ryzen 9 5950X 16-Core Processor
CPU threads             32
RAM total               125.72 GiB
Node version            v16.15.1
ironfish in PATH        true
Telemetry enabled       true
```

### Graffiti

xironfishnode

**Comment by mat-if** [comment]
Hi @76Valeriy, did this just start happening when you reported the issue? Was it working correctly before that, or was this the first time you checked it?

**Comment by 76Valeriy** [comment]
Hi there was no such error before, the problem was solved as follows

systemctl stop ironfishd
ironfish accounts:rescan --reset
systemctl restart ironfishd

It hasn't happened yet

чт, 16 июн. 2022 г. в 01:46, mat-if ***@***.***>:
