### ISSUE TITLE
inconsistent implementation of fees ($IRON vs $ORE)

### ISSUE THREAD

**Issue by msa6867** [iron-fish/ironfish#1638]
### Description

Not a bug per se, but it is rather confusing and lendsd to manual entry errors in filling out transactions for the fee parameter in "Deposit" to be denominated in $ORE and for the fee parameter in accounts:pay (on which "deposits" is built) to be denominated in $IRON.  I suggest changing this to be consistent; preferrably by changing the accounts:pay fee parameter to denote $ORE not $IRON

**Comment by lwisne** [comment]
I would agree with this assessment. If anything, it's annoying to have to type a bunch of leading zeros to denominate small amounts of $IRON

**Comment by aminazeb** [comment]
I have started working on it. @lwisne 
@msa6867 On which version did you face this issue?

**Comment by msa6867** [comment]
This has been an attribute from the earlies versions.  As @lwisne said, it is an annoyance, not so much an "issue"

**Comment by hughy** [comment]
The `deposit` command has been removed after the end of the Phase 2 Testnet. We'll be sure to use consistent units if we add another command!
