### ISSUE TITLE
transaction hash generated on rejected transaction

### ISSUE THREAD

**Issue by msa6867** [iron-fish/ironfish#1640]
### What happened?

Doing a series of tests on race conditions.  Sent two transaction from same account to other accounts controlled by me from separate CLI windows within a fraction of a second from each other.  There were adequate funds in cover both transaction.  First to finish was added to blockchain and immediately displayed correct value in "to" wallet and **eventually* (see #1639) showed correct balance in "from" account.  The second to finish generated transaction hash as if it finished correctly, but did not get added to block chain and did not cause a credit to "to account or debit from "from" account.  Either the rejection of the second transaction is expected behavior , in which case the pay feedback results ought not display results that indicate a successful transaction, or the failure to add the second transaction to the block is unexpected behavior, since there were adequate funds to complete the transaction

### Version

v0.1.36

### Debug output

```shell
Iron Fish version            0.1.36 @ 6dfc736
Iron Fish library            0.0.14 @ 6dfc736
Operating system             Windows_NT x64
CPU model(s)                 AMD Ryzen 9 5950X 16-Core Processor
CPU threads                  32
RAM total                    31.92 GiB
Node version                 v16.15.0
ironfish in PATH             true
Telemetry enabled            true
Accounts head hash           000000000003df967a30cee4e86e225b87a9bcb513359b0bd47f4278d1604246
Accounts head in chain       true
Accounts head sequence       48017
```

### Relevant log output

```shell
C:\Users\Mark>ironfish accounts:pay -f msa6867 -a 0.20000001 -t f5e319d0e98a6edbbb32365b930de9da98a80d08ba914c72c0edc5dfd2e890a235d5f0e266d2433f71e75e -o 1

You are about to send:
$IRON 0.20000001 ($ORE 20,000,001) plus a transaction fee of $IRON 1.00000000 ($ORE 100,000,000) to f5e319d0e98a6edbbb32365b930de9da98a80d08ba914c72c0edc5dfd2e890a235d5f0e266d2433f71e75e from the account msa6867

* This action is NOT reversible *

Do you confirm (Y/N)?: y
Creating the transaction: [████████████████████████████████████████] 100% | ETA: 0s

Sending $IRON 0.20000001 ($ORE 20,000,001) to f5e319d0e98a6edbbb32365b930de9da98a80d08ba914c72c0edc5dfd2e890a235d5f0e266d2433f71e75e from msa6867
Transaction Hash: ecdb5d4455f4e2cd207cc15d460fe3bb80e55d24fa94ac3c748683d76dfebd60
Transaction fee: $IRON 1.00000000 ($ORE 100,000,000)

Find the transaction on https://explorer.ironfish.network/transaction/ecdb5d4455f4e2cd207cc15d460fe3bb80e55d24fa94ac3c748683d76dfebd60 (it can take a few minutes before the transaction appears in the Explorer)
```

### Graffiti

msa6867

**Comment by lwisne** [comment]
The feedback in the CLI does not refer to it as a "successful transaction". The wording could still be clearer, but that's important to note.

Think the only action here may be to better explain the transaction process in the CLI after creation. But I think having some level of clarity for the most common case may be more important than using very generic language that will account for cases in which someone is trying to spend the same notes simultaneously from different terminals. So for now, we will keep as is.
