### ISSUE TITLE
Unexpected results during race condition with insufficient funds

### ISSUE THREAD

**Issue by msa6867** [iron-fish/ironfish#1641]
### What happened?

Attempted simultaneous deposit transaction from different CLI windows from wallet containing $0.20000001. Fee=$ORE 1 for both transactions. ( from account msa6867test1 "publicAddress": "d0ed10a23510f66f14316ca1aebd973319d4b6b5b726e787b718ed58f16387bfb072ffa3b8b875f99de5ca")

Expected result would be for first to be submitted (assuming equal fee structure) to be accepted and other to be rejected for insufficient funds. 

Results: the second submitted deposit completed first and was added to the blockchain and (eventually) resulted in proper debit from my from account.  The first-submitted completed a fraction of a second later and generated a transaction hash as if it completed, but was (correctly) not added to blockchain and did not get debited from account.

Following this, a balance query returned  value $0.30000001.  (expected value was $0.10000000) This is a very striking result (the addition of $Iron 0.1 to the pre-deposit value and a departure from the usual psuedo-jibberish that dominates most wrong balance query results.  This particular signature may help in locating the source of a balance-query bug.

Following this, a new deposit was attempted.  Command passed preliminary check but ultimately (correctly) generated an error due to insufficient funds.  

This new deposit transaction seemed to trigger accounts:balance to reconcile to proper value ($IRON 0.1) and a subsequent deposit attempt was rejected at the preliminary level

summary: the actual blockchain behaves correctly under this race condition, however (1) second-to-finish deposit ought to have generated insufficient fund error rather than to return output indicating successful transaction (2) incorrect result to balance query has unique signature that should aid debugging and is most likely a separate issue from the other wrong-balance bugs previously reported. (3) not a bug per-se as there are all sort of unknown variables, but for same fee structure and submitted over the same network, it is somewhat surprising that the second-submitted deposit finished first

### Version

v0.1.36

### Debug output

```shell
Iron Fish version            0.1.36 @ 6dfc736
Iron Fish library            0.0.14 @ 6dfc736
Operating system             Windows_NT x64
CPU model(s)                 AMD Ryzen 9 5950X 16-Core Processor
CPU threads                  32
RAM total                    31.92 GiB
Node version                 v16.15.0
ironfish in PATH             true
Telemetry enabled            true
Accounts head hash           000000000003df967a30cee4e86e225b87a9bcb513359b0bd47f4278d1604246
Accounts head in chain       true
Accounts head sequence       48017
```

### Relevant log output

```shell
Mark Abinante <markabinante@gmail.com>
9:52 AM (52 minutes ago)
to me

C:\Users\Mark>ironfish deposit -a msa6867test1 --confirm
Creating the transaction: [████████████████████████████████████████] 100% | ETA: 0s

Depositing $IRON 0.10000000 ($ORE 10,000,000) from msa6867test1
Transaction Hash: 0a2a179e4a033dc65698511e757d2c825121cb4e13df53a8d2ccfcf66529e266
Transaction fee: $IRON 0.00000001 ($ORE 1)

Find the transaction on https://explorer.ironfish.network/transaction/0a2a179e4a033dc65698511e757d2c825121cb4e13df53a8d2ccfcf66529e266 (it can take a few minutes before the transaction appears in the Explorer)

C:\Users\Mark>ironfish deposit -a msa6867test1 --confirm
Creating the transaction: [████████████████████████████████████████] 100% | ETA: 0s

Depositing $IRON 0.10000000 ($ORE 10,000,000) from msa6867test1
Transaction Hash: 498d07cead9657072bd05730af99686ecc96b616c122d1f9e5f0357d311cbb52
Transaction fee: $IRON 0.00000001 ($ORE 1)

Find the transaction on https://explorer.ironfish.network/transaction/498d07cead9657072bd05730af99686ecc96b616c122d1f9e5f0357d311cbb52 (it can take a few minutes before the transaction appears in the Explorer)

C:\Users\Mark>ironfish accounts:balance msa6867test1
Account - msa6867test1 (eba55ac)

The balance is: $IRON 0.30000001 ($ORE 30,000,001)
Amount available to spend: $IRON 0.30000001 ($ORE 30,000,001)

C:\Users\Mark>ironfish deposit -a msa6867test1 --confirm
Creating the transaction: [████████████████████████████████████████] 100% | ETA: 0s
An error occurred while sending the transaction.
 »   Error: Request failed (400) error: Insufficient funds

C:\Users\Mark>ironfish deposit -a msa6867test1 --confirm
Insufficient balance: 0.1. Required: 0.10000001

C:\Users\Mark>ironfish accounts:balance msa6867test1
Account - msa6867test1 (eba55ac)

The balance is: $IRON 0.10000000 ($ORE 10,000,000)
Amount available to spend: $IRON 0.10000000 ($ORE 10,000,000)
```

### Graffiti

msa6867

**Comment by hughy** [comment]
We've made significant changes to the wallet since this issue was created. Please create a new issue if you've run into this again on a more recent version. Thanks!
