### ISSUE TITLE
ironfish node module causes Permission Denied error during subsequent `yarn global add ...` commands

### ISSUE THREAD

**Issue by MichaelxhJiang** [iron-fish/ironfish#1650]
## System

OS: Windows 11
CPU: Intel i7-11700F

## Steps
I installed ironfish using

`yarn global add ironfish`

However, subsequent global package installations with `yarn global add ...` results in an error

```
An unexpected error occurred: "EPERM: operation not permitted, unlink 'C:\\Users\\<user>\\AppData\\Local\\Yarn\\Data\\global\\node_modules\\.bin\\ironfish
```

The permissions for this package are:

```
$ ls -l AppData/Local/Yarn/Data/global/node_modules/.bin
total 1
-rw-r--r-- 1 <user>197609 303 Jun 11 14:18 ironfish
```

which causes the permission issue.

I even tried changing the permissions of this module as a root user but failed:
```
chmod: changing permissions of 'AppData/Local/Yarn/Data/global/node_modules/.bin/ironfish': Permission denied
```

This causes a major inconvenience to my global yarn environment.

**Comment by lwisne** [comment]
We recommend using `npm` to install, or to closely follow the install the repo's install guidelines (in this case, you don't do a global install)
