### ISSUE TITLE
syn error

### ISSUE THREAD

**Issue by kakathy** [iron-fish/ironfish#1661]
### Description

/home/leon/.npm-global/lib/node_modules/ironfish/node_modules/levelup/lib/levelup.js:190
        err = new ReadError(err)
              ^
Error [ReadError]: Corruption: bad entry in block
    at /home/leon/.npm-global/lib/node_modules/ironfish/node_modules/levelup/lib/levelup.js:190:15 {
  [cause]: undefined
}

**Comment by lwisne** [comment]
duplicate of https://github.com/iron-fish/ironfish/issues/1662
