### ISSUE TITLE
Issue 1: Two `ironfish deposit` txns on 18jun22 do not appear in block explorer via link or hash, 2) Graffiti doesn't show past TXNs in explorer

### ISSUE THREAD

**Issue by crProductGuy** [iron-fish/ironfish#1667]
I wonder if the default 1 ORE miner's fee is sometimes still insufficient.

After syncing a new node computer, I ran 2 `ironfish deposit` txns on Sat 18 June. They did not appear in the explorer within a few hours, and still are missing on Wed 22 June.

Links are:

https://explorer.ironfish.network/transaction/0debccd4fb6c6f34a909f9cec4e399735af7e5b425344aadf5f905b1a8182e65

returns:
Transaction not found
It looks like the transaction has sunk to the depths of the ocean...or we just can’t find it at this time.

Pasting the hash below into the explorer shows `No matches` in the Explorer search bar
0debccd4fb6c6f34a909f9cec4e399735af7e5b425344aadf5f905b1a8182e65

TXN log on PC:
Saturday, June 18, 2022 10:25:15 PM
depositing
Creating the transaction: [████████████████████████████████████████] 100% | ETA: 0s

Depositing $IRON 0.10000000 ($ORE 10,000,000) from default
Transaction Hash: 0debccd4fb6c6f34a909f9cec4e399735af7e5b425344aadf5f905b1a8182e65
Transaction fee: $IRON 0.00000001 ($ORE 1)

Find the transaction on https://explorer.ironfish.network/transaction/0debccd4fb6c6f34a909f9cec4e399735af7e5b425344aadf5f905b1a8182e65 (it can take a few minutes before the transaction appears in the Explorer)
sleeping-60-sec
loopi
date+time
Saturday, June 18, 2022 11:15:54 PM

Note the TXN took 45 min to run.

Machine = cheap HP 14 laptop with 2-core 3GHz Athlon Silver 
Windows 10 (latest), 
Installed Iron Fish 0.1.36 with `npm` 

=-=-=-=-

2nd TXN soon after that, (in a deposit loop script)

Same result: Txn not found after pasting link in browser, hash not found in Block Explorer

Saturday, June 18, 2022 11:15:54 PM
depositing
Creating the transaction: [████████████████████████████████████████] 100% | ETA: 0s

Depositing $IRON 0.10000000 ($ORE 10,000,000) from default
Transaction Hash: 84503e8020c7e5e60d128a0f8b4773c937f00a5e76d8b2ebda432ccdcc59137b
Transaction fee: $IRON 0.00000001 ($ORE 1)

Find the transaction on https://explorer.ironfish.network/transaction/84503e8020c7e5e60d128a0f8b4773c937f00a5e76d8b2ebda432ccdcc59137b (it can take a few minutes before the transaction appears in the Explorer)

-=-=-
Separate issue (noticed 22jun22)

Also, oddly, putting my graffiti (ProductGuy) in the Block Explorer shows no txns found ("No Matches"), whereas I made several deposits a few weeks ago earlier in Phase 2 and I have 560 points in my page in the leaderboard:

https://testnet.ironfish.network/users/213

Graffiti = "ProductGuy"

My most recent successful transaction (and the newest I have attempted except for the 2 above) was from 4jun22:
50b5ab430672df95ff7a361cfb2ef7df91fcbdcd79c7128270271aff2f3c5108

 - it does show up in both explorer.ironfish.network and in my Leaderboard page (213).
 -

**Comment by lwisne** [comment]
Similar bug as https://github.com/iron-fish/ironfish/issues/1672

Looks like there may be a few days in which we weren't rewarding points correctly.

**Comment by holahula** [comment]
Closed - testnet is over
