### ISSUE TITLE
[Bug] found block, but not showing in nodes

### ISSUE THREAD

**Issue by joe83** [iron-fish/ironfish#1679]
### What happened?

I found block on my private pool, got reports in discord
Block 000000000004a9c8354fdb13d6a0594e0e8733a4249a449324210d2932c7bcf4

Check in explorer, it's a valid block.

But in the nodes, the block not showing. And the balance not increase. 

![Screenshot_20220627-083728_Discord](https://user-images.githubusercontent.com/10484058/175846022-413375b3-e700-46dd-ae8b-250f8f44246b.jpg)

![Screenshot_20220627-083742_Chrome](https://user-images.githubusercontent.com/10484058/175846067-4f76b9f0-cdf1-4167-a0d8-086e5d72e0ca.jpg)

![Screenshot_20220627-083658_Termius](https://user-images.githubusercontent.com/10484058/175846090-2c96cac3-3d8e-4246-9786-1a521fda3cfc.jpg)

My graffiti : Oredox

### Version

0.1.36

### Debug output

```shell
Iron Fish version            0.1.36 @ src
Iron Fish library            0.0.14 @ src
Operating system             Linux x64
CPU model(s)                 AMD EPYC Processor
CPU threads                  8
RAM total                    15.26 GiB
Node version                 v16.15.1
ironfish in PATH             true
Telemetry enabled            true
Accounts head hash           000000000007d088a31ff79c3a291894b660fef5d62ab8002e1cee813b3110cd
Accounts head in chain       true
Accounts head sequence       67557
```

### Graffiti

Oredox

**Comment by wd021** [comment]
could be that your account head sequence is at `67557` and the mined block is at `68257`.

is this still not showing?

**Comment by lwisne** [comment]
This block exists, looks like you just weren't synced.
