### ISSUE TITLE
The problem with the balance on deposit

### ISSUE THREAD

**Issue by Jokersonchik** [iron-fish/ironfish#1692]
### What happened?

When making a deposit, the available balance disappears for a while. maybe after the first deposit, or maybe after several, this will appear.

### Version

0.1.36 @ src

### Debug output

```shell
root@Jokersonchik:~# ironfish debug
yarn run v1.22.19
$ yarn build && yarn start:js debug
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run debug
Database in use, skipping output that requires database.
Stop the node and run the debug command again to show full output.

Iron Fish version       0.1.36 @ src
Iron Fish library       0.0.14 @ src
Operating system        Linux x64
CPU model(s)            Common KVM processor
CPU threads             6
RAM total               5.80 GiB
Node version            v16.15.1
ironfish in PATH        true
Telemetry enabled       true
Done in 3.50s.
```

### Relevant log output

```shell
root@Jokersonchik:~# ironfish accounts:balance $IRONFISH_WALLET
yarn run v1.22.19
$ yarn build && yarn start:js accounts:balance Jokersonchik
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run accounts:balance Jokersonchik
Account - Jokersonchik (a28b975)

The balance is: $IRON 4.40000044 ($ORE 440,000,044)
Amount available to spend: $IRON 4.40000044 ($ORE 440,000,044)
Done in 5.38s.
root@Jokersonchik:~# ironfish deposit --confirm
yarn run v1.22.19
$ yarn build && yarn start:js deposit --confirm
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run deposit --confirm
Creating the transaction: [████████████████████████████████████████] 100% | ETA: 0s

Depositing $IRON 0.10000000 ($ORE 10,000,000) from Jokersonchik
Transaction Hash: e3ebb6a7930737deb039df7d85eb48320fc05470a065ae4347ed0fd02d7c649c
Transaction fee: $IRON 0.00000001 ($ORE 1)

Find the transaction on https://explorer.ironfish.network/transaction/e3ebb6a7930737deb039df7d85eb48320fc05470a065ae4347ed0fd02d7c649c (it can take a few minutes before the transaction appears in the Explorer)
Done in 9.80s.
root@Jokersonchik:~# ironfish accounts:balance $IRONFISH_WALLET
yarn run v1.22.19
$ yarn build && yarn start:js accounts:balance Jokersonchik
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run accounts:balance Jokersonchik
Account - Jokersonchik (a28b975)

The balance is: $IRON 4.30000043 ($ORE 430,000,043)
Amount available to spend: $IRON 0.00000000 ($ORE 0)
Done in 1.99s.
```

### Graffiti

Jokersonchik

**Comment by mat-if** [comment]
From what I can see here, it looks like it's working as expected. For an explanation of why you are seeing the spendable balance decrease, see the FAQ here https://github.com/iron-fish/ironfish/wiki/FAQ#phase-2-transaction-questions (quoted below)

> Q: I see insufficient balance errors when trying to send transactions quickly one after another. A: Transactions use something similar to the UTXO model in Bitcoin (but not the same). Think of it this way:

> You mine a block and you get a special $20 bill with all this cryptographic info inside.
You send $5 to an address using this special bill.
The $20 bill gets destroyed and then bills for $5 and $15 get created. Both have all the fancy cryptographic info inside as well.
To get your $15 bill back, the network has to confirm your transaction, which means that it has to verify that the cryptographic info is actually valid and then include that transaction in a mined block.
When all that happens, you will eventually receive the mined block with your transaction and your $15 bill will show up in your wallet. Then you will have sufficient funds.

> A2: More detailed explanation when you have multiple 20-iron "notes" in your account from mining 3 blocks:

> Lets say you mined 3 blocks, so your balance is 60 $IRON, which you received in 3 different transactions (creating 3 notes)
You deposit once, which would spend 0.1 IRON from one of those notes, which would make the entire 20 IRON note unspendable until the transaction is confirmed.
You now have a remaining available balance of 40 (but a total balance of ~59.9 once its confirmed and change is returned).
You could deposit again immediately, which would leave your available balance as 20 (but a total unconfirmed balance of ~59.8).
If you deposit one more time before the transactions are confirmed, you'd have 0 IRON available until your transactions are confirmed
    Which would result in an Insufficient Funds error if you tried to do ironfish deposit or ironfish send before confirmation.
