### ISSUE TITLE
Sync already in progress from ... possible parallel (duplicate) sync on v0.1.37 

### ISSUE THREAD

**Issue by crProductGuy** [iron-fish/ironfish#1700]
### What happened?

Seeing sync already in progress - interactions with multiple peers in parallel during re-sync after upgrading to 0.1.37 on 28jun

Log:
```
Version       0.1.37 @ 44a7990
Node Name     ProductGuy
Graffiti      ProductGuy
Peer Identity ALYSH4LhAtloS52ebqXpxobl7QHxInzFXyF46oT3LHY=
Peer Agent    ironfish/0.1.37/44a7990
Peer Port     9033
Bootstrap     test.bn1.ironfish.network

WebSocket server started at :::9033
Connected to the Iron Fish network
Starting sync from a9ySAoI (gnimaelglacinilc). work: +444772781722747, ours: 70907, theirs: 70930
Finding ancestor using linear search on last 3 blocks starting at 00000...0d3b7 (70907) from peer a9ySAoI (gnimaelglacinilc) at 70930
Found peer a9ySAoI (gnimaelglacinilc) ancestor 00000...0d3b7, syncing from 70907 -> 70930 (23) after 1 requests
Requesting 20 blocks starting at 00000...0d3b7 (70907) from a9ySAoI (gnimaelglacinilc)
Peer a9ySAoI (gnimaelglacinilc) disconnected (DISCONNECTED) while syncing.
Peer SVobFB+ (DanielMoon) sent orphan 00000...acfdc (70938)
Syncing orphan chain from SVobFB+ (DanielMoon)
Starting sync from SVobFB+ (DanielMoon). work: +578427489426598, ours: 70907, theirs: 70937
Finding ancestor using linear search on last 3 blocks starting at 00000...0d3b7 (70907) from peer SVobFB+ (DanielMoon) at 70937
Found peer SVobFB+ (DanielMoon) ancestor 00000...0d3b7, syncing from 70907 -> 70938 (31) after 1 requests
Requesting 20 blocks starting at 00000...0d3b7 (70907) from SVobFB+ (DanielMoon)
Peer SVobFB+ (DanielMoon) sent orphan 00000...2d83f (70936)
Sync already in progress from SVobFB+ (DanielMoon)
Peer lEPhW0g (SnowyPeaks) sent orphan 00000...759a1 (70937)
Sync already in progress from SVobFB+ (DanielMoon)
Peer a9ySAoI (gnimaelglacinilc) sent orphan 00000...9109f (70936)
Sync already in progress from SVobFB+ (DanielMoon)
Peer pEZeP3n (tetsugyo) sent orphan 00000...c56ae (70939)
Sync already in progress from SVobFB+ (DanielMoon)
Peer lEPhW0g (SnowyPeaks) sent orphan 00000...bca0e (70937)
Sync already in progress from SVobFB+ (DanielMoon)
Peer pEZeP3n (tetsugyo) sent orphan 00000...89bdc (70940)
Sync already in progress from SVobFB+ (DanielMoon)
Peer pEZeP3n (tetsugyo) sent orphan 00000...561bb (70940)
Sync already in progress from SVobFB+ (DanielMoon)
Added block seq: 70920, hash: 00000...92b11, txs: 19, progress: 99.96%, time: 10611.9ms
Peer pEZeP3n (tetsugyo) sent orphan 00000...f018b (70941)
Sync already in progress from SVobFB+ (DanielMoon)
Requesting 20 blocks starting at 00000...b1565 (70927) from SVobFB+ (DanielMoon)
Peer pEZeP3n (tetsugyo) sent orphan 00000...7c682 (70942)
Peer pEZeP3n (tetsugyo) sent orphan 00000...7c682 (70942)
```

### Version

0.1.37

### Debug output

```shell
ironfish debug
Database in use, skipping output that requires database.
Stop the node and run the debug command again to show full output.

Iron Fish version       0.1.37 @ 44a7990
Iron Fish library       0.0.15 @ 44a7990
Operating system        Windows_NT x64
CPU model(s)            AMD Athlon Silver 3050U with Radeon Graphics
CPU threads             2
RAM total               5.88 GiB
Node version            v16.15.1
ironfish in PATH        true
Telemetry enabled       true
```

### Relevant log output

```shell
See above

Env = Win 10, direct install via npm -g, upgraded today same way, started this dedicated node.
```

### Graffiti

ProductGuy

**Comment by crProductGuy** [comment]
Similar after stopping and restarting node.

One thing I notice that's new in 0.1.37 is that after some peers disconnect (right after initial connection), they still send blocks later.   

 Definitely some overlapping activity.

May not be "wrong" in terms of building a valid local blockchain copy, but it looks weird.

Version       0.1.37 @ 44a7990
Node Name     ProductGuy
Graffiti      ProductGuy
Peer Identity ALYSH4LhAtloS52ebqXpxobl7QHxInzFXyF46oT3LHY=
Peer Agent    ironfish/0.1.37/44a7990
Peer Port     9033
Bootstrap     test.bn1.ironfish.network

WebSocket server started at :::9033
Connected to the Iron Fish network
Starting sync from hQawOVs (Kamil). work: +1100434287005299, ours: 70937, theirs: 70996
Finding ancestor using linear search on last 3 blocks starting at 00000...bca0e (70937) from peer hQawOVs (Kamil) at 70996
Found peer hQawOVs (Kamil) ancestor 00000...bca0e, syncing from 70937 -> 70996 (59) after 1 requests
Requesting 20 blocks starting at 00000...bca0e (70937) from hQawOVs (Kamil)
Peer hQawOVs (Kamil) disconnected (DISCONNECTED) while syncing.
Starting sync from Y9AhiJv (paigemerritt860). work: +1081639316599106, ours: 70938, theirs: 70996
Finding ancestor using linear search on last 3 blocks starting at 00000...acfdc (70938) from peer Y9AhiJv (paigemerritt860) at 70996
Found peer Y9AhiJv (paigemerritt860) ancestor 00000...acfdc, syncing from 70938 -> 70996 (58) after 1 requests
Requesting 20 blocks starting at 00000...acfdc (70938) from Y9AhiJv (paigemerritt860)
Peer Y9AhiJv (paigemerritt860) disconnected (DISCONNECTED) while syncing.
Starting sync from ibo7JaM (rezero). work: +1081639316599106, ours: 70938, theirs: 70996
Finding ancestor using linear search on last 3 blocks starting at 00000...acfdc (70938) from peer ibo7JaM (rezero) at 70996
Found peer ibo7JaM (rezero) ancestor 00000...acfdc, syncing from 70938 -> 70996 (58) after 1 requests
Requesting 20 blocks starting at 00000...acfdc (70938) from ibo7JaM (rezero)
Peer ibo7JaM (rezero) disconnected (DISCONNECTED) while syncing.
Starting sync from 1p6EqTE (talisa). work: +1081639316599106, ours: 70938, theirs: 70996
Finding ancestor using linear search on last 3 blocks starting at 00000...acfdc (70938) from peer 1p6EqTE (talisa) at 70996
Found peer 1p6EqTE (talisa) ancestor 00000...acfdc, syncing from 70938 -> 70996 (58) after 1 requests
Requesting 20 blocks starting at 00000...acfdc (70938) from 1p6EqTE (talisa)
Peer 1p6EqTE (talisa) disconnected (DISCONNECTED) while syncing.
Starting sync from oqQdb/k (kakali). work: +1062975465739789, ours: 70938, theirs: 70995
Finding ancestor using linear search on last 3 blocks starting at 00000...acfdc (70938) from peer oqQdb/k (kakali) at 70995
Found peer oqQdb/k (kakali) ancestor 00000...acfdc, syncing from 70938 -> 70995 (57) after 1 requests
Requesting 20 blocks starting at 00000...acfdc (70938) from oqQdb/k (kakali)
Peer oqQdb/k (kakali) disconnected (DISCONNECTED) while syncing.
Starting sync from hZjIHkj (Lindah). work: +1007056712187882, ours: 70938, theirs: 70992
Finding ancestor using linear search on last 3 blocks starting at 00000...acfdc (70938) from peer hZjIHkj (Lindah) at 70992
Peer hZjIHkj (Lindah) disconnected (DISCONNECTED) while syncing.
Starting sync from 3r/WwEW. work: +1100139129706737, ours: 70938, theirs: 70997
Finding ancestor using linear search on last 3 blocks starting at 00000...acfdc (70938) from peer 3r/WwEW at 70997
Found peer 3r/WwEW ancestor 00000...acfdc, syncing from 70938 -> 70997 (59) after 1 requests
Requesting 20 blocks starting at 00000...acfdc (70938) from 3r/WwEW
Peer 3r/WwEW disconnected (DISCONNECTED) while syncing.
Starting sync from oLWMoPW (fastpilot). work: +1081639316599106, ours: 70938, theirs: 70996
Finding ancestor using linear search on last 3 blocks starting at 00000...acfdc (70938) from peer oLWMoPW (fastpilot) at 70996
Found peer oLWMoPW (fastpilot) ancestor 00000...acfdc, syncing from 70938 -> 70996 (58) after 1 requests
Requesting 20 blocks starting at 00000...acfdc (70938) from oLWMoPW (fastpilot)
Peer oqQdb/k (kakali) sent orphan 00000...8a82f (70996)
Sync already in progress from oLWMoPW (fastpilot)
Peer denZcMH sent orphan 00000...96a44 (70993)
Sync already in progress from oLWMoPW (fastpilot)
Peer bt+dklT (nijelijle) sent orphan 00000...b442c (70997)
Sync already in progress from oLWMoPW (fastpilot)
Peer oLWMoPW (fastpilot) sent orphan 00000...5fd37 (70998)
Sync already in progress from oLWMoPW (fastpilot)
Peer bt+dklT (nijelijle) sent orphan 00000...36471 (70998)
Sync already in progress from oLWMoPW (fastpilot)
Peer oLWMoPW (fastpilot) sent orphan 00000...ef179 (70999)
Sync already in progress from oLWMoPW (fastpilot)
Peer oLWMoPW (fastpilot) sent orphan 00000...de1c8 (70999)
Sync already in progress from oLWMoPW (fastpilot)
Peer oLWMoPW (fastpilot) sent orphan 00000...6e44e (71000)
Sync already in progress from oLWMoPW (fastpilot)
Peer bt+dklT (nijelijle) sent orphan 00000...c415f (71001)
Sync already in progress from oLWMoPW (fastpilot)
Peer oLWMoPW (fastpilot) sent orphan 00000...65d2f (71002)
Sync already in progress from oLWMoPW (fastpilot)
Peer RIx7lZM (eclipse) sent orphan 00000...53da8 (70995)
Sync already in progress from oLWMoPW (fastpilot)
Added block seq: 70940, hash: 00000...89bdc, txs: 301, progress: 99.90%, time: 575194.8ms
Peer bt+dklT (nijelijle) sent orphan 00000...5efd0 (71003)
Sync already in progress from oLWMoPW (fastpilot)
Peer bt+dklT (nijelijle) sent orphan 00000...c5c1d (71003)
Sync already in progress from oLWMoPW (fastpilot)
Peer bt+dklT (nijelijle) sent orphan 00000...d291e (71004)
Sync already in progress from oLWMoPW (fastpilot)
Peer bt+dklT (nijelijle) sent orphan 00000...494aa (71004)
Sync already in progress from oLWMoPW (fastpilot)
Peer xdekatr (hugovelaskes) sent orphan 00000...c300b (71005)
Sync already in progress from oLWMoPW (fastpilot)
Peer xdekatr (hugovelaskes) sent orphan 00000...9e3b5 (71006)
Sync already in progress from oLWMoPW (fastpilot)
Peer xdekatr (hugovelaskes) sent orphan 00000...8b1fb (71007)
Sync already in progress from oLWMoPW (fastpilot)
Peer xdekatr (hugovelaskes) sent orphan 00000...02d2c (71008)
Sync already in progress from oLWMoPW (fastpilot)
Peer xdekatr (hugovelaskes) sent orphan 00000...97c43 (71007)
Sync already in progress from oLWMoPW (fastpilot)
Peer QtzgtSO (d4nilid) sent orphan 00000...e6f30 (71009)

**Comment by NullSoldier** [comment]
I'm gonna post this here for information. This is a new log added by @dguenther in this PR. https://github.com/iron-fish/ironfish/pull/1642. It's not a change in behavior so much as a new log. I'll send this to him to see if there's anything he wanted to learn from these logs. I'm getting it a lot too.

```
WebSocket server started at :::9033
Connected to the Iron Fish network
Starting sync from V+6BlnN (tetsugyo). work: +2380480103630593, ours: 70796, theirs: 70919
Finding ancestor using linear search on last 3 blocks starting at 00000...630f7 (70796) from peer V+6BlnN (tetsugyo) at 70919
Found peer V+6BlnN (tetsugyo) ancestor 00000...630f7, syncing from 70796 -> 70919 (123) after 1 requests
Requesting 20 blocks starting at 00000...630f7 (70796) from V+6BlnN (tetsugyo)
Added block to fork seq: 70699, head-seq: 70797, hash: 00000...70fdb, head-hash: 00000...276ef, work: 1547393876878840082, head-work: 1549270023806220123, work-diff: 1876146927380041
Peer V+6BlnN (tetsugyo) sent orphan 00000...92b11 (70920)
Sync already in progress from V+6BlnN (tetsugyo)
Peer kE0m6cb (midikaham) sent orphan 00000...e24fd (70919)
Sync already in progress from V+6BlnN (tetsugyo)
Added block seq: 70800, hash: 00000...ff96f, txs: 301, progress: 99.84%, time: 2457.2ms
Added block to fork seq: 67803, head-seq: 70812, hash: 00000...4b141, head-hash: 00000...4fe1e, work: 1483811185768401579, head-work: 1549555868966216035, work-diff: 65744683197814456
Peer V+6BlnN (tetsugyo) sent orphan 00000...a456c (70921)
Sync already in progress from V+6BlnN (tetsugyo)
Requesting 20 blocks starting at 00000...eb97a (70816) from V+6BlnN (tetsugyo)
Added block seq: 70820, hash: 00000...bbb79, txs: 235, progress: 99.87%, time: 2125.3ms
```
