### ISSUE TITLE
Errors with 0.1.37 update through both npm and git 

### ISSUE THREAD

**Issue by meta-lite** [iron-fish/ironfish#1702]
### Description

I run 2 nodes, and am used to updating through the `git pull` and `yarn install` command. When I attempt this for version 0.1.37, I am met with the error:

`error: Your local changes to the following files would be overwritten by merge:
        yarn.lock
Please commit your changes or stash them before you merge.
Aborting`

Because of this, I tried to run `sudo npm install -g ironfish` was met with the error 

`npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/chjj/bsert.git
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists`

**Comment by NullSoldier** [comment]
`error: Your local changes to the following files would be overwritten by merge: yarn.lock Please commit your changes or stash them before you merge. Aborting` is not an error and is GIT, a programming tool, saving you from over-writing local changes to your files. Though in this case it's `yarn.lock` so you can blow them away with `git checkout .` though I recommend not using GIT if you don't understand that well.

I'll take a look at the NPM error.

**Comment by ojasuno** [comment]
I had a similar error, and blew the `iron.lock` file and was able to upgrade alright

**Comment by ojasuno** [comment]
however, now both my `iron-node` and `iron-miner` keeps crashing & rebooting ...here is what i find in the logs
```
Jun 30 03:52:58 yarn[3570128]: WebSocket server started at :::9033
Jun 30 03:52:58 yarn[3570128]: Connected to the Iron Fish network
Jun 30 03:52:58 yarn[3570128]: Starting sync from p7rwrPm (tetsugyo). work: +22052943898295, ours: 72733, theirs: 72734
Jun 30 03:52:58 yarn[3570128]: Finding ancestor using linear search on last 3 blocks starting at 00000...f3aa2 (72733) from peer p7rwrPm (tetsugyo) at 72734
Jun 30 03:53:07 yarn[3570128]: Found peer p7rwrPm (tetsugyo) ancestor 00000...f3aa2, syncing from 72733 -> 72734 (1) after 1 requests
Jun 30 03:53:07 yarn[3570128]: Requesting 20 blocks starting at 00000...f3aa2 (72733) from p7rwrPm (tetsugyo)
Jun 30 03:53:11 yarn[3570128]: Finished syncing 1 blocks from p7rwrPm (tetsugyo)
Jun 30 03:53:12 yarn[3570128]: /home/iron/ironfish/ironfish/build/src/account/accounts.js:320
Jun 30 03:53:12 yarn[3570128]:                             throw new Error('nullifierToNote mappings must have a corresponding noteToNullifier map');
Jun 30 03:53:12 yarn[3570128]:                                   ^
Jun 30 03:53:12 yarn[3570128]: Error: nullifierToNote mappings must have a corresponding noteToNullifier map
Jun 30 03:53:12 yarn[3570128]:     at /home/iron/ironfish/ironfish/build/src/account/accounts.js:320:35
Jun 30 03:53:12 yarn[3570128]:     at async LevelupDatabase.withTransaction (/home/iron/ironfish/ironfish/build/src/storage/database/database.js:39:28)
Jun 30 03:53:13 yarn[3570109]: error Command failed with exit code 1.
Jun 30 03:53:13 yarn[3570109]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Jun 30 03:53:13 yarn[3570048]: error Command failed with exit code 1.
Jun 30 03:53:13 yarn[3570048]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ojasuno** [comment]
thought may be an `rescan` might help, but given the node keeps crashing, not sure how a rescan might work ?!

**Comment by lwisne** [comment]
Were you able to get things working? If there is any specific ongoing bug may create an issue for that as this one has become a bit of a grab bag of things.

**Comment by meta-lite** [comment]
all set now with newer versions
