### ISSUE TITLE
deposit multiple errors and issues on 0.1.37, node crashes because of deposits

### ISSUE THREAD

**Issue by gzivdo** [iron-fish/ironfish#1705]
### What happened?

ironfish deposit errors on 0.1.37
![изображение](https://user-images.githubusercontent.com/13568002/176510257-db6a9904-ca8b-47ad-b5f9-b917331489e3.png)

next case node crashed too, and cannot start
![изображение](https://user-images.githubusercontent.com/13568002/176510380-d90e6d32-544b-4ffb-ab16-b37279a67e21.png)
![изображение](https://user-images.githubusercontent.com/13568002/176510611-2d6322b3-0c94-433f-9cd3-80ef2c7a22e6.png)

### Version

0.1.37

### Graffiti

ar2Obyahain

**Comment by gzivdo** [comment]
done rescan 2 times, with reset flag. few deposits and error again, then node crashes. sometimes it crashes and cant start. 
!!! Also after rescan available balance to spend and unconfirmed very different (about 20-50 iron), it wasnt like this on 0.1.36. Possibly make a new separate bug report?

**Comment by gzivdo** [comment]
So deposit is completly broken with 0.1.37.

**Comment by gzivdo** [comment]
Also I remind, still huge memory leak when depositing. When it works, swap usage is growing very fast.

**Comment by lwisne** [comment]
Are you still seeing this?

**Comment by gzivdo** [comment]
I can retest, i do not use depositAll now, and i try to avoid this condition, but i can try to trigger this again.

**Comment by gzivdo** [comment]
Triggered it today again
![изображение](https://user-images.githubusercontent.com/13568002/183307543-cc84707f-a722-4358-a7be-10f4c5b64086.png)
![изображение](https://user-images.githubusercontent.com/13568002/183307551-2f473379-89e9-417e-b093-41f791fb58d8.png)
![изображение](https://user-images.githubusercontent.com/13568002/183307587-795ccce4-72b8-4f99-b984-65e989e06d1e.png)
![изображение](https://user-images.githubusercontent.com/13568002/183307610-562eb5f0-9283-4bb3-b72f-acd37c93182c.png)

**Comment by hughy** [comment]
We've made significant changes to the wallet since this issue was created. Please create a new issue if you've run into this again on a more recent version. Thanks!
