### ISSUE TITLE
Balance

### ISSUE THREAD

**Issue by Aeithalides** [iron-fish/ironfish#1706]
### What happened?

The balance command is not working even though I have waited for a long time. All other commands are working

### Version

v0.1.36

### Debug output

```shell
Iron Fish version            0.1.36 @ src
Iron Fish library            0.0.14 @ src
Operating system             Linux x64
CPU model(s)                 DO-Regular
CPU threads                  4
RAM total                    7.77 GiB
Node version                 v16.15.1
ironfish in PATH             true
Telemetry enabled            true
Accounts head hash           00000000000c6bea6f04a60eb43b474445b5280e9ea0e35e088a865f4523b01e
Accounts head in chain       true
Accounts head sequence       71480
```

### Graffiti

Aeithalides

**Comment by QustomQure** [comment]
First of all there is a new version out, can you update your Ironfish

**Comment by NullSoldier** [comment]
You haven't provided any information about how it's not working. Does it hang without outputting any information?
