### ISSUE TITLE
v0.1.37 has lost the %sync'd display in `ironfish status -f`

### ISSUE THREAD

**Issue by crProductGuy** [iron-fish/ironfish#1713]
### What happened?

No longer can see sync percentage in ironfish status.

Not sync'd, but got this.  Last sync % in node log was 99.3%

Version              0.1.37 @ 44a7990
Node                 STARTED
Memory               Heap: 218.33 MiB / 263.39 MiB (82.9%), RSS: 863.45 MiB (14.3%), Free:
1.36 GiB (76.9%)
P2P Network          CONNECTED - In: 37.31 KB/s, Out: 8.24 KB/s, peers 49
Mining               STARTED - 0 miners, 0 mined
Mem Pool             0 tx
Syncer               IDLE - avg time to add block 13931.09 ms
Blockchain           NOT SYNCED @ HEAD 000000000001d5cb5aabc9ab7b3db54be68f84495c8c40b88789d1861c0dcdf1 (72854)                                                                       Telemetry            STARTED - 107 <- 0 pending
Workers              STARTED - 0 -> 0 / 1 - 0 jobs Δ, 0 jobs/s

### Version

0.1.37

### Debug output

```shell
ironfish debug
Database in use, skipping output that requires database.
Stop the node and run the debug command again to show full output.

Iron Fish version       0.1.37 @ 44a7990
Iron Fish library       0.0.15 @ 44a7990
Operating system        Windows_NT x64
CPU model(s)            AMD Athlon Silver 3050U with Radeon Graphics
CPU threads             2
RAM total               5.88 GiB
Node version            v16.15.1
ironfish in PATH        true
Telemetry enabled       true
```

### Relevant log output

```shell
see above
```

### Graffiti

ProductGuy

**Comment by NullSoldier** [comment]
It's only shown when the syncer is syncing. I changed this to always show if you're not synced. https://github.com/iron-fish/ironfish/pull/1719
