### ISSUE TITLE
Corrupted node and rescan ends in SIGABRT

### ISSUE THREAD

**Issue by xorinox** [iron-fish/ironfish#1725]
### What happened?

Node cannot be restarted due to following error message

Version       0.1.37 @ src
Peer Agent    ironfish/0.1.37/src
Peer Port     9033
Bootstrap     test.bn1.ironfish.network

node: ../deps/leveldb/leveldb-1.20/table/table_builder.cc:97: void leveldb::TableBuilder::Add(const leveldb::Slice&, const leveldb::Slice&): Assertion `r->options.comparator->Compare(key, Slice(r->last_key)) > 0' failed.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Trying a rescan doesn't help either

[srv_ironfish@node-6d ironfish]$ cd ironfish-cli/
[srv_ironfish@node-6d ironfish-cli]$ yarn ironfish accounts:rescan
yarn run v1.22.17
$ /home/srv_ironfish/ironfish/node_modules/.bin/ironfish accounts:rescan
node: ../deps/leveldb/leveldb-1.20/table/table_builder.cc:97: void leveldb::TableBuilder::Add(const leveldb::Slice&, const leveldb::Slice&): Assertion `r->options.comparator->Compare(key, Slice(r->last_key)) > 0' failed.
error Command failed with signal "SIGABRT".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Graffiti

xorinox

**Comment by lwisne** [comment]
Did this ever resolve for you?

**Comment by holahula** [comment]
Closing due to staleness. If the issue persists - please file a new issue
