### ISSUE TITLE
Official and self-hosted pool not receiving work

### ISSUE THREAD

**Issue by gjfrn** [iron-fish/ironfish#1757]
### What happened?

For the past few hours I am not receiving work from the official pool. Switching to a self-hosted pool results in the same issue, where the hashrate for all of my miners is at 0 H/s.

### Version

0.1.37

### Relevant log output

```shell
Connecting to pool...
Successfully connected to pool
Subscribing to pool to receive work
Hashrate... ⣟ 0 H/s (0)
```

### Graffiti

GFIRONFISH

**Comment by NullSoldier** [comment]
The official pool was down this weekend but is back up today. It was mentioned here, https://discord.com/channels/771503434028941353/816795744680935445/995720264396587130

I don't know why your personal pool is not working unless you provide more information. I don't even know what software you used to host it. There are roughly 4-5 pool software around, we only support our official pool and our pool software.
