### ISSUE TITLE
multiple npm install fails

### ISSUE THREAD

**Issue by sgreszcz** [iron-fish/ironfish#1778]
### What happened?

Fresh install Ubuntu 20.04, nvm install from https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh
```
root@ironfish:~# nvm use 16
Now using node v16.16.0 (npm v8.11.0)
root@ironfish:~# npm install -g ironfish
```
First get error:
```
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm notice
npm notice New minor version of npm available! 8.11.0 -> 8.13.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.13.2
npm notice Run npm install -g npm@8.13.2 to update!
npm notice
npm ERR! code 127
npm ERR! path /root/.nvm/versions/node/v16.16.0/lib/node_modules/ironfish/node_modules/leveldown
npm ERR! command failed
npm ERR! command sh -c node-gyp-build
npm ERR! sh: 1: node-gyp-build: Permission denied

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-07-13T14_03_10_699Z-debug-0.log
```
Log attached.
[npm-ironfish.txt](https://github.com/iron-fish/ironfish/files/9102937/npm-ironfish.txt)

### Version

latest

### Debug output

```shell
See attached
```

### Relevant log output

```shell
See attached
```

### Graffiti

halo

**Comment by NullSoldier** [comment]
This is an issue with your computer setup, unrelated to Iron Fish. Your `node-gyp-build` permissions has mixed sudo permissions. Either you used sudo at some point, or you're mixing users that you installed with and are using iron fish with.
