### ISSUE TITLE
FIP: Persist blockchain sync to disk?

### ISSUE THREAD

**Issue by sgreszcz** [iron-fish/ironfish#1787]
### Description

I've been experimenting with ironfish in a couple of VPS, using docker with persistent volume shares.  However it seems as though the blockchain sync is happening only in memory.  Why is the sync not persisting/syncing to disk as when there is a crash due to out of memory, it needs to start the sync again.  Also is there a way to bootstrap the blockchain with a daily file 
  download to speed things up rather than an over-the-network only sync.

Graph shows VPS startup and sync with 1GB RAM, and then again with 2GB RAM.  I know more is required but if the blockchain needs to remain in memory, and is not cached, then eventually you will blow up.

<img width="826" alt="Screenshot 2022-07-14 at 10 10 11" src="https://user-images.githubusercontent.com/22910494/178946985-175503ea-f5bc-44eb-8fd8-49607b92b253.png">
?

**Comment by NullSoldier** [comment]
Blockchain sync is only persisted to disk, and there is no memory syncing. Nothing is kept in memory.

That logic is contained here, https://github.com/iron-fish/ironfish/blob/master/ironfish/src/syncer.ts

If you follow it through the flow is:

1. Look for peer that has more work than we do
2. Find the combined forking point
3. Find the forking point between us and the syncing peer
4. Request blocks from the forking point
5. Insert those blocks into the blockchain (and write each to disk)

I don't think this is a FIP as there is no proposal exactly other than what our code already does. Also the idea of a FIP is that its a proposal that someone would work on.
