### ISSUE TITLE
Version 0.1.38 Ironfish Commands Error

### ISSUE THREAD

**Issue by meta-lite** [iron-fish/ironfish#1789]
## End of install process: 
Compiling ironfish_rust v0.1.0 (/home/minnow3/ironfish/ironfish-rust)
    Finished release [optimized] target(s) in 1m 08s
Done in 79.26s.
minnow3@minnow3-dell3:~/ironfish$ cd ironfish-cli
minnow3@minnow3-dell3:~/ironfish/ironfish-cli$     yarn ironfish testnet
yarn run v1.22.19

## Attempted to use testnet and start commands, but only help worked:
$ /home/minnow3/ironfish/node_modules/.bin/ironfish testnet
 ›   Warning: testnet is not a ironfish command.
Did you mean help? [y/n]: y

##Displays only the help command: 
CLI for running and interacting with an Iron Fish node
VERSION
  ironfish/0.1.38 linux-x64 node-v16.16.0
USAGE
  $ ironfish [COMMAND]
COMMANDS
  help  Display help for ironfish.
Done in 3.91s.

##After the failed help command, start command works:
minnow3@minnow3-dell3:~/ironfish/ironfish-cli$ yarn start start
yarn run v1.22.19
$ yarn build && yarn start:js start
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run start                
::::::::::          :::::::::::::::::         
::::::::::::       :::::::::::::::::::        
:::::::::::::     :::::::::::::::::::::       
::::::::::::::   ::::::::::::::::::::::::     
 ::::::::::::: ::::::::::        :::::::::    
   :::::::::::::::::::::          ::::::::::  
   :::::::::::::::::::::          :::::::::   
 ::::::::::::: ::::::::::        :::::::::    
::::::::::::::   ::::::::::::::::::::::::     
:::::::::::::     :::::::::::::::::::::       
::::::::::::       :::::::::::::::::::        
::::::::::           ::::::::::::::::         
Version       0.1.38 @ src
Node Name     NONE
Graffiti      NONE
Peer Identity 4XoMNhgjAnyjTyq6by4PbOYc+uX6pIEuhaYGBaIQPQQ=
Peer Agent    ironfish/0.1.38/src
Peer Port     9033
Bootstrap     test.bn1.ironfish.network

Replicated this over 3 machines with same result

### Version

0.1.38

### Graffiti

mycelium

**Comment by lwisne** [comment]
Is this still an issue? This is probably an issue with the way you were building the code - we recommend installing via npm in order to avoid these kinds of problems.
