### ISSUE TITLE
error running "ironfish debug"

### ISSUE THREAD

**Issue by msa6867** [iron-fish/ironfish#1792]
### What happened?

Entered "ironfish debug" in CLI with node running.  In the past this has never been in issue and the return was to provide what state could be while running the node (which was less state than would be returned when node is stopped).  Now it returns an error as follows:
C:\Users\Mark>ironfish debug
    Error: Database is not open. Call IDatabase.open() first

(If this is the new expected behavior please leave comment and disregard.)

(debug output below is from previous query when node was stopped)

### Version

v0.1.38

### Debug output

```shell
Iron Fish version            0.1.38 @ 85dc82e
Iron Fish library            0.0.16 @ 85dc82e
Operating system             Windows_NT x64
CPU model(s)                 AMD Ryzen 9 5950X 16-Core Processor
CPU threads                  32
RAM total                    31.92 GiB
Node version                 v16.15.0
ironfish in PATH             true
Telemetry enabled            true
Accounts head hash           000000000009a99e6deee713542042dd21e70ae404231fd779428c1387386f08
Accounts head in chain       true
Accounts head sequence       93006
```

### Relevant log output

```shell
C:\Users\Mark>ironfish debug
    Error: Database is not open. Call IDatabase.open() first
```

### Graffiti

msa6867

**Comment by lwisne** [comment]
Do you still get this behavior?

**Comment by msa6867** [comment]
I am away from my setup until sunday.  I will answer when I get back.  When I left on vacation last Wed, the behavior persisted; that was the last I checked

**Comment by msa6867** [comment]
Problem persists
