### ISSUE TITLE
Balance and deposit codes are stuck.

### ISSUE THREAD

**Issue by crazywriter1** [iron-fish/ironfish#1796]
### What happened?

A bug happened! I can't see balance. The code gets stuck. Likewise, the "ironfish deposit" code gets stuck. It always remains as in the screenshot.
![Ekran Alıntısı](https://user-images.githubusercontent.com/53251494/179345829-432260c3-aae3-49d1-a5e6-df373c63ffb1.PNG)

### Version

v0.1.38

### Debug output

```shell
yarn run v1.22.19
$ yarn build && yarn start:js deposit
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run deposit
```

### Graffiti

crazywriter

**Comment by hughy** [comment]
The Wallet 2.0 refactor released in [v0.1.48](https://github.com/iron-fish/ironfish/releases/tag/v0.1.48) included significant changes to speed up transaction creation

Please open a new issue if you run into this again!
