### ISSUE TITLE
FIP: Add expiration to `accounts:transaction` command

### ISSUE THREAD

**Issue by NullSoldier** [iron-fish/ironfish#1799]
### Description

Our `accounts:transactions` command does not show transaction expiration sequence. We should add it for debugging purposes. I noticed a user is having trouble with their transactions and the command doesn't output enough debugging information. https://github.com/iron-fish/ironfish/issues/1727#issuecomment-1185761121

The current output is 

```
Status    Creator Hash                                Miner Fee Fee ($ORE)  Notes Spends
 ───────── ─────── ─────────────────────────────────── ───────── ─────────── ───── ──────
 completed ✔       065002ea4c123afe8592474a6a593c516c… x         1           2     1
 pending   x       07714cf811f6ffb771bd812f0beaad3f24… x         821         822   7
```

But we should add a new column for "expiration" like this:

```
Status    Creator Hash                                Miner Fee Fee ($ORE)  Notes Spends Expiration
───────── ─────── ─────────────────────────────────── ───────── ─────────── ───── ────── ──────────
 completed ✔       065002ea4c123afe8592474a6a593c516c… x         1           2     1     78599
 pending   x       07714cf811f6ffb771bd812f0beaad3f24… x         821         822   7     80000
```

This is what you'll probably need to change:

* Return the expiration in the RPC `account/getAccountTransactions`
* Add the column to the `accounts:transactions` CLI command

**Comment by wd021** [comment]
might be appropriate to add this to the FIP, https://github.com/iron-fish/ironfish/issues/1727#issuecomment-1186861048.

**Comment by NullSoldier** [comment]
I will consider this FIP complete when https://github.com/iron-fish/ironfish/pull/1801 merges
