### ISSUE TITLE
Error when adding new block 103268 from l2sPq2O: Error: Expected value not to be null

### ISSUE THREAD

**Issue by hamza-siddiq** [iron-fish/ironfish#1826]
### Description

I start ironfish node server and mining 
Ironfish start
Ironfish miners:start
20min later, the following error code appears:

![image](https://user-images.githubusercontent.com/92462002/180169862-e9c73d85-c9dc-4479-9563-ea6807755317.png)
graffiti: ironfishup

**Comment by holahula** [comment]
Closing due to staleness. If the issue persists - please file a new issue
