### ISSUE TITLE
FIP: When  ‘config:set enableRpcTcp true‘  is executed, ‘config:show’ should be shown

### ISSUE THREAD

**Issue by hamza-siddiq** [iron-fish/ironfish#1827]
### Description

https://github.com/iron-fish/ironfish/issues/1535
https://github.com/iron-fish/ironfish/issues/1577
https://github.com/iron-fish/ironfish/issues/1527

In these issues, you can see the bug report:
“No route found config/getConfig in namespace config for method getConfig.”

The reason of bugs is in following code on ironfish/ironfish/src/sdk.ts && ironfish/ironfish/src/rpc/routes/router.ts:

<img width="468" alt="image" src="https://user-images.githubusercontent.com/92462002/180170633-c0e6fc82-324d-4832-beab-cfc5003eeb90.png">
<img width="468" alt="image" src="https://user-images.githubusercontent.com/92462002/180170666-81e0821c-1dee-4c9a-9fdd-e109ea20daad.png">
When RpcTcp is enabled, these bugs disappear.

So I’d like to show the result of ‘config: show’ with following sentence when enableRpcTcp is set to true.
“No route found config/getConfig in namespace config for method getConfig.
You must set enableRpcTcp to false
Do you want to set enableRpcTcp to false, or type s to show config? [y/n/s]”
If y, the value of enableRpcTcp is set to false,
else if n, finish 
else if s, show config.

I can try this engine for a total of 15 hours.
If this engine succeeds, many bugs will be automatically eliminated.

graffiti: ironfishup

**Comment by lwisne** [comment]
By default we leave out config and account commands when RPC TCP is enabled. There are workarounds in the other issues you linked. I don't expect this state to change, so closing.
