### ISSUE TITLE
Missing Node Points due to telemetry DB write timing.  Workaround fix by IF API PR 976

### ISSUE THREAD

**Issue by crProductGuy** [iron-fish/ironfish#1847]
Looks like missed telemetry data storage based on Jason's note below.

Seems I'm still missing some 70 node-running points between 6/18 thru 6/22.   I did receive 5 x 10 points showing on my profile https://testnet.ironfish.network/users/213 credited as 6/17, so maybe some fix-ups were done and credited after the fact, all with a date of 6/17, but I still see a gap from 6/18 thru 6/22.  If we say that the 3rd thru 5th points dated 6/17 actually covered 2x 12 hours for 6/18 and 12 hours for 6/19 as backfills with wrong dates, that leaves missing 1x 12 hours on 6/19, 2x 12 hours on 6/20, 2x 12 hours on 6/21, and 2x 12 hours on 6/22.    Then everything looks solid with 2x 12 hours for 6/12 forward.        The missing range covers 7 x 12 hours or 70 points total.        It's possible that my node had crashed undetected for several hours during that period once, but I watch it pretty diligently mornings, multiple times during the day day, and nights before bed, so I would have expected that there wouldn't have been more than 8 hours missing in there.         Please investigate the telemetry data if you have it, and adjust my points.  Thanks!

From Jason (nullSoldier) on 22july22 in IF Discord Ticket-196:
jason — Today at 10:21 AM
I think there are some issues but they are hard to track down right now. I put up a fix that hopefully will help this issue, https://github.com/iron-fish/ironfish-api/pull/976

**Comment by lwisne** [comment]
> some fix-ups were done and credited after the fact, all with a date of 6/17

Yes, we had a bug where we actually credited too many points for some users and then those users had to mine for more than 12 hours to actually earn the points. This is a likely explanation for some of this gap. Will look at the rest.

**Comment by holahula** [comment]
Closing due to staleness. If the issue persists - please file a new issue
