### ISSUE TITLE
[rescan from the 0 position again after reboot from break]

### ISSUE THREAD

**Issue by hellogit2021** [iron-fish/ironfish#1854]
### What happened?

1.running the rescan
2.if the rescan was interrupted for some reasons(for example:power off or reboot node)
3.rerun the rescan ,it does not resume from where it left off , but accutlly start from 0 again
4.considering the rescan time is very long ,seldom could the ordinary machine run long time without any accidents,that cause rescan can not finish forever actually for some users

### Version

0.1.38,0.1.39,0.1.40

### Graffiti

fatgeek

**Comment by mat-if** [comment]
This will be fixed very soon, hopefully in 0.1.41, but maybe 0.1.42. We've already fixed it as part of the accounts improvements we're making, so once we're ready to ship that, rescan progress will save.

**Comment by Rofl92** [comment]
> This will be fixed very soon, hopefully in 0.1.41, but maybe 0.1.42. We've already fixed it as part of the accounts improvements we're making, so once we're ready to ship that, rescan progress will save.

In version 0.1.44, the rescan still starts from block 0 if it was interrupted in the process.
Or do I need to add some parameter to continue the rescan?

**Comment by holahula** [comment]
Closing due to staleness. If the issue persists - please file a new issue
