### ISSUE TITLE
UX issue with accounts:transactions

### ISSUE THREAD

**Issue by lwisne** [iron-fish/ironfish#1877]
### What happened?

The`accounts:transactions` command has a slightly misleading display. 

Once a transaction is added to a block and the block is created, there is a block confirmation time (currently 12 blocks) in which you cannot yet spend new notes created in the block and its transactions. This protects against people spending notes that may end up in a fork.

Given this, **we need one more state for a transaction in which we display that the tx is "confirming".** This means it is waiting for enough blocks to process such that the the new notes created by the tx will now be spendable. Without this, you will see "confirmed" transactions that are not yet applied to your "available to spend" balance.

### Graffiti

lwisne

**Comment by hughy** [comment]
Transaction statuses modified in #1882, #1883, #2264 to include additional statuses
