### ISSUE TITLE
Feature: Dynamic fees on deposit + pay

### ISSUE THREAD

**Issue by lwisne** [iron-fish/ironfish#1879]
### Description

The `deposit` command defaults to 1 $ORE as the fee. However, miners are increasingly not picking up txs that only have 1 $ORE fee. You have to set this a bit higher.

Ideally, the default fee would have a value that adjusts based on recent transactions. So if you look at the last x hours of transactions, pick a fee in the 20th percentile or so. This would help ensure people who just use the deposit without knowing fee mechanics would see their txs go through.

**Comment by wd021** [comment]
As a first step, https://github.com/iron-fish/ironfish/pull/1977 adds a new `ironfish fees` command to get a better look into fees for the last N blocks. 

Next, some changes to deposit + pay -> https://github.com/iron-fish/ironfish/issues/1978
