### ISSUE TITLE
Building & Running on Ubuntu from source requires a workaround

### ISSUE THREAD

**Issue by pkrasam** [iron-fish/ironfish#19]
**Context**
- I am running Iron Fish on Ubuntu.
- The build from source works alright.
- But when I try to run the node, it gives an error.
- Luckily, a community member posted a workaround for now.
- Keen to see if/when/how we can resolve the error.

**Environment Version**
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
```
```
$ node -v
v14.16.1
```
```
$ rustup -V
rustup 1.23.1 (3df2264a9 2020-11-30)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.51.0 (2fd73fabe 2021-03-23)`
```
```
$ yarn -v
1.22.5
```

**Command**
```
$ cd ironfish
$ ironfish-cli/bin/run start
```

**Error**
```
TypeError: Cannot read property 'box' of undefined
```

**Workaround**
```
$ cd ironfish-cli
$ yarn start:js start
```

**Output**
```
yarn run v1.22.5
$ OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run start


::::::::::          :::::::::::::::::
::::::::::::       :::::::::::::::::::
:::::::::::::     :::::::::::::::::::::
::::::::::::::   ::::::::::::::::::::::::
 ::::::::::::: ::::::::::        :::::::::
   :::::::::::::::::::::          ::::::::::
   :::::::::::::::::::::          :::::::::
 ::::::::::::: ::::::::::        :::::::::
::::::::::::::   ::::::::::::::::::::::::
:::::::::::::     :::::::::::::::::::::
::::::::::::       :::::::::::::::::::
::::::::::           ::::::::::::::::

Peer Identity                 nifCWCJF13mAdej5LIhoZOk8Kr9dWrGC5LkCxmba3xg=
Peer Version                  ironfish-sdk/1/cli
Port                          9033
Bootstrap                     test.bn1.ironfish.network

WebSocket server started at :::9033
Connected to the Iron Fish network
```

**Resources**
[Iron Fish Installation - Linux](https://ironfish.network/docs/onboarding/installation-iron-fish#linux)

**Comment by QuickMythril** [comment]
same error on windows, even when using "yarn start:js start"
https://github.com/iron-fish/ironfish/issues/11#issuecomment-814540705

**Comment by dguenther** [comment]
The build instructions on the website were actually incorrect 🤦 I changed them in this PR: https://github.com/iron-fish/website/pull/37 to just point to the README in this repository instead, since I think source-building instructions should live with the source. So to clarify, the workaround mentioned above is actually the intended way to run the coin from source.

Windows appears to have the same crash, but I suspect it's caused by a separate Windows OS-exclusive issue.
