### ISSUE TITLE
Feature: add rescan/decrypt progress in status output

### ISSUE THREAD

**Issue by gzivdo** [iron-fish/ironfish#1914]
### Description

When the node become synced from unsynced state seems it continue to decrypt transactions and  do "re-play" of balance changes since unsynced state to current, it do it slower than sync process. need to add indication of that process in "status" output. sure, if my assumptions is correct. the same when you doing rescan, it should show decrypt process state in percent

**Comment by lwisne** [comment]
To clarify - I think what you're saying here is the underlying data structures that provide balances, etc lag behind the syncing process. How much so, in your experience?

**Comment by lwisne** [comment]
Also, I would consider this a bug, or at the very least unclear UX. Changing label accordingly.

**Comment by gzivdo** [comment]
> To clarify - I think what you're saying here is the underlying data structures that provide balances, etc lag behind the syncing process. How much so, in your experience?

yes, it depends on cpu. 
i use now zfs snapshots instead of regular rescan, before .37 it took about 3-4 hours of 3-5 days after sync is complete. 
but on last versions .40 and .41 it do decrypt even if you create new address, 2 days since upgrade, still cannot complete and i dont know state of it.

**Comment by wd021** [comment]
I've been testing the wallet 2.0 branch today/yesterday and it's awesome. Rescans and balances are super fast. I don't think we need to save rescan positions of accounts, etc.. no need to complicate things.

I do think it'd be beneficial to add some clarity in the CLI response for the account status. We should probably add the scan status and the endHeader of the chainProcessor.

**Comment by gzivdo** [comment]
so if it is, will wait wallet 2.0

**Comment by hughy** [comment]
Rescan progress added to output of `ironfish status` in #1927
