### ISSUE TITLE
Feature: Add expired transaction view

### ISSUE THREAD

**Issue by lwisne** [iron-fish/ironfish#1921]
### Description

See comments here:

https://github.com/iron-fish/ironfish/issues/1727

When a transaction expires, it disappears from the `account:transactions` command and all views of transactions. We should have a way to view expired transactions. Maybe a flag on `account:transactions` would be the most straightforward way.

Note, this is not straightforward because we currently have mechanisms to purge expired transactions. We would have to undo this, and also ensure undoing it doesn't break other things.

**Comment by aminazeb** [comment]
I am interested to work on this issue.

**Comment by aminazeb** [comment]
Hi, I am working on this ticket.

**Comment by aminazeb** [comment]
Just want a little more clarity that is there an addition flag required other than the expired status or there should be a view listing all the expired transactions?

**Comment by danield9tqh** [comment]
Hey @aminazeb really appreciate you wanting to contribute here. Sorry for the late response but I'm afraid this probably isn't the best issue to contribute on right now. The team is most likely going to be making a lot of changes around how expired transactions are stored in the wallet database so any contributions in that area may become obsolete.

**Comment by hughy** [comment]
After release v0.1.48 expired transactions are no longer deleted from the wallet
