### ISSUE TITLE
Validate config files

### ISSUE THREAD

**Issue by lwisne** [iron-fish/ironfish#1924]
### What happened?

See comment below:

https://github.com/iron-fish/ironfish/issues/1675#issuecomment-1166271085_

It appears we don't validate config file settings, which can lead to odd issues (or maybe even a security hole if the settings are used in certain ways).

**Comment by neuronull** [comment]
Hello! I am interested in addressing this.

**Comment by aditya-manit** [comment]
Looks like this is already been addressed, we should close this issue I think
