### ISSUE TITLE
transaction with big fee - very long pending

### ISSUE THREAD

**Issue by alar0n** [iron-fish/ironfish#1926]
### What happened?

Hello. I sended this transaction:
https://explorer.ironfish.network/transaction/469e4cb7dfe60cc9c25cdee09ffb9c027c4f7945e68c15b3b295ca94d108a0c7

It's been a day, but there's no confirmation.
Transaction status - pending.
![image](https://user-images.githubusercontent.com/31000576/182750340-935e3144-2ae0-47ee-95bb-14a776ca10c6.png)

### Version

ex 0.1.41

### Debug output

```shell
Iron Fish version               0.1.41 @ src
Iron Fish library               0.0.19 @ src
Operating system                Linux x64
CPU model(s)                    Intel(R) Xeon(R) Gold 6248R CPU @ 3.00GHz
CPU threads                     8
RAM total                       31.35 GiB
Heap total                      4.00 GiB
Node version                    v16.16.0
ironfish in PATH                true
Garbage Collector Exposed       true
Telemetry enabled               true
Node name                       alar0n
Block graffiti                  alar0n
Done in 2.24s.
```

### Graffiti

alar0n

**Comment by lwisne** [comment]
This tx is currently on the chain - does it still show pending in the CLI?

**Comment by alar0n** [comment]
Yeah.
Nothing changed
![image](https://user-images.githubusercontent.com/31000576/182990067-36ee1a58-826e-4cf7-9935-61378294e459.png)

2nd transactions - it's i tryed sending again. She is pending more what 1 day too.

**Comment by wd021** [comment]
can you paste your output instead of a screenshot, makes copying hashes easier. 

Pending is not a great status at the moment since it means a bunch of things. I'm going to submit a PR to expand the clarity of statuses here.

**Comment by alar0n** [comment]
3bd6928b5126fab653e00f746c63cff2fdb42f2a8a9143d15690167f34f8a91e
469e4cb7dfe60cc9c25cdee09ffb9c027c4f7945e68c15b3b295ca94d108a0c7

**Comment by lwisne** [comment]
These transactions are on chain, so this would imply that there is something up with your syncing process. Is your chain fully synced?

**Comment by alar0n** [comment]
Yeah. I have 2 fully syncronized node. i tryed used rescan and i tryed reinstall one node. It's was helpfull.
