### ISSUE TITLE
Synchronizing orphan chain

### ISSUE THREAD

**Issue by hamza-siddiq** [iron-fish/ironfish#1930]
### What happened?

I found what might be a bug, where when synchronizing an orphan chain, the peer sequence is found to be null. I can fix it, but I need to make sure I've found the root cause, so I can fix the problem, not the symptom.
![IMG-20220804-WA0013](https://user-images.githubusercontent.com/92462002/182916683-288c81ce-c785-4ffe-8721-12d31a12209d.jpg)
I found this chunk of code in blockchain.ts file. Is Orphan blocks implemented yet? If not, why are they being handled in syncer.ts?
![](https://cdn.discordapp.com/attachments/1002151985518235710/1004789938950250526/IMG-20220804-WA0014.jpg)
![IMG-20220804-WA0019](https://user-images.githubusercontent.com/92462002/182917687-7f7854c5-4f27-441e-ada5-e2031fc17ff2.jpg)

### Version

0.1.4.1

### Graffiti

ironfishup

**Comment by hamza-siddiq** [comment]
I think I found the bug that causes the peer sequence to be null. Is this intentional
![IMG-20220804-WA0025](https://user-images.githubusercontent.com/92462002/182931130-6672dd10-129a-4e7a-9084-1bc975631212.jpg)

I think the line there removes the original value of the peer, so the assignment of the sequence later is not performed on the peer itself (the one passed to the function), but to the newly created peer object in line 1060.
Since this code executes only when a peer tries to connect with a new identity, I think the right approach would be to drop the new connection, because it would be more strict and efficient that way
Is my reasoning correct? So I can perform the fix.

**Comment by lwisne** [comment]
Thanks for the heads up - one thing I would ask for future bugs is copy and pasting the logs vs using a screenshot enables us to more easily copy and paste text from there.

**Comment by hamza-siddiq** [comment]
Aah i see. Should i do that right now, or is it good?

**Comment by hamza-siddiq** [comment]
Is my reasoning correct though? I can perform the fix right away

**Comment by hamza-siddiq** [comment]
Thanks @lwisne I'll go ahead, and get started on fixing the bug

**Comment by lwisne** [comment]
Of course - I will warn that issue has a relatively difficult fix. Feel free to take a shot, but this does require a pretty thorough understanding of some core pieces of our syncing processes.

**Comment by holahula** [comment]
Closing due to staleness. If the issue persists - please file a new issue
