### ISSUE TITLE
Feature: Handle Error Messages Better

### ISSUE THREAD

**Issue by hamza-siddiq** [iron-fish/ironfish#1940]
### Description

The problem that I have encountered as I dig deeper into the code was that most error messages aren't really handled well. E.g the message below says "Error". It can be more specific.
![IMG-20220804-WA0018](https://user-images.githubusercontent.com/92462002/182962240-b5b5c9b6-210b-46c3-b4ca-d240a5b8eb7d.jpg)

This also involves checking careless exception throwing (that are not actually caught), and fixing the logic of properly logging the messages attached to those exceptions, then returning the correct failure reason
For example, this error is not caught correctly. And the message attached to it is just discarded
![IMG-20220804-WA0026](https://user-images.githubusercontent.com/92462002/183108151-7d52be12-12c1-4605-963f-8d229c5e12c1.jpg)

Here is the erroneous try/catch block
![IMG-20220804-WA0027](https://user-images.githubusercontent.com/92462002/183108167-1256a14b-7e3a-4aed-affb-476b61309060.jpg)

When people encounter error messages they need to be more specific and handled better. I believe this is very important. I would like to make an improvement to the current code which properly handles and reports errors. 

Some things that this PR would do:
Adds a field (explanation) that can be used to clarify the error with a detailed message. Makes the instances of Verify errors convertible to string so they can be printed conveniently in logs. Add an error to indicate an empty MerkeTree error. Properly handle and report errors. Use correct error type instead of the generic ERROR. Raise the correct error types depending on the error condition. Make sure to pass explanation message to both error cases. Simplify message returning. Update expected error reasons

**Comment by lwisne** [comment]
It is common, and quite useful in some places, to have a generic error message available. 

If you want to add more granular messaging for certain cases, you should focus on the specific cases and the functionality that is not working correctly.

The request is too broad, so I will close.

**Comment by hamza-siddiq** [comment]
Actually, not really. Kindly have a look at the PR, which solves these issues: https://github.com/iron-fish/ironfish/pull/1939

**Comment by hamza-siddiq** [comment]
@lwisne I worked on this myself, and opened a PR. So not a big deal that it's broad, i fixed the issues
