### ISSUE TITLE
Amount available to spend is ZERO

### ISSUE THREAD

**Issue by 0x64696d61** [iron-fish/ironfish#1955]
### What happened?

I can't sent IRON(

The balance is: $IRON 0.17424240 ($ORE 17,424,240)
Amount available to spend: $IRON 0.00000000 ($ORE 0)

Why 'amount available to spend' is zero?

### Version

0.1.40

### Debug output

```shell
yarn run v1.22.19
$ yarn build && yarn start:js debug
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run debug
Database in use, skipping output that requires database.
Stop the node and run the debug command again to show full output.

Iron Fish version       0.1.40 @ src
Iron Fish library       0.0.18 @ src
Operating system        Linux x64
CPU model(s)            AMD EPYC 7401P 24-Core Processor
CPU threads             48
RAM total               125.77 GiB
Heap total              4.00 GiB
Node version            v16.16.0
ironfish in PATH        true
Telemetry enabled       true
Done in 4.28s.
```

### Graffiti

hardnode

**Comment by lwisne** [comment]
This happens routinely while a previous transaction is processing. Likely not a bug unless it persists.

**Comment by 0x64696d61** [comment]
it's been hanging for two days

ironfish accounts:transactions
yarn run v1.22.19
$ yarn build && yarn start:js accounts:transactions
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run accounts:transactions

 hardnode (bc26fe6) - Account transactions

 Status  Creator Hash                                                             Miner Fee Fee ($ORE) Notes Spends Expiration 
 ─────── ─────── ──────────────────────────────────────────────────────────────── ───────── ────────── ───── ────── ────────── 
 pending x       8ba0301d521465ccf6f859cb6be7e1835056557a5d4be0128a5ca319931d5954 x         710        711   1      123704     
 pending x       e5ee10360160578fbee6ce9a3078cc9596c348cc8bf6061b01b34252d794becf x         1011       1012  1      124101     
 pending x       e36a6bd56689027d1afb83cf75fafd4fd927d011608655bba4a02926046fc764 x         1006       1007  1      124306     
 pending x       8440ebf08cfb30f57253075fbd431faf1c592bbf9b6ff1f71df5ee1504cef999 x         1086       1087  1      125552     
 pending x       1793414b03d0837e9b76be488643121b883597a77d6a440269014852b07375e1 x         688        689   1      125598     
 pending x       efa6a8a5fe2159d42c7fe0abe4ac76d9c561a9acce22ba46a7f46caab1f8c290 x         833        834   1      125702     
 pending x       d6ec21d4274e4c7be49757c00dfa9b1ea3f016b5e21ee98d4bdc8ea58e0adaad x         701        702   1      125766     
 pending x       d9b3ac0bdcb56fe6bbc555411829f17cba6e78fb96d7ba975c2089cbce12ab6b x         711        712   1      125841     


Done in 18.85s.
