### ISSUE TITLE
having trouble with my IRON balance again

### ISSUE THREAD

**Issue by alterkahn** [iron-fish/ironfish#196]
I again facing this error `All decryptable notes should be in the noteToNullifier map` when trying to check my node balance. Last time the command `ironfish accounts:rescan --reset` reset my balance to 0, so maybe there is another way to fix this bug?

**Comment by NullSoldier** [comment]
This has been fixed in the beta branch, once you do a deploy you can use `ironfish rescan --reset`

**Comment by alterkahn** [comment]
> This has been fixed in the beta branch, once we do a deploy you can use `ironfish rescan --reset`

OK, I've already updated my node with the new beta. But seems like the amount of $IRONs on the balance is still displayed incorrectly.

**Comment by daveconcannon** [comment]
After the latest update I get the following when running accounts:balance - 

The account balance is:    $IRON NaN ($ORE NaN)
Amount available to spend: $IRON NaN ($ORE NaN)

I've tried "accounts:rescan --reset", no change.

**Comment by mat-if** [comment]
Closing as I believe this is resolved and this issue is very old
