### ISSUE TITLE
0.1.43 hangs, lost sync, etc - the worst degradation ever since start

### ISSUE THREAD

**Issue by gzivdo** [iron-fish/ironfish#1967]
### What happened?

after upgrade to 0.1.43 status hangs for minutes and very slow sync after rescan. actually it cant sync after rescan finished (less than 24h), 8h sync proceed from 99.2% only to 99.45%.

### Version

0.1.43

### Graffiti

ar2Obyahain

**Comment by gzivdo** [comment]
restart slow too on 0.1.43, can take few minutes

**Comment by gzivdo** [comment]
all operation actually to slow, after few hours of work it hangs itself and losing sync.

**Comment by gzivdo** [comment]
Also it not see new payments without rescan. Checked 3 times, so the mempool even not consistent across nodes.

**Comment by gzivdo** [comment]
1) All operations slow, status and balance can hang or complete in 3-8 minutes.
2) Node hangs completly after few hours of work.
3) Often node cannot connect to network after restart for hours, see 0 peers. the workaround - copy hosts.json from working node, it work only for one restart, then again the same.
4) Sync super slow, after rescan need to restart few times to get synced, it require now 5-20h with few restarts.
5) Payment between nodes (different address) not seen without rescan, i suppose mempool inconsistent now too and network not united (or something similar).

**Comment by holahula** [comment]
Closing due to staleness. If the issue persists in versions `1.0.0+` - please file a new issue
