### ISSUE TITLE
chain:download error

### ISSUE THREAD

**Issue by Midnight95** [iron-fish/ironfish#1972]
### What happened?

I am getting "TypeError: snapshotFile.createWriteStream is not a function" error when I run "ironfish chain:download" command. 
I installed ironfish node from npm, my linux distro is Ubuntu 22.04.1 LTS

### Version

0.1.43

### Debug output

```shell
Iron Fish version               0.1.43 @ 4f2ddb6
Iron Fish library               0.0.20 @ 303e054
Operating system                Linux x64
CPU model(s)                    AMD Ryzen 7 1700 Eight-Core Processor
CPU threads                     16
RAM total                       15.57 GiB
Heap total                      4.01 GiB
Node version                    v16.10.0
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name
Block graffiti                  midnode
Accounts head hash              000000000003b96a14d488d24a7df5c085e8d411655637d6f9a9bf4b51218533
Accounts head in chain          true
Accounts head sequence          34478
```

### Graffiti

midnode

**Comment by hughy** [comment]
Hi @Midnight95 , I'll take a look at this issue and try to get a fix out soon.

In the meantime, there's a workaround you can use to download and import a snapshot:
1. Download the snapshot from https://d1kj1bottktsu0.cloudfront.net/ironfish_snapshot_1659661487895.tar.gz
2. Use `ironfish chain:download --path=<path_to_downloaded_snapshot>` to import the snapshot

**Comment by NullSoldier** [comment]
This should resolve it, https://github.com/iron-fish/ironfish/pull/1980

**Comment by dguenther** [comment]
This is probably it -- Node.js docs indicate [`filehandle.createWriteStream`](https://nodejs.org/api/fs.html#filehandlecreatewritestreamoptions) was added in v16.11.0.
