### ISSUE TITLE
No indicator of error message

### ISSUE THREAD

**Issue by hamza-siddiq** [iron-fish/ironfish#1973]
### What happened?

While running the code, I encountered some errors but there is no indicator for the reason of the errors. Useful error information is being suppressed. In fact, some bugs may exist that we can do nothing about, because there are no indicators of the reason of the errors. There were try/catch blocks that were silently ignoring exceptions. This suppresses information that could be useful otherwise (in debugging for example). 

I had opened a feature request #1940 that had gotten closed, but the PR #1939 that is still open, and would solve this issue. Here is the bug:
![183157587-8fa724bc-b816-4111-aaae-37399d46d59c](https://user-images.githubusercontent.com/92462002/183289355-ded74184-d1ea-4b90-90b7-d91a3564153b.jpeg)

If you feel that this issue still needs to be closed, I'll close the PR associated with it as well. 

### Version

0.1.4.3

### Graffiti

ironfishup

**Comment by wd021** [comment]
says on the same line 'sent an invalid block'. that is the reason

**Comment by lwisne** [comment]
There may be room for more detail here. I'll verify and we can see how that PR addresses this.

**Comment by danield9tqh** [comment]
@hamza-siddiq I appreciate the attempt to contribute to better error messages but I think there needs to be a reason why we need the better error messages. As @wd021 mentioned we can already see that that error is associated with `sent an invalid block` or whatever else is on that same line. 

More specific error messages are usually good but there doesn't have to be a specific error for every case in the code. There are too many cases. There will ALWAYS be generic and unhandled error messages. If they cause other problems with the user experience then that is a reason to open an issue. If the only problem is that the error message is not specific enough then this seems like a solution in search of a problem.
