### ISSUE TITLE
Node sync stalling before 100%

### ISSUE THREAD

**Issue by lwisne** [iron-fish/ironfish#1984]
### What happened?

 Need to instrument sync to debug the RPC stack issues

We have seen various issues concerning this, like https://github.com/iron-fish/ironfish/issues/1979 and https://github.com/iron-fish/ironfish/issues/1967

### Version

0.1.43

**Comment by holahula** [comment]
Closing due to staleness. If the issue persists in versions `1.0.0+` - please file a new issue
