### ISSUE TITLE
telemetry should measure node crashes

### ISSUE THREAD

**Issue by lwisne** [iron-fish/ironfish#1986]
### What happened?

We have no visibility into nodes crashing. Is there a way to measure this?

Possible ideas - peers not responding, spike in dropoffs from node online pings

### Version

0.1.43

**Comment by wd021** [comment]
we update telemetry[ when nodes are stopped](https://github.com/iron-fish/ironfish/blob/master/ironfish/src/telemetry/telemetry.ts#L305-L311). what if run a cron job on the db and any node that is still online without new events in X number of intervals can be set as likely crashed.

**Comment by holahula** [comment]
Closing due to staleness. If the issue persists in versions `1.0.0+` - please file a new issue
