### ISSUE TITLE
Balance is empty after 3 transactions

### ISSUE THREAD

**Issue by alar0n** [iron-fish/ironfish#1988]
### What happened?

I rescaned node, after this i checked balance there was 700+ Iron. 
After this i tryed depositAll. Node sended 3 transactions and deposit was ended with error, what balance is insufficient.
![image](https://user-images.githubusercontent.com/31000576/183582220-997b6b08-791f-4155-98b9-af6bc981c75f.png)
![image](https://user-images.githubusercontent.com/31000576/183582388-dc2f586e-1f71-4e09-83a8-fc5a45b3b0c9.png)

Now need new rescan for next transactions.

My 3 sucess transactions
![image](https://user-images.githubusercontent.com/31000576/183582763-4b91ff28-96eb-47cc-93bc-23a420090766.png)

Node was synced:
![image](https://user-images.githubusercontent.com/31000576/183583002-7388a936-b589-4bd6-bcde-0fe2fbacee21.png)

It turns out that after sending several transactions, you need to rescan the node? This is a very big problem.

### Version

ex 0.1.41

### Debug output

```shell
Iron Fish version               0.1.43 @ src
Iron Fish library               0.0.20 @ src
Operating system                Linux x64
CPU model(s)                    Intel(R) Xeon(R) Gold 6248R CPU @ 3.00GHz
CPU threads                     8
RAM total                       31.35 GiB
Heap total                      4.00 GiB
Node version                    v16.16.0
ironfish in PATH                true
Garbage Collector Exposed       true
Telemetry enabled               true
Node name                       alar0n
Block graffiti                  alar0n
Done in 2.21s.
```

### Graffiti

alar0n

**Comment by hughy** [comment]
The Wallet 2.0 refactor released in [v0.1.48](https://github.com/iron-fish/ironfish/releases/tag/v0.1.48) included significant changes to the way that account balances are stored and calculated.

Please open a new issue if you run into this again!
