### ISSUE TITLE
API workers do not process jobs fasts enough

### ISSUE THREAD

**Issue by lwisne** [iron-fish/ironfish#1990]
### What happened?

API seems to always have a large number of outstanding worker jobs.

Amongst other things, add per job count to admin health check to help monitor.

### Version

0.1.43

**Comment by hughy** [comment]
Most outstanding worker jobs were jobs that had reached their maximum number of attempts and were stuck. I've cleared these from queue by re-queueing the old jobs where necessary.

I updated the admin health check to alert if queued jobs rises above 1000 again.
