### ISSUE TITLE
API points aggregation job is slow

### ISSUE THREAD

**Issue by lwisne** [iron-fish/ironfish#1991]
### What happened?

We have a job that never seems to fully finish and likely backs up everything else. Investigate, and either remove or improve performance.

### Version

0.1.43

**Comment by hughy** [comment]
@lwisne is this the `update_latest_points` job? It looks like p95 runtime for that job is usually <200ms: https://app.datadoghq.com/s/66fa108a-56ce-11ec-a99e-da7ad0900002/fxh-gy4-m5c
