### ISSUE TITLE
accounts:transactions should stream, not render response 

### ISSUE THREAD

**Issue by lwisne** [iron-fish/ironfish#1993]
### What happened?

the rendering does not scale to big wallets, or support other use cases outside of this specific view in the CLI

### Version

0.1.43

**Comment by hamza-siddiq** [comment]
I'll start working on this right away

**Comment by hamza-siddiq** [comment]
Should the streaming of transactions end once all transactions have been outputted? Or should it listen on other events as well?

**Comment by wd021** [comment]
i'd say the latter. 

would also be nice to add flag to scan a block range, the same way we have miners:mined [startBlock] [endBlock]

**Comment by wd021** [comment]
also export option? would be nice to save to csv once there's more than 500 transactions.

**Comment by hughy** [comment]
`accounts:transactions` streams following #2257
