### ISSUE TITLE
Need better transaction tracking

### ISSUE THREAD

**Issue by lwisne** [iron-fish/ironfish#1995]
### What happened?

When will it expire?
When will it be confirmed?
Has it missed blocks due to too-low tx fee?

### Version

0.1.43

**Comment by hamza-siddiq** [comment]
Is this bug regarding the **display** of transactions with the `accounts:transactions` command? Because I think the current code enables all of the three pieces of information you mentioned to be obtained.

**Comment by hughy** [comment]
Closing since we implemented this in transactions CLI changes during Phase 3 (e.g., #2907)
