### ISSUE TITLE
Keep some record on expired transactions

### ISSUE THREAD

**Issue by lwisne** [iron-fish/ironfish#1996]
### What happened?

When a tx expires, it is deleted and there is no mechanism to get information on its expiration. From a user standpoint, it is impossible to see if the tx expired, or if it never existed at all.

Should have some temporary store that allows us to examine expired transactions.

### Version

0.1.43

**Comment by hamza-siddiq** [comment]
I think this can be implemented with relative ease for transactions that are sent to the node (while not expired yet), then expire within the the lifetime of the node in a fixed time window.
However, if you mean keeping ALL expired transactions, this will cause the database to explode in size with no real justifying benefit in my opinion.

**Comment by wd021** [comment]
I think the purpose is to show expired transactions initiated by the user.

**Comment by hughy** [comment]
Wallet 2.0 refactor released in v0.1.48 no longer deletes expired transactions
