### ISSUE TITLE
No individual transaction command to inspect a transaction locally

### ISSUE THREAD

**Issue by lwisne** [iron-fish/ironfish#1998]
### What happened?

Should have a detailed view that allows us to dig into transactions, even after expiration.

### Version

0.1.43

**Comment by wd021** [comment]
accounts:transactions has a optional flag to inspect a specific tx hash, but we do delete expired transactions atm, so that's preventing this..

**Comment by hughy** [comment]
Wallet 2.0 refactor released in v0.1.48 no longer deletes expired transactions
