### ISSUE TITLE
npm install -g ironfish error: git@github.com: Permission denied (publickey)

### ISSUE THREAD

**Issue by fhigher** [iron-fish/ironfish#2035]
### What happened?

npm install -g ironfish

npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/chjj/loady.git
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

Many people can not use this method because of this problem

It should not use the SSH protocol here ( ssh://git @github.com/chjj/loady.git ) to access the GitHub repository. 
It is normal to compile from the source code because the source code uses the HTTPS protocol ( loady "git+https://github.com/chjj/loady.git#semver:~0.0.1" )

### Version

v0.1.43,  v0.1.44

### Graffiti

fhigherfly

**Comment by lwisne** [comment]
Need a bit more detail here. I don't think it's true that _nobody_ can install via npm. What do you think is different about your setup that would be causing permission errors?
