### ISSUE TITLE
Commands correction not working properly

### ISSUE THREAD

**Issue by hamza-siddiq** [iron-fish/ironfish#2041]
### What happened?

When a command is miss-typed, the CLI would suggest a correction. If the correction is accepted, then the CLI would go ahead and execute the command. After the command completes, the CLI would then show an error about the miss-typed command. 

### Version

0.1.44

### Relevant log output

```shell
$ yarn start accounts:creae
yarn run v1.22.19
$ yarn build && yarn start:js accounts:creae
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node --expose-gc bin/run accounts:creae
 ›   Warning: accounts:creae is not a ironfish command.
Did you mean accounts:create? [y/n]: y
Enter the name of the account: void
Creating account void
Account void created with public address cea463a25982ae65fd98bde16f3d36386bc325393d0493c613625e703bcacd1aaa32d34165260df36b9809
Run "ironfish accounts:use void" to set the account as default
 ›   Error: command accounts:creae not found
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Graffiti

ironfishup

**Comment by wd021** [comment]
this has been previously discussed and is ok and not an actual bug. when running from source, you have to deal with these. any solution (like adding --silent) are sub-optimal.

the npm builds aren't affected by this.
