### ISSUE TITLE
Feature: ironfish depositAll.ts     in this loop        getAccountBalance take a long time. can change like this?

### ISSUE THREAD

**Issue by kakathy** [iron-fish/ironfish#2047]
### Description

 while (true) {
//      balanceResp = await this.client.getAccountBalance({ account: accountName })
//      confirmedBalance = Number(balanceResp.content.confirmed)
//      unconfirmedBalance = Number(balanceResp.content.unconfirmed)

      // terminate condition
      if (terminate && unconfirmedBalance < ironToOre(IRON_TO_SEND) + fee) {
        screen.destroy()
        process.exit(0)
      }

      // send transaction
      if (confirmedBalance > ironToOre(IRON_TO_SEND) + fee) {
        try {
          const result = await this.client.sendTransaction({
            fromAccountName: accountName,
            receives: [
              {
                publicAddress: bankDepositAddress,
                amount: ironToOre(IRON_TO_SEND).toString(),
                memo: graffiti,
              },
            ],
            fee: fee.toString(),
            expirationSequenceDelta: expirationSequenceDelta,
          })

          const transaction = result.content
          txs.push(transaction)
        } catch (error: unknown) {
          screen.destroy()
          process.exit(2)
        }
      }
      unconfirmedBalance=unconfirmedBalance-ironToOre(IRON_TO_SEND)-fee
      // wait 30 seconds for next transaction
      await PromiseUtils.sleep(30000)
    }

**Comment by lwisne** [comment]
Can you clarify the problem further instead of going straight to the fix?

**Comment by MrMitch17** [comment]
I will add to this that deposit-all is painfully slow for me.  Like 1 TX per 5 min.

**Comment by hughy** [comment]
The Wallet 2.0 refactor released in [v0.1.48](https://github.com/iron-fish/ironfish/releases/tag/v0.1.48) included significant changes that should have sped up transaction creation

Please open a new issue if you run into this again!
