### ISSUE TITLE
Overflow bug

### ISSUE THREAD

**Issue by wd021** [iron-fish/ironfish#2061]
### What happened?

 An overflow bug processing new transaction, noticed by AREZA on telegram 
 
 <img width="1285" alt="Screenshot 2022-08-13 at 23 00 05" src="https://user-images.githubusercontent.com/2752586/185160268-ddfb2b0c-b3e7-47bb-a2a4-3984c68b8222.png">

### Graffiti

credit to xeonareza

**Comment by AREZA13** [comment]
I
<img width="1059" alt="Снимок экрана 2022-08-18 в 23 14 37" src="https://user-images.githubusercontent.com/88317106/185486338-de50ed60-3710-4fc5-ad88-3c5df09c633a.png">
 want to add that I tried full reinstall of node on new server and have same errors after snapshot is complete

**Comment by AREZA13** [comment]
<img width="1059" alt="Снимок экрана 2022-08-18 в 23 16 54" src="https://user-images.githubusercontent.com/88317106/185486842-954a6ebc-0837-4a74-811d-6966dc9ad056.png">

**Comment by holahula** [comment]
Closing this issue - tracking all overflow bugs in #3314
