### ISSUE TITLE
Missing Phase 1 testnet points

### ISSUE THREAD

**Issue by lwisne** [iron-fish/ironfish#2065]
### What happened?

(From user Louchi) 

https://phase1.testnet.ironfish.network/users/21553 - link to my profile in phase 1 leaderboard. 

https://t.me/louchi_ch/296 - points received
https://t.me/louchi_ch/298 -  points received

https://telegra.ph/Iron-Fish--33mln-investicij-ot-Sequoia-Capital-a16z-slow-ventures-02-07-2 - points received, but there should clearly be 750 points here, not 500. This is obvious. The man just translated the article and got 750 points (in examples), and I conducted an analysis of the project, explained in understandable words to the reader, conducted an analysis of those who subscribe to twitter ironfish, told about where the team previously worked and many other things. 

https://youtu.be/TJLV7rDx1pM - Points not received. On this video I spent about 3-4 days, even if you do not understand Russian, you can go and just scroll through the video and even the pictures and sound quality will be clear that in the video I put a lot of effort.

**Comment by Louchii** [comment]
Hello! It's been 19 days since my problem was published. Maybe you need some more information to make a decision?

**Comment by dguenther** [comment]
I'll follow up with @adi7dev on this.

**Comment by adi7dev** [comment]
@Username-louchi-is-not-available The only rejected entry was Telegram, it has now been processed.
If you have any further queries, feel free to reachout on #questions channel in Discord.
Thanks

**Comment by Username-louchi-is-not-available** [comment]
@adi7dev @dguenther I think you misunderstood me.
I submitted four applications:
1. https://t.me/louchi_ch/296
2. https://t.me/louchi_ch/298
3. https://telegra.ph/Iron-Fish--33mln-investicij-ot-Sequoia-Capital-a16z-slow-ventures-02-07-2
4. https://youtu.be/TJLV7rDx1pM

I got points on 3 of them. On the first, second and third:
1. Yes
2. Yes
3. Yes
4. No

I only didn't get the award for the 4th submission. For the YouTube video. 
![image](https://user-images.githubusercontent.com/84071296/201943474-50e5867b-d7c9-4af0-96b2-697e6486d0c6.png)

**Comment by holahula** [comment]
Closing due to staleness, it is past kyc deadline now
