### ISSUE TITLE
Transaction empty! after import account

### ISSUE THREAD

**Issue by omiDBaghi** [iron-fish/ironfish#2078]
### What happened?

root@VM-bucket-12832-vm-2660:~# ironfish accounts:balance omiD
yarn run v1.22.19
$ yarn build && yarn start:js accounts:balance omiD
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node --expose-gc bin/run accounts:balance omiD
Account - omiD (96396ad)

The balance is: $IRON 0.00000000 ($ORE 0)
Amount available to spend: $IRON 0.00000000 ($ORE 0)
Done in 13.39s.
root@VM-bucket-12832-vm-2660:~# 

![Untitled](https://user-images.githubusercontent.com/3645938/185891005-2e03eaf5-8072-444a-a44c-ae5f70156962.png)

(ironfish accounts:rescan) I have done it twice

### Version

0.1.44

### Debug output

```shell
Iron Fish version               0.1.44 @ src
Iron Fish library               0.0.21 @ src
Operating system                Linux x64
CPU model(s)                    AMD EPYC Processor
CPU threads                     3
RAM total                       7.74 GiB
Heap total                      1.88 GiB
Node version                    v16.17.0
ironfish in PATH                true
Garbage Collector Exposed       true
Telemetry enabled               true
Node name                       omiD
Block graffiti                  omiD
```

### Graffiti

omiD

**Comment by omiDBaghi** [comment]
(ironfish accounts:rescan) I have done it twice

**Comment by hughy** [comment]
@omiDBaghi has this issue continued?

If you run `ironfish debug` with your node stopped, you should see output for `Accounts head sequence`. Is that value behind the head of the chain on your node?

**Comment by hughy** [comment]
Closing this issue as stale.
