### ISSUE TITLE
Account balance depleting despite not doing anything

### ISSUE THREAD

**Issue by srwhitney19** [iron-fish/ironfish#2086]
### What happened?

I've been running my miner on the public pool for ~48 hours. I check every 2-3 hours if my account has enough to deposit and earn a transaction pt.

Strangely, it seems as though my account balance (amount available to spend) randomly decreases in value from time to time, even though I have not sent any transactions or touched my account in anyway. This might be a consequence of pool mining I'm unaware of? Or some type of strange bug

<img width="900" alt="Screen Shot 2022-08-22 at 3 49 53 PM" src="https://user-images.githubusercontent.com/37627499/186032482-6286125d-8d92-46bd-b4a1-a01bbed077b1.png">

### Graffiti

WhittyFish19

**Comment by wd021** [comment]
would be interested to see the status of your node. probably sync is in progress in the background..

**Comment by hughy** [comment]
Closing this issue because we've made significant changes to how the node stores and calculates balances.
