### ISSUE TITLE
Feature: Fix version-bump.js to add a new line

### ISSUE THREAD

**Issue by NullSoldier** [iron-fish/ironfish#2093]
### Description

Our new version-bump script does not add a newline to the end of package.json when writing it out. This means after each release we re-add it back. https://github.com/iron-fish/ironfish/blob/master/tools/version-bump.js

See here, https://github.com/iron-fish/ironfish/pull/2084/files#diff-a4e73c2862e083bfd89c63ceb355d8ee4b2b96ea4bfb3b6843916f854a3d5ea7L114

Bonus points if you also add a lint rule for this for our repository in a separate PR.

**Comment by dguenther** [comment]
Fixed in #2094
