### ISSUE TITLE
Since 0.1.44 node do not see pool payments

### ISSUE THREAD

**Issue by gzivdo** [iron-fish/ironfish#2096]
### What happened?

After upgrade every day my nodes do not see pool payments at all.
Workaround for now:
- rescan
- OR stop node before pool payment made and start after 3h+.
- OR rollback fs to yesterday (actually 3h+ after payment and rollback to just before payment)

I suppose something wrong with mempool or transaction broadcasting code.

### Version

0.1.44

### Graffiti

ar2Obyahain

**Comment by lwisne** [comment]
What do you mean by not "seeing" pool payments? You think your account has received payment but isn't updating locally? Or the pool isn't paying you at all?

What is the output of `ironfish debug` for you?

**Comment by gzivdo** [comment]
Not see locally, it was about week on all my nodes, now it almost ok (may be 1 of few nodes not see each day), but i have similar issue when i sending from node a to node b, it not see part of transactions, i need to wait about 5h then rescan. without it it can stay for a day and nothging changes, it see only part of transactions.

**Comment by gzivdo** [comment]
I see now what you wanted to check in debug, after rescan head is reset, but i supposed that it will be at the highest block in local database. Its affect issue in previous comment, but not to original issue, because node was online without rescan for few days.

**Comment by hughy** [comment]
Closing this issue since we rewrote a lot of the logic for pool payours in #3353.

Please open a new issue if you're continuing to see problems with pool payouts.
