### ISSUE TITLE
Often you cannot spend notes right after they come, you have to wait 3-5h

### ISSUE THREAD

**Issue by gzivdo** [iron-fish/ironfish#2097]
### What happened?

I preparing deposits via rpc and sending from node A to node B.
If i start depositing right after notes become available on node B i very often getting "All decryptable notes should be in the noteToNullifier map" OR "insufficient balance" in a middle of process (not righ after start depositing), then node crash.
But if I wait 3h+ i never get this error.

### Version

0.1.44

### Graffiti

ar2Obyahain

**Comment by gzivdo** [comment]
![изображение](https://user-images.githubusercontent.com/13568002/186461888-1038e269-9978-4183-9bd4-8bdb62fc63ed.png)

**Comment by hughy** [comment]
The Wallet 2.0 refactor released in [v0.1.48](https://github.com/iron-fish/ironfish/releases/tag/v0.1.48) included significant changes to the wallet code and should prevent errors related to `noteToNullifier`

Please open a new issue if you run into this again!
