### ISSUE TITLE
404/incorrect peer dependency?

### ISSUE THREAD

**Issue by muckerscluckers** [iron-fish/ironfish#210]
I get the following error when running command, yarn install.

[3/4] Linking dependencies...
warning " > eslint-config-ironfish-react@0.1.0" has incorrect peer dependency "e
slint-plugin-react@7.20.6".
warning " > eslint-config-ironfish@0.1.0" has incorrect peer dependency "eslint-
plugin-jest@24.0.1".
warning "wrtc@0.4.7" is missing a bundled dependency "node-pre-gyp". This should
 be reported to the package maintainer.
[4/4] Building fresh packages...
[1/9] ⢀ mrmr
[8/9] ⢀ @nestjs/core
[3/9] ⢀ segfault-handler
[4/9] ⢀ wrtc
error C:\Users\anon\desktop\ironfish-master\ironfish-master\node_modules\wrtc:
Command failed.
Exit code: 1
Command: node scripts/download-prebuilt.js
Arguments:
Directory: C:\Users\anon\desktop\ironfish-master\ironfish-master\node_modules\w
rtc
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.13.0
node-pre-gyp info using node@14.17.0 | win32 | ia32
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for "C:\Users\anon\desktop\ironfish-master\iron
fish-master\node_modules\wrtc\build\Release\wrtc.node" (not found)
node-pre-gyp http GET https://node-webrtc.s3.amazonaws.com/wrtc/v0.4.7/Release/w
in32-ia32.tar.gz
node-pre-gyp http 404 https://node-webrtc.s3.amazonaws.com/wrtc/v0.4.7/Release/w
in32-ia32.tar.gz
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://node-
webrtc.s3.amazonaws.com/wrtc/v0.4.7/Release/win32-ia32.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (C:\Users\anon\Desktop\ironf
ish-master\ironfish-master\node_modules\node-pre-gyp\lib\install.js:149:27)
node-pre-gyp ERR! stack     at Request.emit (events.js:388:22)
node-pre-gyp ERR! stack     at Request.onRequestResponse (C:\Users\anon\Desktop
\ironfish-master\ironfish-master\node_modules\request\request.js:1059:10)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:376:20)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming]
 (_http_client.js:647:27)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.
js:126:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:515:22)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:376:20)
node-pre-gyp ERR! stack     at addChunk (internal/streams/readable.js:309:12)
node-pre-gyp ERR! stack     at readableAddChunk (internal/streams/readable.js:28
4:9)
node-pre-gyp ERR! System Windows_NT 10.0.19042
node-pre-gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users
\\anon\\Desktop\\ironfish-master\\ironfish-master\\node_modules\\node-pre-gyp\\
bin\\node-pre-gyp" "install"
node-pre-gyp ERR! cwd C:\Users\dylan\desktop\ironfish-master\ironfish-master\nod
e_modules\wrtc
node-pre-gyp ERR! node -v v14.17.0
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok

can anyone please help?

**Comment by muckerscluckers** [comment]
found a release of the wrtc node that should have worked but upon trying to run the cli, it tells me 

....\node_modules\wrtc\build\Release\wrtc.node is not a valid Win32 application.


so. im still stumped.

**Comment by dguenther** [comment]
Ah, are you using 32-bit Windows? The lack of `node-webrtc` prebuilt modules are blocking platform compatibility on Apple Silicon as well. We're going to be looking at alternatives (likely [node-datachannel](https://github.com/murat-dogan/node-datachannel)) that aren't as complex to compile once we've finished our refactor of blockchain syncing, since we'd definitely like to more easily support additional platforms.

**Comment by dguenther** [comment]
Closing this since we're now using `node-datachannel`, which is easier to build on different platforms.

**Comment by hamzahkhan** [comment]
`[-/6] ⠁ waiting...`
`[-/6] ⠁ waiting...`
`[3/6] ⠁ node-datachannel`
`[-/6] ⠁ waiting...`
`[-/6] ⠁ waiting...`


been running for more than 10 minutes here...
