### ISSUE TITLE
[Transaction status bug] Get completed while it should be forked

### ISSUE THREAD

**Issue by hairtail** [iron-fish/ironfish#2115]
### What happened?

Response from `ironfish accounts:transactions --hash=9c824fe6df89c5e583ac61fd1fd387d0bd37958d98b13d14e9c3c192ba56da64`
```
Transaction: 9c824fe6df89c5e583ac61fd1fd387d0bd37958d98b13d14e9c3c192ba56da64
Status: completed
Miner Fee: x
Fee ($ORE): 500
Spends: 2
```
However, this transaction is mined by a forked block:
https://explorer.ironfish.network/transaction/9c824fe6df89c5e583ac61fd1fd387d0bd37958d98b13d14e9c3c192ba56da64
https://explorer.ironfish.network/blocks/00000000000871aa59fcc759a2e22a3021baa0aab3fad74203c5e92a3a122004

### Version

0.1.44 @

### Graffiti

miningKing

**Comment by wd021** [comment]
was also mined on the main chain

https://explorer.ironfish.network/blocks/00000000000069e0c066fdb340bfa6f0bf4880a4ad79fde1773fc9869216c974

**Comment by hughy** [comment]
Closing since transaction was mined on main chain
