### ISSUE TITLE
Feature: Add blockhash for accounts:transactions --hash=xxx

### ISSUE THREAD

**Issue by hairtail** [iron-fish/ironfish#2116]
### Description

Add blockhash so that we can check whether this block is on mainchain or forked chain.

**Comment by AmberKiso** [comment]
I picked up this one. 
![image](https://user-images.githubusercontent.com/96642073/196875725-49c0c288-eebd-490c-b234-8131cd2f4e8f.png)

**Comment by AmberKiso** [comment]
Got something working (compare hash of last transaction with the first in the list, above).
I'm not sure we want to have the block hash appear in the table by default. A flag (default = off) may keep the display more tidy.

@hairtail is this what you were intending for the enhancement?
![image](https://user-images.githubusercontent.com/96642073/196877765-61834abe-2826-47c6-ba81-d47a9fe2aa1d.png)


TODO: look at accounts:transaction to see if I can make a similar update there.

**Comment by hughy** [comment]
Resolved in #2127
