### ISSUE TITLE
Amount available to spend DROPS

### ISSUE THREAD

**Issue by muhmad-f-k** [iron-fish/ironfish#2133]
### What happened?

So I done full scan with reset. right balance shows both on the balance is: and Amount available to spend: Then when I do one transaction then Amount available to spend drops by alot and if I do one more or two the Amount available to spend goes to zero and it come back little by little with time. 
![iron](https://user-images.githubusercontent.com/22121200/187250640-a20e6118-a974-468d-9d3f-e08f37808732.PNG)

### Version

lastest

**Comment by frode88** [comment]
![iron2](https://user-images.githubusercontent.com/22121200/187253145-e8ae6c81-5399-43a6-8869-60f1682ec2e8.PNG)

**Comment by hughy** [comment]
The Wallet 2.0 refactor released in [v0.1.48](https://github.com/iron-fish/ironfish/releases/tag/v0.1.48) included significant changes to the way that account balances are stored and calculated.

Please open a new issue if you run into this again!
