### ISSUE TITLE
Stop syncing new blocks

### ISSUE THREAD

**Issue by hairtail** [iron-fish/ironfish#2164]
### What happened?

Since 0.1.45, sync is really faster than before, but nodes often stop syncing new blocks. 
Restart works. 

### Version

0.1.45 @ src

### Debug output

```shell
Iron Fish version               0.1.45 @ src
Iron Fish library               0.0.22 @ src
Operating system                Linux x64
CPU model(s)                    AMD Ryzen Threadripper 3960X 24-Core Processor
CPU threads                     48
RAM total                       62.82 GiB
Heap total                      4.01 GiB
Node version                    v16.16.0
ironfish in PATH                false
Garbage Collector Exposed       false
```
```


### Relevant log output

_No response_

### Graffiti

miningKing

**Comment by hughy** [comment]
@hairtail could you provide a little more detail? Does the node crash, or does the syncer just go idle?

**Comment by hairtail** [comment]
> @hairtail could you provide a little more detail? Does the node crash, or does the syncer just go idle?

Node works well, just syncer stop syncing.

**Comment by hughy** [comment]
What indicates to you that the syncer has stopped? Does `ironfish status` show the syncer as idle? Is your node synced with the main chain, or is it behind? Does it look like the syncer has stopped because there isn't any log output?

Note that the node will only produce logging output when adding blocks periodically, so if your node is synced then there won't be as much logging output.

**Comment by hairtail** [comment]
> What indicates to you that the syncer has stopped? Does `ironfish status` show the syncer as idle? Is your node synced with the main chain, or is it behind? Does it look like the syncer has stopped because there isn't any log output?
> 
> Note that the node will only produce logging output when adding blocks periodically, so if your node is synced then there won't be as much logging output.

1. The `ironfish status` shows the syncer is idle while the chain header is behind the one on explorer about 200 height.
2. This node is used as mining node for my pool, my pool can not receive any blockTemplate from this node anymore.

**Comment by D-Elektra** [comment]
Is there any solution for this issue? My node is the same 97-99% all the time, chain download didn't help, restart didnt help...

**Comment by holahula** [comment]
Closing due to staleness. If the issue persists in versions `1.0.0+` - please file a new issue
