### ISSUE TITLE
Explorer query bug (related to forked blocks)

### ISSUE THREAD

**Issue by Ryushka** [iron-fish/ironfish#2168]
### What happened?

When searching for a transaction in the explorer, and the transaction existing in both mainchain block and forked block, it might jump to and display details of the forked block...

Example: 
559e9cc3a2f29761467818a0e1e52eff817f6965fb721893d10171d7b11d6b77  - This tx hash leads to block hash : 000000000003b06346d4210f767537a9ec7fcc74da2845a3c222870bbe97fa03  
Which is forked block...
The same transaction is on the mainchain in block with the hash : 0000000000035ebd7a2892c7cc639d696de0eab47865c98cb2406370aee23afd
![Screenshot from 2022-09-08 14-58-41](https://user-images.githubusercontent.com/113109172/189116476-8e5771a8-587a-471f-8228-1a041ffeac1b.png)

### Version

v0.1.45

### Graffiti

PaRUSaI

**Comment by hairtail** [comment]
Already fixed https://github.com/iron-fish/block-explorer-v2/pull/103

**Comment by hughy** [comment]
This still seems to be an issue: the explorer page transaction hash in the description (https://explorer.ironfish.network/transaction/559e9cc3a2f29761467818a0e1e52eff817f6965fb721893d10171d7b11d6b77) contains the block hash of the forked block (000000000003b06346d4210f767537a9ec7fcc74da2845a3c222870bbe97fa03)
