### ISSUE TITLE
Feature: Wallet restore height

### ISSUE THREAD

**Issue by wd021** [iron-fish/ironfish#2173]
We should add block height metadata to accounts to eliminate the unnecessary scanning of genesis to the height at which the wallet was created. Should also add this to export/import functionality.

**New account Structure**
```
name
spendingKey
incomingViewKey
outgoingViewKey
publicAddress
rescan
restoreHeight
```

Additional thought regarding wallet UX:

Block height isn't very user-friendly for mainstream users. I think this feature would be better exposed to users as selecting the date range when wallet was created and in the backend, we use a mapping to identify the height at which scanning starts.

**Comment by hughy** [comment]
Implemented as account 'birthday' in #3719
