### ISSUE TITLE
[ShallowCopy] RecalculateTarget changes miningRequestBlocks of current miningRequestId

### ISSUE THREAD

**Issue by hairtail** [iron-fish/ironfish#2215]
### What happened?

[SourceCodeHere](https://github.com/iron-fish/ironfish/blob/master/ironfish/src/mining/pool.ts#:~:text=const%20latestBlock%20%3D%20this.miningRequestBlocks.get(this.nextMiningRequestId%20%2D%201))
```
const latestBlock = this.miningRequestBlocks.get(this.nextMiningRequestId - 1)
latestBlock.header.target = BigIntUtils.toBytesBE(newTarget.asBigInt(), 32).toString('hex')
latestBlock.header.timestamp = newTime.getTime()
// timeA
// target & timestamp of this.miningRequestBlocks.get(this.nextMiningRequestId - 1) changes
this.distributeNewBlock(latestBlock)
// timeB
```
Valid shares submitted between timeA and timeB are marked as Invalid.

### Version

0.1.47 @ src

### Graffiti

miningKing

**Comment by mat-if** [comment]
Fixed in #2216 🙌 

Thanks!
