### ISSUE TITLE
Stop syncing 0.1.47

### ISSUE THREAD

**Issue by hairtail** [iron-fish/ironfish#2236]
### What happened?

```
Version              0.1.47 @ src
Node                 STARTED
Memory               Heap: 433.23 MiB -> 473.46 MiB / 4.00 GiB (10.6%), RSS: 4.94 GiB (2.0%), Free: 241.84 GiB (4.0%)
P2P Network          CONNECTED - In: 56.53 KB/s, Out: 83.27 KB/s, peers 49
Mining               STARTED - 0 miners, 0 mined
Mem Pool             Size: 86844 tx, Bytes: 132.81 MiB
Syncer               IDLE - avg time to add block 2929.95 ms
Blockchain           000000000000077513ecf806001d0bebcd9504c32b65cd179a0eee4e3898d279 (194993), Since HEAD: 6h 12m (SYNCED)
Accounts             000000000000077513ecf806001d0bebcd9504c32b65cd179a0eee4e3898d279 (194993)
Telemetry            STARTED - 86079 <- 1 pending
Workers              STARTED - 0 -> 1 / 315 - 10.52 jobs Δ, 32.94 jobs/s
```

### Version

0.1.47 @ src

### Debug output
```
Iron Fish version               0.1.47 @ src
Iron Fish library               0.0.24 @ src
Operating system                Linux x64
CPU model(s)                    AMD Ryzen Threadripper 3970X 32-Core Processor
CPU threads                     64
RAM total                       251.84 GiB
Heap total                      3.98 GiB
Node version                    v16.15.1
ironfish in PATH                false
Garbage Collector Exposed       false
Telemetry enabled               true
Accounts head hash              00000000000070f70efc51e0c84c9b1338dc48eae6f973e8f543a0eea6b3f448
Accounts head in chain          true
Accounts head sequence          195279
```

### Graffiti

miningKing

**Comment by hairtail** [comment]
stop again after restart.

**Comment by terrancewong** [comment]
this is #2236

**Comment by hughy** [comment]
> this is #2236

Thanks! Updated to 2164!

**Comment by Shekelme** [comment]
I observe the same behavior of my nodes. The nodes run on dedicated physical servers, Threadripper PRO 3955WX processors, the DB runs on NVME. 512 GB of DDR4-3200 memory.

**Comment by leoncryp** [comment]
I confirm same issue with rescan --reset.
8 days to scan while node is running.
0.1.49. metal rig, Ryzen 3600, 32gb ram, 1tb nvme. Linux Mint.
after about the 7th day, node went out of sync.

1-2 days to rescan --reset. if i turn the node off
this was running node version .47 or .46 about a month ago.

**Comment by D-Elektra** [comment]
Guys if somebody knows how to fix the sync, please share. Its been a month I cannot sync and cannot send any transactions.

**Comment by leoncryp** [comment]
> Guys if somebody knows how to fix the sync, please share. Its been a month I cannot sync and cannot send any transactions.

change blocksPerMessage from 20 to 5, this help me and other people a lot regards sync.

stop your node
yarn --cwd ~/ironfish/ironfish-cli/ ironfish config:set blocksPerMessage 5

**Comment by D-Elektra** [comment]
Didn't help 10 and didn't help 5... I almost gave up with sync...

**Comment by holahula** [comment]
Closing due to staleness. If the issue persists in versions `1.0.0+` - please file a new issue
