### ISSUE TITLE
Server sent mining.wait_for_work message - hangs miners.

### ISSUE THREAD

**Issue by UnNicky** [iron-fish/ironfish#2280]
### What happened?

My miner works for Iron Fish Pool, under Alerts monitoring channel in discord it shows:

 — Today at 5:44 PM
Disconnected from node unexpectedly. Reconnecting.
Successfully connected to node
 — Today at 5:52 PM
Status for mining pool 'Iron.Fish.Pool':
    Hashrate: 12.45 GH/s
    Miners: 1520
    Shares pending: 424886
    Clients: 4478
    Bans: 3378

Meaning something happened with the node owning the pool, which leads miner to disconnect:
Sep 30 17:37:45 unnicky ironfish[2650931]: Found share: 0000059b1769d759 3 86.96 MH/s
Sep 30 17:44:03 unnicky ironfish[2650931]: Server sent mining.wait_for_work message

And after the node and the pool became working and available my miner didn't receive any work until I manually restart it:
Sep 30 17:44:03 unnicky ironfish[2650931]: Server sent mining.wait_for_work message
Sep 30 20:41:41 unnicky ironfish[3003077]: Starting to mine with public address: xxxx at pool 54.90.34.95:9034
Sep 30 20:41:41 unnicky ironfish[3003077]: Connecting to pool...
Sep 30 20:41:41 unnicky ironfish[3003077]: Successfully connected to pool
Sep 30 20:41:41 unnicky ironfish[3003077]: Subscribing to pool to receive work
Sep 30 20:41:41 unnicky ironfish[3003077]: Server sent mining.subscribed message
Sep 30 20:41:41 unnicky ironfish[3003077]: Server has identified us as client 12200
Sep 30 20:41:41 unnicky ironfish[3003077]: Server sent mining.set_target message
Sep 30 20:41:41 unnicky ironfish[3003077]: Server sent mining.notify message
Sep 30 20:41:41 unnicky ironfish[3003077]: new work 00000000494cff9a3f4f473f91d116af7382c45e653facfeef85b8f43d9d6b64 3 0 H/s
Sep 30 20:42:32 unnicky ironfish[3003077]: Found share: 000000011b42cfe3 3 90.21 MH/s

### Version

0.1.47

### Debug output

```shell
Iron Fish version               0.1.47 @ 0efb836
Iron Fish library               0.0.24 @ 0efb836
Operating system                Linux x64
CPU model(s)                    Intel(R) Xeon(R) CPU E5-2695 v2 @ 2.40GHz
CPU threads                     48
RAM total                       125.85 GiB
Heap total                      4.01 GiB
Node version                    v16.17.1
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       UnNicky
Block graffiti                  UnNicky
```

### Graffiti

UnNicky

**Comment by holahula** [comment]
Closing due to staleness. If the issue persists please file a new issue
