### ISSUE TITLE
Error: getLatestHeadHash: No header found

### ISSUE THREAD

**Issue by CooperNic** [iron-fish/ironfish#2304]
### What happened?

1) I have downloaded snapshot (chain:download):
~$ docker run --rm --tty --interactive --name iron_fish_node --network host --volume $HOME/.ironfish:/root/.ironfish ghcr.io/iron-fish/ironfish:latest chain:download
Download 66.65 GB snapshot to update from block 50776 to 214889?
Are you sure? (Y)es / (N)o: y
Downloading snapshot from https://ironfish-snapshots.s3-accelerate.amazonaws.com/ironfish_snapshot_1665015137796.tar.gz to /root/.ironfish/temp/ironfish_snapshot_1665015137796.tar.gz
Downloading snapshot: [████████████████████████████████████████] 100% | 66.65 GB / 66.65 GB | 45.80 MB/s | ETA: soon
Removing existing chain data at /root/.ironfish/databases/default before importing snapshot... done
Unzipping snapshot: [████████████████████████████████████████] 100% | 39530 / 39530 entries | 105.67/s | ETA: soon
Cleaning up snapshot file at /root/.ironfish/temp/ironfish_snapshot_1665015137796.tar.gz... done

2) Then run _ironfish start_ the and the error message appeared:
Error: getLatestHeadHash: No header found for 0000000000007d5e20fb5669afaaac93a4e3e29874dbcc4562a2b5e367b98fc7

### Version

0.1.49

### Debug output

```shell
Error: Database is not open. Call IDatabase.open() first
    at LevelupDatabase.get levelup [as levelup] (/usr/src/app/node_modules/@ironfish/sdk/build/src/storage/levelup/database.js:31:19)
    at LevelupStore.getAllIter (/usr/src/app/node_modules/@ironfish/sdk/build/src/storage/levelup/store.js:82:32)
    at getAllIter.next (<anonymous>)
    at WalletDB.loadHeadHashes (/usr/src/app/node_modules/@ironfish/sdk/build/src/wallet/walletdb/walletdb.js:137:46)
    at loadHeadHashes.next (<anonymous>)
    at Debug.outputRequiringDB (/usr/src/app/build/src/commands/debug.js:77:48)
    at Debug.start (/usr/src/app/build/src/commands/debug.js:37:57)
    at async Debug.run (/usr/src/app/build/src/command.js:24:13)
    at async Debug._run (/usr/src/app/node_modules/@oclif/core/lib/command.js:81:22)
    at async Config.runCommand (/usr/src/app/node_modules/@oclif/core/lib/config/config.js:272:25)
```

### Relevant log output

```shell
Version       0.1.49 @ ec57ed3
Node Name     Cooper
Graffiti      Cooper
Peer Identity mNBpjXQvAYdYfGsRKp9VswZ5AGODau4ZIa8GwT+3Ig4=
Peer Agent    ironfish/0.1.49/ec57ed3
Peer Port     9045
Bootstrap     test.bn1.ironfish.network

Error: getLatestHeadHash: No header found for 0000000000007d5e20fb5669afaaac93a4e3e29874dbcc4562a2b5e367b98fc7
    at Function.isNotNull (/usr/src/app/node_modules/@ironfish/sdk/build/src/assert.js:23:19)
    at Wallet.getLatestHeadHash (/usr/src/app/node_modules/@ironfish/sdk/build/src/wallet/wallet.js:766:29)
    at async Wallet.load (/usr/src/app/node_modules/@ironfish/sdk/build/src/wallet/wallet.js:127:36)
    at async Wallet.open (/usr/src/app/node_modules/@ironfish/sdk/build/src/wallet/wallet.js:112:9)
    at async IronfishNode.openDB (/usr/src/app/node_modules/@ironfish/sdk/build/src/node.js:185:13)
    at async Object.waitForOpen (/usr/src/app/node_modules/@ironfish/sdk/build/src/utils/node.js:16:13)
    at async Start.start (/usr/src/app/build/src/commands/start.js:96:9)
    at async Start.run (/usr/src/app/build/src/command.js:24:13)
    at async Start._run (/usr/src/app/node_modules/@oclif/core/lib/command.js:81:22)
    at async Config.runCommand (/usr/src/app/node_modules/@oclif/core/lib/config/config.js:272:25)
```

### Graffiti

Cooper

**Comment by hughy** [comment]
@CooperNic and @airj1012 , to help me debug this issue would you please share output for the following:

- `ironfish config:get databaseName`

- The contents of the `<datadir>/databases` directory

Thank you!

**Comment by airj1012** [comment]
![image](https://user-images.githubusercontent.com/64874325/194390719-85252b1b-bb23-4709-b4e6-49d7eddf13d1.png)
![image](https://user-images.githubusercontent.com/64874325/194390737-7acc35df-c462-45cc-a077-8d36ba371e43.png)

**Comment by hughy** [comment]
Thanks @airj1012 !

It looks like the data from the snapshot may be in a different place than the 'datadir' that your node is using: there are only a few files in `.ironfish/databases/default`, but there should be many.

You can set the datadir that your node uses using the `--datadir=` flag

**Comment by airj1012** [comment]
I have two nodes right now. One on my C: drive and one on my D: drive. I initially set up on C: and used the address to mine. However I realized that I didn't have enough disc space on C, so I moved files to D. I've been using D just fine. However...my transactions are going to go to my address from my C: drive. Thats why I'm trying to recover it. It's not a ton of coins, but I'm trying to get that one working again so I can get access to that address (so I can either make a deposit or export the address). I tried to reinstall ironfish on C, but not sure that I did it correctly. Starting the sync from scratch on C would be OK if I could get the address to export. Any thoughts on how to achieve this?

**Comment by hughy** [comment]
@airj1012 you might need to copy your accounts data from `.ironfish/accounts` to a datadir where you have the chain data.

If you don't need the accounts data from the node on your D: drive you can overwrite your accounts data in that datadir with the accounts from your C: drive. Otherwise I'd suggest making a copy of the `accounts` directory on the D: drive before copying.

This is definitely a bug, and prevents even resetting the account database through normal commands!

**Comment by airj1012** [comment]
OK thanks. That makes sense.

And just so I'm clear, when using datadir, you really need to have a copy of all the files there, correct? You're not just accessing the blockchain databases, but all the files (.json files, etc). Right now I have essentially one copy of ".ironfish" on my C drive and another on my D drive. I'm not just using D to access the blockchain databases. Just wanted to make sure I'm doing it correctly!

I'll copy my working ".ironfish" director on my D drive, to another area on my D drive. And then copy over the files from the "accounts" folder from my now not working node, so I can extract the address that I was mining to.

Thanks for the help and sorry if this is bogging you down. Very helpful for me!

**Comment by hughy** [comment]
Happy to help!

> And just so I'm clear, when using datadir, you really need to have a copy of all the files there, correct?

Correct -- the datadir should have all of the files that the node needs in order to run. That includes separate databases for blockchain data (in `<datadir>/databases`) and for accounts data (in `<datadir>/accounts`)

**Comment by CooperNic** [comment]
> @CooperNic and @airj1012 , to help me debug this issue would you please share output for the following:
> 
@hughy sorry, it was my mistake.  The command `ironfish chain:download` required more disk space then I expected. When I extended the partition size from 127Gb to 140GB, downloaded and unzipped the snapshot again, the `ironfish start` command runned without errors:

_Version       0.1.49 @ ec57ed3
Node Name     Cooper
Graffiti      Cooper
Peer Identity mNBpjXQvAYdYfGsRKp9VswZ5AGODau4ZIa8GwT+3Ig4=
Peer Agent    ironfish/0.1.49/ec57ed3
Peer Port     9045
Bootstrap     test.bn1.ironfish.network

WebSocket server started at :::9045
Connected to the Iron Fish network
Starting sync from zBcFf0N (ShinBoard). work: +1112525919902194813, ours: 214889, theirs: 216114
Finding ancestor using linear search on last 3 blocks starting at 00000...b5dfc (214889) from peer zBcFf0N (ShinBoard) at 216114
Found peer zBcFf0N (ShinBoard) ancestor 00000...b5dfc, syncing from 214889 -> 216114 (1225) after 1 requests
Requesting 20 blocks starting at 00000...b5dfc (214889) from zBcFf0N (ShinBoard)
Added block seq: 214900, hash: 00000...845e5, txs: 52, progress: 99.32%, time: 934.7ms_

**Comment by hughy** [comment]
Glad that you were able to get it working!

**Comment by airj1012** [comment]
> This is definitely a bug, and prevents even resetting the account database through normal commands!

Can I get some bug bounty points?!

By the way your work around worked. Thanks. Waiting for my main node to rescan all the accounts and then I can import. Thanks for the support.

**Comment by D-Elektra** [comment]
Guys, I need some help as well. 
Having the same issue. downloaded snapshot but all previous files were deleted. I have done the migration and tried to restart, upgrade many times.
But I cannot start the node for 3 days.
The database directory is the same as before .ironfish/databases/default
No other nodes in this server. Where to find a solution? Cannot download, and cannot start...

ironfish chain:download
Error: getLatestHeadHash: No header found for 00000000000b4c0d2d32cae86be0e3490d9a9ac9e7dc0c3c2d39addfb1359e1a
    at Function.isNotNull (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/assert.js:23:19)
    at Wallet.getLatestHeadHash (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/wallet/wallet.js:766:29)
    at async Wallet.load (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/wallet/wallet.js:127:36)
    at async Wallet.open (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/wallet/wallet.js:112:9)
    at async IronfishNode.openDB (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/node.js:185:13)
    at async Object.waitForOpen (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/utils/node.js:16:13)
    at async Download.start (/usr/lib/node_modules/ironfish/build/src/commands/chain/download.js:24:9)
    at async Download.run (/usr/lib/node_modules/ironfish/build/src/command.js:24:13)
    at async Download._run (/usr/lib/node_modules/ironfish/node_modules/@oclif/core/lib/command.js:81:22)
    at async Config.runCommand (/usr/lib/node_modules/ironfish/node_modules/@oclif/core/lib/config/config.js:272:25)

**Comment by CooperNic** [comment]
@D-Elektra before downloading a snapshot, you need to make sure that there is enough free disk space on the drive with the `ironfish` folder. It needs  at least 140 GB of free space on your device to download and unzip a snapshot.
You also can change output path to download the snapshot file using command-line flag `-o, --outputPath=<value>   `


> Guys, I need some help as well. Having the same issue. downloaded snapshot but all previous files were deleted. I have done the migration and tried to restart, upgrade many times. But I cannot start the node for 3 days. The database directory is the same as before .ironfish/databases/default No other nodes in this server. Where to find a solution? Cannot download, and cannot start...
> 
> ironfish chain:download Error: getLatestHeadHash: No header found for 00000000000b4c0d2d32cae86be0e3490d9a9ac9e7dc0c3c2d39addfb1359e1a at Function.isNotNull (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/assert.js:23:19) at Wallet.getLatestHeadHash (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/wallet/wallet.js:766:29) at async Wallet.load (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/wallet/wallet.js:127:36) at async Wallet.open (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/wallet/wallet.js:112:9) at async IronfishNode.openDB (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/node.js:185:13) at async Object.waitForOpen (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/utils/node.js:16:13) at async Download.start (/usr/lib/node_modules/ironfish/build/src/commands/chain/download.js:24:9) at async Download.run (/usr/lib/node_modules/ironfish/build/src/command.js:24:13) at async Download._run (/usr/lib/node_modules/ironfish/node_modules/@oclif/core/lib/command.js:81:22) at async Config.runCommand (/usr/lib/node_modules/ironfish/node_modules/@oclif/core/lib/config/config.js:272:25)

**Comment by hughy** [comment]
> > This is definitely a bug, and prevents even resetting the account database through normal commands!
> 
> Can I get some bug bounty points?!
> 
> By the way your work around worked. Thanks. Waiting for my main node to rescan all the accounts and then I can import. Thanks for the support.

@airj1012 please create a separate GitHub issue and submit the form here for testnet points: https://docs.google.com/forms/d/e/1FAIpQLSfMerCUGGQWNDxss2Ay_iVG35zpCHTFxe5tpXLI-1yqLgADnA/viewform

**Comment by airj1012** [comment]
> @airj1012 please create a separate GitHub issue and submit the form here for testnet points:

Thanks. Created and submitted.

https://github.com/iron-fish/ironfish/issues/2328
