### ISSUE TITLE
WriteError: IO error: Structure needs cleaning

### ISSUE THREAD

**Issue by belgeran** [iron-fish/ironfish#2316]
### What happened?

Was syncing normally, but it started having error.

Requesting 10 blocks starting at 00000...63837 (217359) from a08eQIA (merab)
Stopping sync from a08eQIA (merab) due to WriteError: IO error: /home/ubuntu/.ironfish/databases/default/9498483.ldb: Structure needs cleaning
    at /home/ubuntu/.nvm/versions/node/v16.17.0/lib/node_modules/ironfish/node_modules/levelup/lib/levelup.js:274:23
Peer a08eQIA (merab) disconnected (DISCONNECTED) while syncing.

Stopping and starting the node again resolves the issue.. but if thats the case, the node should be able to auto heal or recover.

### Version

0.1.49 @ ec57ed3

### Debug output

```shell
Iron Fish version                  0.1.49 @ ec57ed3
Iron Fish library                  0.0.26 @ ec57ed3
Operating system                   Linux x64
CPU model(s)                       Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
CPU threads                        8
RAM total                          15.30 GiB
Heap total                         2.01 GiB
Node version                       v16.17.0
ironfish in PATH                   true
Garbage Collector Exposed          false
Telemetry enabled                  true
Node name                          iron_fish
Block graffiti                     iron_fish
Account 0586e9 uuid                0586e985-d527-40af-9680-99d9a74be527
Account 0586e9 name                zyvier
Account 0586e9 head hash           00000000000411df886e7b257c511b05b9e7a210476da09edc7d51bf42cbacb8
Account 0586e9 head in chain       true
Account 0586e9 sequence            68122
```

### Graffiti

iron_fish

**Comment by belgeran** [comment]
another error today:

Finished syncing 2 blocks from Z2Uib/Y, skipped 1

/home/ubuntu/.nvm/versions/node/v16.17.0/lib/node_modules/ironfish/node_modules/levelup/lib/levelup.js:274
      return callback(new WriteError(err))
                      ^
Error [WriteError]: IO error: /home/ubuntu/.ironfish/databases/default/10201438.ldb: Structure needs cleaning
    at /home/ubuntu/.nvm/versions/node/v16.17.0/lib/node_modules/ironfish/node_modules/levelup/lib/levelup.js:274:23 {
  [cause]: undefined
}

**Comment by hughy** [comment]
`Structure needs cleaning` often indicates file system corruption on Linux.

You may need to run `chain:download` with a fresh datadir, and then copy the data over to your database at `/home/ubuntu/.ironfish/databases/default`
