### ISSUE TITLE
Syncing 

### ISSUE THREAD

**Issue by omiDBaghi** [iron-fish/ironfish#2338]
### What happened?

Version              0.1.49 @ ec57ed3
Node                 STARTED
Node Name            omiD
Block Graffiti       omiD
Memory               Heap: 77.33 MiB -> 114.20 MiB / 1.88 GiB (4.0%), RSS: 544.96 MiB (14.2%), Free: 2.80 GiB (25.0%)
CPU                  Cores: 3, Current: 81.1% 
P2P Network          CONNECTED - In: 41.40 KB/s, Out: 852 B/s, peers 48   
Mining               STARTED - 1 miners, 0 mined
Mem Pool             Size: 0 tx, Bytes: 0 B
Syncer               SYNCING - 0.38 blocks per seconds, avg time to add block 579.11 ms, progress: 0.69%
Blockchain           00000000000246cc74dcadd7d554c57fbb80a20840981fc6848a8b7fb75c2540 (1381), **`Since HEAD: 7h 22m (SYNCED)`**
Accounts             00000000000246cc74dcadd7d554c57fbb80a20840981fc6848a8b7fb75c2540 (1381)
Telemetry            STARTED - 163 <- 0 pending
Workers              STARTED - 0 -> 0 / 2 - 0 jobs Δ, 1.31 jobs/s      

### Version

0.1.49

### Debug output

```shell
Iron Fish version               0.1.49 @ ec57ed3
Iron Fish library               0.0.26 @ ec57ed3
Operating system                Linux x64
CPU model(s)                    AMD EPYC Processor
CPU threads                     3
RAM total                       7.74 GiB
Heap total                      1.88 GiB
Node version                    v16.17.1
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       omiD
Block graffiti                  omiD
```

### Graffiti

omiD

**Comment by hughy** [comment]
Same issue as #2326 

The underlying cause here is that the node stops receiving blocks and falls behind. We're working on addressing syncing issues!

**Comment by danield9tqh** [comment]
Closing this. I've posted an update on https://github.com/iron-fish/ironfish/issues/2326
