### ISSUE TITLE
ironfish node synced but fall behind

### ISSUE THREAD

**Issue by darrencavell** [iron-fish/ironfish#2343]
### What happened?

ironfish node does not really synced, i just realized it is 10h away from head

Version              0.1.49 @ ec57ed3
Node                 STARTED
Node Name            DarrzDC
Block Graffiti       DarrzDC
Memory               Heap: 609.38 MiB -> 678.04 MiB / 2.01 GiB (29.5%), RSS: 3.09 GiB (41.2%), Free: 3.18 GiB (57.8%)
CPU                  Cores: 16, Current: 197.5%
P2P Network          CONNECTED - In: 31.27 KB/s, Out: 10.49 KB/s, peers 49
Mining               STARTED - 0 miners, 0 mined
Mem Pool             Size: 174857 tx, Bytes: 269.03 MiB
Syncer               SYNCING - 0 blocks per seconds, avg time to add block 35395.55 ms
Blockchain           00000000000025e14a5cd9968c0516c82c615e4e7868f79d6eaaa55432daf3ed (226086), **Since HEAD: 10h 44m (SYNCED)**
Accounts             0000000000004e092e4bb817f22996ced915d17533e04616c8df2aebfa5c2bee (225882)
Telemetry            STARTED - 68181 <- 230 pending
Workers              STARTED - 0 -> 0 / 6 - 3.77 jobs Δ, 8.12 jobs/s

### Version

0.1.49

### Debug output

```shell
Iron Fish version               0.1.49 @ ec57ed3
Iron Fish library               0.0.26 @ ec57ed3
Operating system                Linux x64
CPU model(s)                    11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz
CPU threads                     16
RAM total                       7.53 GiB
Heap total                      2.01 GiB
Node version                    v16.17.1
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       DarrzDC
Block graffiti                  DarrzDC
```

### Graffiti

DarrzDC

**Comment by danield9tqh** [comment]
Closing this. I've posted an update on https://github.com/iron-fish/ironfish/issues/2326
