### ISSUE TITLE
Show Last 10-100 Transactions

### ISSUE THREAD

**Issue by airj1012** [iron-fish/ironfish#2347]
### Description

Trying to understand the status of recent transactions. It would be good to see the most recent transactions so you could look at the status without seeing a full list of transactions (ironfish accounts:transactions --show=100)

Similarly, how are the transactions sorted? Doesn't appear to be sequential.

**Comment by hughy** [comment]
I think that something like this would definitely be useful!

Right now the output of transactions in the list is ordered by the database keys of the transactions rather than sequentially.
