### ISSUE TITLE
Memory Leak (Heap)

### ISSUE THREAD

**Issue by aswhale** [iron-fish/ironfish#2350]
### What happened?

Latest node version (49) has a memory leak.  After 2 days of running, the node cannot release the memory back to the system.    Windows 11 Home Laptop.  Seems to happen if I leave the laptop unattended for extended time, meaning lift the screen up.  I have noticed when I open the screen, task manager shows a bump in memoery useage (assume due to video display kicking on), after sometime, it will go back down to previous levels of memory.

![Memory Crash](https://user-images.githubusercontent.com/114945271/195911934-a7436961-8af6-459b-9eac-d190c80118a4.png)

This has also persisted in previous versions as well.  Note block height for time frame reference since I forgot to hit debug command

![capture1](https://user-images.githubusercontent.com/114945271/195912071-50fe8f7a-e1ca-48d5-abb5-bbe8cdc06919.png)

### Debug output

```shell
Iron Fish version                  0.1.49 @ ec57ed3
Iron Fish library                  0.0.26 @ ec57ed3
Operating system                   Windows_NT x64
CPU model(s)                       AMD Ryzen 9 4900H with Radeon Graphics
CPU threads                        16
RAM total                          15.36 GiB
Heap total                         2.01 GiB
Node version                       v16.17.0
ironfish in PATH                   true
Garbage Collector Exposed          false
Telemetry enabled                  true
Node name                          **
Block graffiti                     **
Account a0a97b uuid                **
Account a0a97b name                **
Account a0a97b head hash           **
Account a0a97b head in chain       true
Account a0a97b sequence            225481
```

### Relevant log output

```shell
1: 00007FF75A93B1EF v8::internal::CodeObjectRegistry::~CodeObjectRegistry+123599
 2: 00007FF75A8C8BA6 v8::internal::MicrotaskQueue::GetMicrotasksScopeDepth+65206
 3: 00007FF75A8C9C7D node::OnFatalError+301
 4: 00007FF75B1FC20E v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF75B1E67ED v8::SharedArrayBuffer::Externalize+781
 6: 00007FF75B089DCC v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1468
 7: 00007FF75B086EE4 v8::internal::Heap::CollectGarbage+4244
 8: 00007FF75B084860 v8::internal::Heap::AllocateExternalBackingStore+2000
 9: 00007FF75B0A93E6 v8::internal::Factory::NewFillerObject+214
10: 00007FF75ADDBB85 v8::internal::DateCache::Weekday+1797
11: 00007FF75B289F01 v8::internal::SetupIsolateDelegate::SetupHeap+494417
12: 00007FF75B21EE0E v8::internal::SetupIsolateDelegate::SetupHeap+55902
13: 000002763483D5BA
```

### Graffiti

aswhalesCook

**Comment by holahula** [comment]
Closing due to staleness. If the issue persists in versions `1.0.0+` - please file a new issue
