### ISSUE TITLE
Confirmed Transactions - 404 Explorer

### ISSUE THREAD

**Issue by airj1012** [iron-fish/ironfish#2356]
### What happened?

Trying to view the details of my deposits is leading to 404 errors on the explorer website.

See attached video.

![image](https://user-images.githubusercontent.com/64874325/195994306-357a1ee8-8ef3-401b-9e08-493bf1ecf637.png)

https://www.dropbox.com/s/iejpe0c44k703qt/airj1012%20-%20Google%20Chrome%202022-10-15%2011-18-15.mp4?dl=0

### Graffiti

airj1012

**Comment by hughy** [comment]
Can you paste the hash(es) of transactions that you're having trouble with?

The node that we run to update the block explorer is running into some syncing issues and has fallen about 10 hours behind the head of the chain.

I've restarted the node, so hopefully it will start to catch up quickly!

**Comment by airj1012** [comment]
3df1e59b4e6d22b6ac97798153d9ccf145ea8bea1c09e4bc88de5a9a27a2bc56
27ec008755e1dedb7c67c9baedae21b0a9463e835439f02b50615da9c1d825d0
4d0b76b47884bb650f24bdd8d87e6f85236f8841e6183ca4b08a0f5945d71fb5
55930a64e4939d708e0d2b20536dc66578f576fbbea6bc7895d7f558f332edef

Just to name a few...

**Comment by airj1012** [comment]
Do tickets like these count toward bug reports?

**Comment by hughy** [comment]
It looks like the hashes you pasted show up on the block explorer now!

> Do tickets like these count toward bug reports?

It's helpful to know when the block explorer falls behind, but we generally only award points for issues that result in fixes or improvements to the code.

**Comment by airj1012** [comment]
Still happening...

6dd2a80b58bfdc9af6e2ae19b2a158a5ba7f360eb8ede3758ac03ef909dcbc8d
64239885904fc927ebb6050a34dc8ad2ce64aad52a536d66cde560f7be4557f4

**Comment by hughy** [comment]
Both of these hashes appear on the block explorer now.
