### ISSUE TITLE
brew install error

### ISSUE THREAD

**Issue by qq234876317** [iron-fish/ironfish#2380]
### What happened?

Warning: Bottle missing, falling back to the default domain...
==> Downloading https://ghcr.io/v2/homebrew/core/node/16/manifests/16.17.0
Already downloaded: /Users/zouzhe/Library/Caches/Homebrew/downloads/55d9241b5f87af5d597454dab571ffcb6b12e0b5fe53493cd19bb1976d11ab6e--node@16-16.17.0.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/node/16/blobs/sha256:8058af2eb3
Already downloaded: /Users/zouzhe/Library/Caches/Homebrew/downloads/a4c8ef4b8ab01e16f5e205948725b71e0b35e437795fca2c8bb7e7e839b29684--node@16--16.17.0.arm64_monterey.bottle.tar.gz
==> Downloading https://ironfish-cli.s3.amazonaws.com/ironfish-cli-ec57ed3.tar.g
Already downloaded: /Users/zouzhe/Library/Caches/Homebrew/downloads/e0e8b13b1b6bfd828f481b2a61ee9e58d67894e4bf47e98fb1a60175aeddf4f2--ironfish-cli-ec57ed3.tar.gz
==> Installing ironfish from iron-fish/brew
==> Installing dependencies for iron-fish/brew/ironfish: icu4c, libnghttp2, libuv, ca-certificates, openssl@1.1 and node@16
==> Installing iron-fish/brew/ironfish dependency: icu4c
==> Pouring icu4c-70.1.arm64_monterey.bottle.tar.gz
Error: No such file or directory @ rb_sysopen - /Users/zouzhe/Library/Caches/Homebrew/downloads/dc354616d9d47a48298e44e175dbd58df0adee89833512aafa9060a8b53c5ba7--icu4c-70.1.arm64_monterey.bottle.tar.gz

**Comment by ygao76** [comment]
Can you provide full log of the output? Also what command are you running

**Comment by qq234876317** [comment]
That well, thanks!
