### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by qq234876317** [iron-fish/ironfish#2381]
### What happened?

npm WARN deprecated @types/minipass@3.3.5: This is a stub types definition. minipass provides its own type definitions, so you do not need this installed.
npm ERR! code 2
npm ERR! path /Users/zouzhe/.nvm/versions/node/v16.14.2/lib/node_modules/ironfish/node_modules/node-datachannel
npm ERR! command failed
npm ERR! command sh -c prebuild-install || (npm install --ignore-scripts && npm run _prebuild)
npm ERR! added 609 packages, removed 13 packages, changed 45 packages, and audited 657 packages in 36s
npm ERR!
npm ERR! 64 packages are looking for funding
npm ERR!   run `npm fund` for details
npm ERR!
npm ERR! 4 high severity vulnerabilities
npm ERR!
npm ERR! To address all issues (including breaking changes), run:
npm ERR!   npm audit fix --force
npm ERR!
npm ERR! Run `npm audit` for details.
npm ERR!
npm ERR! > node-datachannel@0.3.4 _prebuild
npm ERR! > prebuild --backend cmake-js
npm ERR!
npm ERR! [
npm ERR!   '/Users/zouzhe/.nvm/versions/node/v16.14.2/bin/node',
npm ERR!   '/Users/zouzhe/.nvm/versions/node/v16.14.2/lib/node_modules/ironfish/node_modules/node-datachannel/node_modules/.bin/cmake-js',
npm ERR!   'rebuild',
npm ERR!   '--runtime-version=16.14.2',
npm ERR!   '--arch=arm64',
npm ERR!   '--runtime=node'
npm ERR! ]
npm ERR! prebuild-install WARN install No prebuilt binaries found (target=16.14.2 runtime=node arch=arm64 libc= platform=darwin)
npm ERR! npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm ERR! npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm ERR! npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm ERR! npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm ERR! npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm ERR! prebuild info begin Prebuild version 11.0.4
npm ERR! prebuild info build Preparing to prebuild node-datachannel@0.3.4 for node 16.14.2 on darwin-arm64 using cmake-js
npm ERR! info TOOL Using Unix Makefiles generator.
npm ERR! ERR! OMG CMake executable is not found. Please use your system's package manager to install it, or you can get installers from there: http://cmake.org.
npm ERR! prebuild ERR! build Error: Failed to build cmake with exit code 1
npm ERR! prebuild ERR! build     at ChildProcess.<anonymous> (/Users/zouzhe/.nvm/versions/node/v16.14.2/lib/node_modules/ironfish/node_modules/node-datachannel/node_modules/prebuild/cmakebuild.js:32:19)
npm ERR! prebuild ERR! build     at ChildProcess.emit (node:events:526:28)
npm ERR! prebuild ERR! build     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zouzhe/.npm/_logs/2022-10-20T06_46_29_692Z-debug-0.log

**Comment by ygao76** [comment]
Do you install cmake with version 3.15 or higher? More details see here https://github.com/iron-fish/ironfish#developer-install

**Comment by qq234876317** [comment]
That well, thanks! my network is error in china!
