### ISSUE TITLE
[issue name] Decreasing Balance without any action

### ISSUE THREAD

**Issue by artespraticas** [iron-fish/ironfish#2384]
### What happened?

A bug happened!  I've been trying to get my node going since August, and if after one week say I had 1 IRON, after all this time I continue to have the same and a few decimals (made 5 transactions-of 0,1 so far). With much of my surprise, tried again to make a deposit and realized I continue to have the same IRON after 2 months... So I've monitored for 2 days and what is incredible is that the amount gets smaller even if I didn't make any deposit! How bizarre is this? Does this mean that someone has access to my account?? Thanks for any help and excuse my ignorance but I'm really sad that all my efforts and time mean almost nothing... 😦  I also have tried to run the Ironfish deposit and nothing happens now... I'll restart my node later... Thx! Tried to close the node and said I've needed to stop it first... but it's running!

[Your balance is $IRON 1,00608653 ($ORE 100 608 653)  (18/10/22-12H)

Your balance is $IRON 1,04677119 ($ORE 104 677 119)  (18/10/22-16H)

Your balance is $IRON 1,01827289 ($ORE 101 827 289)  (20/10/22-13H)]

### Version

0.1.49

### Debug output

```shell
reismesquita@iMac-de-Reis ~ % ironfish debug
Iron Fish version                  0.1.49 @ ec57ed3
Iron Fish library                  0.0.26 @ ec57ed3
Operating system                   Darwin x64
CPU model(s)                       Intel(R) Core(TM) i5-5675R CPU @ 3.10GHz
CPU threads                        4
RAM total                          8.00 GiB
Heap total                         2.00 GiB
Node version                       v16.16.0
ironfish in PATH                   true
Garbage Collector Exposed          false
Telemetry enabled                  true
Node name                          artespraticas
Block graffiti                     artespraticas
Account cbb068 uuid                cbb068d3-98ed-42df-99cb-cac93b3ef187
Account cbb068 name                default
Account cbb068 head hash           000000000000561a29bc0a71113dedd52f8da5f4873c6cd34b1336e62f884bc7
Account cbb068 head in chain       true
Account cbb068 sequence            235132
```

### Graffiti

artespraticas

**Comment by hughy** [comment]
After discussion on Discord I believe this issue was resolved in v0.1.52 and/or the subsequent release of the `accounts:repair` command.

Please reopen this issue or open a new issue if you run into this problem again!
