### ISSUE TITLE
NPM Installed Failed Ubuntu 22

### ISSUE THREAD

**Issue by trgm7** [iron-fish/ironfish#2403]
### What happened?

I'm trying to install ironfish node but I'm constantly met with errors. Below is the error. Could anyone please assist?

ironfish@ironfish-node:~$ npm install -g ironfish --force
npm WARN using --force Recommended protections disabled.
npm WARN deprecated @types/minipass@3.3.5: This is a stub types definition. minipass provides its own type definitions, so you do not need this installed.
npm ERR! code 1
npm ERR! path /home/ironfish/.nvm/versions/node/v16.17.1/lib/node_modules/ironfish/node_modules/segfault-handler
npm ERR! command failed
npm ERR! command sh /tmp/install-f58907d4.sh
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@16.17.1 | linux | x64
npm ERR! gyp info find Python using Python version 3.10.6 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/ironfish/.nvm/versions/node/v16.17.1/lib/node_modules/ironfish/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/ironfish/.nvm/versions/node/v16.17.1/lib/node_modules/ironfish/node_modules/segfault-handler/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/ironfish/.nvm/versions/node/v16.17.1/lib/node_modules/ironfish/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/ironfish/.cache/node-gyp/16.17.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/ironfish/.cache/node-gyp/16.17.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/ironfish/.nvm/versions/node/v16.17.1/lib/node_modules/ironfish/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/ironfish/.cache/node-gyp/16.17.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/ironfish/.nvm/versions/node/v16.17.1/lib/node_modules/ironfish/node_modules/segfault-handler',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: not found: make
npm ERR! gyp ERR! stack     at getNotFoundError (/home/ironfish/.nvm/versions/node/v16.17.1/lib/node_modules/ironfish/node_modules/node-gyp/node_modules/which/which.js:10:17)
npm ERR! gyp ERR! stack     at /home/ironfish/.nvm/versions/node/v16.17.1/lib/node_modules/ironfish/node_modules/node-gyp/node_modules/which/which.js:57:18
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at step (/home/ironfish/.nvm/versions/node/v16.17.1/lib/node_modules/ironfish/node_modules/node-gyp/node_modules/which/which.js:54:21)
npm ERR! gyp ERR! stack     at /home/ironfish/.nvm/versions/node/v16.17.1/lib/node_modules/ironfish/node_modules/node-gyp/node_modules/which/which.js:71:22
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at subStep (/home/ironfish/.nvm/versions/node/v16.17.1/lib/node_modules/ironfish/node_modules/node-gyp/node_modules/which/which.js:69:33)
npm ERR! gyp ERR! stack     at /home/ironfish/.nvm/versions/node/v16.17.1/lib/node_modules/ironfish/node_modules/node-gyp/node_modules/which/which.js:80:22
npm ERR! gyp ERR! stack     at /home/ironfish/.nvm/versions/node/v16.17.1/lib/node_modules/ironfish/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /home/ironfish/.nvm/versions/node/v16.17.1/lib/node_modules/ironfish/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! System Linux 5.15.0-52-generic
npm ERR! gyp ERR! command "/home/ironfish/.nvm/versions/node/v16.17.1/bin/node" "/home/ironfish/.nvm/versions/node/v16.17.1/lib/node_modules/ironfish/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /home/ironfish/.nvm/versions/node/v16.17.1/lib/node_modules/ironfish/node_modules/segfault-handler
npm ERR! gyp ERR! node -v v16.17.1
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ironfish/.npm/_logs/2022-10-24T07_07_09_155Z-debug-0.log

**Comment by ygao76** [comment]
Hi @trgm7, I recently installed Iron Fish on a AWS ubuntu machine. 
There are some pre-requisite you need to install first before install Iron Fish. 
Can you run following commands on your Ubuntu machine?
node version
``` 
node -v
```
yarn version 
```
yarn --version
```
npm version
```
npm --version
```
cmake version
```
cmake --version
```

**Comment by trgm7** [comment]
> 

Thanks for the response @ygao76.  I tried to install ironfish via their guide on the official website.

Here is the output of which you requested.


ironfish@ironfish-node:~$ node -v
v16.0.0
ironfish@ironfish-node:~$ yarn --version
0.32+git
ironfish@ironfish-node:~$ npm --version
7.10.0
ironfish@ironfish-node:~$ cmake --version
cmake version 3.22.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
ironfish@ironfish-node:~$ rustup --version
rustup 1.24.3 (ce5817a94 2021-05-31)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
ironfish@ironfish-node:~$

**Comment by ygao76** [comment]
Hi @trgm7 thanks for the infos. You need to install build-essential
You run ```apt install build-essential```
