### ISSUE TITLE
Feature: Disable coinbase reward

### ISSUE THREAD

**Issue by hairtail** [iron-fish/ironfish#2421]
### Description

1. Hard fork to disable coinbase reward and get ready for the end of Phase 2. There are 1440 blocks, 28800 tokens everyday, which takes about 28800 transactions, nearly 1000 blocks to be converted to points even if `maxDepositValue = 1 IRON`. The blockspace is limited, so it's better to get some blockspace ready for tokens minted before.
2. There are some issues which may cause incorrect balance, so rescan needed. It's better to work on parallel-rescan so everyone here has chance to finish at least one time rescan to get correct notes and balance. Then deposit their tokens for testnet points.

**Comment by hairtail** [comment]
Mis-calculation in 1st reason, the number of blocks needed to mine tokens new minted everyday is about 100 with `maxDepositValue = 1 IRON`.

**Comment by hairtail** [comment]
Maybe it's better to disable coinbase reward when Phase 2 ends (15th Nov), and leave the deposit points system running for users that still have token to deposit because slow rescan and incorrect balance.

**Comment by hughy** [comment]
Implemented in #2620 , thanks for the suggestion!
