### ISSUE TITLE
hard to enter when logging in[issue name]

### ISSUE THREAD

**Issue by hallosayael** [iron-fish/ironfish#2433]
### What happened?

When logging in to: https://testnet.ironfish.network/login and when we click the confirmation email, our account dashboard display just keeps loading. Doesn't show anything

![image](https://user-images.githubusercontent.com/110147776/198533968-fc306629-b4c1-4c6f-8562-9d8060c90554.png)

### Graffiti

hallosayael

**Comment by hughy** [comment]
@hallosayael we've made some changes in the last few days that should have improved performance on the testnet website. Are you still having issues logging in?

**Comment by hallosayael** [comment]
yes, this morning I tried it and it successfully logged into my dashboard.. great job, thanks
