### ISSUE TITLE
Response of getTransaction misses notes

### ISSUE THREAD

**Issue by hairtail** [iron-fish/ironfish#2435]
### What happened?

Codebase: staging https://github.com/iron-fish/ironfish/commit/51125b62ea9f7b0631e580f42299a8ce304bdff7
```
Transaction: 61833f03e7ff7187ee0558be27e96907b55213ce4ac60681ccd3997914aa69d8
Account: test
Status: pending
Miner Fee: x
Fee: $IRON 0.00010000
Spends Count: 1
Notes Count: 2
```

### Version

staging

### Graffiti

miningKing

**Comment by hairtail** [comment]
When transaction is expired, notes should be remove but it appears... 
```
Transaction: 61833f03e7ff7187ee0558be27e96907b55213ce4ac60681ccd3997914aa69d8
Account: test
Status: expired
Miner Fee: x
Fee: $IRON 0.00010000
Spends Count: 1
Notes Count: 2
---Notes---

 Amount ($IRON) Spent Memo
 ────────────── ───── ─────────
 1.00000000     x     hellotest
```

**Comment by hairtail** [comment]
Account `test` is receiver of this transaction. So what happens above makes balance of `test` confusion.

**Comment by NullSoldier** [comment]
Yes we recently discovered this bug and the fix is going out in the next release. https://github.com/iron-fish/ironfish/pull/2399

**Comment by hairtail** [comment]
> Yes we recently discovered this bug and the fix is going out in the next release. #2399

Do we need a migration for this release? Actually, what I mentioned above happens on `staging` branch. I have tagged the commit status I'm working on above.

**Comment by hairtail** [comment]
Maybe I get the idea, the reason why this happens is rebroadcasting of expired transaction from other peers. Thanks. I will close this issue as completed.
