### ISSUE TITLE
[issue docker]The docker image is broken

### ISSUE THREAD

**Issue by Lzggno1** [iron-fish/ironfish#2472]
### What happened?

Since I couldn't run the node using npm, I chose docker. But do'ce'k'r images often break on their own after running for more than a dozen hours. docker ps does not have this image anymore

### Graffiti

lzgg

**Comment by NullSoldier** [comment]
Can you provide more information? You haven't provided any information. How does it break after running for dozens of hours?

**Comment by dguenther** [comment]
You can use `docker run --restart=always` to make sure your Docker container automatically restarts if it crashes. See the documentation here: https://docs.docker.com/engine/reference/run/#restart-policies---restart

We'd recommend you use npm to run the node though, and if you can't, post an issue so we can help solve the problem.
