### ISSUE TITLE
v1.50 won't install correctly on Windows 10.  

### ISSUE THREAD

**Issue by crProductGuy** [iron-fish/ironfish#2473]
### What happened?

2 attempts at `npm install -g ironfish` as usual failed, upgrading from 0.1.49 to 1.50 via npm in powershell 7

Same error messages both times, shown here below.

1.49 and prior versions were successfully installed with npm as above (no change in installation method)

checking version after shows 0.1.49 still:

 ironfish --version
name       ironfish
version    0.1.49
git        ec57ed3
runtime    node/16.16.0
PS C:\Users\markt>

Luckily 0.1.49 still works after the failed upgrade attempts

----

Installation Logs in powershell 7:

 npm install -g ironfish
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm WARN deprecated @types/minipass@3.3.5: This is a stub types definition. minipass provides its own type definitions, so you do not need this installed.
npm ERR! code 2
npm ERR! path C:\Users\markt\AppData\Roaming\npm\node_modules\ironfish\node_modules\node-datachannel
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c prebuild-install || (npm install --ignore-scripts && npm run _prebuild)
npm ERR! added 610 packages, removed 13 packages, changed 45 packages, and audited 658 packages in 29s
npm ERR!
npm ERR! 64 packages are looking for funding
npm ERR!   run `npm fund` for details
npm ERR!
npm ERR! 4 high severity vulnerabilities
npm ERR!
npm ERR! To address all issues (including breaking changes), run:
npm ERR!   npm audit fix --force
npm ERR!
npm ERR! Run `npm audit` for details.
npm ERR!
npm ERR! > node-datachannel@0.3.6 _prebuild
npm ERR! > prebuild --backend cmake-js
npm ERR!
npm ERR! [
npm ERR!   'C:\\Program Files\\nodejs\\node.exe',
npm ERR!   'C:\\Users\\markt\\AppData\\Roaming\\npm\\node_modules\\ironfish\\node_modules\\node-datachannel\\node_modules\\cmake-js\\bin\\cmake-js',
npm ERR!   'rebuild',
npm ERR!   '--runtime-version=16.16.0',
npm ERR!   '--arch=x64',
npm ERR!   '--runtime=node'
npm ERR! ]
npm ERR! prebuild-install WARN install The specified module could not be found.
npm ERR! prebuild-install WARN install \\?\C:\Users\markt\AppData\Roaming\npm\node_modules\ironfish\node_modules\node-datachannel\build\Release\node_datachannel.node
npm ERR! npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm ERR! npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm ERR! npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm ERR! npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm ERR! npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm ERR! npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! prebuild info begin Prebuild version 11.0.4
npm ERR! prebuild info build Preparing to prebuild node-datachannel@0.3.6 for node 16.16.0 on win32-x64 using cmake-js
npm ERR! ERR! OMG CMake is not installed. Install CMake.
npm ERR! ERR! OMG CMake is not installed. Install CMake.
npm ERR! prebuild ERR! build Error: Failed to build cmake with exit code 1
npm ERR! prebuild ERR! build     at ChildProcess.<anonymous> (C:\Users\markt\AppData\Roaming\npm\node_modules\ironfish\node_modules\node-datachannel\node_modules\prebuild\cmakebuild.js:32:19)
npm ERR! prebuild ERR! build     at ChildProcess.emit (node:events:527:28)
npm ERR! prebuild ERR! build     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\markt\AppData\Local\npm-cache\_logs\2022-11-01T06_47_04_646Z-debug-0.log

### Version

v0.1.49

### Debug output

```shell
ironfish debug
Iron Fish version                  0.1.49 @ ec57ed3
Iron Fish library                  0.0.26 @ ec57ed3
Operating system                   Windows_NT x64
CPU model(s)                       AMD Athlon Silver 3050U with Radeon Graphics
CPU threads                        2
RAM total                          5.88 GiB
Heap total                         2.01 GiB
Node version                       v16.16.0
ironfish in PATH                   true
Garbage Collector Exposed          false
Telemetry enabled                  true
Node name                          ProductGuy
Block graffiti                     ProductGuy
Account 340cde uuid                340cde12-8aaf-43be-8572-9bdc209f06c4
Account 340cde name                default
Account 340cde head hash           0000000000004e704cb26b66ade3f902be66a42bfe03e330494e22dc523ce3cf
Account 340cde head in chain       true
Account 340cde sequence            252926
```

### Relevant log output

```shell
see above
```

### Graffiti

ProductGuy

**Comment by dguenther** [comment]
Looking into this -- I'll send you a message on Discord if I need any help debugging!

**Comment by airj1012** [comment]
How do you downgrade? Will you lose any important data for your node?

**Comment by dguenther** [comment]
You can install the previous version by running `npm install -g ironfish@0.1.49`.

**Comment by AmberKiso** [comment]
The upgrade was successful for me, but then I get a run time error:

> Version       0.1.50 @ 02939ae
Node Name     Here fishie fishie fishie!!!
Graffiti      Here fishie fishie fishie!!!
Peer Identity ...
Peer Agent    ironfish/0.1.50/02939ae
Peer Port     9033
Bootstrap     test.bn1.ironfish.network

WebSocket server started at :::9033
Error: listen EACCES: permission denied C:\Users\mjolnir\.ironfish\ironfish.ipc
    at Server.setupListenHandle [as _listen2] (node:net:1317:21)
    at listenInCluster (node:net:1382:12)
    at Server.listen (node:net:1480:5)
    at C:\Users\mjolnir\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\rpc\adapters\socketAdapter\socketAdapter.js:75:20
    at new Promise (<anonymous>)
    at RpcIpcAdapter.start (C:\Users\mjolnir\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\rpc\adapters\socketAdapter\socketAdapter.js:62:16)
    at async Promise.all (index 0)
    at async RpcServer.start (C:\Users\mjolnir\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\rpc\server.js:34:9)
    at async IronfishNode.start (C:\Users\mjolnir\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\node.js:226:13)
    at async Start.start (C:\Users\mjolnir\AppData\Roaming\npm\node_modules\ironfish\build\src\commands\start.js:118:9)

I'll assume it's related to the node_module version and wait for the next IF release.
