### ISSUE TITLE
Error submitting telemetry to API

### ISSUE THREAD

**Issue by RT41yo** [iron-fish/ironfish#2476]
### What happened?

A bug happened!
Error submitting telemetry to API. No one point since 23.10. Besides, I guess, there is no possibilities to update on 0.1.50.
<img width="946" alt="119" src="https://user-images.githubusercontent.com/117180622/199245088-cdc5d59b-537f-4978-a1a4-fb7fa496fa7f.png">

### Version

0.1.49

### Graffiti

IronFish_RT41yo

**Comment by NullSoldier** [comment]
It means the DNS server replied that it cannot currently fulfill the request. You are probably getting rate limited by cloudflare.  If you let it run when the API load is lower you'll get through. We'll look at potentially relaxing our rate limiting restrictions.
