### ISSUE TITLE
RangeError: Invalid WebSocket frame: RSV2 and RSV3 must be clear

### ISSUE THREAD

**Issue by guilhermeysm** [iron-fish/ironfish#2481]
### What happened?

error while syncing.

Starting sync from ypL4Ydm. work: +58567163119804205522, ours: 93116, theirs: 251296
Finding ancestor using linear search on last 3 blocks starting at 00000...125b4 (93116) from peer ypL4Ydm at 251296
node:events:491
      throw er; // Unhandled 'error' event
      ^

RangeError: Invalid WebSocket frame: RSV2 and RSV3 must be clear
    at Receiver.getInfo (C:\Users\guilh\AppData\Roaming\npm\node_modules\ironfish\node_modules\ws\lib\receiver.js:171:14)
    at Receiver.startLoop (C:\Users\guilh\AppData\Roaming\npm\node_modules\ironfish\node_modules\ws\lib\receiver.js:131:22)
    at Receiver._write (C:\Users\guilh\AppData\Roaming\npm\node_modules\ironfish\node_modules\ws\lib\receiver.js:78:10)
    at writeOrBuffer (node:internal/streams/writable:391:12)
    at _write (node:internal/streams/writable:332:10)
    at Receiver.Writable.write (node:internal/streams/writable:336:10)
    at Socket.socketOnData (C:\Users\guilh\AppData\Roaming\npm\node_modules\ironfish\node_modules\ws\lib\websocket.js:920:35)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
Emitted 'error' event on WebSocket instance at:
    at Receiver.receiverOnError (C:\Users\guilh\AppData\Roaming\npm\node_modules\ironfish\node_modules\ws\lib\websocket.js:826:13)
    at Receiver.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'WS_ERR_UNEXPECTED_RSV_2_3',
  [Symbol(status-code)]: 1002
}

### Version

v0.1.49

### Debug output

```shell
Iron Fish version                  0.1.49 @ ec57ed3
Iron Fish library                  0.0.26 @ ec57ed3
Operating system                   Windows_NT x64
CPU model(s)                       Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
CPU threads                        8
RAM total                          7.87 GiB
Heap total                         2.01 GiB
Node version                       v16.18.0
ironfish in PATH                   true
Garbage Collector Exposed          false
Telemetry enabled                  false
Node name
Block graffiti                     guilhermeysm
Account a46ce6 uuid                a46ce653-f929-4e1b-890d-f4807f56ca47
Account a46ce6 name                guilhermeysm
Account a46ce6 head hash           00000000000081260db5f1e9c534a200234bab06e2f1d886857c7301cff24a1d
Account a46ce6 head in chain       true
Account a46ce6 sequence            93090
```

### Relevant log output

```shell
2022/10/31-06:55:50.289 44d0 Recovering log #630713
2022/10/31-06:55:50.394 44d0 Delete type=0 #630713
2022/10/31-06:55:50.394 44d0 Delete type=2 #630714
2022/10/31-06:55:50.401 44d0 Delete type=2 #630715
2022/10/31-06:55:50.401 44d0 Delete type=3 #630711
2022/10/31-06:55:50.403 4c70 Compacting 1@3 + 10@4 files
2022/10/31-06:55:50.488 4c70 Generated table #630716@3: 6435 keys, 2123487 bytes
2022/10/31-06:55:50.645 4c70 Generated table #630717@3: 6435 keys, 2123483 bytes
2022/10/31-06:55:50.934 4c70 Generated table #630718@3: 6435 keys, 2123481 bytes
2022/10/31-06:55:51.149 4c70 Generated table #630719@3: 6435 keys, 2123479 bytes
2022/10/31-06:55:51.434 4c70 Generated table #630720@3: 6435 keys, 2123484 bytes
2022/10/31-06:55:51.956 4c70 Generated table #630721@3: 6435 keys, 2123478 bytes
2022/10/31-06:55:52.123 4c70 Generated table #630722@3: 6435 keys, 2123482 bytes
2022/10/31-06:55:52.276 4c70 Generated table #630723@3: 6435 keys, 2123485 bytes
2022/10/31-06:55:52.434 4c70 Generated table #630724@3: 6435 keys, 2123493 bytes
2022/10/31-06:55:52.589 4c70 Generated table #630725@3: 6435 keys, 2123487 bytes
2022/10/31-06:55:52.656 4c70 Generated table #630726@3: 1178 keys, 388881 bytes
2022/10/31-06:55:52.656 4c70 Compacted 1@3 + 10@4 files => 21623720 bytes
2022/10/31-06:55:52.688 4c70 compacted to: files[ 4 7 83 871 5386 9110 0 ]
2022/10/31-06:55:52.701 4c70 Delete type=2 #619407
2022/10/31-06:55:52.702 4c70 Delete type=2 #619410
2022/10/31-06:55:52.702 4c70 Delete type=2 #619411
2022/10/31-06:55:52.703 4c70 Delete type=2 #619412
2022/10/31-06:55:52.703 4c70 Delete type=2 #619413
2022/10/31-06:55:52.703 4c70 Delete type=2 #619501
2022/10/31-06:55:52.727 4c70 Delete type=2 #619502
2022/10/31-06:55:52.727 4c70 Delete type=2 #619505
2022/10/31-06:55:52.730 4c70 Delete type=2 #619506
2022/10/31-06:55:52.730 4c70 Delete type=2 #619507
2022/10/31-06:55:52.731 4c70 Delete type=2 #628167
2022/10/31-06:55:52.733 4c70 Compacting 1@3 + 11@4 files
2022/10/31-06:55:52.979 4c70 Generated table #630727@3: 6435 keys, 2123478 bytes
2022/10/31-06:55:53.167 4c70 Generated table #630728@3: 6435 keys, 2123489 bytes
2022/10/31-06:55:53.312 4c70 Generated table #630729@3: 6435 keys, 2123475 bytes
```

### Graffiti

guilhermeysm

**Comment by danield9tqh** [comment]
I am going to close this as a duplicate since it seems to be the same issue you previously reported here https://github.com/iron-fish/ironfish/issues/2447
