### ISSUE TITLE
Max Deposit 

### ISSUE THREAD

**Issue by muhmad-f-k** [iron-fish/ironfish#2490]
### What happened?

Hi. I deposit 0.6 Coins and website shows only 5 point! It should be 6 point.

Using node 1.49

![point](https://user-images.githubusercontent.com/22121200/199350359-520ad611-73d1-4a68-93ca-6dcdf530b01a.PNG)

**Comment by danield9tqh** [comment]
Hey @muhmad-f-k can you add the transaction id and your graffiti here as well?

**Comment by muhmad-f-k** [comment]
Well the issue is the api.  take a look here  https://api.ironfish.network/deposits/min_and_max_deposit_size
it say 0.5 not 0.6.

**Comment by danield9tqh** [comment]
We've just added a fix (https://github.com/iron-fish/ironfish-api/pull/1075/files) for this in the API and retroactively changed points to be correct so I am going to close this. Wait a little while for points to update. If it is still not correct in the next day or so please let us know.
