### ISSUE TITLE
The point after deposit ironfish is not displayed

### ISSUE THREAD

**Issue by luoam** [iron-fish/ironfish#2515]
### What happened?

My account has completed two different dispositions on the local ironfish node，But it is not displayed in the point record of the testnet phase2 webpage
![Screenshot from 2022-11-05 18-03-04](https://user-images.githubusercontent.com/22240627/200114459-183f13d5-48bb-47cc-8bad-cb161ebdefed.png)
txn info：https://explorer.ironfish.network/transaction/b2f2b0d9d8f7be71f6b02c7f0ab428c023239722b9ae5a2cf31346e8ff32503f

no point increase yet：
![Screenshot from 2022-11-05 18-10-22](https://user-images.githubusercontent.com/22240627/200114688-c6eb6e35-13b9-4e15-b165-38dc66d6d582.png)

### Version

ironfish/0.1.49 win32-x64 node-v16.14.2

### Graffiti

maoul

**Comment by hughy** [comment]
The process that we use to track points was backed up due to high transaction volume. Do you see points for your transactions now? Please also note that only confirmed transactions receive points, so if your transaction does not appear on the block explorer it was likely not confirmed
