### ISSUE TITLE
Syncing problem at 77.06%, progress went backwards

### ISSUE THREAD

**Issue by guilhermeysm** [iron-fish/ironfish#2524]
### What happened?

While syncing my node, after reaching 70.05% progress went backwards to 69.98%.

Increments are tooking too long. 
_Requesting 20 blocks starting at 00000...bc3c6 (201863) from GSlWe2j (enlangaaronlonnelly)
Added block seq: 201880, hash: 00000...9ec52, txs: 301, progress: 76.97%, time: 47204.7ms
Requesting 20 blocks starting at 00000...40e4f (201883) from 5/lWICV (ZK.Work)
Added block seq: 201900, hash: 00000...b7d46, txs: 301, progress: 76.97%, time: 14511.3ms
Requesting 20 blocks starting at 00000...78b8b (201903) from 5/lWICV (ZK.Work)
Added block seq: 201920, hash: 00000...8429d, txs: 145, progress: 76.98%, time: 6618.2ms
Requesting 20 blocks starting at 00000...d4c33 (201923) from 5/lWICV (ZK.Work)
Added block seq: 201940, hash: 00000...19ab1, txs: 134, progress: 76.99%, time: 8116.2ms
Requesting 20 blocks starting at 00000...6046e (201943) from 5/lWICV (ZK.Work)
Added block seq: 201960, hash: 00000...5651e, txs: 301, progress: 76.99%, time: 43481.9ms
Requesting 20 blocks starting at 00000...886bb (201963) from 5/lWICV (ZK.Work)
Added block seq: 201980, hash: 00000...4da00, txs: 301, progress: 77.00%, time: 16773.8ms
Requesting 20 blocks starting at 00000...09960 (201983) from 5/lWICV (ZK.Work)
Added block seq: 202000, hash: 00000...37420, txs: 301, progress: 77.00%, time: 24733.0ms_

Disconnections happens a lot.
_Starting sync from yaox3el (luzzord). work: +51854694276478583441, ours: 201883, theirs: 262049
Finding ancestor using linear search on last 3 blocks starting at 00000...40e4f (201883) from peer yaox3el (luzzord) at 262049
Found peer yaox3el (luzzord) ancestor 00000...40e4f, syncing from 201883 -> 262049 (60166) after 1 requests
Requesting 20 blocks starting at 00000...40e4f (201883) from yaox3el (luzzord)
Peer yaox3el (luzzord) disconnected (DISCONNECTED) while syncing.
Starting sync from fiil97D (allotv89). work: +37933399838018021722, ours: 201883, theirs: 246728
Finding ancestor using linear search on last 3 blocks starting at 00000...40e4f (201883) from peer fiil97D (allotv89) at 246728
Found peer fiil97D (allotv89) ancestor 00000...40e4f, syncing from 201883 -> 246728 (44845) after 1 requests
Requesting 20 blocks starting at 00000...40e4f (201883) from fiil97D (allotv89)
Peer fiil97D (allotv89) disconnected (DISCONNECTED) while syncing._

Error RequestTimeoutError happening sometimes.
_Stopping sync from POBSPH1 (robochan) due to RequestTimeoutError: Closing connections to POBSPH1 (robochan) because RPC message of type GetBlockHashesRequest (2) timed out after 30000 ms in request: 33.
    at Timeout.<anonymous> (C:\Users\guilh\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\network\peerNetwork.js:358:31)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)_

Attached full log with all evidences.

[e9.txt](https://github.com/iron-fish/ironfish/files/9957044/e9.txt)

### Version

v0.1.49

### Debug output

```shell
Iron Fish version                  0.1.49 @ ec57ed3
Iron Fish library                  0.0.26 @ ec57ed3
Operating system                   Windows_NT x64
CPU model(s)                       Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
CPU threads                        8
RAM total                          7.87 GiB
Heap total                         2.01 GiB
Node version                       v16.18.0
ironfish in PATH                   true
Garbage Collector Exposed          false
Telemetry enabled                  false
Node name
Block graffiti                     guilhermeysm
Account a46ce6 uuid                a46ce653-f929-4e1b-890d-f4807f56ca47
Account a46ce6 name                guilhermeysm
Account a46ce6 head hash           0000000000003dbf426d6ef7ced56f6393aa18ea9928280c1690f9515c3f8797
Account a46ce6 head in chain       true
Account a46ce6 sequence            202342
```

### Graffiti

guilhermeysm

**Comment by guilhermeysm** [comment]
Problem continues, maximum percentage is 77.06 and sudenly goes backwards and advances until 77.06 again and the cycle repeats.

**Comment by hughy** [comment]
`chain:download` will automatically extract and move files to the right folder. Does `ironfish status` still show that your node is behind?

**Comment by guilhermeysm** [comment]
> `chain:download` will automatically extract and move files to the right folder. Does `ironfish status` still show that your node is behind?

Where can I see that? After updating, syncing is advancing again.

Is still worth a chain download?

Status:
_Version              0.1.51 @ 67da183
Node                 STOPPED
Node Name
Block Graffiti       guilhermeysm
Memory               Heap: 0 B -> 0 B / 2.00 GiB (0.0%), RSS: 0 B (0.0%), Free: 0 B (100.0%)
CPU                  Cores: 8, Current: 0.0%
P2P Network          WAITING - In: 0 B/s, Out: 0 B/s, peers 0
Mining               STARTED - 0 miners, 0 mined
Mem Pool             Count: 0 tx, Bytes: 0 B
Syncer               STOPPED - progress: 78.63%
Blockchain           0000000000001834db382d0b1ca7082de967a96fa05781df04df2135937acfa8 (208662), Since HEAD: 938h 53m (NOT SYNCED)
Accounts             0000000000001834db382d0b1ca7082de967a96fa05781df04df2135937acfa8 (-1)
Telemetry            STOPPED
Workers              STOPPED_

**Comment by hughy** [comment]
These lines show that your node is still pretty far behind, but catching up:
```
Syncer STOPPED - progress: 78.63%
Blockchain 0000000000001834db382d0b1ca7082de967a96fa05781df04df2135937acfa8 (208662), Since HEAD: 938h 53m (NOT SYNCED)
```

Your node is currently at block sequence 208662. `chain:download` will get you to 264120, but it will take several hours to complete and needs ~180GB of hard drive space to run.

**Comment by guilhermeysm** [comment]
@hughy ok, thanks for your feedback, I will keep syncing and see what happens.

**Comment by hughy** [comment]
@guilhermeysm were you able to sync?

**Comment by guilhermeysm** [comment]
Yes I do!

Em qui., 8 de dez. de 2022 20:12, Hugh Cunningham ***@***.***>
escreveu:
