### ISSUE TITLE
Accounts are unable to Spend Due to mismatch in noted DB

### ISSUE THREAD

**Issue by ADADarkpool** [iron-fish/ironfish#2545]
### What happened?

Two accounts have issues with their noted DB.  Was troubleshooting with @hughy earlier today.

![image](https://user-images.githubusercontent.com/86623622/201216039-c86067e7-676c-4920-b771-509581d764a8.png)

One account is much older (the default account actually)

The other accounts is newer one.  Can't say if it was pre or post 1.50.

### Version

v0.1.51

### Graffiti

DarkPool

**Comment by hughy** [comment]
Have you run into the original issue (insufficient balance error, but balance not changing) again since rescanning?
