### ISSUE TITLE
Database cannot be opened, skipping output that requires database.

### ISSUE THREAD

**Issue by luoam** [iron-fish/ironfish#2552]
### What happened?

i run commond : ironfish debug --datadir=E:\ironfish-testnet
it  display some errors :+1: 
Database cannot be opened, skipping output that requires database.

OpenError: IO error: LockFile E:\ironfish-testnet\databases\default/LOCK: ��һ����������ʹ�ô��ļ��������޷����ʡ�

    at C:\Users\admin\AppData\Roaming\npm\node_modules\ironfish\node_modules\levelup\lib\levelup.js:119:23
    at C:\Users\admin\AppData\Roaming\npm\node_modules\ironfish\node_modules\abstract-leveldown\abstract-leveldown.js:38:14
    at C:\Users\admin\AppData\Roaming\npm\node_modules\ironfish\node_modules\deferred-leveldown\deferred-leveldown.js:31:21
    at C:\Users\admin\AppData\Roaming\npm\node_modules\ironfish\node_modules\abstract-leveldown\abstract-leveldown.js:38:14

Iron Fish version               0.1.49 @ ec57ed3
Iron Fish library               0.0.26 @ ec57ed3
Operating system                Windows_NT x64
CPU model(s)                    AMD Ryzen 5 3500X 6-Core Processor
CPU threads                     6
RAM total                       15.93 GiB
Heap total                      4.01 GiB
Node version                    v16.14.2
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       maoul
Block graffiti                  maoul

### Version

 0.1.49 @ ec57ed3

### Debug output

```shell
Database cannot be opened, skipping output that requires database.

OpenError: IO error: LockFile E:\ironfish-testnet\databases\default/LOCK: ��һ����������ʹ�ô��ļ��������޷����ʡ�

    at C:\Users\admin\AppData\Roaming\npm\node_modules\ironfish\node_modules\levelup\lib\levelup.js:119:23
    at C:\Users\admin\AppData\Roaming\npm\node_modules\ironfish\node_modules\abstract-leveldown\abstract-leveldown.js:38:14
    at C:\Users\admin\AppData\Roaming\npm\node_modules\ironfish\node_modules\deferred-leveldown\deferred-leveldown.js:31:21
    at C:\Users\admin\AppData\Roaming\npm\node_modules\ironfish\node_modules\abstract-leveldown\abstract-leveldown.js:38:14

Iron Fish version               0.1.49 @ ec57ed3
Iron Fish library               0.0.26 @ ec57ed3
Operating system                Windows_NT x64
CPU model(s)                    AMD Ryzen 5 3500X 6-Core Processor
CPU threads                     6
RAM total                       15.93 GiB
Heap total                      4.01 GiB
Node version                    v16.14.2
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       maoul
Block graffiti                  maoul
```

### Graffiti

maoul

**Comment by NullSoldier** [comment]
Yep, this is no error. The reason you are seeing this is because the database cannot be opened, and it's skipping output that requires database. the database is being used by your node.
