### ISSUE TITLE
ironfish accounts:balance seems mistake

### ISSUE THREAD

**Issue by luoam** [iron-fish/ironfish#2556]
### What happened?

A bug happened!
![Screenshot from 2022-11-12 09-26-37](https://user-images.githubusercontent.com/22240627/201450219-288452a4-4aa4-4da9-9209-2e212922721c.png)

i run "ironfish accounts:balance" twice, but the result is  diffirent. look the picture please

### Version

0.1.49 @ ec57ed3

### Graffiti

maoul

**Comment by hughy** [comment]
This is likely caused by a bug that was resolved in v0.1.50: https://github.com/iron-fish/ironfish/pull/2399

We're continuing to work on additional issues related to wallet balances!

**Comment by hughy** [comment]
v0.1.54 added a command, `ironfish accounts:repair`, that is intended to resolve balance issues like the one you reported here.

**Comment by holahula** [comment]
Closing - addressed
