### ISSUE TITLE
Deposit error if balance is less than 2.5 $IRON

### ISSUE THREAD

**Issue by justmml** [iron-fish/ironfish#2582]
### What happened?

Hardware:
CPU: 4 core AMD EPYC 7282
RAM: 8 Gb
OS: Ubuntu 20.04

Steps to reproduce:
1. Balance is needed to be less than 2.5 $IRON (e.g. 2.2 $IRON)
2. Use command `ironfish deposit`

**Result:** 
An error occurred while sending the transaction.
 ›   Error: Request failed (400) insufficient-balance: Your balance is too low. Add funds to your account first

**Expected result:** Successful transaction, balance decreased by 0.5 $IRON + fee ($IRON 0.00000008)

### Version

0.1.51 @ 67da183

### Debug output

```shell
Iron Fish version               0.1.51 @ 67da183
Iron Fish library               0.0.28 @ 67da183
Operating system                Linux x64
CPU model(s)                    AMD EPYC 7282 16-Core Processor
CPU threads                     4
RAM total                       7.77 GiB
Heap total                      2.01 GiB
Node version                    v16.17.0
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       mml_node
Block graffiti                  mml_node
```

### Relevant log output

```shell
root@vmi881185:~# ironfish deposit

Your balance is $IRON 2.20925487.

You are about to send $IRON 0.50000000 plus a transaction fee of $IRON 0.00000008 to the Iron Fish deposit account.
Your remaining balance after this transaction will be $IRON 1.70925479.
The memo will contain the graffiti "mml_node".

* This action is NOT reversible *

Do you confirm (Y/N)?: y
Creating the transaction: [████████████████████████████████████████] 100% | ETA: 0s
An error occurred while sending the transaction.
 ›   Error: Request failed (400) insufficient-balance: Your balance is too low. Add funds to your account first
```

### Graffiti

mml_node

**Comment by justmml** [comment]
Bug is still actual on 0.1.52

**Comment by hughy** [comment]
Can you share the outputs to `ironfish accounts:balance --explain`?

**Comment by justmml** [comment]
Yes, of course, here it is:
`root@vmi881185:~# ironfish accounts:balance --explain
Account: mml_wallet

Your balance is made of notes on the chain that are safe to spend
Balance: $IRON 2.92467300

0 notes worth $IRON 0.00000000 are on the chain within 2 blocks of the head
Unconfirmed: $IRON 2.92467300

2 notes worth $IRON 0.03265315 are waiting for miners to add them to the chain
Pending: $IRON 2.95732615`

Looks like my balance is unconfirmed?

**Comment by hughy** [comment]
```
Your balance is made of notes on the chain that are safe to spend
Balance: $IRON 2.92467300
```

You should be able to send transactions for up to this amount.

Could you also please share the output of `ironfish accounts:status`?

Thanks for your help!

**Comment by justmml** [comment]
Yep, hopes it will help:

`root@vmi881185:~# ironfish status
Version              0.1.52 @ 1bf0c8e
Node                 STARTED
Node Name            mml_node
Block Graffiti       mml_node
Memory               Heap: 99.26 MiB -> 171.68 MiB / 2.01 GiB (4.8%), RSS: 1.49 GiB (19.2%), Free: 5.91 GiB (23.9%)
CPU                  Cores: 4, Current: 122.6%
P2P Network          CONNECTED - In: 12.39 KB/s, Out: 51.20 KB/s, peers 49
Mining               STARTED - 0 miners, 0 mined
Mem Pool             Count: 407 tx, Bytes: 573.88 KiB
Syncer               IDLE - 0.34 blocks added/sec
Blockchain           000000000000001196588eb881ec34beac0943619f8520efa719092f26f61fea (273942), Since HEAD: 2m 56s (SYNCED)
Accounts             000000000000001196588eb881ec34beac0943619f8520efa719092f26f61fea (273942)
Telemetry            STARTED - 20275 <- 62 pending
Workers              STARTED - 0 -> 0 / 3 - 0.54 jobs Δ, 7.18 jobs/s`

**Comment by justmml** [comment]
If you need more information - I'm happy to help

**Comment by hughy** [comment]
Which of the two accounts is currently being used as the node's default account?

You can run `ironfish accounts:which` to be sure.

It looks like your account `mml_wallet` has enough of a balance to send, but the error `Error: Request failed (400) insufficient-balance: Your balance is too low. Add funds to your account first` suggests that a different balance is being read when the node starts to create a transaction

**Comment by justmml** [comment]
I'm sure that I'm using mml_wallet:
`root@vmi881185:~# ironfish accounts:which`
`mml_wallet`
`root@vmi881185:~# ironfish accounts:balance`
`Account: mml_wallet`
`Balance: $IRON 2.88480595`
I'm using it since 05.2022, when I started with Ironfish

**Comment by justmml** [comment]
Also, I was making successful transactions till my balance was about 2.5 $IRON
`root@vmi881185:~# ironfish accounts:balance default`
`Account: default`
`Balance: $IRON 0.00000000`
`root@vmi881185:~# ironfish accounts:balance mml_wallet`
`Account: mml_wallet`
`Balance: $IRON 2.92467300`

**Comment by hughy** [comment]
I think your account may have been affected by a bug addressed in #2595 

The bug results in the balance showing a value that is higher than your actual balance on the chain. We're working on getting a fix out soon

**Comment by justmml** [comment]
I'll check this bug after #2595 fixing and send you information. Thx a lot

**Comment by justmml** [comment]
After updating to 0.1.53 I used command `ironfish accounts:repair` and now my balance is correct.
If it'll be a trouble with transaction - I'll add a comment to this issue
