### ISSUE TITLE
Chain Sync Going Backwards & Also Another Double Spend (271993)

### ISSUE THREAD

**Issue by airj1012** [iron-fish/ironfish#2593]
### What happened?

Notice that my chain sync was moving in reverse. See screens and the time is visible in the bottom right corner.

Also noticed another double spend. See second line from the bottom in the last screen. Not sure if that is evidence of another hard fork, but thought that was an issue before.
![2022 11 16 - Ironfish Error v10](https://user-images.githubusercontent.com/64874325/202228325-71b3c3f4-24df-44b9-b547-2140bb33e455.png)
![2022 11 16 - Ironfish Error v11](https://user-images.githubusercontent.com/64874325/202228333-7222006d-2334-4795-bb1c-1e2159c807ee.png)
![2022 11 16 - Ironfish Error v12](https://user-images.githubusercontent.com/64874325/202228344-0b06a093-e3a8-44cc-81b4-4a0ca252951a.png)

### Version

0.1.52

### Graffiti

airj1012

**Comment by airj1012** [comment]
Now the chain is moving in the right direction again. But I lost of "hard work"

**Comment by hughy** [comment]
There are still some nodes out there that are still gossiping blocks from the invalid chain. Now that the valid chain has surpassed it we're unlikely to see this problem again during the testnet.
