### ISSUE TITLE
negative balance after accounts:-repair

### ISSUE THREAD

**Issue by useroop** [iron-fish/ironfish#2622]
### What happened?

After updating node and using new command "ironfish accounts:repair" my balance turned to negative.

this issue is possibly related to the problem of pending balances that have already been expaired.

![image](https://user-images.githubusercontent.com/43512615/202898254-a8a2e757-e8d9-413e-a380-8b0ca1892efe.png)

### Version

0.1.53

### Debug output

```shell
Iron Fish version               0.1.53 @ de27e51
Iron Fish library               0.0.30 @ de27e51
Operating system                Linux x64
CPU model(s)                    AMD Ryzen 5 3600 6-Core Processor
CPU threads                     12
RAM total                       62.74 GiB
Heap total                      4.01 GiB
Node version                    v16.17.0
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       ironfish_1
Block graffiti                  ironfish_1
```

### Graffiti

ironfish_1

**Comment by hughy** [comment]
`accounts:repair` unfortunately has a bug that doesn't account for expired transactions or expired transactions that are "stuck" in the wallet. A fix is up for review in #2623

**Comment by hughy** [comment]
The fix in #2623 has been released. Try running `accounts:repair` again and let me know if it resolves the negative balance!

**Comment by useroop** [comment]
Super! The problem was resolved.
![image](https://user-images.githubusercontent.com/43512615/203008501-7d30b697-1d9c-44d2-9bcc-f5fd807b184d.png)

**Comment by hughy** [comment]
Excellent! Glad to see this issue resolved 😁
