### ISSUE TITLE
Error parsing message

### ISSUE THREAD

**Issue by GMND** [iron-fish/ironfish#2625]
### What happened?

Version              0.1.54 @ 22e9f8c
Node                 STARTED
Node Name            SSL_Mining
Block Graffiti       SSL_Mining
Memory               Heap: 49.61 MiB -> 129.98 MiB / 4.01 GiB (1.2%), RSS: 557.05 MiB (0.4%), Free: 4.34 GiB (96.6%)
CPU                  Cores: 32, Current: 9.3%
P2P Network          CONNECTED - In: 2.37 KB/s, Out: 69.30 KB/s, peers 47
Mining               STARTED - 0 miners, 0 mined
Mem Pool             Count: 137 tx, Bytes: 200.94 KiB
Syncer               IDLE - 4.40 blocks added/sec
Blockchain           0000000000002d28bce851256d1d11907872e58dffca2511eacdc9c87ecdb6ed (278899), Since HEAD: 4m 26s (SYNCED)
Accounts             0000000000002d28bce851256d1d11907872e58dffca2511eacdc9c87ecdb6ed (278899)
Telemetry            STARTED - 2924 <- 52 pending
Workers              STARTED - 0 -> 0 / 16 - 0 jobs Δ, 0.35 jobs/s

### Version

0.1.54 @ 22e9f8c

### Debug output

D:\IRONFISH\0.1.54>ironfish debug
Iron Fish version                  0.1.54 @ 22e9f8c
Iron Fish library                  0.0.31 @ 22e9f8c
Operating system                   Windows_NT x64
CPU model(s)                       AMD Ryzen 9 5950X 16-Core Processor
CPU threads                        32
RAM total                          127.91 GiB
Heap total                         4.01 GiB
Node version                       v16.13.0
ironfish in PATH                   true
Garbage Collector Exposed          false
Telemetry enabled                  true
Node name                          SSL_Mining
Block graffiti                     SSL_Mining
Account f8c2f2 uuid                f8c2f259-fa98-4a01-aedb-b273c85eefd1
Account f8c2f2 name                default
Account f8c2f2 head hash           0000000000002d28bce851256d1d11907872e58dffca2511eacdc9c87ecdb6ed
Account f8c2f2 head in chain       true
Account f8c2f2 sequence            278899

### Relevant log output

```shell
D:\IRONFISH\0.1.54>ironfish start


::::::::::          :::::::::::::::::
::::::::::::       :::::::::::::::::::
:::::::::::::     :::::::::::::::::::::
::::::::::::::   ::::::::::::::::::::::::
 ::::::::::::: ::::::::::        :::::::::
   :::::::::::::::::::::          ::::::::::
   :::::::::::::::::::::          :::::::::
 ::::::::::::: ::::::::::        :::::::::
::::::::::::::   ::::::::::::::::::::::::
:::::::::::::     :::::::::::::::::::::
::::::::::::       :::::::::::::::::::
::::::::::           ::::::::::::::::

Version       0.1.54 @ 22e9f8c
Node Name     SSL_Mining
Graffiti      SSL_Mining
Peer Identity krS85xxaqbsxF/KbAhPn3w++BKgozgH7Ku6xw6ANbU8=
Peer Agent    ironfish/0.1.54/22e9f8c
Peer Port     9033
Bootstrap     test.bn1.ironfish.network

WebSocket server started at :::9033
Connected to the Iron Fish network
Already have a WebSocket connection, ignoring the new one
Already have a WebSocket connection, ignoring the new one
Starting sync from V+6BlnN (tetsugyo). work: +77721337166580258, ours: 278568, theirs: 278629
Finding ancestor using linear search on last 3 blocks starting at 00000...d4fb5 (278568) from peer V+6BlnN (tetsugyo) at 278629
Found peer V+6BlnN (tetsugyo) ancestor 00000...d4fb5, syncing from 278568 -> 278629 (61) after 1 requests
Requesting 5 blocks starting at 00000...d4fb5 (278568) from V+6BlnN (tetsugyo)
Requesting 5 blocks starting at 00000...b56cd (278573) from V+6BlnN (tetsugyo)
Requesting 5 blocks starting at 00000...42419 (278578) from V+6BlnN (tetsugyo)
Requesting 5 blocks starting at 00000...d3bd2 (278583) from V+6BlnN (tetsugyo)
Added block seq: 278580, hash: 00000...1c557, txs: 45, progress: 99.98%, time: 281.0ms
Requesting 5 blocks starting at 00000...4fd17 (278588) from V+6BlnN (tetsugyo)
Requesting 5 blocks starting at 00000...15484 (278593) from V+6BlnN (tetsugyo)
Requesting 5 blocks starting at 00000...f0bd2 (278598) from V+6BlnN (tetsugyo)
Requesting 5 blocks starting at 00000...2eaba (278603) from V+6BlnN (tetsugyo)
Added block seq: 278600, hash: 00000...4b175, txs: 20, progress: 99.99%, time: 132.2ms
Requesting 5 blocks starting at 00000...893ec (278608) from V+6BlnN (tetsugyo)
Requesting 5 blocks starting at 00000...e13a6 (278613) from V+6BlnN (tetsugyo)
Requesting 5 blocks starting at 00000...587f2 (278618) from V+6BlnN (tetsugyo)
Requesting 5 blocks starting at 00000...e8030 (278623) from V+6BlnN (tetsugyo)
Added block seq: 278620, hash: 00000...341f8, txs: 33, progress: 100.00%, time: 189.5ms
Requesting 5 blocks starting at 00000...27a0b (278628) from V+6BlnN (tetsugyo)
Finished syncing from V+6BlnN (tetsugyo)
Starting sync from JXsHcwH (Leste). work: +1253252373037778, ours: 278630, theirs: 278631
Finding ancestor using linear search on last 3 blocks starting at 00000...d8116 (278630) from peer JXsHcwH (Leste) at 278631
Found peer JXsHcwH (Leste) ancestor 00000...d8116, syncing from 278630 -> 278631 (1) after 1 requests
Requesting 5 blocks starting at 00000...d8116 (278630) from JXsHcwH (Leste)
Finished syncing from JXsHcwH (Leste)
Reorganizing chain from 00000...daaba (278638) for 00000...cfb6b (278638) on prev 00000...85eff (278637)
Reorganized chain. blocks: 1, old: 00000...daaba (278638), new: 00000...85eff (278637), fork: 00000...85eff (278637)
Added block seq: 278640, hash: 00000...10ac4, txs: 16, progress: 100.00%, time: 83.4ms
Already have a WebSocket connection, ignoring the new one
Error parsing message
```

### Graffiti

SSL_Mining

**Comment by hughy** [comment]
A recent version of ironfish (v0.1.52) dropped support for an older message schema. Some nodes on the network are still running older versions, so they may still send unsupported messages occasionally. You can safely ignore this message
