### ISSUE TITLE
Deposit Fee High

### ISSUE THREAD

**Issue by azharsarbudeen** [iron-fish/ironfish#2643]
### What happened?

I use Ironfish Deposit but the recommended fees are so high![Ironfish deposit fee high](https://user-images.githubusercontent.com/108316660/203886353-67c9fead-adbf-407c-9639-28114441a789.png)

### Version

v0.1.54

### Graffiti

azharsarbudeen

**Comment by hughy** [comment]
Thanks for bringing this to our attention!

You don't need to use the recommended/suggested fees. With many blocks currently containing very few transactions you should be able to use a very low fee.

We're planning on making changes to fee estimation to address this soon!

**Comment by azharsarbudeen** [comment]
okay, great!

i love Ironfish team  :)

**Comment by hughy** [comment]
The issue with very high recommended fees should be resolved by #2549

**Comment by azharsarbudeen** [comment]
Hi Hugh, can i know does this issue count as Pull Request? On 2 Feb 2023, at 3:02 AM, Hugh Cunningham ***@***.***> wrote:﻿
Closed #2643 as completed.

**Comment by hughy** [comment]
This will count as a bug report. You can claim points for the bug report by submitting this form: https://forms.gle/bLfwN9jb14ZWkHkZA

**Comment by azharsarbudeen** [comment]
Okay, thanks Hugh.  From: Hugh CunninghamSent: Thursday, February 2, 2023 9:56 AMTo: iron-fish/ironfishCc: azharsarbudeen; AuthorSubject: Re: [iron-fish/ironfish] Deposit Fee High (Issue #2643) This will count as a bug report. You can claim points for the bug report by submitting this form: https://forms.gle/bLfwN9jb14ZWkHkZA—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
