### ISSUE TITLE
[node is not connected: has been banned: Miner's fee is incorrect / Peer LnJwqRE (usti) disconnected (DISCONNECTED) while syncing.]

### ISSUE THREAD

**Issue by mikane** [iron-fish/ironfish#2644]
### What happened?

When I tried to starting a node, it's deconnected and I'm getting this error:

Requesting 5 blocks starting at 00000...a6e31 (279899) from LnJwqRE (usti)
Peer LnJwqRE (usti) sent an invalid block. score: 10, hash: 00000...9abb9 (279900), reason: Miner's fee is incorrect
Peer LnJwqRE (usti) has been banned: Miner's fee is incorrect
Peer LnJwqRE (usti) disconnected (DISCONNECTED) while syncing.
Starting sync from ypL4Ydm. work: +1070198535454806243, ours: 279901, theirs: 285487
Finding ancestor using linear search on last 3 blocks starting at 00000...1957b (279901) from peer ypL4Ydm at 285487
Found peer ypL4Ydm ancestor 00000...a6e31, syncing from 279899 -> 285487 (5588) after 2 requests

### Version

Version       0.1.51 @ 67da183

### Graffiti

Mikane

**Comment by mikane** [comment]
Now it's seem to run in a first window I can read something like this:

Added block seq: 27380, hash: 00000...45e56, txs: 110, progress: 9.49%, time: 730.2ms
Requesting 5 blocks starting at 00000...05976 (27382) from CTK0kBg (Batska)
Requesting 5 blocks starting at 00000...25650 (27387) from CTK0kBg (Batska)
Requesting 5 blocks starting at 00000...7299d (27392) from CTK0kBg (Batska)
Requesting 5 blocks starting at 00000...9a466 (27397) from CTK0kBg (Batska)
Added block seq: 27400, hash: 00000...de941, txs: 231, progress: 9.50%, time: 1185.8ms
Requesting 5 blocks starting at 00000...b5bd7 (27402) from CTK0kBg (Batska)
Requesting 5 blocks starting at 00000...e06ef (27407) from CTK0kBg (Batska)
Requesting 5 blocks starting at 00000...6a528 (27412) from CTK0kBg (Batska)
Requesting 5 blocks starting at 00000...53130 (27417) from CTK0kBg (Batska)
Added block seq: 27420, hash: 00000...58441, txs: 68, progress: 9.51%, time: 465.4ms
Requesting 5 blocks starting at 00000...ecb88 (27422) from CTK0kBg (Batska)
Requesting 5 blocks starting at 00000...3b1a7 (27427) from CTK0kBg (Batska)
Requesting 5 blocks starting at 00000...4e59c (27432) from CTK0kBg (Batska)
Requesting 5 blocks starting at 00000...cd28a (27437) from CTK0kBg (Batska)
Added block seq: 27440, hash: 00000...4f49b, txs: 169, progress: 9.51%, time: 952.8ms
Requesting 5 blocks starting at 00000...ab116 (27442) from CTK0kBg (Batska)
Requesting 5 blocks starting at 00000...c2680 (27447) from CTK0kBg (Batska)
Requesting 5 blocks starting at 00000...12cb6 (27452) from CTK0kBg (Batska)
Requesting 5 blocks starting at 00000...b6205 (27457) from CTK0kBg (Batska)
Added block seq: 27460, hash: 00000...6526d, txs: 73, progress: 9.52%, time: 446.1ms
Requesting 5 blocks starting at 00000...18da5 (27462) from CTK0kBg (Batska)
Requesting 5 blocks starting at 00000...b9cc1 (27467) from CTK0kBg (Batska)
Requesting 5 blocks starting at 00000...f7e36 (27472) from CTK0kBg (Batska)
.....etc

But went I ask:
ironfish status -f

The answer is:
Node: STOPPED

And I don't win any rewards since last tuesday in the incentivized testnet Leaderboard.

Thank's for your help. ;)

**Comment by hughy** [comment]
Your node is a few versions behind, and versions 0.1.52 and 0.1.53 included consensus changes. In particular, v0.1.53 disabled mining rewards. Your node is banning peers that send blocks that use the new miner's fee (0).

> And I don't win any rewards since last tuesday in the incentivized testnet Leaderboard.

The Phase 2 testnet ended last Tuesday, so no more points will be added for hosting a node

**Comment by mikane** [comment]
Thanks a lot for those clarifications Hughy.
