### ISSUE TITLE
ironfish accounts:repair doesn't work correctly

### ISSUE THREAD

**Issue by justmml** [iron-fish/ironfish#2647]
### What happened?

Usage of `ironfish accounts:repair` command doesn't get (or saves) correct balance:

```
root@vmi881185:~# ironfish accounts:balance
Account: mml_wallet
Balance: $IRON 2.98348675
root@vmi881185:~# sudo systemctl stop ironfishd
root@vmi881185:~# ironfish accounts:balance
Account: mml_wallet
Balance: $IRON 2.98348675
root@vmi881185:~# sudo systemctl stop ironfishd
root@vmi881185:~# ironfish accounts:repair
Repairing wallet for account mml_wallet
Repairing expired transactions
Repaired 81 expired transactions stuck in unexpired state.
Repairing balance
	Saving new unconfirmed balance: $IRON 0.28015240
	Repaired 314 decrypted notes incorrectly marked as unspent
Repairing nullifierToNote
	Repaired 0 nullifiers that map to notes that are not in the wallet
Repairing sequenceToNoteHash
	Repaired 0 incorrect sequenceToNoteHash mappings
root@vmi881185:~# sudo systemctl restart ironfishd
root@vmi881185:~# ironfish accounts:balance
Account: mml_wallet
Balance: $IRON 1.26948809
root@vmi881185:~# ironfish accounts:balance
Account: mml_wallet
Balance: $IRON 1.26948809
root@vmi881185:~# sudo systemctl restart ironfishd
root@vmi881185:~# ironfish accounts:balance
Account: mml_wallet
Balance: $IRON 1.26948809
root@vmi881185:~# ironfish deposit
Your balance is $IRON 1.26948809.
You are about to send $IRON 1.20000000 plus a transaction fee of $IRON 0.00000012 to the Iron Fish deposit account.
Your remaining balance after this transaction will be $IRON 0.06948797.
The memo will contain the graffiti "mml_node".

* This action is NOT reversible *
      
Do you confirm (Y/N)?: Y
Creating the transaction: [████████████████████████████████████████] 100% | ETA
An error occurred while sending the transaction.
 ›   Error: Request failed (400) insufficient-balance: Your balance changed 
 ›   while creating a transaction.
root@vmi881185:~# ironfish accounts:balance
Account: mml_wallet
Balance: $IRON 1.26948809
root@vmi881185:~# sudo systemctl stop ironfishd
root@vmi881185:~# ironfish accounts:balance
Account: mml_wallet
Balance: $IRON 1.26948809
root@vmi881185:~# ironfish accounts:repair
Repairing wallet for account mml_wallet
Repairing expired transactions
Repaired 81 expired transactions stuck in unexpired state.
Repairing balance
	Saving new unconfirmed balance: $IRON 0.28015240
	Repaired 314 decrypted notes incorrectly marked as unspent
Repairing nullifierToNote
	Repaired 0 nullifiers that map to notes that are not in the wallet
Repairing sequenceToNoteHash
	Repaired 0 incorrect sequenceToNoteHash mappings
root@vmi881185:~# ironfish accounts:balance
Account: mml_wallet
Balance: $IRON 0.28015240
root@vmi881185:~# sudo systemctl restart ironfishd
root@vmi881185:~# ironfish accounts:balance
Account: mml_wallet
Balance: $IRON 1.37680861

```

Looks like I get wrong balance after restarting node. But to use repair command correctly I need to stop the node, use `ironfish accounts:repair` command, and then restart the ironfishd service. So it's definitely a bug.

### Version

0.1.54

### Debug output

```shell
Iron Fish version               0.1.54 @ 22e9f8c
Iron Fish library               0.0.31 @ 22e9f8c
Operating system                Linux x64
CPU model(s)                    AMD EPYC 7282 16-Core Processor
CPU threads                     4
RAM total                       7.77 GiB
Heap total                      2.01 GiB
Node version                    v16.17.0
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       mml_node
Block graffiti                  mml_node
```

### Graffiti

mml_node

**Comment by hughy** [comment]
Could you share the outputs of `ironfish status` and `ironfish accounts:status`?

If your accounts are scanning then your balance may change as new transactions are scanned. I'd like to rule out that possibility

**Comment by justmml** [comment]
Yep, of course
`ironfish status` : 
root@vmi881185:~# ironfish status
Version              0.1.54 @ 22e9f8c
Node                 STARTED
Node Name            mml_node
Block Graffiti       mml_node
Memory               Heap: 60.38 MiB -> 106.19 MiB / 2.01 GiB (2.9%), RSS: 735.49 MiB (9.2%), Free: 6.82 GiB (12.2%)
CPU                  Cores: 4, Current: 75.4%
P2P Network          CONNECTED - In: 211 B/s, Out: 737 B/s, peers 46
Mining               STARTED - 0 miners, 0 mined
Mem Pool             Count: 0 tx, Bytes: 0 B
Syncer               IDLE - 8.73 blocks added/sec
Blockchain           0000000000056787903bf49b21c05af928e7c9a1174e8cc00b6d6e2a2419d710 (288765), Since HEAD: 1m 41s (SYNCED)
Accounts             0000000000056787903bf49b21c05af928e7c9a1174e8cc00b6d6e2a2419d710 (288765)
Telemetry            STARTED - 1662 <- 6 pending
Workers              STARTED - 0 -> 0 / 3 - 0 jobs Δ, 0.02 jobs/s

`ironfish accounts:status` :
root@vmi881185:~# ironfish accounts:status
 Account Name Account ID                           Head Hash                  Head In Chain Head Sequence 
 ──────────── ──────────────────────────────────── ────────────────────────── ───────────── ───────────── 
 mml_wallet   5e199487-5b7b-4889-ab20-fd9372f096c4 000000000003b00a0054c9683… true          288768        
 default      b1ef0178-b2ae-4822-b2fd-72f16e61b2ec 000000000003b00a0054c9683… true          288768        

And of course, I'm using wallet mml_wallet:
root@vmi881185:~# ironfish accounts:which
mml_wallet

**Comment by justmml** [comment]
Bad luck that I cannot do it because I need to start node to deposit, but right after node starting my balance is wrong:

root@vmi881185:~# sudo systemctl stop ironfishd
root@vmi881185:~# ironfish accounts:repair
Repairing wallet for account mml_wallet
Repairing expired transactions
Repaired 81 expired transactions stuck in unexpired state.
Repairing balance
	Saving new unconfirmed balance: $IRON 0.28015240
	Repaired 314 decrypted notes incorrectly marked as unspent
Repairing nullifierToNote
	Repaired 0 nullifiers that map to notes that are not in the wallet
Repairing sequenceToNoteHash
	Repaired 0 incorrect sequenceToNoteHash mappings
root@vmi881185:~# ironfish deposit
Cannot connect to your node, start your node first.
root@vmi881185:~# sudo systemctl restart ironfishd
root@vmi881185:~# ironfish deposit

Your balance is $IRON 0.93773261.

You are about to send $IRON 0.90000000 plus a transaction fee of $IRON 0.00000012 to the Iron Fish deposit account.
Your remaining balance after this transaction will be $IRON 0.03773249.
The memo will contain the graffiti "mml_node".

* This action is NOT reversible *
      
Do you confirm (Y/N)?: y
Creating the transaction: [████████████████████████████████████████] 100% | ETA: 0s
An error occurred while sending the transaction.
 ›   Error: Request failed (400) insufficient-balance: Your balance changed while creating a transaction.

**Comment by hughy** [comment]
I'd suggest sending the balance found by `accounts:repair`: $IRON 0.28

This balance is based on the unspent notes that the command finds for your account. Some transaction sseem to be getting synced to your wallet after the node starts that show an incorrect balance

**Comment by justmml** [comment]
I couldn't send a transaction, because `deposit` command is trying to send more than 0.28 IRON. But it doesn't matter, what matters is to find this bug. It's fixing will be more useful for the whole network than 2 points for me ;)
