### ISSUE TITLE
cli hangs indefinitely despite ctrl+c / sigint

### ISSUE THREAD

**Issue by UnsungHero97** [iron-fish/ironfish#27]
After starting the node and miner, it seemed like nothing was happening. I decided to kill both, but the node does not get killed. It hangs indefinitely despite multiple ctrl+c. 

<img width="530" alt="Screen Shot 2021-04-08 at 10 14 27 AM" src="https://user-images.githubusercontent.com/440299/114068848-355e1d80-9853-11eb-8bb9-3b7b1443157b.png">

macOS v10.15.7
node v15.14.0
npm v7.7.6

**Comment by dguenther** [comment]
We tried to fix this by limiting the number of connections the node attempts to establish at once, but it may still be lingering -- double-check you're up to date with the latest source or deployment and see if it's still an issue. If it is, we'll have to do some more debugging on it.

**Comment by UnsungHero97** [comment]
It's still happening, 99% sure I'm on the latest.

**Comment by dguenther** [comment]
Got it -- I have two suspicions here, one is that it might be running out of memory, and the other is that it might be related to network congestion issues that are blocking the main thread. We need to fix both of those issues, and I'm currently working on the network congestion issues, but if you're seeing it max out your memory, you might be able to set a limit on the process's memory to get around those issues for now.

**Comment by UnsungHero97** [comment]
Ran into the issue again, but instead of manually killing the process, I just let it be for a while and got this:

```
Shutting down node after SIGINT
Shutting down node after SIGINT
Shutting down node after SIGINT
Shutting down node after SIGINT
Shutting down node after SIGINT
Shutting down node after SIGINT
Shutting down node after SIGINT
Shutting down node after SIGINT
Shutting down node after SIGINT
(node:61155) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(node:61155) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
Shutting down node after SIGINT
```

**Comment by UnsungHero97** [comment]
I agree. I think the issue is the main thread being blocked. I'll close for now, and will reopen if this is still an issue after y'all release the block syncing + network congestion fixes.
