### ISSUE TITLE
[Windows / docker toolbox] Another node is using the database, waiting for that node to close.

### ISSUE THREAD

**Issue by ElderOrb** [iron-fish/ironfish#28]
![image](https://user-images.githubusercontent.com/23638/114094819-6e36da80-98c5-11eb-9e6d-6ece014c33cc.png)

This is on windows, Docker Toolbox

**Comment by dguenther** [comment]
Sometimes if a node crashes, it seems like it doesn't clean up the database properly. In the database folder there's a `LOCK` file you can delete, then try restarting the node and see if it connects to the database as expected.

You can also try restarting your PC and see if that might clear out any nodes that were created but stuck in the background somewhere.

**Comment by lutianxiong** [comment]
Is the issue solved?

**Comment by surenderverma509** [comment]
no

**Comment by earningdose** [comment]
Same Error I'm facing 😪
Help pls

**Comment by UEhQZXI** [comment]
> 我面临同样的错误😪 请帮助

Because IronFish will automatically start the node after installation, so instead of typing the start command manually, you can type ironfish status to see the status of the node.

**Comment by surenderverma509** [comment]
> 

Bro you need to install your node and install it again, you will not lose your earnings, just configuration has to rb done with same information and it will work, atleast it worked for me, good luck..
