### ISSUE TITLE
Cant import Account

### ISSUE THREAD

**Issue by brahitoz** [iron-fish/ironfish#2877]
### What happened?

A bug happened! when i try to import accaunt i see Provided public address b1533ed68878e22222669e0254ab8eab06866aa7c04609c013e18d8b                                                                                                                                       a4923f18475592a79c015ac65774d5 is invalid . I try to use file backup file. also i try to use "name", "spendingKey"  "incomingViewKey": "outgoingViewKey" "publicAddress" manually, always i see that adress is invalid. 

### Version

v0.1.57

### Debug output

```shell
Iron Fish version               0.1.57 @ 7886c32
Iron Fish library               0.0.34 @ 7886c32
Operating system                Linux x64
CPU model(s)                    AMD Ryzen Threadripper 3970X 32-Core Processor
CPU threads                     64
RAM total                       62.74 GiB
Heap total                      4.00 GiB
Node version                    v18.12.1
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               false
Node name                       dda
Block graffiti                  dda
```

### Graffiti

dda

**Comment by mat-if** [comment]
Thanks for reporting this - we're updating the import command to only require a name and the spending key. This fix will be released in the next version (0.1.58). https://github.com/iron-fish/ironfish/pull/2888

Feel free to re-open or file a new issue if the problem persists when we release the next version
