### ISSUE TITLE
mining pool feature doesn't work (0.1.57)

### ISSUE THREAD

**Issue by wk27** [iron-fish/ironfish#2886]
### What happened?

I've tried to start my own local pool and it looks like don't work

Node:
/usr/bin/yarn --cwd ${HOME}/ironfish/ironfish-cli/ ironfish start --rpc.tcp --rpc.tcp.host=192.168.88.229 --rpc.tcp.port=1337

**telnet says that connection is OK, but**:
/usr/bin/yarn --cwd ${HOME}/ironfish/ironfish-cli/ ironfish miners:start -v -t 12 --no-richOutput -a 1e3e33aca465830186aa465edb5522ee604d9018d3d00f9e0cdde83eb0dc39e9 --pool=192.168.88.229:1337 --rpc.tcp

Connecting to pool...
Successfully connected to pool
Subscribing to pool to receive work
Disconnected from pool unexpectedly. Reconnecting.
Successfully connected to pool
Subscribing to pool to receive work
Disconnected from pool unexpectedly. Reconnecting.

**I've tried to use the official pool (pool.ironfish.network), but it says**
Disconnected: You have been banned from the pool until Wed, 11 Jan 2023 19:19:34 GMT: Invalid public address: 1e3e33aca465830186aa465edb5522ee604d9018d3d00f9e0cdde83eb0dc39e9

I'm sure I use the correct address from wallet:export output.
I know that 3rd testnet isn't started yet, but may be it's a bug...

### Version

0.1.57

### Graffiti

Iron_Fish

**Comment by mat-if** [comment]
Hi @wk27 

Thanks for reporting this! Can you show me what command you used to start the pool? This definitely does not look right.

As for the official pool - it hasn't been updated to the newer version yet, we will get that sorted today.

**Comment by wk27** [comment]
Hi @mat-if 

It was not a bug, it's my mistake
`/usr/bin/yarn --cwd ${HOME}/ironfish/ironfish-cli/ ironfish start --rpc.tcp --rpc.tcp.host=192.168.88.229 --rpc.tcp.port=1337`
This command started "rpc over tcp" socket, not a mining pool.

The correct way is
`/usr/bin/yarn --cwd ${HOME}/ironfish/ironfish-cli/ ironfish miners:pools:start -h 192.168.88.229:1337 --no-payouts --no-banning`

I will close this issue.
