### ISSUE TITLE
Feature: normalization of send/mint/burn transaction

### ISSUE THREAD

**Issue by hairtail** [iron-fish/ironfish#2909]
### Description

High level abstract for above mentioned transaction type. As described in https://github.com/iron-fish/ironfish/pull/2869, different transaction can be indicated with different `transaction.data.method`. As for `mint`/`burn` transaction, which has extra params, params can be contained in `transaction.data`. 
```
  account: string
  receives: {
    publicAddress: string
    amount: string
    memo: string
    assetId?: string
  }[]
  fee: string
  expiration?: number
  expirationDelta?: number
  data: {
    method: '0' | '1' | '2'
    params?: MintParams | BurnParams
  }
```

**Comment by lwisne** [comment]
Wwe are working on this!

**Comment by hughy** [comment]
This has been implemented on the createTransaction RPC endpoint!
