### ISSUE TITLE
importing an account interactively doesn't work as described in documentation

### ISSUE THREAD

**Issue by bashkirov1960** [iron-fish/ironfish#2910]
### What happened?

Expected:
while importing an account interactively ( as per procedure on page https://ironfish.network/docs/onboarding/iron-fish-wallet-commands) I should enter the name of an already existing wallet, a spending key, incoming view key, outgoing view key and public address and run "ironfish wallet:use wallet" to set the account as default
Actual:
immediately after entering a spending key I am informed that the wallet is imported. It is suggested to run "ironfish **accounts**:use wallet" command to set the account as default.
![import_account_interactively)](https://user-images.githubusercontent.com/79743419/212280784-f5b99a47-c3d3-4e88-a1d5-21a4623dd012.png)

### Version

0.1.58

### Debug output

```shell
Iron Fish version               0.1.58 @ d49b13f
Iron Fish library               0.0.35 @ d49b13f
Operating system                Linux x64
CPU model(s)                    AMD Ryzen 5 3600 6-Core Processor
CPU threads                     12
RAM total                       62.73 GiB
Heap total                      4.00 GiB
Node version                    v18.12.1
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       fred1960
Block graffiti                  fred1960
```

### Graffiti

fred1960

**Comment by wd021** [comment]
Updating here https://github.com/iron-fish/website/pull/265
