### ISSUE TITLE
Did You Mean For Accounts Pulling Wrong Suggestion

### ISSUE THREAD

**Issue by aswhale** [iron-fish/ironfish#2930]
### What happened?

When failing to type the correct command in accounts, the did you mean is not suggesting items in accounts:  When trying to use accounts:help or accounts:-help, I get suggestions for chain:show and blocks:show.  If it was intended to change from accounts to wallet, then the did you mean should link for accounts help should link like accounts:address did.

![capture](https://user-images.githubusercontent.com/114945271/212766479-b1e8fdba-2b2c-4f21-9500-6073140dd479.png)

### Version

0.1.58

### Debug output

```shell
Iron Fish version               0.1.58 @ d49b13f
Iron Fish library               0.0.35 @ d49b13f
Operating system                Windows_NT x64
CPU model(s)                    AMD Ryzen 9 4900H with Radeon Graphics
CPU threads                     16
RAM total                       15.36 GiB
Heap total                      2.00 GiB
Node version                    v18.13.0
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       aswhalesCook
Block graffiti                  aswhalesCook
```

### Graffiti

aswhalesCook

**Comment by holahula** [comment]
Closing - the tooltip suggestion is part of the CLI package and is outside of our control. Use `accounts --help` to get a list of acceptable commands
