### ISSUE TITLE
Progress indicators are off while synciing

### ISSUE THREAD

**Issue by lwisne** [iron-fish/ironfish#2969]
### What happened?

When syncing the chain from scratch, progress quickly zooms to ~65%, then slooowly moves from there. 

Basically, the entirety of the progress is crammed in that last 35%, making it feel slower than it was.

### Version

0.1.59

### Graffiti

lwisne

**Comment by wd021** [comment]
noticed this as well, will take a look into it

**Comment by wd021** [comment]
can't replicate it anymore

**Comment by holahula** [comment]
Closing - unreplicatable
