### ISSUE TITLE
can send 0 ammount assets in send transaction

### ISSUE THREAD

**Issue by fedor3825** [iron-fish/ironfish#2991]
### What happened?

A bug happened!

Hi!
You can send 0 ammount assets in send transaction, and it successfully send, and not give error about invalid asset amount, and then leaderboard count point for that send transaction with 0 asset and gives 200 point for this 0 asset amount transaction  !))) Its wrong!!!!) Check and repair pls this!

~# ironfish wallet:send                                                 ? Select the asset you wish to send d407236dcf9a0e257e5f66e6b2982a695ea55894bc34261a7c2c55181f522d55 (Luter777)
 Enter the amount (balance: 0.00000000): 
Enter the amount (balance: 0.00000000): 0 
Enter the the public address of the recipient: dfc2679369551e64e3950e06a88e68466e813c63b100283520045925adbe59ca 
Enter the fee amount in $IRON (min: 0.00000001 recommended: 0.00000001) [0.00000001]: 
You are about to send: d407236dcf9a0e257e5f66e6b2982a695ea55894bc34261a7c2c55181f522d55 0.00000000 plus a transaction fee of $IRON 0.00000001 to dfc2679369551e64e3950e06a88e68466e813c63b100283520045925adbe59ca from the account default * This action is NOT reversible * Do you confirm (Y/N)?: y Creating the transaction: [████████████████████████████████████████] 100% | ETA: 0 Sending d407236dcf9a0e257e5f66e6b2982a695ea55894bc34261a7c2c55181f522d55 0.00000000 to dfc2679369551e64e3950e06a88e68466e813c63b100283520045925adbe59ca from default Transaction Hash: 4c7033e8ac322449e139484d07c10eadd96b4677ee67e55b68491094d1c318ed Transaction fee: $IRON 0.00000001 

Find the transaction on https://explorer.ironfish.network/transaction/4c7033e8ac322449e139484d07c10eadd96b4677ee67e55b68491094d1c318ed (it can take a few minutes before the transaction appears in the Explorer)

![Screenshot_2023-01-18-22-53-09-147_com sonelli juicessh](https://user-images.githubusercontent.com/50149437/213312928-d581ca4a-49eb-4edf-9298-f503b581f85c.jpg)

### Version

0.1.61

### Graffiti

Luter777

**Comment by wd021** [comment]
i don't think this is a bug, you should be able to send a transaction with 0. someone may just want to send a memo.

**Comment by hughy** [comment]
We added minimum amount validation to the CLI
