### ISSUE TITLE
BalanceBug

### ISSUE THREAD

**Issue by KrotBegemot** [iron-fish/ironfish#2995]
### What happened?

When I attemp to send a few tarnsaction one by one appeared balance bug. It show zero balance in wallet. Since few minutes balance restore.
And all procedure repeat again with new 2 transactions.

![bugBalance](https://user-images.githubusercontent.com/48887448/213331261-520db34e-d47e-4896-8b9a-39c31f8035ad.jpg)

this comands was sent one by one in 20-40 seconds

![bugbalance2](https://user-images.githubusercontent.com/48887448/213331434-7bf14c3d-8f56-44f2-af80-93bcbbc3bf26.jpg)

### Version

0.1.61 @ 009c85e

### Debug output

```shell
Iron Fish version               0.1.61 @ 009c85e
Iron Fish library               0.0.38 @ 009c85e
Operating system                Linux arm64
CPU model(s)                    Neoverse-N1
CPU threads                     4
RAM total                       23.42 GiB
Heap total                      4.00 GiB
Node version                    v18.13.0
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       KrotBegemot
Block graffiti                  KrotBegemot
```

### Graffiti

KrotBegemot

**Comment by hughy** [comment]
When you send a transaction, some of your balance is temporarily unavailable until the transaction has been confirmed (or until it expires). We've updated the wallet to compute the available balance by summing the values of unspent notes to try to avoid errors like this.
