### ISSUE TITLE
The balance show uncorrectly

### ISSUE THREAD

**Issue by tonyhikarui** [iron-fish/ironfish#2999]
### What happened?

root@S202103104393:/usr/src/app# ironfish wallet:balance --all
Account: iron_1
Head Hash: 0000000000be052891d3bd20520ec6d32b66db38c5b8c3c993f02d58989effe7
Head Sequence: 2688
Balance:     $IRON 0.00000002
Unconfirmed: $IRON 20.00000000
root@S202103104393:/usr/src/app#
root@S202103104393:/usr/src/app#
root@S202103104393:/usr/src/app#
root@S202103104393:/usr/src/app#
root@S202103104393:/usr/src/app# ironfish wallet:balance --all
Account: iron_1
Head Hash: 0000000000be052891d3bd20520ec6d32b66db38c5b8c3c993f02d58989effe7
Head Sequence: 2688
Balance:     $IRON 20.00000000
Unconfirmed: $IRON 20.00000000
root@S202103104393:/usr/src/app# ironfish wallet:balance --all
Account: iron_1
Head Hash: 0000000000be052891d3bd20520ec6d32b66db38c5b8c3c993f02d58989effe7
Head Sequence: 2688
Balance:     $IRON 20.00000000
Unconfirmed: $IRON 20.00000000

the balance should be confirmed status,but is still shown as unconfirmed.

### Version

1.6.1

### Graffiti

tonyhikarui

**Comment by tonyhikarui** [comment]
After send 0.00000001 to other address, the status still uncorrect.
root@S202103104393:/usr/src/app# ironfish wallet:balance --all
Account: iron_1
Head Hash: 000000000058f7eb86de2f1c7ce1e057ca7b37b9beb354ebc135546e9f00c7be
Head Sequence: 2713
Balance:     $IRON 19.99999999
Unconfirmed: $IRON 19.99999999

**Comment by hughy** [comment]
The line for `Balance` is displaying your confirmed balance.

You can run `ironfish wallet:balance --explain` to see an explanation of the difference between confirmed and unconfirmed balance:

The `unconfirmed` balance is equal to your confirmed balance but includes transactions that are close to the head of the chain.
