### ISSUE TITLE
Syncer STOPPED

### ISSUE THREAD

**Issue by lionff** [iron-fish/ironfish#3001]
### What happened?

![photo_2023-01-18_23-04-14](https://user-images.githubusercontent.com/79597699/213399521-18e9e91e-8a92-4354-94fa-8099e9bb0764.jpg)

VPS with a low amount of CPU cores: 6 threads and 16 GB Ram

If I started the miner with a 1-3 threads, then the node syncer stopped. And it continue to sync only if I stopped a miner. And VPS worked not on 100% with node + miner.

Also I had a problem with a node.js version 19

### Version

0.1.61

### Graffiti

okayko

**Comment by holahula** [comment]
Closing due to staleness. If the issue persists in versions `1.0.0+` - please file a new issue

**Comment by holahula** [comment]
#3811 will track syncing issues
