### ISSUE TITLE
[issue name]

### ISSUE THREAD

**Issue by oracleooo** [iron-fish/ironfish#3004]
### What happened?

A bug happened! #
Sometimes the balance is not displayed and the transaction does not go through. It is displayed an error
![image](https://user-images.githubusercontent.com/123023528/213448457-1f085eb4-a29b-47e7-b532-2d4b19ec0ce2.png)

### Graffiti

oracleooo

**Comment by hughy** [comment]
v0.1.70 uses checks the available balance before attempting to send transactions.
