### ISSUE TITLE
 logs of the node

### ISSUE THREAD

**Issue by Mayovka** [iron-fish/ironfish#3005]
### What happened?

![photo_2023-01-19_15-01-32](https://user-images.githubusercontent.com/95088734/213450587-1e6528e6-1f3e-47d1-96b6-ef38c2aeeac5.jpg)
after stopping the miner, I check the logs of the node, most likely due to server overload, it was decided by the command -systemctl stop ironfishd
systemctl stop ironfishd-miner
rm -rf $HOME/.ironfish

### Version

v0.1.57

### Graffiti

mayovka

**Comment by hughy** [comment]
Closing this issue. It's not clear from the issue what the problem was or if the node was operating normally.
