### ISSUE TITLE
Node stopped while syncing

### ISSUE THREAD

**Issue by Vichuvi** [iron-fish/ironfish#3006]
### What happened?

node stopped 3 times (after restarting)
Requesting 5 blocks starting at 00000...3b53c (3252) from NohaG6F (t4ka)
Requesting 5 blocks starting at 00000...12eb8 (3257) from NohaG6F (t4ka)
Requesting 5 blocks starting at 00000...bfc9d (3262) from NohaG6F (t4ka)
Added block seq: 3260, hash: 00000...9be31, txs: 6, progress: 95.16%, time: 93.0ms
Requesting 5 blocks starting at 00000...1e098 (3267) from NohaG6F (t4ka)
PID 11050 received SIGSEGV for address: 0x7f1724216
/root/ironfish/node_modules/segfault-handler/build/Release/segfault-handler.node(+0x372d)[0x7f175c11f72d]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x7f175ca74520]
/root/.nvm/versions/node/v18.13.0/bin/node(napi_delete_reference+0x23)[0xb18f53]
/root/ironfish/ironfish-rust-nodejs/ironfish-rust-nodejs.linux-x64-gnu.node(+0x4b0fd)[0x7f173a3d90fd]
/root/.nvm/versions/node/v18.13.0/bin/node(_ZN4node13CallbackQueueIvJPNS_11EnvironmentEEE12CallbackImplIZN15node_napi_env__13CallFinalizerILb1EEEvPFvP10napi_env__PvS9_ES9_S9_EUlS2_E0_E4CallES2_+0x5b)[0xb321ab]
/root/.nvm/versions/node/v18.13.0/bin/node(_ZN4node11Environment27RunAndClearNativeImmediatesEb+0x1ac)[0xaf2e3c]
/root/.nvm/versions/node/v18.13.0/bin/node(_ZN4node11Environment14CheckImmediateEP10uv_check_s+0x76)[0xaf3446]
/root/.nvm/versions/node/v18.13.0/bin/node[0x165abb9]
/root/.nvm/versions/node/v18.13.0/bin/node(uv_run+0x1d0)[0x16532f0]
/root/.nvm/versions/node/v18.13.0/bin/node(_ZN4node13SpinEventLoopEPNS_11EnvironmentE+0x14d)[0xaafa2d]
/root/.nvm/versions/node/v18.13.0/bin/node(_ZN4node6worker6Worker3RunEv+0xf7b)[0xc3e14b]
/root/.nvm/versions/node/v18.13.0/bin/node[0xc3e718]
/lib/x86_64-linux-gnu/libc.so.6(+0x94b43)[0x7f175cac6b43]
/lib/x86_64-linux-gnu/libc.so.6(+0x126a00)[0x7f175cb58a00]
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Version

 0.1.61 @ 009c85e

### Debug output

```shell
root@DESKTOP-APKRAN5:~/ironfish/ironfish-cli# ironfish debug
Iron Fish version                  0.1.61 @ 009c85e
Iron Fish library                  0.0.38 @ 009c85e
Operating system                   Linux x64
CPU model(s)                       Intel(R) Core(TM) i5-4300M CPU @ 2.60GHz
CPU threads                        4
RAM total                          9.25 GiB
Heap total                         1.99 GiB
Node version                       v18.13.0
ironfish in PATH                   true
Garbage Collector Exposed          false
Telemetry enabled                  true
Node name                          V_Fish
Block graffiti                     V_Fish
Account 6b7569 uuid                6b756959-29f6-4eee-a769-6ba3d381fa6f
Account 6b7569 name                V_Fish
Account 6b7569 head hash           00000000007a8d75d9dc9b7ff40831975d1eb8d1ef6d513ea07464dda04f2bbd
Account 6b7569 head in chain       true
Account 6b7569 sequence            3264
root@DESKTOP-APKRAN5:~/ironfish/ironfish-cli#
```

### Graffiti

V_Fish

**Comment by ygao76** [comment]
segfault-handler issue is resolved.
