### ISSUE TITLE
Mined Blocks lost

### ISSUE THREAD

**Issue by KrotBegemot** [iron-fish/ironfish#3008]
### What happened?

My miner mined 2 blocks, but now node status shows that I have 0 mined blocks.

![0block](https://user-images.githubusercontent.com/48887448/213483511-3ba3660a-9790-4ad4-bed8-9badfb343cd1.jpg)

My miner logs:

![1Block](https://user-images.githubusercontent.com/48887448/213483588-7d6d2bf3-ef94-4f51-a66b-3f6a628af516.jpg)

![2block](https://user-images.githubusercontent.com/48887448/213483613-3a7bd9c2-d321-4183-b5d9-aedd2ebab62e.jpg)

Balances show correct data:

![balance](https://user-images.githubusercontent.com/48887448/213483712-d978dfde-f154-4786-9d6f-b89506972de9.jpg)

### Version

0.1.61 @ 009c85e

**Comment by hughy** [comment]
The node status command will only show how many blocks your miners have mined while your node has been running. If you restart the node then this amount will reset to 0.

As long as your balance is correct your wallet has not lost the blocks.

If you run `ironfish wallet:transactions` you should see two transactions with Type `miner` for the two blocks

**Comment by hughy** [comment]
Closing as stale.
