### ISSUE TITLE
[bug start]

### ISSUE THREAD

**Issue by mr-pologne** [iron-fish/ironfish#3010]
### What happened?

Hello, my node stopped and when I wanted to restart with the command "ironfish start" it started to synchronize but then it stopped and impossible to add any command or to detach the session. I turned my vps off and onagain and then my node restarted correctly.

![Capture d’écran 2023-01-19 170456](https://user-images.githubusercontent.com/108233038/213498330-0b4956de-d740-4b42-a64e-2fc8f3b967d3.png)

### Graffiti

stanbyme

**Comment by hughy** [comment]
The node seems to be running normally based on the screenshot. Please open a new issue if you've continued to run into issues when syncing.
