### ISSUE TITLE
Possibility to Send Asset with a 0 value

### ISSUE THREAD

**Issue by Danzou62** [iron-fish/ironfish#3012]
### What happened?

I was able to send 0 Danzoucoin (New asset created) to a Wallet and transaction has been registered

# ironfish wallet:send
? Select the asset you wish to send 00ac1a3b14f67e00b5e1337e8cc371962cf2a0c6c05e3d7c0b8264bfb3ba1068 (Danzoucoin)
Enter the amount (balance: 0.00000000): 0
Enter the the public address of the recipient: dfc2679369551e64e3950e06a88e68466e813c63b100283520045925adbe59ca
Enter the fee amount in $IRON (min: 0.00000001 recommended: 0.00000001) [0.00000001]: 0.00000001

You are about to send:
00ac1a3b14f67e00b5e1337e8cc371962cf2a0c6c05e3d7c0b8264bfb3ba1068 0.00000000 plus a transaction fee of $IRON 0.00000001 to dfc2679369551e64e3950e06a88e68466e813c63b100283520045925adbe59ca from the account default

* This action is NOT reversible *

Do you confirm (Y/N)?: y
Creating the transaction: [████████████████████████████████████████] 100% | ETA: 0s

Sending 00ac1a3b14f67e00b5e1337e8cc371962cf2a0c6c05e3d7c0b8264bfb3ba1068 0.00000000 to dfc2679369551e64e3950e06a88e68466e813c63b100283520045925adbe59ca from default
Transaction Hash: 37649b48dac856d69de60840d24fa5260fa2704f5c9e944e4a7a7f60ffee69a1
Transaction fee: $IRON 0.00000001

Find the transaction on https://explorer.ironfish.network/transaction/37649b48dac856d69de60840d24fa5260fa2704f5c9e944e4a7a7f60ffee69a1 (it can take a few minutes before the transaction appears in the Explorer)

### Version

v0.1.61

### Debug output

```shell
Iron Fish version               0.1.61 @ 009c85e
Iron Fish library               0.0.38 @ 009c85e
Operating system                Linux x64
CPU model(s)                    AMD Ryzen 7 5800X 8-Core Processor
CPU threads                     16
RAM total                       15.58 GiB
Heap total                      4.00 GiB
Node version                    v18.12.1
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       Danzou62
Block graffiti                  Danzou62
```

### Graffiti

Danzou62

Expected  :  
We should have an error message saying that amount is not sufficient as we ue fee for nothing

**Comment by hughy** [comment]
We've added input validation for the send amount.
