### ISSUE TITLE
Node crashed several times unexpected...

### ISSUE THREAD

**Issue by go6ooo** [iron-fish/ironfish#3016]
### What happened?

Trying to start again after crash several times to start running again...
[ifcrash.md](https://github.com/iron-fish/ironfish/files/10460159/ifcrash.md)

### Version

v0.1.61

### Graffiti

manChuMamaGleda6e

**Comment by holahula** [comment]
Closing, `segfault-handler` dependency was removed in PR #3545 so this is no longer an issue
