### ISSUE TITLE
The incorrect message about wrong email after the few faucets

### ISSUE THREAD

**Issue by ipohosov** [iron-fish/ironfish#3024]
### What happened?

STR:
1. Use **_ironfish faucet_** command 2 times with entering your email
2. Do it third time
3. Check error message

Expected result: The message displays some info that the faucet is limited and you can't do it now.
Actual result: Error message: **Collecting your funds... You entered an invalid email.**

<img width="1024" alt="screenshort" src="https://user-images.githubusercontent.com/6196297/213596541-9ce06764-bade-4429-ad09-0320c94f7935.png">
<img width="606" alt="screenshort" src="https://user-images.githubusercontent.com/6196297/213596534-4d3b5880-7335-42f9-9e40-e11591fa888f.png">

### Version

0.1.61 @ 009c85e

### Debug output

```shell
Iron Fish version               0.1.61 @ 009c85e
Iron Fish library               0.0.38 @ 009c85e
Operating system                Linux x64
CPU model(s)                    AMD EPYC 7282 16-Core Processor
CPU threads                     8
RAM total                       29.39 GiB
Heap total                      4.00 GiB
Node version                    v18.12.1
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       mplife
Block graffiti                  mplife
```

### Graffiti

mplife

**Comment by hallosayael** [comment]
Yes me too, I got the same error 
![image](https://user-images.githubusercontent.com/110147776/213605598-d138cd69-da99-436d-b7e7-a5b2fa8f7b0a.png)

**Comment by justmml** [comment]
Try to update your node to v.0.1.62
Looks like this issue is fixed

**Comment by ipohosov** [comment]
> Try to update your node to v.0.1.62 Looks like this issue is fixed

Yes now it's displayed as - Too many faucet requests.
Thanks
