### ISSUE TITLE
send transaction but not receive and amount not  right

### ISSUE THREAD

**Issue by coldneverdie** [iron-fish/ironfish#3029]
### What happened?

A bug happened!

**Comment by coldneverdie** [comment]
<img width="1332" alt="image" src="https://user-images.githubusercontent.com/3645071/213612167-4b88010b-42a0-42f3-b0e6-a82bfbeeb719.png">
Transaction Hash: 9d924bb2b9a264463d8cf1eea5c6d8d246a8f77a671a830b105f81203f18479e

i've done some trans
but can't see it on the block
it said have been done
but amount is not reduce
and can't receive it

**Comment by hughy** [comment]
It looks like this transaction is on the chain: https://explorer.ironfish.network/transaction/9d924bb2b9a264463d8cf1eea5c6d8d246a8f77a671a830b105f81203f18479e 

Does your confirmed balance still show an incorrect value?

What is the transaction status if you run `ironfish wallet:transaction 9d924bb2b9a264463d8cf1eea5c6d8d246a8f77a671a830b105f81203f18479e` ?
