### ISSUE TITLE
bug of sending but no points at leaderboard

### ISSUE THREAD

**Issue by hellogit2021** [iron-fish/ironfish#3031]
### What happened?

A bug happened!
if test : mint->send->burn, user will not get points,but if user test :mint->burn->send ,can get the points
at test phase 3

### Graffiti

fatgeek

**Comment by hallosayael** [comment]
I did a test: mint -> burn -> sent
But when the sent doesn't get points, even though the transaction is successful, but the mint and burn tests get points on the dashboard

![image](https://user-images.githubusercontent.com/110147776/213628530-904963a3-99d4-4295-9985-76e17163ccbe.png)

**Comment by hellogit2021** [comment]
yes, send will get no point anyway

**Comment by hughy** [comment]
Closing because the Phase 3 testnet has ended.
