### ISSUE TITLE
Registration possibility without filling all needed fields

### ISSUE THREAD

**Issue by aleksandrgulko** [iron-fish/ironfish#3038]
### What happened?

When I filled only nessesary fields (Email, Graffiti, Country) in registration form I had warning "Please fill out all fields".
![image](https://user-images.githubusercontent.com/117280102/213724070-1e07c074-a345-427c-a167-c8bf327f61c4.png)
But when I pressed "Sign Up" I successfully passed registration.

### Graffiti

miklyxa1

**Comment by ygao76** [comment]
thanks for reporting this.
