### ISSUE TITLE
telemetry errors

### ISSUE THREAD

**Issue by Mayovka** [iron-fish/ironfish#3039]
### What happened?

I see telemetry errors 503 in the node logs
![photo_2023-01-20_17-06-01](https://user-images.githubusercontent.com/95088734/213731524-6be57a0f-85ea-421f-a3c4-6b29f4db6447.jpg)

### Version

v0.1.62

### Graffiti

mayovka

**Comment by holahula** [comment]
Closing due to staleness. If the issue persists in versions `1.0.0+` - please file a new issue
