### ISSUE TITLE
The token balance display is not valid, tokens are not sent to the wallet[issue name]

### ISSUE THREAD

**Issue by AntonMatveychuk** [iron-fish/ironfish#3040]
### What happened?

The display of the token balance is not valid, tokens do not come to the wallet, I requested iron tokens in faucet also from discord users in the screenshot you can see that transactions took place but the balance has not changed, here is my public key:Account: matvey2705, public key: e0bf59ba71b50f8d816aaa43ae81856da13f69eea2041923c86d7515a8960b2f
![Знімок екрана (570)](https://user-images.githubusercontent.com/101927107/213751725-15c4b29a-c030-4ab8-9f2e-0782ae36e8ef.png)

### Version

Iron Fish v0.1.62

### Graffiti

matvey2705

**Comment by hughy** [comment]
@AntonMatveychuk could you post the output to `ironfish wallet:status` please?

This may happen if your wallet has not yet scanned the transactions after they have been added to the chain.

If the problem persists you can run `ironfish wallet:rescan --reset` to force a rescan of the transactions.

**Comment by hughy** [comment]
Closing as stale.
