### ISSUE TITLE
 Points are not fixed on the site

### ISSUE THREAD

**Issue by litvinch** [iron-fish/ironfish#3049]
### What happened?

Points are not fixed on the site if my graffiti contains the symbol "." I had to change the graffiti and only then my scores for actions were fixed in the testnet account

### Graffiti

litvinchuk1471

**Comment by hughy** [comment]
Could you explain more? What was your graffiti before and after the change?

Did you create a new account when changing graffiti?

**Comment by litvinch** [comment]
graffiti before: o.v.litvinchuk
graffiti after: litvinchuk1471

Сб, 21 янв. 2023 г. в 19:53, Hugh Cunningham ***@***.***>:

**Comment by litvinch** [comment]
I did not understand for a long time why points for graffiti are not
counted: o.v.litvinchuk.  I completed all the transactions, wrote in
discord, no one could help.  I noticed that no one crosses the dots in the
graffiti, so I decided to change the graffiti to: litvinchuk1471 in the
settings of my account ***@***.***  Then I reconfigured the
node and was credited with the points.


graffiti before: o.v.litvinchuk
graffiti after: litvinchuk1471

Сб, 21 янв. 2023 г. в 19:53, Hugh Cunningham ***@***.***>:

> Could you explain more? What was your graffiti before and after the change?
>
Did you create a new account when changing graffiti?
