### ISSUE TITLE
Sending mint asset with enough balance in wallet but show error with not enough balance

### ISSUE THREAD

**Issue by larryhopecode** [iron-fish/ironfish#3051]
### What happened?

Step 1. use ironfish wallet:send
Step 2. select one mint asset (customized asset) that has enough asset. for example: 1023 in balance
Step 3. enter the amount of asset to be sent. for example: 1
Step 4. enter "Y" to confirm
Then shows the error message of 
An error occurred while sending the transaction.    
 ›   Error: Request failed (400) insufficient-balance: Your balance is too low. Add funds to your account 
 ›   first   
![bug1](https://user-images.githubusercontent.com/12761142/213837709-4d883975-6347-440e-956c-89159e9e7c21.jpg)

### Version

0.1.62 

### Debug output

```shell
Iron Fish version               0.1.62 @ 4ab43f3
Iron Fish library               0.0.39 @ 4ab43f3
Operating system                Linux x64
CPU model(s)                    AMD Ryzen 9 5950X 16-Core Processor
CPU threads                     32
RAM total                       62.73 GiB
Heap total                      4.00 GiB
Node version                    v18.13.0
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       Ironman2021
Block graffiti                  Ironman2021
```

### Graffiti

Ironman2021

**Comment by gggsssaaa** [comment]
You need 0.00000001 $IRON to do it (transaction fee).. try to do _ironfish faucet_

**Comment by larryhopecode** [comment]
Already done that BEFORE the send. The account has 0.0000004 $IRON on that time.
