### ISSUE TITLE
Asset name specified with quotes doesn't count in your leaderboard

### ISSUE THREAD

**Issue by jurlit** [iron-fish/ironfish#3053]
### What happened?

When I created asset by this method:

ironfish wallet:mint --name=$(ironfish config:get blockGraffiti)

Asset is created with  quotes. And I did not have any points.

But then I created asset by the direct name without quotes and your bot gave me points immediatelly
I prepared a list of balance and list of transactions:

![Screenshot_2023-01-21-004](https://user-images.githubusercontent.com/28047645/213858721-d733c34c-48dc-451f-999c-3f91489d049c.png)

![Screenshot_2023-01-21-005](https://user-images.githubusercontent.com/28047645/213858729-e073f3c6-70e0-4ca4-a1a2-0857db6c4aee.png)

Also I think this bug is related to this one:

https://github.com/iron-fish/ironfish/issues/3052

### Graffiti

zp-node-777

**Comment by hughy** [comment]
We've updated our documentation so that it does not mention using `$(ironfish config:get blockGraffiti)` to set the asset name.
