### ISSUE TITLE
"Error parsing messages" affect ability to receive transactions & telemetry connections

### ISSUE THREAD

**Issue by serverum** [iron-fish/ironfish#3056]
### What happened?

hello mates, node is synced, all seems well, but  getting the same Error parsing messages on logs, and succesfuly sent transactions doesn't appear on my wallet(node) to be spendable after 15+ hours (! it's the first reason why Im reporting it), (the second) I've noticed some gaps in node's uptime on leaderboard, my node is running since 19 jan, but there weren't  any gaps during the interval, about 20 hours it says! I guess it might be reason of Error parsing messages & websockets connections, because of the time gaps I guess(telemetry can't send correct data to leaderboard).... I can't send\receive transactions as well, any idea\solutions?
![ironfish_failed](https://user-images.githubusercontent.com/88902671/213866760-0a7375ef-23cf-4cfe-8f32-5aeb4a3b4687.png)
![ironfish_failed2](https://user-images.githubusercontent.com/88902671/213866778-ee71502a-9b59-4a1f-a9ed-67b9109472dc.png)

### Version

0.1.62

### Debug output

```shell
Iron Fish version               0.1.62 @ 4ab43f3
Iron Fish library               0.0.39 @ 4ab43f3
Operating system                Linux x64
CPU model(s)                    AMD EPYC 7282 16-Core Processor
CPU threads                     4
RAM total                       7.77 GiB
Heap total                      1.99 GiB
Node version                    v18.13.0
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       FNORD_NODE
Block graffiti                  FNORD_NODE
```

### Relevant log output

```shell
Jan 21 11:13:36 server.net ironfish[3191]: Error parsing message
Jan 21 11:14:16 server.net ironfish[3191]: Error parsing message
Jan 21 11:15:54 server.net ironfish[3191]: Error parsing message
Jan 21 11:16:59 server.net ironfish[3191]: Error parsing message
Jan 21 11:19:26 server.net ironfish[3191]: Error parsing message
Jan 21 11:19:39 server.net ironfish[3191]: Error parsing message
Jan 21 11:19:57 server.net ironfish[3191]: Error parsing message
Jan 21 11:22:17 server.net ironfish[3191]: Error parsing message
Jan 21 11:22:34 oserver.net ironfish[3191]: Added block seq: 6260, hash: 00000...64975, txs: 7, progress: 100.00%, time: 91.8ms
Jan 21 11:29:07 server.net ironfish[3191]: Error parsing message
Jan 21 11:40:23 vserver.net ironfish[3191]: Error parsing message
```

### Graffiti

FNORD_NODE

**Comment by hughy** [comment]
I don't think that the parsing errors are to blame, but I'd like to know more about this: `succesfuly sent transactions doesn't appear on my wallet(node) to be spendable after 15+ hours `

Could you share the output of `ironfish wallet:transactions` and `ironfish wallet:status`?

**Comment by hughy** [comment]
Closing as stale
