### ISSUE TITLE
Installation error!

### ISSUE THREAD

**Issue by Mayovka** [iron-fish/ironfish#3058]
### What happened?

![photo_2023-01-21_18-37-51](https://user-images.githubusercontent.com/95088734/213877228-d8abcdaa-0179-4b23-b816-88bf2bf60753.jpg)
I install the miner, but there is an error in the end of the logs, I checked the version of the node " node -v " 
![photo_2023-01-21_18-42-48](https://user-images.githubusercontent.com/95088734/213877360-e540ee52-3791-4f57-b7c8-0ff175ae31a2.jpg)
The problem was solved by reinstalling.

### Version

v0.1.62

### Debug output

```shell
node -v
```

### Graffiti

mayovka

**Comment by wd021** [comment]
try node v18

**Comment by holahula** [comment]
Closing due to staleness. If the issue persists in versions `1.0.0+` - please file a new issue
