### ISSUE TITLE
Wrong balance while a transaction is pending

### ISSUE THREAD

**Issue by tatsoplo** [iron-fish/ironfish#3060]
### What happened?

When a transaction is ongoing, for instance in state "unconfirmed", the displayed wallet balance is 0.

### Version

0.1.62

### Debug output

```shell
$ ironfish debug
Iron Fish version                  0.1.62 @ 4ab43f3
Iron Fish library                  0.0.39 @ 4ab43f3
Operating system                   Windows_NT x64
CPU model(s)                       Intel(R) Core(TM) i5-4310U CPU @ 2.00GHz
CPU threads                        4
RAM total                          7.90 GiB
Heap total                         2.00 GiB
Node version                       v18.12.0
ironfish in PATH                   true
Garbage Collector Exposed          false
Telemetry enabled                  true
Node name                          hkzork2972
Block graffiti                     hkzork2972
Account 3df8f2 uuid                3df8f215-05cc-4b6c-b8f7-eeb7ca99f4ec
Account 3df8f2 name                hkzork2972
Account 3df8f2 head hash           000000000026482be2f7f3453de508f452bd0301b705ffdef3c90f6b50a515b6
Account 3df8f2 head in chain       true
Account 3df8f2 sequence            6885
```

### Relevant log output

```shell
1) Wallet balance is "1000000" before to burn assets:
$ ironfish wallet:balances
Account: hkzork2972
 Asset Name Asset Id                                                         Confirmed Balance
 ────────── ──────────────────────────────────────────────────────────────── ─────────────────
 hkzork2972 5c5a31d3c0a7c0b755417c87290b68a3501414485a0bdb6c521f6b9545d8da33 1000000.00000000
 $IRON      d7c86706f5817aa718cd1cfad03233bcd64a7789fd9422d3b17af6823a7e6ac6 0.00000009

2) Burs assets transaction is ongoing:
$ ironfish wallet:transactions
 Timestamp                 Status      Type    Hash      Amount ($IRON)      Fee ($IRON)         Notes Spends Mints Burns Expiration
 ───────────────────────── ─────────── ─────── ───────── ─────────────────── ─────────────────── ───── ────── ───── ───── ──────────
 21/01/2023 21:44:11 UTC+1 unconfirmed send    d5b9f180… -0.00000001         0.00000001          3     2      0     0     6890
 21/01/2023 18:24:27 UTC+1 confirmed   send    f4cfa5a2… -0.00000001         0.00000001          2     1      1     0     6663
 21/01/2023 18:19:47 UTC+1 confirmed   receive bc2f899b… 0.00000005          0.00000001          2     1      0     0     6170
 21/01/2023 18:19:47 UTC+1 confirmed   receive ffed59f7… 0.00000005          0.00000005          6     1      0     0     6170

3) Wallet balance displayed is "0" while transaction is "unconfirmed":
$ ironfish wallet:balances
Account: hkzork2972
 Asset Name Asset Id                                                         Confirmed Balance
 ────────── ──────────────────────────────────────────────────────────────── ─────────────────
 hkzork2972 5c5a31d3c0a7c0b755417c87290b68a3501414485a0bdb6c521f6b9545d8da33 0.00000000
 $IRON      d7c86706f5817aa718cd1cfad03233bcd64a7789fd9422d3b17af6823a7e6ac6 0.00000005
```

### Graffiti

hkzork2972

**Comment by NodeOperator881** [comment]
damn you fast i was able to recreate the same bug

**Comment by tatsoplo** [comment]
love to ear that :D ...  I'm very interested by this project. Then, I'm checking lot of commands and transactions to help improve the application ;)

Sent from Yahoo Mail on Android 
 
  On Sun, Jan 22, 2023 at 1:53, ***@***.***> wrote:   


damn you fast i was able to recreate the same bug

**Comment by tatsoplo** [comment]
FYI, the issue is more general : it seems not possible to make a new transaction while another one is ongoing, no matter it is a "send" or "burn" transaction...

**Comment by tatsoplo** [comment]
1) transactions status
 Timestamp                Status      Type    Hash       Amount ($IRON)      Fee ($IRON)         Notes Spends Mints Burns Expiration
 ──────────────────────── ─────────── ─────── ────────── ─────────────────── ─────────────────── ───── ────── ───── ───── ──────────
 22/01/2023 7:34:52 UTC+1 pending     send    c0a4608bd… -0.00000001         0.00000001          3     2      0     0     7506
 22/01/2023 7:26:40 UTC+1 confirmed   send    dcf9a2d8e… -0.00000001         0.00000001          3     2      0     0     7501
 22/01/2023 7:19:00 UTC+1 confirmed   send    1390cfbc3… -0.00000001         0.00000001          2     1      1     0     7494
 21/01/2023 23:18:53 UTC+1 confirmed   receive 0645a605… 0.00000005          0.00000001          2     1      0     0     6746
 21/01/2023 23:18:53 UTC+1 confirmed   receive 128780ee… 0.00000005          0.00000001          2     1      0     0     6746

2) new transaction failed until the previous one is confirmed
? Select the asset you wish to burn 3ef087a020700b60e474c46feeabdd923cecfcf021204d3dcd0c3ae2282e1dcc (idjska2027)
Enter the fee amount in $IRON (min: 0.00000001) [0.00000001]:

You are about to burn:
3ef087a020700b60e474c46feeabdd923cecfcf021204d3dcd0c3ae2282e1dcc 1000.00000000 plus a transaction fee of $IRON 0.00000001 with the acc
ount idjska2027

* This action is NOT reversible *

Do you confirm (Y/N)?: Y
Creating the transaction: [████████████████████████████████████████] 100% | ETA: 0s
An error occurred while burning the asset.
 »   Error: Request failed (400) error: Insufficient funds: Needed 3ef087a020700b60e474c46feeabdd923cecfcf021204d3dcd0c3ae2282e1dcc
 »   1000.00000000 but have 0.00000000 available to spend. Please fund your account and/or wait for any pending transactions to be
 »   confirmed.'

**Comment by smokim87** [comment]
I get the exact same issue, once the txn confirms balances show up normally again.

**Comment by NodeOperator881** [comment]
if you have the TX queued up while the other is pending you will still have an issue even after the original TX confirms. you have to completely reset the send or burn tx for it to register the correct balance.

**Comment by NodeOperator881** [comment]
tatsoplo how do you get the detailed debug info or you write it yourself?

**Comment by tatsoplo** [comment]
I got the detailled debug info by adding the option "--verbose" to the command:
ironfish wallet:send --verbose ...
