### ISSUE TITLE
Getting insufficient balance, even though i have enough balance.

### ISSUE THREAD

**Issue by ziggy010** [iron-fish/ironfish#3062]
### What happened?

while sending the assets to the official address, i encountered a bug that says insufficient balance, even though i had enough balance.

### Debug output

```shell
Error: Request failed (400) insufficient-balance: Not enough unspent notes available to fund the transaction.
```

### Graffiti

Ziggy

**Comment by ygao76** [comment]
Can you run wallet:balance to show your balance and screenshot the balance you have. This will help us debug your issue.

**Comment by hughy** [comment]
Closing as stale
