### ISSUE TITLE
[balances]

### ISSUE THREAD

**Issue by dashnode13** [iron-fish/ironfish#3064]
### What happened?

A bug happened!

Hello
When checking balances - it is showing it incorrectly
I check balances some times without aking any changes in balaces - and it is showing different balances, see screen shot 
it is showing incorrect balance for a new item i minted 
<img width="714" alt="image" src="https://user-images.githubusercontent.com/123141706/213914661-8b127cc7-53a4-4d70-8381-bcfbcc1e8783.png">

### Version

v0.1.62

### Debug output

```shell
Iron Fish version               0.1.62 @ 4ab43f3
Iron Fish library               0.0.39 @ 4ab43f3
Operating system                Linux x64
CPU model(s)                    Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz
CPU threads                     2
RAM total                       4.00 GiB
Heap total                      1.99 GiB
Node version                    v18.13.0
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       dashnode13
Block graffiti                  dashnode13
```

### Graffiti

dashnode13

**Comment by hughy** [comment]
Resolved by #3059 released in v0.1.63
