### ISSUE TITLE
Faucet command always return error "You entered an invalid email."

### ISSUE THREAD

**Issue by cynic-1** [iron-fish/ironfish#3065]
### What happened?

A bug happened!

![image](https://user-images.githubusercontent.com/68074066/213918438-516617e6-695d-4929-845c-f4a6fb7578d1.png)

eudaimonia.bit@mail3.me is the same email address which I signed up on ironfish testnet https://testnet.ironfish.network.

I also try out my other email address like cynic2001@gmail.com, it still return error "You entered an invalid email."

### Version

v0.1.59

### Debug output

C:\Users\song>ironfish faucet

::::::::::          :::::::::::::::::
::::::::::::       :::::::::::::::::::
:::::::::::::     :::::::::::::::::::::
::::::::::::::   ::::::::::::::::::::::::
 ::::::::::::: ::::::::::        :::::::::
   :::::::::::::::::::::          ::::::::::
   :::::::::::::::::::::          :::::::::
 ::::::::::::: ::::::::::        :::::::::
::::::::::::::   ::::::::::::::::::::::::
:::::::::::::     :::::::::::::::::::::
::::::::::::       :::::::::::::::::::
::::::::::           ::::::::::::::::

Enter your email to stay updated with Iron Fish: cynic2001@gmail.com
Collecting your funds... You entered an invalid email.

C:\Users\song>ironfish faucet

::::::::::          :::::::::::::::::
::::::::::::       :::::::::::::::::::
:::::::::::::     :::::::::::::::::::::
::::::::::::::   ::::::::::::::::::::::::
 ::::::::::::: ::::::::::        :::::::::
   :::::::::::::::::::::          ::::::::::
   :::::::::::::::::::::          :::::::::
 ::::::::::::: ::::::::::        :::::::::
::::::::::::::   ::::::::::::::::::::::::
:::::::::::::     :::::::::::::::::::::
::::::::::::       :::::::::::::::::::
::::::::::           ::::::::::::::::

Enter your email to stay updated with Iron Fish: eudaimonia.bit@mail3.me
Collecting your funds... You entered an invalid email.

### Graffiti

cynic

**Comment by cynic-1** [comment]
I believe this is happening after I ran `ironfish faucet` with email address `eudaimonia.bit@mail3.me` and got `The Iron Fish Faucet just added your request to the queue!` success outcome last night.

Unfortunately, my wallet balance doesn't change tonight so I run the `ironfish faucet` command again and get the outcome as described above.

Actually, I just create a new account, set it as default, run `ironfish faucet` for test and get success outcome. Let's wait and see if it works this time.

**Comment by cynic-1** [comment]
After one hour, my wallet balance still doesn't change. So I run `ironfish faucet` again and get the same problem described above. 

C:\Users\song>ironfish faucet

::::::::::          :::::::::::::::::
::::::::::::       :::::::::::::::::::
:::::::::::::     :::::::::::::::::::::
::::::::::::::   ::::::::::::::::::::::::
 ::::::::::::: ::::::::::        :::::::::
   :::::::::::::::::::::          ::::::::::
   :::::::::::::::::::::          :::::::::
 ::::::::::::: ::::::::::        :::::::::
::::::::::::::   ::::::::::::::::::::::::
:::::::::::::     :::::::::::::::::::::
::::::::::::       :::::::::::::::::::
::::::::::           ::::::::::::::::

Enter your email to stay updated with Iron Fish: eudaimonia.bit@mail3.me
Collecting your funds... Success



::::::::::          :::::::::::::::::             ::::::::::          :::::::::::::::::
::::::::::::       :::::::::::::::::::            ::::::::::::       :::::::::::::::::::
:::::::::::::     :::::::::::::::::::::           :::::::::::::     :::::::::::::::::::::
::::::::::::::   ::::::::::::::::::::::::         ::::::::::::::   ::::::::::::::::::::::::
 ::::::::::::: ::::::::::        :::::::::         ::::::::::::: ::::::::::        :::::::::
   :::::::::::::::::::::          ::::::::::         :::::::::::::::::::::          ::::::::::
   :::::::::::::::::::::          :::::::::          :::::::::::::::::::::          :::::::::
 ::::::::::::: ::::::::::        :::::::::         ::::::::::::: ::::::::::        :::::::::
::::::::::::::   ::::::::::::::::::::::::         ::::::::::::::   ::::::::::::::::::::::::
:::::::::::::     :::::::::::::::::::::           :::::::::::::     :::::::::::::::::::::
::::::::::::       :::::::::::::::::::            ::::::::::::       :::::::::::::::::::
::::::::::           ::::::::::::::::             ::::::::::           ::::::::::::::::

Congratulations! The Iron Fish Faucet just added your request to the queue!

It will be processed within the next hour and $IRON will be sent directly to your account.

Check your balance by running:
  - ironfish accounts:balance

Learn how to send a transaction by running:
  - ironfish accounts:pay --help

C:\Users\song>ironfish wallet:balances
Account: curve
 Asset Name Asset Id Confirmed Balance
 ────────── ──────── ─────────────────

C:\Users\song>ironfish wallet:balance
Account: curve
Balance: $IRON 0.00000000

C:\Users\song>ironfish faucet

::::::::::          :::::::::::::::::
::::::::::::       :::::::::::::::::::
:::::::::::::     :::::::::::::::::::::
::::::::::::::   ::::::::::::::::::::::::
 ::::::::::::: ::::::::::        :::::::::
   :::::::::::::::::::::          ::::::::::
   :::::::::::::::::::::          :::::::::
 ::::::::::::: ::::::::::        :::::::::
::::::::::::::   ::::::::::::::::::::::::
:::::::::::::     :::::::::::::::::::::
::::::::::::       :::::::::::::::::::
::::::::::           ::::::::::::::::

Enter your email to stay updated with Iron Fish: eudaimonia.bit@mail3.me
Collecting your funds... You entered an invalid email.

**Comment by ygao76** [comment]
Does this still happen to you? The wallet:faucet command should work as expected. Let us know if this is still an issue for you.

**Comment by cynic-1** [comment]
> Does this still happen to you? The wallet:faucet command should work as expected. Let us know if this is still an issue for you.

I'm not sure whether it's because of not starting a node. After I spined up a node, the wallet:faucet command worked as expected. However, if that's the reason, I suggest you should mention it in the docs. 
Thanks for your reply.
