### ISSUE TITLE
Balances issues

### ISSUE THREAD

**Issue by Aptosuper** [iron-fish/ironfish#3067]
### What happened?

At "balance 1" picture, you can see the differents amounts of tokens (0,00000102 $IRON)

At "balance 2" picture, you can see that the amounts change from the first picture "balance1"(few minutes later). I was trying to type the command "ironfish wallet : send" but my transaction failed, saying my balance is too low --> you can see 0.00000000 $IRON.

So where are my $IRON ?

At "balance 3" picture, you can see directly on the same screenshot the difference between the the command "balances" at 2minutes intervals.

The tokens are back 👍 but the issue is here and create some ERROR transcations.

Thanks for reading mates

Love and Fish and Ironfish

![balances 1](https://user-images.githubusercontent.com/111451773/213927142-35f7c159-7b7f-4871-b71b-17b7de5d3cf4.jpg)
![balances 2](https://user-images.githubusercontent.com/111451773/213927143-87a0cc2b-9100-4266-8530-1543a470e930.jpg)
![balances 3](https://user-images.githubusercontent.com/111451773/213927144-49b7ce45-19a8-452a-9758-1ee2bfcb6188.jpg)

### Graffiti

SuperIron

**Comment by hughy** [comment]
This issue should be resolved by #3059 in an upcoming release
