### ISSUE TITLE
Geting Point task 2 time in one week

### ISSUE THREAD

**Issue by pemulungtoken** [iron-fish/ironfish#3069]
### What happened?

user can get multiple point task in one week with do task MULTI_ASSET_BURN FIRST first and then MULTI_ASSET_MINT and last do MULTI_ASSET_TRANSFER

i see the rules is only can do one time each task/weekly?
![image](https://user-images.githubusercontent.com/108206972/213934336-b536765d-3f22-445d-b07b-ba609a73df94.png)

### Graffiti

alvinnasa

**Comment by wd021** [comment]
think the week resets on sunday, so its the start of a new week.
