### ISSUE TITLE
telemetry not working

### ISSUE THREAD

**Issue by Mayovka** [iron-fish/ironfish#3071]
### What happened?

Telemetry does not work, daily water points are not accrued, according to the logs, error 403
![photo_2023-01-22_22-31-59](https://user-images.githubusercontent.com/95088734/213939013-67632885-f6bd-488e-87bf-259e4f54ce71.jpg)
Most likely this is a problem with the server, since the error points to the server, to fix it, you need to reduce the number of threads, if it does not help, reinstall the database

### Version

v0.1.62

### Graffiti

mayovka

**Comment by holahula** [comment]
Closing - related to testnet phase
