### ISSUE TITLE
ironfish wallet:send amount

### ISSUE THREAD

**Issue by jhuffman00** [iron-fish/ironfish#3072]
### What happened?

- Entered command ironfish wallet:send
- Selected my new asset I created
- Accidentally copy and pasted the send to address of dfc2679369551e64e3950e06a88e68466e813c63b100283520045925adbe59ca into the amount prompt instead of a valid value and the below error was returned

Error: invalid decimal value (argument="value", value="dfc2679369551e64e3950e06a88e68466e813c63b100283520045925adbe59ca", code=INVALID_ARGUMENT, version=bignumber/5.7.0)
    at Logger.makeError (/usr/lib/node_modules/ironfish/node_modules/@ethersproject/logger/lib/index.js:238:21)
    at Logger.throwError (/usr/lib/node_modules/ironfish/node_modules/@ethersproject/logger/lib/index.js:247:20)
    at Logger.throwArgumentError (/usr/lib/node_modules/ironfish/node_modules/@ethersproject/logger/lib/index.js:250:21)
    at Object.parseFixed (/usr/lib/node_modules/ironfish/node_modules/@ethersproject/bignumber/lib/fixednumber.js:73:16)
    at CurrencyUtils.decodeIron (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/utils/currency.js:21:28)
    at Send.start (/usr/lib/node_modules/ironfish/build/src/commands/wallet/send.js:47:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Send.run (/usr/lib/node_modules/ironfish/build/src/command.js:24:13)
    at async Send._run (/usr/lib/node_modules/ironfish/node_modules/@oclif/core/lib/command.js:80:22)
    at async Config.runCommand (/usr/lib/node_modules/ironfish/node_modules/@oclif/core/lib/config/config.js:272:25)

### Version

 0.1.62 @ 4ab43f3

### Debug output

```shell
Iron Fish version                  0.1.62 @ 4ab43f3
Iron Fish library                  0.0.39 @ 4ab43f3
Operating system                   Linux x64
CPU model(s)                       Intel(R) Xeon(R) E-2246G CPU @ 3.60GHz
CPU threads                        12
RAM total                          31.59 GiB
Heap total                         3.99 GiB
Node version                       v18.13.0
ironfish in PATH                   true
Garbage Collector Exposed          false
Telemetry enabled                  true
Node name                          ChiaKing
Block graffiti                     ChiaKing
Account 0cf7ce uuid                0cf7ceb7-8b57-4855-8092-ad1783c15c61
Account 0cf7ce name                default
Account 0cf7ce head hash           00000000001578d2db273937200bc618c0dc2830a895890bd91a95ec070baa6e
Account 0cf7ce head in chain       true
Account 0cf7ce sequence            8353
```

### Graffiti

https://testnet.ironfish.network/users/272977

**Comment by ygao76** [comment]
We only allow numeric value for amount. When you accidentally enter the address string instead of a value, its expected to see the error. But the transaction did not go through. Overall this is the expected behavior.

**Comment by jhuffman00** [comment]
I don't think you want the program to error out like that. You should check the input and respond back that the address was invalid instead of the program just blowing up with an error code etc. That does not look professional. You should fix that. Just my opinion.

**Comment by ygao76** [comment]
That's reasonable, I will make a change to display a user friendly error message.

**Comment by ygao76** [comment]
@jhuffman00 I can not reproduce the error message you see. I am just getting `Error: Invalid amount The number inputted for amount is invalid.` There must be improvement made to the error message and parser. Please try again with latest IronFish version, and if you still see the long error message please reopen the issue.

```
 ironfish-cli % yarn start wallet:send
yarn run v1.22.19
$ yarn build && yarn start:js wallet:send
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node --expose-gc --inspect=:0 --inspect-publish-uid=http --enable-source-maps bin/run wallet:send
? Select the asset you wish to send d7c86706f5817aa718cd1cfad03233bcd64a7789fd9422d3b17af6823a7e6ac6
($IRON)
Enter the amount (balance: 0.00000007): dfc2679369551e64e3950e06a88e68466e813c63b100283520045925adbe59ca
 ›   Error: Invalid amount The number inputted for amount is invalid.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
