### ISSUE TITLE
chain:download doesn't work as expected.

### ISSUE THREAD

**Issue by cynic-1** [iron-fish/ironfish#3073]
### What happened?

A bug happened!

Every time I ran the `ironfish chain:download` command, after the download is done, it returned `Error: EBUSY: resource busy or locked, unlink 'C:\Users\song\.ironfish\databases\chain\000010.ldb'`. However, the `.ironfish` directory is created by the program and there is no other program could possibly use any file in that directory.

I expected there's no error.

### Version

v0.1.59

### Debug output

```shell
C:\Users\song>ironfish chain:download
Download 241.51 MB snapshot to update from block 1 to 8536?
At least 483.03 MB of free disk space is required to download and unzip the snapshot file.
Are you sure? (Y)es / (N)o: Y
Downloading snapshot from https://ironfish-snapshots.s3-accelerate.amazonaws.com/ironfish_snapshot_1674432134367.tar.gz to C:\Users\song\.ironfish\temp\ironfish_snapshot_1674432134367.tar.gz
Downloading snapshot: [████████████████████████████████████████] 100% | 241.51 MB / 241.51 MB | 7.81 MB/s | ETA: soon
Unzipping snapshot: [████████████████████████████████████████] 100% | 126 / 126 entries | 31.11/s | ETA: soon
Error: EBUSY: resource busy or locked, unlink 'C:\Users\song\.ironfish\databases\chain\000010.ldb'
Removing existing chain data at C:\Users\song\.ironfish\databases\chain before importing snapshot... !
```

### Graffiti

cynic

**Comment by ygao76** [comment]
Can you follow this guide to check what process is accessing that folder


> If all the above solutions did not work AND you are using windows PC like in my case, the easiest thing to do is:
> 
> Press windows key plus R on your keyboard to open the run command box and type this
> 
> resmon.exe
> 
> click OK to open resource monitor
> 
> In the monitor, navigate to CPU tab
> 
> Under Associated Handles in the search box, copy the path to the file or folder in question and paste it in there
> 
> Click on the search icon
> 
> You should be able to see all the programs using the file or folder
> 
> right-click each and end-process
> 


https://stackoverflow.com/a/61720199
