### ISSUE TITLE
Mint asset still runs even I choose N (NO)

### ISSUE THREAD

**Issue by testtk1** [iron-fish/ironfish#3076]
### What happened?

When I mint an asseet, the system asked me to choose Y or N. Even if I choose N, the node still continue run as the same choosing Yes
![bug 1](https://user-images.githubusercontent.com/115237020/213988131-e60838a4-b8d4-4e8e-b764-3070c2a03187.PNG)

### Graffiti

khuongchugranlund

**Comment by ygao76** [comment]
Hi @testtk1 the flow you triggered is the right one for Not mint a new asset. 
When you enter No, it will ask you to select the asset to mint.
If you enter Yes, it will ask you to enter the name for the new asset. 

Enter No or n does not kill the command . This is the expected behavior.
