### ISSUE TITLE
MULTI_ASSET_TRANSFER

### ISSUE THREAD

**Issue by cryptohilbert** [iron-fish/ironfish#3077]
### What happened?

A bug happened!
I minted and burned successfully, but after sent I didn't receive points. I tried yesterday and today, but nothing happens, I see only success transactions.
[http://joxi.ru/DmBkbJ7IPzyz52](url)

### Version

0.1.62

### Debug output

^A^Aion              0.1.62 @ 4ab43f3
Node                 STARTED
Node Name            webmakler
Block Graffiti       webmakler
Memory               Heap: 268.27 MiB -> 340.76 MiB / 4.00 GiB (6.5%), RSS: 1.10 GiB (1.9%), Free: 51.36 GiB (12.8%)
CPU                  Cores: 10, Current: 45.7%
P2P Network          CONNECTED - In: 156 B/s, Out: 1.11 KB/s, peers 50
Mining               STARTED - 0 miners, 4 mined
Mem Pool             Count: 45 tx, Bytes: 81.60 KiB
Syncer               IDLE - 2.31 blocks added/sec
Blockchain           000000000034cea5c5715d1477dfcccaf4fdfb5c5eec2abe2f74506b0489552c (9221), Since HEAD: 1m 39s (SYNCED)
Accounts             000000000034cea5c5715d1477dfcccaf4fdfb5c5eec2abe2f74506b0489552c (9221)
Telemetry            STARTED - 47978 <- 2 pending
Workers              STARTED - 0 -> 0 / 6 - 0 jobs Δ, 0.54 jobs/s

### Graffiti

webmakler

**Comment by hughy** [comment]
Please ensure that the name of the custom asset that you mint, burn, and send is exactly the same as your testnet graffiti

**Comment by hughy** [comment]
Closing as stale
