### ISSUE TITLE
Transactions are pending for several days and still pending.

### ISSUE THREAD

**Issue by dminer3080** [iron-fish/ironfish#3078]
### What happened?

Attempted to mint and send an asset on 1/21/23 and the transactions are still pending.

### Version

0.1.62

### Debug output

```shell
dbaker2690@PC:~$ ironfish debug
Iron Fish version                  0.1.62 @ 4ab43f3
Iron Fish library                  0.0.39 @ 4ab43f3
Operating system                   Linux x64
CPU model(s)                       12th Gen Intel(R) Core(TM) i9-12900K
CPU threads                        24
RAM total                          15.51 GiB
Heap total                         3.99 GiB
Node version                       v18.13.0
ironfish in PATH                   true
Garbage Collector Exposed          false
Telemetry enabled                  true
Node name                          Dminer3080
Block graffiti                     Dminer3080
Account 55cdb6 uuid                55cdb623-5b53-42c1-bba5-ef33bc0e283c
Account 55cdb6 name                default
Account 55cdb6 head hash           00000000000267ad67d70917b3e97af25146848e91b054f92946e1507715eae5
Account 55cdb6 head in chain       true
Account 55cdb6 sequence            6332
```

### Relevant log output

_dbaker2690@PC:~$ ironfish wallet:transactions
 Timestamp          Status      Type    Hash Amount ($IRON)      Fee ($IRON)         Notes Spends Mints Burns Expiration
 ────────────────── ─────────── ─────── ──── ─────────────────── ─────────────────── ───── ────── ───── ───── ──────────
 1/22/2023 10:12:4… pending     receive 45f… 0.00000005          0.00000006          7     1      0     0     7999
 1/21/2023 4:44:04… pending     send    dd2… -0.00000001         0.00000001          2     2      0     1     6347
 1/21/2023 4:43:35… pending     send    fbb… -0.00000001         0.00000001          2     1      1     0     6347
 1/20/2023 7:16:24… confirmed   send    6c2… -0.00000001         0.00000001          3     2      0     0     5519
 1/20/2023 6:48:08… confirmed   send    d86… -0.00000001         0.00000001          2     2      0     1     5493
 1/20/2023 6:43:58… confirmed   send    55f… -0.00000001         0.00000001          2     1      1     0     5484
 1/20/2023 6:12:45… confirmed   receive 773… 0.00000100          0.00000001          2     1      0     0     5446
 1/20/2023 6:12:45… confirmed   receive 07c… 0.00000005          0.00000001          2     1      0     0     5443_

### Graffiti

https://testnet.ironfish.network/users/18111

**Comment by hughy** [comment]
Can you share the output of the `wallet:status` command please?

I can think of two possibilities for why the transactions still show as pending:
1. Your account has not yet scanned the block that contains these transactions
2. Something went wrong when updating your account with these transactions

The `status` output will show whether your accounts have scanned all blocks on the chain.

**Comment by dminer3080** [comment]
![Screenshot 2023-01-23 113311status](https://user-images.githubusercontent.com/98119943/214095436-3ab855f0-44be-43dd-9276-edadcbe0c534.png)

**Comment by hughy** [comment]
This is helpful, but could you also run `wallet:status`?

**Comment by dminer3080** [comment]
So sorry didnt see the wallet part lol. 
![Screenshot 2023-01-23 123823iron1](https://user-images.githubusercontent.com/98119943/214110260-35c5187f-6645-42b3-9742-f48c7147f4d5.png)

**Comment by dminer3080** [comment]
I also have an node running as well. Didnt know if that would be helpful info as well.

**Comment by hughy** [comment]
Thanks! It looks like your account is up-to-date, so something must have gone wrong with scanning the transactions.

You can try running `ironfish wallet:rescan --reset` to get the pending transactions unstuck.

A couple of users have run into this issue, so I'm investigating what causes it.

**Comment by dminer3080** [comment]
So that worked. Im sure it will take some time but I minted 2 assets and 1 of them was one of the pending transactions but it did not show up. 
![Uploading Screenshot 2023-01-23 125254Reset.png…]()

**Comment by dminer3080** [comment]
![Screenshot 2023-01-23 125254Reset](https://user-images.githubusercontent.com/98119943/214114448-6f2f0e5c-77fa-419d-9e5e-8ac9236649f6.png)

**Comment by hughy** [comment]
It's possible that that transaction expired without being added to the chain. In that case rescanning the chain would not re-surface that transaction.

Do you happen to have the transaction hash? If so you can check the block explorer to see if it was added to the chain

**Comment by hughy** [comment]
Yes, a 404 will indicate that that transaction isn't on the chain. Please do try minting again!

**Comment by dminer3080** [comment]
Just minted a new asset will keep you updated. I minted another asset before but didnt use my graffiti so I just burned all of them because it wouldnt let me before.

**Comment by dminer3080** [comment]
Minted a new asset, sent that asset, and also burned some. All transactions have been confirmed and my wallet:balances reflects the correct info.

Thank you for all the help!!

**Comment by hughy** [comment]
Excellent!

Thanks for raising the issue and helping us to make Iron Fish better!

**Comment by dminer3080** [comment]
Glad to be able to help. Wish I had dev skills to do more. Any advice on how or where to learn?

**Comment by hughy** [comment]
There are a lot of online tutorials in programming and different programming languages. A couple that I've played around with in the past are codecademy and Scrimba.

I think once you've learned the basics the best way to learn is to start building things! replit is another online platform that I'd recommend for that.

Have fun!
