### ISSUE TITLE
Error-unpacking nodejs-1nodesource1

### ISSUE THREAD

**Issue by 0x28a4** [iron-fish/ironfish#3080]
### What happened?

I am trying to install ironfish on my Ubuntu 22.04.1 LTS- Running this command 
curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - &&\
sudo apt-get install -y nodejs

Whenever I do I get the attached error. If I ignore it and run sudo npm install -g ironfish- I get npm is not found
A bug happened!
![Error-unpacking nodejs-1nodesource1](https://user-images.githubusercontent.com/95450473/214039765-463d29b2-c618-439c-bed4-11ac8972c2f2.png)

### Version

Ubuntu 22.04.1 LTS- Codename:       jammy

### Graffiti

masterchief

**Comment by holahula** [comment]
Closing - this is more related to being unable to install node rather than ironfish
