### ISSUE TITLE
multi asset mint

### ISSUE THREAD

**Issue by fathoni6** [iron-fish/ironfish#3081]
### What happened?

A bug happened! I can mint as much as 1000 assets but I can't send or burn
![bug mint multi aset](https://user-images.githubusercontent.com/48874766/214051835-5dadba49-b710-408f-a12a-f616546c77d8.png)

### Version

0.1.62

### Graffiti

guloiron32

**Comment by hughy** [comment]
From the screenshot you pasted it looks like you were able to burn successfully
