### ISSUE TITLE
illegible assets

### ISSUE THREAD

**Issue by fathoni6** [iron-fish/ironfish#3083]
### What happened?

A bug happened!unreadable asset when import spending key to new vps
![bug iron](https://user-images.githubusercontent.com/48874766/214053921-8754f59d-d398-4e1c-a7a4-1285a76aa9e5.png)

### Version

0.1.62

### Graffiti

guloiron32

**Comment by hughy** [comment]
When you import an account to another wallet the wallet will need to scan the entire chain for any transactions involving the imported account.

Until this rescanning process is complete the balances for the imported account will not be up-to-date with the head of the chain.

You can run `ironfish wallet:status` to see how far on the chain each account in a wallet has scanned.
