### ISSUE TITLE
have balance but can not mint

### ISSUE THREAD

**Issue by 0xzuru** [iron-fish/ironfish#3085]
### What happened?
have balance but can not mint

![image](https://user-images.githubusercontent.com/119164185/214061587-3d8a9e22-05ed-400d-8f5d-8d3f0a893ed2.png)

### Version

0.1.62

### Graffiti

zuruyu

**Comment by hughy** [comment]
@0xzuru this error will often occur if you have pending transactions that are using your available notes.

Iron Fish is a UTXO currency, similar to bitcoin. Your balance is made of unique 'notes' with different values like physical cash. When you create a transaction you spend one or more of these notes. If the amount that you're spending is less than the value of the note then you get new notes back as 'change'. You can then use the new notes in transactions, but you need to wait until the first transaction has processed.

**Comment by hughy** [comment]
#3515 adds calculation of 'available' balance: the amount that you can send in a transaction at the given time.
