### ISSUE TITLE
send ironfish

### ISSUE THREAD

**Issue by fathoni6** [iron-fish/ironfish#3086]
### What happened?

A bug happened! I tried to send ironfish to someone else's wallet worth 0.0001 ironfish, before I had 0.009 $ IRON, now it's 0.00000002, but I checked a few times, my balance returned to 0.009 
![bug44](https://user-images.githubusercontent.com/48874766/214066982-dc359a11-56dd-412b-8b61-de897e7ff7ea.png)

![bug4](https://user-images.githubusercontent.com/48874766/214066441-2f4d5bae-74f7-4478-b71c-7395ba72189b.png)

### Graffiti

guloiron32

**Comment by hughy** [comment]
#3059 will resolve the temporarily incorrect `confirmed` balance value
