### ISSUE TITLE
Ironfish server connectivity issues

### ISSUE THREAD

**Issue by coldsjf** [iron-fish/ironfish#3088]
### What happened?

I've seen many testers run into this issue in the Discord, and I believe it's ironfish connectivity issue.

I'm running the node on a dedicated server hosted in EU, and the server can not resolve the testnet.ironfish.network domain

the error code is 
`Error submitting telemetry to API: connect ETIMEDOUT`

### Relevant log output

```shell
Error submitting telemetry to API: connect ETIMEDOUT
```

### Graffiti

hotsjf

**Comment by holahula** [comment]
Closing - transient DNS issue
