### ISSUE TITLE
'pending' transactions after minting

### ISSUE THREAD

**Issue by MaximusBaton** [iron-fish/ironfish#3089]
### What happened?

`ironfish wallet:mint --name=GRAFFITI_NAME`

and then transactions stuck

![image](https://user-images.githubusercontent.com/10597367/214120163-c1a6b9fc-c5c9-4ecc-b370-d3371dc2c0d3.png)

`ironfish wallet:repair` does not help

### Version

0.1.62 @ 4ab43f3

### Debug output

```shell
root@f00dda906e31:/usr/src/app# ironfish debug
Iron Fish version                  0.1.62 @ 4ab43f3
Iron Fish library                  0.0.39 @ 4ab43f3
Operating system                   Linux x64
CPU model(s)                       Intel(R) Core(TM) i3-2370M CPU @ 2.40GHz
CPU threads                        2
RAM total                          1.94 GiB
Heap total                         976.32 MiB
Node version                       v18.12.1
ironfish in PATH                   true
Garbage Collector Exposed          false
Telemetry enabled                  true
Node name
Block graffiti
Account f8337c uuid                f8337c9f-fc09-4954-a75e-81a1905d1916
Account f8337c name                default
Account f8337c head hash           000000000033763576d9871ead18fc554998af430a8a8bbe27b5b7b48bc0c110
Account f8337c head in chain       true
Account f8337c sequence            7735
root@f00dda906e31:/usr/src/app#
```

### Graffiti

maximusbaton

**Comment by hughy** [comment]
From the screenshot you posted it looks like your accounts have only scanned up to block 7292 while your chain is up to block 9611.

You can wait for your accounts to catch up, or run `ironfish wallet:rescan` to force your wallet to rescan the chain.

**Comment by MaximusBaton** [comment]
I see...
those transactions have been marked as 'expired' in ~2h after I posted this issue, and right after that everything started to work as usual. meanwhile, it's not the first time when I face with the similar issue.
I will try the command you proposed next time.
Best regards!
