### ISSUE TITLE
Did not earn points for tasks

### ISSUE THREAD

**Issue by AgataGolik** [iron-fish/ironfish#3099]
### What happened?

Dear Sirs,

yesterday (23.01.2023) I completed all three tasks:

- Multi-Asset Mint (GOLDENBEE - 5 tokens)
- Multi-Asset Burn (GOLDENBEE - 2 tokens) 
- Multi-Asset Send (dfc2679369551e64e3950e06a88e68466e813c63b100283520045925adbe59ca)

To date, I have not accrued points for this . 

From the faucet I received tokens for gas 0.00000005,  at the moment the balance is 0.00000002  which means that the gas has been paid  . I paid 0.00000001 for one transaction. 

Hosted Node : regarding the hosted node here the points are counted but only here  .

Today (24.01.2023) I did the tasks again, faucet and :

Multi-Asset Mint - XYZGOLD 10 tokens
https://explorer.ironfish.network/transaction/40dcdb9513ad5ab48fa52ecbc2dd4567a76dbe179aaa2bf768a187e32d4424bc

Multi-Asset Burn - XYZGOLD 5 tokens
https://explorer.ironfish.network/transaction/3117a67d85336175c75a2e29129b4fd903644754d82c4db41dcd469d80ddda19

Multi-Asset Send - XYZGOLD 1 token
https://explorer.ironfish.network/transaction/521792a6998de6bdbe01ac89d710d151a685bea159f162580a593cc75d6108d5

But I still do not see that the task has been credited o points have been accrued.

My public key: 9678a52e7609284f116dc9f5e344866780cca3a5d116de8c0596be52c1aa2a14
Graffiti : Agata
https://testnet.ironfish.network/users/276048

Regards
Agata Golik

P.S.
Regarding OUTPUTS are from today's transaction

### Version

v18.13.0

### Debug output

```shell
2a0d6bbd3a3bc3f857a4fa6f0595cbdd88dca95f12fca8b1f367463d9e1b8672
2a476e53d513960c93d248c117de3af7f2e24c9facc755a695a6fe22828cb42f
5edb6a83fd763ef243ea034cb17f30d6d21c0c1a64add9ff7f42d02251c7dc55
```

### Relevant log output

```shell
6f5c6263f65ea572a30bfe2dfcb5d2504f1d1b9d08c101d93e52fa9bb128301d
34ed7b84b5ff885f574f0c487da3e96bc5528a80300b9ff1d48de1c087827628
0c3ebe38367ed6fb9e519a3358faeca29c19db084e548d28d33dc0ddb305c405
1ed5a98a8dc996f4ae7ac0adf26cbf0184267d4fd6e86702b7f52ea9b6846860
```

### Graffiti

Agata

**Comment by Qloun** [comment]
You didn't read the FAQ carefully enough. Make sure you use your graffiti as your asset name

**Comment by AgataGolik** [comment]
You are right, sorry. I saw but forgot.

**Comment by mat-if** [comment]
Going to close this since it isn't a bug, per Qloun's comment
