### ISSUE TITLE
Truncate entered metadata after symbol 4095

### ISSUE THREAD

**Issue by Qloun** [iron-fish/ironfish#3100]
### What happened?

If enter more than 4095 symbols in metadata, then in transaction stay only 4095 symbols with no warning about this

![image](https://user-images.githubusercontent.com/35996623/214264701-ee04a511-c67c-4dc9-a301-f1dcdf30f2fb.png)

![image](https://user-images.githubusercontent.com/35996623/214264744-535335a7-9b1a-464e-8eb6-951474df7256.png)

### Version

0.1.62

### Debug output

```shell
Database in use, skipping output that requires database.
Stop the node and run the debug command again to show full output.

Iron Fish version               0.1.62 @ 4ab43f3
Iron Fish library               0.0.39 @ 4ab43f3
Operating system                Linux x64
CPU model(s)                    AMD Ryzen 7 5800X 8-Core Processor
CPU threads                     16
RAM total                       125.73 GiB
Heap total                      4.00 GiB
Node version                    v18.13.0
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       megapapka
Block graffiti                  megapapka
```

### Graffiti

megapapka

**Comment by holahula** [comment]
Closing - an internal ticket will be made and this will be addressed
