### ISSUE TITLE
When executing "wallet:mint", about the input value (special symbol) of asset name and metadata..

### ISSUE THREAD

**Issue by jjungssang** [iron-fish/ironfish#3119]
### What happened?

I tried minting the asset by inputting English letters, numbers, and special symbols as shown below.
Minting was successful without any problems.
Is there no need to check the validity of the input text?

```
   (1) Random letters, numbers and special symbols
     Enter the name for the new asset: TEST#?!!@#$%^&*()_12345
     Enter metadata for the new asset: TEST#?!!@#$%^&*()_12345

   (2) Execution of Linux commands
     Enter the name for the new asset: `ll | mkdir TestDir | ll | rmdir TestDir`
     Enter metadata for the new asset: `ll | mkdir TestDir | ll | rmdir TestDir`

   (3) JavaScript code
     Enter the name for the new asset: <script>alert("ironfish mint test!!");</script>
     Enter metadata for the new asset: <script>alert("ironfish mint test!!");</script>
     
```
     

### Version

0.1.61 @ 009c85e

### Debug output

root@ubuntu-node-01:~# ironfish wallet:mint
Do you want to create a new asset (Y/N)?: Y
Enter the name for the new asset: TEST#?!!@#$%^&*()_12345
Enter metadata for the new asset: TEST#?!!@#$%^&*()_12345
Enter the amount to mint in the custom asset: 50
Enter the fee amount in $IRON (min: 0.00000001) [0.00000001]:

You are about to mint Name: TEST#?!!@#$%^&*()_12345 Metadata: TEST#?!!@#$%^&*()_12345
50.00000000 plus a transaction fee of $IRON 0.00000001 with the account default

* This action is NOT reversible *

Do you confirm (Y/N)?: Y
Creating the transaction: [████████████████████████████████████████] 100% | ETA: 0s

Minted asset TEST#?!!@#$%^&*()_12345 from default
Asset Identifier: 21f9a0ca06d0c8685c9ac56a03a8e63de2ed463cb3978b85fffc4ecce470b270
Value: 50.00000000

Transaction Hash: b10207db2b3132c970d20cffcfddacef39145ef8c1e8d6bf09d4a8feba6e7735

Find the transaction on https://explorer.ironfish.network/transaction/b10207db2b3132c970d20cf                                             fcfddacef39145ef8c1e8d6bf09d4a8feba6e7735 (it can take a few minutes before the transaction a                                             ppears in the Explorer)

#################################################################################

root@ubuntu-node-01:~# ironfish wallet:mint
Do you want to create a new asset (Y/N)?: Y
Enter the name for the new asset: `ll | mkdir TestDir | ll | rmdir TestDir`
Enter metadata for the new asset: `ll | mkdir TestDir | ll | rmdir TestDir`
Enter the amount to mint in the custom asset: -1
Enter the fee amount in $IRON (min: 0.00000001) [0.00000001]:

You are about to mint Name: `ll | mkdir TestDir | ll | rmdir TestDir` Metadata: `ll | mkdir T                                             estDir | ll | rmdir TestDir`
-1.00000000 plus a transaction fee of $IRON 0.00000001 with the account default

* This action is NOT reversible *

Do you confirm (Y/N)?: Y
Creating the transaction: [████████████████████████████████████████] 100% | ETA: 0s
An error occurred while minting the asset.
 ›   Error: Request failed (400) validation: Invalid mint amount
root@ubuntu-node-01:~# ironfish wallet:mint
Do you want to create a new asset (Y/N)?: Y
Enter the name for the new asset: `ll | mkdir TestDir | ll | rmdir TestDir`
Enter metadata for the new asset: `ll | mkdir TestDir | ll | rmdir TestDir`
Enter the amount to mint in the custom asset: 50
Enter the fee amount in $IRON (min: 0.00000001) [0.00000001]:

You are about to mint Name: `ll | mkdir TestDir | ll | rmdir TestDir` Metadata: `ll | mkdir T                                             estDir | ll | rmdir TestDir`
50.00000000 plus a transaction fee of $IRON 0.00000001 with the account default

* This action is NOT reversible *

Do you confirm (Y/N)?: Y
Creating the transaction: [████████████████████████████████████████] 100% | ETA: 0s

Minted asset `ll | mkdir TestDir | ll | rmdir from default
Asset Identifier: 62697e6439407bad26c85b3d1158e65f7699697eda20e683205ffecfb90d43b2
Value: 50.00000000

Transaction Hash: aee3ab57ac1a28b98c2966c21ce8d40a09bfcfa412703217931dff41ebf36301

Find the transaction on https://explorer.ironfish.network/transaction/aee3ab57ac1a28b98c2966c                                             21ce8d40a09bfcfa412703217931dff41ebf36301 (it can take a few minutes before the transaction a                                             ppears in the Explorer)

#################################################################################

root@ubuntu-node-01:~# ironfish wallet:mint
Do you want to create a new asset (Y/N)?: Y
Enter the name for the new asset: javascriptNameTest
Enter metadata for the new asset: ^C
root@ubuntu-node-01:~# ironfish wallet:mint
Do you want to create a new asset (Y/N)?: Y
Enter the name for the new asset: <script>alert("ironfish mint test!!");</script>
Enter metadata for the new asset: <script>alert("ironfish mint test!!");</script>
Enter the amount to mint in the custom asset: 50
Enter the fee amount in $IRON (min: 0.00000001) [0.00000001]:

You are about to mint Name: <script>alert("ironfish mint test!!");</script> Metadata: <script                                             >alert("ironfish mint test!!");</script>
50.00000000 plus a transaction fee of $IRON 0.00000001 with the account default

* This action is NOT reversible *

Do you confirm (Y/N)?: Y
Creating the transaction: [████████████████████████████████████████] 100% | ETA: 0s

Minted asset <script>alert("ironfish mint tes from default
Asset Identifier: 6018001b76d6f623efe1c9e72a573ee485d99235a27cbafd862e9f5087b2ebf1
Value: 50.00000000

Transaction Hash: c73c16593e3962a8eb2a8587c9830968587622de15fac995697d8554604a33f2

Find the transaction on https://explorer.ironfish.network/transaction/c73c16593e3962a8eb2a858                                             7c9830968587622de15fac995697d8554604a33f2 (it can take a few minutes before the transaction a                                             ppears in the Explorer)

### Relevant log output

```shell
Asset Name                       Asset Id                                Confirmed Balance
    ──────────────────────────────── ─────────────────────────────────────── ─────────────────
    TEST#?!!@#$%^&*()_12345          21f9a0ca06d0c8685c9ac56a03a8e63de2ed46… 50.00000000
    <script>alert("ironfish mint tes 6018001b76d6f623efe1c9e72a573ee485d992… 50.00000000
    `ll | mkdir TestDir | ll | rmdir 62697e6439407bad26c85b3d1158e65f769969… 50.00000000


    Transaction Hash: 
        b10207db2b3132c970d20cffcfddacef39145ef8c1e8d6bf09d4a8feba6e7735 
        aee3ab57ac1a28b98c2966c21ce8d40a09bfcfa412703217931dff41ebf36301 
        c73c16593e3962a8eb2a8587c9830968587622de15fac995697d8554604a33f2
```

### Graffiti

jjungssang

**Comment by hughy** [comment]
I don't see anything invalid about the names and metadata that you used in the examples.
