### ISSUE TITLE
I have 3 bugs. 1./ Node stops running without error. 2./ Node stops running with error. 3./ Minting_Sending_ Burning work/doesnt work no matter if I have or doesnt have enough balance.

### ISSUE THREAD

**Issue by Atesz1** [iron-fish/ironfish#3123]
### What happened?

A bug happened!

1./ Sometimes Node stops working without any error. 

2./ As you can see on "node bug1" screenshot, node stops working with this error even though it was running perfectly before.

3./ As you can see on "node bug2" screenshot, I tried to send some amount to the main address, but many times It failed because of insufficient balance, but after that It has been done successfully no matter if I have enough balance or I don't. I have this bug by doing minting/sending/burning all the time, and sometimes even by just put random numbers (larger than my balance is) It goess throw successfully, othertimes it fails even though I have enough balance on my wallet. . 

![node bug1](https://user-images.githubusercontent.com/47777498/214575917-d19e8ccd-8a1c-4a7b-a87c-0d3349a0fa5c.png)
![node bug2](https://user-images.githubusercontent.com/47777498/214575922-b7fa403f-8704-456b-845d-c49115d921c9.png)

### Version

Version       0.1.62 @ 4ab43f3

### Graffiti

Craft120

**Comment by hughy** [comment]
I'd suggest opening separate issues for the different problems you're seeing: it's easier for us to track them that way and you can earn testnet points for each issue

**Comment by holahula** [comment]
Closing due to staleness - if you are still running into problems please create separate issues
