### ISSUE TITLE
ironfish wallet send - null amount validation

### ISSUE THREAD

**Issue by nadavasan** [iron-fish/ironfish#3124]
### What happened?

name       ironfish
version    0.1.62
git        4ab43f3
runtime    node/18.13.0

ironfish wallet:send command is issued.
Amount to send is entered as 0 (Zero)
Instead of throwing error, it prompts for next step to get address and completes the zero amount transaction. 

Trx details:  https://explorer.ironfish.network/transaction/0c582d85773eff07fc9d9192f82b19fe3cc6d4d1a60e961baebef3c095248074

### Version

0.1.62

### Debug output

```shell
https://explorer.ironfish.network/transaction/0c582d85773eff07fc9d9192f82b19fe3cc6d4d1a60e961baebef3c095248074
```

### Relevant log output

```shell
https://explorer.ironfish.network/transaction/0c582d85773eff07fc9d9192f82b19fe3cc6d4d1a60e961baebef3c095248074
```

### Graffiti

sanjugsn

**Comment by hughy** [comment]
We've added input validation to amounts entered into the send command.

**Comment by nadavasan** [comment]
Thanks for your review. Kindly requesting you to add Bugs reported points :)

**Comment by hughy** [comment]
Of course! Please submit the form here to request points for the bug report: https://forms.gle/bLfwN9jb14ZWkHkZA
