### ISSUE TITLE
Feature: wallet send amount validation and address verification

### ISSUE THREAD

**Issue by nadavasan** [iron-fish/ironfish#3125]
### Description

![image](https://user-images.githubusercontent.com/37139275/214587235-2aaf8bdc-d7c2-4436-81c9-f5e67cf9220d.png)

Currently there is no validation for the 2 prompts:
1. Wallet send amount:
2. Wallet address:
Adding these validation for null, special character will avoid processing a fake or unwanted transaction.

In the screenshot attached, I have tried with "0" as send amount but the transaction was processed with success.
Details:
https://explorer.ironfish.network/transaction/0c582d85773eff07fc9d9192f82b19fe3cc6d4d1a60e961baebef3c095248074

**Comment by hughy** [comment]
We've added input validation for send amounts. We already included address verification.
