### ISSUE TITLE
Mint produces hash but no IRON spent, tx hash not found in explorer

### ISSUE THREAD

**Issue by githjo** [iron-fish/ironfish#3128]
### What happened?

I have minted, burnt and sent IRON to the proposed wallet. Burn and send has spent IRON, the mint did not spend any IRON. Same wallet balance before and after the mint. Checked with ironfish wallet:balance after each action. 

There were no points accredited in leaderboard. The transaction hashes for all three actions were not found in the explorer although they were produced in CLI. 

Addition: after 15min I checked again the hash was found in explorer. but points were not awarded in leaderboard. 

example: 

root@vmi838756:~# ironfish wallet:balance
Account: default
Balance: $IRON 0.00000006

root@vmi838756:~# ironfish wallet:burn
? Select the asset you wish to burn 
938820296a5001bc0c11646a77ee029c0470f7316da34b26ffc972bc58028506 (Eisenfisch)
Enter the amount to burn in the custom asset: 5
Enter the fee amount in $IRON (min: 0.00000001) [0.00000001]: 

You are about to burn:
938820296a5001bc0c11646a77ee029c0470f7316da34b26ffc972bc58028506 5.00000000 plus a transaction fee of $IRON 0.00000001 with the account default

* This action is NOT reversible *

Do you confirm (Y/N)?: y
Creating the transaction: [████████████████████████████████████████] 100% | ETA: 0s

Burned asset 938820296a5001bc0c11646a77ee029c0470f7316da34b26ffc972bc58028506 from default
Value: 5.00000000

Transaction Hash: dd81f2a9999f1f8c45093a9d2c30c247a44c3fb8758371f454c4c2c2fd0d2a55

Find the transaction on https://explorer.ironfish.network/transaction/dd81f2a9999f1f8c45093a9d2c30c247a44c3fb8758371f454c4c2c2fd0d2a55 (it can take a few minutes before the transaction appears in the Explorer)
root@vmi838756:~# ironfish wallet:send
? Select the asset you wish to send 
938820296a5001bc0c11646a77ee029c0470f7316da34b26ffc972bc58028506 (Eisenfisch)
Enter the amount (balance: 30.00000000): 5
Enter the public address of the recipient: dfc2679369551e64e3950e06a88e68466e813c63b100283520045925adbe59ca
Enter the fee amount in $IRON (min: 0.00000001 recommended: 0.00000001) [0.00000001]: 

You are about to send:
938820296a5001bc0c11646a77ee029c0470f7316da34b26ffc972bc58028506 5.00000000 plus a transaction fee of $IRON 0.00000001 to dfc2679369551e64e3950e06a88e68466e813c63b100283520045925adbe59ca from the account default

* This action is NOT reversible *

Do you confirm (Y/N)?: y
Creating the transaction: [████████████████████████████████████████] 100% | ETA: 0s

Sending 938820296a5001bc0c11646a77ee029c0470f7316da34b26ffc972bc58028506 5.00000000 to dfc2679369551e64e3950e06a88e68466e813c63b100283520045925adbe59ca from default
Transaction Hash: ee434759f913ce86457d8b3a984e3ba435375495d1ea03cf9b99b02e4cbbdcfd
Transaction fee: $IRON 0.00000001

Find the transaction on https://explorer.ironfish.network/transaction/ee434759f913ce86457d8b3a984e3ba435375495d1ea03cf9b99b02e4cbbdcfd (it can take a few minutes before the transaction appears in the Explorer)
root@vmi838756:~# ironfish wallet:balance
Account: default
Balance: $IRON 0.00000005

root@vmi838756:~# ironfish wallet:mint
Do you want to create a new asset (Y/N)?: y
Enter the name for the new asset: Eisenfisch
Enter metadata for the new asset: Eisenfisch
Enter the amount to mint in the custom asset: 20
Enter the fee amount in $IRON (min: 0.00000001) [0.00000001]:  

You are about to mint Name: Eisenfisch Metadata: Eisenfisch
20.00000000 plus a transaction fee of $IRON 0.00000001 with the account default

* This action is NOT reversible *

Do you confirm (Y/N)?: y
Creating the transaction: [████████████████████████████████████████] 100% | ETA: 0s

Minted asset Eisenfisch from default
Asset Identifier: 938820296a5001bc0c11646a77ee029c0470f7316da34b26ffc972bc58028506
Value: 20.00000000

Transaction Hash: 40f574b2147a3e7cd4ada5e8bd98e15a23952e50d3d970886b1aadfd74b219a6

Find the transaction on https://explorer.ironfish.network/transaction/40f574b2147a3e7cd4ada5e8bd98e15a23952e50d3d970886b1aadfd74b219a6 (it can take a few minutes before the transaction appears in the Explorer)
root@vmi838756:~# ironfish wallet:balance
Account: default
Balance: $IRON 0.00000005
root@vmi838756:~# 

### Graffiti

Eisenfisch

**Comment by githjo** [comment]
Version v0.1.62

**Comment by hughy** [comment]
The leaderboard for `Eisenfisch` shows that points have already been awarded for mint, burn, and send for this week: https://testnet.ironfish.network/users/275653

**Comment by githjo** [comment]
so Sunday was part of the current week correct? means earliest I can do new transaction is Sunday again. Thanks for short confirmation
