### ISSUE TITLE
Frequently Asked Questions

### ISSUE THREAD

**Issue by Serge-GHSHCH** [iron-fish/ironfish#3139]
### What happened?

There is a typo on the [FAQ page](https://testnet.ironfish.network/faq):
see qestion "Will there be weekly limits on earning points?".
The word "able" is printed twice in a row ("Yes, each graffiti will be **able able** to earn points once a week for interacting with multiasset transactions").

### Graffiti

QuasiNode

**Comment by ygao76** [comment]
Thanks @Serge-GHSHCH for catching the typo. the FAQ page is updated.
