### ISSUE TITLE
Burn Asset & Balances

### ISSUE THREAD

**Issue by nurulihsan27** [iron-fish/ironfish#3140]
### What happened?

For information, I have mint 10000 token (asset).
I try to burn 1000 token and the transaction was success, then I try to send but it's failed and give an output "Error: Request failed (400) insufficient-balance: Your balance is too low. Add funds to your account first". then I tried to check my balance and it turned out that my token had 0 balance, even though I only burned 1000 tokens and there should still be 9000 tokens left. Then I tried to wait a while, and I tried again to check my wallet, and it turned out that my balance had returned to 9000. I don't know whether the mechanism is like this or not, but in my opinion the problem of an inappropriate balance after we make a transaction is fatal. because it will cause confusion and panic, especially later on the mainnet.

### Version

v18.13.0

### Graffiti

nurulihsan

**Comment by hughy** [comment]
This issue will be resolved when #3059 is released
