### ISSUE TITLE
Send $IRON 1 to other wallet, but the balance is not right for a minutes

### ISSUE THREAD

**Issue by dboyxyz** [iron-fish/ironfish#3153]
### What happened?

What happened?
Step 1. send $IRON 1 from A wallet to B wallet,  the balance of the A wallet is 60.01216181 befor send
Step 2. use ironfish wallet:send
Step 3. use ironfish wallet:balance, the balance oft the A wallet is 40.01216181
Step 4. wait for a minutes, the balance of the A wallet is 59.01216181
![2581674559653_ pic](https://user-images.githubusercontent.com/14068284/215077534-631c88e4-3269-4c2e-adba-3017a2e4b72b.jpg)
![2611674559989_ pic](https://user-images.githubusercontent.com/14068284/215077556-ff5401d8-36d4-4509-9aa3-1c920db11591.jpg)

### Version

0.1.62

### Debug output

```shell
Iron Fish version               0.1.62 @ 4ab43f3
Iron Fish library               0.0.39 @ 4ab43f3
Operating system                Linux x64
CPU model(s)                    12th Gen Intel(R) Core(TM) i9-12900K
CPU threads                     24
RAM total                       125.54 GiB
Heap total                      4.00 GiB
Node version                    v18.12.1
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       xym1221
Block graffiti                  xym1221
```

### Graffiti

xym1221

**Comment by hughy** [comment]
This issue should be resolved by #3059 on version 0.1.63
