### ISSUE TITLE
Stuck in WebSocket Server Started at ::9033

### ISSUE THREAD

**Issue by mapogo7th** [iron-fish/ironfish#3154]
### What happened?

My node got stucked in websocket server and can't do anything about it it's been like an hour already after I start typing the ironfish start command. What should be the possible ways to get out of this and continue node registration?

### Graffiti

totoy4741

**Comment by hughy** [comment]
Nodes were temporarily unable to connect to the network because the bootstrap node was down.

Please open a new issue or reopen this one if this issue was note resolved.
