### ISSUE TITLE
Send tx is getting Failed

### ISSUE THREAD

**Issue by pratikgarg1122** [iron-fish/ironfish#3156]
### What happened?

Trying to send some $IRON but it got failed with the below error : 

> No route found wallet/createTransaction in namespace wallet for method createTransaction    

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/123742309/215091180-97380028-b689-4071-89b8-d05ca89df520.png">

### Version

v0.1.63

### Graffiti

pratikmbm1122

**Comment by ygao76** [comment]
You need to upgrade your ironfish version. The send command is calling a new API endpoint. You need to upgrade your node and restart your node.
