### ISSUE TITLE
Websocket Error 

### ISSUE THREAD

**Issue by pratikgarg1122** [iron-fish/ironfish#3157]
### What happened?

After Ironfish got upgraded to v0.1.63, lot many users got impacted and node is getting stuck while launching. It got stuck and no progress since one hr

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/123742309/215091559-dcf5c874-077e-4326-b971-7f22536a8ac4.png">

### Version

v0.1.63

### Debug output

I tried downgrading to v0.1.62 but it didn't work out. It still got stuck
`sudo npm install -g ironfish@0.1.62` 

### Graffiti

pratikmbm1122

**Comment by pratikgarg1122** [comment]
Tried to replace hosts.json file but still it couldn't sync

**Comment by hughy** [comment]
Users were unable to connect to the network because the bootstrap node was down.
