### ISSUE TITLE
Mining Pool Reward Issue and Reason

### ISSUE THREAD

**Issue by lovely230** [iron-fish/ironfish#3166]
### What happened?

All node runners are not getting any mining pool share even after running node for so many hours.

 Issue is my node ran mining pool for several hours yesterday and day before yesterday as well but i didnot get any mining reward even after running miner for several hours.  I am single running node (ironfish only) on single terminal only. I was getting only hash power of 1 to 1.5 max MHS and i was not getting any reward. One of my friends was getting 4 MHS with same node provider and same specs of vps x4 and 8 GB ram.
 
 I tried to optimize my VPS  and finally  yesterday night i was getting 4 Mhs . and very soon i got mining pool reward of 0.051
 
 Conclusion: All nodes are not getting mining pool reward even if they are running nodes properly with continuous uptime.
 I didnot get any reward at 1.5 Mhs but got at 4 Mhs .   It means all users are not being rewarded .  Only users with higher hash rate are being rewarded from mining pool.

### Version

ubuntu latest

### Graffiti

bhavya

**Comment by hughy** [comment]
Users are rewarded from the mining pool proportionate to the hash rate that they contribute to the mining pool.
