### ISSUE TITLE
Faucet not working

### ISSUE THREAD

**Issue by KudrinDV** [iron-fish/ironfish#3177]
### What happened?

A bug happened!
Faucet not working.

Wallet replenishment not working KudrinDV (ff2a534e84947e2c23a989698987aa0cae8262771a0c8be97d2358eb7ab38812)

Created a new wallet, payments are now coming to it: kudrin (1238b1e9a76fe39485659d0da6a353ca3d63e3024540e2501a595ec47a8d5206)

Faucet still not working

Email: kudrindv@mail.ru

### Version

18.13.0

### Debug output

```shell
Database in use, skipping output that requires database.
Stop the node and run the debug command again to show full output.

Iron Fish version               0.1.63 @ 693ff0f
Iron Fish library               0.0.40 @ 693ff0f
Operating system                Linux x64
CPU model(s)                    Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz
CPU threads                     8
RAM total                       11.70 GiB
Heap total                      2.00 GiB
Node version                    v18.13.0
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       KudrinDV
Block graffiti                  KudrinDV
```

### Graffiti

KudrinDV

**Comment by hughy** [comment]
Can you include error message or an explanation of how you know that it is not working?

**Comment by KudrinDV** [comment]
Coins to the address ff2a534e84947e2c23a989698987aa0cae8262771a0c8be97d2358eb7ab38812 are not coming from my friends!

**Comment by KudrinDV** [comment]
Coins don't come out of the faucet

**Comment by hughy** [comment]
Is your node and wallet synced with the chain?

You can run `ironfish status` to see whether your node is synced and `ironfish wallet:status` to see whether your accounts are synced

Do you see pending transactions when you run `ironfish wallet:transactions`?

**Comment by KudrinDV** [comment]
Account Name Account ID                 Head Hash Head In Chain Head Sequence 
 ──────────── ────────────────────────── ───────── ───────────── ───────────── 
 default      28a29fbe-8716-4a06-977f-9… 00000000… true          19704         
 KudrinDV     e0110f0b-ec64-4ee0-b6a3-7… 00000000… true          915           
 kudrin       95baceb3-13a9-4d4d-b2b0-f… 00000000… true          19704

**Comment by KudrinDV** [comment]
Account Name Account ID                 Head Hash Head In Chain Head Sequence 
 ──────────── ────────────────────────── ───────── ───────────── ───────────── 
 default      28a29fbe-8716-4a06-977f-9… 00000000… true          19704         
 KudrinDV     e0110f0b-ec64-4ee0-b6a3-7… 00000000… true          915           
 kudrin       95baceb3-13a9-4d4d-b2b0-f… 00000000… true          19704         
root@vm938985:~# ironfish status
Version              0.1.63 @ 693ff0f
Node                 STARTED
Node Name            KudrinDV
Block Graffiti       KudrinDV
Memory               Heap: 251.53 MiB -> 398.36 MiB / 1.99 GiB (12.3%), RSS: 1.47 GiB (12.6%), Free: 8.77 GiB (25.0%)
CPU                  Cores: 8, Current: 406.5%
P2P Network          CONNECTED - In: 50.88 KB/s, Out: 55.93 KB/s, peers 50
Mining               STARTED - 1 miners, 1 mined
Mem Pool             Count: 80 tx, Bytes: 168.99 KiB
Syncer               IDLE - 0.41 blocks added/sec
Blockchain           0000000000352796f327838a10c016fb67bc9ad659ec2c825b249b9d91d90642 (19705), Since HEAD: 30s 831ms (SYNCED)
Accounts             0000000000352796f327838a10c016fb67bc9ad659ec2c825b249b9d91d90642 (19705)
Telemetry            STARTED - 37699 <- 62 pending
Workers              STARTED - 101 -> 6 / 6 - 9.76 jobs Δ, 41.38 jobs/s

**Comment by KudrinDV** [comment]
Timestamp                   Status      Type    Hash Net Amount ($IRON)  Fee Paid ($IRON)    Notes Spends Mints Burns Expiration 
 ─────────────────────────── ─────────── ─────── ──── ─────────────────── ─────────────────── ───── ────── ───── ───── ────────── 
 1/30/2023 8:28:20 AM GMT+1  confirmed   miner   048… 20.00000001                             1     0      0     0     0          
 1/29/2023 5:38:04 PM GMT+1  confirmed   send    f97…                     0.00000001          2     2      0     0     18209      
 1/29/2023 10:10:42 AM GMT+1 confirmed   send    279…                     0.00000001          1     1      1     0     17780      
 1/29/2023 5:43:26 AM GMT+1  confirmed   receive e1f… 0.00000001                              1     1      0     0     17525      
 1/28/2023 7:05:33 PM GMT+1  confirmed   send    fa1…                     0.00000001          1     2      0     1     16861      
 1/28/2023 6:58:57 PM GMT+1  confirmed   send    4c6…                     0.00000001          3     2      0     0     16853      
 1/28/2023 6:52:26 PM GMT+1  confirmed   send    569…                     0.00000001          1     1      1     0     16846      
 1/28/2023 6:51:18 PM GMT+1  confirmed   receive 8e9… 0.00000002                              2     1      0     0     16843      
 1/28/2023 6:50:10 PM GMT+1  confirmed   receive 9c9… 0.00000002                              1     1      0     0     16843      
 1/28/2023 6:42:48 PM GMT+1  confirmed   receive d50… 0.00000001                              1     1      0     0     16837

**Comment by hughy** [comment]
Your account `KudrinDV` is very far behind the head of the chain : it is only at block 915. Any transactions that occurred after that block won't show up for that account because the account hasn't scanned them yet.

You can try running `ironfish wallet:rescan` to force your wallet to scan the chain for transactions involving that account

**Comment by KudrinDV** [comment]
root@vm938985:~# ironfish wallet:rescan
Asking node to start scanning... ⣯
