### ISSUE TITLE
Burn Asset Failed

### ISSUE THREAD

**Issue by dboyxyz** [iron-fish/ironfish#3181]
### What happened?

I want to finish the task of Mint/Send/Burn asset.
Mint and send success, But burn asset failed, the error is:
Creating the transaction: [████████████████████████████████████████] s
An error occurred while burning the asset.
 ›   Error: Request failed (400) error: Insufficient funds: Needed 
 ›   $IRON 0.00000001 but have 0.00000000 available to spend. Please 
 ›   fund your account and/or wait for any pending transactions to be
 ›    confirmed.'

And I sure I have enough $IRON in my wallet.

![2023-01-29 09-04-48屏幕截图](https://user-images.githubusercontent.com/14068284/215298311-1daed6df-68f4-444e-8ba9-81cf3e354909.png)

### Version

v18.13.0

### Debug output

```shell
Database in use, skipping output that requires database.
Stop the node and run the debug command again to show full output.

Iron Fish version               0.1.62 @ 4ab43f3
Iron Fish library               0.0.39 @ 4ab43f3
Operating system                Linux x64
CPU model(s)                    12th Gen Intel(R) Core(TM) i9-12900K
CPU threads                     24
RAM total                       125.54 GiB
Heap total                      4.00 GiB
Node version                    v18.12.1
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       xym1221
Block graffiti                  xym1221
```

### Graffiti

xym1221

**Comment by hughy** [comment]
#3515 adds calculation of 'available' balance: the amount that you can send in a transaction at the given time.
