### ISSUE TITLE
Burn asset and balances

### ISSUE THREAD

**Issue by ziggy010** [iron-fish/ironfish#3182]
### What happened?

After i minted 1000 tokens, and decided to burn 10 of the asset, it did it successfully but it burned my whole 1000 tokens and took 0.1 iron for the transaction when i used only 0.00000001 iron for the transaction fee.
<img width="1260" alt="Screenshot 2023-01-29 at 8 38 54 AM" src="https://user-images.githubusercontent.com/93469715/215302050-46cc3812-70c8-4b82-b11d-e909b0a9d7bd.png">

### Graffiti

Ziggy

**Comment by hughy** [comment]
Which version of ironfish are you running? This should be resolved on v0.1.63 by #3059
