### ISSUE TITLE
Send Request failed : Insufficient balance

### ISSUE THREAD

**Issue by satya-jugran** [iron-fish/ironfish#3187]
### What happened?

I tried to send some amount to the public address provided on ironfish faq - dfc2679369551e64e3950e06a88e68466e813c63b100283520045925adbe59ca

It has given me the following error (even though I have enough balance on the test asset minted:
Error: Request failed (400) insufficient-balance: Not enough unspent notes available to fund the transaction. Please wait for any pending transactions to be
 ›   confirmed.
 
![image](https://user-images.githubusercontent.com/9986730/215316155-ab5f6a43-268e-451c-8ee0-376bf8c7b24e.png)

### Version

0.1.62 @ 4ab43f3

### Graffiti

satyaj

**Comment by hughy** [comment]
#3515 adds calculation of 'available' balance: the amount that you can send in a transaction at the given time.
