### ISSUE TITLE
The number of miners is displayed incorrectly

### ISSUE THREAD

**Issue by t1ddl3r** [iron-fish/ironfish#3188]
### What happened?

Manually started miners don't seem to be counted even though the hashrate can be seen.
It seems that the count is always 0 after stopping the autostarted miner service.

<img width="628" alt="1" src="https://user-images.githubusercontent.com/16135583/215317257-bbce530f-2153-498c-a83a-57d6486ce08e.png">

We run the miner.

`ironfish miners:start -v -t 1 --pool pool.ironfish.network --address 9f28e744a0928daee7....`

<img width="727" alt="2" src="https://user-images.githubusercontent.com/16135583/215317410-51663c64-4da3-40e5-88ba-ea366a65717f.png">

But the miner count didn't change to 1 and after 4 hours of mining I didn't get the reward.

### Version

v0.1.63

### Debug output

```shell
Iron Fish version               0.1.63 @ 693ff0f
Iron Fish library               0.0.40 @ 693ff0f
Operating system                Linux x64
CPU model(s)                    AMD EPYC-Rome Processor
CPU threads                     2
RAM total                       3.83 GiB
Heap total                      1.91 GiB
Node version                    v18.13.0
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       chu4nx
Block graffiti                  chu4nx
```

### Graffiti

t1ddl3r

**Comment by hughy** [comment]
`ironfish status` will only display miners that are connected to your node. If you connect to a mining pool, like `pool.ironfish.network`, then your miner is not connected to your node.

You will receive payouts from the pool in proportion to any valid 'shares' that you submit to the pool. You can track pool payouts on Discord in the mining-pool '#alerts' channel
