### ISSUE TITLE
wrong balances

### ISSUE THREAD

**Issue by pgekr** [iron-fish/ironfish#3189]
### What happened?

A bug happened!
after i mint and burn an asset, the balances is incorrect.

the balance of minted asset $pgekr became from 2000 to 1000, balance of $iron became from 38.92660157 to 36.81834874.
![image](https://user-images.githubusercontent.com/103747513/215319778-77f2c18b-03f0-4432-af40-a5cd7956153e.png)

### Version

 ironfish/0.1.62 linux-x64 node-v18.13.0

### Graffiti

pgekr

**Comment by pgekr** [comment]
fyi: this happened in the process of burning of asset.

**Comment by pgekr** [comment]
today, i checked the balances twice, and did nothing. the balances are different. it became 55.74032888 from 58.88808017, i did not send, did not burn, nothing.
![image](https://user-images.githubusercontent.com/103747513/215531830-fa132ec5-8a51-4faf-b956-6f2fbe034b5b.png)

**Comment by hughy** [comment]
Is your node and wallet fully up-to-date with the chain?

You can run `ironfish wallet:status` to see if your accounts have scanned up to the current head of the chain.

You can also run `ironfish wallet:transactions` to see a list of all transactions sent from and received by your account
