### ISSUE TITLE
[Account register]

### ISSUE THREAD

**Issue by quangthanh010290** [iron-fish/ironfish#3197]
### What happened?

When create a new account, the site popup logged in, but in fact, it was not
![Screenshot from 2023-01-30 10-56-15](https://user-images.githubusercontent.com/8197161/215385145-e07d169c-86cb-403c-adc5-dc05661ea48e.png)

### Graffiti

https://testnet.ironfish.network/users/272976

**Comment by ygao76** [comment]
this is expected flow.
