### ISSUE TITLE
 Burn balnace update issue

### ISSUE THREAD

**Issue by mano18** [iron-fish/ironfish#3198]
### What happened?

A bug happened!
![Capture](https://user-images.githubusercontent.com/54184441/215391143-8a3ab979-7766-4dcf-9c6f-1454d42b00d9.JPG)

### Graffiti

manohar

**Comment by hughy** [comment]
The `wallet:balances` command currently shows the on-chain balance of each asset. If a transaction is pending, then it will not update this balance. You can run `ironfish wallet:balances --all` to see the pending balance for each asset.

**Comment by hughy** [comment]
@mano18 which version of ironfish are you running? this issue should be resolved on v0.1.63, which includes the fix in #3059

**Comment by mano18** [comment]
i am running v0.1.64 now

**Comment by mano18** [comment]
currently nope but if i find again will report here

**Comment by hughy** [comment]
Great! Please feel free to reopen this issue if you run into this again!
