### ISSUE TITLE
Request failed (400) insufficient-balance

### ISSUE THREAD

**Issue by AgataGolik** [iron-fish/ironfish#3199]
### What happened?

Dear Sirs,

mint was made for 50 Rafal tokens, burn for 5 tokens. After waiting a few minutes the balance showed 54. Then there was an attempt to perform the third task, send 1 token to the wallet, it showed "Error: Request failed (400) insufficient-balance: Your balance is too low. Add funds to your account first". The balance of the token was already 49, i.e. the tokens were taken from the account and the error remained.
On the next attempt, the transaction was ok , I send 1 token and now wallet blance is 48. 
The task was completed, however, the first attempt failed and the funds disappeared.

It shows me on the dashboardhat it shows me on the dashboard:

? Select the asset you wish to send d3673307728311b9275a5ccc982833e190fc596174f3b71ff580cd9f732f8028 (Rafal)
Enter the amount (balance: 54.00000000): 1
Enter the public address of the recipient: dfc2679369551e64e3950e06a88e68466e813c63b100283520045925adbe59ca
Enter the fee amount in $IRON (min: 0.00000001 recommended: 0.00000001) [0.00000001]: 0.00000001

You are about to send:
d3673307728311b9275a5ccc982833e190fc596174f3b71ff580cd9f732f8028 1.00000000 plus a transaction fee of $IRON 0.00000001 to dfc2679369551e64e3950e06a88e68466e813c63b100283520045925adbe59ca from the account default

* This action is NOT reversible *

Do you confirm (Y/N)?: y
Creating the transaction: [████████████████████████████████████████] 100% | ETA: 0s
An error occurred while sending the transaction.
 ›   Error: Request failed (400) insufficient-balance: Your balance is too low. Add funds to your account first
root@fish:~# ironfish wallet:send
? Select the asset you wish to send d3673307728311b9275a5ccc982833e190fc596174f3b71ff580cd9f732f8028 (Rafal)
Enter the amount (balance: 49.00000000): 1

Regards
Agata Golik

### Graffiti

Rafal

**Comment by hughy** [comment]
You may see insufficient balance errors when you have one or more pending transactions that are using notes in your account.

You can run `ironfish wallet:transactions` to see any pending transactions, and `ironfish wallet:balances --all` to see the pending balances (what the balance will be after pending transactions have completed)

**Comment by hughy** [comment]
#3515 adds calculation of 'available' balance: the amount that you can send in a transaction at the given time.
