### ISSUE TITLE
build from source failing on Linux (ubuntu 18.04) 

### ISSUE THREAD

**Issue by navneetlakra** [iron-fish/ironfish#32]
Building from source by following the steps provided at https://github.com/iron-fish/ironfish#readme. Performed following steps:

1. Installed nodejs [v14.16.1]
2. Installed rust [v1.48.0 (7eac88abb 2020-11-16)]
3. Installed yarn [1.22.5]
4. Installed WASM using `cargo install wasm-pack`
5. Ran yarn from ironfish root directory

Got the following output from `yarn`
-------------------------------------------------------------------------------
yarn install v1.22.5
$ (cd ironfish-wasm && yarn build)
yarn run v1.22.5
$ node build.js
Building Web: TRUE
Building Node: TRUE
Generating nodejs build...
[INFO]: Checking for the Wasm target...
[INFO]: Compiling to Wasm...
   Compiling ironfish_rust v0.1.0 (/home/azureuser/ironfish/ironfish-rust)
error: could not compile `ironfish_rust`

Caused by:
  process didn't exit successfully: `rustc --crate-name ironfish_rust --edition=2018 /home/azureuser/ironfish/ironfish-rust/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C metadata=979b04c0e2c98600 -C extra-filename=-979b04c0e2c98600 --out-dir /home/azureuser/ironfish/ironfish-wasm/target/wasm32-unknown-unknown/release/deps --target wasm32-unknown-unknown -L dependency=/home/azureuser/ironfish/ironfish-wasm/target/wasm32-unknown-unknown/release/deps -L dependency=/home/azureuser/ironfish/ironfish-wasm/target/release/deps --extern bellman=/home/azureuser/ironfish/ironfish-wasm/target/wasm32-unknown-unknown/release/deps/libbellman-e76a888b782aa027.rmeta --extern blake2b_simd=/home/azureuser/ironfish/ironfish-wasm/target/wasm32-unknown-unknown/release/deps/libblake2b_simd-3efcad22c63616cb.rmeta --extern blake2s_simd=/home/azureuser/ironfish/ironfish-wasm/target/wasm32-unknown-unknown/release/deps/libblake2s_simd-bedfb6996d3abe1c.rmeta --extern byteorder=/home/azureuser/ironfish/ironfish-wasm/target/wasm32-unknown-unknown/release/deps/libbyteorder-191e06838c827d97.rmeta --extern ff=/home/azureuser/ironfish/ironfish-wasm/target/wasm32-unknown-unknown/release/deps/libff-0f4bbc378e77dbee.rmeta --extern lazy_static=/home/azureuser/ironfish/ironfish-wasm/target/wasm32-unknown-unknown/release/deps/liblazy_static-648b5e6ff3716478.rmeta --extern pairing=/home/azureuser/ironfish/ironfish-wasm/target/wasm32-unknown-unknown/release/deps/libpairing-92dbfaf097c6ec08.rmeta --extern rand=/home/azureuser/ironfish/ironfish-wasm/target/wasm32-unknown-unknown/release/deps/librand-752ac871cf82f4d2.rmeta --extern crypto=/home/azureuser/ironfish/ironfish-wasm/target/wasm32-unknown-unknown/release/deps/libcrypto-f158c947b1df7fcc.rmeta --extern shrinkwraprs=/home/azureuser/ironfish/ironfish-wasm/target/release/deps/libshrinkwraprs-040184ef3997064b.so --extern bip39=/home/azureuser/ironfish/ironfish-wasm/target/wasm32-unknown-unknown/release/deps/libbip39-99c803848e0a3a35.rmeta --extern zcash_primitives=/home/azureuser/ironfish/ironfish-wasm/target/wasm32-unknown-unknown/release/deps/libzcash_primitives-f1386c11db967052.rmeta --extern zcash_proofs=/home/azureuser/ironfish/ironfish-wasm/target/wasm32-unknown-unknown/release/deps/libzcash_proofs-13a74049ea3519e1.rlib -L native=/home/azureuser/ironfish/ironfish-wasm/target/wasm32-unknown-unknown/release/build/rust-crypto-wasm-9524ee1103f6eb96/out` (signal: 9, SIGKILL: kill)
Error: Compiling your crate to WebAssembly failed
Caused by: failed to execute `cargo build`: exited with exit code: 101
  full command: "cargo" "build" "--lib" "--release" "--target" "wasm32-unknown-unknown"
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by dguenther** [comment]
Do you have any additional error messages? It may have run out of memory while doing the build

**Comment by navneetlakra** [comment]
No, there are no other error messages. As you pointed out it could be due to memory. I am running a crappy VM. Will try on a a better spec'ed VM again.

**Comment by dguenther** [comment]
Going to close this since the build runs in Github Actions, but feel free to post in our Discord and Telegram if you're still running into issues after trying on a different computer.
