### ISSUE TITLE
Multi-asset send transaction dose not show on https://testnet.ironfish.network/

### ISSUE THREAD

**Issue by 696lucky13** [iron-fish/ironfish#3202]
### What happened?

"Multi-asset send" transaction dose not show on https://testnet.ironfish.network/ 
-transaction went through 
-other transactions mint/burn show up immidiatly https://testnet.ironfish.network/ 
Made "send" transaction week 2 -nothing showed up
Made "send" transaction week 3 -nothing showed up
<img width="818" alt="Skjermbilde 2023-01-30 kl  12 43 56" src="https://user-images.githubusercontent.com/107635364/215469256-08e14de0-d2b2-4c89-adeb-7eb29d89d9e8.png">
<img width="862" alt="Skjermbilde 2023-01-30 kl  12 44 20" src="https://user-images.githubusercontent.com/107635364/215469273-6381bcc1-a22a-4ba5-b466-f26bd31a4001.png">
<img width="1047" alt="Skjermbilde 2023-01-30 kl  12 45 27" src="https://user-images.githubusercontent.com/107635364/215469287-08fd5164-2dc8-4d91-9f76-da4b81e5f7dc.png">

### Debug output

```shell
Iron Fish version               0.1.63 @ 693ff0f
Iron Fish library               0.0.40 @ 693ff0f
Operating system                Linux x64
CPU model(s)                    AMD EPYC 7282 16-Core Processor
CPU threads                     4
RAM total                       7.77 GiB
Heap total                      2.00 GiB
Node version                    v18.13.0
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       YellowBear
Block graffiti                  YellowBear
```

### Graffiti

YellowBear

**Comment by hughy** [comment]
Your screenshot shows that you are sending $IRON to the testnet address instead of your custom asset. You need to send some of your custom asset to that address in order to earn Phase 3 testnet points
