### ISSUE TITLE
Insufficient fund error (when wallet balance showing positive funds)

### ISSUE THREAD

**Issue by RaeesC** [iron-fish/ironfish#3206]
### What happened?

Hi team - as of 30th Jan 2023 and 17:50 UTC - I identified a bug where transactions to burn and transfer (cannot confirm mint) are not working due to an error report saying:

Error: Request failed (400) error: Insufficient funds: Needed $IRON 0.00000001 but have 0.00000000 
 ›   available to spend. Please fund your account and/or wait for any pending transactions to be confirmed.'
 
 However when I go back and check wallet balance, it is positive and says:

ironfish wallet:balance
Account: default
Balance: $IRON 0.00000005

I cannot therefore complete any transactions such as burn or transfer.  Many thanks

<img width="1018" alt="Screenshot 2023-01-30 at 17 53 42" src="https://user-images.githubusercontent.com/32003183/215555456-5a88878d-b380-4d54-a772-710bd750ca8a.png">
<img width="781" alt="Screenshot 2023-01-30 at 17 53 11" src="https://user-images.githubusercontent.com/32003183/215555459-c3db4048-6abf-419a-8bce-f631b67369ee.png">

### Graffiti

https://testnet.ironfish.network/users/231445

**Comment by hughy** [comment]
Iron Fish is a UTXO currency similar to bitcoin: your balance is made of 'notes' and each note has a specific value, like physical cash.

When you make a transaction, you spend one or more of your notes. If the amount that you are sending is less than the value of the note then you receive a new note as 'change'. Just like a transaction with physical cash: if you buy something worth $10 using a note worth $20, you still have $10, but you can't spend that $10 until the vendor gives you your change.

However, a transaction in Iron Fish may be pending for several minutes before your change has been received. We're working on the wallet user experience to make this clearer.

**Comment by RaeesC** [comment]
Hi Hughy - I understand your logic, but it may be worth confirming whether there may be a bug.  

I am aware of the UTXO currency system but my example above is the equivalent - using your example - of having $50 in physical cash, making a transaction with a $20 note for a product (i.e. with $30 untouched) worth $10 and not being able to utilise the remaining $30 that is untouched.  I.e. I had a relatively high amount of $IRON for gas utilised that should I expect have been able to take the mint transaction?  Please do correct me if I'm wrong - thanks.

**Comment by hughy** [comment]
It depends on how many notes you have in your account. You can use `ironfish wallet:notes` to see all notes

If you have only one $50 note when you make your transaction, then you don't have anything available to spend until the change is returned. It's possible for your entire balance to be held in a single note, which basically limits you to one transaction at a time.

**Comment by RaeesC** [comment]
I will check this - unfortunately I cannot do it retroactively for the error I screenshotted but will attempt to recreate the error.  Thanks and have a good day / evening

**Comment by hughy** [comment]
#3515 adds calculation of 'available' balance: the amount that you can send in a transaction at the given time.
