### ISSUE TITLE
Waiting for graffiti from pool...

### ISSUE THREAD

**Issue by hntrader** [iron-fish/ironfish#3214]
### Description

i am trying to mining last 12 hour , waiting for graffiti from pool, so please help , as soon possible as

**Comment by hughy** [comment]
Can you explain more about what you're seeing?

What command did you run to join a mining pool?

What is the output that you're seeing?

**Comment by hntrader** [comment]
Thanks bro my problem is resolved, i appreciate you

**Comment by hughy** [comment]
Great! Glad to hear the issue is resolved! 

Please feel free to reopen this issue if you run into it again
