### ISSUE TITLE
Feature:  Auto Sync of Node Runtime on Web Interface

### ISSUE THREAD

**Issue by izziest** [iron-fish/ironfish#3223]
### Description

It will be nice if the runtime of the hosted node is displayed on the dashboard since it has been synced with the user Graffiti. This will help whichever user logging in to the dashboard to know the status of his node. 

What is currently on display on the dashboard is just the time(hours) a node is up and it doesn't tell if the node is still running or it is stopped.
![Node](https://user-images.githubusercontent.com/90400315/215862195-9439bfa0-69c3-4dde-a678-fabf74e229d1.JPG)

**Comment by dguenther** [comment]
Closing this since the testnet has ended.
