### ISSUE TITLE
"ironfish logs"  dont output any thing

### ISSUE THREAD

**Issue by weekendfootballhappy** [iron-fish/ironfish#3231]
### What happened?

"ironfish logs"  dont output any thing

![image](https://user-images.githubusercontent.com/124109740/215921995-04cce71b-0b59-497c-81e6-8a53ded66c9d.png)

### Version

0.1.63 @ 693ff0f

### Debug output

```shell
root@49fbc84acc5c:/usr/src/app# date
Wed Feb  1 01:17:43 UTC 2023
root@49fbc84acc5c:/usr/src/app# ironfish logs
^C
root@49fbc84acc5c:/usr/src/app# date
Wed Feb  1 01:22:46 UTC 2023
root@49fbc84acc5c:/usr/src/app# ironfish status
Version              0.1.63 @ 693ff0f
```

### Graffiti

weekend.football

**Comment by holahula** [comment]
Closing - answered
