### ISSUE TITLE
"ironfish ceremony" dont get any respond

### ISSUE THREAD

**Issue by weekendfootballhappy** [iron-fish/ironfish#3232]
### What happened?

"ironfish ceremony" dont get any respond
![image](https://user-images.githubusercontent.com/124109740/215922963-c3ba7de8-3ffb-4bcf-8f9e-25b5dd08701b.png)

### Version

0.1.63 @ 693ff0f

### Graffiti

weekend.football

**Comment by hughy** [comment]
Closing this issue as complete. The trusted setup process was still in development when this issue was created. Please create a new issue if you're still having issues with `ceremony`
