### ISSUE TITLE
"ironfish  chain:asset" get error

### ISSUE THREAD

**Issue by weekendfootballhappy** [iron-fish/ironfish#3234]
### What happened?

"ironfish  chain:asset" get error
![image](https://user-images.githubusercontent.com/124109740/215924863-1c52ef68-dcb9-4a62-ba8f-e98c82165fa6.png)

### Version

0.1.63 @ 693ff0f

### Graffiti
weekend.football

**Comment by NullSoldier** [comment]
Fixed by https://github.com/iron-fish/ironfish/pull/3247
