### ISSUE TITLE
"ironfish chain:download" point Another node is using the database, waiting for that node to close. But there is just one node running.

### ISSUE THREAD

**Issue by weekendfootballhappy** [iron-fish/ironfish#3235]
### What happened?

A bug happened!
"ironfish chain:download" point Another node is using the database, waiting for that node to close.
 But there is just one node running.
![image](https://user-images.githubusercontent.com/124109740/215930743-1d4ae114-375c-429a-86ec-cb7ff02295b2.png)

### Version

0.1.63 @ 693ff0f

### Graffiti

weekend.football

**Comment by hughy** [comment]
If one node is running, then that node needs to close. `chain:download` requires *zero* nodes to be running before you run it because it needs to modify the underlying database
