### ISSUE TITLE
ironfish miners:mined is not a command

### ISSUE THREAD

**Issue by rdano89** [iron-fish/ironfish#3237]
### What happened?

Trying run the command to check for the mined hashes according to the CLI docs (https://ironfish.network/docs/onboarding/iron-fish-cli#miners), but i'm getting the following:
```
root@vmd107181:~# ironfish miners:mined
 ›   Warning: miners:mined is not a ironfish command.
Did you mean miners:start? [y/n]: 
```

### Version

ironfish/0.1.63 linux-x64 node-v18.13.0

### Graffiti

rdano

**Comment by Ryushka** [comment]
This command no longer exists, my PR #274 should delete it's description from the docs.

**Comment by hughy** [comment]
Resolved by https://github.com/iron-fish/website/pull/274
