### ISSUE TITLE
The node is running, but it is not reflected on the leaderboard.

### ISSUE THREAD

**Issue by jjungssang** [iron-fish/ironfish#3238]
### What happened?

The node is up and running, but it hasn't been reflected on the leaderboard since January 26th.
The points of Burn/Mint/Transfer are well reflected.
(Could you please reflect the points not reflected on the leaderboard?)

![image](https://user-images.githubusercontent.com/11862843/216012562-053d4b7e-494b-4641-80f6-eb1441861b11.png)

### Version

0.1.61 @ 009c85e

### Graffiti

jjungssang

**Comment by hughy** [comment]
Your node needs to be running the current version in order to earn uptime points. The current version is `0.1.63`

**Comment by hughy** [comment]
There's a one week grace period for updating to the latest version in order to earn points, but version `0.1.62` was released on January 19th
