### ISSUE TITLE
[Can't able to sent minted asset to dfc2679369551e64e3950e06a88e68466e813c63b100283520045925adbe59ca]

### ISSUE THREAD

**Issue by N0deverse** [iron-fish/ironfish#3242]
### What happened?

At the time of sending the minted asset with the command` ironfish wallet:send` it shows some unknown error: `Not enough unspent notes available to fund the transaction. Please wait for any pending transactions to be confirmed.`

<img width="877" alt="Screenshot 2023-02-01 at 9 25 27 PM" src="https://user-images.githubusercontent.com/123908451/216095107-1efd574a-5aea-415c-a673-62a69034d4e1.png">

### Version

 v0.1.63

### Debug output

```shell
root@vmi1151057:~#  ironfish debug
Iron Fish version                  0.1.63 @ 693ff0f
Iron Fish library                  0.0.40 @ 693ff0f
Operating system                   Linux x64
CPU model(s)                       AMD EPYC 7282 16-Core Processor
CPU threads                        8
RAM total                          29.39 GiB
Heap total                         4.00 GiB
Node version                       v18.13.0
ironfish in PATH                   true
Garbage Collector Exposed          false
Telemetry enabled                  true
Node name                          
Block graffiti                     Nodeverse
Account 966250 uuid                96625049-b6c7-427d-aadb-205967d93aa2
Account 966250 name                default
Account 966250 head hash           00000000000387fa017cbef8ce66f02d7dc6f88c5252ff3ef717e233f5a66272
Account 966250 head in chain       true
Account 966250 sequence            22487
```

### Graffiti

Nodeverse

**Comment by hughy** [comment]
When you run `ironfish wallet:transactions` do you see any with `pending` or `unconfirmed` status?

You may need to wait for those transactions to be confirmed before you can make another transaction. The reason is that your balance is made of 'notes' which are similar to physical cash. You can't have two transactions that are spending the same note.

**Comment by N0deverse** [comment]
According to the error, I checked the pending transaction, but there were no pending transactions; I could make the transaction after debugging my node.

**Comment by hughy** [comment]
#3515 adds calculation of 'available' balance: the amount that you can send in a transaction at the given time.
