### ISSUE TITLE
[wrong info in stats page on website]

### ISSUE THREAD

**Issue by mik-click** [iron-fish/ironfish#3253]
### What happened?

One place on personal page has wrong information about earned points - in this case uncounted Multi-Asset Mint. (a circle is drawn around it on a pic ) Interesting, that sum of all points is counted correctly. Transaction was submitted couple of days ago. Have a look on Png file.
![count_bug](https://user-images.githubusercontent.com/124210929/216173456-ca848377-e3b9-4ed4-b11b-95c6a59b35d4.png)

### Graffiti

fishlover

**Comment by hughy** [comment]
Thanks for noticing this! One of our database updates failed. I re-ran the job to update that table, so you should see the counts updated now.

Please reopen this issue if you notice this happening again!
