### ISSUE TITLE
wallet:rescan

### ISSUE THREAD

**Issue by omiDBaghi** [iron-fish/ironfish#3260]
### What happened?
after wallet:rescan
The time of all transactions is the same

![Untitled-1](https://user-images.githubusercontent.com/3645938/216316059-822dde1b-52c1-44c6-bce9-5389545334f5.png)

### Version

0.1.63 @ 693ff0f

### Graffiti

omiD

https://testnet.ironfish.network/users/30562

**Comment by hughy** [comment]
This will be resolved by #3230 after rescanning

**Comment by hughy** [comment]
Closing now that #3230 has been released in v0.1.65
