### ISSUE TITLE
Unable to continue any commands after command ironfish chain:download

### ISSUE THREAD

**Issue by Yatsenkoa320** [iron-fish/ironfish#3261]
### What happened?

A bug happened! 
Hi! could you help me. How can i continue after this command without closing active session?
Is it a bug? Thx
![2023-02-02_17-47-25](https://user-images.githubusercontent.com/117216789/216330423-44130a5f-82d6-4a74-86fb-44e87dbe1c55.png)

### Version

Ubuntu 22.04.1 LTS

### Graffiti

Yatsenko

**Comment by hughy** [comment]
It looks like `chain:download` is not able to run because you already have a node running: `Another node is using the database, waiting for that node to close.`

**Comment by hughy** [comment]
Closing the issue; marked as stale
