### ISSUE TITLE
wallet does not enforce max size limits on memo field

### ISSUE THREAD

**Issue by kim0** [iron-fish/ironfish#3262]
### What happened?

I could successfully send a transaction with memo field set to 101,000 characters as below
```
# ironfish wallet:send -a 0.00000001 --fee 0.00000001 \
--to dfc2679369551e64e3950e06a88e68466e813c63b100283520045925adbe59ca \
-i 4eb0354bd703ccf85f28a8d26c445b3f91202049f78a2bfc792966925b81fb21 \
-m "$(base64 -w0 ./node_modules/lodash/lodash.js | head -c 101000)"
```

Even if not all the data is being committed to the blockchain, the cli wallet should make it clear when/if the memo is being truncated

### Version

v0.1.63

### Graffiti

7oreya

**Comment by holahula** [comment]
I've created an internal ticket to handle this issue
