### ISSUE TITLE
The wallet:mint command argument is not parsed correctly.

### ISSUE THREAD

**Issue by 4mi1amai** [iron-fish/ironfish#3278]
### What happened?

A bug happened!
The wallet:mint command argument is not parsed correctly.
If I set the parameter --name=burn3 but application asks to fill "Enter the name for the new asset:" 
Also if I set argument without double dash -metadata=burn3 field metadata to fill **etadata=burn3** 
```
iron@:~$ ironfish wallet:mint -a 0.1 -f $IRON --name=burn3 -metadata=burn3 -o 0.00000001  -v
Connecting to /home/iron/.ironfish/ironfish.ipc
Enter the name for the new asset: burn4

You are about to mint Name: burn4 Metadata: etadata=burn3
0.10000000 plus a transaction fee of $IRON 0.00000001 with the account --name=burn3

* This action is NOT reversible *

Do you confirm (Y/N)?:
```
 
![image](https://user-images.githubusercontent.com/116466878/216617829-795cc390-ee88-4baf-bac2-550fb748164e.png)

### Version

0.1.62

### Debug output

```shell
Iron Fish version               0.1.62 @ 4ab43f3
Iron Fish library               0.0.39 @ 4ab43f3
Operating system                Linux x64
CPU model(s)                    Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz
CPU threads                     40
RAM total                       31.35 GiB
Heap total                      3.99 GiB
Node version                    v18.13.0
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       ir2
Block graffiti                  ir2
```

### Graffiti

ir2

**Comment by Ryushka** [comment]
-metadata works as -m etadata, 
Do you have an account called $IRON?It is variable in terminal AFAIK, it skips $IRON (maybe there's nothing loaded into that variable) and interprets --name=burn3 as argument of -f flag....

**Comment by 4mi1amai** [comment]
Yes, account $IRON there's

**Comment by 4mi1amai** [comment]
![image](https://user-images.githubusercontent.com/116466878/216648927-7fd8cb5c-827f-43ad-b1fb-8ff32e4b1b22.png)

**Comment by Ryushka** [comment]
your account is called iron why are you using variables for that? and use flags in the proper way with two dashes if it's long and not short...

**Comment by 4mi1amai** [comment]
This is a feature of the OS settings. 
Please see the following cases. If I execute:  
`1)  ironfish wallet:mint -a 0.1  -n burn3 --metadataburnMeta3 -o 0.00000001  -v`  I get error `Error: Unexpected argument: --metadataburnMeta3 `
`2) ironfish wallet:mint -a 0.1  -n burn3 -metadataburnMeta3 -o 0.00000001  -v` I get `You are about to mint Name: burn3 Metadata: etadataburnMeta3`

In two cases, the arguments are not set correctly, but in the first case we get an error and in the second we don't.
![image](https://user-images.githubusercontent.com/116466878/216723536-21885317-c886-48d7-890a-7b18f183f7b4.png)

**Comment by hughy** [comment]
Closing this issue as won't fix. It looks like the errors here are from arguments passed incorrectly based on your OS
