### ISSUE TITLE
unable to mint new asset

### ISSUE THREAD

**Issue by kumbumsheker** [iron-fish/ironfish#3290]
### What happened?

A bug happened! from yesterday to till now i am trying to mint new asset, yesterday i did 2 times of mint process and trxn hash also generated but asset not showing in wallet balance, and to day i checked in wallet balances its shows as pervious balance and , today i again try to mint but it says no available balances in wallet ,but i have 0.0623 ironfish in wallet. 

### Version

ubuntu22.04

**Comment by wd021** [comment]
can you show outputs and logs please

**Comment by kumbumsheker** [comment]
Now it's showing outstanding and minted, problem is solved

**Comment by kumbumsheker** [comment]
Awesome, thanks!
