### ISSUE TITLE
node set up, but not displayed properly in testnet.ironfish.network

### ISSUE THREAD

**Issue by githjo** [iron-fish/ironfish#3294]
### What happened?

I am running a node for a while already. When doing my weekly mint, burn, send assets I realized that the last time points were awarded is from 31.01. 

When checking ironfish status -f I get the following (which looks like node is running properly). 

Version              0.1.62 @ 4ab43f3
Node                 STARTED
Node Name            Eisenfisch
Block Graffiti       Eisenfisch
Memory               Heap: 422.04 MiB -> 458.57 MiB / 4.00 GiB (10.3%), RSS:   
1.27 GiB (8.1%), Free: 10.15 GiB (35.0%)
CPU                  Cores: 6, Current: 1.7%  
P2P Network          CONNECTED - In: 7.55 KB/s, Out: 12.73 KB/s, peers 45  
Mining               STARTED - 0 miners, 0 mined
Mem Pool             Count: 4195 tx, Bytes: 8.70 MiB
Syncer               IDLE - 2.79 blocks added/sec                              
Blockchain           00000000002e926c4ae4c00498f7a8bf99a200c9e841c8329e3f8859cdf
1a72b (26915), Since HEAD: 1h 47m (SYNCED)                                      
Accounts             00000000002e926c4ae4c00498f7a8bf99a200c9e841c8329e3f8859cdf
1a72b (26915)                                                                   
Telemetry            STARTED - 34455 <- 0 pending 
Workers              STARTED - 0 -> 0 / 5 - -0.02 jobs Δ, 3 jobs/s    

### Version

0.1.62

### Debug output

```shell
Database in use, skipping output that requires database.
Stop the node and run the debug command again to show full output.

Iron Fish version               0.1.62 @ 4ab43f3
Iron Fish library               0.0.39 @ 4ab43f3
Operating system                Linux x64
CPU model(s)                    AMD EPYC 7282 16-Core Processor
CPU threads                     6
RAM total                       15.63 GiB
Heap total                      4.00 GiB
Node version                    v18.13.0
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       Eisenfisch
Block graffiti                  Eisenfisch
```

### Graffiti

Eisenfisch

**Comment by hughy** [comment]
There is a one week grace period for updating your node before uptime points are no longer awarded. Version 0.1.63 was released on January 26th, so after February 3rd you needed to be on at least version 0.1.63 to earn points.

The current version is 0.1.65, released on February 5th.
