### ISSUE TITLE
wallet:transaction:index command doesn't work

### ISSUE THREAD

**Issue by Ryushka** [iron-fish/ironfish#3295]
### What happened?

Command doesn't work :
 ›   Error: Command wallet:transaction:index not found.

### Version

0.1.64

### Debug output

```shell
Iron Fish version               0.1.64 @ src
Iron Fish library               0.0.41 @ src
Operating system                Linux x64
CPU model(s)                    AMD Ryzen 9 3900X 12-Core Processor
CPU threads                     24
RAM total                       15.64 GiB
Heap total                      3.99 GiB
Node version                    v18.13.0
ironfish in PATH                true
Garbage Collector Exposed       true
Telemetry enabled               true
Node name                       PaRUSaI
Block graffiti                  PaRUSaI
Done in 2.28s.
```

### Graffiti

PaRUSaI

**Comment by Ryushka** [comment]
#3296

**Comment by hughy** [comment]
The command is `wallet:transaction`, have you had any issues running that one?

**Comment by Ryushka** [comment]
> The command is `wallet:transaction`, have you had any issues running that one?

I see now that i got it all wrong... When transaction command moved from wallet folder to transaction folder i thought that it must be launched as wallet:transaction:transaction
