### ISSUE TITLE
Transactions done but lead board points are not updating.

### ISSUE THREAD

**Issue by saitejasais** [iron-fish/ironfish#3300]
### What happened?

I am doing all the transactions mint, burn, send in my node. But my points are not updating in the testnet leadboard. 

### Graffiti

saitejasais

**Comment by satya-jugran** [comment]
I am also facing same issue. Hosted node hours are not updating in the leaderboard. 
Also, asset minting is not working even though it is returning the hash as output.

Logs below:
-----------------------------------

Do you want to create a new asset (Y/N)?: Y
Enter the name for the new asset: satyaj3
Enter metadata for the new asset: satyaj3 official
Enter the amount to mint in the custom asset: 100000
Enter the fee amount in $IRON (min: 0.00000001) [0.00000001]: 0.00000001

You are about to mint Name: satyaj3 Metadata: satyaj3 official
100000.00000000 plus a transaction fee of $IRON 0.00000001 with the account default

* This action is NOT reversible *

Do you confirm (Y/N)?: Y
Creating the transaction: [████████████████████████████████████████] 100% | ETA: 0s

Minted asset satyaj3 from default
Asset Identifier: f405658d0466602da078f8df2c4e2e5b3ca3341cd6068bdba2e542c658b569bc
Value: 100000.00000000

Transaction Hash: ab67db5c1fd4dad0aabc21b9d89dffc9955a75b7e5ed74e0506f79ccedb889b0

Find the transaction on https://explorer.ironfish.network/transaction/ab67db5c1fd4dad0aabc21b9d89dffc9955a75b7e5ed74e0506f79ccedb889b0 (it can take a few minutes before the transaction appears in the Explorer)

**Comment by hughy** [comment]
@saitejasais please ensure that the name of your custom asset is exactly the same as your graffiti on the testnet leaderboard

**Comment by hughy** [comment]
Closing as stale
