### ISSUE TITLE
Transaction Pending!

### ISSUE THREAD

**Issue by omiDBaghi** [iron-fish/ironfish#3302]
### What happened?

All transactions are pending!
![Untitled](https://user-images.githubusercontent.com/3645938/216818340-42c529e7-52ab-4221-9312-00021673ba8e.png)
https://testnet.ironfish.network/users/30562

### Version

0.1.63 @ 693ff0f

### Debug output

```shell
Iron Fish version               0.1.63 @ 693ff0f
Iron Fish library               0.0.40 @ 693ff0f
Operating system                Linux x64
CPU model(s)                    AMD EPYC Processor
CPU threads                     8
RAM total                       15.26 GiB
Heap total                      2.00 GiB
Node version                    v18.13.0
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       omiD
Block graffiti                  omiD
```

### Graffiti

omiD

**Comment by hughy** [comment]
@omiDBaghi are your accounts synced with the chain? Can you share the outputs of `ironfish status` and `ironfish wallet:status`?
