### ISSUE TITLE
Incorrect calculation points on site for graffiti

### ISSUE THREAD

**Issue by wowss** [iron-fish/ironfish#3303]
### What happened?

Incorrect calculation points on site for graffiti

![image](https://user-images.githubusercontent.com/89159322/216824306-7fdf655e-3611-4f12-a0a8-4c6f89dd5026.png)

![image](https://user-images.githubusercontent.com/89159322/216824335-f2ad2bc0-910a-4b5d-9e4a-531d4b5cf94d.png)

![image](https://user-images.githubusercontent.com/89159322/216824347-6e05e78f-793d-4deb-b8f7-578870272b29.png)

400 points doesn't calc

### Version

0.1.64

### Graffiti

wow_sss

**Comment by hughy** [comment]
Thanks for noticing this! One of our database updates failed. I re-ran the job to update that table, so you should see the counts updated now.

Please reopen this issue if you notice this happening again!
