### ISSUE TITLE
Node running but lead board points are not updating

### ISSUE THREAD

**Issue by satya-jugran** [iron-fish/ironfish#3305]
### What happened?

Hosted node hours are not updating in the leaderboard. This is happening since 3rd of Feb

Also, asset minting is not working even though it is returning the hash as output (not showing assets in balance even after hours of waiting).

### Version

0.1.62 @ 4ab43f3

### Relevant log output

```shell
ironfish wallet:mint
Do you want to create a new asset (Y/N)?: Y
Enter the name for the new asset:
Enter the name for the new asset: satyaj
Enter metadata for the new asset: satyaj 3
Enter the amount to mint in the custom asset: 10000
Enter the fee amount in $IRON (min: 0.00000001) [0.00000001]: 0.00000001

You are about to mint Name: satyaj Metadata: satyaj 3
10000.00000000 plus a transaction fee of $IRON 0.00000001 with the account default

This action is NOT reversible *
Do you confirm (Y/N)?: Y
Creating the transaction: [████████████████████████████████████████] 100% | ETA: 0s

Minted asset satyaj from default
Asset Identifier: 4b199b1bd8dad9403b082ec16c91f20467f27c0a9209034dc0a92cbe5a422590
Value: 10000.00000000

Transaction Hash: 4e876c9c53d5a0a8e23b3938b30febfac1c53ff52a2b5cd45f774334802315b9

Find the transaction on https://explorer.ironfish.network/transaction/4e876c9c53d5a0a8e23b3938b30febfac1c53ff52a2b5cd45f774334802315b9 (it can take a few minutes before the transaction appears in the Explorer)
```

### Graffiti

satyaj

**Comment by hughy** [comment]
There is a one week grace period for updating your node before uptime points are no longer awarded. Version `0.1.63` was released on January 26th, so after February 3rd you needed to be on at least version `0.1.63` to earn points.

The current version is `0.1.65`, released on February 5th.

**Comment by satya-jugran** [comment]
I updated with the new version of ironfish. Things are working fine now and reflecting on dashboard.
However, some of my reward points are missed because of not timely upgrading the latest version and I have not been notified via email as well. This was unfortunate. Nonetheless, thanks for guiding.
