### ISSUE TITLE
[ironfish  blockchain did not sync for severl days]

### ISSUE THREAD

**Issue by dboyxyz** [iron-fish/ironfish#3312]
### What happened?

the dash board of ironfish testnet show:  I miss some points of node point.
I use the command "ironfish status" in my node, and find my Blockchain did not sync for severl days.

And I check the dash board yesterday, it looks like work fine.（looks like a fallback happened）

![2023-02-06 13-15-02屏幕截图](https://user-images.githubusercontent.com/14068284/216889166-932b8b1e-9b13-4686-9360-a31314b3c6aa.png)

I try to restart the docker container fo ironfish, it seems to sync
![2023-02-06 13-13-49屏幕截图](https://user-images.githubusercontent.com/14068284/216889049-3891d98c-3799-410c-9e85-56ac5b57e3fa.png)

### Version

0.1.62

### Debug output

```shell
Iron Fish version               0.1.62 @ 4ab43f3
Iron Fish library               0.0.39 @ 4ab43f3
Operating system                Linux x64
CPU model(s)                    Intel(R) Xeon(R) Platinum 8163 CPU @ 2.50GHz
CPU threads                     2
RAM total                       1.93 GiB
Heap total                      971.43 MiB
Node version                    v18.12.1
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       dboyxyz
Block graffiti                  dboyxyz
```

### Graffiti

dboyxyz

**Comment by hughy** [comment]
Were you able to get your node to sync?
