### ISSUE TITLE
the beta-node doesn't sync, neither mining or showing balance

### ISSUE THREAD

**Issue by alterkahn** [iron-fish/ironfish#332]
Hello, I'm running Ironfish node version 0.1.0 and it stopped mining and syncing from Aug 05. What should I do to fix it? Already tried to restart both miner and node a couple of times but it didn't help, though both are active. My node name is: alterkahn

![Снимок экрана 2021-08-17 в 17 45 32](https://user-images.githubusercontent.com/67752860/129748958-16c608da-91dc-4050-a18f-f5c1f391636b.png)
![Снимок экрана 2021-08-17 в 17 36 35](https://user-images.githubusercontent.com/67752860/129748963-0d261119-aa8b-4af4-834b-884842b84739.png)
![Снимок экрана 2021-08-17 в 17 38 24](https://user-images.githubusercontent.com/67752860/129748967-d2105d55-04ca-4905-918e-631df1206244.png)
![Снимок экрана 2021-08-17 в 17 51 32](https://user-images.githubusercontent.com/67752860/129748969-08c44d7d-c6c9-4cc0-b3c0-9549342bc37d.png)

**Comment by dguenther** [comment]
We're not currently running a beta test, so we haven't been consistently updating the beta node -- I'd recommend using the main release unless we make an announcement in Discord that we're doing a beta test.
