### ISSUE TITLE
rescan

### ISSUE THREAD

**Issue by DIDAO-id** [iron-fish/ironfish#3328]
### What happened?

after ironfish wallet:rescan --reset , the status is always in 1.
Accounts             SCANNING - 1 / 30481

and balance is not recovered.

### Version
Iron Fish version               0.1.65 @ f3fdfa1
Iron Fish library               0.0.42 @ f3fdfa1
Operating system                Linux x64

### Graffiti

michael_zhao

**Comment by LinLL** [comment]
I had got the same problem

**Comment by wd021** [comment]
are you keeping the scanning process running in the background? what does the `Scanning Blocks:..` text  show?

**Comment by DIDAO-id** [comment]
After upgrade to  0.1.67, it's working fine now.
