### ISSUE TITLE
notes not spent

### ISSUE THREAD

**Issue by DIDAO-id** [iron-fish/ironfish#3330]
### What happened?

wallet:notes always show x for the transaction.
Amount     Asset Name   Asset Id     Memo                             Sender From Transaction                                                 Spent 
 ────────── ──────────── ──────────── ──────────────────────────────── ────── ──────────────────────────────────────────────────────────────── ───── 
 0.10000000 michael_zhao cfe88e2568d…                                  cbfb9… 9b2ce865cfc1286464d49ef8f8c893a5247ccfc62454f4ee4377341025e33fee x     

but the trx were all in  confirmed status
    Timestamp                   Status      Type    Hash                            Expiration Fee Paid ($IRON) Asset                Net Amount      
 ── ─────────────────────────── ─────────── ─────── ─────────────────────────────── ────────── ──────────────── ──────────────────── ─────────────── 
    2/7/2023 2:21:45 PM GMT+8   confirmed   send    d6006a9462b91d03db1219bc0608e5… 30531      0.00000001       michael_zhao      (… -0.10000000     

### Debug output

```shell
Iron Fish version               0.1.65 @ f3fdfa1
Iron Fish library               0.0.42 @ f3fdfa1
Operating system                Linux x64
CPU model(s)                    AMD Ryzen 9 3900X 12-Core Processor
CPU threads                     24
RAM total                       31.34 GiB
Heap total                      4.00 GiB
Node version                    v18.14.0
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       michael_zhao
Block graffiti                  michael_zhao
```

### Graffiti

michael_zhao

**Comment by hughy** [comment]
Note that the transaction hash in the output for `wallet:notes` is the hash of the transaction that you received the note from.

The `Spent` column shows whether you have spent that note in another transaction.
