### ISSUE TITLE
Send Asset. Low fee notification when there is enough gas on your balance

### ISSUE THREAD

**Issue by RomulRS** [iron-fish/ironfish#3344]
### What happened?

ironfish wallet:balances
RomulRS    5a2e2979a378c91aea2f270eeecf4ba2da0e50e69130fdb4498c261ad13c90ee 3000.00000000     
$IRON      d7c86706f5817aa718cd1cfad03233bcd64a7789fd9422d3b17af6823a7e6ac6 **0.00000007**        

ironfish wallet:send -a 1000 -f RomulRS -i 5a2e2979a378c91aea2f270eeecf4ba2da0e50e69130fdb4498c261ad13c90ee -t dfc2679369551e64e3950e06a88e68466e813c63b100283520045925adbe59ca
? Select the fee you wish to use for this transaction **low: 0.00000001 IRON**

### Graffiti

RomulRS

**Comment by hughy** [comment]
The `low` is to describe the fee relative to other fees being used on the network and does not relate to your balance.

This will be clarified by #3324 in the next release
