### ISSUE TITLE
Transactions have pending when I send more than the property balance

### ISSUE THREAD

**Issue by pmhieu111** [iron-fish/ironfish#3345]
### What happened?

A bug happened!
My command is pending and can't Mint or Burn, send anything anymore
![image](https://user-images.githubusercontent.com/54319153/217433037-9ca9b8e1-a028-453e-bcc2-5a6635877c35.png)
![image](https://user-images.githubusercontent.com/54319153/217433066-0876d2e0-0e9c-4b7d-9968-f411679ccebb.png)

### Version

v0.1.65

### Debug output

```shell
➜  ~ ironfish debug 
Database in use, skipping output that requires database.
Stop the node and run the debug command again to show full output.

Iron Fish version               0.1.65 @ f3fdfa1
Iron Fish library               0.0.42 @ f3fdfa1
Operating system                Linux x64
CPU model(s)                    AMD EPYC 7282 16-Core Processor
CPU threads                     4
RAM total                       7.77 GiB
Heap total                      2.00 GiB
Node version                    v18.13.0
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       zMH
Block graffiti                  zMH
```

### Graffiti

zMH

**Comment by hughy** [comment]
Your accounts have not finished scanning the chain. Based on the output of the `status` command your local chain is at block 31830, but your accounts have only scanned blocks up to 12360.

**Comment by pmhieu111** [comment]
> Your accounts have not finished scanning the chain. Based on the output of the `status` command your local chain is at block 31830, but your accounts have only scanned blocks up to 12360.

 So now how do I continue? Can I cancel that order?

**Comment by hughy** [comment]
You need to keep your node running to allow the wallet to continue scanning the chain.

Transactions can't be canceled, but they will expire if they aren't mined before their expiration sequence.

**Comment by pmhieu111** [comment]
> You need to keep your node running to allow the wallet to continue scanning the chain.
> 
> Transactions can't be canceled, but they will expire if they aren't mined before their expiration sequence.

I got it. Thanks sir
