### ISSUE TITLE
Confirmed / Unconfirmed / Pending balances are all same

### ISSUE THREAD

**Issue by pratikgarg1122** [iron-fish/ironfish#3347]
### What happened?

Here confirmed / unconfirmed / pending balances all are same. Its not the expected results. 

<img width="1455" alt="image" src="https://user-images.githubusercontent.com/123742309/217515230-3e172a73-272f-4153-973e-d6d770f4b9d6.png">

### Version

v0.1.65

### Debug output

```shell
Iron Fish version               0.1.65 @ f3fdfa1
Iron Fish library               0.0.42 @ f3fdfa1
Operating system                Linux x64
CPU model(s)                    DO-Premium-AMD
CPU threads                     4
RAM total                       7.76 GiB
Heap total                      2.00 GiB
Node version                    v18.13.0
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       pratikmbm1122
Block graffiti                  pratikmbm1122
```

### Relevant log output

```shell
Account: default
 Asset Name    Asset Id                                 Confirmed Balance Unconfirmed Balance Pending Balance Head Hash                                                        Head Sequence 
 ───────────── ──────────────────────────────────────── ───────────────── ─────────────────── ─────────────── ──────────────────────────────────────────────────────────────── ───────────── 
 pratikmbm1122 74dc4d30c0fecf181ed50cc9fee42f4c76edbb6… 890.00000000      890.00000000        890.00000000    00000000002c72edeed7dfdd2ab58cb144d6d2117ec761573d7974916857a176 32237         
 silipjacknat  95b4464ae183d619a481e24c8bc8eda893b9bc1… 12.00000000       12.00000000         12.00000000     00000000002c72edeed7dfdd2ab58cb144d6d2117ec761573d7974916857a176 32237         
 $IRON         d7c86706f5817aa718cd1cfad03233bcd64a778… 0.14729977        0.14729977          0.14729977      00000000002c72edeed7dfdd2ab58cb144d6d2117ec761573d7974916857a176 32237
```

### Graffiti

pratikmbm1122

**Comment by hughy** [comment]
Can you explain more about the differences you're expecting to see? Do you have any pending or unconfirmed transactions that would cause the balances to be different?

Can you also share the output of `ironfish wallet:balances --explain`?

**Comment by pratikgarg1122** [comment]
Ideally pending/unconfirmed balance should be zero. Because no pending/unconfirmed txs.

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/123742309/217739504-e31fb04a-78b1-4b7a-9b1b-8d28a22de7ca.png">

**Comment by hughy** [comment]
We've typically thought about the different balances this way:

- Unconfirmed: balance including all on-chain transactions
- Confirmed: balance including only 'confirmed' on-chain transactions
- Pending: balance including all on-chain and pending transactions
- Available: balance available to spend

We could change balances to include only notes/transactions of that type if that's clearer.
