### ISSUE TITLE
Transaction pending for several hours

### ISSUE THREAD

**Issue by saitejasais** [iron-fish/ironfish#3348]
### What happened?

I have minted an Asset. The transaction status is showing as pending from several hours. I can't able to do another transaction because of that pending transaction.

### Graffiti

saitejasais

**Comment by hughy** [comment]
Can you post the outputs of `ironfish status` and `ironfish wallet:status`?

Transactions may remain in a pending state if your node or your account are not synced with the chain.

**Comment by saitejasais** [comment]
Version              0.1.64 @ aaba8cb
Node                 STARTED
Node Name            saitejasais
Block Graffiti       saitejasais
Memory               Heap: 204.46 MiB -> 231.96 MiB / 1.99 GiB (10.0%), RSS: 1.14 GiB (14.8%), Free: 6.16 GiB (20.6%)
CPU                  Cores: 4, Current: 314.4%
P2P Network          CONNECTED - In: 53.39 KB/s, Out: 3.36 KB/s, peers 50
Mining               STARTED - 1 miners, 0 mined
Mem Pool             Count: 838 tx, Bytes: 1.76 MiB
Syncer               SYNCING - 0.06 blocks synced/sec, 0.57 blocks downloaded/sec, 0.03 blocks added/sec
Blockchain           0000000000247b2026ea3f843a655aa41340ad0d5df62a5abba9f54d3ee844bc (32660), Since HEAD: 8m 12s (SYNCED)
Accounts             000000000011c7f929f22d3804ab09b6f7460072b8a5b317af18e7d25b955bc0 (29601)
Telemetry            STARTED - 35924 <- 0 pending
Workers              STARTED - 500 -> 3 / 3 - 0.01 jobs Δ, 0.93 jobs/s

**Comment by hughy** [comment]
It looks like your accounts are a few thousand blocks behind your chain (29601 vs 32660). Any transactions that may have been added to the chain on one of those blocks will have a pending status.

Your accounts will catch up to the chain over time as your node runs

**Comment by saitejasais** [comment]
Still it is showing the same... Because of that I'm not getting any points for the transactions... It happened in week 3 also

**Comment by hughy** [comment]
Were you able to get your node and accounts synced?

**Comment by holahula** [comment]
Closing, lack of response
