### ISSUE TITLE
Points are not crediting for Mint/Burn n Send Task

### ISSUE THREAD

**Issue by pratikgarg1122** [iron-fish/ironfish#3361]
### What happened?

Lot many users completed Mint/Burn n Send tasks but points are not reflecting in the UI.

Followed below checklist -
1. Ironfish version is v0.1.65
2. Asset name is same as graffiti
3. Nodes are fully synced. 
4. Transactions are getting completed in the backend. 

### Version

v0.1.65

### Graffiti

pratikmbm1122

**Comment by NullSoldier** [comment]
Thanks this was resolved when we rolled back the testnet.
