### ISSUE TITLE
Transactions "stuck" for over 12-hours - cannot make any new ones (e.g. send asset)

### ISSUE THREAD

**Issue by RaeesC** [iron-fish/ironfish#3369]
### What happened?

A bug happened!

<img width="1317" alt="Screenshot 2023-02-09 at 21 35 25" src="https://user-images.githubusercontent.com/32003183/218042916-4000e94e-61a1-4ff3-9b21-649b64a806ea.png">

Transactions "stuck" for over 12-hours - cannot make any new ones (e.g. send asset)

Furthermore, the "number of assets" changed midway through transactions (see screenshot) from 7 to 6.  This may have been due to a "burn" transaction completing midway, but irrespective 12-hours later I cannot still do any new transactions of "send asset".

### Graffiti

https://testnet.ironfish.network/users/231241

**Comment by hughy** [comment]
Can you share the output of `ironfish status` and `ironfish wallet:status`?

Note that you need to sync the chain to both you local copy of the chain and to your wallet database to see the updated status of transactions.

**Comment by RaeesC** [comment]
Sure - see attached.
<img width="1029" alt="Screenshot 2023-02-10 at 16 58 57" src="https://user-images.githubusercontent.com/32003183/218151038-40f8e634-8af6-4926-8c53-013a513f487a.png">

**Comment by hughy** [comment]
Thanks! It looks like your chain and wallet are synced.

Could you also share `ironfish wallet:balances` and `ironfish wallet:transactions`?

**Comment by RaeesC** [comment]
<img width="1028" alt="Screenshot 2023-02-10 at 17 02 27" src="https://user-images.githubusercontent.com/32003183/218151897-dede8625-3afd-4d94-a4f2-b37983fe302a.png">

**Comment by hughy** [comment]
It looks like your wallet is out of $IRON! You need $IRON to pay transaction fees for any transaction.

You can use `ironfish faucet` to get more
