### ISSUE TITLE
Users not able to login 

### ISSUE THREAD

**Issue by pratikgarg1122** [iron-fish/ironfish#3370]
### What happened?

Lot many users reported the bug that they are not able to login to the ironfish port. 

https://discord.com/channels/771503434028941353/771503434028941356/1073533035011645521
https://discord.com/channels/771503434028941353/771503434028941356/1073534191272218684
and so on 

Please check

### Version

v0.1.65

### Graffiti

pratikmbm1122

**Comment by Ola1108** [comment]
I can't login to the ironfish user profile

**Comment by Ola1108** [comment]
![Uploading Screenshot_20230210_111337_Chrome.jpg…]()
