### ISSUE TITLE
Isuue with an old wallet (from previous versions) with 0.1.66 

### ISSUE THREAD

**Issue by lionff** [iron-fish/ironfish#3371]
### What happened?

I exported my wallet before do update to 0.1.66 
The node didnt start after update 
and I did
```
sudo systemctl stop ironfishd
rm -rf $HOME/.ironfish/databases/wallet
ironfish migrations:start
ironfish wallet:import
sudo systemctl restart ironfishd
```

Node started but it has stopped and disconnected once in 1 minute and crashed after

![photo_2023-02-10_18-36-54 - iron](https://user-images.githubusercontent.com/79597699/218132033-e7ba912c-0f3e-42f1-a1c8-d5f27dbfc2bd.jpg)

Only deleting the wallet and generating a new one helps.

### Version

0.1.66 

### Graffiti

okayko

**Comment by wd021** [comment]
can you show the actual error

**Comment by holahula** [comment]
Closing due to staleness. If the issue persists in versions `1.0.0+` - please file a new issue
