### ISSUE TITLE
transactions pending for more than 24 hours [transaction stuck]

### ISSUE THREAD

**Issue by kevin486** [iron-fish/ironfish#3383]
### What happened?

# I made a coup of transactions  more than 24 hours ago, but all got stuck. 

## screen shot of  wallet:transactions 

<img width="1562" alt="image" src="https://user-images.githubusercontent.com/6076501/218235264-8e0c8cac-2189-414c-9cb9-43796aa05261.png">

## screen shot of  wallet:balance 
<img width="366" alt="image" src="https://user-images.githubusercontent.com/6076501/218235321-062b3dab-5425-4be9-9371-788d33aae3e5.png">

### ironfish version 
name       ironfish
version    0.1.67
git        bba0453
runtime    node/18.14.0

* the transactions were sent in older version of ironfish.

### transactions are confirmed on scanner 
- Here are a part of pending transactions on above transactions:

f0feec348a11519880336e702419f2810c06b9691b24575939f58a27610c2855
2e4ce7de6986612c31791f7e5cdec9eaa4d2176544aeb5f4c0d9e690a59ea62b
4a677171bd643e599d11ad673343ea44e29e8629248d3eaf0e0b83089f6bb88e
74a5b4de5c988d7f0c53c25baa42324edb605907afcf9cc94383999868e5c63c
aa6a94c0b6d966d0392a9933f4c8067cb2b0e68ef4217c9e2a5a9c62b1f4ac7b
503290882e90d444ec685c62b6d90f739f9bef1b4d802ff821cd74f792b7ca17
ad30b9ef3b71268b69ad0d9847f5963f223fbf6840510c760b068cca95d744a4
26fb68df20cc8b05704faef61be8171080f61bfe3f61c50944ecb4c47c911886
364080d171c124731dbf50cc4a0b9a9ddb7bf35afac21e0a3c0aa85150ef6484
b6b323abac63f81652f33c08c9f2c52d7be54ca020d6011273c8dab04483731c
83cd7e9d11125bfb4b29ac80d660882a709cc4fa437528289435bffd0328961e
472395403c48aaf45d949e77f74aced8f25dbc2c1497054a15de71f3e0a37975
2284e608252cd9a6630cdbdd794f8ee78623f90af1152e8da23e7ddc22da1064

### Version

0.1.67

### Status 

```
root@ifish01:~/fish# ironfish status
Version              0.1.67 @ bba0453
Node                 STARTED
Node Name            
Block Graffiti       kevin486
Memory               Heap: 104.29 MiB -> 228.74 MiB / 2.00 GiB (5.1%), RSS: 866.11 MiB (11.3%), Free: 6.32 GiB (15.8%)
CPU                  Cores: 4, Current: 237.8%
P2P Network          CONNECTED - In: 26.67 KB/s, Out: 10.74 KB/s, peers 49
Mining               STARTED - 0 miners, 0 mined
Mem Pool             Count: 44 tx, Bytes: 211.60 KiB
Syncer               IDLE - 2.50 blocks added/sec
Blockchain           000000000004c4da3547e8d4a0dfe303a1afac0dee46473c2fc6250ce43a7ac7 (36144), Since HEAD: 49s 525ms (SYNCED)
Accounts             SCANNING - 33767 / 34205
Telemetry            STARTED - 1028 <- 6 pending
Workers              STARTED - 7 -> 3 / 3 - 0.31 jobs Δ, 1052.93 jobs/s
```

### Debug output

```shell
Database in use, skipping output that requires database.
Stop the node and run the debug command again to show full output.

Iron Fish version               0.1.67 @ bba0453
Iron Fish library               0.0.44 @ bba0453
Operating system                Linux x64
CPU model(s)                    Intel(R) Xeon(R) Platinum 8269CY CPU @ 2.50GHz
CPU threads                     4
RAM total                       7.50 GiB
Heap total                      2.00 GiB
Node version                    v18.14.0
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       
Block graffiti                  kevin486
```

### Graffiti

kevin486

**Comment by hughy** [comment]
It looks like your wallet is still scanning the chain:
```
Accounts             SCANNING - 33767 / 34205
```

Since all of your pending transactions have expiration sequences greater than 34205 it's likely that your wallet has not yet scanned any block that may include those transactions.
