### ISSUE TITLE
[issue name]Transaction verification error and delay

### ISSUE THREAD

**Issue by ankuba2609** [iron-fish/ironfish#3384]
### What happened?

I performed desired tasks for getting points ( claiming faucet, mint, burn and send ) but I didn't get any points. Then I performed the same task again and till now my points are not showing. Node is running for 24 hrs.
![Ironfish ankuba2609](https://user-images.githubusercontent.com/124869257/218243967-e8f4a7e4-81b4-49b5-bd89-eb42fe259c93.PNG)

### Debug output

```shell
root@vm978084:~# ironfish debug / yarn start debug
 ›   Error: Unexpected arguments: /, yarn, start, debug
 ›   See more help with --help
```

### Relevant log output

```shell
root@vm978084:~# ironfish wallet:balances
Account: default
 Asset Name Asset Id                                         Confirmed Balance
 ────────── ──────────────────────────────────────────────── ─────────────────
 ankuba2609 0a6ec539a818c49ca52d6315bc23242c8660e652d5aeac2… 19960.00000000
 $IRON      d7c86706f5817aa718cd1cfad03233bcd64a7789fd9422d… 0.26328272
```

### Graffiti

ankuba2609

**Comment by wd021** [comment]
are you sure you registered for an account with the graffiti? i don't see any search results for ankuba2609 on the leaderboard.

**Comment by holahula** [comment]
Closing - testnet is over
