### ISSUE TITLE
Error migrations and error upgrade start

### ISSUE THREAD

**Issue by AntonMatveychuk** [iron-fish/ironfish#3389]
### What happened?

My node is working and synchronized, but I can't export my wallet, it also doesn't import the wallet correctly, after I import the wallet, the address is correct, but the balance on the wallet is 0, although it should have more than 0 iron tokens, also problems with migration and upgrading the node, it started after updating the node to version 0.1.67

### Version

Iron Fish v0.1.67

### Debug output

```shell
Iron Fish version               0.1.67 @ bba0453
Iron Fish library               0.0.44 @ bba0453
Operating system                Linux x64
CPU model(s)                    AMD EPYC 7282 16-Core Processor
CPU threads                     6
RAM total                       15.63 GiB
Heap total                      4.00 GiB
Node version                    v18.14.0
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       matvey2705
Block graffiti                  matvey2705
```

### Graffiti

matvey2705

**Comment by ygao76** [comment]
migration issue fixed in new version.
