### ISSUE TITLE
[ironfish upgrade error]

### ISSUE THREAD

**Issue by olaideabimbola** [iron-fish/ironfish#3391]
### What happened?

A bug happened!i upgrade my npm version to 19.0 but now i get error when upgrading ironfish
when i was on npm version 18, each time i upgrade ironfish to latest version 0.1.67 on my ubuntu system, it doesnt upgrade, i keep on getting same old version 0.1.65.
But now i upgrade npm to version 19.0.1 and try to upgrade ironfish, i am getting error
![image](https://user-images.githubusercontent.com/83757245/218273849-acd65ab3-1023-412b-8d2f-ec30da70e016.png)

**Comment by cyberkd** [comment]
Checked error occurs only on 20.04 Ubuntu on 22.04 LTS there are no errors. Apparently due to an incorrect update of Node.js

**Comment by dguenther** [comment]
It looks like you're running Node.js 19, but we only support Node.js 18. Give it another try on Node.js 18 and see if it works!
