### ISSUE TITLE
after upgrade issue with import wallet

### ISSUE THREAD

**Issue by AntonMatveychuk** [iron-fish/ironfish#3392]
### What happened?

After I updated the version of my node to 0.1.67, I wanted to create an export file for further downloading, but I got an error and could not export my private keys

### Version

Iron Fish v0.1.67

### Graffiti

matvey2705

**Comment by wd021** [comment]
the export method got update. it returns a bech32 string by default, if you still want the JSON output, use `--json` flag. will need to update the docs to reflect this
