### ISSUE TITLE
I did not display the balance of my tokens on the wallet

### ISSUE THREAD

**Issue by AntonMatveychuk** [iron-fish/ironfish#3393]
### What happened?

after I updated the version of my node to 0.1.67, I did not display the balance of my tokens on the wallet, this is the result I gave, I will attach a link to the screenshot
https://discord.com/channels/771503434028941353/816795916627345450/1074229850405097533

### Version

Iron Fish v0.1.67

### Graffiti

matvey2705

**Comment by hughy** [comment]
Did this issue get resolved, or do you still not see any balances?

**Comment by holahula** [comment]
Closing, lack of response
