### ISSUE TITLE
[issue name] Node is running but the point is not updated in leaderboard

### ISSUE THREAD

**Issue by hungqlam** [iron-fish/ironfish#3395]
### What happened?

My node is running for 2 days but it has not updated point on leaderboard 
<img width="867" alt="Screenshot 2023-02-12 090652" src="https://user-images.githubusercontent.com/98580130/218325656-e31620a2-6530-418f-8773-20286e4265cd.png">
<img width="898" alt="Screenshot 2023-02-12 090756" src="https://user-images.githubusercontent.com/98580130/218325726-4368dcad-8667-4dd3-ab9f-4e7b12030274.png">

### Version

0.1.63

**Comment by hughy** [comment]
Your node is running an older version. You need to update to the latest version to receive uptime points.

**Comment by lyonsstar** [comment]
> Your node is running an older version. You need to update to the latest version to receive uptime points.

How can I update the node on vps?
