### ISSUE TITLE
Cant send assets[

### ISSUE THREAD

**Issue by undertucke** [iron-fish/ironfish#3397]
### What happened?

A bug happened! 
Cant send assets
when I'am wright : ironfish wallet:send . Was a new NodeError (node:internal/errors:399:5)

![Снимок экрана (302)](https://user-images.githubusercontent.com/124922497/218342487-c5539b38-b8a5-4f6c-92d9-b90e2d038a0c.png)

at new NodeError (node:internal/errors:399:5)

### Version

0.1.67

### Debug output

```shell
Iron Fish version               0.1.67 @ bba0453
Iron Fish library               0.0.44 @ bba0453
Operating system                Linux x64
CPU model(s)                    Intel(R) Xeon(R) E-2136 CPU @ 3.30GHz
CPU threads                     12
RAM total                       31.12 GiB
Heap total                      4.00 GiB
Node version                    v18.14.0
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       undertucker
Block graffiti                  undertucker
```

### Relevant log output

Added block to fork seq: 38723, head-seq: 38723, hash: 00000...cfb58, head-hash: 00000...fc40e, work: 171544502991168898, head-work: 171544502991168898, work-diff: 0

### Graffiti

undertucker

**Comment by ygao76** [comment]
Can you paste the send command you are trying to run here?

**Comment by undertucke** [comment]
Hello,

 ironfish wallet:send

**Comment by wd021** [comment]
your node and status have different versions. restart your node.
