### ISSUE TITLE
Can't stop Node

### ISSUE THREAD

**Issue by undertucke** [iron-fish/ironfish#3398]
### What happened?

I am wright stop node
And I have this ansfer - Cannot connect to your node, start your node first.
![Снимок экрана (305)](https://user-images.githubusercontent.com/124922497/218342871-8c88cc18-f2e0-46bf-a796-2225dc30aa18.png)

### Version

0.1.67

### Debug output

```shell
Iron Fish library               0.0.44 @ bba0453
Operating system                Linux x64
CPU model(s)                    Intel(R) Xeon(R) E-2136 CPU @ 3.30GHz
CPU threads                     12
RAM total                       31.12 GiB
Heap total                      4.00 GiB
Node version                    v18.14.0
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       undertucker
Block graffiti                  undertucker
```

### Graffiti

undertucker

**Comment by hughy** [comment]
`Cannot connect to your node, start your node first.` indicates that the node has stopped.

We made changes in #3641 to make the output of the stop command clearer.
