### ISSUE TITLE
Transactions do not appear in the explorer

### ISSUE THREAD

**Issue by Yuramazyrenko** [iron-fish/ironfish#3399]
### What happened?

I try several times to send a transaction, it is sent, but then it doesn't show up in the explorer after a long period of time. The screenshots are examples of transactions. 
<img width="1552" alt="CleanShot 2023-02-13 at 00 41 09@2x" src="https://user-images.githubusercontent.com/94488458/218347338-f41a0b43-ac8a-41d5-8d09-5e0b08ed2181.png">

Transaction Hash: 15b0fd5657123a837ce34b6a21fd9ff6816545632e665e24b802c3af165860c9
Transaction Hash: 8cd3970f05e6aa219ac01de5d4150d687e358e8aa8793a58e5566447a4979d7c

### Version

 0.1.67 @ bba0453

### Debug output

```shell
Iron Fish version               0.1.67 @ bba0453
Iron Fish library               0.0.44 @ bba0453
Operating system                Linux x64
CPU model(s)                    AMD Ryzen 5 3600 6-Core Processor
CPU threads                     12
RAM total                       62.72 GiB
Heap total                      4.00 GiB
Node version                    v18.12.1
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       handy1
Block graffiti                  handy1
```

### Graffiti

handy1

**Comment by wd021** [comment]
what does `wallet:transactions` show?

**Comment by Yuramazyrenko** [comment]
> what does `wallet:transactions` show?

The problem disappeared after a repeat  of mint + burn

**Comment by Yuramazyrenko** [comment]
> what does `wallet:transactions` show?

<img width="1091" alt="CleanShot 2023-02-18 at 19 35 01@2x" src="https://user-images.githubusercontent.com/94488458/219884784-5f2485ae-078e-48ac-b01e-9358ffdff063.png">

**Comment by wd021** [comment]
yea as you can see in the transactions list, the tx hashes from your initial question all have the `expired` status.

**Comment by Yuramazyrenko** [comment]
> yea as you can see in the transactions list, the tx hashes from your initial question all have the `expired` status.



> yea as you can see in the transactions list, the tx hashes from your initial question all have the `expired` status.

Anyway, I've tried many times to send tokens, it doesn't work. It worked when I did it all over again
