### ISSUE TITLE
Incorrect asset is getting minted when an account has multiple assets with same name (one minted and other received), No error while minting.

### ISSUE THREAD

**Issue by NL501** [iron-fish/ironfish#3400]
### What happened?

Incorrect asset is getting minted when an account has multiple assets with same name (one minted and other received).

Steps:
Accounts : nl501alpha1 & nl501beta1
1. An asset with name IAMNL501 is minted from nl501alpha1 and sent part of it is sent to nl501beta1.
2. An asset with same name IAMNL501 is minted from nl501beta1 and sent to burn.
3. Tried to re-mint or mint more of received asset (from step#1) from nl501beta1. Able to trigger the mint for the received asset and minting happened successfully.
4. After minting noticed that the asset minted was from step#2. No error messages were displayed during this whole process.

**Details before minting :** 
Account: nl501alpha1
 Asset Name Asset Id                                                         Confirmed Balance
 ────────── ──────────────────────────────────────────────────────────────── ─────────────────
 NL501ALPT1 05bf83ae3f0b268a4ea89cfa0a576dc09fc8de330b2cf5748c5b9237fe4adea2 60.00000000
 IAMNL501   732e1f8bcd3800e6af40c543632cf079b9579462858823a21b0b4e1bbc8a631c 0.01000000
 $IRON      d7c86706f5817aa718cd1cfad03233bcd64a7789fd9422d3b17af6823a7e6ac6 0.81391634

C:\WINDOWS\system32>ironfish wallet:balances
Account: nl501beta1
 Asset Name Asset Id                                                         Confirmed Balance
 ────────── ──────────────────────────────────────────────────────────────── ─────────────────
 NL501ALPT1 05bf83ae3f0b268a4ea89cfa0a576dc09fc8de330b2cf5748c5b9237fe4adea2 65.00000000
 IAMNL501   732e1f8bcd3800e6af40c543632cf079b9579462858823a21b0b4e1bbc8a631c 0.00500000
 IAMNL501   941c4cec3d8625a9aaf51b8dadd38dd6d8dfd2c4438a79502620c224554b0408 0.01000000
 $IRON      d7c86706f5817aa718cd1cfad03233bcd64a7789fd9422d3b17af6823a7e6ac6 1.87601936

**Minting Details :** 
C:\WINDOWS\system32>ironfish wallet:mint
Do you want to create a new asset (Y/N)?: N
? Select the asset you wish to mint 732e1f8bcd3800e6af40c543632cf079b9579462858823a21b0b4e1bbc8a631c (IAMNL501)
(0.00500000)
Enter the amount to mint in the custom asset: 10
? Select the fee you wish to use for this transaction fast: 0.00000001 IRON

You are about to mint
_732e1f8bcd3800e6af40c543632cf079b9579462858823a21b0b4e1bbc8a631c 10.00000000_ plus a transaction fee of $IRON 0.00000001 with the account nl501beta1

* This action is NOT reversible *

Do you confirm (Y/N)?: Y
Creating the transaction: [████████████████████████████████████████] 100% | ETA: 0s

Minted asset 49414d4e4c353031000000000000000000000000000000000000000000000000 from nl501beta1
Asset Identifier: _941c4cec3d8625a9aaf51b8dadd38dd6d8dfd2c4438a79502620c224554b0408_
Value: 941c4cec3d8625a9aaf51b8dadd38dd6d8dfd2c4438a79502620c224554b0408 10.00000000

Transaction Hash: 236248c3574d69c83fa01dcb71b98937fc2d26694a6d71de50135038b8c6241c

Find the transaction on https://explorer.ironfish.network/transaction/236248c3574d69c83fa01dcb71b98937fc2d26694a6d71de50135038b8c6241c (it can take a few minutes before the transaction appears in the Explorer)

**After Minting :** 
C:\WINDOWS\system32>ironfish wallet:balances
Account: nl501beta1
 Asset Name Asset Id                                                         Confirmed Balance
 ────────── ──────────────────────────────────────────────────────────────── ─────────────────
 NL501ALPT1 05bf83ae3f0b268a4ea89cfa0a576dc09fc8de330b2cf5748c5b9237fe4adea2 65.00000000
 IAMNL501   732e1f8bcd3800e6af40c543632cf079b9579462858823a21b0b4e1bbc8a631c 0.00500000
 IAMNL501   _941c4cec3d8625a9aaf51b8dadd38dd6d8dfd2c4438a79502620c224554b0408 10.01000000_
 $IRON      d7c86706f5817aa718cd1cfad03233bcd64a7789fd9422d3b17af6823a7e6ac6 1.87601935

**Ironfish Status :** 
Version              0.1.67 @ bba0453
Node                 STARTED
Node Name            IAMNL501
Block Graffiti       IAMNL501
Memory               Heap: 450.02 MiB -> 499.71 MiB / 2.00 GiB (21.9%), RSS: 861.99 MiB (7.1%), Free: 5.69 GiB (52.3%)
CPU                  Cores: 4, Current: 15.1%
P2P Network          CONNECTED - In: 13.99 KB/s, Out: 12.84 KB/s, peers 50
Mining               STARTED - 0 miners, 0 mined
Mem Pool             Count: 1654 tx, Bytes: 3.36 MiB
Syncer               IDLE - 0.29 blocks added/sec
Blockchain           0000000000106c8f199b0de8683e2ad593052c9e46c603ae6181f9f14c9f2d3a (38870), Since HEAD: 1m 7s (SYNCED)
Accounts             0000000000106c8f199b0de8683e2ad593052c9e46c603ae6181f9f14c9f2d3a (38870)
Telemetry            STARTED - 27136 <- 2 pending
Workers              STARTED - 0 -> 0 / 3 - -0.02 jobs Δ, 12.2 jobs/s

### Version

0.1.67

### Graffiti

IAMNL501

**Comment by ygao76** [comment]
Hi @NL501, we can not reproduce this issue. In the latest version of Iron Fish, we are seeing consistency between the confirmation output vs the transaction output for mint command. 
From your output, the confirmation output is different with the transaction output. Can you upgrade to the latest version and try again?
The confirmation output 
```
You are about to mint
732e1f8bcd3800e6af40c543632cf079b9579462858823a21b0b4e1bbc8a631c 10.00000000 plus a transaction fee of $IRON 0.00000001 with the account nl501beta1

This action is NOT reversible *
Do you confirm (Y/N)?: Y
Creating the transaction: [████████████████████████████████████████] 100% | ETA: 0s
```
is different with the transaction output 
```
Minted asset 49414d4e4c353031000000000000000000000000000000000000000000000000 from nl501beta1
Asset Identifier: 941c4cec3d8625a9aaf51b8dadd38dd6d8dfd2c4438a79502620c224554b0408
Value: 941c4cec3d8625a9aaf51b8dadd38dd6d8dfd2c4438a79502620c224554b0408 10.00000000
```

**Comment by NL501** [comment]
Hi @ygao76,
Good to know that it is fixed and I believe the root cause is same as below issue so the fix put in for that might have fixed this as well.
https://github.com/iron-fish/ironfish/issues/3477

Unfortunately I refreshed my machine after end of testnet phase 3, so won't be able to re-try from my end.
Please check details of the issue#3477 just to confirm. Thanks.


> Hi @NL501, we can not reproduce this issue. In the latest version of Iron Fish, we are seeing consistency between the confirmation output vs the transaction output for mint command. From your output, the confirmation output is different with the transaction output. Can you upgrade to the latest version and try again? The confirmation output
> 
> ```
> You are about to mint
> 732e1f8bcd3800e6af40c543632cf079b9579462858823a21b0b4e1bbc8a631c 10.00000000 plus a transaction fee of $IRON 0.00000001 with the account nl501beta1
> 
> This action is NOT reversible *
> Do you confirm (Y/N)?: Y
> Creating the transaction: [████████████████████████████████████████] 100% | ETA: 0s
> ```
> 
> is different with the transaction output
> 
> ```
> Minted asset 49414d4e4c353031000000000000000000000000000000000000000000000000 from nl501beta1
> Asset Identifier: 941c4cec3d8625a9aaf51b8dadd38dd6d8dfd2c4438a79502620c224554b0408
> Value: 941c4cec3d8625a9aaf51b8dadd38dd6d8dfd2c4438a79502620c224554b0408 10.00000000
> ```
