### ISSUE TITLE
Minted Asset balance is wrong, cannot burn or send

### ISSUE THREAD

**Issue by Chadwicksracing** [iron-fish/ironfish#3402]
### What happened?

rtm@ironfishnode-01:~$ ironfish wallet:balances
Account: Minter
 Asset Name      Asset Id                                                         Confirmed Balance
 ─────────────── ──────────────────────────────────────────────────────────────── ─────────────────
 $IRON           d7c86706f5817aa718cd1cfad03233bcd64a7789fd9422d3b17af6823a7e6ac6 0.00000008
 Chadwicksracing e6095605c1d5a38d1a1c14f79d0818f8dbc6aebfc8c1eeaa7bd47c8c90506101 90.00000000
rtm@ironfishnode-01:~$ ironfish wallet:burn
? Select the asset you wish to burn e6095605c1d5a38d1a1c14f79d0818f8dbc6aebfc8c1eeaa7bd47c8c90506101 (Chadwicksracing)
Enter the amount to burn in the custom asset: 90
Enter the fee amount in $IRON (min: 0.00000001) [0.00000001]:

You are about to burn:
e6095605c1d5a38d1a1c14f79d0818f8dbc6aebfc8c1eeaa7bd47c8c90506101 90.00000000 plus a transaction fee of $IRON 0.00000001 with the account Minter

* This action is NOT reversible *

Do you confirm (Y/N)?: y
Creating the transaction: [████████████████████████████████████████] 100% | ETA: 0s
An error occurred while burning the asset.
 ›   Error: Request failed (400) error: Insufficient funds: Needed
 ›   e6095605c1d5a38d1a1c14f79d0818f8dbc6aebfc8c1eeaa7bd47c8c90506101 90.00000000 but have 0.00000000 available to
 ›   spend. Please fund your account and/or wait for any pending transactions to be confirmed.'
 
 
![image](https://user-images.githubusercontent.com/42011043/218481079-8b694256-6276-4261-86af-dc2af4748523.png)

### Version

0.1.63

### Debug output

```shell
Iron Fish version               0.1.63 @ 693ff0f
Iron Fish library               0.0.40 @ 693ff0f
Operating system                Linux x64
CPU model(s)                    Common KVM processor
CPU threads                     6
RAM total                       7.67 GiB
Heap total                      2.00 GiB
Node version                    v18.13.0
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       Chadwicksracing
Block graffiti                  Chadwicksracing
```

### Graffiti

Chadwicksracing

**Comment by hughy** [comment]
Do you have any other transactions pending that burn or send this asset?

**Comment by holahula** [comment]
Closing due to staleness. If the issue persists in versions `1.0.0+` - please file a new issue
