### ISSUE TITLE
Your node must be synced with the Iron Fish network

### ISSUE THREAD

**Issue by zaki9501** [iron-fish/ironfish#3404]
![Screenshot (3)](https://user-images.githubusercontent.com/80619916/218512668-61f7d665-5a78-4244-b982-81c6d881390d.png)
### What happened?

so after updating the node we are not able to run any cmd whenever we are trying ti run any cmd we get an error known as "Your node must be synced with the Iron Fish network to send a transaction. Please try again later" please fix this fast 

### Debug output

```shell
Database in use, skipping output that requires database.
Stop the node and run the debug command again to show full output.

Iron Fish version               0.1.67 @ bba0453
Iron Fish library               0.0.44 @ bba0453
Operating system                Linux x64
CPU model(s)                    Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz
CPU threads                     4
RAM total                       7.76 GiB
Heap total                      2.00 GiB
Node version                    v18.14.0
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       bigbull
Block graffiti
```

### Graffiti

bigbull

**Comment by ygao76** [comment]
Some cmd needs your node to be synced with the network. Run `ironfish start` to start your node and it will automatically sync with the network, it might take some time to be fully synced. Run `ironfish status -f` to check your sync status.

**Comment by ygao76** [comment]
Im closing this issue since I am able to run cmd with the latest version. Feel free to reopen if you still have issues.
