### ISSUE TITLE
wasm doesn't work on M1 mac

### ISSUE THREAD

**Issue by NathanielOstrer** [iron-fish/ironfish#341]
I'm following instructions to compile from source but I get the following 

```curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

wasm-pack-init: no precompiled binaries available for CPU architecture: arm64```

Is there a workaround?

**Comment by brekk** [comment]
@NathanielOstrer When I ran into this problem last I found that I was able to fix it by running `cargo install wasm-pack` via [this issue](https://github.com/rustwasm/wasm-pack/issues/952) (the documented `curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh` did not work for me).

Does that help?

**Comment by dguenther** [comment]
Wasm compilation has been removed, so this step should no longer be necessary. Additionally, M1 builds should work properly from source now (though as of writing, the Homebrew tap does not support M1)
