### ISSUE TITLE
node stop syncing to the leaderboard

### ISSUE THREAD

**Issue by wuchouk** [iron-fish/ironfish#3427]
### What happened?

When I have a window running the node and start another window to run the node again, it would show the node is running. After I closed the second window while keeping the first window running the node, the counting time on the leaderboard would stop.
![image](https://user-images.githubusercontent.com/26582477/218951300-104ad17b-9d96-4163-a9cf-2d7977159f06.png)
Therefore the time in the leaderboard would not continue to increase while the node is running.

This should not happen because my first window is still running the node. 

### Version

0.1.63 @ 693ff0f

### Debug output

```shell
Iron Fish version               0.1.63 @ 693ff0f
Iron Fish library               0.0.40 @ 693ff0f
Operating system                Linux x64
CPU model(s)                    AMD Ryzen 9 5900X 12-Core Processor
CPU threads                     24
RAM total                       31.30 GiB
Heap total                      4.00 GiB
Node version                    v18.13.0
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       Ororov
Block graffiti                  Ororov
```

### Graffiti

Ororov

**Comment by hughy** [comment]
Your node is several version behind. The current version is 0.1.68. You need to be running the most recent version within one week of its release in order to earn uptime points.

**Comment by wuchouk** [comment]
Ok thanks!
