### ISSUE TITLE
[issue name] leader board showing negative hours until next reward

### ISSUE THREAD

**Issue by anotherhabit** [iron-fish/ironfish#3440]
### What happened?

leader board counting negative hours for next reward. see AnotherHabit on leaderboard

### Graffiti

AnotherHabit

**Comment by anotherhabit** [comment]
was informed I will be rewarded in 9 hours due to being rewarded early. will close and later check that my rewards add up as I also noted 2 rewards that were rewarded also went missing on the ninth. and now I'm not on the lead 12 hours which does not seem right to me I have not had more than 6 hours down time since genisis block.

**Comment by anotherhabit** [comment]
issue appears to be resolved. the amount I'm behind from genesis block is correct as far as I can tell. Still missing 24hrs from week 4 but I think everyone is.

**Comment by dguenther** [comment]
Closing this since the testnet has ended.
