### ISSUE TITLE
[-1 hour until next reward]Showing wrong data and no points updated

### ISSUE THREAD

**Issue by AlfredTAB** [iron-fish/ironfish#3441]
### What happened?

![image](https://user-images.githubusercontent.com/89577374/219272407-839b7db2-de92-4cf8-b3eb-de3d6c3e8d2f.png)
Graffiti name: tlalflin
Have tried to restart the node, but not work.
![image](https://user-images.githubusercontent.com/89577374/219272862-4c16af81-a45a-4c66-b27c-9debf866ff31.png)

Everything was fine until 02/15.

### Version

Node version V0.1.67

### Graffiti

tlalflin

**Comment by hughy** [comment]
Is the leaderboard still displaying incorrect data for you?

**Comment by dguenther** [comment]
Closing this since the testnet has ended.
