### ISSUE TITLE
 [My leaderboard shows -3 hour until next reward]

### ISSUE THREAD

**Issue by megamozg2022** [iron-fish/ironfish#3442]
### What happened?

A bug happened! My leaderboard shows negative hours for the next reward. My last reward was on 2023-02-15 16:21:34. Now I see "-3 hour until next reward". Please, fix the problem. 
https://github.com/megamozg2022/megamozg2022/blob/main/Screenshot%202023-02-16%20102455.png

### Version

v0.1.67

### Graffiti

megamozg2023

**Comment by dguenther** [comment]
Closing this issue since the testnet has ended.
