### ISSUE TITLE
Reward estimate time showing minus hours

### ISSUE THREAD

**Issue by coldsjf** [iron-fish/ironfish#3444]
### What happened?

The dashboard is having bug showing the estimated hours for rewards

See attached screen

<img width="307" alt="Screenshot 2023-02-16 at 11 20 21 AM" src="https://user-images.githubusercontent.com/123399284/219426659-48e87955-aec8-46f2-9e6f-1aabaf3a185f.png">

### Graffiti

hotsjf

**Comment by dguenther** [comment]
Closing this since the testnet has ended.
