### ISSUE TITLE
error messges

### ISSUE THREAD

**Issue by greywoood** [iron-fish/ironfish#3447]
### What happened?

A bug happened!
![Screenshot 2023-02-17 at 3 29 05 AM](https://user-images.githubusercontent.com/91202015/219455418-99aa16b8-6995-4cc0-a196-55cd6f5bc9a2.png)

### Version

  ironfish/0.1.67

### Graffiti

greywoood

**Comment by ygao76** [comment]
Make sure your node version is up to date and restart your node.
