### ISSUE TITLE
Explorer Stuck - Not Loading 

### ISSUE THREAD

**Issue by pratikgarg1122** [iron-fish/ironfish#3461]
### What happened?

Block explorer is not loading. Please check - 

<img width="1470" alt="image" src="https://user-images.githubusercontent.com/123742309/219650121-541e952d-1fe3-4bfb-9659-afddfbce6b48.png">

Tried on different browsers n devices.

### Version

v0.1.67

### Graffiti

pratikmbm1122

**Comment by hughy** [comment]
Closing the issue since the API was temporarily struggling under heavy load from the testnet.
