### ISSUE TITLE
The corresponding points have not been credited to my account on the website while hosting a node over 24 hours.

### ISSUE THREAD

**Issue by xqjcool1** [iron-fish/ironfish#3471]
### What happened?

I have been hosting a node for 24 hours, but the corresponding points have not been credited to my account on the website.I have tried multiple times, but the result is still the same.

### Version

v0.1.63

### Graffiti

xqjcool

**Comment by adnanrana39** [comment]
please upgrade your node version

**Comment by xqjcool1** [comment]
root@DESKTOP-7B1REV8:/home/xqjcool# ironfish version
name       ironfish
version    0.1.63
git        693ff0f
runtime    node/18.13.0

**Comment by wd021** [comment]
latest is 0.1.67, you don't get points for older versions.

**Comment by xqjcool1** [comment]
How do I upgrade to the latest version?

**Comment by wd021** [comment]
1) stop your node -> `ironfish stop`
2) update -> `npm install -g ironfish`
3) start your node -> `ironfish start`
