### ISSUE TITLE
Incorrect command on website

### ISSUE THREAD

**Issue by anotherhabit** [iron-fish/ironfish#3481]
### What happened?

A bug happened!

When using ironfish command `ironfish config:show` as displayed on website [https://ironfish.network/docs/onboarding/iron-fish-cli](https://ironfish.network/docs/onboarding/iron-fish-cli) it gives warning message.

The ironfish command that prints out the content of the config file is `ironfish config`

Website or Ironfish should be updated to avoid confusion with users.

### Version

 v0.1.67

### Relevant log output

```shell
›   Warning: config:show is not a ironfish command.
Did you mean config:set? [y/n]:
 ›   Error: Run ironfish help config for a list of available commands
```

### Graffiti

AnotherHabit

**Comment by ygao76** [comment]
Website updated.
