### ISSUE TITLE
Faucet is stuck

### ISSUE THREAD

**Issue by pratikgarg1122** [iron-fish/ironfish#3489]
### What happened?

Approx 10k faucet requests are in queue. Please check : 
<img width="728" alt="image" src="https://user-images.githubusercontent.com/123742309/220264381-499b1119-fbd4-47bc-ab48-e5b5dc6025e9.png">

### Version

v0.1.67

### Graffiti

pratikmbm1122

**Comment by hughy** [comment]
Thanks for elevating this! We restarted the faucet process early yesterday and transactions are flowing again
