### ISSUE TITLE
“yarn start status”doesn‘t work

### ISSUE THREAD

**Issue by ashlooper** [iron-fish/ironfish#3490]
### What happened?

use another terminal for sending command
![1676972581727](https://user-images.githubusercontent.com/44914149/220308185-9c21bf0a-801a-4ea4-af0b-28672e548829.png)

### Graffiti

eyujie

**Comment by hughy** [comment]
What version of the node were you running when you ran into this issue?

Are you still seeing this issue?

**Comment by ashlooper** [comment]
The issue has been solved.Thank you😋.The network crashed at that time,now
it works well.

Hugh Cunningham ***@***.***> 于2023年4月20日周四 04:33写道：
