### ISSUE TITLE
ironfish ceremony

### ISSUE THREAD

**Issue by svarichevskiy** [iron-fish/ironfish#3511]
### What happened?

root@ubuntu-s-4vcpu-8gb-blr1-01:~# ironfish ceremony
    ParseJsonError: Parsing internal.json Failed
    Unexpected end of JSON input while parsing empty string in internal.json
root@ubuntu-s-4vcpu-8gb-blr1-01:~#

### Version

0.1.67

**Comment by dguenther** [comment]
The ceremony has ended, so we won't be making further adjustments to this code. Thanks for reporting though!
