### ISSUE TITLE
Feature: Display Error Message when burning, minting, sending transaction

### ISSUE THREAD

**Issue by irontankfish** [iron-fish/ironfish#3549]
### Description

Currently when sending, minting or burning a transaction, no Error message is displayed to let the user know, that the amount that they entered is 0, or less than 0. An output message, would be useful:

Burning:
<img width="888" alt="before-burn" src="https://user-images.githubusercontent.com/114656810/221302362-70e490cb-6fb0-4d51-a19a-ff29a9663c1f.png">

Minting:
<img width="894" alt="before-mint" src="https://user-images.githubusercontent.com/114656810/221302365-32e992c5-41a0-4f24-857e-b3c0fc1c34c4.png">

Sending:
<img width="886" alt="before-send" src="https://user-images.githubusercontent.com/114656810/221302369-57eb8679-036a-427d-841a-d9875b7f70e2.png">

**Comment by hughy** [comment]
Resolved by #3567
