### ISSUE TITLE
Ceremony error, 1 remained in the queue

### ISSUE THREAD

**Issue by iblademan** [iron-fish/ironfish#3556]
### What happened?

I didn't update the version to the new one so that the ceremony wouldn't fly off. There was 1 person left in the queue and this error popped up.
<img width="831" alt="Снимок экрана 2023-02-25 в 10 11 44" src="https://user-images.githubusercontent.com/92264737/221345909-f381f624-0f4c-40fb-9262-d55cde31d493.png">

### Version

v.0.1.67

### Debug output

Iron Fish version               0.1.69 @ 46295bc
Iron Fish library               0.0.46 @ 46295bc
Operating system                Linux x64
CPU model(s)                    AMD EPYC 7282 16-Core Processor
CPU threads                     4
RAM total                       7.77 GiB
Heap total                      2.00 GiB
Node version                    v18.14.0
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       Blademan
Block graffiti                  Blademan
root@vmi1192847:~# 

### Graffiti

Blademan

**Comment by dguenther** [comment]
The ceremony has ended, so we won't be making further adjustments to this code. Thanks for reporting though!
