### ISSUE TITLE
mint burn send - balance has not changed - 0.1.70

### ISSUE THREAD

**Issue by velyar** [iron-fish/ironfish#3570]
### What happened?

After performing mint burn send operations, the balance of the main wallet ($IRON ) has not changed.
Screenshot is attached.
![image](https://user-images.githubusercontent.com/22917604/221418788-8c9958bc-06a3-4653-a4c6-6e9a4ff53c7a.png)

### Version

0.1.70

### Graffiti

velyar

**Comment by velyar** [comment]
After 17 hours, the balance also remained unchanged.

**Comment by hughy** [comment]
Can you explain more about the problem that you're seeing?

Based on your screenshots, you started with `$IRON 0.04858987`.

You sent a transaction with a fee of `$IRON 0.00000001`, and your balance decreased to `$IRON 0.04858986`.

You then send a transaction with a fee of `$IRON 0.00000100`, and your balance decreased to `$IRON 0.04858886`

The balance seems to have updated, decreasing by the amount of the fee after each transaction.

**Comment by velyar** [comment]
Yes, as you rightly noted, only transaction fees were debited from the wallet.
I made the operation mint - 0.01 - the commission was set to the minimum 0.00000001.
Then there was the burn operation - 0.005 - the commission was the maximum and also 0.00000001.
Then there was the send operation - 0.005 - I set the commission manually 0.00000100.
As a result, a commission was deducted from the wallet for all operations, but the amount of 0.01 was not debited.

**Comment by hughy** [comment]
The mint added 0.01 of your custom asset, 'velyar'.

The burn of 0.005 subtracted 0.005 from the balance of that asset to give a balance of 0.005.

The send of 0.005 subtracted the remaining 0.005 from the balance. The final balance of the custom asset is 0.

**Comment by velyar** [comment]
I repeat now these three operations again with the same parameters.

1. mint
In this game, we should have 0.01 written from the $IRON wallet to the velyar wallet. On velar coins of heaven, but not reduced by $IRON. Prior to version 0.1.70, there were no such problems.
https://explorer.ironfish.network/transaction/48b9f59518291bc66a7b9d4652f1d29132a12d78741b5649c2643df3bbdae6c3
![image](https://user-images.githubusercontent.com/22917604/221697781-79bf4fa3-aefd-4018-b48b-9bc892aee95a.png)

2. burn
https://explorer.ironfish.network/transaction/1e023d2f68e408cd431849aa5b3c04da9c32910fbfa9fa706d03429e63bf3128
![image](https://user-images.githubusercontent.com/22917604/221698424-161f13dc-9efb-4246-83a2-dfbda1d18bf7.png)

3. send
https://explorer.ironfish.network/transaction/0748580e34bd267340518e5a6414140da6209de7e13dd713c50e45bc40816c6d
![image](https://user-images.githubusercontent.com/22917604/221700321-1c3fab5e-191f-43a2-9264-9a668f3849a3.png)

Final balans
![image](https://user-images.githubusercontent.com/22917604/221701203-ff682858-ca3a-44ea-bee3-d353e7b5f1f1.png)
Well, by the way, the balance is zero everywhere after the send operation, you have to wait 10 minutes for the balance to be displayed again.
And as a result, everything on the $IRON wallet remains unchanged, only the commission is debited.
Or is the mint command not taking coins from the $IRON wallet? And only the commission is deducted from it?

**Comment by hughy** [comment]
The `mint` command is creating a new asset called `velyar`. This is a different asset than the native asset, `$IRON`.

Each transaction is paying fees in `$IRON` that are deducted from the balance.

The available balance of an asset may decrease to 0 while there are one ore more transactions pending that spend that asset. Iron Fish is a UTXO currency, so your balance is composed of 'notes'. Each note has a specific value, like cash. When you spend a note, you spend the whole note, but receive a new note with your 'change' if the amount that you sent was less than the value of the note.

**Comment by velyar** [comment]
Thanks for the clarification, sorry to bother you, it just seemed to me before that that money was always withdrawn from the $IRON wallet during the mint operation.))
