### ISSUE TITLE
Leaderboard Website not updating?

### ISSUE THREAD

**Issue by tonedr** [iron-fish/ironfish#3576]
### What happened?

Ever since yesterday, the Leaderboard webpage does not seem to be updating.  No record of new burn, send, or mint.  No update in Hosted Node times, no change in ranking, etc...

Even I check one of the top 10 users, no updates for week #7.  Last updates seen on webpage are from 2/25/2023

### Version

0.1.70

### Graffiti

ToneDr

**Comment by hughy** [comment]
Phase 3 ended on 2/25/2023. You can read more here: https://ironfish.network/blog/2023/02/23/phase3-update
