### ISSUE TITLE
Stopped getting credit for running a node.

### ISSUE THREAD

**Issue by stacknsats** [iron-fish/ironfish#3598]
### What happened?

Node was running great from 2/17 - 2/25 and then it stopped counting points for running the node.  The node is still running on my end.  

ironfish@ironfishnode:~$ ironfish status
Version              0.1.70 @ 6fb75f4
Node                 STARTED
Node Name            stacknsats
Block Graffiti       stacknsats
Memory               Heap: 144.27 MiB -> 314.02 MiB / 2.00 GiB (7.0%), RSS: 851.64 MiB (8.7%), Free: 8.32 GiB (13.4%)
CPU                  Cores: 4, Current: 86.9%
P2P Network          CONNECTED - In: 9.42 KB/s, Out: 34.36 KB/s, peers 47
Mining               STARTED - 0 miners, 0 mined
Mem Pool             Count: 61 tx, Bytes: 113.20 KiB
Syncer               IDLE - 3.24 blocks added/sec
Blockchain           00000000002e63094bcb9bb746c8bf166259256d65a86bbb30b1d3f3ed36df0c (64221), Since HEAD: 13s 768ms (SYNCED)
Accounts             00000000002e63094bcb9bb746c8bf166259256d65a86bbb30b1d3f3ed36df0c (64221)
Telemetry            STARTED - 11816 <- 12 pending
Workers              STARTED - 0 -> 0 / 3 - -0.04 jobs Δ, 7.35 jobs/s

### Version

0.1.7.0

### Debug output

```shell
Database in use, skipping output that requires database.
Stop the node and run the debug command again to show full output.

Iron Fish version               0.1.70 @ 6fb75f4
Iron Fish library               0.0.47 @ 6fb75f4
Operating system                Linux x64
CPU model(s)                    AMD Ryzen 7 1700X Eight-Core Processor
CPU threads                     4
RAM total                       9.60 GiB
Heap total                      2.00 GiB
Node version                    v18.14.2
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       stacknsats
Block graffiti                  stacknsats
```

### Graffiti

stacknsats

**Comment by stacknsats** [comment]
Output from ironfish logs

Added block seq: 64240, hash: 00000...bfa5e, txs: 56, progress: 100.00%, time: 393.0ms
Reorganizing chain from 00000...bd949 (64258) for 00000...6f409 (64258) on prev 00000...05b6f (64257)
Reorganized chain. blocks: 1, old: 00000...bd949 (64258), new: 00000...05b6f (64257), fork: 00000...05b6f (64257)
Added block seq: 64260, hash: 00000...77d2e, txs: 16, progress: 100.00%, time: 86.1ms
Added block seq: 64280, hash: 00000...952bb, txs: 84, progress: 100.00%, time: 579.5ms
Added block seq: 64300, hash: 00000...321cc, txs: 61, progress: 100.00%, time: 347.7ms
Added block to fork seq: 64305, head-seq: 64305, hash: 00000...1171c, head-hash: 00000...42ac9, work: 279594289747386083, head-work: 279594291065339159, work-diff: 1317953076
Added block to fork seq: 64314, head-seq: 64314, hash: 00000...b6bb1, head-hash: 00000...9b32a, work: 279618644285322338, head-work: 279618644285322338, work-diff: 0
Reorganizing chain from 00000...2067c (64317) for 00000...9a7b4 (64317) on prev 00000...c02aa (64316)
Reorganized chain. blocks: 1, old: 00000...2067c (64317), new: 00000...c02aa (64316), fork: 00000...c02aa (64316)
Added block seq: 64320, hash: 00000...f963b, txs: 77, progress: 100.00%, time: 461.4ms
Reorganizing chain from 00000...96587 (64326) for 00000...4b9f1 (64326) on prev 00000...00f15 (64325)
Reorganized chain. blocks: 1, old: 00000...96587 (64326), new: 00000...00f15 (64325), fork: 00000...00f15 (64325)
Added block seq: 64340, hash: 00000...2dd00, txs: 63, progress: 100.00%, time: 410.8ms
Added block to fork seq: 64340, head-seq: 64340, hash: 00000...5147d, head-hash: 00000...2dd00, work: 279689517829530413, head-work: 279689517829530413, work-diff: 0
Added block seq: 64340, hash: 00000...5147d, txs: 53, progress: 100.00%, time: 416.3ms
Reorganizing chain from 00000...cdc62 (64354) for 00000...142ba (64354) on prev 00000...5fc69 (64353)
Reorganized chain. blocks: 1, old: 00000...cdc62 (64354), new: 00000...5fc69 (64353), fork: 00000...5fc69 (64353)
Added block seq: 64360, hash: 00000...2e210, txs: 124, progress: 100.00%, time: 782.3ms
Added block to fork seq: 64369, head-seq: 64369, hash: 00000...5cdff, head-hash: 00000...9b993, work: 279768621667806533, head-work: 279768621667806533, work-diff: 0
Added block seq: 64380, hash: 00000...2390b, txs: 17, progress: 100.00%, time: 120.9ms
Added block to fork seq: 64393, head-seq: 64393, hash: 00000...6c6dd, head-hash: 00000...44733, work: 279833714218438477, head-work: 279833714218438477, work-diff: 0
Added block to fork seq: 64397, head-seq: 64397, hash: 00000...7e8b3, head-hash: 00000...b1966, work: 279844581805027959, head-work: 279844581805027959, work-diff: 0
Added block seq: 64400, hash: 00000...aa2c2, txs: 28, progress: 100.00%, time: 247.0ms
Reorganizing chain from 00000...c8a94 (64414) for 00000...8ecf6 (64414) on prev 00000...2a708 (64413)
Reorganized chain. blocks: 1, old: 00000...c8a94 (64414), new: 00000...2a708 (64413), fork: 00000...2a708 (64413)
Added block seq: 64420, hash: 00000...96d09, txs: 24, progress: 100.00%, time: 162.7ms
Added block seq: 64440, hash: 00000...baaad, txs: 48, progress: 100.00%, time: 299.1ms
Added block to fork seq: 64441, head-seq: 64441, hash: 00000...5c3b6, head-hash: 00000...a7ba0, work: 279963484044816013, head-work: 279963485369301289, work-diff: 1324485276
Reorganizing chain from 00000...b402a (64448) for 00000...484ca (64448) on prev 00000...aff08 (64447)
Reorganized chain. blocks: 1, old: 00000...b402a (64448), new: 00000...aff08 (64447), fork: 00000...aff08 (64447)
Added block seq: 64460, hash: 00000...e93c7, txs: 25, progress: 100.00%, time: 196.7ms
Added block seq: 64480, hash: 00000...c510c, txs: 91, progress: 100.00%, time: 731.9ms
Added block seq: 64500, hash: 00000...0f5f4, txs: 24, progress: 100.00%, time: 185.3ms
Error parsing message
Added block seq: 64520, hash: 00000...9ffac, txs: 14, progress: 100.00%, time: 86.7ms
Added block to fork seq: 64527, head-seq: 64527, hash: 00000...8b450, head-hash: 00000...bacfe, work: 280197782834345510, head-work: 280197782834345510, work-diff: 0
Added block seq: 64540, hash: 00000...dee6d, txs: 127, progress: 100.00%, time: 784.3ms
Reorganizing chain from 00000...b09a9 (64547) for 00000...c7388 (64547) on prev 00000...48c6e (64546)
Reorganized chain. blocks: 1, old: 00000...b09a9 (64547), new: 00000...48c6e (64546), fork: 00000...48c6e (64546)
Added block seq: 64560, hash: 00000...6f129, txs: 33, progress: 100.00%, time: 232.9ms
Added block seq: 64580, hash: 00000...2e721, txs: 37, progress: 100.00%, time: 270.4ms
Reorganizing chain from 00000...27658 (64589) for 00000...71c82 (64589) on prev 00000...009d8 (64588)
Reorganized chain. blocks: 1, old: 00000...27658 (64589), new: 00000...009d8 (64588), fork: 00000...009d8 (64588)
Added block to fork seq: 61246, head-seq: 64596, hash: 00000...c519b, head-hash: 00000...e72e4, work: 270673517181820718, head-work: 280380500272743010, work-diff: 9706983090922292
Added block seq: 64600, hash: 00000...2ea74, txs: 65, progress: 100.00%, time: 421.7ms
Added block to fork seq: 64606, head-seq: 64606, hash: 00000...2d91e, head-hash: 00000...89922, work: 280406309964817404, head-work: 280406311227812459, work-diff: 1262995055
Reorganizing chain from 00000...9c2ac (64609) for 00000...b8fd1 (64609) on prev 00000...4e3aa (64608)
Reorganized chain. blocks: 1, old: 00000...9c2ac (64609), new: 00000...4e3aa (64608), fork: 00000...4e3aa (64608)
Added block to fork seq: 64610, head-seq: 64610, hash: 00000...a7b92, head-hash: 00000...5b53b, work: 280416624877541671, head-work: 280416624877541671, work-diff: 0
Added block seq: 64620, hash: 00000...bbd51, txs: 62, progress: 100.00%, time: 356.9ms
Added block to fork seq: 64621, head-seq: 64621, hash: 00000...506fb, head-hash: 00000...ccf89, work: 280444488178678507, head-work: 280444490642187771, work-diff: 2463509264
Added block seq: 64640, hash: 00000...7c70c, txs: 11, progress: 100.00%, time: 87.2ms
Added block seq: 64660, hash: 00000...efc22, txs: 23, progress: 100.00%, time: 171.0ms
Added block seq: 64680, hash: 00000...4016e, txs: 41, progress: 100.00%, time: 258.3ms
Reorganizing chain from 00000...2b438 (64687) for 00000...db9a8 (64687) on prev 00000...78d5a (64686)
Reorganized chain. blocks: 1, old: 00000...2b438 (64687), new: 00000...78d5a (64686), fork: 00000...78d5a (64686)
Added block seq: 64700, hash: 00000...c04b8, txs: 85, progress: 100.00%, time: 753.0ms

**Comment by hughy** [comment]
The phase 3 testnet ended on 2/25, so no uptime points are awarded after that date.
