### ISSUE TITLE
Audit points for PRs

### ISSUE THREAD

**Issue by krompets** [iron-fish/ironfish#3607]
### What happened?

We have to audit points for PRs. 
Here is Google docs with records which requires audit.
- wrong points
- wrong category
- duplicate 
https://docs.google.com/spreadsheets/d/1Pg11IrD4MFk84lPgtqk0w4KGk3SkZQG9HGedB6SFIZU/edit#gid=1584448613

### Graffiti

testnet-ironfish21

**Comment by NullSoldier** [comment]
We'll give you 100 points for this, thank you.

**Comment by danield9tqh** [comment]
@krompets please add your graffiti to this PR if you would like points

**Comment by krompets** [comment]
@danield9tqh updated.

**Comment by dguenther** [comment]
I think this should be taken care of now, thanks!
