### ISSUE TITLE
[account`s output is aways pending ]

### ISSUE THREAD

**Issue by Geapefurit** [iron-fish/ironfish#3652]
### What happened?

I create a transaction and post it ,then add it to ironfish node whth golang sdk named https://github.com/web3eye-io/ironfish-go-sdk
The transaction is aways pending.not success and fail.
I find the expiration is zero.like
```json
{
  hash: '4eb81ebb02636f7b7978358d2f8abc22ed4fecd0a9641e69edd246e9adca9ce1',
  fee: '1',
  notesCount: 2,
  spendsCount: 1,
  mintsCount: 0,
  burnsCount: 0,
  expiration: 0,
  timestamp: 1678857838972,
  assetBalanceDeltas: [
    {
      assetId: 'd7c86706f5817aa718cd1cfad03233bcd64a7789fd9422d3b17af6823a7e6ac6',
      assetName: '2449524f4e',
      delta: '-100001'
    }
  ],
  status: 'pending',
  type: 'send'
}
```

### Version

v0.1.70

### Debug output

```shell
no
```

### Relevant log output

```shell
no
```

**Comment by hughy** [comment]
Which version of Iron Fish is your node running? Is your node synced with the network?

**Comment by Geapefurit** [comment]
v0.1.70,yes it`s synced.

**Comment by hughy** [comment]
If your node is synced (`ironfish status`) and your account is synced (`ironfish wallet:status`) then it looks like your transaction has not been mined.

**Comment by Geapefurit** [comment]
Ok I found out why.When I import a account,then the transaction is aways pending.
