### ISSUE TITLE
[Money that appears out of thin air]

### ISSUE THREAD

**Issue by Geapefurit** [iron-fish/ironfish#3661]
### What happened?

When I test transaction，I find my blance that appears out of thin air.Then I waited for a long time and it was like same thing.
I am rescanning my wallet and waitting to confirm where the bug from.
I check the transactions and notes as follows：
```
// the key of account
RpcResponse {
  status: 200,
  content: {
    account: {
      version: 1,
      name: 'd42fe13c83bac7ebd97018ce0e8253624676aac36f20ba8102b2686bb227c8eb',
      spendingKey: null,
      viewKey: '76cf53c12acc4a06f37a34edac69b3dc5f16ec26d63b58330580391f52385a4eb99ec465feb6d361f9d5f4d29b928319fb8b9e26aca1e2ddd5da4968387cc183',
      incomingViewKey: 'ad292fec85b70fefbfbc0cb471865602ba5935f75ffdd0ae8121df6bb6d2e605',
      outgoingViewKey: 'a00d3106c3aee52a2e18bb82284f95a3715463b218d5aab524ec7a931e340233',
      publicAddress: 'd42fe13c83bac7ebd97018ce0e8253624676aac36f20ba8102b2686bb227c8eb'
    }
  },
  promise: Promise { { account: [Object] } },
  stream: Stream { buffer: [], waiting: [], closed: true, error: undefined },
  timeout: null
}


// getAccountTransactionsStream({account:"d42fe13c83bac7ebd97018ce0e8253624676aac36f20ba8102b2686bb227c8eb"})
{
  hash: '9b1c271692b16f89c3ad6e10ee0d76a691941e37aad91fbf7d9ee00da22375d6',
  fee: '1',
  notesCount: 2,
  spendsCount: 1,
  mintsCount: 0,
  burnsCount: 0,
  expiration: 85797,
  timestamp: 1679037497314,
  assetBalanceDeltas: [
    {
      assetId: 'd7c86706f5817aa718cd1cfad03233bcd64a7789fd9422d3b17af6823a7e6ac6',
      assetName: '2449524f4e',
      delta: '-100001'
    }
  ],
  status: 'expired',
  type: 'send'
}
{
  hash: '0b599541086d0aaa9805d1a58ca3deeeb21fe958b7131ff0aa5e0b7e17d7140f',
  fee: '1',
  blockHash: '0000000000064432ed77a5e7e856bf2d569a0990ece091efe5f7bcc4a2114ea4',
  blockSequence: 85784,
  notesCount: 2,
  spendsCount: 1,
  mintsCount: 0,
  burnsCount: 0,
  expiration: 85797,
  timestamp: 1679037496452,
  assetBalanceDeltas: [
    {
      assetId: 'd7c86706f5817aa718cd1cfad03233bcd64a7789fd9422d3b17af6823a7e6ac6',
      assetName: '2449524f4e',
      delta: '-100001'
    }
  ],
  status: 'confirmed',
  type: 'send'
}
{
  hash: 'ae454f9a02aa105d028e9465744bf906af83a7f2e868dccf771c173ebe29b3fb',
  fee: '1',
  notesCount: 2,
  spendsCount: 1,
  mintsCount: 0,
  burnsCount: 0,
  expiration: 85788,
  timestamp: 1679036708444,
  assetBalanceDeltas: [
    {
      assetId: 'd7c86706f5817aa718cd1cfad03233bcd64a7789fd9422d3b17af6823a7e6ac6',
      assetName: '2449524f4e',
      delta: '-100001'
    }
  ],
  status: 'expired',
  type: 'send'
}
{
  hash: 'c3ae41ff748e626706f3e80f18376eeb4d956ef7d62586af31b9e41cd02b40e4',
  fee: '1',
  blockHash: '00000000000115f481578639f112299b052d1d10983a9c8bec9dcacdf421a97a',
  blockSequence: 85775,
  notesCount: 2,
  spendsCount: 1,
  mintsCount: 0,
  burnsCount: 0,
  expiration: 85788,
  timestamp: 1679036706747,
  assetBalanceDeltas: [
    {
      assetId: 'd7c86706f5817aa718cd1cfad03233bcd64a7789fd9422d3b17af6823a7e6ac6',
      assetName: '2449524f4e',
      delta: '-100001'
    }
  ],
  status: 'confirmed',
  type: 'send'
}
{
  hash: 'c1cc15ef0fbabb9bd37444205e019d0a040ecbf47e727d19245a917c4eb7fef4',
  fee: '1',
  blockHash: '0000000000047ac71f0c5d08e55f498d396d7542d79aee853f92c479ce0c7f8a',
  blockSequence: 83387,
  notesCount: 5,
  spendsCount: 1,
  mintsCount: 0,
  burnsCount: 0,
  expiration: 83400,
  timestamp: 1678878406500,
  assetBalanceDeltas: [
    {
      assetId: 'd7c86706f5817aa718cd1cfad03233bcd64a7789fd9422d3b17af6823a7e6ac6',
      assetName: '2449524f4e',
      delta: '1000000'
    }
  ],
  status: 'confirmed',
  type: 'receive'
}

// getAccountNotesStream({account:"d42fe13c83bac7ebd97018ce0e8253624676aac36f20ba8102b2686bb227c8eb"}) 
{
  value: '799998',
  assetId: 'd7c86706f5817aa718cd1cfad03233bcd64a7789fd9422d3b17af6823a7e6ac6',
  assetName: '2449524f4e',
  memo: '',
  sender: 'd42fe13c83bac7ebd97018ce0e8253624676aac36f20ba8102b2686bb227c8eb',
  transactionHash: '0b599541086d0aaa9805d1a58ca3deeeb21fe958b7131ff0aa5e0b7e17d7140f',
  spent: false
}
{
  value: '899999',
  assetId: 'd7c86706f5817aa718cd1cfad03233bcd64a7789fd9422d3b17af6823a7e6ac6',
  assetName: '2449524f4e',
  memo: '',
  sender: 'd42fe13c83bac7ebd97018ce0e8253624676aac36f20ba8102b2686bb227c8eb',
  transactionHash: 'c3ae41ff748e626706f3e80f18376eeb4d956ef7d62586af31b9e41cd02b40e4',
  spent: false
}
{
  value: '1000000',
  assetId: 'd7c86706f5817aa718cd1cfad03233bcd64a7789fd9422d3b17af6823a7e6ac6',
  assetName: '2449524f4e',
  memo: '',
  sender: '162bfbd6831ea047862b404e07418a35ba3bdc41fa3390057f119b69ae730b4d',
  transactionHash: 'c1cc15ef0fbabb9bd37444205e019d0a040ecbf47e727d19245a917c4eb7fef4',
  spent: false
}
```

### Version

v0.1.70

### Graffiti

discord coast#1853

**Comment by Geapefurit** [comment]
another account,but notes is right

// getBalance

RpcResponse {
  status: 200,
  content: {
    account: '903e0a76bf4b599970b997756f794a5e2f336e3f6ebae4af6f00cc2e6b220a0f',
    assetId: 'd7c86706f5817aa718cd1cfad03233bcd64a7789fd9422d3b17af6823a7e6ac6',
    confirmed: '699997',
    unconfirmed: '699997',
    unconfirmedCount: 0,
    pending: '699997',
    available: '1499995',
    pendingCount: 0,
    confirmations: 2,
    blockHash: '000000000007394ae875d9a2192609163cdea63118c4e690e462db6a35253303',
    sequence: 85864
  },
  promise: Promise {
    {
      account: '903e0a76bf4b599970b997756f794a5e2f336e3f6ebae4af6f00cc2e6b220a0f',
      assetId: 'd7c86706f5817aa718cd1cfad03233bcd64a7789fd9422d3b17af6823a7e6ac6',
      confirmed: '699997',
      unconfirmed: '699997',
      unconfirmedCount: 0,
      pending: '699997',
      available: '1499995',
      pendingCount: 0,
      confirmations: 2,
      blockHash: '000000000007394ae875d9a2192609163cdea63118c4e690e462db6a35253303',
      sequence: 85864
    }
  },
  stream: Stream { buffer: [], waiting: [], closed: true, error: undefined },
  timeout: null
}

// getTransactions
{
  hash: 'a1c50a675d3885ae017309a4285836aaf510216121376578b7bcc92aeb571c1f',
  fee: '1',
  notesCount: 2,
  spendsCount: 1,
  mintsCount: 0,
  burnsCount: 0,
  expiration: 85843,
  timestamp: 1679042017591,
  assetBalanceDeltas: [
    {
      assetId: 'd7c86706f5817aa718cd1cfad03233bcd64a7789fd9422d3b17af6823a7e6ac6',
      assetName: '2449524f4e',
      delta: '-100001'
    }
  ],
  status: 'expired',
  type: 'send'
}
{
  hash: '55e3625ae987c37da9f8888ac852f7e79472e0c75e835dca9e919a784f9ee540',
  fee: '1',
  blockHash: '0000000000114c6fe0150f8d552381649443576fe3ca73080458c4e7b02e83ac',
  blockSequence: 85830,
  notesCount: 2,
  spendsCount: 1,
  mintsCount: 0,
  burnsCount: 0,
  expiration: 85843,
  timestamp: 1679042016867,
  assetBalanceDeltas: [
    {
      assetId: 'd7c86706f5817aa718cd1cfad03233bcd64a7789fd9422d3b17af6823a7e6ac6',
      assetName: '2449524f4e',
      delta: '-100001'
    }
  ],
  status: 'confirmed',
  type: 'send'
}
{
  hash: 'cbfbadda917b2ef6cdcdd38081db8e1f1a8ab5ba7362ea509441dff0b07f08e6',
  fee: '1',
  blockHash: '00000000000b52b49e176958174d9d305ea38a6fc2766dfbc90edd9a0c58c396',
  blockSequence: 85826,
  notesCount: 2,
  spendsCount: 1,
  mintsCount: 0,
  burnsCount: 0,
  expiration: 85839,
  timestamp: 1679041596366,
  assetBalanceDeltas: [
    {
      assetId: 'd7c86706f5817aa718cd1cfad03233bcd64a7789fd9422d3b17af6823a7e6ac6',
      assetName: '2449524f4e',
      delta: '-100001'
    }
  ],
  status: 'confirmed',
  type: 'send'
}
{
  hash: '3c7d5f477c6306e638a2ec915cb92759b6bf5bcf7d0caaa0b3e2510865c84823',
  fee: '1',
  blockHash: '0000000000025bed444f0420c58c4b0db930035683d9406fb79e2b39a9ea9a8d',
  blockSequence: 85822,
  notesCount: 2,
  spendsCount: 1,
  mintsCount: 0,
  burnsCount: 0,
  expiration: 85835,
  timestamp: 1679040571841,
  assetBalanceDeltas: [
    {
      assetId: 'd7c86706f5817aa718cd1cfad03233bcd64a7789fd9422d3b17af6823a7e6ac6',
      assetName: '2449524f4e',
      delta: '-100001'
    }
  ],
  status: 'confirmed',
  type: 'send'
}
{
  hash: 'c1cc15ef0fbabb9bd37444205e019d0a040ecbf47e727d19245a917c4eb7fef4',
  fee: '1',
  blockHash: '0000000000047ac71f0c5d08e55f498d396d7542d79aee853f92c479ce0c7f8a',
  blockSequence: 83387,
  notesCount: 5,
  spendsCount: 1,
  mintsCount: 0,
  burnsCount: 0,
  expiration: 83400,
  timestamp: 1678878406448,
  assetBalanceDeltas: [
    {
      assetId: 'd7c86706f5817aa718cd1cfad03233bcd64a7789fd9422d3b17af6823a7e6ac6',
      assetName: '2449524f4e',
      delta: '1000000'
    }
  ],
  status: 'confirmed',
  type: 'receive'
}

// getNotes

{
  value: '699997',
  assetId: 'd7c86706f5817aa718cd1cfad03233bcd64a7789fd9422d3b17af6823a7e6ac6',
  assetName: '2449524f4e',
  memo: '',
  sender: '903e0a76bf4b599970b997756f794a5e2f336e3f6ebae4af6f00cc2e6b220a0f',
  transactionHash: '55e3625ae987c37da9f8888ac852f7e79472e0c75e835dca9e919a784f9ee540',
  spent: false
}
{
  value: '799998',
  assetId: 'd7c86706f5817aa718cd1cfad03233bcd64a7789fd9422d3b17af6823a7e6ac6',
  assetName: '2449524f4e',
  memo: '',
  sender: '903e0a76bf4b599970b997756f794a5e2f336e3f6ebae4af6f00cc2e6b220a0f',
  transactionHash: 'cbfbadda917b2ef6cdcdd38081db8e1f1a8ab5ba7362ea509441dff0b07f08e6',
  spent: true
}
{
  value: '899999',
  assetId: 'd7c86706f5817aa718cd1cfad03233bcd64a7789fd9422d3b17af6823a7e6ac6',
  assetName: '2449524f4e',
  memo: '',
  sender: '903e0a76bf4b599970b997756f794a5e2f336e3f6ebae4af6f00cc2e6b220a0f',
  transactionHash: '3c7d5f477c6306e638a2ec915cb92759b6bf5bcf7d0caaa0b3e2510865c84823',
  spent: true
}
{
  value: '1000000',
  assetId: 'd7c86706f5817aa718cd1cfad03233bcd64a7789fd9422d3b17af6823a7e6ac6',
  assetName: '2449524f4e',
  memo: '',
  sender: '162bfbd6831ea047862b404e07418a35ba3bdc41fa3390057f119b69ae730b4d',
  transactionHash: 'c1cc15ef0fbabb9bd37444205e019d0a040ecbf47e727d19245a917c4eb7fef4',
  spent: true
}

**Comment by hughy** [comment]
@Geapefurit I think that what's happening here is you're creating multiple transactions that spend the same note: double spends.

For example, I think that transaction `c3ae41ff748e626706f3e80f18376eeb4d956ef7d62586af31b9e41cd02b40e4` spends a note that has a value of `1000000`. That transaction is confirmed on the chain and the note was updated with `spent: true`.

I think that transaction `ae454f9a02aa105d028e9465744bf906af83a7f2e868dccf771c173ebe29b3fb` was created spending the same note. That transaction expired. When the transaction expired your wallet changed the note from `spent: true` to `spent: false`.

We implemented a fix for this in #3523 , but that change was released in v0.1.71 and you're running v0.1.70.

**Comment by hughy** [comment]
Which RPC are you using when creating transactions?

The `sendTransaction` RPC will update the wallet database after creating a transaction to avoid double spends. You can also prevent double spends by calling `postTransaction` after each `createTransaction`

**Comment by holahula** [comment]
Closing - fixed
