### ISSUE TITLE
Feature: Add transaction initialNoteIndex for `chain/getTransaction`

### ISSUE THREAD

**Issue by hairtail** [iron-fish/ironfish#3693]
### Description

With this feature, `note index` can be calculated offline. Then we can get `noteWitness` with `index` by `chain/getNoteWitness`, then closer to create and sign a transaction offline.

**Comment by hughy** [comment]
#3709 added `noteSize` to the response of `chain/getTransaction`.

You can get `initialNoteIndex` as `initialNoteIndex = noteSize - transaction.notes.length`.

We used `noteSize` to be consistent with other RPCs that use `noteSize` in block headers.
