### ISSUE TITLE
get rpc auth token wrong

### ISSUE THREAD

**Issue by Geapefurit** [iron-fish/ironfish#3798]
### What happened?

When I use 'ironfish rpc:token' to get auth-token,it return wrong value.
It should be same as the value in internal.json.

![1681811569820](https://user-images.githubusercontent.com/25075249/232741068-fd97c99b-fec8-48f7-ba91-04ff47de4ed8.png)

### Version

v0.1.76

**Comment by hughy** [comment]
I'm not able to reproduce this.

Is the `datadir` for your node `/home/coast/ironfish/ironfish-data/`?

**Comment by Geapefurit** [comment]
> I'm not able to reproduce this.
> 
> Is the `datadir` for your node `/home/coast/ironfish/ironfish-data/`?

Sorry,I change the data-dir,but run "ironfish rpc:token" without config of data-dir.
