### ISSUE TITLE
ironfish node stuck

### ISSUE THREAD

**Issue by MiningKiiNG** [iron-fish/ironfish#3811]
### What happened?

the node keeps getting stuck at around 97-98 percent of syncing and then just goes idle

### Version

0.1.76

### Graffiti

there is no graffiti

**Comment by holahula** [comment]
@MiningKiiNG Can you post relevant logs and `ironfish status` output?

**Comment by MiningKiiNG** [comment]
<img width="595" alt="Screenshot 2023-04-20 153846" src="https://user-images.githubusercontent.com/125224762/233501809-1a716006-4994-4f29-b300-bb56bca81707.png">

**Comment by MiningKiiNG** [comment]
I have reset the node twice

**Comment by MiningKiiNG** [comment]
<img width="596" alt="Screenshot 2023-04-20 154426" src="https://user-images.githubusercontent.com/125224762/233502427-8a9e094b-fc3c-430d-abed-382675512158.png">

bootstrap is still testnet maybe?

**Comment by MiningKiiNG** [comment]
<img width="720" alt="Capture" src="https://user-images.githubusercontent.com/125224762/233504008-56e58e46-287c-4b3a-ba4f-d1eb86515d87.PNG">

went to mainent still stuck
