### ISSUE TITLE
windows wallet client

### ISSUE THREAD

**Issue by gabrieldan69** [iron-fish/ironfish#3821]
### Description

please release a updated windows wallet

**Comment by cwkoomy** [comment]
wallet also cannot find , how to start my mining...

**Comment by gabrieldan69** [comment]
i have a windows wallet but keeps crashing.... i use the  linux version, works good but i walt a  GUI version

**Comment by gabrieldan69** [comment]
you can mine it on herominers pool using  bzminer ( best hashrate 8 x rtx3080 ~145 gh/s)

**Comment by gabrieldan69** [comment]
https://ironfish.herominers.com/

**Comment by 108414** [comment]
用了这个钱包的地址了，但是现在钱包进不去了呀！也不知道收到了么！  
![Uploading IMG_20230422_140700_014.jpg…]()

**Comment by holahula** [comment]
@gabrieldan69 the wallet GUI app is a work in progress. You can follow updates on it's progress in discord.
