### ISSUE TITLE
Node won't sync from Docker or CLI

### ISSUE THREAD

**Issue by daveconcannon** [iron-fish/ironfish#383]
I'm running the node from the docker image, ironfish-cli installed and working as expected. Tests all pass. 

As the node attempts to connect to peers, it bans each peer in turn with the following error:

> Peer kPA/lIK (SIN5A) sent an invalid block. score: 10, hash: 00000...6da7a (
>          294880
>        ), reason: error

This repeats endlessly for each peer that connects.

**ironfish status output:**

> Node                 STARTED  @ 3813c31
> P2P Network          CONNECTED - In: 83 KB/s, Out: 5 KB/s, peers 12
> Mining               STOPPED - 0 miners, 0 mined
> Mem Pool             0 tx
> Syncer               IDLE @ 1.83 blocks per seconds
> Blockchain           NOT SYNCED @ HEAD 00007981659f7ae2cc6432543256b67ecc4861e07fd1aab4c8336e12742ad589 (420313)
> Workers              STARTED - 0 -> 0 / 11 - 0 jobs Δ, 6.6 jobs/s

**Version info:**

> name       ironfish
> version    0.1.0
> git        src
> runtime    node/14.18.0

What am I missing?

**Comment by daveconcannon** [comment]
Attached! I've also tested this by starting the node via the CLI, and get the same errors.

**First few peers:**

> Starting sync from fry40zl (sinbad.xoptov.ru). work: +21836971247, ours: 420313, theirs: 327601
> Finding ancestor using linear search on last 3 blocks starting at 00007...ad589 (420313) from peer fry40zl (sinbad.xoptov.ru) at 327601
> Finding ancestor using binary search from fry40zl (sinbad.xoptov.ru), lower: 1, upper: 327601
> Searched for ancestor from fry40zl (sinbad.xoptov.ru), needle: 163801, lower: 1, upper: 327601, hash: 00000...9a745, time: 48.22ms: HIT
> Searched for ancestor from fry40zl (sinbad.xoptov.ru), needle: 245701, lower: 163802, upper: 327601, hash: 00000...2ebd8, time: 51.36ms: HIT
> Searched for ancestor from fry40zl (sinbad.xoptov.ru), needle: 286651, lower: 245702, upper: 327601, hash: 00000...57f77, time: 48.73ms: HIT
> Searched for ancestor from fry40zl (sinbad.xoptov.ru), needle: 307126, lower: 286652, upper: 327601, hash: 00000...f1f23, time: 47.45ms: MISS
> Searched for ancestor from fry40zl (sinbad.xoptov.ru), needle: 296888, lower: 286652, upper: 307125, hash: 00000...764e8, time: 47.31ms: MISS
> Searched for ancestor from fry40zl (sinbad.xoptov.ru), needle: 291769, lower: 286652, upper: 296887, hash: 00000...2aa1f, time: 50.21ms: HIT
> Searched for ancestor from fry40zl (sinbad.xoptov.ru), needle: 294328, lower: 291770, upper: 296887, hash: 00000...e28c9, time: 49.04ms: HIT
> Searched for ancestor from fry40zl (sinbad.xoptov.ru), needle: 295608, lower: 294329, upper: 296887, hash: 00000...cc1f4, time: 48.38ms: MISS
> Searched for ancestor from fry40zl (sinbad.xoptov.ru), needle: 294968, lower: 294329, upper: 295607, hash: 00000...9a662, time: 48.51ms: MISS
> Searched for ancestor from fry40zl (sinbad.xoptov.ru), needle: 294648, lower: 294329, upper: 294967, hash: 00000...aae43, time: 48.45ms: HIT
> Searched for ancestor from fry40zl (sinbad.xoptov.ru), needle: 294808, lower: 294649, upper: 294967, hash: 00000...9f402, time: 47.08ms: HIT
> Searched for ancestor from fry40zl (sinbad.xoptov.ru), needle: 294888, lower: 294809, upper: 294967, hash: 00000...94b55, time: 47.53ms: MISS
> Searched for ancestor from fry40zl (sinbad.xoptov.ru), needle: 294848, lower: 294809, upper: 294887, hash: 00000...8c137, time: 47.28ms: HIT
> Searched for ancestor from fry40zl (sinbad.xoptov.ru), needle: 294868, lower: 294849, upper: 294887, hash: 00000...4bfc9, time: 47.03ms: MISS
> Searched for ancestor from fry40zl (sinbad.xoptov.ru), needle: 294858, lower: 294849, upper: 294867, hash: 00000...25118, time: 70.01ms: HIT
> Searched for ancestor from fry40zl (sinbad.xoptov.ru), needle: 294863, lower: 294859, upper: 294867, hash: 00000...ab8f6, time: 49.79ms: MISS
> Searched for ancestor from fry40zl (sinbad.xoptov.ru), needle: 294860, lower: 294859, upper: 294862, hash: 00000...cbe08, time: 47.30ms: MISS
> Searched for ancestor from fry40zl (sinbad.xoptov.ru), needle: 294859, lower: 294859, upper: 294859, hash: 00000...ef868, time: 48.43ms: MISS
> Found peer fry40zl (sinbad.xoptov.ru) ancestor 00000...25118, syncing from 294858 -> 327601 (32743) after 21 requests
> Requesting 20 blocks starting at 00000...25118 (294858) from fry40zl (sinbad.xoptov.ru)
> Requesting 20 blocks starting at 00000...8acd9 (294878) from fry40zl (sinbad.xoptov.ru)
> Invalid block adding to fork 00000...4dc7a (294880): Invalid spend
> Peer fry40zl (sinbad.xoptov.ru) sent an invalid block. score: 10, hash: 00000...4dc7a (
>           294880
>         ), reason: Invalid spend
> Peer fry40zl (sinbad.xoptov.ru) has been banned: Invalid spend
> Peer fry40zl (sinbad.xoptov.ru) disconnected (DISCONNECTED) while syncing.
> Found peer OmaneJ2 (zzzNODA) ancestor 00000...25118, syncing from 294858 -> 325053 (30195) after 21 requests
> Requesting 20 blocks starting at 00000...25118 (294858) from OmaneJ2 (zzzNODA)
> Requesting 20 blocks starting at 00000...8acd9 (294878) from OmaneJ2 (zzzNODA)
> Invalid block adding to fork 00000...6da7a (294880): Invalid spend
> Peer OmaneJ2 (zzzNODA) sent an invalid block. score: 10, hash: 00000...6da7a (
>           294880
>         ), reason: Invalid spend
> Peer OmaneJ2 (zzzNODA) has been banned: Invalid spend
> Peer OmaneJ2 (zzzNODA) disconnected (DISCONNECTED) while syncing.
> Starting sync from cV8Wktn. work: +21836971247, ours: 420313, theirs: 327601
> Finding ancestor using linear search on last 3 blocks starting at 00007...ad589 (420313) from peer cV8Wktn at 327601
> Finding ancestor using binary search from cV8Wktn, lower: 1, upper: 327601
> Searched for ancestor from cV8Wktn, needle: 163801, lower: 1, upper: 327601, hash: 00000...9a745, time: 46.24ms: HIT
> Searched for ancestor from cV8Wktn, needle: 245701, lower: 163802, upper: 327601, hash: 00000...2ebd8, time: 46.34ms: HIT
> Searched for ancestor from cV8Wktn, needle: 286651, lower: 245702, upper: 327601, hash: 00000...57f77, time: 52.09ms: HIT
> Searched for ancestor from cV8Wktn, needle: 307126, lower: 286652, upper: 327601, hash: 00000...f1f23, time: 45.27ms: MISS
> Searched for ancestor from cV8Wktn, needle: 296888, lower: 286652, upper: 307125, hash: 00000...764e8, time: 45.57ms: MISS
> Searched for ancestor from cV8Wktn, needle: 291769, lower: 286652, upper: 296887, hash: 00000...2aa1f, time: 44.91ms: HIT
> 
> Searched for ancestor from cV8Wktn, needle: 294328, lower: 291770, upper: 296887, hash: 00000...e28c9, time: 46.23ms: HIT
> Searched for ancestor from cV8Wktn, needle: 295608, lower: 294329, upper: 296887, hash: 00000...cc1f4, time: 43.40ms: MISS
> Searched for ancestor from cV8Wktn, needle: 294968, lower: 294329, upper: 295607, hash: 00000...9a662, time: 45.16ms: MISS
> Searched for ancestor from cV8Wktn, needle: 294648, lower: 294329, upper: 294967, hash: 00000...aae43, time: 46.44ms: HIT
> Searched for ancestor from cV8Wktn, needle: 294808, lower: 294649, upper: 294967, hash: 00000...9f402, time: 43.89ms: HIT
> Searched for ancestor from cV8Wktn, needle: 294888, lower: 294809, upper: 294967, hash: 00000...94b55, time: 42.26ms: MISS
> Searched for ancestor from cV8Wktn, needle: 294848, lower: 294809, upper: 294887, hash: 00000...8c137, time: 44.91ms: HIT
> Searched for ancestor from cV8Wktn, needle: 294868, lower: 294849, upper: 294887, hash: 00000...4bfc9, time: 46.81ms: MISS
> Searched for ancestor from cV8Wktn, needle: 294858, lower: 294849, upper: 294867, hash: 00000...25118, time: 45.19ms: HIT
> Searched for ancestor from cV8Wktn, needle: 294863, lower: 294859, upper: 294867, hash: 00000...ab8f6, time: 43.65ms: MISS
> Searched for ancestor from cV8Wktn, needle: 294860, lower: 294859, upper: 294862, hash: 00000...cbe08, time: 44.70ms: MISS
> Searched for ancestor from cV8Wktn, needle: 294859, lower: 294859, upper: 294859, hash: 00000...ef868, time: 42.64ms: MISS
> Found peer cV8Wktn ancestor 00000...25118, syncing from 294858 -> 327601 (32743) after 21 requests
> Requesting 20 blocks starting at 00000...25118 (294858) from cV8Wktn
> Requesting 20 blocks starting at 00000...8acd9 (294878) from cV8Wktn
> Peer cV8Wktn sent an invalid block. score: 10, hash: 00000...4dc7a (
>           294880
>         ), reason: error
> Peer cV8Wktn has been banned: error
> Peer cV8Wktn disconnected (DISCONNECTED) while syncing.

**Comment by deekerno** [comment]
@daveconcannon One of our recent PRs (#393) has fixed this issue and we've released an update. Please update your node and check that it works.
