### ISSUE TITLE
Node STOPPED

### ISSUE THREAD

**Issue by DerClownU** [iron-fish/ironfish#3845]
### What happened?

A bug happened!

`C:\Windows\system32>ironfish status
Version              1.0.0 @ 79e7e05
Node                 STOPPED
Node Name
Block Graffiti
Memory               Heap: 0 B -> 0 B / 3.98 GiB (0.0%), RSS: 0 B (0.0%), Free: 0 B (100.0%)
CPU                  Cores: 8, Current: 0.0%
P2P Network          WAITING - In: 0 B/s, Out: 0 B/s, peers 0
Mining               STARTED - 0 miners, 0 mined
Mem Pool             Count: 0 tx, Bytes: 0 B / 57.22 MiB (0.00%), Evictions: 0
Syncer               STOPPED
Blockchain           000000000000002a12624ab52d083fb997e242de07a55cae0274b3a1c4ecbde7 (6824), Since HEAD: 5m 40s (SYNCED)
Accounts             000000000000002a12624ab52d083fb997e242de07a55cae0274b3a1c4ecbde7 (6824)
Telemetry            STOPPED
Workers              STOPPED`

`C:\Windows\system32>ironfish start

::::::::::          :::::::::::::::::
::::::::::::       :::::::::::::::::::
:::::::::::::     :::::::::::::::::::::
::::::::::::::   ::::::::::::::::::::::::
 ::::::::::::: ::::::::::        :::::::::
   :::::::::::::::::::::          ::::::::::
   :::::::::::::::::::::          :::::::::
 ::::::::::::: ::::::::::        :::::::::
::::::::::::::   ::::::::::::::::::::::::
:::::::::::::     :::::::::::::::::::::
::::::::::::       :::::::::::::::::::
::::::::::           ::::::::::::::::

Version       1.0.0 @ 79e7e05
Node Name     NONE
Graffiti      NONE
Peer Identity cZyAr7iFKM4fsfRoE4u3JU3xbMxB0n/3xIuCxcGJoyY=
Peer Agent    ironfish/1.0.0/79e7e05
Peer Port     9033
Bootstrap     1.main.bn.ironfish.network,2.main.bn.ironfish.network

WebSocket server started at :::9033
Connected to the Iron Fish network
Starting sync from 31XVZuZ. work: +677553719363064397, ours: 6824, theirs: 6826
Finding ancestor using linear search on last 3 blocks starting at 00000...cbde7 (6824) from peer 31XVZuZ at 6826
Found peer 31XVZuZ ancestor 00000...cbde7, syncing from 6824 -> 6826 (2) after 1 requests
Requesting 25 blocks starting at 00000...cbde7 (6824) from 31XVZuZ
Finished syncing from 31XVZuZ`

It doesn't want to start.

### Version

1.0.0 @ 79e7e05

**Comment by DerClownU** [comment]
I update it to Version  1.0.1 @ 03bfdc4

it doesn't help me

`C:\Windows\system32>ironfish status
Version              1.0.1 @ 03bfdc4
Node                 STOPPED
Node Name
Block Graffiti
Network              Mainnet
Memory               Heap: 0 B -> 0 B / 3.98 GiB (0.0%), RSS: 0 B (0.0%), Free: 0 B (100.0%)
CPU                  Cores: 8, Current: 0.0%
P2P Network          WAITING - In: 0 B/s, Out: 0 B/s, peers 0
Mining               STARTED - 0 miners, 0 mined
Mem Pool             Count: 0 tx, Bytes: 0 B / 57.22 MiB (0.00%), Evictions: 0
Syncer               STOPPED
Blockchain           0000000000000009c999bc01488997a888ca1965465a9ad3e3ad53403c3053d6 (6828), Since HEAD: 14m 55s (SYNCED)
Accounts             0000000000000009c999bc01488997a888ca1965465a9ad3e3ad53403c3053d6 (6828)
Telemetry            STOPPED
Workers              STOPPED`

**Comment by AmberKiso** [comment]
`ironfish start` just starts the node. And it automatically requests blocks from peers, which it did up to the head of the blockchain (6826).
To start _mining_ read the instructions here: https://ironfish.network/use/get-started/mining#join-a-mining-pool
You should have GPUs to join a mining pool. CPUs are no longer useful to mine with.

**Comment by DerClownU** [comment]
I don't want to start mining, i use other miner. I wanna see my wallet and balance.

**Comment by wd021** [comment]
@DerClownU i don't see any errors. are you closing the window for your node? you need to keep it open/running in the background for it to persist.

**Comment by AmberKiso** [comment]
https://ironfish.network/use/get-started/wallet-commands#account-balance
Wallet commands are in there.
ironfish wallet:accounts will show you the wallets on your node.

**Comment by hughy** [comment]
Closing this issue. It looks like the node was running without errors. Please re-open if you're running into an error!
