### ISSUE TITLE
No Balance in my Wallet

### ISSUE THREAD

**Issue by Alan911Black** [iron-fish/ironfish#3887]
### What happened?

i installed the Wallet and start mining into it, unfortunately no balance

![Untitled](https://user-images.githubusercontent.com/31937768/236072153-c2db0322-7ee5-4349-9fbd-5c0fb8060816.jpg)

whats wrong?

**Comment by hughy** [comment]
Your node needs to sync the chain in order for your wallet to scan transactions that it may have received (including miner's fee transactions).

You can start your node with `ironfish start` and it will start syncing from the network automatically.
