### ISSUE TITLE
Connection Refused error

### ISSUE THREAD

**Issue by rodionlim** [iron-fish/ironfish#42]
Getting the following error when starting a node and checking the status.
```Error: connect ECONNREFUSED 54.84.67.207:9033``` 

![image](https://user-images.githubusercontent.com/47183406/114266339-6479b800-9a28-11eb-88a0-dcb4f69c0a1c.png)

**Comment by pkrasam** [comment]
@rodionlim  try updating your `config.json` w/ additional [bootstrapNodes](https://discord.com/channels/771503434028941353/828778383918891038/830277215358156800)

**Comment by rodionlim** [comment]
Removing the docker container and launching a new instance seem to have fixed it. Somehow, docker containers are not shutting down by themselves even with --rm flag specified and sending a ironfish stop command via a separate process

**Comment by dguenther** [comment]
Ah, it was probably conflicting on that port with the existing node. Glad you figured it out!
