### ISSUE TITLE
[Error Broadcast Transaction By rpc]

### ISSUE THREAD

**Issue by GeassV** [iron-fish/ironfish#4239]
### What happened?

A bug happened!
Have always run scripts to send Ironfish by RPC with Ironfish Node 1.5.0 successfully.

After updating to Node 1.7.1 with the fascinating changes, the broadcast RPC always throws error "Peer network is not ready"

Updated to Node 1.8.0 once released. No error thrown, transaction id got. However, the transactions can never be found on the chain.

Rolled back to Node 1.5.0, everything recovered. Could you please fix or update the RPC usage for the new releases

### Version

v1.8 v1.7.1 v1.5

### Debug output

```shell
ERROR Log for Node v1.7.1

ironfish postTransaction failed {"code": "validaation", "data": null, "message": "Cannot
broadcast transaction. Peer network is not ready", "stack": "ValidationError: Cannot broadcast
transaction. Peer network is not ready
at /home/ps/.nvm/versions/node/v18.16.0/lib/node_modules/ironfish/node_modules/@ironfish/sd
k/build/src/rpc/routes/chain/broadcastTransaction.js:45:15
at Router.route (/home/ps/.nvm/versions/node/v18.16.0/lib/node_modules/ironfish/node_module
s/@ironfish/sdk/build/src/rpc/routes/router.js:57:19D
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async RpcHttpAdapter.handleRequest (/home/ps/.nvmVversions/node/v18.16.0/lib/node_module
s/ironfish/node_modules/@ironfish/sdk/build/src/rpc/adapters/httpAdapter.js:166:9)", "status":
400}
```

**Comment by hughy** [comment]
The response from `wallet/broadcastTransaction` in v1.8.0 includes a boolean field `broadcasted` that indicates whether the transaction was broadcasted to the network. Does the transaction broadcast in v1.8.0?

The `Peer network is not ready` message indicates that your node's peer network is either not running or does not have enough connected peers to send the transaction to. The default config for `minPeers` is 1. Have you changed this configuration for your node?

**Comment by hughy** [comment]
Could you share the output of either `ironfish status` or the `node/getStatus` RPC?

I'm interested in the "P2P Network" output to see the status of your node's peer network

**Comment by GeassV** [comment]
> Could you share the output of either `ironfish status` or the `node/getStatus` RPC?
> 
> I'm interested in the "P2P Network" output to see the status of your node's peer network

Sure. Peer Network Error is for v1.7.1
Here goes ironfish status:
Version              1.7.1 @ 226715c
Node                 STARTED
Node Name
Peer ID              wM8ErvC4v6Tz6cvoXweOXyJx2FbLrdXAmqc09b4xk2U=
Block Graffiti
Network              Mainnet
Memory               Heap: 138.68 MiB -> 171.02 MiB / 3.99 GiB (3.4%), RSS: 1.33 GiB (0.1%), Free: 967.40 GiB (2.8%)
CPU                  Cores: 32, Current: 1.4%
P2P Network          CONNECTED - In: 179 B/s, Out: 951 B/s, peers 50
Mining               STARTED - 0 miners, 0 mined
Mem Pool             Count: 0 tx, Bytes: 0 B / 57.22 MiB (0.00%), Evictions: 0
Syncer               IDLE - 45.66 blocks added/sec
Blockchain           0000000000000056dea82c6598106781af83e36227c6a655ea6d7172cd09a0fd (181135), Since HEAD: 3m 55s (SYNCED)
Accounts             0000000000000056dea82c6598106781af83e36227c6a655ea6d7172cd09a0fd (181135)
Telemetry            STOPPED
Workers              STARTED - 0 -> 0 / 6 - 0 jobs Δ, 0.06 jobs/s

and here goes `node/getStatus`
{
    "status": 200,
    "data": {
        "peerNetwork": {
            "peers": 50,
            "isReady": true,
            "inboundTraffic": 279.23824141249105,
            "outboundTraffic": 954.4839551351234,
            "publicIdentity": "wM8ErvC4v6Tz6cvoXweOXyJx2FbLrdXAmqc09b4xk2U="
        },
        "blockchain": {
            "synced": true,
            "head": {
                "hash": "00000000000000ad90704f70f31a4303ca3849a117d3603f7f3b33d9853824fd",
                "sequence": 181138
            },
            "headTimestamp": 1692807783753,
            "newBlockSpeed": 0,
            "dbSizeBytes": 2491635384
        },
        "node": {
            "status": "started",
            "version": "1.7.1",
            "git": "226715c",
            "nodeName": "",
            "networkId": 1
        },
        "cpu": {
            "cores": 32,
            "percentRollingAvg": 11.6934753184217,
            "percentCurrent": 14.093370473537606
        },
        "memory": {
            "heapMax": 4293977536,
            "heapTotal": 180383744,
            "heapUsed": 147743288,
            "rss": 1427374080,
            "memFree": 1038779879424,
            "memTotal": 1068998307840
        },
        "miningDirector": {
            "status": "started",
            "miners": 0,
            "blocks": 0,
            "blockGraffiti": "",
            "newEmptyBlockTemplateSpeed": 0,
            "newBlockTemplateSpeed": 0,
            "newBlockTransactionsSpeed": 0
        },
        "memPool": {
            "size": 1,
            "sizeBytes": 2608,
            "maxSizeBytes": 60000000,
            "evictions": 0,
            "recentlyEvictedCache": {
                "size": 0,
                "maxSize": 60000
            }
        },
        "blockSyncer": {
            "status": "idle",
            "syncing": {
                "blockSpeed": 21.91,
                "speed": 0.03,
                "downloadSpeed": 792.1,
                "progress": 0.9999887540673769
            }
        },
        "telemetry": {
            "status": "stopped",
            "pending": 0,
            "submitted": 0
        },
        "workers": {
            "started": true,
            "workers": 6,
            "executing": 0,
            "queued": 0,
            "capacity": 6,
            "change": 0,
            "speed": 14.42
        },
        "accounts": {
            "head": {
                "hash": "00000000000000ad90704f70f31a4303ca3849a117d3603f7f3b33d9853824fd",
                "sequence": 181138
            }
        },
        "misc": {
            "uvMonitorActive": true,
            "uvActiveReqs": 1
        }
    }
}

**Comment by GeassV** [comment]
> Could you share the output of either `ironfish status` or the `node/getStatus` RPC?
> 
> I'm interested in the "P2P Network" output to see the status of your node's peer network

Since it's easier to update than rollback. maybe we can focus on v1.8 to see how we can solve the issue

**Comment by hughy** [comment]
Thanks for sharing these!

It's odd that the `isReady` field in the getStatus response shows `true` because that's the property being checked when the `Peer network is not ready` error is thrown 🤔

**Comment by GeassV** [comment]
> Could you share the output of either `ironfish status` or the `node/getStatus` RPC?
> 
> I'm interested in the "P2P Network" output to see the status of your node's peer network

caught the status with "peer network error" this time:
```

{
    "status": 200,
    "data": {
        "peerNetwork": {
            "peers": 49,
            "isReady": false,
            "inboundTraffic": 1803.5278004073123,
            "outboundTraffic": 2043.5508518946413,
            "publicIdentity": "odojTgiXSnWtJBhlmvcnIlJDgMZwWO9iwXvt5+fAckM="
        },
        "blockchain": {
            "synced": true,
            "head": {
                "hash": "000000000000001fdab48f50fbc85075ad668356256feed5ec3c8be155ac285f",
                "sequence": 181192
            },
            "headTimestamp": 1692811407578,
            "newBlockSpeed": 0,
            "dbSizeBytes": 2491837945
        },
        "node": {
            "status": "started",
            "version": "1.7.1",
            "git": "226715c",
            "nodeName": "",
            "networkId": 1
        },
        "cpu": {
            "cores": 32,
            "percentRollingAvg": 9.607772049347338,
            "percentCurrent": 1.6485393258426966
        },
        "memory": {
            "heapMax": 4294043208,
            "heapTotal": 170692608,
            "heapUsed": 117517376,
            "rss": 1441124352,
            "memFree": 1052613226496,
            "memTotal": 1068998467584
        },
        "miningDirector": {
            "status": "started",
            "miners": 0,
            "blocks": 0,
            "blockGraffiti": "",
            "newEmptyBlockTemplateSpeed": 0,
            "newBlockTemplateSpeed": 0,
            "newBlockTransactionsSpeed": 0
        },
        "memPool": {
            "size": 0,
            "sizeBytes": 0,
            "maxSizeBytes": 60000000,
            "evictions": 0,
            "recentlyEvictedCache": {
                "size": 0,
                "maxSize": 60000
            }
        },
        "blockSyncer": {
            "status": "idle",
            "syncing": {
                "blockSpeed": 24.66,
                "speed": 0.03,
                "downloadSpeed": 874.01,
                "progress": 1
            }
        },
        "telemetry": {
            "status": "stopped",
            "pending": 0,
            "submitted": 0
        },
        "workers": {
            "started": true,
            "workers": 6,
            "executing": 0,
            "queued": 0,
            "capacity": 6,
            "change": 0,
            "speed": 83.24
        },
        "accounts": {
            "head": {
                "hash": "000000000000001fdab48f50fbc85075ad668356256feed5ec3c8be155ac285f",
                "sequence": 181192
            }
        },
        "misc": {
            "uvMonitorActive": true,
            "uvActiveReqs": 0
        }
    }
}
```
How can I deal with that, wait until peers get ready or restart the node?

**Comment by GeassV** [comment]
this may be the situation:
for node v1.5.0, peer network is not considered. I found transaction successfully broadcasted with following node status.
```
Version              1.5.0 @ e27a127
Node                 STARTED
Node Name
Peer ID              EHndawv3PH14WBMgfMGMGQI8yBxDPxVCuaBZm+SdHSI=
Block Graffiti
Network              Mainnet
Memory               Heap: 92.67 MiB -> 121.34 MiB / 3.99 GiB (2.3%), RSS:
1.02 GiB (0.1%), Free: 980.48 GiB (1.5%)
CPU                  Cores: 32, Current: 1.8%
P2P Network          WAITING - In: 1 B/s, Out: 1.52 KB/s, peers 50
Mining               STARTED - 0 miners, 0 mined
Mem Pool             Count: 1 tx, Bytes: 2.19 KiB / 57.22 MiB (0.00%),
Evictions: 0
Syncer               IDLE - 45.19 blocks added/sec
Blockchain           000000000000005582a7cb140d5c3fcce813d428861b68c04aa7b21a4b
0eb1c0 (181222), Since HEAD: 1m 31s (SYNCED)
Accounts             000000000000005582a7cb140d5c3fcce813d428861b68c04aa7b21a4b
0eb1c0 (181222)
Telemetry            STOPPED
Workers              STARTED - 0 -> 0 / 6 - 0 jobs Δ, 0.05 jobs/s
```
But for node v1.7.1, error "Peer network is not ready" will be thrown with above node status.
And for node v1.8, error will not be thrown, but has to check broadcasted value from the response.
Is it?

**Comment by hughy** [comment]
> But for node v1.7.1, error "Peer network is not ready" will be thrown with above node status.
And for node v1.8, error will not be thrown, but has to check broadcasted value from the response.
Is it?

That's correct, the check for peer network status before broadcast was added here: https://github.com/iron-fish/ironfish/pull/4106

The only thing I can think of that would prevent the peer network from being ready is the configuration of `minPeers`. Could you share `ironfish config` on v1.8.0?

**Comment by GeassV** [comment]
> > But for node v1.7.1, error "Peer network is not ready" will be thrown with above node status.
> > And for node v1.8, error will not be thrown, but has to check broadcasted value from the response.
> > Is it?
> 
> That's correct, the check for peer network status before broadcast was added here: #4106
> 
> The only thing I can think of that would prevent the peer network from being ready is the configuration of `minPeers`. Could you share `ironfish config` on v1.8.0?

You're right. All the minPeers of node v1.5, v1.7.1, v1.8.0 are set as 100. Cannot remember why I did that. Assume that's the reason for not ready even get 50 peers

**Comment by hughy** [comment]
That might be it! You could try setting `minPeers` to a lower value -- it's only used to determine whether the node is ready to start sending messages to the peer network

**Comment by GeassV** [comment]
> That might be it! You could try setting `minPeers` to a lower value -- it's only used to determine whether the node is ready to start sending messages to the peer network

Yeah, just deleted the config for minPeers. Peer Network Status changed. Really appreciate the help. I will keep it with v1.7.1. Hope everything goes well

**Comment by hughy** [comment]
Excellent! Thanks for helping to sort out this issue!
