### ISSUE TITLE
Lowercase transaction hash not found on Explorer

### ISSUE THREAD

**Issue by Daniel-Fernandez-951** [iron-fish/ironfish#427]
https://github.com/iron-fish/ironfish/blob/7e479fe46f9e896f78c5d94c0f6f258c65711668/ironfish-cli/src/commands/accounts/pay.ts#L206

https://github.com/iron-fish/ironfish/blob/48b6bd4b99fd459e2ba7c8a99e51713f0cc72e4d/ironfish-cli/src/commands/accounts/pay.ts#L202

**Comment by dguenther** [comment]
This should be fixed now -- please reopen with steps to reproduce the problem if you're still seeing this issue.
