### ISSUE TITLE
npm uninstall -g ironfish

### ISSUE THREAD

**Issue by sacredland** [iron-fish/ironfish#4292]
### What happened?

I want to unistall all the cli wallet. I am not mining/keeping any ironfish. I would like to eliminate all it's related. npm uninstall -g ironfish show an error.. the usal one... npm ERR! ENOTEMPTY: directory not empty, rename '/usr/local/lib/node_modules/ironfish' -> '/usr/local/lib/node_modules/.ironfish-c9b0NOiO'

I don't want to move/rename, I want to delete it. I just rm -rf the rep and it's done?

**Comment by dguenther** [comment]
Using `npm uninstall -g ironfish` will remove it, but apparently it does a rename or a move first. You can try

```
sudo rm -rf `/usr/local/lib/node_modules/.ironfish-c9b0NOiO
npm uninstall -g ironfish
```

and if that doesn't work, you can just rm -rf the folder directly. I believe you'll need to remove the binary as well, but this will all be specific to your particular computer. I think these should be the things you'd need to rm -rf:

```
sudo rm -rf `/usr/local/lib/node_modules/ironfish`
sudo rm -rf `/usr/local/bin/ironfish`
```
