### ISSUE TITLE
ironfish-graph-explorer dependencies 

### ISSUE THREAD

**Issue by testingPurposes1** [iron-fish/ironfish#440]
Graph explorer requires webpack-cli >= 4.9.0 to start,  master/staging branch has only 4.6.0 version in devDependencies
<img width="1245" alt="Screenshot 2021-11-19 at 16 58 09" src="https://user-images.githubusercontent.com/63149499/142603683-bb25ef96-1b33-40ef-ba43-be7707a16fb2.png">

**Comment by NullSoldier** [comment]
@testingPurposes1 Hello, did you claim your points for the test net on our website? If not you should get credited for this report. https://forms.gle/yrAtzoyKTwLgLTRZA

**Comment by testingPurposes1** [comment]
> @testingPurposes1 Hello, did you claim your points for the test net on our website? If not you should get credited for this report. https://forms.gle/yrAtzoyKTwLgLTRZA

Thanks, I'll do
