### ISSUE TITLE
Error 500 when user click in your name in Personal Account 

### ISSUE THREAD

**Issue by thedruny** [iron-fish/ironfish#482]
username - bezruk

When the user clicks on his name in the Personal Account, he sees this error on his screen and in the console.

Steps:
1. Login in your account
2. Сlick on your nickname in the header

![Screenshot_5](https://user-images.githubusercontent.com/53578081/144129266-b23d793e-2edd-4254-9c68-c37b65020e54.png)
e
![Screenshot_6](https://user-images.githubusercontent.com/53578081/144129339-597c019d-412e-4f45-be2e-8bd657a745df.png)
.

**Comment by thedruny** [comment]
username - bezruk

**Comment by dguenther** [comment]
Thanks, we're working on fixing this now.

**Comment by dguenther** [comment]
This should be fixed now.
