### ISSUE TITLE
run ironfish Log stuck

### ISSUE THREAD

**Issue by mrliu998** [iron-fish/ironfish#488]
docker runs ironfish log for the first time and gets stuck,I don't know if the node is running。
![IMG_20211201_000612](https://user-images.githubusercontent.com/95321571/144145933-8030837d-fa71-45c3-8969-a9f5d3d8feae.jpg)

**Comment by deekerno** [comment]
`ironfish logs` effectively runs `tail -f` on the log file; the command output will only update when the server logs update with node activity.
