### ISSUE TITLE
ironfish miners:mined not showing correct results

### ISSUE THREAD

**Issue by saneeshps** [iron-fish/ironfish#491]
HI Team

I have mined 2 blocks successfully, but when I view the blocks mined (ironfish miners:mined) its showing 4 entries.  The last 2 blocks are not mine. Why is showing like that?
My graffiti : saneesh.eth
Mail id : saneesh4crypto@protonmail.com

# ironfish miners:mined
Scanning for mined blocks
Exporting mined block from 1 -> 5330
0000000cfc52c6c94102da5599cc30a99ec2855f9a2c035c49b01debb2908679 saneesh.eth 20 MAIN 2844: view in web
000000036d19ee8336fed688f744e496bb24402a3713791f7f9048f8c942604d saneesh.eth 20 MAIN 2910: view in web
0000000050597dfe10efa0d797907ba3333f87dcd4f2b912053a9024b118827a saneesh.eth 20 MAIN 4685: view in web
000000003bed9482f67d684d1dff5007b3855defde3f83fcaac6eb4159521150 saneesh.eth 20 MAIN 4702: view in web
Exporting blocks: [========================================] 5325/5330 99% | ETA: soon | SEQ 5326#

![iron fish issue](https://user-images.githubusercontent.com/28531624/144249372-ca6198f4-a2f0-4a05-bde7-d5d758a18c92.png)

**Comment by dguenther** [comment]
This should be fixed now in the latest release. Please reopen this issue and post your Iron Fish version if you're still seeing the problem.
