### ISSUE TITLE
Wrong block listed in the mined blocks list: ironfish miners:mined

### ISSUE THREAD

**Issue by sebastiantf** [iron-fish/ironfish#492]
Running `ironfish miners:mined` listed a block that was not actually mined by my node, from the looks of it on the explorer

Screenshots:
<img width="936" alt="Screenshot 2021-12-01 at 7 43 17 PM" src="https://user-images.githubusercontent.com/36922376/144249713-56440759-3085-4dc1-8042-ec8d2f286439.png">

Link to block explorer: https://explorer.ironfish.network/blocks/0000000050597dfe10efa0d797907ba3333f87dcd4f2b912053a9024b118827a

<img width="1031" alt="Screenshot 2021-12-01 at 7 44 05 PM" src="https://user-images.githubusercontent.com/36922376/144249839-eaf79489-6d27-45c3-908d-a7dcae32db11.png">

My graffiti was `sebastiantf` then later changed to `sebastianf`. But I've never used the graffiti mentioned in the block explorer - `gunwest123#2565`

Number of blocks mined in the status report also stays at zero
<img width="764" alt="Screenshot 2021-12-01 at 7 45 38 PM" src="https://user-images.githubusercontent.com/36922376/144250080-714bc75c-3184-4809-baf9-65e7aeac1d5d.png">

**Comment by dguenther** [comment]
This should be fixed in the current release -- please reopen if you're still running into this issue.
