### ISSUE TITLE
Incorrect IRON for the number of blocks I mined

### ISSUE THREAD

**Issue by georeith** [iron-fish/ironfish#500]
Node: Sports

I mined 15 blocks but have 200 IRON.
I noticed I have been consistently 5 block rewards out since the start of the testnet.

![unknown](https://user-images.githubusercontent.com/3090066/144309958-b3d0779a-6fb6-4808-8b49-18310cc4115f.png)

**Comment by CumpsD** [comment]
Same here with 10 blocks:

```
ubuntu: ~/ironfish-src/ironfish-cli$ yarn start:once status --datadir /home/ubuntu/ironfish
yarn run v1.22.17
$ yarn build && yarn start:js status --datadir /home/ubuntu/ironfish
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run status --datadir /home/ubuntu/ironfish

Version              0.1.6 @ 4b3079f
Node                 STARTED
P2P Network          CONNECTED - In: 1 KB/s, Out: 51 KB/s, peers 50
Mining               STARTED - 1 miners, 10 mined
Mem Pool             1 tx
Syncer               IDLE @ 0.05 blocks per seconds | avg time to add block 69.29 ms
Blockchain           SYNCED @ HEAD 000000005507a0dc81983f15f5729264c6b5bf6dd3bd34be1f2bb137b8333d1e (4149)
Workers              STARTED - 0 -> 0 / 31 - 0 jobs Δ, 0.6 jobs/s
Done in 1.62s.
ubuntu:~/ironfish-src/ironfish-cli$ yarn start:once accounts:balance --datadir /home/ubuntu/ironfish
yarn run v1.22.17
$ yarn build && yarn start:js accounts:balance --datadir /home/ubuntu/ironfish
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run accounts:balance --datadir /home/ubuntu/ironfish
The account balance is:    $IRON 200.00000000 ($ORE 20,000,000,000)
Amount available to spend: $IRON 200.00000000 ($ORE 20,000,000,000)
Done in 1.67s.
ubuntu:~/ironfish-src/ironfish-cli$
```

**Comment by deekerno** [comment]
When you successfully mine a block on your node, it does not necessarily mean that it will be included on the main chain. You and every other miner on the network are competing to mine the same block, and thus it is entirely possible that another miner submitted their block to the network just moments before yours.

The `mined` part of the `Mining` line in the status output indicates the number of blocks that have been mined during _the current session_. You can use `ironfish miners:mined` to show you which blocks on the main chain have been mined by your account.

**Comment by georeith** [comment]
@deekerno maybe the number should not be incremented in status until the block is accepted by the chain?

This still seems like a bug regardless of how it works under the hood you don't need to expose that.

**Comment by deekerno** [comment]
I see how it can still seem like a bug, so I'll share it with the team and we'll decide on a course of action. Thanks!
