### ISSUE TITLE
Available balance does not match account balance

### ISSUE THREAD

**Issue by georeith** [iron-fish/ironfish#502]
Node: Sports

My account balance does not match my available balance, I have not made any transactions.

![balance](https://user-images.githubusercontent.com/3090066/144310184-3e39ddce-8e38-413f-bdc5-0d62153f60ad.png)

**Comment by georeith** [comment]
I tried restarting the node as mentioned in #501 but it did not fix the issue

**Comment by ufukblockchain** [comment]
Same for me too, upgrade to .7 and reboot didnt fix. 

The account balance is:    $IRON 100.00000000 ($ORE 10,000,000,000)
Amount available to spend: $IRON 60.00000000 ($ORE 6,000,000,000)

**Comment by georeith** [comment]
Not fixed by https://github.com/iron-fish/ironfish/releases/tag/v0.1.8

**Comment by daveconcannon** [comment]
0.1.9:

> The account balance is:    $IRON NaN ($ORE NaN)
> Amount available to spend: $IRON NaN ($ORE NaN)
> Done in 0.70s.

**Comment by daveconcannon** [comment]
Same issue with 0.1.10.
