### ISSUE TITLE
mined blocks not reflecting

### ISSUE THREAD

**Issue by saneeshps** [iron-fish/ironfish#504]
ironfish status is showing as 1 block mined.

![image](https://user-images.githubusercontent.com/28531624/144312856-c9fbd390-2f5a-4871-b57b-920cc3f31ed7.png)

But when I check the **ironfish miners:mined** and **ironfish accounts:balance** its not reflected there

![image](https://user-images.githubusercontent.com/28531624/144313065-7644ae49-d88b-4802-add0-81c5bf4497e3.png)

**Comment by deekerno** [comment]
When you successfully mine a block on your node, it does not necessarily mean that it will be included on the main chain. You and every other miner on the network are competing to mine the same block, and thus it is entirely possible that another miner submitted their block to the network just moments before yours. This same possibility is true for every miner on the network.
