### ISSUE TITLE
CLI link to explorer doesn't work

### ISSUE THREAD

**Issue by alterkahn** [iron-fish/ironfish#511]
Recently I transferred 1 IRON from `39423d564734cffa2a79bcd1b9da59a3c392de0d3d264ca93a85394231aeb4facd43dd59d7a5cd8367a84c` to `06a81184071fbec0820a06274454d01c7ff10e079122c76bd20710d17c48cfc9175b195de8f1b360595107` with a fee of 0.00000001 IRON (https://explorer.ironfish.network/transaction/9e1c4f45e110c0b581b7bbe2d311a84b06a8920166cce782733e26273eb0fb6b)and it was successful tx, but the https://explorer.ironfish.network/ doesn't show it. Though I can find it via the search line with my tx hash, it is next: 9e1c4f45e110c0b581b7bbe2d311a84b06a8920166cce782733e26273eb0fb6b

**Comment by deekerno** [comment]
@brekk's recent PR on the block explorer repository has fixed this issue.
