### ISSUE TITLE
[Bug] nodeWorkers parameter in config file does't work

### ISSUE THREAD

**Issue by Qloun** [iron-fish/ironfish#518]
**nodeWorkers** parameter set 4, but miner still works on the maximum possible number of threads

![image](https://user-images.githubusercontent.com/35996623/144333916-1a9271fa-b866-45bc-b6b0-7ae479d7e148.png)
![image](https://user-images.githubusercontent.com/35996623/144333998-d4e280ea-0c3c-4258-ba8c-020de03bb362.png)
![image](https://user-images.githubusercontent.com/35996623/144334417-f23671ec-55b9-455f-a001-d3928b93ddf7.png)

**Comment by Qloun** [comment]
![image](https://user-images.githubusercontent.com/35996623/144398851-3a68d3f5-b953-4de7-9db8-a817617e786e.png)

**Comment by dguenther** [comment]
`nodeWorkers` only changes how many processes the node uses. To change how many threads the miner uses, you need to change your `miners:start` command from `miners:start -t -1` to `miners:start -t 6`, if you want the miner to use 6 threads.
