### ISSUE TITLE
MacBook Pro doesn't proccess any ironfish command on the local machine

### ISSUE THREAD

**Issue by georgekhelidze** [iron-fish/ironfish#524]
**STR**:

1. Start node
2. Start mining
3. Open new window and run the command (ex. ironfish logs, ironfish status, ironfish faucet)

**A.R:** Just nothing happened. Mac and terminal are responsive, but on the terminal screen u don't see any action except jump to new row [https://gyazo.com/eb3dff32a519c9cb92a202c884a161a0](url)
**E.R:** Command work as expected

**Comment by bogdanteodoru** [comment]
@georgekhelidze what OS are you on? I just download the latest code and tried it on my local env and it worked without any issues.

**Comment by georgekhelidze** [comment]
MacOS Monterey 12.0.1

**Comment by bogdanteodoru** [comment]
@georgekhelidze are you using the latest version? Just tried again now pulling the code from github and have same OS as yours and didn't have any issues.

**Comment by georgekhelidze** [comment]
@bogdanteodoru After full reinstall from scratch it works right now. But it's really weird.
