### ISSUE TITLE
CORS problem on https://testnet.ironfish.network/ site (login, leaderboard pages)

### ISSUE THREAD

**Issue by verkhohliad** [iron-fish/ironfish#526]
![image](https://user-images.githubusercontent.com/23651458/144427124-608a4a2c-baf2-41d3-8083-854407b29057.png)

**Comment by dguenther** [comment]
This isn't happening for me, can you re-test it? Also you might see if you have issues with any of the public API endpoints here: https://api.ironfish.network/docs/

**Comment by verkhohliad** [comment]
> This isn't happening for me, can you re-test it? Also you might see if you have issues with any of the public API endpoints here: https://api.ironfish.network/docs/

yeah, it's already fixed, thx
