### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by mettler** [iron-fish/ironfish#530]
While mining, I've noticed steady gradual memory usage increases, presumably due to leaks.  

On an M1 Pro after an hour, the mining node process consumes about 2G. Roughly 10M is leaking every ~10 seconds or so. 

Killing and restarting the mining node process drops memory back down to original levels (300-600MB), before slowly rising again.

Running: 
Version       0.1.7 @ src

**Comment by dguenther** [comment]
Could you retest on version 0.1.9 to see if this is still an issue for you? We made a fix in that version to address the mining process leaking memory.

**Comment by dguenther** [comment]
Closing this issue as it should have been fixed as of 0.1.9 -- Please reopen an issue if you're still seeing this problem.
