### ISSUE TITLE
yarn start start    Failed

### ISSUE THREAD

**Issue by bananooo-zhang** [iron-fish/ironfish#535]
ubuntu20.04
amd7452x2
ram128g

sudo apt update
curl -sL https://deb.nodesource.com/setup_16.x | sudo bash -
sudo apt -y install nodejs
sudo curl https://sh.rustup.rs -sSf | sh -s -- -y
source $HOME/.cargo/env
rustup default stable
rustup update stable --force
npm install --global yarn
git clone https://github.com/iron-fish/ironfish.git
cd ironfish
yarn install
cd
<img width="616" alt="WeChat487be1fee28a350f4b36caf30642686d" src="https://user-images.githubusercontent.com/61408588/144490476-1e1355fe-72f9-4561-af44-f65c61e0e1fb.png">
 ironfish-cli
yarn start start  

These are the steps I took to report an error in the last step, I had no problem on the other machines.docker doesn't work either, same error

**Comment by toints** [comment]
same error

**Comment by deekerno** [comment]
This memory error should be fixed in our newest updates.
