### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by vht210** [iron-fish/ironfish#537]
Running miners on few machines, it works well for 1-2 days but then many eventually crashed because of Javascript heap out of memory.
This is stacktrace it print out, let me know if you need to have more logs (and how to turn on)

<--- Last few GCs --->

[339323:0x7f4a080008d0] 63663216 ms: Scavenge 728.4 (806.4) -> 713.6 (806.4) MB, 9.5 / 0.0 ms  (average mu = 0.994, current mu = 0.993) task 
[339323:0x7f4a080008d0] 63663272 ms: Scavenge 729.1 (806.4) -> 713.5 (806.4) MB, 7.7 / 0.0 ms  (average mu = 0.994, current mu = 0.993) allocation failure 
[339323:0x7f4a080008d0] 63663330 ms: Scavenge 729.1 (806.4) -> 713.5 (806.4) MB, 18.2 / 0.0 ms  (average mu = 0.994, current mu = 0.993) allocation failure 

<--- JS stacktrace --->

FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
 1: 0xb02ec0 node::Abort() [/usr/bin/node]
 2: 0xa181fb node::FatalError(char const*, char const*) [/usr/bin/node]
 3: 0xced88e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
 4: 0xcedc07 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
 5: 0xea5ea5  [/usr/bin/node]
 6: 0xed4668 v8::internal::EvacuateNewSpaceVisitor::Visit(v8::internal::HeapObject, int) [/usr/bin/node]
 7: 0xef3e6e v8::internal::FullEvacuator::RawEvacuatePage(v8::internal::MemoryChunk*, long*) [/usr/bin/node]
 8: 0xece2cf v8::internal::Evacuator::EvacuatePage(v8::internal::MemoryChunk*) [/usr/bin/node]
 9: 0xece713 v8::internal::PageEvacuationJob::Run(v8::JobDelegate*) [/usr/bin/node]
10: 0x18e4876 v8::platform::DefaultJobState::Join() [/usr/bin/node]
11: 0x18e48e3 v8::platform::DefaultJobHandle::Join() [/usr/bin/node]
12: 0xedbfa3 void v8::internal::MarkCompactCollectorBase::CreateAndExecuteEvacuationTasks<v8::internal::FullEvacuator, v8::internal::MarkCompactCollector>(v8::internal::MarkCompactCollector*, std::vector<std::pair<v8::internal::ParallelWorkItem, v8::internal::MemoryChunk*>, std::allocator<std::pair<v8::internal::ParallelWorkItem, v8::internal::MemoryChunk*> > >, v8::internal::MigrationObserver*, long) [/usr/bin/node]
13: 0xef2253 v8::internal::MarkCompactCollector::EvacuatePagesInParallel() [/usr/bin/node]
14: 0xef261b v8::internal::MarkCompactCollector::Evacuate() [/usr/bin/node]
15: 0xef2fa1 v8::internal::MarkCompactCollector::CollectGarbage() [/usr/bin/node]
16: 0xeb3749 v8::internal::Heap::MarkCompact() [/usr/bin/node]
17: 0xeb4bd8  [/usr/bin/node]
18: 0xeb5300 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/bin/node]
19: 0xeb827e v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/bin/node]
20: 0xe796aa v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/usr/bin/node]
22: 0x15e7879  [/usr/bin/node]
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by vht210** [comment]
Another node
<--- Last few GCs --->

[2360758:0x7f4464000dc0] 62920211 ms: Scavenge 914.5 (1004.9) -> 898.7 (1004.9) MB, 2.1 / 0.0 ms  (average mu = 0.991, current mu = 0.990) allocation failure
[2360758:0x7f4464000dc0] 62921372 ms: Scavenge 914.5 (1004.9) -> 898.8 (1004.9) MB, 17.1 / 0.0 ms  (average mu = 0.991, current mu = 0.990) allocation failure
[2360758:0x7f4464000dc0] 62922521 ms: Scavenge 911.6 (1004.9) -> 898.8 (1004.9) MB, 3.2 / 0.0 ms  (average mu = 0.991, current mu = 0.990) task


<--- JS stacktrace --->

FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
 1: 0xb00d90 node::Abort() [/usr/bin/node]
 2: 0xa1823b node::FatalError(char const*, char const*) [/usr/bin/node]
 3: 0xcedbce v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
 4: 0xcedf47 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
 5: 0xea6105  [/usr/bin/node]
 6: 0xed48c8 v8::internal::EvacuateNewSpaceVisitor::Visit(v8::internal::HeapObject, int) [/usr/bin/node]
 7: 0xef40ce v8::internal::FullEvacuator::RawEvacuatePage(v8::internal::MemoryChunk*, long*) [/usr/bin/node]
 8: 0xece52f v8::internal::Evacuator::EvacuatePage(v8::internal::MemoryChunk*) [/usr/bin/node]
 9: 0xece973 v8::internal::PageEvacuationJob::Run(v8::JobDelegate*) [/usr/bin/node]
10: 0x18e4876 v8::platform::DefaultJobState::Join() [/usr/bin/node]
11: 0x18e48e3 v8::platform::DefaultJobHandle::Join() [/usr/bin/node]
12: 0xedc203 void v8::internal::MarkCompactCollectorBase::CreateAndExecuteEvacuationTasks<v8::internal::FullEvacuator, v8::internal::MarkCompactCollector>(v8::internal::MarkCompactCollector*, std::vector<std::pair<v8::internal::ParallelWorkItem, v8::internal::MemoryChunk*>, std::allocator<std::pair<v8::internal::ParallelWorkItem, v8::internal::MemoryChunk*> > >, v8::internal::MigrationObserver*, long) [/usr/bin/node]
13: 0xef24b3 v8::internal::MarkCompactCollector::EvacuatePagesInParallel() [/usr/bin/node]
14: 0xef287b v8::internal::MarkCompactCollector::Evacuate() [/usr/bin/node]
15: 0xef3201 v8::internal::MarkCompactCollector::CollectGarbage() [/usr/bin/node]
16: 0xeb39a9 v8::internal::Heap::MarkCompact() [/usr/bin/node]
17: 0xeb4e38  [/usr/bin/node]
18: 0xeb5560 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/bin/node]
19: 0xeb8455 v8::internal::Heap::HandleGCRequest() [/usr/bin/node]
20: 0xe459c7 v8::internal::StackGuard::HandleInterrupts() [/usr/bin/node]
21: 0x11f2655 v8::internal::Runtime_StackGuard(int, unsigned long*, v8::internal::Isolate*) [/usr/bin/node]
22: 0x15e7819  [/usr/bin/node]
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by kunxian-xia** [comment]
have the same issue too

**Comment by dguenther** [comment]
This issue should be fixed in 0.1.9 -- Please reopen an issue if you're still seeing this problem on the latest version.
