### ISSUE TITLE
The program was killed for some reason.

### ISSUE THREAD

**Issue by trojan20161207** [iron-fish/ironfish#544]
Started with docker and found that the program stopped the next day.I hope to help optimize it,thanks.

error message:
91892 H/s/usr/src/app/bin/ironfish: line 45:   138 Killed                  "$NODE" "$DIR/run" "$@"

**Comment by dguenther** [comment]
Unfortunately there's not enough information in this issue to debug it. If you're able to find log messages from the Iron Fish node at the time it was killed, please reopen a new issue including the logs and we'll take a look.
