### ISSUE TITLE
Difficulty does not load on the page

### ISSUE THREAD

**Issue by Raiseros** [iron-fish/ironfish#548]
Difficulty does not load on the page https://explorer.ironfish.network/#blocks
browser chrome , 03.12.21 9:48 moscow time
![Screenshot_27](https://user-images.githubusercontent.com/49815815/144558019-89e884b3-b7f5-4574-be85-a0f61acebb74.png)

**Comment by dguenther** [comment]
The API has been under heavy load and has gone down on occasion. It should now be working fairly consistently, but may still go down from time to time while we're working on scaling up the API.
