### ISSUE TITLE
Invalid email in faucet

### ISSUE THREAD

**Issue by helidze** [iron-fish/ironfish#551]
**STR**:

1. Start node
2. Start mining
3. Enter the command "ironfish faucet"
4. Enter valid email: helidze@gmail.com

**A.R:** `Collecting your funds... You entered an invalid email` 
**E.R:** Email is valid. Funds sent
<img width="569" alt="Screenshot 2021-12-03 at 08 23 56" src="https://user-images.githubusercontent.com/17140053/144584441-d0e23959-fa67-4e46-836f-26c7a39c5e69.png">

**Comment by rohanjadvani** [comment]
It looks like you've hit the limit for faucet requests. We'll be updating our API and this command to surface the error more clearly.
