### ISSUE TITLE
No new blocks mined

### ISSUE THREAD

**Issue by crptnwb** [iron-fish/ironfish#561]
Mined 7 blocks from 12/1/2021, 9:32:21 PM till 12/2/2021, 10:38:43 PM (timezone is UTC+1) and then new blocks stoped mining.

**Comment by deekerno** [comment]
The difficulty has increased substantially since the testnet launch and will continue to self-adjust according to the total hash-rate of the network. As such, it may be harder to mine blocks compared to points in the past.
