### ISSUE TITLE
Can't Import Account - Invalid prefix for base64 encoded account

### ISSUE THREAD

**Issue by detherminal** [iron-fish/ironfish#5648]
### What happened?

I get the following error while trying to import from my mnemonic, I have replaced with my_mnemonic where my mnemonic shows

`
Request failed (400) error: Account could not be decoded, decoder errors: JsonEncoder: Invalid JSON: Parsing undefined Failed Unexpected token 'my_mnemonic', "my_mnemonic"... is not valid JSON while parsing 'my_mnemonic' MnemonicEncoder: Invalid mnemonic SpendingKeyEncoder: Invalid spending key: InvalidPaymentAddress To enable Rust backtraces, use RUST_BACKTRACE=1 Bech32JsonEncoder: Invalid bech32 JSON encoding: Failed to decode Bech32Encoder: Could not decode account my_mnemonic using bech32: Failed to decode : Invalid prefix for base64 encoded account
`

THIS IS A CRITICAL BUG WHICH DOES NOT ALLOW USERS TO IMPORT THEIR EXISTING WALLETS, FIX THIS ASAP.

Similar issue: https://github.com/iron-fish/ironfish/issues/5084

### Version

v3.0.11

**Comment by NullSoldier** [comment]
@detherminal What command did you run to try to import this?

**Comment by detherminal** [comment]
> @detherminal What command did you run to try to import this?

I was trying to import my wallet using the Node App > Import Account

**Comment by detherminal** [comment]
> @detherminal are you importing using a mnemonic phrase?

Yeah, 24 word
