### ISSUE TITLE
Memory usage is getting higher and higher during mining

### ISSUE THREAD

**Issue by Kus-A** [iron-fish/ironfish#568]
Latest version，Windows11 environment
Memory usage is getting higher and higher，
write to virtual memory，the hard disk has been used for about 50G in 24 hours.
It needs to be restarted, hoping to release the memory automatically.

**Comment by deekerno** [comment]
Are you still encountering this issue after upgrading to the newest version?

**Comment by Kus-A** [comment]
It's ok,thanks
