### ISSUE TITLE
miner exited with code 137

### ISSUE THREAD

**Issue by IanXuCode** [iron-fish/ironfish#570]
Hi, I run the miner by Docker, after mined a block , it happend an error : miner exited with code 137.
My machine is 4 Core 8G, Ubuntu 20.4

**Comment by IanXuCode** [comment]
I found that it may be caused by insufficient server performance, but there is no specific log information and cannot be judged. are there any error code documents?

**Comment by deekerno** [comment]
That's an operating system error code that indicates that your process may have been terminated due to excessive memory usage. We've done a lot of work to fix memory leaks, so I'm going to close this issue. If you are continuing to see this problem, then feel free to re-open this issue.
