### ISSUE TITLE
Syncing orphan chain

### ISSUE THREAD

**Issue by ahmetyah** [iron-fish/ironfish#573]
Hi, 
After resetting my ironfish, I mined 30 block while starting and now my node syncing with orphan chain.

![bug](https://user-images.githubusercontent.com/95548780/144725086-f64a0df1-1959-4cd1-8826-b5a4e72329e1.PNG)

![Sync](https://user-images.githubusercontent.com/95548780/144725135-db442556-d306-49eb-ad60-71a625c911bb.PNG)
![Sync2](https://user-images.githubusercontent.com/95548780/144725780-7ac4c3ee-ce11-4794-8542-a721dc32a15e.PNG)

**Comment by deekerno** [comment]
As evidenced by your screenshots, your node is still properly syncing the chain from other nodes in the network. An orphan block (and subsequently a chain) is a received block whose previous block is not present in your chain. We haven't fully implemented all the operations around this type of event, so the node gets more information from the node sending the orphan block in case it needs it later. In any case, your node is/was still working properly.
