### ISSUE TITLE
Ironfish-Cli: Clean and prepack failing to run on Windows

### ISSUE THREAD

**Issue by spale777** [iron-fish/ironfish#574]
Running yarn prepack or yarn clean does not work under Windows due to how these commands ware defined, they ware defined as `rm -rf ./build`, `-rf` cannot be used  in Windows.

**Comment by wealthz01** [comment]
Keep clearing shit for me .. if I copy you clean it what’s that’s 😡

**Comment by spale777** [comment]
Issue fixed with merge #575
