### ISSUE TITLE
Bug when importing account

### ISSUE THREAD

**Issue by srwhitney19** [iron-fish/ironfish#578]
There is a strange bug in the ironfish accounts:import process that lists the prompt to the user twice starting at "incoming view key" step (see screen shot):

"_ubuntu@ip-xxx-xx-xx-xxx:~$ ./ironfish/ironfish-cli/bin/ironfish accounts:import
Enter the account name: WhittyFish19
Enter the account spending key: xxx
Enter the account incoming view key: Enter the account incoming view key: xxx
Enter the account outgoing view key: Enter the account outgoing view key: xxx
Enter the account public address: Enter the account public address: xxx_"

<img width="1289" alt="Screen Shot 2021-12-04 at 6 33 24 PM" src="https://user-images.githubusercontent.com/37627499/144731278-63f3e8b9-26b1-4efe-a16b-cd30836cf84c.png">

**Comment by wealthz01** [comment]
Remove all shit … where did get those info

**Comment by wealthz01** [comment]
Make me understand better

**Comment by lwisne** [comment]
We believe this is now closed. Let us know if you don't agree!
