### ISSUE TITLE
The login icon display problem on the homepage.

### ISSUE THREAD

**Issue by kansic** [iron-fish/ironfish#584]
If you log in after signing up for a membership, the login icon should be changed to logout when you log in, but it is logged in as it is.

When you click the login icon again with your mouse, you will see a screen to enter your ID again, and when you enter your ID again and press OK, you will see a message that you are logged in, but the login icon remains the same.

It is not possible to [distinguish] whether the user is logged in or not when logging in after signing up as a member.

**Comment by deekerno** [comment]
This should be resolved after several updates to the testnet website. If you're still encountering this issue, feel free to open an issue in the testnet repo: https://github.com/iron-fish/website-testnet.
