### ISSUE TITLE
Inconsistency in leaderboard block count

### ISSUE THREAD

**Issue by reshordling** [iron-fish/ironfish#589]
"ironfish status" shows more mined blocks than in testnet2 leaderboard.

Might have to do eitther with block height in testnet explorer (https://explorer.ironfish.network/#blocks shows 9633, whereas in ironfish status it is 10332) or with JavaScript heap out of memory, but no proofs, logs attached. Potentially 2 separate bugs - oom and not reporting to leaderboard

Dell VDS, 32 CPU cores, 128GB ram
Ubuntu 20.04

Graffiti reshire

```
root@research-2-de ~ # ironfish status

Version              0.1.8 @ 45df922
Node                 STARTED
P2P Network          CONNECTED - In: 70 KB/s, Out: 121 KB/s, peers 50
Mining               STARTED - 1 miners, 3 mined
Mem Pool             0 tx
Syncer               IDLE @ 0.03 blocks per seconds | avg time to add block 182.64 ms
Blockchain           SYNCED @ HEAD 00000000064c5bbfafadea9d05608d6db80e1782c5ce96cba2c5222d5ae64554 (10332)
Workers              STARTED - 0 -> 0 / 63 - 0.06 jobs Δ, 1.4 jobs/s
```

Leaderboard shows still 1 block (mined yesterday, 3 newly mined not reflected)

[logs.txt.zip](https://github.com/iron-fish/ironfish/files/7656440/logs.txt.zip)

<img width="1155" alt="image" src="https://user-images.githubusercontent.com/17854317/144756024-659792dd-2abf-4d0a-91ee-8621a7c465ec.png">

**Comment by deekerno** [comment]
When you successfully mine a block on your node, it does not necessarily mean that it will be included on the main chain. You and every other miner on the network are competing to mine the same block, and thus it is entirely possible that another miner submitted their block to the network just moments before yours.

In the future, you can use `ironfish miners:mined` to show you which blocks on the main chain have been mined by your account.
