### ISSUE TITLE
Weekly Cycles

### ISSUE THREAD

**Issue by kazantip85** [iron-fish/ironfish#591]
The weekly cycles are not working correctly, or the information on the site is false and misleading.

"Weekly Cycles
Weekly cycles run from Monday to Sunday, during which a participant can earn points in the defined categories above. Once a participant has earned his or her maximum amount of points in a given category, a participant can no longer earn points in that category until the next cycle."  (https://testnet.ironfish.network/about#:~:text=Weekly%20Cycles,the%20next%20cycle). 

However, mined blocks in excess of the 10 blocks / week limit have already begun to be counted.

![Снимок экрана 2021-12-05 172943](https://user-images.githubusercontent.com/70476848/144756318-e148431e-1b4c-49f0-8e63-5ea867a80b23.png)

**Comment by leanthebean** [comment]
I believe this has already been fixed. There are further UI fixes being rolled out that make the week separation more clear.
