### ISSUE TITLE
Mined blocks not displaying well.

### ISSUE THREAD

**Issue by nexusproject** [iron-fish/ironfish#594]
Sometimes already mined blocks are not shown in leaderboard.

Many peoples have this problem and me too.
Right now i have 1 mined block but not see it

**Comment by deekerno** [comment]
When you successfully mine a block on your node, it does not necessarily mean that it will be included on the main chain. You and every other miner on the network are competing to mine the same block, and thus it is entirely possible that another miner submitted their block to the network just moments before yours.

In the future, you can use `ironfish miners:mined` to show you which blocks on the main chain have been mined by your account.
