### ISSUE TITLE
JSON error while starting testnet mining server node

### ISSUE THREAD

**Issue by svinayak8k** [iron-fish/ironfish#603]
/home/ironfish/ironfish/node_modules/js-message/Message.js:38
        return JSON.stringify(

**Comment by svinayak8k** [comment]
![Screen Shot 2021-12-05 at 10 39 40 PM](https://user-images.githubusercontent.com/50720752/144799524-1d230667-a860-4f27-a18e-f54091ade13a.png)

**Comment by deekerno** [comment]
Duplicate of #507.
