### ISSUE TITLE
No blocks in the leaderboard

### ISSUE THREAD

**Issue by NichkaNik** [iron-fish/ironfish#606]
Hi!

Although I mined 1 block, it disapear after miner restart:
root@:~# journalctl -u ironfishd -g "Successfully mined"
-- Logs begin at Sun 2021-12-05 20:02:53 UTC, end at Mon 2021-12-06 08:15:12 UTC. --
Dec 06 06:37:58 ubuntu yarn[27356]: Successfully mined block 000000000626fad9641a53d42541d09e8faf3c0f5430f8e4>
lines 1-2/2 (END)

root@:~# ironfish miners:mined
yarn run v1.22.17
$ yarn build && yarn start:js miners:mined
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run miners:mined
Scanning for mined blocks
Exporting mined block from 1 -> 11288
000000000626fad9641a53d42541d09e8faf3c0f5430f8e43edf57676882a118 default 20 MAIN 11200: view in web
Done in 89.97s.
root@:~# ironfish chain:block 000000000626fad9641a53d42541d09e8faf3c0f5430f8e43edf57676882a118
yarn run v1.22.17
$ yarn build && yarn start:js chain:block 000000000626fad9641a53d42541d09e8faf3c0f5430f8e43edf57676882a118
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run chain:block 000000000626fad9641a53d42541d09e8faf3c0f5430f8e43ed8
{
  "block": {
    "graffiti": "Nichka",
    "hash": "000000000626fad9641a53d42541d09e8faf3c0f5430f8e43edf57676882a118",
    "previousBlockHash": "00000000012fdba4738325f9792ab9e541d0631b4f7d25fde4c9ca13d685a8a9",
    "sequence": 11200,
    "timestamp": 1638772671440,
    "transactions": [
      {
        "signature": "1d6c7fbd9a82ff6d34b20eeba384fba9926a300d208bb4fa4bbf10fb971a29b6772776d13b3bfdacf094eebacd3ec39ce68,
        "hash": "677f83a8e7f1f6b5938df1fb14d07a7c91c55c89f59e785003ddc068b03074e0",
        "fee": "-2000000000",
        "spends": 0,
        "notes": 1
      }
    ]
  },
  "metadata": {
    "main": true
  }
}
Done in 1.80s.

Before restart =))):
![photo_2021-12-06_12-38-56](https://user-images.githubusercontent.com/95591053/144823094-0baa18ae-80fc-4568-b4e3-aef90b7dcd30.jpg)
After restart =(((:

Version              0.1.8 @ src
Node                 STARTED
P2P Network          CONNECTED - In: 7 KB/s, Out: 46 KB/s, peers 49
Mining               STARTED - 1 miners, 0 mined
Mem Pool             3 tx
Syncer               IDLE @ 0.02 blocks per seconds | avg time to add block 121.29 ms
Blockchain           SYNCED @ HEAD 0000000007b5771914b3d9f62bac398c3282f55a207ea9e36fb6aac41c366787 (11299)
Workers              STARTED - 0 -> 0 / 15 - 0 jobs Δ, 0.76 jobs/s

Also none of my blocks in leaderboard!(
![image](https://user-images.githubusercontent.com/95591053/144812646-639544ca-f111-4cab-8ee2-d3d3f69d3f93.png)

**Comment by deekerno** [comment]
Upon checking into this, it seems that the problem resolved itself at some point in the past as your block is properly showing in the block explorer as well as your personal recent activity log.
