### ISSUE TITLE
Miner dropped two times because of memory leak (HeapObject, MemoryChunk)

### ISSUE THREAD

**Issue by wd0j7zhe05** [iron-fish/ironfish#613]
Miner dropped two times because of memory leak (HeapObject, MemoryChunk) with following  explanation:
```
0xed48c8 v8::internal::EvacuateNewSpaceVisitor::Visit(v8::internal::HeapObject, int) [/usr/bin/node]
0xef40ce v8::internal::FullEvacuator::RawEvacuatePage(v8::internal::MemoryChunk*, long*) [/usr/bin/node]
0xece52f v8::internal::Evacuator::EvacuatePage(v8::internal::MemoryChunk*) [/usr/bin/node]
0xece84b v8::internal::PageEvacuationJob::Run(v8::JobDelegate*) [/usr/bin/node]
0x18da9e4 v8::platform::DefaultJobWorker::Run() [/usr/bin/node]
0xb6d4b5  [/usr/bin/node]
0x7f3b2d9ad609  [/lib/x86_64-linux-gnu/libpthread.so.0]
0x7f3b2d8d4293 clone [/lib/x86_64-linux-gnu/libc.so.6]
```
I understand there is a RAM issue, this is being referenced by the V8 JavaScript engine. But the fact is that at the time of the error, 100 GB of RAM is idle free. For this reason, the miner crashes for the second time, after restarting everything works without problems. Nowhere in the documentation and chats, I have not found ways to limit the consumption of RAM.
Perhaps my machine data can help you:
```
Graffiti: Diana_IronfishUA
RAM: 128 GB DDR4 ECC  
OS: Ubuntu 20.04
```

**Comment by deekerno** [comment]
Are you still encountering this issue after upgrading to the newest version?
