### ISSUE TITLE
Mining block is not counted

### ISSUE THREAD

**Issue by DrBoBo1** [iron-fish/ironfish#614]
![image](https://user-images.githubusercontent.com/90654962/144901945-f51b7970-e18c-402e-b48c-333ac5df75f5.png)

root@IRFAX16132c128G ~ # journalctl -u ironfishd -g "Successfully mined"
-- Logs begin at Sat 2021-12-04 12:59:28 CET, end at Mon 2021-12-06 18:58:08 CET. --
Dec 05 00:53:29 IRFAX16132c128G yarn[31990]: Successfully mined block 000000000125f4f6157d1a29ce9c62ee3f1fdac35d81483059599c51101f2f9c (9287) has 2 transactions
Dec 05 09:16:07 IRFAX16132c128G yarn[31990]: Successfully mined block 0000000009bbd273cc6b2aa93e5b8067a88bfadc1b65fbb2f600b4ae53302582 (9729) has 1 transactions
Dec 05 12:00:10 IRFAX16132c128G yarn[31990]: Successfully mined block 0000000005fd747921b0c36704e89412167401fc3fcb3566a72b631ad03c4d9a (9909) has 1 transactions
Dec 05 21:30:04 IRFAX16132c128G yarn[31990]: Successfully mined block 0000000002c18b11a7666e13b14526323eb6de586033c0d87c8c479e5e87438c (10580) has 1 transactions
**Dec 06 09:33:27 IRFAX16132c128G yarn[31990]: Successfully mined block 000000000052d8e2ba1aeb219a00a3bfd0bf38baee322af9841ad062c73b5aae (11301) has 2 transactions**
Dec 06 12:02:36 IRFAX16132c128G yarn[31990]: Successfully mined block 000000000769020a168c1232ef87984c15eab9e55116e4534f272017393dc124 (11444) has 1 transactions
Dec 06 13:21:07 IRFAX16132c128G yarn[31990]: Successfully mined block 00000000045eeaf623af3d459a4ff885117229cd012f954d3d0b03364eddcc8c (11519) has 1 transactions

![image](https://user-images.githubusercontent.com/90654962/144902092-fd9f4d1a-772f-4124-ab64-064f14b6c7e9.png)
Other Hash: 000000000081318b50b54075fbd08c53a9e49ad21bb814019a252ce7e93e17dd

My Graffiti: MCryp_Ironfish_node1

**Comment by deekerno** [comment]
When you successfully mine a block on your node, it does not necessarily mean that it will be included on the main chain. You and every other miner on the network are competing to mine the same block, and thus it is entirely possible that another miner submitted their block to the network just moments before yours.

In the future, you can use `ironfish miners:mined` to show you which blocks on the main chain have been mined by your account.
