### ISSUE TITLE
could we add peers manually? 

### ISSUE THREAD

**Issue by knight2008** [iron-fish/ironfish#615]
when I sync blocks, it hangs forever at 6481.
so could we add specific peers manually like bitcoin (add peers in bitcion.conf )? 
I think this is helpful.

**Comment by deekerno** [comment]
It's not officially recommended, but you can attempt to add information to the `hosts.json` file found in your Iron Fish data directory, namely the IP and port of the peer that you want to add.

**Comment by syyongx** [comment]
@deekerno 

> It's not officially recommended, but you can attempt to add information to the `hosts.json` file found in your Iron Fish data directory, namely the IP and port of the peer that you want to add.

The modified hosts.json will be reset automatically.
