### ISSUE TITLE
Some blocks are taking hours to mine unexpectedly

### ISSUE THREAD

**Issue by fernando42** [iron-fish/ironfish#622]
::::::::::          :::::::::::::::::
::::::::::::       :::::::::::::::::::
:::::::::::::     :::::::::::::::::::::
::::::::::::::   ::::::::::::::::::::::::
 ::::::::::::: ::::::::::        :::::::::
   :::::::::::::::::::::          ::::::::::
   :::::::::::::::::::::          :::::::::
 ::::::::::::: ::::::::::        :::::::::
::::::::::::::   ::::::::::::::::::::::::
:::::::::::::     :::::::::::::::::::::
::::::::::::       :::::::::::::::::::
::::::::::           ::::::::::::::::

Version       0.1.8 @ 45df922
Node Name     NONE
Peer Identity 4SEIOgxSQv8qBExrpQkohj4kfalIApLpsniPO2C09xQ=
Peer Agent    if/cli/45df922
Peer Port     9033
Bootstrap     test.bn1.ironfish.network

WebSocket server started at :::9033
Connected to the Iron Fish network
Starting sync from 1BSY2UX (Royalfu). work: +58714327029601, ours: 11768, theirs: 12244
Finding ancestor using linear search on last 3 blocks starting at 00000...ec312 (11768) from peer 1BSY2UX (Royalfu) at 12244
Found peer 1BSY2UX (Royalfu) ancestor 00000...ec312, syncing from 11768 -> 12244 (476) after 1 requests
Requesting 20 blocks starting at 00000...ec312 (11768) from 1BSY2UX (Royalfu)
Added block seq: 11780, hash: 00000...fdcb2, txs: 1, progress: 95.41%, time: 19.6ms
Requesting 20 blocks starting at 00000...edcb0 (11788) from 1BSY2UX (Royalfu)
Added block seq: 11800, hash: 00000...c521f, txs: 1, progress: 95.63%, time: 17.5ms
Requesting 20 blocks starting at 00000...f0b0a (11808) from 1BSY2UX (Royalfu)
Added block seq: 11820, hash: 00000...6c876, txs: 1, progress: 95.82%, time: 19.5ms
Requesting 20 blocks starting at 00000...747b9 (11828) from 1BSY2UX (Royalfu)
Added block seq: 11840, hash: 00000...e9b0b, txs: 1, progress: 96.06%, time: 17.4ms
Requesting 20 blocks starting at 00000...c76bf (11848) from 1BSY2UX (Royalfu)
Added block seq: 11860, hash: 00000...958a7, txs: 2, progress: 96.29%, time: 253.9ms
Requesting 20 blocks starting at 00000...5ae13 (11868) from 1BSY2UX (Royalfu)
Added block seq: 11880, hash: 00000...f0ae5, txs: 1, progress: 96.48%, time: 15.5ms
Requesting 20 blocks starting at 00000...94b6f (11888) from 1BSY2UX (Royalfu)
Added block seq: 11900, hash: 00000...7695e, txs: 2, progress: 96.66%, time: 224.9ms
Requesting 20 blocks starting at 00000...f2d9d (11908) from 1BSY2UX (Royalfu)
Added block seq: 11920, hash: 00000...9817b, txs: 1, progress: 96.90%, time: 17.2ms
Requesting 20 blocks starting at 00000...c35d1 (11928) from 1BSY2UX (Royalfu)
Added block seq: 11940, hash: 00000...efa6f, txs: 1, progress: 97.07%, time: 15.1ms
Requesting 20 blocks starting at 00000...79f28 (11948) from 1BSY2UX (Royalfu)
Added block seq: 11960, hash: 00000...3cef2, txs: 1, progress: 97.26%, time: 16.1ms
Requesting 20 blocks starting at 00000...3a751 (11968) from 1BSY2UX (Royalfu)
Added block seq: 11980, hash: 00000...2217f, txs: 2, progress: 97.45%, time: 277.8ms
Requesting 20 blocks starting at 00000...19d8b (11988) from 1BSY2UX (Royalfu)
Added block seq: 12000, hash: 00000...3b61f, txs: 1, progress: 97.60%, time: 15.3ms
Requesting 20 blocks starting at 00000...5f276 (12008) from 1BSY2UX (Royalfu)
Added block seq: 12020, hash: 00000...8c813, txs: 2, progress: 97.82%, time: 220.9ms
Requesting 20 blocks starting at 00000...403a8 (12028) from 1BSY2UX (Royalfu)
Added block seq: 12040, hash: 00000...b717e, txs: 1, progress: 98.09%, time: 15.8ms
Requesting 20 blocks starting at 00000...c7563 (12048) from 1BSY2UX (Royalfu)
Added block seq: 12060, hash: 00000...e2f42, txs: 1, progress: 98.29%, time: 16.0ms
Requesting 20 blocks starting at 00000...92381 (12068) from 1BSY2UX (Royalfu)
Added block seq: 12080, hash: 00000...6bbde, txs: 1, progress: 98.54%, time: 15.7ms
Requesting 20 blocks starting at 00000...795c8 (12088) from 1BSY2UX (Royalfu)
Added block seq: 12100, hash: 00000...57bf1, txs: 1, progress: 98.71%, time: 16.3ms
Requesting 20 blocks starting at 00000...2aeec (12108) from 1BSY2UX (Royalfu)
Added block seq: 12120, hash: 00000...c3f41, txs: 2, progress: 98.82%, time: 227.6ms
Requesting 20 blocks starting at 00000...b5ffd (12128) from 1BSY2UX (Royalfu)
Added block seq: 12140, hash: 00000...ebc34, txs: 2, progress: 99.10%, time: 240.5ms
Requesting 20 blocks starting at 00000...49843 (12148) from 1BSY2UX (Royalfu)
Added block seq: 12160, hash: 00000...48df8, txs: 1, progress: 99.32%, time: 15.7ms
Requesting 20 blocks starting at 00000...9d973 (12168) from 1BSY2UX (Royalfu)
Peer 1BSY2UX (Royalfu) disconnected (DISCONNECTED) while syncing.
Starting sync from GzMGFn5 (sobolkzn). work: +9484773526613, ours: 12168, theirs: 12244
Finding ancestor using linear search on last 3 blocks starting at 00000...9d973 (12168) from peer GzMGFn5 (sobolkzn) at 12244
Found peer GzMGFn5 (sobolkzn) ancestor 00000...9d973, syncing from 12168 -> 12244 (76) after 1 requests
Requesting 20 blocks starting at 00000...9d973 (12168) from GzMGFn5 (sobolkzn)
Added block seq: 12180, hash: 00000...f0bf8, txs: 1, progress: 99.50%, time: 15.6ms
Requesting 20 blocks starting at 00000...9a1ee (12188) from GzMGFn5 (sobolkzn)
Added block seq: 12200, hash: 00000...ee274, txs: 1, progress: 99.68%, time: 15.8ms
Requesting 20 blocks starting at 00000...28c5c (12208) from GzMGFn5 (sobolkzn)
Added block seq: 12220, hash: 00000...81a45, txs: 1, progress: 99.85%, time: 15.9ms
Requesting 20 blocks starting at 00000...8e2be (12228) from GzMGFn5 (sobolkzn)
Added block seq: 12240, hash: 00000...a570c, txs: 1, progress: 99.99%, time: 16.7ms
Finished syncing 78 blocks from GzMGFn5 (sobolkzn)
Added block seq: 12260, hash: 00000...a908e, txs: 1, progress: 100.00%, time: 344.5ms
Added block to fork seq: 12235, head-seq: 12267, hash: 00000...6d7c7, head-hash: 00000...52a99, work: 694345489850343, head-work: 698450156495978, work-diff: 4104666645635
Added block to fork seq: 12105, head-seq: 12276, hash: 00000...d8941, head-hash: 00000...6e16a, work: 678216237002753, head-work: 699612472144276, work-diff: 21396235141523
Added block seq: 12280, hash: 00000...d6b2f, txs: 3, progress: 100.00%, time: 1162.7ms
Reorganizing chain from 00000...0f5a7 (12286) for 00000...316c4 (12286) on prev 00000...cc20f (12285)
Reorganized chain. blocks: 1, old: 00000...0f5a7 (12286), new: 00000...cc20f (12285), fork: 00000...cc20f (12285)
Added block to fork seq: 11956, head-seq: 12297, hash: 00000...4f3e1, head-hash: 00000...c5251, work: 659823002058033, head-work: 702330935120914, work-diff: 42507933062881
Added block seq: 12300, hash: 00000...272f4, txs: 1, progress: 100.00%, time: 59.5ms
Reorganizing chain from 00000...df21b (12312) for 00000...7319d (12312) on prev 00000...fc0bc (12311)
Reorganized chain. blocks: 1, old: 00000...df21b (12312), new: 00000...fc0bc (12311), fork: 00000...fc0bc (12311)
Added block to fork seq: 11972, head-seq: 12312, hash: 00000...c2a47, head-hash: 00000...7319d, work: 661804766980752, head-work: 704286824092547, work-diff: 42482057111795
Added block to fork seq: 11937, head-seq: 12312, hash: 00000...686ae, head-hash: 00000...7319d, work: 657484427127590, head-work: 704286824092547, work-diff: 46802396964957
Added block to fork seq: 11982, head-seq: 12312, hash: 00000...a0943, head-hash: 00000...7319d, work: 663042927734398, head-work: 704286824092547, work-diff: 41243896358149
Added block to fork seq: 12201, head-seq: 12312, hash: 00000...4385c, head-hash: 00000...7319d, work: 690086977053868, head-work: 704286824092547, work-diff: 14199847038679
Added block to fork seq: 12004, head-seq: 12312, hash: 00000...5465d, head-hash: 00000...7319d, work: 665792037612855, head-work: 704286824092547, work-diff: 38494786479692
Added block to fork seq: 12215, head-seq: 12312, hash: 00000...10917, head-hash: 00000...7319d, work: 691834099086429, head-work: 704286824092547, work-diff: 12452725006118
Added block to fork seq: 12160, head-seq: 12312, hash: 00000...8ed57, head-hash: 00000...7319d, work: 685020533141446, head-work: 704286824092547, work-diff: 19266290951101
Added block seq: 12160, hash: 00000...8ed57, txs: 1, progress: 98.07%, time: 13.6ms
Added block to fork seq: 12045, head-seq: 12312, hash: 00000...7974e, head-hash: 00000...7319d, work: 670877298944881, head-work: 704286824092547, work-diff: 33409525147666
Added block to fork seq: 12045, head-seq: 12312, hash: 00000...14779, head-hash: 00000...7319d, work: 670877358959005, head-work: 704286824092547, work-diff: 33409465133542
Added block to fork seq: 12059, head-seq: 12312, hash: 00000...6dee4, head-hash: 00000...7319d, work: 672585986598242, head-work: 704286824092547, work-diff: 31700837494305
Added block to fork seq: 12068, head-seq: 12312, hash: 00000...7074c, head-hash: 00000...7319d, work: 673691176145742, head-work: 704286824092547, work-diff: 30595647946805

**Comment by NullSoldier** [comment]
Some blocks are taking hours to mine, versus 60 seconds which is our target block time.
