### ISSUE TITLE
the fee is minus

### ISSUE THREAD

**Issue by shandongdacongge** [iron-fish/ironfish#623]
hello, block 12312 which we're all stuck on has 4 transactions... 
I find the first trasactions has a unnormal fee, it's a minus and a big number.

so, maybe this is the blocking Key problem.

![image](https://user-images.githubusercontent.com/64308935/144990783-91a66f37-8548-483e-a322-345699d92c7a.png)

**Comment by shandongdacongge** [comment]
again that's a minus fee
and the chain blocked for one hour.

**Comment by dguenther** [comment]
The first transaction is expected to be negative -- it's awarding the block miner the mining reward, plus the fees of the other transactions on the block.

The fee values are in the smallest denomination of IRON, called Ore, where 1 IRON = 100000000 Ore. Similar to how 1 eth = 10^18 wei.

The stuck block issue is something we're continuing to investigate, but it's possible that the hash power of the network dropped significantly during that time.

**Comment by shandongdacongge** [comment]
OK,  I got it.
thank u.
