### ISSUE TITLE
Block successfully mined but not appearing on the explorer and leaderboard

### ISSUE THREAD

**Issue by stepby9** [iron-fish/ironfish#628]
Hi, 
I've mined a block, and can see it in the logs.
![image](https://user-images.githubusercontent.com/78685883/145065103-851dd838-d09e-4a36-a784-0aeb05c67881.png)

However, it doesn't appear in the explorer and leaderboard, thus I don't get any points. The error I get is that "no block found with that hash".
![image](https://user-images.githubusercontent.com/78685883/145065413-a217ee07-4a45-4a2c-9b5e-4c59392883c5.png)

Please have a look if something can be done here. 
My graffiti is stepby9

Thank you.

**Comment by deekerno** [comment]
When you successfully mine a block on your node, it does not necessarily mean that it will be included on the main chain. You and every other miner on the network are competing to mine the same block, and thus it is entirely possible that another miner submitted their block to the network just moments before yours.

In the future, you can use `ironfish miners:mined` to show you which blocks on the main chain have been mined by your account.
