### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by kyyoo** [iron-fish/ironfish#634]
![image](https://user-images.githubusercontent.com/21254706/145085483-8c59dc8a-c53b-4d78-aa21-312b91e4e3a3.png)

Google GCP / 8core vCPU / 32GB RAM / Ubuntu 20.04 LTS

graffiti : monokaii

**Comment by NullSoldier** [comment]
This is expected and not an error. The other node disconnected from you while you were syncing from them.
