### ISSUE TITLE
new Error('nullifierToNote mappings must have a corresponding noteToNullifier map');

### ISSUE THREAD

**Issue by shandongdacongge** [iron-fish/ironfish#643]
I can't start the node. 
Blow is the details error info.

Version       0.1.8 @ src
Node Name     NONE
Peer Identity o5ZHWG8VTOSP22ReggZOqRNMpoif757yE1R2zOLkv3k=
Peer Agent    if/cli/src
Peer Port     9033
Bootstrap     test.bn1.ironfish.network
 
WebSocket server started at :::9033
Connected to the Iron Fish network
Starting sync from Zd+mDRl. work: +266714372296, ours: 13434, theirs: 13436
Finding ancestor using linear search on last 3 blocks starting at 00000...97e1d (13434) from peer Zd+mDRl at 13436
Found peer Zd+mDRl ancestor 00000...97e1d, syncing from 13434 -> 13436 (2) after 1 requests
Requesting 20 blocks starting at 00000...97e1d (13434) from Zd+mDRl
Finished syncing 2 blocks from Zd+mDRl
/root/ironfish.git/trunk/ironfish/build/src/account/accounts.js:363
                        throw new Error('nullifierToNote mappings must have a corresponding noteToNullifier map');
                              ^

Error: nullifierToNote mappings must have a corresponding noteToNullifier map
    at /root/ironfish.git/trunk/ironfish/build/src/account/accounts.js:363:31
    at async LevelupDatabase.withTransaction (/root/ironfish.git/trunk/ironfish/build/src/storage/database/database.js:39:28)
    at async Accounts.removeTransaction (/root/ironfish.git/trunk/ironfish/build/src/account/accounts.js:345:9)
    at async Accounts.expireTransactions (/root/ironfish.git/trunk/ironfish/build/src/account/accounts.js:596:17)
    at async Accounts.eventLoop (/root/ironfish.git/trunk/ironfish/build/src/account/accounts.js:169:9)
error Command failed with exit code 1.

**Comment by shandongdacongge** [comment]
I have modified the accounts.ts and reinstall it, I find the other details info.
This error was happend in the  https://github.com/iron-fish/ironfish/blob/45df9225165bac4e623ebeb067acf2283480472f/ironfish/src/account/accounts.ts#L561
I try print the spend object and ignore the Error, it can works, but I don't know while the nullifier is null.

{
  size: 19091,
  nullifier: <Buffer 18 f3 fd 1d b6 30 90 21 94 da 4d 6c f9 cd ae 2a 62 d6 0a 89 ff fc 81 1a c7 81 70 5e 5d 4b 29 47>,
  commitment: <Buffer 4a 27 f6 ca ea ef 69 ad cf e3 d5 ba d9 ec db 77 52 bd e1 fa 00 de a7 b1 1a 07 d5 db 96 29 be 41>
}
{
  size: 17947,
  nullifier: <Buffer 99 d9 64 74 c2 b2 87 34 fc c9 31 2f 2b d1 59 36 c0 38 9e a0 cc 15 45 9e 1a 8c 0c 73 97 49 3b 43>,
  commitment: <Buffer 22 5f 90 cf e8 d8 53 10 c7 64 7e c6 f6 03 3c 1c 34 42 03 3a 8f a6 bf 5c ef 04 ea bc f2 5e 43 5b>
}
nullifierToNote mappings must have a corresponding
{
  size: 17947,
  nullifier: <Buffer 3d 80 e1 43 0b d0 7d 52 99 54 20 f4 6d b5 d0 eb d3 88 61 de ce 44 61 a1 e3 cb e2 2d 91 96 9d 04>,
  commitment: <Buffer 22 5f 90 cf e8 d8 53 10 c7 64 7e c6 f6 03 3c 1c 34 42 03 3a 8f a6 bf 5c ef 04 ea bc f2 5e 43 5b>
}
nullifierToNote mappings must have a corresponding
{
  size: 19106,
  nullifier: <Buffer cd 90 60 3b 9b 06 6f 93 0b 24 1d bd fa 0d 5b 0d 9e dd c5 64 90 be 44 7f 54 e5 7c 99 01 43 2a 11>,
  commitment: <Buffer c8 97 c7 62 9c c0 11 58 f0 b9 6d 9e 74 c1 2a ae cc a4 ff f1 2d 59 d8 91 cd 23 78 8e a7 e3 0c 4d>
}

**Comment by Megavolv** [comment]
I have exactly the same error.

**Comment by Megavolv** [comment]
Deleting accounts dir helped me.

**Comment by shandongdacongge** [comment]
I have delete all and reinstall the ironfish, it's ok now.
