### ISSUE TITLE
node is not sync on 0.1.9

### ISSUE THREAD

**Issue by iljoo-yoon** [iron-fish/ironfish#646]
i updated my node and restart node and miner.

but Blocks are not incrementing for more than 1 hours and nodes are not syncing.

![image](https://user-images.githubusercontent.com/85475248/145158917-658131d1-378d-491f-b6fd-de6234a0bf44.png)

i am not sure this error message has related to the problem.

ironfish-node_1   | Error occurred while sending GetBlocks message in state CONNECTED Error: libdatachannel error while sending dataChannel msg# Message size exceeds limit
ironfish-node_1   |     at WebRtcConnection.send (/usr/src/app/node_modules/ironfish/build/src/network/peers/connections/webRtcConnection.js:58:34)
ironfish-node_1   |     at Peer.send (/usr/src/app/node_modules/ironfish/build/src/network/peers/peer.js:316:47)
ironfish-node_1   |     at PeerManager.sendTo (/usr/src/app/node_modules/ironfish/build/src/network/peers/peerManager.js:548:21)
ironfish-node_1   |     at RpcRouter.handle (/usr/src/app/node_modules/ironfish/build/src/network/messageRouters/rpc.js:169:34)
ironfish-node_1   |     at async PeerNetwork.handleMessage (/usr/src/app/node_modules/ironfish/build/src/network/peerNetwork.js:378:17)

**Comment by iljoo-yoon** [comment]
i guess peer version can be problem..

ironfish-node     | CONN WebSocket unidentified STATE DISCONNECTED -> WAITING_FOR_IDENTITY
ironfish-node     | SEND WebSocket unidentified: identity
ironfish-node     | PEER unidentified STATE DISCONNECTED -> CONNECTING
ironfish-node     | RECV WebSocket unidentified: identity
ironfish-node     | Disconnecting from CsrETxd9xHtQu237Oss+KLXsXNFyCACEjQ9U2672vUs= - Peer version 10 is not compatible with our minimum: 11
ironfish-node     | PEER unidentified STATE CONNECTING -> DISCONNECTED
ironfish-node     | CONN WebSocket unidentified STATE WAITING_FOR_IDENTITY -> DISCONNECTED
ironfish-node     | CONN WebSocket unidentified STATE DISCONNECTED -> WAITING_FOR_IDENTITY
ironfish-node     | SEND WebSocket unidentified: identity
ironfish-node     | PEER unidentified STATE DISCONNECTED -> CONNECTING
ironfish-node     | RECV WebSocket unidentified: identity
ironfish-node     | Disconnecting from sCW9ORWY1blbjVCBLmvC4QVWOSDDAt6I2Q1vPLWZb3g= - Peer version 10 is not compatible with our minimum: 11

**Comment by jerryxue09** [comment]
Hi Yoon, did you solve this problem?

**Comment by deekerno** [comment]
This was due to a variety of factors that were addressed in v0.1.11.
