### ISSUE TITLE
Miner doesn't support machines larger than 96 threads

### ISSUE THREAD

**Issue by asto** [iron-fish/ironfish#655]
Miner crashes when launched on machines with more than 96 threads available. Here is the error I get:

> admin@ip-172-31-34-4:~/ironfish/ironfish-cli$ yarn start:once miners:start --threads 125 --rpc.tcp --rpc.tcp.host=172.31.36.75 --rpc.tcp.port=8001
> yarn run v1.22.17
> $ yarn build && yarn start:js miners:start --threads 125 --rpc.tcp --rpc.tcp.host=172.31.36.75 --rpc.tcp.port=8001
> $ tsc -b
> $ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run miners:start --threads 125 --rpc.tcp --rpc.tcp.host=172.31.36.75 --rpc.tcp.port=8001
> Starting to mine with 125 threads
> Mining block 13967 on request 2444... done
> 
> node:internal/event_target:777
>   process.nextTick(() => { throw err; });
>                            ^
> RangeError [Error]: WebAssembly.Instance(): Out of memory: wasm memory
>     at Object.<anonymous> (/home/admin/ironfish/node_modules/blake3-wasm/dist/wasm/nodejs/blake3_js.js:193:22)
>     at Module._compile (node:internal/modules/cjs/loader:1101:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
>     at Module.load (node:internal/modules/cjs/loader:981:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
>     at Module.require (node:internal/modules/cjs/loader:1005:19)
>     at require (node:internal/modules/cjs/helpers:102:18)
>     at Object.<anonymous> (/home/admin/ironfish/node_modules/blake3-wasm/dist/node/hash-fn.js:4:21)
>     at Module._compile (node:internal/modules/cjs/loader:1101:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
> Emitted 'error' event on Worker instance at:
>     at Worker.[kOnErrorMessage] (node:internal/worker:289:10)
>     at Worker.[kOnMessage] (node:internal/worker:300:37)
>     at MessagePort.<anonymous> (node:internal/worker:201:57)
>     at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:562:20)
>     at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by dguenther** [comment]
Hmm, it looks like the miner is running out of memory. I'm assuming you're on the latest version, 0.1.9?

Can you try setting `nodeWorkers` in your config to a smaller value, like 8, and restart your node? You can also pass `--workers` to the node's start command, like `ironfish start --workers 8`.

The node, by default, creates a process for every core on your machine for handling long-running work like verifying transactions. However, each of these processes takes up some memory. I don't expect the node to need more than 8 of these processes on a relatively recent computer, so limiting these may free up enough memory for the miner to be able to run more workers.

**Comment by NullSoldier** [comment]
We should measure the memory usage per thread, and see if we can reduce it. Maybe in miners, we should not load the sapling params.

**Comment by asto** [comment]
`ironfish start --workers 8` didn't work.

Just for clarity, the node is run separately on a low powered cloud instance (2 core, 2gb ram). And a large cloud instance (128 core, 512gb ram) is connected to the node for mining. It's the large instance with the miner that crashes. So unless setting --workers on the node instance influences memory usage on the miner instance, this one's probably a dead end.

**Comment by asto** [comment]
Did some reading on this and it seem WASM has a memory limit of 4GB since it's 32bit. Doing some quick calculation, if each thread uses about 35MB of memory, 4 GB can run out with 128 threads.

It seems we're out of luck until WASM-64 is out then!

Time to close this thread I guess?

**Comment by CumpsD** [comment]
The newer version uses `blake3` instead of `blake3-wasm`, maybe that works now?

**Comment by CumpsD** [comment]
100 cores works by the way :) (using 8 workers, and threads 100)

**Comment by dguenther** [comment]
@asto, if you could retry with the latest version that uses `blake3`, that would be great -- we've been curious if `blake3` will help with the crashing when running a bunch of threads like this.

**Comment by CumpsD** [comment]
@dguenther anything above 100 still throws the same error, even with `blake3`

**Comment by dguenther** [comment]
I believe this should be fixed now since #815 -- please reopen if you're still seeing this though!
