### ISSUE TITLE
 upgrade from 0.1.8 to 0.1.9 from source will lost data to restart

### ISSUE THREAD

**Issue by hellogit2021** [iron-fish/ironfish#657]
if you upgrade from 0.1.8 to 0.1.9 from source, after you start the node, you will meet "Another node is using the database, waiting for that node to close.", that will cause you have to delete the old ./ironrish folder to start new version node,that means who upgrade will loss all his old data, and he will have to sync the block again

platform: the ubuntu18.04 under win10
and i directly use new source not buy git-clone, i think the upgrade the source should not effect the old database

**Comment by deekerno** [comment]
It is not necessary to delete the folder when a database reset is not required; however it is not obvious how to remove the database lock.

While we work on improving the workflow for this, you can go in to the sub-folders in the databases directory and remove the `LOCK` file, if present.
