### ISSUE TITLE
Testnet leaderboard can't show the points correctly

### ISSUE THREAD

**Issue by jueduizone** [iron-fish/ironfish#659]
by the linux command ,I find I have mined 2 block, but on the Testnet leaderboard, it shows 0. I confirm the blockGraffiti set up right.
**command show**
<img width="777" alt="WechatIMG279" src="https://user-images.githubusercontent.com/16284115/145320712-bf4d67b3-110d-47f4-963b-efccd02c0824.png">
**blockGraffiti config**
<img width="514" alt="WX20211209-095609@2x" src="https://user-images.githubusercontent.com/16284115/145320723-d5f00182-f2e3-4696-ac04-b4a467a10644.png">
**Testnet leaderboard show**
![image](https://user-images.githubusercontent.com/16284115/145320766-db85c02f-345b-4d7a-9be2-ead38123b5d1.png)

**Comment by deekerno** [comment]
When you successfully mine a block on your node, it does not necessarily mean that it will be included on the main chain. You and every other miner on the network are competing to mine the same block, and thus it is entirely possible that another miner submitted their block to the network just moments before yours.

In the future, you can use `ironfish miners:mined` to show you which blocks on the main chain have been mined by your account.
