### ISSUE TITLE
Message propagation bug

### ISSUE THREAD

**Issue by Andrew-M-Cox** [iron-fish/ironfish#662]
I am mining with two machines. One keeps falling behind and I have to restart the node. It catches up initially but then fails to update. Notice the two screenshots that were taken seconds apart. This happened repeatedly on the same (lagging) machine.
<img width="577" alt="Screen Shot 2021-12-08 at 9 56 46 PM" src="https://user-images.githubusercontent.com/53104102/145461235-c07a6058-a4f5-4638-af69-12498602f2c4.png">
<img width="577" alt="lagging_machine" src="https://user-images.githubusercontent.com/53104102/145332508-d068ec7e-3fcd-41a5-a5e6-d0be0be9a5f6.png">
0c13-43ef-ad50-07ab690c9552.png">

**Comment by Andrew-M-Cox** [comment]
I'll add that both were updated about 2 hours ago to the same version (0.1.9 @ cca3c88)

**Comment by NullSoldier** [comment]
I think your first screenshot is bugged. The URL is missing. Can you fix it?

**Comment by Andrew-M-Cox** [comment]
@NullSoldier, thanks. should be good now.
