### ISSUE TITLE
during the running, the node stop and show "Another node is using the database, waiting for that node to close."

### ISSUE THREAD

**Issue by hellogit2021** [iron-fish/ironfish#665]
during the running for about 6 hours, the node suddently stop and it try reconnect serval times, and show "Another node is using the database, waiting for that node to close.", if run command "yarn ironfish status -f", it pompt the "NODE STOP" message, then if you stop the node by CTRL+C twice and close the windows, and then re-run the node at new windows with start command, it will prompt "Another node is using the database, waiting for that node to close." again, then can not run without removing the .ironfish foler, and do re-sync job....

my platform:ubuntu18.04 at win10, ironfish version is 0.1.9

**Comment by deekerno** [comment]
It is not necessary to delete the folder when a database reset is not required; however it is not obvious how to remove the database lock.

While we work on improving the workflow for this, you can go in to the sub-folders in the databases directory and remove the LOCK file, if present.
