### ISSUE TITLE
peers (DISCONNECTED) while syncing.

### ISSUE THREAD

**Issue by T0O0Z** [iron-fish/ironfish#671]
Hey got this happening after 5min running correctly: (any fix?
![disco](https://user-images.githubusercontent.com/95851059/145368038-bd2a0aeb-68fd-43a8-8923-b6bfd4d919de.PNG)
)

**Comment by T0O0Z** [comment]
Always around 32% done..
![a](https://user-images.githubusercontent.com/95851059/145372675-e17e75bb-7d97-45d9-b8e1-ec0f302898d6.PNG)
.

**Comment by T0O0Z** [comment]
btw it started back at 32% after a ironfish restart

**Comment by JulsKawa** [comment]
WebSocket server started at :::9033

Connected to the Iron Fish network

Not connected to the Iron Fish network

Connected to the Iron Fish network

Starting sync from 8DKol6T (Britva_2018). work: +1061877494908983, ours: 6481, theirs: 15651

Finding ancestor using linear search on last 3 blocks starting at 00000...bb62e (6481) from peer 8DKol6T (Britva_2018) at 15651

Found peer 8DKol6T (Britva_2018) ancestor 00000...bb62e, syncing from 6481 -> 15651 (9170) after 1 requests

Requesting 20 blocks starting at 00000...bb62e (6481) from 8DKol6T (Britva_2018)

Peer 8DKol6T (Britva_2018) disconnected (DISCONNECTED) while syncing.

Starting sync from ac31iV9. work: +1061877494908983, ours: 6481, theirs: 15651

Finding ancestor using linear search on last 3 blocks starting at 00000...bb62e (6481) from peer ac31iV9 at 15651

Found peer ac31iV9 ancestor 00000...bb62e, syncing from 6481 -> 15651 (9170) after 1 requests

Requesting 20 blocks starting at 00000...bb62e (6481) from ac31iV9

Peer ac31iV9 disconnected (DISCONNECTED) while syncing.

**Comment by T0O0Z** [comment]
Whith docker, click on this and see if it goes back at 32% after 30s / 1min (The bug happened again at 96%
![dock](https://user-images.githubusercontent.com/95851059/145454032-61f2224c-70cc-4858-a034-82a4b4e9b3fe.PNG)

**Comment by JulsKawa** [comment]
> Whith docker, click on this and see if it goes back at 32% after 30s / 1min (The bug happened again at 96%)
> ![dock](https://user-images.githubusercontent.com/95851059/145454032-61f2224c-70cc-4858-a034-82a4b4e9b3fe.PNG)
> 

This work but it's a real issue who need to be resolved

**Comment by dguenther** [comment]
This should be fixed on the latest version of Iron Fish. Please try updating your node to 0.1.15 or later, and if you're still seeing the issue, feel free to reopen this.
