### ISSUE TITLE
ironfish miners:mined bug

### ISSUE THREAD

**Issue by srwhitney19** [iron-fish/ironfish#675]
When running ironfish miners:mined bug the links are now clickable, but they do not work. Nothing populates when visiting that url. See video attachment for experience.

Searching the block hash from the URL produces no results.

 You have to highlight the block hash from the terminal window and paste it into the search bar to find the page that actually shows the block information on the block explorer

https://user-images.githubusercontent.com/37627499/145468265-facf50b3-2f83-4aad-813c-d83b218fcab2.mp4

**Comment by jakegrella** [comment]
this will be fixed with [#601](https://github.com/iron-fish/ironfish/pull/601)

**Comment by srwhitney19** [comment]
Will I get the bug reward points?

**Comment by srwhitney19** [comment]
Will I get the bug reward points?
