### ISSUE TITLE
Account Balance Increased by ~20 IRON On Canceled Transaction

### ISSUE THREAD

**Issue by zkstorm** [iron-fish/ironfish#678]
**Issue**

I attempted to send 1 IRON with a fee of 1 ORE, but ended up killing the process w/Ctrl+C since it was stuck at 100% for a few minutes without any sign of change. After this, I attempted the same transaction again, which completed successfully.

Following the first attempt and second successful attempt, I ran ironfish accounts:balance and noticed that my balance had increased by around 20 IRON.  I had not mined an additional block inbetween checks, and cannot find a root cause for why the balance increased. Interestingly, my account balance also appears to have be decremented by both transactions. 

On a side note, I am aware that "creating the transaction" progress bar also is related to confirming the transaction, but I found this wording, and the hanging at 100% for minutes, to be misleading. 

The increase in balance is what caught my attention. In writing this and attempting to reproduce, I have now added an additional 20 IRON to my balance using the same process. Note that the "available to spend" reflects the expected balance in both cases. 

**Expectation**

No increase in balance and no decrement of balance for the transaction killed while "creating the transaction."

**Supporting Information**

![Screen Shot 2021-12-09 at 11 19 35 PM](https://user-images.githubusercontent.com/84751530/145521466-8997850a-cefe-4bbf-8bc5-9c2f0c84b5b9.png)
![Screen Shot 2021-12-09 at 11 21 23 PM](https://user-images.githubusercontent.com/84751530/145521666-287a0ca1-8ee6-4601-91b9-7d1fd4ee3b4f.png)

**Comment by zkstorm** [comment]
Also seeing some additional odd behavior where my available balance has also increased without reason. Just sent a transaction that should've taken my available balance to 0 (from ~20 IRON), and instead my available balance doubled (to about 39 IRON).

**Comment by wd021** [comment]
I've tried replicating this issue on the latest version (0.1.25), but can't seem to get this result.

Killed the pay process at each stage in the process, but never can I get this inaccurate "increase in account balance" situation. 

@zkstorm can you confirm that this is still the behavior on the latest version? and if you do replicate it, can you provide some more insights. thx.

**Comment by lwisne** [comment]
We think this is fixed now. Closing. Let me know if you believe otherwise.
