### ISSUE TITLE
Block (13014) was not accounted for and did not appear in the leaderboard

### ISSUE THREAD

**Issue by FunkyLSD** [iron-fish/ironfish#680]
It has been a long time, but the block has not been accounted for.
00000000074c90d0e4cdc68adfc819c0a98af968c492118bd615d4ae0e0cb4f5 funkylsd_wallet 20 MAIN 13014: view in web

root@srv22005:~# ironfish config:get blockGraffiti
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run config:get blockGraffiti
"funkylsd_node"

**Comment by deekerno** [comment]
Checking this block number shows that your block was in fact on the main chain. This may have been caused by slowness in our API, which we've been continually working to improve.
