### ISSUE TITLE
missing block

### ISSUE THREAD

**Issue by petroff100289** [iron-fish/ironfish#681]
In the status of my node i got 6 mined block, but if i scan  "ironfish miners:mined" , I got only 5 hashes. It looks like something missing. If i mined it in fork, why does it display on "ironfish status -f"?

**Comment by deekerno** [comment]
When you successfully mine a block on your node, it does not necessarily mean that it will be included on the main chain. You and every other miner on the network are competing to mine the same block, and thus it is entirely possible that another miner submitted their block to the network just moments before yours.

Additionally, the status command shows blocks that you have mined in the current running session.
