### ISSUE TITLE
Can't find block

### ISSUE THREAD

**Issue by x777** [iron-fish/ironfish#682]
GraffitiI: `SPECULARI`
Got from miner message:
`Submitting hash for block 15993 on request 3513 (2772287967219735)`

Node's log shows: `Mining  STARTED - 1 miners, 1 mined`

chain:block 15993 output:
```{
  "block": {
    "graffiti": "woosung",
    "hash": "0000000010867ac60376bd3743376d0a9557f0bfecfb9b8add265747d95af314",
    "previousBlockHash": "00000000048f417537205a377089c3b351dafeafdc1cc827c1436e4519b10a9c",
    "sequence": 15993,
    "timestamp": 1639128442459,
    "transactions": [
      {
        "signature": "c41dd0e06138de16e73d04648d990416ee1e8d6d5491d1b6ac1968199f37364b05670f07854ac84723ae02ba7701de157530f0af7bf475f57347c1ac73e3ff07",
        "hash": "3786469ce19e3c6e4b590e6cc7885bc3192263ea9b557c27a1764ee69f7f7b61",
        "fee": "-2000000000",
        "spends": 0,
        "notes": 1
      }
    ]
  },
  "metadata": {
    "main": true
  }
}
```

`miners:mined` output: nothing

**Comment by deekerno** [comment]
When you successfully mine a block on your node, it does not necessarily mean that it will be included on the main chain. You and every other miner on the network are competing to mine the same block, and thus it is entirely possible that another miner submitted their block to the network just moments before yours. This same possibility is true for every miner on the network.
