### ISSUE TITLE
Zero balance on account imported into another node.

### ISSUE THREAD

**Issue by georeith** [iron-fish/ironfish#683]
I have double checked that my credentials are the same.

Here you can see one of my nodes currently at block 16049:

![image](https://user-images.githubusercontent.com/3090066/145567068-623da8e9-a1f7-42b3-9713-c28c45ddd525.png)

Meanwhile my other account also at block 16049:

![image](https://user-images.githubusercontent.com/3090066/145567172-9df0adbf-390c-4c3c-bc5f-1d30da2a53e1.png)

Same account, one has 0 balance (despite having mined a block with that node) and the other has balance.

**Comment by ozzyjon** [comment]
This issue is similar to this issue that I have raised: https://github.com/iron-fish/ironfish/issues/853

**Comment by wd021** [comment]
@georeith can you verify if this is still an issue on the latest version? can't seem to replicate on my end.
