### ISSUE TITLE
The block mined from my machine ended up in others Graffiti account

### ISSUE THREAD

**Issue by snzhangxx** [iron-fish/ironfish#686]
![bug1](https://user-images.githubusercontent.com/95923488/145587600-64f83858-e84b-454b-8ce9-248846ea6b75.png)
![bug2](https://user-images.githubusercontent.com/95923488/145587630-1df27dbe-362e-45eb-b364-e18266ae8f6b.jpg)
![bug3](https://user-images.githubusercontent.com/95923488/145588028-6c2bb411-8823-4916-a0f1-cbccb4db29a4.jpg)

**Comment by snzhangxx** [comment]
![Uploading bug3.jpg…]()

**Comment by deekerno** [comment]
When you submit a hash for a block, it does not necessarily mean that your block will make it on the main chain. Upon submission, the network checks your block and makes sure that it is indeed a valid block. Furthermore, you are competing with many other miners to submit a block at that particular height. In this case, another miner was able to find a correct hash and submit it to the network before you could do so.
