### ISSUE TITLE
After the update, translations do not work and information about the node is not displayed

### ISSUE THREAD

**Issue by Vesperin7** [iron-fish/ironfish#688]
User/Node name: Vesperino Vesper#6557 mao.vesper77@gmail.com
After the update, translations do not work and information about the node is not displayed. When you enter a command, sometimes the information is loaded, but not completely. You can see it on the screenshot. The problem affects at least a few users.
![ironfishBag](https://user-images.githubusercontent.com/95927742/145600179-e8b0ea49-8712-44ff-a0cf-b2b6ac9fdf61.png)
.

**Comment by dguenther** [comment]
I'm not sure what's in `if_node_info`, but that command wasn't built by the Iron Fish team, so you'll need to contact whoever wrote `if_node_info` and file an issue with them.
