### ISSUE TITLE
Mining on two machines - node is crashing

### ISSUE THREAD

**Issue by MacFxRTM** [iron-fish/ironfish#690]
While masternode is working properly node is crashing from time to time - sometimes is working for 30 minutes, sometimes over 90 min. but finally it crash with errors like attached
![Screen Shot 12-10-21 at 04 35 PM](https://user-images.githubusercontent.com/95928760/145603705-f4863039-eb3b-436f-905c-d83540c20ecc.PNG)
![Screen Shot 12-10-21 at 04 40 PM](https://user-images.githubusercontent.com/95928760/145603730-2ceee377-6ac1-4d2b-b3ce-646d5442610d.PNG)

**Comment by leanthebean** [comment]
I believe this has been fixed in later updates.
