### ISSUE TITLE
Another node is using the database, waiting for that node to close.

### ISSUE THREAD

**Issue by dcliubing** [iron-fish/ironfish#692]
Another node is using the database, waiting for that node to close.
delete  .ironfish folder is not work

**Comment by plaam** [comment]
Same problem here!

**Comment by deekerno** [comment]
This typically happens when you are running multiple `ironfish` commands. Please check that you've ended all `ironfish` processes (`ironfish start`, `ironfish status`, etc.). Additionally, you can check to see if a `LOCK` file is present in the databases folder of your Iron Fish data directory.
