### ISSUE TITLE
Mined blocks are not counted

### ISSUE THREAD

**Issue by yuriikovalchuk** [iron-fish/ironfish#695]
Submitting hash for block 15865 on request 12533 (6809996396474508)
Submitting hash for block 15942 on request 13569 (3886617616858949)
Submitting hash for block 16250 on request 16308 (5451715576167941)

**Comment by dguenther** [comment]
Your mined blocks need to be included on the main chain in order to be counted toward testnet points -- if you run `miners:mined`, do any of those blocks show up with `MAIN` ?

**Comment by yuriikovalchuk** [comment]
No, they don't.

I have new reproductions.

Submitting hash for block 16250 on request 16308 (5451715576167941)
Submitting hash for block 16250 on request 16308 (5451752982758404)
Submitting hash for block 16250 on request 16308 (5451787594727768)

after which it was a OOM

<--- Last few GCs --->

[7:0x5534020] 208074153 ms: Mark-sweep 3887.6 (4143.3) -> 3874.8 (4143.5) MB, 3424.5 / 0.0 ms  (average mu = 0.473, current mu = 0.472) task scavenge might not succeed
[7:0x5534020] 208080591 ms: Mark-sweep 3888.0 (4143.5) -> 3875.0 (4143.8) MB, 3341.8 / 0.0 ms  (average mu = 0.477, current mu = 0.481) task scavenge might not succeed
[7:0x5534020] 208087042 ms: Mark-sweep 3888.1 (4143.8) -> 3875.3 (4144.0) MB, 3362.8 / 0.0 ms  (average mu = 0.478, current mu = 0.479) task scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb02ec0 node::Abort() [node]
 2: 0xa181fb node::FatalError(char const*, char const*) [node]
 3: 0xced88e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xcedc07 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xea5ea5  [node]
 6: 0xeb557d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 7: 0xf18844 v8::internal::ScavengeJob::Task::RunInternal() [node]
 8: 0xdabcfb non-virtual thunk to v8::internal::CancelableTask::Run() [node]
 9: 0xb707a4 node::PerIsolatePlatformData::RunForegroundTask(std::unique_ptr<v8::Task, std::default_delete<v8::Task> >) [node]
10: 0xb72609 node::PerIsolatePlatformData::FlushForegroundTasksInternal() [node]
11: 0x155a396  [node]
12: 0x156c804  [node]
13: 0x155acc8 uv_run [node]
14: 0xa3ffe5 node::SpinEventLoop(node::Environment*) [node]
15: 0xb45056 node::NodeMainInstance::Run(node::EnvSerializeInfo const*) [node]
16: 0xac67e2 node::Start(int, char**) [node]
17: 0x7fd6ab3ead0a __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
18: 0xa3bfbc  [node]
Aborted

**Comment by yuriikovalchuk** [comment]
6 more submits which not present in main :(

Submitting hash for block 16785 on request 899 (7933004775100858)
Submitting hash for block 16878 on request 951 (1276626895333649)
Submitting hash for block 17345 on request 1285 (2523982692416401)
Submitting hash for block 17429 on request 1747 (5259134730160072)
Submitting hash for block 17486 on request 1869 (3157672914120244)
Submitting hash for block 17516 on request 1905 (6980897548021529)

**Comment by yuriikovalchuk** [comment]
Submitting hash for block 18673 on request 1056 (8751579203089965)
Submitting hash for block 19225 on request 3108 (2522532105283484)
Submitting hash for block 19268 on request 3110 (7512070050254587)
Submitting hash for block 19307 on request 3113 (6273089069106654)
Submitting hash for block 19307 on request 3113 (6273089424138862)
Submitting hash for block 19307 on request 3113 (6273097140939651)
Submitting hash for block 19307 on request 3113 (6273105974539044)
Submitting hash for block 19307 on request 3113 (6273108450947608)
Submitting hash for block 19548 on request 3170 (7296683873807506)
Submitting hash for block 19840 on request 3319 (767593737439097)
Submitting hash for block 19958 on request 3341 (4138825599606521)
Submitting hash for block 20025 on request 3356 (5456548023880693)
Submitting hash for block 20088 on request 3371 (7876592209628038)
Submitting hash for block 20088 on request 3371 (7876612030966965)
Submitting hash for block 20088 on request 3371 (7876616682631004)
Submitting hash for block 20088 on request 3371 (7876618038797385)
Submitting hash for block 20088 on request 3371 (7876620059097791)
Submitting hash for block 20088 on request 3371 (7876636334788677)
Submitting hash for block 20088 on request 3371 (7876640736034836)
Submitting hash for block 20088 on request 3371 (7876640773814990)
Submitting hash for block 20088 on request 3371 (7876649457198689)
Submitting hash for block 20088 on request 3371 (7876667582083624)
Submitting hash for block 20088 on request 3371 (7876685577220230)

Again, none of these is mined actually

**Comment by deekerno** [comment]
When you successfully mine a block on your node, it does not necessarily mean that it will be included on the main chain. You and every other miner on the network are competing to mine the same block, and thus it is entirely possible that another miner submitted their block to the network just moments before yours. This same possibility is true for every miner on the network.
