### ISSUE TITLE
accounts:pay allows for very long, very granular (small decimal), and leading zeroes. Outputs back to console.

### ISSUE THREAD

**Issue by zkstorm** [iron-fish/ironfish#699]
**Issue**

I attempted to enter 3 kinds of values when using accounts:pay:

1. Very large and absurd values (100+ 9s for example)
2. Large number of leading zeroes
3. Small granular amounts that shouldn't be allowed (0.0000000100000001 IRON for example).

This never led to an invalid transaction on the blockchain, but in all cases, it let me input these up to the point it created the transaction (2 and 3 were valid and went through, however, as expected). For each one, the command line echoed back the value that I input, which may be misleading. Some additional input checking and formatting would be helpful to confirm what is actually happening. 

Screenshots demonstrate these in sufficient detail and are easily understood. In one case, the amount of ORE I'm transacting with is marked as "Infinity".

**Expectation**

Invalid values should be either truncated (e.g. 0.00000001001 -> 0.00000001) or marked as invalid. Leading 0s should be formatted off of the echo-backs. 

**Supporting Resources**

<img width="965" alt="Screen Shot 2021-12-10 at 3 45 10 PM" src="https://user-images.githubusercontent.com/84751530/145645965-0b538a5d-82f9-46f2-ab32-118916654323.png">
<img width="965" alt="Screen Shot 2021-12-10 at 3 49 23 PM" src="https://user-images.githubusercontent.com/84751530/145645993-710947ff-2805-4d1a-902b-135828315977.png">
<img width="965" alt="Screen Shot 2021-12-10 at 3 50 44 PM" src="https://user-images.githubusercontent.com/84751530/145645998-3fbf4cdd-a887-4a4d-a618-61cf0e563ca6.png">

**Comment by wd021** [comment]
working on improving this

**Comment by wd021** [comment]
should be fixed with https://github.com/iron-fish/ironfish/pull/1089

**Comment by lwisne** [comment]
We believe this is now closed. Let us know if you don't agree!
