### ISSUE TITLE
soft lockup bugs reported

### ISSUE THREAD

**Issue by fernando42** [iron-fish/ironfish#701]
CPU: AMD 3900x
OS: UBUNTU 20.04
Graffiti: fernando

Message from syslogd@zyr at Dec 10 05:25:44 ...
 kernel:[55716.328117] watchdog: BUG: soft lockup - CPU#0 stuck for 27s! [node:1984]

Message from syslogd@zyr at Dec 10 05:25:44 ...
 kernel:[55716.331981] watchdog: BUG: soft lockup - CPU#9 stuck for 27s! [kworker/9:0:24827]

Message from syslogd@zyr at Dec 10 05:26:41 ...
 kernel:[55773.109671] watchdog: BUG: soft lockup - CPU#1 stuck for 22s! [node:297680]

Message from syslogd@zyr at Dec 10 05:26:55 ...
 kernel:[55787.066677] NMI watchdog: Watchdog detected hard LOCKUP on cpu 3

Message from syslogd@zyr at Dec 10 05:29:25 ...
 kernel:[55937.153564] watchdog: BUG: soft lockup - CPU#23 stuck for 22s! [node:297675]

Message from syslogd@zyr at Dec 10 05:29:28 ...
 kernel:[55939.882275] NMI watchdog: Watchdog detected hard LOCKUP on cpu 10

Message from syslogd@zyr at Dec 10 05:31:24 ...
 kernel:[56056.094898] NMI watchdog: Watchdog detected hard LOCKUP on cpu 8

Message from syslogd@zyr at Dec 10 05:31:44 ...
 kernel:[56076.238577] watchdog: BUG: soft lockup - CPU#20 stuck for 22s! [SCTP timer:2111]

Message from syslogd@zyr at Dec 10 05:31:44 ...
 kernel:[56076.238926] watchdog: BUG: soft lockup - CPU#21 stuck for 37s! [node:297692]

Message from syslogd@zyr at Dec 10 05:32:44 ...
 kernel:[56113.123716] watchdog: BUG: soft lockup - CPU#9 stuck for 22s! [node:297681]

Message from syslogd@zyr at Dec 10 05:32:44 ...
 kernel:[56113.147739] watchdog: BUG: soft lockup - CPU#20 stuck for 22s! [node:297675]

Message from syslogd@zyr at Dec 10 05:32:44 ...
 kernel:[56113.151749] watchdog: BUG: soft lockup - CPU#22 stuck for 22s! [node:1988]

Message from syslogd@zyr at Dec 10 05:32:44 ...
 kernel:[56136.210485] watchdog: BUG: soft lockup - CPU#14 stuck for 43s! [kworker/u256:4:331971]

Message from syslogd@zyr at Dec 10 05:34:16 ...
 kernel:[56228.155718] NMI watchdog: Watchdog detected hard LOCKUP on cpu 13

Message from syslogd@zyr at Dec 10 05:35:49 ...
 kernel:[56321.111456] watchdog: BUG: soft lockup - CPU#2 stuck for 23s! [node:333996]

Message from syslogd@zyr at Dec 10 05:35:49 ...
 kernel:[56321.119461] watchdog: BUG: soft lockup - CPU#5 stuck for 23s! [node:333997]

Message from syslogd@zyr at Dec 10 05:36:17 ...
 kernel:[56349.110400] watchdog: BUG: soft lockup - CPU#2 stuck for 23s! [node:333996]

Message from syslogd@zyr at Dec 10 05:36:17 ...
 kernel:[56349.118406] watchdog: BUG: soft lockup - CPU#5 stuck for 23s! [node:333997]

Message from syslogd@zyr at Dec 10 05:36:33 ...
 kernel:[56364.666244] watchdog: BUG: soft lockup - CPU#1 stuck for 37s! [vmtoolsd:1058]

Message from syslogd@zyr at Dec 10 05:36:33 ...
 kernel:[56364.666316] watchdog: BUG: soft lockup - CPU#16 stuck for 37s! [kworker/16:1H:740]

Message from syslogd@zyr at Dec 10 05:36:33 ...
 kernel:[56364.666396] watchdog: BUG: soft lockup - CPU#10 stuck for 25s! [kworker/10:2:275060]

Message from syslogd@zyr at Dec 10 05:36:33 ...
 kernel:[56364.668157] NMI watchdog: Watchdog detected hard LOCKUP on cpu 14

Message from syslogd@zyr at Dec 10 05:37:01 ...
 kernel:[56393.139070] watchdog: BUG: soft lockup - CPU#17 stuck for 23s! [node:334603]

Message from syslogd@zyr at Dec 10 05:37:05 ...
 kernel:[56397.130623] watchdog: BUG: soft lockup - CPU#12 stuck for 22s! [node:1984]

Message from syslogd@zyr at Dec 10 05:38:41 ...
 kernel:[56493.146208] watchdog: BUG: soft lockup - CPU#20 stuck for 24s! [node:1984]

Message from syslogd@zyr at Dec 10 05:38:45 ...
 kernel:[56497.232866] watchdog: BUG: soft lockup - CPU#21 stuck for 30s! [node:334611]

Message from syslogd@zyr at Dec 10 05:39:17 ...
 kernel:[56529.114401] watchdog: BUG: soft lockup - CPU#4 stuck for 22s! [node:334607]

**Comment by dguenther** [comment]
This is likely a kernel or hardware bug with your machine, or just related to using the max resources of your machine. See these articles, for example: https://kb.vmware.com/s/article/1009996 https://askubuntu.com/questions/1257939/20-04-soft-lockup

If you'd like to reduce the resources the node is using, try starting with `nodeWorkers` set to a lower number, like 2. Or mining with `--threads` set to a lower number.
