### ISSUE TITLE
Mined blocks added to forks are counted as 'mined' blocks. 

### ISSUE THREAD

**Issue by kernel32uiuc** [iron-fish/ironfish#702]
The blocks mined locally but added to forks should not be reported as mined blocks. status command will report those blocks as 'mined':

./ironfish status:

Version 0.1.9 @ src
Node STARTED
Mining STARTED - 1 miners, X mined
...

------------

Successfully mined block 00000000076ef9860eba6ba1009946f9d6f3573e3f5ad2d0fdeb06177a6ade01 (**15879**) has 2 transactions

Added block to fork seq: **15879**, head-seq: 15879, hash: 00000...ade01, head-hash: 00000...52ba7, work: 1221616441828749, head-work: 1221616441828749, work-diff: 0

**Comment by deekerno** [comment]
Fixed as of #704.
