### ISSUE TITLE
Testnet Leaderboard on mobile

### ISSUE THREAD

**Issue by srwhitney19** [iron-fish/ironfish#703]
Testnet mobile view has a number of bugs in how it is rendered

![2927AB8C-0C05-4A66-BC12-4F120C3527B3](https://user-images.githubusercontent.com/37627499/145666142-30d058e2-7c1c-44dc-b5a4-64e03c77fb43.jpeg)

**Comment by leanthebean** [comment]
Referenced this issue in an [open issue on the testnet website repo](https://github.com/iron-fish/website-testnet/issues/171) instead
