### ISSUE TITLE
Mempool and reset node

### ISSUE THREAD

**Issue by wowss** [iron-fish/ironfish#706]
After a while a lot of transactions appear in mempool. After restarting the node, everything is fine.

**Comment by wowss** [comment]
![image](https://user-images.githubusercontent.com/89159322/145732129-29986157-ed8f-4159-9416-decc0f78bec8.png)

**Comment by deekerno** [comment]
Does this issue still persist after the latest update?

**Comment by wowss** [comment]
All works fine!
