### ISSUE TITLE
balance issue

### ISSUE THREAD

**Issue by andyxie016** [iron-fish/ironfish#713]
updated version to 0.1.9, but the accounts balance is zero.
in the version of 0.1.8, there is ablance in the same accounts.

attached two pictures in different version.

<img width="684" alt="018 accounts" src="https://user-images.githubusercontent.com/95515918/145699115-1f8c367b-b791-45d7-a04d-11d111a238a8.PNG">
<img width="676" alt="019 accounts" src="https://user-images.githubusercontent.com/95515918/145699118-5ca2bfba-d9f3-4c5e-bb23-676482b03bce.PNG">

**Comment by ozzyjon** [comment]
I have a similar issue and have created this ticket: https://github.com/iron-fish/ironfish/issues/853

**Comment by wd021** [comment]
Tested accounts:balance quite a bit in the past few days. Can't seem to replicate on latest version. @ozzyjon can you confirm this is still an issue? Also, in your screenshot, your @ HEAD is off by a lot in your 2 statuses.
