### ISSUE TITLE
Memory Leak Error on Large Server Machine

### ISSUE THREAD

**Issue by guytenn** [iron-fish/ironfish#715]
Benchmarking over server with 2x64 cpus raises a memory leak error. This error does not exist on machines with 20 or 40 cpus.

![image](https://user-images.githubusercontent.com/25770010/145704704-25e0d1df-1eb3-4fbd-84d4-fea8ba7db39e.png)

**Comment by deekerno** [comment]
Does this issue still persist for you on the latest update?

**Comment by guytenn** [comment]
Problem has been resolved in 0.1.11. Thank you.
