### ISSUE TITLE
SYNCED Node does not match block explorer, miner several blocks behind

### ISSUE THREAD

**Issue by Andrew-M-Cox** [iron-fish/ironfish#720]
As you can notice in my screen capture, the block explorer shows a height that behind my node. Further my miner is mining several blocks behind my node.
<img width="1185" alt="Screen Shot 2021-12-12 at 8 02 54 AM" src="https://user-images.githubusercontent.com/53104102/145715721-5f1fdf91-1fb8-400e-90ed-c9bf0c160cff.png">

**Comment by deekerno** [comment]
This was partially due to our API node becoming unresponsive. While we've alleviated some of the issue, we're continuing to work on improving the recency of the data in the block explorer.
