### ISSUE TITLE
Mining stops due to lack of heap memory space in Node js.

### ISSUE THREAD

**Issue by kawanami-kosuke** [iron-fish/ironfish#721]
I started mining, and after a few hours, it stopped with the following error.
When I ran systemctl restart ironfished-miner, mining resumed normally. This happened only once.

Server info
Ubuntu 20.4 LTS
CPU 64C
Memory 512GB
SSD 256GB
runtime    node/16.13.1
ironfish version    0.1.9

`Dec 11 04:12:27 myserver yarn[30618]: <--- Last few GCs --->
Dec 11 04:12:27 myserver yarn[30618]: [30618:0x52d8040] 177309778 ms: Mark-sweep 4033.1 (4128.9) -> 4019.9 (4129.1) MB, 4716.3 / 0.0 ms  (average mu = 0.192, current mu = 0.140) t>
Dec 11 04:12:27 myserver yarn[30618]: [30618:0x52d8040] 177315154 ms: Mark-sweep 4032.6 (4129.1) -> 4020.0 (4128.9) MB, 4631.7 / 0.0 ms  (average mu = 0.167, current mu = 0.139) t>
Dec 11 04:12:27 myserver yarn[30618]: <--- JS stacktrace --->
Dec 11 04:12:27 myserver yarn[30618]: FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
Dec 11 04:12:27 myserver yarn[30618]:  1: 0xb00d90 node::Abort() [/usr/bin/node]
Dec 11 04:12:27 myserver yarn[30618]:  2: 0xa1823b node::FatalError(char const*, char const*) [/usr/bin/node]
Dec 11 04:12:27 myserver yarn[30618]:  3: 0xcedbce v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
Dec 11 04:12:27 myserver yarn[30618]:  4: 0xcedf47 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
Dec 11 04:12:27 myserver yarn[30618]:  5: 0xea6105  [/usr/bin/node]
Dec 11 04:12:27 myserver yarn[30618]:  6: 0xea6be6  [/usr/bin/node]
Dec 11 04:12:27 myserver yarn[30618]:  7: 0xeb4b1e  [/usr/bin/node]
Dec 11 04:12:27 myserver yarn[30618]:  8: 0xeb5560 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/>
Dec 11 04:12:27 myserver yarn[30618]:  9: 0xf18aa4 v8::internal::ScavengeJob::Task::RunInternal() [/usr/bin/node]
Dec 11 04:12:27 myserver yarn[30618]: 10: 0xdabeeb non-virtual thunk to v8::internal::CancelableTask::Run() [/usr/bin/node]
Dec 11 04:12:27 myserver yarn[30618]: 11: 0xb6e964 node::PerIsolatePlatformData::RunForegroundTask(std::unique_ptr<v8::Task, std::default_delete<v8::Task> >) [/usr/bin/node]
Dec 11 04:12:27 myserver yarn[30618]: 12: 0xb707c9 node::PerIsolatePlatformData::FlushForegroundTasksInternal() [/usr/bin/node]
Dec 11 04:12:27 myserver yarn[30618]: 13: 0x155a336  [/usr/bin/node]
Dec 11 04:12:27 myserver yarn[30618]: 14: 0x156c7a4  [/usr/bin/node]
Dec 11 04:12:27 myserver yarn[30618]: 15: 0x155ac68 uv_run [/usr/bin/node]
Dec 11 04:12:27 myserver yarn[30618]: 16: 0xa3dfe5 node::SpinEventLoop(node::Environment*) [/usr/bin/node]
Dec 11 04:12:27 myserver yarn[30618]: 17: 0xb42dc6 node::NodeMainInstance::Run(node::EnvSerializeInfo const*) [/usr/bin/node]
Dec 11 04:12:27 myserver yarn[30618]: 18: 0xac4812 node::Start(int, char**) [/usr/bin/node]
Dec 11 04:12:27 myserver yarn[30618]: 19: 0x7ff41b3d90b3 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
Dec 11 04:12:27 myserver yarn[30618]: 20: 0xa3bf3c  [/usr/bin/node]
Dec 11 04:12:28 myserver yarn[30599]: error Command failed with exit code 1.
Dec 11 04:12:28 myserver yarn[30599]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by deekerno** [comment]
Does this issue still persist after the latest update?

**Comment by leanthebean** [comment]
I believe this has been fixed in later versions.
