### ISSUE TITLE
It's not error or issue) It's idea how fix it)

### ISSUE THREAD

**Issue by ynateling** [iron-fish/ironfish#723]
You can raise several **servers** with the actual data chain (the block chain can be copied from the server that displays information in explorer). And in the new update set the synchronization priority with these **servers**. Then new users will not encounter the problem of slow synchronization. 

This is important if ironfish plans to scale).

I'm sure there are more elegant solutions to this problem (you can try to implement them after the solution above, but the solution above is very easy to implement)

**Comment by leanthebean** [comment]
Syncing from a snapshot is indeed on our roadmap. Closing this for now since it's not an actual issue but a feature request.
