### ISSUE TITLE
A lot of forks in 0.1.10 @ 191d772 update

### ISSUE THREAD

**Issue by ynateling** [iron-fish/ironfish#724]
And in new update (0.1.10 @ 191d772) a lt of peoples can't sync their node with blockchain. I restart my node several times and time after time my node would go into a fork and start mining on the wrong network.

**Comment by ynateling** [comment]
![image](https://user-images.githubusercontent.com/90978662/145730840-a8561c66-b3af-44af-8a6c-541a9998704a.png)
But head block about 19k (on moment of writing this phrase head block is 19034 block)

**Comment by ynateling** [comment]
![image](https://user-images.githubusercontent.com/90978662/145730940-aad1d0db-9fc3-4b5f-80bc-513a8c8aee91.png)

Many nodes can't send actual blockchain

I try restart my node, but it's didn't work

**Comment by shandongdacongge** [comment]
I meet this questions too.
any resolve?

**Comment by leanthebean** [comment]
This has been fixed in later updates
