### ISSUE TITLE
Max synced age is not suitable for current network

### ISSUE THREAD

**Issue by testingPurposes1** [iron-fish/ironfish#727]
I've noticed that current MAX_SYNCED_AGE_MS in consensus.ts can provide much instability.
With last commit value of this constant was changed to 12 hours instead of 60 seconds, and now people and me can't just be synced for hours, it should be way more lower value - 4x was suggested by Jason in the last commit,  2x and 3x also can be working.

**Comment by testingPurposes1** [comment]
To reproduce this issue just run ironfish reset, node most likely to stop and be synced at 18890 block.

**Comment by deekerno** [comment]
This value has since been adjusted to a more reasonable value. If you're continuing to encounter this issue after updating to the newest version, feel free to re-open.
