### ISSUE TITLE
[BUG] ironfish-miner stop show logs after some period

### ISSUE THREAD

**Issue by mrrusik** [iron-fish/ironfish#728]
versionL 0.1.10

ironfish-miner stop show logs after some period (for example after all night mining) 

NodeName: rekap
grafiti: rekap

Logs on atached screen more detailed:
`ironfish-miner    | Submitting hash for block 19209 on request 223 (1848331768472204)
ironfish-miner    | Mining block 19314 on request 224... 418003 H/s
ironfish          | Added block to fork seq: 19319, head-seq: 19319, hash: 00000...c11c8, head-hash: 00000...7b094, work: 1324624640198422, head-work: 1324624640198422, work-diff: 0
ironfish          | Added block seq: 19320, hash: 00000...f9381, txs: 2, progress: 100.00%, time: 16828.7ms
ironfish          | Added block to fork seq: 19322, head-seq: 19322, hash: 00000...ddb9b, head-hash: 00000...0f191, work: 1324658190692208, head-work: 1324658196154676, work-diff: 5462468
ironfish          | Added block to fork seq: 19037, head-seq: 19336, hash: 00000...20cb8, head-hash: 00000...df097, work: 1320722944461773, head-work: 1324815268849613, work-diff: 4092324387840
ironfish          | Invalid block adding to fork 00000...d57b0 (18612): Transaction expired
ironfish          | Peer V8g2Sv5 (mddl.fngz) sent an invalid block. score: 10, hash: 00000...d57b0 (
ironfish          |           18612
ironfish          |         ), reason: Transaction expired
ironfish          | Peer V8g2Sv5 (mddl.fngz) has been banned: Transaction expired
ironfish          | Invalid block adding to fork 00000...4cd4d (18705): Transaction expired
ironfish          | Peer u57ZN4u (sunren) sent an invalid block. score: 10, hash: 00000...4cd4d (
ironfish          |           18705
ironfish          |         ), reason: Transaction expired
ironfish          | Peer u57ZN4u (sunren) has been banned: Transaction expired
ironfish          | Added block to fork seq: 19337, head-seq: 19337, hash: 00000...1a341, head-hash: 00000...c0759, work: 1324826428465662, head-work: 1324826428465662, work-diff: 0
ironfish          | Added block to fork seq: 18649, head-seq: 19339, hash: 00000...cf63a, head-hash: 00000...ba8ed, work: 1311057988870088, head-work: 1324848676889628, work-diff: 13790688019540
ironfish          | Added block seq: 19340, hash: 00000...48a8a, txs: 2, progress: 100.00%, time: 16444.0ms`

**ironfish status -f** logs:
`Version              0.1.10 @ 191d772
Node                 STARTED
P2P Network          CONNECTED - In: 66 KB/s, Out: 51 KB/s, peers 49
Mining               STARTED - 1 miners, 0 mined
Mem Pool             203 tx
Syncer               IDLE @ 0.09 blocks per seconds | avg time to add block 10206.88 ms
Blockchain           SYNCED @ HEAD 000000003771477a6117ae893231ce3f159a02c0366735a0c082
be22af9dce9f (19384)
Workers              STARTED - 0 -> 0 / 9 - 0 jobs ?, 0 jobs/s`

![image](https://user-images.githubusercontent.com/11456782/145760286-8e474c49-b033-41e3-abd9-8c6f33bcc895.png)

**Comment by deekerno** [comment]
Are you still encountering this issue after updating to the newest version?

**Comment by mrrusik** [comment]
No
