### ISSUE TITLE
Can't sync node 14301

### ISSUE THREAD

**Issue by iephesus** [iron-fish/ironfish#729]
see the local ironfish node log,the block 14301 can't sync..

Version       0.1.10 @ 191d772
Node Name     NONE
Peer Identity Ltgg9CoMLcTEAorWUAlHVUiekdHfFSYVlwBK9vDwNCs=
Peer Agent    if/cli/191d772
Peer Port     9033
Bootstrap     test.bn1.ironfish.network
blockGraffiti : aisurohito

![Snipaste_2021-12-13_14-08-03](https://user-images.githubusercontent.com/8626162/145761149-9bb98761-ba55-49c3-bba5-feeaf1324d02.png)

**Comment by CumpsD** [comment]
Check https://github.com/iron-fish/ironfish/issues/725 for a solution

**Comment by iephesus** [comment]
> 

ok thanks

**Comment by iephesus** [comment]
> ok,thanks
