### ISSUE TITLE
Lots of requests on version 0.1.10 @ 191d772

### ISSUE THREAD

**Issue by wowss** [iron-fish/ironfish#730]
![image](https://user-images.githubusercontent.com/89159322/145782431-cbd6182a-18fa-483f-b175-15614970a1f8.png)

**Comment by wowss** [comment]
It helps to restart the miner, and after a while all over again. This did not happen with the previous version.

**Comment by leanthebean** [comment]
This is a bug with the logs (and how they're displayed) more than anything else.

**Comment by lwisne** [comment]
We believe this is now closed. Let us know if you don't agree!
