### ISSUE TITLE
blake3 shows no hash rate improvement for Zen 2 CPUs

### ISSUE THREAD

**Issue by gjfrn** [iron-fish/ironfish#732]
Since upgrading to 0.1.10, I have not observed any significant hash rate improvement (certainly nothing like 15%) for the following AMD Zen2 CPUs:
Ryzen 5 3600
Ryzen 7 3700X
Ryzen 9 3900X

This is in reference to the following update: Use blake3 instead of blake3-wasm in our miner leading to a 15% increase in hash rate #698

**Comment by shandongdacongge** [comment]
I think so .
the update has no improvement.

**Comment by gjfrn** [comment]
Am pleased to report that this issue is resolved in 1.1.12 due to https://github.com/iron-fish/ironfish/pull/815

**Comment by NullSoldier** [comment]
Ok, this looks like it has been resolved, yes?

**Comment by gjfrn** [comment]
> Ok, this looks like it has been resolved, yes?

Correct. Closing this issue now.
