### ISSUE TITLE
syncing orphan chain . What is the solution

### ISSUE THREAD

**Issue by bizhenlong** [iron-fish/ironfish#734]
syncing orphan chain . What is the solution
`
Finding ancestor using linear search on last 3 blocks starting at 00000...3aef9 (14301) from peer aejVz2k (sanketsohaliya) at 16391
Found peer aejVz2k (sanketsohaliya) ancestor 00000...3aef9, syncing from 14301 -> 16391 (2090) after 1 requests
Requesting 20 blocks starting at 00000...3aef9 (14301) from aejVz2k (sanketsohaliya)
Peer aejVz2k (sanketsohaliya) disconnected (DISCONNECTED) while syncing.
Peer zSIepL+ (RussellGalt) sent orphan 00000...b1264 (19523), syncing orphan chain.
Starting sync from zSIepL+ (RussellGalt). work: +404448743884742, ours: 14301, theirs: 19610
Finding ancestor using linear search on last 3 blocks starting at 00000...3aef9 (14301) from peer zSIepL+ (RussellGalt) at 19610
Found peer zSIepL+ (RussellGalt) ancestor 00000...3aef9, syncing from 14301 -> 19610 (5309) after 1 requests
Requesting 20 blocks starting at 00000...3aef9 (14301) from zSIepL+ (RussellGalt)
Peer zSIepL+ (RussellGalt) disconnected (DISCONNECTED) while syncing.
Starting sync from ExGpU2g. work: +397583714869908, ours: 14301, theirs: 19074
Finding ancestor using linear search on last 3 blocks starting at 00000...3aef9 (14301) from peer ExGpU2g at 19074
Peer ExGpU2g disconnected (DISCONNECTED) while syncing.
Starting sync from iGaQEje. work: +330415338388219, ours: 14301, theirs: 16569
Finding ancestor using linear search on last 3 blocks starting at 00000...3aef9 (14301) from peer iGaQEje at 16569
Found peer iGaQEje ancestor 00000...3aef9, syncing from 14301 -> 16569 (2268) after 1 requests
Requesting 20 blocks starting at 00000...3aef9 (14301) from iGaQEje
Peer iGaQEje disconnected (DISCONNECTED) while syncing.
Starting sync from hJlxjwF (Saboluigi). work: +382521624518401, ours: 14301, theirs: 18529
Finding ancestor using linear search on last 3 blocks starting at 00000...3aef9 (14301) from peer hJlxjwF (Saboluigi) at 18529
Found peer hJlxjwF (Saboluigi) ancestor 00000...3aef9, syncing from 14301 -> 18529 (4228) after 1 requests
Requesting 20 blocks starting at 00000...3aef9 (14301) from hJlxjwF (Saboluigi)
Peer hJlxjwF (Saboluigi) disconnected (DISCONNECTED) while syncing.
Starting sync from 2Njjxjk (mazofazo). work: +411403448228028, ours: 14301, theirs: 20123
Finding ancestor using linear search on last 3 blocks starting at 00000...3aef9 (14301) from peer 2Njjxjk (mazofazo) at 20123
Found peer 2Njjxjk (mazofazo) ancestor 00000...3aef9, syncing from 14301 -> 20123 (5822) after 1 requests
Requesting 20 blocks starting at 00000...3aef9 (14301) from 2Njjxjk (mazofazo)
Peer 2Njjxjk (mazofazo) disconnected (DISCONNECTED) while syncing.
Starting sync from BFPeqtw (ISKIN). work: +349996335198468, ours: 14301, theirs: 17640
Finding ancestor using linear search on last 3 blocks starting at 00000...3aef9 (14301) from peer BFPeqtw (ISKIN) at 17640
Found peer BFPeqtw (ISKIN) ancestor 00000...3aef9, syncing from 14301 -> 17640 (3339) after 1 requests
Requesting 20 blocks starting at 00000...3aef9 (14301) from BFPeqtw (ISKIN)
Peer BFPeqtw (ISKIN) disconnected (DISCONNECTED) while syncing.
Starting sync from CCjUmk+. work: +411355500225647, ours: 14301, theirs: 20120
Finding ancestor using linear search on last 3 blocks starting at 00000...3aef9 (14301) from peer CCjUmk+ at 20120
Found peer CCjUmk+ ancestor 00000...3aef9, syncing from 14301 -> 20120 (5819) after 1 requests
Requesting 20 blocks starting at 00000...3aef9 (14301) from CCjUmk+
Peer CCjUmk+ disconnected (DISCONNECTED) while syncing.
Starting sync from n/Bh+Sh (Susanna). work: +393081144157498, ours: 14301, theirs: 18847
Finding ancestor using linear search on last 3 blocks starting at 00000...3aef9 (14301) from peer n/Bh+Sh (Susanna) at 18847
Found peer n/Bh+Sh (Susanna) ancestor 00000...3aef9, syncing from 14301 -> 18847 (4546) after 1 requests
Requesting 20 blocks starting at 00000...3aef9 (14301) from n/Bh+Sh (Susanna)
Peer n/Bh+Sh (Susanna) disconnected (DISCONNECTED) while syncing.
Starting sync from uiNdYyj (zaebaza). work: +411419485549128, ours: 14301, theirs: 20124
Finding ancestor using linear search on last 3 blocks starting at 00000...3aef9 (14301) from peer uiNdYyj (zaebaza) at 20124
Found peer uiNdYyj (zaebaza) ancestor 00000...3aef9, syncing from 14301 -> 20124 (5823) after 1 requests
Requesting 20 blocks starting at 00000...3aef9 (14301) from uiNdYyj (zaebaza)
Peer uiNdYyj (zaebaza) disconnected (DISCONNECTED) while syncing.
Starting sync from q6/zQCv (Vovan9669node). work: +411195944339041, ours: 14301, theirs: 20110
Finding ancestor using linear search on last 3 blocks starting at 00000...3aef9 (14301) from peer q6/zQCv (Vovan9669node) at 20110
Found peer q6/zQCv (Vovan9669node) ancestor 00000...3aef9, syncing from 14301 -> 20110 (5809) after 1 requests
Requesting 20 blocks starting at 00000...3aef9 (14301) from q6/zQCv (Vovan9669node)
`

**Comment by deekerno** [comment]
Your node is still properly syncing the chain from other nodes in the network. An orphan block (and subsequently a chain) is a received block whose previous block is not present in your chain. We haven't fully implemented all the operations around this type of event, so the node gets more information from the node sending the orphan block in case it needs it later. In any case, your node is/was still working properly.
