### ISSUE TITLE
mined 12 blocks, status: fork

### ISSUE THREAD

**Issue by kdolli072** [iron-fish/ironfish#742]
Good day!
My graffiti on leaderboard: kdolli072
I mined 12 blocks on the IronFish testnet.
All 12 blocks were found to be illiquid. Block status - fork.
Help fix the situation.
The operating system UBUNTU 20.04 and the IronFish miner reinstalled, the problem was not solved.

**Comment by gjfrn** [comment]
Duplicate of #731

**Comment by lwisne** [comment]
We think this is fixed now. Closing. Let me know if you believe otherwise.
