### ISSUE TITLE
Block height higher than main chain

### ISSUE THREAD

**Issue by nftcurator** [iron-fish/ironfish#745]
My node says the current Block height is 21212 where as the explorer says Block height is 20894
<img width="712" alt="Screenshot 2021-12-14 at 10 39 28 AM" src="https://user-images.githubusercontent.com/96113232/145972909-fc3f697a-6991-46f8-b9b9-5a1b1ec93599.png">

![Screenshot 2021-12-14 at 10 40 47 AM](https://user-images.githubusercontent.com/96113232/145973142-a2766d6f-1ebb-483b-8a00-fc20937a4092.png)
How do I resolve this?

**Comment by gleason86** [comment]
I am having the same issue, it appears my miner can't determine that it is mining on a forked chain

**Comment by CumpsD** [comment]
The explorer is not always up to date.

**Comment by deekerno** [comment]
The block explorer gets its information from another node; sometimes, that node may be slightly behind, but will eventually catch up to the head of the chain. We're also investigating ways to minimize this occurrence.
