### ISSUE TITLE
Double leader board entry

### ISSUE THREAD

**Issue by roadswithoutend** [iron-fish/ironfish#746]
![image](https://user-images.githubusercontent.com/96118587/145989241-b5836ad0-3379-4778-b8c3-14b619fdfd52.png)

My graffiti got doubled somehow. Couldn't remember anything in my actions for it to happen.
Thank you.

**Comment by zkstorm** [comment]
Thinking this should be in the testnet website repo: https://github.com/iron-fish/website-testnet/issues

**Comment by roadswithoutend** [comment]
Thank you. Will put it there and close this one.
