### ISSUE TITLE
Peer 62jaf+2 has been banned

### ISSUE THREAD

**Issue by webdevandseo** [iron-fish/ironfish#752]
ironfish          | Invalid block adding to fork 00000...605ce (18526): Transaction expired
ironfish          | Peer 62jaf+2 sent an invalid block. score: 10, hash: 00000...605ce (
ironfish          |           18526
ironfish          |         ), reason: Transaction expired
ironfish          | Peer 62jaf+2 has been banned: Transaction expired
ironfish          | Peer 62jaf+2 disconnected (DISCONNECTED) while syncing.

**Comment by webdevandseo** [comment]
ironfish          | Requesting 20 blocks starting at 00000...d9aff (18517) from /IBIlVn (guandon)
ironfish          | Peer /IBIlVn (guandon) has been banned: error
ironfish          | Peer /IBIlVn (guandon) sent an invalid block. score: 10, hash: 00000...605ce (
ironfish          |           18526
ironfish          |         ), reason: error
ironfish          | Peer /IBIlVn (guandon) disconnected (DISCONNECTED) while syncing.
ironfish          | Invalid block adding to fork 00000...40acc (20642): Transaction expired
ironfish          | Peer MdPFMKM (cryptolife) sent an invalid block. score: 10, hash: 00000...40acc (
ironfish          |           20642
ironfish          |         ), reason: Transaction expired
ironfish          | Peer MdPFMKM (cryptolife) has been banned: Transaction expired

**Comment by dguenther** [comment]
This should be fixed as of v0.1.12, please open a new issue if you're still seeing this problem after upgrading.
