### ISSUE TITLE
Large portion of CLI commands timing out on my running node

### ISSUE THREAD

**Issue by DavisTrey** [iron-fish/ironfish#757]
I have a node and miner running. I ran "yarn start config:get blockGraffiti" to quickly check that my graffiti was set properly. The command starts, but stalls for ~10 seconds. I then get the following error: 

5:25:45 PM - Found 0 errors. Watching for file changes.
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run config:get blockGraffiti
Error: connect ETIMEDOUT \\.\pipe\C:\Users\ruthg\.ironfish\ironfish.ipc
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

This happens every time I run this command. However, if I check my config file, it shows "blockGraffiti": "davistreybig" in the JSON. 

While some CLI commands are working no problem - e.g. "yarn start config" works properly - many others are showing the same problem. For example, "yarn start miners:mined" has the same timeout issue, as well as "yarn start workers:status"

Details on my version and the status of my node can be seen below. Not sure what is happening: 

VERSION - ironfish-cli/0.0.0 win32-x64 node-v16.13.1
Status Console
Version              0.1.10 @ src
Node                 STARTED
P2P Network          CONNECTED - In: 52 KB/s, Out: 302 KB/s, peers 50
Mining               STARTED - 1 miners, 2 mined
Mem Pool             6 tx
Syncer               IDLE @ 0.12 blocks per seconds | avg time to add block 511.69 ms
Blockchain           SYNCED @ HEAD 000000000fa0b4a1853d219d4a9d65e5c732cedfdd25f04edb36ef2aada38c57 (22273)
Workers              STARTED - 0 -> 0 / 31 - 0 jobs Δ, 2 jobs/s

My blockgraffiti is "davistreybig"

**Comment by deekerno** [comment]
Does this issue still persist after the latest update?

**Comment by DavisTrey** [comment]
Not happening anymore
