### ISSUE TITLE
Node_start_failed. Did not see this error before today.

### ISSUE THREAD

**Issue by suzumiya2014** [iron-fish/ironfish#76]
![node_start_failed](https://user-images.githubusercontent.com/24888155/115119055-1856e680-9fd9-11eb-9912-db3fce1ce812.png)

**Comment by suzumiya2014** [comment]
Did not see this error before today.
I think this is a common problem, my environment is gcp vps: ubuntu20.04 lts, from source.
I have done update,there's still the same error.

**Comment by nickon** [comment]
Have the same error

**Comment by dguenther** [comment]
This should be fixed by #77, which is in master now. The error will still log, but it should no longer cause a crash.
