### ISSUE TITLE
Problem with mined block command

### ISSUE THREAD

**Issue by Mayovka** [iron-fish/ironfish#762]
found such a bug when executing a command to check block
![Inkedphoto_2021-12-15_20-36-06_LI](https://user-images.githubusercontent.com/95088734/146245676-c9978a3d-9a3a-4a12-8598-cc760b01047c.jpg)
Resolved issues: Reuse command

**Comment by leanthebean** [comment]
Closing as it's resolved.  
In the future please help us debug such issues by providing hashes in text format.
