### ISSUE TITLE
Could you use the rimraf package to do this instead, so we can make the postpack script OS-agnostic as well? It should take adding rimraf as a devDependency here, then re-running yarn install in the root directory to update

### ISSUE THREAD

**Issue by chenghua0322** [iron-fish/ironfish#768]

**Comment by chenghua0322** [comment]
yy

**Comment by CumpsD** [comment]
This is a mistake PR I think?

You copied a comment from https://github.com/iron-fish/ironfish/pull/575

**Comment by dguenther** [comment]
Closing this as it looks like an accident. If there was supposed to be an issue description here, please open a new issue with steps to reproduce the problem.
