### ISSUE TITLE
the 0.1.11 node are always not synced and syncer is idle

### ISSUE THREAD

**Issue by shandongdacongge** [iron-fish/ironfish#770]
hello, man:
look an this .
it's always this almost 6 hours.
this node is a new create node,  run with the docker,  but it can't finished the sync any time.
but the syncer is idel, but the bolckchain is not synced,   the block heigh is same with the web explore.

![image](https://user-images.githubusercontent.com/64308935/146365597-0b8480b2-7565-41f1-a97e-184b11644c30.png)

**Comment by deekerno** [comment]
This was due to a change in `MAX_SYNCED_AGE`, which has since been adjusted to a more reasonable value.
