### ISSUE TITLE
The transaction does not go through. Previously, such problems did not occur.

### ISSUE THREAD

**Issue by Vesperin7** [iron-fish/ironfish#772]
![ironfishBag2](https://user-images.githubusercontent.com/95927742/146404035-d4c1ed70-ccda-494c-9c69-cb570d4f5f16.png)
Graffiti: Rarity123
E-mail: willnevidson@gmail.com

**Comment by Vesperin7** [comment]
![ironfishBag3](https://user-images.githubusercontent.com/95927742/146404794-c490daa0-c50d-4aac-9cc1-261a1a669db6.png)

**Comment by deekerno** [comment]
What was your balance prior to starting the second transaction? Additionally, after the first successful transaction, how soon after did you try again?

**Comment by Vesperin7** [comment]
Balance : 59,999200
I tried to send again after half an hour. Did not work. Everything works
again today

чт, 16 дек. 2021 г., 22:39 Alexander Decurnou ***@***.***>:

**Comment by deekerno** [comment]
Seems that this is resolved. If this problem reappears, feel free to let us know.
