### ISSUE TITLE
redundant line breaks in the log of invalid blocks

### ISSUE THREAD

**Issue by shandongdacongge** [iron-fish/ironfish#776]
There are redundant line breaks in the log of invalid blocks, affecting readability, as shown in the following figure

The source code is https://github.com/iron-fish/ironfish/blob/73a192a784e60bcaa7f0ff284cfa355e1572a081/ironfish/src/syncer.ts#L459

![1639721894(1)](https://user-images.githubusercontent.com/64308935/146498490-8f9392cd-36d8-45f2-a318-87445963a7f2.png)

**Comment by deekerno** [comment]
Fixed as a result of #777 and went live as a part of #803.
