### ISSUE TITLE
Blocks mined but do not appear on the leaderboard and block explorer

### ISSUE THREAD

**Issue by JDCRMartins** [iron-fish/ironfish#778]
Hi,
I've successfully mined these blocks but the ones that are underlined don't appear on the leaderboard and if you look in the block explorer, another graffiti appears. 
My graffiti is jdcrmartins.

![image](https://user-images.githubusercontent.com/86152006/146523846-56bc5ce8-a923-42eb-975f-faf0f8533583.png)

**Comment by lwisne** [comment]
We think this is fixed now. Closing. Let me know if you believe otherwise.
