### ISSUE TITLE
core dumped

### ISSUE THREAD

**Issue by snappyJack** [iron-fish/ironfish#779]
<--- Last few GCs --->

[7:0x56f6030] 421864208 ms: Mark-sweep 1985.2 (2091.2) -> 1969.2 (2090.7) MB, 3056.6 / 7.5 ms  (average mu = 0.085, current mu = 0.006) allocation failure scavenge might not succeed
[7:0x56f6030] 421868731 ms: Mark-sweep 1985.0 (2090.7) -> 1969.2 (2090.9) MB, 2765.3 / 7.5 ms  (average mu = 0.261, current mu = 0.389) allocation failure scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb02ec0 node::Abort() [node]
 2: 0xa181fb node::FatalError(char const*, char const*) [node]
 3: 0xced88e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xcedc07 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xea5ea5  [node]
 6: 0xea6986  [node]
 7: 0xeb48be  [node]
 8: 0xeb5300 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xeb827e v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
10: 0xe796aa v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
11: 0x11f2e86 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
12: 0x15e7879  [node]
Aborted (core dumped)

**Comment by lwisne** [comment]
We think this is fixed now. Closing. Let me know if you believe otherwise.
