### ISSUE TITLE
Submitted blocks don't apear

### ISSUE THREAD

**Issue by idanshahar** [iron-fish/ironfish#795]
![image](https://user-images.githubusercontent.com/10245593/146730694-631ba138-577e-4aa6-991c-a0f92c0ed95f.png)
![image](https://user-images.githubusercontent.com/10245593/146730812-51298dac-dc9a-4241-89e4-c4484369f60b.png)

The account is configured with my right graffiti.
Also tried running ironfish miners:mined, but nothing changed.
I use MacOS BigSure
Ironfish version output is:
name       ironfish
version    0.1.12
git        1971e64
runtime    node/16.13.1

**Comment by deekerno** [comment]
When you successfully mine a block on your node, it does not necessarily mean that it will be included on the main chain. You and every other miner on the network are competing to mine the same block, and thus it is entirely possible that another miner submitted their block to the network just moments before yours.
