### ISSUE TITLE
Waiting for director to send work 0H/s in win10 docker

### ISSUE THREAD

**Issue by lutianxiong** [iron-fish/ironfish#800]
![微信截图_20211221140419](https://user-images.githubusercontent.com/42662202/146879839-43009ba0-e5b6-4ec4-8bc2-d0a7ed0a1c46.png)
![微信截图_20211221140434](https://user-images.githubusercontent.com/42662202/146879841-f4aa3508-4757-419a-b74c-e9e587cdfa39.png)

**Comment by deekerno** [comment]
Your chain was not fully synced (read the 'Blockchain' line in the second picture); your chain needs to be in a synced state for the miner to start the mining process.

**Comment by lutianxiong** [comment]
> Your chain was not fully synced (read the 'Blockchain' line in the second picture); your chain needs to be in a synced state for the miner to start the mining process.

Does blockchain synchronization start automatically? Until now, it was still NOT SYNCED.
