### ISSUE TITLE
Bug in mining blocks after increased thread

### ISSUE THREAD

**Issue by realisophie** [iron-fish/ironfish#807]
I was working on Mac homebrew. Hash was slow on 1 thread so increased thread count for mining, which increased hash rate, but then the "mining block number" doesn't change at all, but my hash rate keeps running. This has been the same for more than 12 hrs, and I still haven't mined a block, is this a bug? Started new command to mine, and it's stuck for ages at "waiting for director to send work. My testnet act name = ironfishfan

<img width="431" alt="1" src="https://user-images.githubusercontent.com/7575414/147009208-459c7327-61a0-4b1b-a041-2ebd52a99584.png">
<img width="361" alt="2" src="https://user-images.githubusercontent.com/7575414/147009252-dbc106c8-08c9-4946-ab7a-4011794fd6af.png">

**Comment by mat-if** [comment]
Going to close as I believe this is fixed, we've since re-written all of the mining code
