### ISSUE TITLE
yarn setup

### ISSUE THREAD

**Issue by VAAADIM123** [iron-fish/ironfish#826]
`Error: Cannot find module 'C:\Users\╨Р╨┤╨╝╨╕╨╜╨╕╤Б╤В╤А╨░╤В╨╛╤А\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
error Command failed with exit code 1.`
got this problem while installing iron-fish. npm and yarn were installed without troubles, but still missing some module

**Comment by deekerno** [comment]
Were you able to successfully install the node? If not, at which step in the installation instructions did you encounter this error?

**Comment by VAAADIM123** [comment]
I install it allready.
Trouble was with russian symbols in path to node
