### ISSUE TITLE
miners:mined miner [sic] formatting issues

### ISSUE THREAD

**Issue by AmberKiso** [iron-fish/ironfish#830]
IronFish Version       0.1.15
Running Docker 4.3.1, using their CLI
Windows 10 Home

Noticed a few minor formatting issues with the ironfish miners:mined command:
(Head node is roughly at 37838.)

> `# ironfish miners:mined -1000 1000`
Scanning for mined blocks...
Scanning for mined blocks from 36840 -> 36840
Scanning blocks: [----------------------------------------] 0/1 0% | ETA: {estimate} | SEQ {sequence}#

I'd expect the minimum start node to be at 0 (or 1 on how things are indexed), not negative.
The variables are not valid for estimate nor sequence.
This command also doesn't send a newline, so the # prompt is lost with the command output

> `# ironfish miners:mined 0 0`
Scanning for mined blocks...
Scanning for mined blocks from 1 -> 37885
Scanning blocks: [----------------------------------------] 61/37885 0% | ETA: N/A | SEQ 62

Double zero parameters = whole chain. Probably not what was intended.

> `# ironfish miners:mined -1000 -10000`
Scanning for mined blocks...
Scanning for mined blocks from 36875 -> 36875
Scanning blocks: [----------------------------------------] 0/1 0% | ETA: {estimate} | SEQ {sequence}#

> `# ironfish miners:mined -10000 -1000`
Scanning for mined blocks...
Scanning for mined blocks from 27876 -> 36876
Scanning blocks: [========================================] 8997/9001 99% | ETA: soon | SEQ 36873#

Testing negative numbers. Definitely an unexpected block range with the second example. Better to just refuse negative numbers.

> `# ironfish miners:mined 37000 99999999999`
Scanning for mined blocks...
Scanning for mined blocks from 37000 -> 37840
Scanning blocks: [========================================] 832/841 98% | ETA: soon | SEQ 37832#

>`# ironfish miners:mined 37840 37840`
Scanning for mined blocks...
Scanning for mined blocks from 37840 -> 37840
Scanning blocks: [----------------------------------------] 0/1 0% | ETA: {estimate} | SEQ {sequence}#

> `# ironfish miners:mined 37839 37840`
Scanning for mined blocks...
Scanning for mined blocks from 37839 -> 37840
Scanning blocks: [----------------------------------------] 0/2 0% | ETA: {estimate} | SEQ {sequence}#

> `# ironfish miners:mined 37800 37840`
Scanning for mined blocks...
Scanning for mined blocks from 37800 -> 37840
Scanning blocks: [=================================-------] 34/41 82% | ETA: N/A | SEQ 37034#

> `# ironfish miners:mined 1900 1909`
Scanning for mined blocks...
Scanning for mined blocks from 1900 -> 1909
Scanning blocks: [================================--------] 8/10 80% | ETA: N/A | SEQ 1908#

Couple examples of the command completing but the progress bar does not quite hit 100%.
It looks like (on my machine) the minimum number of blocks is 10 to have the sequence number update.

> `# ironfish miners:mined 2021 2021.00000000001`
Scanning for mined blocks...
Scanning for mined blocks from 2021 -> 2021.00000000001
Scanning blocks: [----------------------------------------] 0/1.0000000000100044 0% | ETA: {estimate} | SEQ {sequence}#

> `# ironfish miners:mined 2021 3021.1234`
Scanning for mined blocks...
Scanning for mined blocks from 2021 -> 3021.1234
Scanning blocks: [========================================] 993/1001.1234 99% | ETA: soon | SEQ 3014#

Fractions should be truncated.

**Comment by AmberKiso** [comment]
Looks like the "not quite 100%" error type was reported in #748 and will be fixed with #994.

**Comment by AmberKiso** [comment]
There is some input sanitizing now performed on start and stop, so most cases he have been taken care of by that and #994.
Fraction are the only remaining bug case. Discovered #1034 while testing a fix.

**Comment by NullSoldier** [comment]
Ok, so I think there is some misunderstanding. As a standard, where we accept sequence, we accept a negative number which then acts as a number from the head. So -100 is with a head of 35600 would be block 35500. We accept these  negative numbers anywhere sequence is accepted. That is why you are getting these unexpected numbers. I think from that regard, maybe this functionality should just be documented in the command better.
