### ISSUE TITLE
CLI help = odd behaviors, hang

### ISSUE THREAD

**Issue by AmberKiso** [iron-fish/ironfish#831]
IronFish Version 0.1.15
Running Docker 4.3.1, using their CLI
Windows 10 Home

Some sub commands will display verbose help while others will run with a default (unknown) set of parameters:

> `# ironfish miners:start help`

Start a miner and subscribe to new blocks for the node

USAGE
  $ ironfish miners:start

OPTIONS
  -t, --threads=threads        [default: 1] number of CPU threads to use for mining. -1 will auto-detect based on number
                               of CPU cores.

(Snip)

> `# ironfish miners:mined help`
Scanning for mined blocks...
Scanning for mined blocks from 1 -> 37906
Scanning blocks: [==--------------------------------------] 2177/37906 5% | ETA: 3m 3s | SEQ 2178^C

The latter command was definitely unexpected.

> `#  ironfish chain:show help`
Getting the chain blocks...
^C

Seems to hang. I gave up after waiting ~30 seconds.

Since `--help` seems to be safer, should we depreciate `help` and enforce `--help`?

**Comment by deekerno** [comment]
Does this issue still persist after the latest update?

**Comment by AmberKiso** [comment]
Ran 0.1.21 on a Windows command prompt:

`yarn start miners:mined help` will still scan the entire chain

`yarn start chain:show help` will eventually dump the entire chain
Other commands like `yarn start chain 300`  `yarn start chain:show 93990 94000` work as well.

This might need a documentation change to add [start] and [stop] parameters and a warning about the length of time it takes to dump ~95k blocks.
