### ISSUE TITLE
Condition 'reason' is always false at this point 

### ISSUE THREAD

**Issue by knight2008** [iron-fish/ironfish#834]
Condition 'reason' is always false at this point because the false branch of the condition 'reason' at line 453 has been taken.

ironfish/src/syncer.ts (453-469) 

> 
if (reason) {
      Assert.isNotNull(score)
 
      this.logger.warn(
        `Peer ${
          peer.displayName
        } sent an invalid block. score: ${score}, hash: ${HashUtils.renderHash(
          block.header.hash,
        )} (${Number(block.header.sequence)}), reason: ${reason}`,
      )
 
      peer.punish(score, reason)
      return { added: false, block, reason }
    }
 
    Assert.isTrue(isAdded)
    return { added: true, block, reason: reason || null }
  }

![20211226155527](https://user-images.githubusercontent.com/28775897/147402320-3b06bcee-bf63-4c7f-b7b4-5f1a5da5af00.png)

**Comment by knight2008** [comment]
![Uploading 20211226155527.png…]()

**Comment by lwisne** [comment]
We think this is fixed now. Closing. Let me know if you believe otherwise.
