### ISSUE TITLE
Backward Compatibility for database after version upgrade

### ISSUE THREAD

**Issue by idanshahar** [iron-fish/ironfish#835]
Version update requires wiping the database.
It will be great to add backward compatibility :)

**Comment by hygkui** [comment]
after reset or remove .ironfish, i cannot find the balance, have you meet the same problem?

**Comment by ozzyjon** [comment]
> after reset or remove .ironfish, i cannot find the balance, have you meet the same problem?

@hygkui I have the same issue and created this bug: https://github.com/iron-fish/ironfish/issues/853

**Comment by lwisne** [comment]
We believe this is now closed. Let us know if you don't agree!
