### ISSUE TITLE
Miner crashing with error "malloc_consolidate(): invalid chunk size"

### ISSUE THREAD

**Issue by gjfrn** [iron-fish/ironfish#842]
Miner is crashing with the below reported via journalctl. This is running on a Ryzen 3700X.

Mining block 44498 on request 22686... 2530503 H/s
malloc_consolidate(): invalid chunk size
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by gjfrn** [comment]
Third time today so far:
Mining block 44532 on request 25... 2469121 H/s
malloc_consolidate(): invalid chunk size
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by lwisne** [comment]
We think this is fixed now. Closing. Let me know if you believe otherwise.
