### ISSUE TITLE
Security concerns: Exporting accounts via rpc.tcp

### ISSUE THREAD

**Issue by FireNirva** [iron-fish/ironfish#844]
I was reading the source code and debugging the CLI has raised some flags.

The node machine that open rpc.tcp can easily export account and change graffiti remotely. If the RPC port forwards over the internet, the node machine's account will be exposed.

### **Steps to Reproduce:**

1. Run the Iron Fish CLI
2. Ironfish accounts:export default ~/ --rpc.tcp --rpc.tcp.host=Ip.Address --rcp.tcp.port=Port
3. The default accounts will be exported to the root directory of the local machine.

Except for config:show and config:edit commands are only working on the local machine, many other commands which have *RemoteFlags* in the source code can run remotely.

Adding token authentication may solve this problem, but some accounts have already been exposed. 

### **Additional Information**

* Operating System: Linux
* Ironfish Version: v0.1.15

**Comment by lwisne** [comment]
Think this is still true. Worth checking back into.

**Comment by danield9tqh** [comment]
@FireNirva thanks for the report. Combing through unclosed issue so sorry for the late reply. We've [enabled TLS by default](https://github.com/iron-fish/ironfish/pull/1575) and added [Authentication turned on by default](https://github.com/iron-fish/ironfish/pull/2224) on all nodes. So I think this issue has been solved
