### ISSUE TITLE
Hashrate with 16 and 31 threads are the same

### ISSUE THREAD

**Issue by CrazySerGo** [iron-fish/ironfish#849]
Ironfish miner shows similar hashrate ~3.6kk if I run it with 16 or 31 threads on the same server with 5950x processor.

**Comment by CrazySerGo** [comment]
![image](https://user-images.githubusercontent.com/11334923/147991799-9afd590c-e2d5-46b3-a55f-ff9b37ebde7e.png)
![image](https://user-images.githubusercontent.com/11334923/147991882-2da44d1c-2918-4437-94ad-4a3cc3139228.png)

**Comment by deekerno** [comment]
Does this issue still persist after the latest update?

**Comment by CrazySerGo** [comment]
Yes, it's still present. Below screenshots for node that started with 21 vs 31 threads on similar servers(5950x) 
![image](https://user-images.githubusercontent.com/11334923/149232532-b5a86633-6ecf-4851-a1b8-337fe1e39c43.png)
![image](https://user-images.githubusercontent.com/11334923/149232659-c6e34404-7bb4-416f-b69f-044bab766d2b.png)

**Comment by AmberKiso** [comment]
To confirm, your command line used was `yarn start miners:start -t -16` (or -t 31)?

It might be worth a look at this comment thread in the Discord server: https://discord.com/channels/771503434028941353/828803908067262484/948444206861541386 (#mining)
People mining seriously have experimented with the batch size parameter to get better performance out of their rigs.
Try `yarn start:once config:set minerBatchSize 50000` and experiment with that value to see what hash rate you can generate.
You can use `yarn start:once config:show` to see what the current value of the minerBatchSize parameter is.
