### ISSUE TITLE
Random characters appear sporadically while updating blocks

### ISSUE THREAD

**Issue by pushprajj** [iron-fish/ironfish#852]
Hi Team,

I ran the following command for installing Iron Fish:
docker run --rm --tty --interactive --network host --volume <home-directory>/.ironfish:/root/.ironfish ghcr.io/iron-fish/ironfish:latest

While updating the blocks, there were patches of random characters appearing in between. May not be a major issue, but I thought I would report it anyway.

![Screenshot 2022-01-05 181022 - random characters](https://user-images.githubusercontent.com/35641260/148177837-59e9a981-93a7-475d-89c1-92927c6c3315.png)

Regards,
Pushpraj

**Comment by deekerno** [comment]
What OS and terminal software are you using?

**Comment by pushprajj** [comment]
Windows and Poweshell.

**Comment by lwisne** [comment]
Does this still happen in Powershell?
