### ISSUE TITLE
Account balance is zero after 'ironfish reset'.

### ISSUE THREAD

**Issue by ozzyjon** [iron-fish/ironfish#853]
Steps to reproduce.

1. perform a `git pull` to get latest code - I'm now on version v0.1.15 
2. run up the node `yarn start start` and receive the message :
`Error: You are running a newer version of ironfish on an older database.
Wipe your database using "ironfish reset" or delete your data directory at ~/.ironfish`
3. perform the database reset `yarn start reset`
4. run up the node again, it now runs
5. import my old account named myaccount `yarn start accounts:import`
6. now perform an account balance `yarn start accounts:balance myaccount` and **my balance is zero**.

I do not know how to retrieve all my iron that I have previously mined.

Furthermore I have tried `accounts:rescan` which has not helped.

**Comment by ozzyjon** [comment]
Similar to https://github.com/iron-fish/ironfish/issues/683

**Comment by wd021** [comment]
Can't seem to replicate on latest version. @ozzyjon can you verify? make sure the `accounts:import` and `accounts:balance` names are consistent. I added account name's to the display of accounts:balance in https://github.com/iron-fish/ironfish/pull/1089, which should make it clearer in the future.

**Comment by ozzyjon** [comment]
I have: 

1. git pulled and I'm now on v1.22.17 running on Windows.
2. run 'npm update' and 'yarn install',
3. navigated to the ironfish-cli director and started the node (yarn start start).
4. verified I'm using the correct account by using 'yarn start accounts:which'
5. performed another 'yarn start accounts:rescan'.

My account balance still shows none of my previously mined ironfish.  It only shows the 15 ore donated by the faucet.

**Comment by lwisne** [comment]
Were you ever able to recover these tokens?

**Comment by hughy** [comment]
Closing this issue because we've made significant changes to the wallet since 7/22/22 and haven't received a response on this issue
