### ISSUE TITLE
windows docker run error

### ISSUE THREAD

**Issue by tsonghua** [iron-fish/ironfish#857]
stopping sync from e6Jxx (vary_glad) due to Error: Connection closed while waiting for request GetBlocks: 1026
at..
...

<img width="1585" alt="windows_docker_ironfish_error202201080910" src="https://user-images.githubusercontent.com/3368177/148626367-68e9eed6-b494-41ff-a2e4-0e2c32bb8580.png">

**Comment by deekerno** [comment]
This is not an error with Docker nor Windows; this error appears when a connection is closed during a request for blocks. We've done some work to improve this in recent versions, so it should be less frequent. If you continue to see this a lot, feel free to re-open the issue.
