### ISSUE TITLE
'yarn test' failing in windows command prompt

### ISSUE THREAD

**Issue by AmberKiso** [iron-fish/ironfish#861]
IronFish Version 0.1.15
Windows 10 Home

Copied from the discord chat to claim some points since I'm not going to be able compete in the mining arena on a consumer laptop. ;)
https://discord.com/channels/771503434028941353/828767731305676810/929192909469810688

> I'm getting the following error message when I've run 'yarn test' in a windows command prompt:
> FAIL ironfish src/workerPool/pool.test.ts (7.581 s)
>   ● Worker Pool › executes in worker
> 
>     Cannot find module 'C:\Users\mjolnir\Documents\GitHub\ironfish\ironfish\src\workerPool\worker.js'
> 
> Did I mis-install something? GitHub doesn't have that file in the workerPool directory...

Appears to be fixed with commit 859, but ironfish-cli tests then fail.

**Comment by deekerno** [comment]
Thanks for letting us know! This issue is eligible for testnet credit, if you like!
