### ISSUE TITLE
Command yarn test:slow not found

### ISSUE THREAD

**Issue by AmberKiso** [iron-fish/ironfish#863]
IronFish Version 0.1.15
Windows 10 Home
Fetched pull request 859 to fix bug 861.

`yarn test:slow` from the root, per the "Running Test" 1ii instructions in the Readme returns:

> 
> yarn run v1.22.17
> error Command "test:slow" not found.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> 
> C:\Users\mjolnir\Documents\GitHub\ironfish>

`yarn test` and `yarn test:coverage` run with the prior reported ironfish-cli issues.

**Comment by AmberKiso** [comment]
Reverted my local repo back to master and same failure occurs.

**Comment by deekerno** [comment]
Our documentation was wrong, so thanks for catching this! This issue is eligible for testnet credit, if you like!

**Comment by AmberKiso** [comment]
Fixed by #1052
