### ISSUE TITLE
yarn test:watch failing. Missing git/hg?

### ISSUE THREAD

**Issue by AmberKiso** [iron-fish/ironfish#864]
IronFish Version 0.1.15
Windows 10 Home
Current branch is master.

Not sure if this should return an error if there's no changes...

`yarn test:watch` from the root, per the "Running Test" 2ii instructions in the Readme returns:

> 
> yarn run v1.22.17
> $ tsc -b tsconfig.test.json && jest --watch --coverage false
> Determining test suites to run...
> --watch is not supported without git/hg, please use --watchAll
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Same output if I run with the 859 pull request.

**Comment by deekerno** [comment]
Our documentation was wrong, so thanks for catching this! This issue is eligible for testnet credit, if you like!

**Comment by AmberKiso** [comment]
Claimed for all 3. Thank you!

**Comment by AmberKiso** [comment]
Fixed by #1052
