### ISSUE TITLE
ironfish-master in windows still fail 1 test

### ISSUE THREAD

**Issue by QustomQure** [iron-fish/ironfish#875]
Summary of all failing tests
FAIL src/utils/currency.test.ts (5.482 s)
  ● Currency utils › displayIronAmountWithCurrency returns the right string

    expect(received).toEqual(expected) // deep equality

    Expected: "$IRON 0.00000002 ($ORE 2)"
    Received: "$IRON 0,00000002 ($ORE 2)"

       6 | describe('Currency utils', () => {
       7 |   test('displayIronAmountWithCurrency returns the right string', () => {
    >  8 |     expect(displayIronAmountWithCurrency(0.00000002, true)).toEqual('$IRON 0.00000002 ($ORE 2)')
         |                                                             ^
       9 |     expect(displayIronAmountWithCurrency(0.0000001, true)).toEqual('$IRON 0.00000010 ($ORE 10)')
      10 |     expect(displayIronAmountWithCurrency(0, true)).toEqual('$IRON 0.00000000 ($ORE 0)')
      11 |     expect(displayIronAmountWithCurrency(1, true)).toEqual(

      at Object.<anonymous> (src/utils/currency.test.ts:8:61)

**Comment by QustomQure** [comment]
Graffiti Qualia

**Comment by NullSoldier** [comment]
This is an interesting bug because it's related to localization and not windows. You can reproduce this on any platform by changing your local to any language that uses commas for number delimters. We should fix this, but is also an easy bug for someone to get PR credit for.

**Comment by wd021** [comment]
just submitted PR for this - https://github.com/iron-fish/ironfish/pull/974
