### ISSUE TITLE
Mining Ironfish

### ISSUE THREAD

**Issue by goodthebest** [iron-fish/ironfish#878]
Does Ironfish provide built-in stratum mining feature or any third-party mining stratum available to setup a mining pool?

**Comment by AmberKiso** [comment]
Hi,

Not at the moment.

From the Ironfish documentation: https://ironfish.network/docs/onboarding/miner-iron-fish#join-a-mining-pool
> $IRON is not available on a mining pool at the moment. Join our Discord if you're interested in creating a pool for Iron Fish.

Also, I would recommend joining the Discord channel and asking in the #questions channel for any future questions - you'll get a much faster response from the Devs there.

**Comment by AmberKiso** [comment]
Recent update from Iron Fish discord: https://discord.com/channels/771503434028941353/828803908067262484/944217439326076938
There is a 3rd party pool available.

Will close this as information has been provided.
