### ISSUE TITLE
Incorrect graffity in Leaderboard

### ISSUE THREAD

**Issue by m4steel** [iron-fish/ironfish#884]
Node shows me that there were mined 2 blocks - 63049 and 63058, but in leaderboard these blocks are mined by another miner. Who is wrong - me or leaderboard?

<img width="645" alt="qweqwe" src="https://user-images.githubusercontent.com/91045460/149075843-219fe37f-602b-4183-93b4-052a73c039e1.png">
<img width="845" alt="qwe1" src="https://user-images.githubusercontent.com/91045460/149075850-16a55dac-4f54-4624-bf2d-6959f465a2e8.png">
<img width="842" alt="qwe2" src="https://user-images.githubusercontent.com/91045460/149075853-88507c6e-4334-4dd2-8cfb-393c5aa1ebdc.png">

**Comment by deekerno** [comment]
Can you share more information about what system you're running Iron Fish on? Also, can you run `miners:mined` again and share the output here?

**Comment by m4steel** [comment]
That was bug on 0.1.16, before updating on 0.1.18. After update my mined blocks dissapeared

**Comment by lwisne** [comment]
Were you ever able to resolve the blocks disappearing?
