### ISSUE TITLE
#bug log shows disconnected from ironfish net and cannot restart node

### ISSUE THREAD

**Issue by tsonghua** [iron-fish/ironfish#885]
I don't know why it shows "Connected to the Iron fish network, Not Connected to the Ironfish network"

ironfish stop

ironfish start  it shows "another node is using this database..."

what could I do now?

![not_connected](https://user-images.githubusercontent.com/3368177/149080401-3abec977-e182-4356-bc37-834fd15c0c00.jpeg)

**Comment by deekerno** [comment]
Your node is several versions behind and needs to update to the latest version to continue interacting with the network. Please pull the latest Docker image for Iron Fish.
