### ISSUE TITLE
Mining to RPC server results in significantly reduced hashrate for slave nodes.

### ISSUE THREAD

**Issue by franzibb** [iron-fish/ironfish#896]
Using three slave nodes and a master node in RPC mode on a LAN, hashrates on some slave nodes were significantly reduced. For example, a node with a Ryzen 5950x mined work sent from the RPC master node at about 2.5m/h. After converting the 5950x node to sync its own blockchain and assign work to itself, the hashrate jumped to 3.6 m/H without making any other changes.

**Comment by QustomQure** [comment]
Maybe for some reason your workers count in your node didn't enough for all miners. Or something limits your lan exchange speed. Try start node with more workers count 
--workers=xx

**Comment by deekerno** [comment]
Does this issue still persist after the latest update?
