### ISSUE TITLE
Error yarn install

### ISSUE THREAD

**Issue by xoptov** [iron-fish/ironfish#90]
Hello!
I have a strange issue when I try to install Ironfish from the source. It looks like errors in dependencies:

![image](https://user-images.githubusercontent.com/2604833/115781234-c809cb00-a3c2-11eb-8f79-27819b5f6e66.png)

My environment:
OS FreeBSD 13.0
nodejs v14.16.1
rustc 1.51.0
yarn 1.22.10
wasm-pack 0.9.1

Help me please to resolve this issue! :-)

**Comment by dguenther** [comment]
I've seen that before, that indicates it's trying to build the Wasm code with a newer version of Rust than is expected. There's a `rust_toolchain` file in the root of the repository that should be telling Cargo to use `1.48.0` -- Could there be any reason that FreeBSD might not read that file?

**Comment by NullSoldier** [comment]
Commentor has not responded, closing. Overall it looks like you are using Rust 1.51, but we depend on Rust 1.48. Try downgrading to see if it fixes and re-open the issue, or comment here if it persists.
