### ISSUE TITLE
Silent accounts export. Different wording.

### ISSUE THREAD

**Issue by QustomQure** [iron-fish/ironfish#900]
### Description

After accounts exporting just writes nothing. It would be much better if atleast getting message: Successfully done or something like that.

There is command accounts:publickey which do what it suppose to do. But when you export account publickey is named "publicAddress" there. Stylistically should be one or another to prevent misconceptions

graffiti Qualia

**Comment by AmberKiso** [comment]
Hi,
On 0.1.24 I get:

> C:\Users\mjolnir\Documents\GitHub\ironfish\ironfish-cli>yarn start:once accounts:export
> yarn run v1.22.17
> $ yarn build && yarn start:js accounts:export
> $ tsc -b
> $ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run accounts:export
> {
>    "name": "Name here",
>    "spendingKey": "numbers here",
>    "incomingViewKey": "numbers here",
>    "outgoingViewKey": "numbers here",
>    "publicAddress": "numbers here",
>    "rescan": null
> }
> Done in 2.17s.
> 
> C:\Users\mjolnir\Documents\GitHub\ironfish\ironfish-cli>

What command did you run and was there an error printed?
When you said "nothing written" do you mean there was no output file written in the directory you specified?

**Comment by lwisne** [comment]
We think this is fixed now. Closing. Let me know if you believe otherwise.
