### ISSUE TITLE
Node did not starting after restart - Node: STOPPED 

### ISSUE THREAD

**Issue by aleksfoHub** [iron-fish/ironfish#903]
### What happened?

A bug happened!

Graffiti: Airfree

After checking status with command
 ironfish status -f have  message- Node: STOPPED 
This command doesn't help - 
systemctl restart ironfishd ironfishd-miner

### Version

v0.0.19

### Relevant log output

```shell
Node: STOPPED
```

**Comment by leanthebean** [comment]
Could you provide more details here? Why does that command not help? And are you still seeing this issue currently on later updates?

**Comment by leanthebean** [comment]
`systemctl restart ironfishd ironfishd-miner` 
Looks like you're using an unofficial script. Closing this for now.
