### ISSUE TITLE
Can I use 2 computers for 1 node (1 graffiti)

### ISSUE THREAD

**Issue by linhphambqn** [iron-fish/ironfish#909]
### Description

Hey Iron Fish Team, Can I use two computers ( two miners) for one node (one graffiti)? How can I set up? And will this more efficient?

**Comment by QustomQure** [comment]
You actually should be banned for spamming this

**Comment by linhphambqn** [comment]
> 
Thank you for observing me 👍 , I posted this topic before receiving an answer in discord.

**Comment by jrwashburn** [comment]
> > 
> 
> Thank you for observing me 👍 , I posted this topic before receiving an answer in discord.

Maybe update the comments here for others in the future, and close since it's not an issue?

**Comment by deekerno** [comment]
Yes, you can do this. To ensure that your nodes are properly set up, you should upgrade to the newest version (v0.1.21 at the time of this comment) and run `ironfish testnet` to automatically configure your node settings.
