### ISSUE TITLE
v0.1.20 crash while mining 

### ISSUE THREAD

**Issue by tsonghua** [iron-fish/ironfish#928]
### Description

v 0.1.20
crash while mining

![image](https://user-images.githubusercontent.com/3368177/150718425-8f415992-1632-4b28-937b-a3005278dff2.png)

**Comment by Kupuyc** [comment]
You may try to extend memory limit. Change [this line](https://github.com/iron-fish/ironfish/blob/master/ironfish-cli/package.json#L31) to next:
`"start:js": "cross-env NODE_OPTIONS=--max_old_space_size=8192 OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run",`

By default limit ~4 Gb but we set it to 8Gb. It may help.

P.S. Don't forget to restart the miners.

**Comment by jrwashburn** [comment]
All my v 0.1.21 miners also crashed with this overnight. Haven't seen it before; will extend limit, but is this hiding a leak?

**Comment by Kupuyc** [comment]
It does. This issue pretty rare and extending of memory limit had chance to solve it. But looks like, unfortunately, it doesn't work. Could you specify your nodejs version?

**Comment by jrwashburn** [comment]
> It does. This issue pretty rare and extending of memory limit had chance to solve it. But looks like, unfortunately, it doesn't work. Could you specify your nodejs version?

v16.13.2

**Comment by deekerno** [comment]
Does this issue still persist after the latest update?

**Comment by jrwashburn** [comment]
Due to #1008 I'm not able to run, so I cannot confirm.

**Comment by lwisne** [comment]
Are you still having issues here?

**Comment by jrwashburn** [comment]
> 

I am not; however, I haven't run miners since 0.1.37. Not sure for OP.

**Comment by lwisne** [comment]
Thanks for the feedback - closing due to age of the issue + being tied to a very old version.
