### ISSUE TITLE
Completed mining 1 block but the point in leaderboard is not increased.

### ISSUE THREAD

**Issue by mrkevinht** [iron-fish/ironfish#935]
### What happened?

A bug happened!
I finished mining 1 block. I checked in the block explorer it's under my graffiti also. But my point in leader board is not increased.
https://explorer.ironfish.network/blocks/0000000000062a090ace21a354afbfc55a475c0e9ea9257eeb85eeabd736631c

Link to leader board: https://testnet.ironfish.network/users/17392

I believe this is a bug. Please help to review. 

### Version

0.1.20

**Comment by AmberKiso** [comment]
Hi,
The latest timestamp of the credited block in the leaderboard is 1/25/2022, 10:27:52 AM.
This matches the timestamp for the block in the block explorer.

So it looks like your account was credited.

**Comment by NullSoldier** [comment]
I spoke with this user in discord.  We'll close it for now and give this user credit for being responsive in attempting to find out if there is a bug.
