### ISSUE TITLE
Jobs in Status screen doesn't display correctly for multiple miners sharing one node

### ISSUE THREAD

**Issue by McGillDad** [iron-fish/ironfish#939]
### What happened?

I have two miners. One miner has 36MH/s, another has 74MH/s.  The node is running on the first miner server. When the second miner is connected to the same node, the jobs of Workers on the Status screen didn't change. It looks like it doesn't display the second miner's job.

**Comment by AmberKiso** [comment]
If you can attach a capture of the terminal windows and the commands used to set up the miners+node, that would help the devs.

**Comment by McGillDad** [comment]
#start node
sudo yarn start start --rpc.tcp --rpc.tcp.host=192.168.5.2 --rpc.tcp.port=8001

#start minter, it wil be ran on two different computers
sudo yarn start miners:start --threads=32 --rpc.tcp --rpc.tcp.host=192.168.5.2--rpc.tcp.port=8001

No matter how many miners are connected to the same node, the Workers show the jobs from one miner only.

![Screenshot 2022-01-27 092310](https://user-images.githubusercontent.com/98481538/151377648-be256e39-d280-4b47-a326-1a509066f82d.png)

**Comment by QustomQure** [comment]
workers has nothing to do with miners. they are dispatch node net interaction, blockchain sync etc, transactions, fees.

**Comment by QustomQure** [comment]
you should close this since it is not a bug - it is your lack of knowledge

**Comment by McGillDad** [comment]
Thanks for answer
