### ISSUE TITLE
[Account problem]

### ISSUE THREAD

**Issue by htcwrs** [iron-fish/ironfish#953]
### Description

Hey! As expected, I immediately registered on the site, checked the number of blocks on the leaderboard, almost did not go to the profile. Now I can't log in. I have all the evidence that the server and mail belong to me.

**Comment by AmberKiso** [comment]
Hello,
Try checking the blocks you mined were accepted by the network by using the block explorer tool here: https://explorer.ironfish.network/
Getting credit for blocks also requires a graffiti being set. Points are unfortunately not given retroactively.

You can ask in the Iron Fish discord channel for help. #questions

**Comment by htcwrs** [comment]
I want to regain access to my account

**Comment by AmberKiso** [comment]
I'm just a community contributor. It's best to join the Discord for this project and ask for help there.

**Comment by deekerno** [comment]
As @AmberKiso stated, for this type of problem, it's best to join the Discord and ask an Iron Fish team member for help, if you haven't already done so.
