### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by Alarmod** [iron-fish/ironfish#956]
After using the script from nodes.guru or direct compile from github sources, I must go to the "ironfish-cli" folder and explicitly call "yarn start". Otherwise I can't run command "ironfish miners:start": it run with error 
"(node:23637) [MODULE_NOT_FOUND] Error Plugin: ironfish-cli: Cannot find module '/root/ironfish/ironfish-cli/build/src/hooks/version'"

Reason - "build" directory is not created during compilation.

If I run command "npm install" in "ironfish-cli" folder, I get compile error:
"Not Found - GET https://registry.npmjs.org/eslint-config-ironfish - Not found". 

After "yarn start" (in "ironfish-cli" folder) command "ironfish miners:start" executing without any errors.

**Comment by Alarmod** [comment]
My Graffiti is "alarmod".

**Comment by dguenther** [comment]
This is expected. The instructions for starting the CLI from source already mention that you need to go to the `ironfish-cli` directory and run `yarn start` or `yarn start:once`. They're linked from the main README here: https://github.com/iron-fish/ironfish#usage which links to https://github.com/iron-fish/ironfish/tree/master/ironfish-cli
