### ISSUE TITLE
Several errors after update

### ISSUE THREAD

**Issue by QustomQure** [iron-fish/ironfish#958]
### What happened?

After update trying to run node getting error messages. Win 10, building from source.
Graffiti: Qualia

### Version

0.1.21

### Relevant log output

```shell
13:23:52 - Starting compilation in watch mode...

src/commands/start.ts(208,28): error TS2345: Argument of type '"telemetryNodeId"' is not assignable to parameter of type 'keyof InternalOptions'.
src/commands/start.ts(209,25): error TS2345: Argument of type '"telemetryNodeId"' is not assignable to parameter of type 'keyof InternalOptions'.
src/commands/start.ts(256,23): error TS2345: Argument of type '"telemetryNodeId"' is not assignable to parameter of type 'keyof InternalOptions'.
src/commands/testnet.ts(74,28): error TS2339: Property 'getUser' does not exist on type 'WebApi'.

13:23:53 - Found 4 errors. Watching for file changes.
```

**Comment by QustomQure** [comment]
PS C:\Users\fr0ze\ironfish-master\ironfish-cli> yarn build
yarn run v1.22.15
$ tsc -b
src/commands/start.ts:208:28 - error TS2345: Argument of type '"telemetryNodeId"' is not assignable to parameter of type 'keyof InternalOptions'.

208     if (!node.internal.get('telemetryNodeId')) {
                               ~~~~~~~~~~~~~~~~~

src/commands/start.ts:209:25 - error TS2345: Argument of type '"telemetryNodeId"' is not assignable to parameter of type 'keyof InternalOptions'.

209       node.internal.set('telemetryNodeId', uuid())
                            ~~~~~~~~~~~~~~~~~

src/commands/start.ts:256:23 - error TS2345: Argument of type '"telemetryNodeId"' is not assignable to parameter of type 'keyof InternalOptions'.

256     node.internal.set('telemetryNodeId', uuid())
                          ~~~~~~~~~~~~~~~~~

src/commands/testnet.ts:74:28 - error TS2339: Property 'getUser' does not exist on type 'WebApi'.

74     const user = await api.getUser(userId)
                              ~~~~~~~

**Comment by deekerno** [comment]
This user's issue was fixed in a ticket on Discord. For posterity's sake, the modules needed to be rebuilt after pulling down the latest changes.
