### ISSUE TITLE
my blocks without specifying graffiti

### ISSUE THREAD

**Issue by fomoiks** [iron-fish/ironfish#959]
### Description

hi, in the first week of mining, an update came out and after the update I didn’t install graffiti, I clicked update, then somehow deleted my graffiti, at first I didn’t understand it well, as a result I mined 5 blocks without specifying graffiti, these are my blocks 100%, I wrote to James in discord , he said he would not assign these blocks to me. But I ask you to assign them to me, I deserve them, I mined them. It’s difficult to grow a lot now, it’s difficult to mine, and it’s a shame to lose these 5 blocks, the servers are expensive...

blocks  

0000001bf9ca1f63668696cb651a31753bd30406d38b4ba11868f3ebda3fcc2f 
0000000f26b1429a6fbe7113ffa1b80e9aa9df92aa46ae22311b2d2889373e39 
0000001480ef9c4e65c46b58bc3e762e8e055ddfcd9b7178024f5945d928c7a8 
00000003043755f71cd9f0ef52678acc550ceaf2924aa18749d5b51a9f99ad33 
0000000a608c331e883fafe7825705d5148087f1ef7ecc48187c6709bac80e0e 

my graffiti - forexer2566

**Comment by QustomQure** [comment]
https://testnet.ironfish.network/about

**Comment by leanthebean** [comment]
We can't modify blocks (since blockchains are immutable) to add your graffiti, but I can award you points just this one time for submitting a bug. Please make sure you have your graffiti set going forward!

**Comment by fomoiks** [comment]
Thank you. Yes, my graffiti - forexer2566

how many points will you give me?

В Ср, февр. 9, 2022 в 00:57, Elena Nadolinski ***@***.***> пишет:
