### ISSUE TITLE
Cannot run ironfish when built on M1 - incompatible architecture for index.node

### ISSUE THREAD

**Issue by jrwashburn** [iron-fish/ironfish#962]
I tried the below as noted in issue #9, and got a successful build from yarn install. But yarn test fails (as does trying to run ironfish-cli as via yarn start ...) with several dlopen errors complaining about the architecture.

"Just as an update, Homebrew is not yet supported, but you should be able to build and run a node from source on M1 machines by following the instructions in the README."

_Originally posted by @dguenther in https://github.com/iron-fish/ironfish/issues/9#issuecomment-983205820_

The runtime errors are all:
mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'

```
dlopen(/Users/jrwashburn/ironfish/ironfish-rust-nodejs/index.node, 0x0001): tried: '/Users/jrwashburn/ironfish/ironfish-rust-nodejs/index.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/index.node' (no such file), '/usr/lib/index.node' (no such file)
```

**Comment by dguenther** [comment]
The error you posted seems to indicate that the build you did didn't actually target arm64/M1. This is probably a configuration issue with your build machine -- I'm able to build on a fresh M1 machine and run the CLI. When you run `arch` in your terminal, do you see `arm64`?

**Comment by jrwashburn** [comment]
yes 
```
~ % arch
arm64
```

**Comment by dguenther** [comment]
What does `rustup show` display?

**Comment by jrwashburn** [comment]
~ % rustup show
Default host: x86_64-apple-darwin
rustup home:  /Users/jrwashburn/.rustup

installed toolchains
--------------------

stable-x86_64-apple-darwin (default)
1.52.1-x86_64-apple-darwin

active toolchain
----------------

stable-x86_64-apple-darwin (default)
rustc 1.58.1 (db9d1b20b 2022-01-20)

**Comment by dguenther** [comment]
Aha, I bet that's it! Try running `rustup set default-host aarch64-apple-darwin` followed by `rustup show` again, and if it shows aarch64, then you could try deleting `ironfish-rust-nodejs/index.node` and re-running the build from `yarn install`.

I've seen a few other people with a similar configuration issue -- I imagine it has something to do with how Rust is set up, but I'm not sure what.

**Comment by jrwashburn** [comment]
Pebkac - or at least environmental. I just reinstalled rust (did that before I saw your response, but I'm a little uncomfortable with my environment now -- not sure why it was like that -- so happy to reinstall.) I was able to rebuild without a problem, and yarn test is successful. Sorry for opening the issue and thanks for tech support.

**Comment by dguenther** [comment]
Great, glad it's working!
