### ISSUE TITLE
Problem with not registered graffiti

### ISSUE THREAD

**Issue by Issavon** [iron-fish/ironfish#963]
### Description

Hi IronFish Team!
I started mining in testnet and set in node graffiti "issavon" but I didn't know that the graffiti name must set to the testnet username.
I already mined 16 blocks before im tried register graffiti in testnet
After 2 months I registered an account in testnet with my graffiti, but the previously mined blocks are not displayed (and rewards also).
Please help me get my points. I created this issue and fill claim form by Elena's advice
My node and miner ip - 88.99.166.120
Graffiti - issavon
Email - streetday148@gmail.com
Wallet id - 154bdabd4bc61c2ef083dde27e0849586cf7063c8f3f46c5df669b750b73092de84e704d37e86821807602
If need i can provide more proof information (private keys, ip ping and more)
Thank you, Team!

**Comment by pantsarny** [comment]
Yes, my friend got same problem.
Maybe it's worth accruing points in this case?

**Comment by leanthebean** [comment]
We are doing a full re-sync of our leaderboard on 2/14/22 (Feb 14) at 12 PM EST (5 PM UTC). The re-sync will take some time (no more than a few hours). After the re-sync all blocks marked with your graffiti will count for points. 

See the Discord announcement for more details: https://discord.com/channels/771503434028941353/816795744680935445/940338404669947955
