### ISSUE TITLE
Missing mined blocks or node Status counted wrong?

### ISSUE THREAD

**Issue by McGillDad** [iron-fish/ironfish#968]
### What happened?

I got 4 mined showed in my node Status, but only 3 blocks are shown in testnet leaderboard. 

![image](https://user-images.githubusercontent.com/98481538/152916039-b602a179-fc46-4528-9283-f7abe839f809.png)

Please look at block "103415 - 00000000000972F88A5A7A2513AB7B3354F3A1BA484CBEE7AA1BECEF28FE0321", it has two Transactions, -2000000001 $ORE and 1 $ORE. I think the block is counted twice in node Status by Transaction. Is it a bug?
Why does it have 2 Transactions here? My other blocks have 1 Transaction each.

### Version

0.1.21

**Comment by McGillDad** [comment]
Please look at block "103415 - 00000000000972F88A5A7A2513AB7B3354F3A1BA484CBEE7AA1BECEF28FE0321", it has two Transactions. I think it counts 2 mined in node Status.

**Comment by Kupuyc** [comment]
@McGillDad It most probably some of them were forked. You may check it by `ironfish miners:mined 90000` (90000 is start height to speed up search). All blocks in list are in main net. It will be exact number of mined blocks. Number in status output still doesn't filter forks.

**Comment by leanthebean** [comment]
@Kupuyc is right here, it's most likely on a fork. Blocks can certainly have more than 1 transaction also. Closing this for now.
