### ISSUE TITLE
Points in the leaderboard are not displayed correctly

### ISSUE THREAD

**Issue by alar0n** [iron-fish/ironfish#971]
### Description

On example user:
https://testnet.ironfish.network/users/4373
![image](https://user-images.githubusercontent.com/31000576/153135937-04628f7e-0902-4587-b088-2a1f966825f0.png)
now date 09.02.2022 how he can mined 7 block on this week if i scroll down and seen:
![image](https://user-images.githubusercontent.com/31000576/153136041-9e61661b-9342-4e01-9d25-ee4c768e96ff.png)

Maybe exist more users with this bug, but I couldn't find them

**Comment by alar0n** [comment]
It seems that this page does not display statistics for the current week.
Can be closed.

**Comment by leanthebean** [comment]
It is indeed a bug that is being worked on already in the website-testnet repo (https://github.com/iron-fish/website-testnet/pull/179)

**Comment by alar0n** [comment]
Ok. Thanks for your answer!
