### ISSUE TITLE
"ironfish miners:mined" displaying wrong graffiti when multiple graffiti exists

### ISSUE THREAD

**Issue by McGillDad** [iron-fish/ironfish#973]
### What happened?

I have two graffiti used when mining. One is my main graffiti, the first letter is M; another one is for testing, the first letter is L. 
I mine with M normally. I tested "ironfish testnet" to switch to L and mined, then run "ironfish testnet" again to switch back to M.
When running "ironfish miners:mined 90000" in ubuntu, it displayed the test graffiti L mined the blocks. This is wrong, it is M mined those blocks. 

### Version

0.1.21

**Comment by lwisne** [comment]
We believe this is now fixed. Let us know if you don't agree!
