### ISSUE TITLE
Error in chain export

### ISSUE THREAD

**Issue by aditya-manit** [iron-fish/ironfish#997]
### What happened?

I ran
```
ironfish chain:export
```
It showed me the output
```
Exporting chain from 1 -> 40987 to /usr/src/ironfish-graph-explorer/src/data.json
Exporting blocks: [========================================] 40987/40987 100% | ETA: 0s
    Error: ENOENT: no such file or directory, open '/usr/src/ironfish-graph-explorer/src/data.json'
    Code: ENOENT
```

### Version

ironfish-cli/0.1.21 linux-x64 node-v16.13.0

**Comment by aditya-manit** [comment]
Got it, so I guess the default position needs to be fixed ?

From what I can see the only thing there is in `/usr/src/` is app and there is no `ironfish-graph-explorer`

**Comment by deekerno** [comment]
This should be fixed as a result of #1035.

**Comment by aditya-manit** [comment]
hey @deekerno  I never received any testnet credits for this PR

**Comment by aditya-manit** [comment]
Bumping this up
