### ISSUE TITLE
How to run chain:repair command ?

### ISSUE THREAD

**Issue by aditya-manit** [iron-fish/ironfish#998]
### What happened?

I ran
```
ironfish chain:repair
```
It showed me the output
```
Opening node... !
    Error: IO error: lock /root/.ironfish/databases/default/LOCK: Resource temporarily unavailable
```
I think it's because node is running. How can I run this command within the container without running the node ?

### Version

ironfish-cli/0.1.21 linux-x64 node-v16.13.0

**Comment by lwisne** [comment]
We believe this is resolved. Let us know if this is not the case!

**Comment by aditya-manit** [comment]
Hey @lwisne I never received any testnet credits for this issue
